using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ElementsAwoken.Buffs
{
	internal class ElementsAwokenBuffs
	{
		public static void Setup()
		{
			Buffs();
		}
		private static void Buffs()
		{
			Mod elementsAwoken = ModLoader.GetMod("ElementsAwoken");
			
			elementsAwoken.GetBuff("AwokenHealing").DisplayName.AddTranslation(GameCulture.Russian, "Пробуждённая регенерация");
			elementsAwoken.GetBuff("AwokenHealing").Description.AddTranslation(GameCulture.Russian, "Ваше здоровье быстро восстанавливается");
			elementsAwoken.GetBuff("Bloodbath").DisplayName.AddTranslation(GameCulture.Russian, "Кровавая баня");
			elementsAwoken.GetBuff("Bloodbath").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 20");
			elementsAwoken.GetBuff("ChaosShield").DisplayName.AddTranslation(GameCulture.Russian, "Щит хаоса");
			elementsAwoken.GetBuff("ElementalArmorCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Элементального оживления");
			elementsAwoken.GetBuff("ElementalArmorCooldown").Description.AddTranslation(GameCulture.Russian, "Ваше оживление перезаряжается");
			elementsAwoken.GetBuff("ExtinctionCurseImbue").DisplayName.AddTranslation(GameCulture.Russian, "Флакон с проклятьем вымирания");
			elementsAwoken.GetBuff("ExtinctionCurseImbue").Description.AddTranslation(GameCulture.Russian, "При ударе накладывает «Проклятье вымирания»");
			elementsAwoken.GetBuff("FrostShield").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной щит");
			elementsAwoken.GetBuff("Glowing").DisplayName.AddTranslation(GameCulture.Russian, "Свечение");
			elementsAwoken.GetBuff("Glowing").Description.AddTranslation(GameCulture.Russian, "Вы испускаете ослепляющий свет\nКаждый монстр видит вас");
			elementsAwoken.GetBuff("GoldenWeapons").DisplayName.AddTranslation(GameCulture.Russian, "Золотое оружие");
			elementsAwoken.GetBuff("GoldenWeapons").Description.AddTranslation(GameCulture.Russian, "Ваш урон увеличен на 10%");
			elementsAwoken.GetBuff("Invincibility").DisplayName.AddTranslation(GameCulture.Russian, "Неуязвимость");
			elementsAwoken.GetBuff("Invincibility").Description.AddTranslation(GameCulture.Russian, "Вам не могут нанести урон");
			elementsAwoken.GetBuff("NeovirtuoCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Неовиртуо");
			elementsAwoken.GetBuff("NeovirtuoCooldown").Description.AddTranslation(GameCulture.Russian, "Ваш Неовиртуо перезаряжается");
			elementsAwoken.GetBuff("PsychologistSanity").DisplayName.AddTranslation(GameCulture.Russian, "Консультация");
			elementsAwoken.GetBuff("PsychologistSanity").Description.AddTranslation(GameCulture.Russian, "Восстановление здравомыслия происходит быстрее");
			elementsAwoken.GetBuff("StrongHeart").DisplayName.AddTranslation(GameCulture.Russian, "Крепкое сердце");
			elementsAwoken.GetBuff("StrongHeart").Description.AddTranslation(GameCulture.Russian, "Ваш максимальный запас здоровья увеличен на 10%");
			elementsAwoken.GetBuff("SuperSpeed").DisplayName.AddTranslation(GameCulture.Russian, "Супер скорость");
			elementsAwoken.GetBuff("SuperSpeed").Description.AddTranslation(GameCulture.Russian, "Вы двигаетесь на неконтролируемых скоростях");
			elementsAwoken.GetBuff("VilePower").DisplayName.AddTranslation(GameCulture.Russian, "Гнусная сила");
			elementsAwoken.GetBuff("VilePower").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 5%\nАтаки накладывают «Отравление» и «Яд»");
			elementsAwoken.GetBuff("WindsBlessing").DisplayName.AddTranslation(GameCulture.Russian, "Благословение ветров");
			elementsAwoken.GetBuff("WindsBlessing").Description.AddTranslation(GameCulture.Russian, "'Ветра, направляйте меня!'");
			elementsAwoken.GetBuff("ArchaicProtectionCD").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Архаичной защиты");
			elementsAwoken.GetBuff("ArchaicProtectionCD").Description.AddTranslation(GameCulture.Russian, "Вы не можете заключить себя в кристаллы");
			elementsAwoken.GetBuff("AstralTearCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Астрального разрыва");
			elementsAwoken.GetBuff("AstralTearCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Астральный разрыв");
			elementsAwoken.GetBuff("BoostDriveCD").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Ускоряющего привода");
			elementsAwoken.GetBuff("BoostDriveCD").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Ускоряющий привод");
			elementsAwoken.GetBuff("BrokenToyBlade").DisplayName.AddTranslation(GameCulture.Russian, "Сломанный игрушечный меч");
			elementsAwoken.GetBuff("BrokenToyBlade").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Игрушечный меч");
			elementsAwoken.GetBuff("ChaosShieldCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Щита хаоса");
			elementsAwoken.GetBuff("ChaosShieldCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете создать Щит хаоса");
			elementsAwoken.GetBuff("CrystallineLocketCD").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Кристального медальона");
			elementsAwoken.GetBuff("CrystallineLocketCD").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Кристальный медальон");
			elementsAwoken.GetBuff("DashCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка рывка ниндзя");
			elementsAwoken.GetBuff("DashCooldown").Description.AddTranslation(GameCulture.Russian, "Ваш рывок перезаряжается");
			elementsAwoken.GetBuff("DeathwarpCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Деформирующей смерти");
			elementsAwoken.GetBuff("DeathwarpCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете активировать Деформирующую смерть");
			elementsAwoken.GetBuff("GreatLensCD").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Великой линзы");
			elementsAwoken.GetBuff("GreatLensCD").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Великую линзу");
			elementsAwoken.GetBuff("HoneyCocoonCD").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Медового кокона");
			elementsAwoken.GetBuff("HoneyCocoonCD").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Медовый кокон");
			elementsAwoken.GetBuff("InfinityBubbleCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка пузырей-снарядов");
			elementsAwoken.GetBuff("InfinityBubbleCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете превратить снаряды в пузыри");
			elementsAwoken.GetBuff("InfinityPortalCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка портала");
			elementsAwoken.GetBuff("InfinityPortalCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете создать портал");
			elementsAwoken.GetBuff("InfinityVoidCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка пустоты");
			elementsAwoken.GetBuff("InfinityVoidCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете стереть жизнь... пока что");
			elementsAwoken.GetBuff("SolusKunaiCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Солнечных кунаев");
			elementsAwoken.GetBuff("SolusKunaiCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Солнечные кунаи");
			elementsAwoken.GetBuff("AcidBurn").DisplayName.AddTranslation(GameCulture.Russian, "Химический ожог");
			elementsAwoken.GetBuff("AcidBurn").Description.AddTranslation(GameCulture.Russian, "Ощущается как жидкий металл");
			elementsAwoken.GetBuff("AncientDecay").DisplayName.AddTranslation(GameCulture.Russian, "Древнее разложение");
			elementsAwoken.GetBuff("AncientDecay").Description.AddTranslation(GameCulture.Russian, "Ваша душа разрушается");
			elementsAwoken.GetBuff("AncientsCurse").DisplayName.AddTranslation(GameCulture.Russian, "Проклятье древних");
			elementsAwoken.GetBuff("BehemothGaze").DisplayName.AddTranslation(GameCulture.Russian, "Взор на чудище");
			elementsAwoken.GetBuff("BehemothGaze").Description.AddTranslation(GameCulture.Russian, "Пристальный взгляд на существо не даёт вам уйти");
			elementsAwoken.GetBuff("BurningHands").DisplayName.AddTranslation(GameCulture.Russian, "Горящие руки");
			elementsAwoken.GetBuff("BurningHands").Description.AddTranslation(GameCulture.Russian, "Вы держите горячее оружие");
			elementsAwoken.GetBuff("ChaosBurn").DisplayName.AddTranslation(GameCulture.Russian, "Хаотичный некроз");
			elementsAwoken.GetBuff("ChaosBurn").Description.AddTranslation(GameCulture.Russian, "Ваши клетки разрываются в клочья");
			elementsAwoken.GetBuff("Corroding").DisplayName.AddTranslation(GameCulture.Russian, "Разъедание");
			elementsAwoken.GetBuff("Corroding").Description.AddTranslation(GameCulture.Russian, "Ощущается как жидкий огонь");
			elementsAwoken.GetBuff("Cuddled").DisplayName.AddTranslation(GameCulture.Russian, "Дуновение");
			elementsAwoken.GetBuff("Cuddled").Description.AddTranslation(GameCulture.Russian, "Вы чувствуете тепло внутри\nУрон ближнего боя снижен на 20%\nНо увеличена скорость регенерации здоровья");
			elementsAwoken.GetBuff("DeterioratingWings").DisplayName.AddTranslation(GameCulture.Russian, "Испорченные крылья");
			elementsAwoken.GetBuff("DeterioratingWings").Description.AddTranslation(GameCulture.Russian, "Ваши крылья крошатся в чёрную пыль");
			elementsAwoken.GetBuff("Discord").DisplayName.AddTranslation(GameCulture.Russian, "Раздор");
			elementsAwoken.GetBuff("Discord").Description.AddTranslation(GameCulture.Russian, "Всё тело болит...");
			elementsAwoken.GetBuff("Dragonfire").DisplayName.AddTranslation(GameCulture.Russian, "Драконий огонь");
			elementsAwoken.GetBuff("Dragonfire").Description.AddTranslation(GameCulture.Russian, "Ваша кожа сгорает");
			elementsAwoken.GetBuff("EldritchHorror").DisplayName.AddTranslation(GameCulture.Russian, "Древний ужас");
			elementsAwoken.GetBuff("EldritchHorror").Description.AddTranslation(GameCulture.Russian, "Ваш разум не может постичь его силы...\nЗдравомыслие истощается");
			elementsAwoken.GetBuff("ElectrifiedNPC").DisplayName.AddTranslation(GameCulture.Russian, "Электризованный");
			elementsAwoken.GetBuff("EndlessTears").DisplayName.AddTranslation(GameCulture.Russian, "Бесконечные слезы");
			elementsAwoken.GetBuff("EndlessTears").Description.AddTranslation(GameCulture.Russian, "Вас сбивает грусть...");
			elementsAwoken.GetBuff("ExtinctionCurse").DisplayName.AddTranslation(GameCulture.Russian, "Проклятье вымирания");
			elementsAwoken.GetBuff("ExtinctionCurse").Description.AddTranslation(GameCulture.Russian, "Силы бездны тянут вас глубже...");
			elementsAwoken.GetBuff("FastPoison").DisplayName.AddTranslation(GameCulture.Russian, "Тяжёлый яд");
			elementsAwoken.GetBuff("FastPoison").Description.AddTranslation(GameCulture.Russian, "Ваше здоровье быстро ухудшается");
			elementsAwoken.GetBuff("HandsOfDespair").DisplayName.AddTranslation(GameCulture.Russian, "Руки отчаяния");
			elementsAwoken.GetBuff("HandsOfDespair").Description.AddTranslation(GameCulture.Russian, "Они хватают вас за конечности, сбивая с толку");
			elementsAwoken.GetBuff("IceBound").DisplayName.AddTranslation(GameCulture.Russian, "Скованный льдами");
			elementsAwoken.GetBuff("IceBound").Description.AddTranslation(GameCulture.Russian, "Ваши кости и суставы замораживаются");
			elementsAwoken.GetBuff("ImpishCurse").DisplayName.AddTranslation(GameCulture.Russian, "Проклятье беса");
			elementsAwoken.GetBuff("Irradiated").DisplayName.AddTranslation(GameCulture.Russian, "Облучённый");
			elementsAwoken.GetBuff("Irradiated").Description.AddTranslation(GameCulture.Russian, "Радиация вас убивает");
			elementsAwoken.GetBuff("RottenHeart").DisplayName.AddTranslation(GameCulture.Russian, "Гнилое сердце");
			elementsAwoken.GetBuff("RottenHeart").Description.AddTranslation(GameCulture.Russian, "Ваш максимальный запас здоровья снижен на 10%");
			elementsAwoken.GetBuff("SoulInferno").DisplayName.AddTranslation(GameCulture.Russian, "Инферно душ");
			elementsAwoken.GetBuff("SoulInferno").Description.AddTranslation(GameCulture.Russian, "От вас исходит странное излучение");
			elementsAwoken.GetBuff("Starstruck").DisplayName.AddTranslation(GameCulture.Russian, "Воодушевление");
			elementsAwoken.GetBuff("Starstruck").Description.AddTranslation(GameCulture.Russian, "Ваша воля нависает над вашими врагами\nКаждый удар противника увеличивает получаемый игроком урон");
			elementsAwoken.GetBuff("SuperSlow").DisplayName.AddTranslation(GameCulture.Russian, "Супер медленный");
			elementsAwoken.GetBuff("SuperSlow").Description.AddTranslation(GameCulture.Russian, "Вам тяжело идти");
			elementsAwoken.GetBuff("VariableLifeRegen").DisplayName.AddTranslation(GameCulture.Russian, "Высасывание жизни");
			elementsAwoken.GetBuff("VariableLifeRegen").Description.AddTranslation(GameCulture.Russian, "Из вас вытягивают жизнь");
			elementsAwoken.GetBuff("AbyssCultistBuff").DisplayName.AddTranslation(GameCulture.Russian, "Культист бездны");
			elementsAwoken.GetBuff("AbyssCultistBuff").Description.AddTranslation(GameCulture.Russian, "Да здравствует тьма...");
			elementsAwoken.GetBuff("AqueousMinions").DisplayName.AddTranslation(GameCulture.Russian, "Прислужники Аквауса");
			elementsAwoken.GetBuff("AqueousMinions").Description.AddTranslation(GameCulture.Russian, "Миньоны Аквауса защищают вас");
			elementsAwoken.GetBuff("AwakenedMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пробуждение");
			elementsAwoken.GetBuff("AwakenedMinionBuff").Description.AddTranslation(GameCulture.Russian, "Они пробудились");
			elementsAwoken.GetBuff("AzanaMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Азана");
			elementsAwoken.GetBuff("AzanaMinionBuff").Description.AddTranslation(GameCulture.Russian, "От неё исходит энергия хаоса");
			elementsAwoken.GetBuff("BabyPuffBuff").DisplayName.AddTranslation(GameCulture.Russian, "Малыш пушистик!");
			elementsAwoken.GetBuff("BabyPuffBuff").Description.AddTranslation(GameCulture.Russian, "Этот милый пушистик защитит вас!");
			elementsAwoken.GetBuff("BubbleBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пузырь");
			elementsAwoken.GetBuff("BubbleBuff").Description.AddTranslation(GameCulture.Russian, "Я люблю пузыри!");
			elementsAwoken.GetBuff("CoalescedOrbBuff").DisplayName.AddTranslation(GameCulture.Russian, "Слившаяся сфера");
			elementsAwoken.GetBuff("CoalescedOrbBuff").Description.AddTranslation(GameCulture.Russian, "Материя воссоединилась, чтобы создать один пристальный глаз");
			elementsAwoken.GetBuff("CorroderBuff").DisplayName.AddTranslation(GameCulture.Russian, "Разъедальщик");
			elementsAwoken.GetBuff("CorroderBuff").Description.AddTranslation(GameCulture.Russian, "Не пытайтесь подружится с ним");
			elementsAwoken.GetBuff("CorruptPenguinBuff").DisplayName.AddTranslation(GameCulture.Russian, "Искажённый пингвин");
			elementsAwoken.GetBuff("CorruptPenguinBuff").Description.AddTranslation(GameCulture.Russian, "Наносит дополнительный урон портному");
			elementsAwoken.GetBuff("CosmicObserverBuff").DisplayName.AddTranslation(GameCulture.Russian, "Космический наблюдатель");
			elementsAwoken.GetBuff("CosmicObserverBuff").Description.AddTranslation(GameCulture.Russian, "Его края невероятно острые");
			elementsAwoken.GetBuff("CrystallineEntityBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кристальное существо");
			elementsAwoken.GetBuff("CrystallineEntityBuff").Description.AddTranslation(GameCulture.Russian, "Слабый гул исходит из кристалла");
			elementsAwoken.GetBuff("DeathwatcherBuff").DisplayName.AddTranslation(GameCulture.Russian, "Могильщик");
			elementsAwoken.GetBuff("DeathwatcherBuff").Description.AddTranslation(GameCulture.Russian, "У вас мурашки от одного взора на него");
			elementsAwoken.GetBuff("EnchantedTrio").DisplayName.AddTranslation(GameCulture.Russian, "Зачарованная троица");
			elementsAwoken.GetBuff("EnchantedTrio").Description.AddTranslation(GameCulture.Russian, "Зачарованные оружия Террарии защищают вас!");
			elementsAwoken.GetBuff("EnergySpiritBuff").DisplayName.AddTranslation(GameCulture.Russian, "Дух энергии");
			elementsAwoken.GetBuff("EnergySpiritBuff").Description.AddTranslation(GameCulture.Russian, "Слишком ярок, чтобы смотреть на него прямо");
			elementsAwoken.GetBuff("Eyeball").DisplayName.AddTranslation(GameCulture.Russian, "Глазное яблоко");
			elementsAwoken.GetBuff("Eyeball").Description.AddTranslation(GameCulture.Russian, "Небесные миньоны следуют за вами");
			elementsAwoken.GetBuff("FireElementalBuff").DisplayName.AddTranslation(GameCulture.Russian, "Дух огня");
			elementsAwoken.GetBuff("FireElementalBuff").Description.AddTranslation(GameCulture.Russian, "Он сохранит вас в тепле в холодную ночь");
			elementsAwoken.GetBuff("GlobuleMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Глобула звездного света");
			elementsAwoken.GetBuff("GlobuleMinionBuff").Description.AddTranslation(GameCulture.Russian, "Она блестит");
			elementsAwoken.GetBuff("HappyCloudBuff").DisplayName.AddTranslation(GameCulture.Russian, "Счастливое маленькое облако");
			elementsAwoken.GetBuff("HappyCloudBuff").Description.AddTranslation(GameCulture.Russian, "Боб Росс");
			elementsAwoken.GetBuff("HearthMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сердце");
			elementsAwoken.GetBuff("HearthMinionBuff").Description.AddTranslation(GameCulture.Russian, "Оно излучает приятное тепло");
			elementsAwoken.GetBuff("IceAxeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной топор");
			elementsAwoken.GetBuff("IceAxeBuff").Description.AddTranslation(GameCulture.Russian, "Он режет всё на своём пути");
			elementsAwoken.GetBuff("IcicleBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сосулька");
			elementsAwoken.GetBuff("IcicleBuff").Description.AddTranslation(GameCulture.Russian, "Никогда не расплавится");
			elementsAwoken.GetBuff("InfectionMouthBuff").DisplayName.AddTranslation(GameCulture.Russian, "Зараженные уста");
			elementsAwoken.GetBuff("InfectionMouthBuff").Description.AddTranslation(GameCulture.Russian, "Не вдыхайте частицы");
			elementsAwoken.GetBuff("KirovAirshipBuff").DisplayName.AddTranslation(GameCulture.Russian, "Киров дирижабль");
			elementsAwoken.GetBuff("KirovAirshipBuff").Description.AddTranslation(GameCulture.Russian, "Бомбардировщиков на ваше местоположение");
			elementsAwoken.GetBuff("MiniDragonBuff").DisplayName.AddTranslation(GameCulture.Russian, "Миниатюрный дракон");
			elementsAwoken.GetBuff("MiniDragonBuff").Description.AddTranslation(GameCulture.Russian, "Он мил и страшен одновременно");
			elementsAwoken.GetBuff("MiniSandstormBuff").DisplayName.AddTranslation(GameCulture.Russian, "Миниатюрная песчаная буря");
			elementsAwoken.GetBuff("MiniSandstormBuff").Description.AddTranslation(GameCulture.Russian, "Это странное существо защитит вас");
			elementsAwoken.GetBuff("MiniVleviBuff").DisplayName.AddTranslation(GameCulture.Russian, "Миниатюрный пустотный левиафан");
			elementsAwoken.GetBuff("MiniVleviBuff").Description.AddTranslation(GameCulture.Russian, "Этот пустотный левиафан защитит вас");
			elementsAwoken.GetBuff("PhantomHookBuff").DisplayName.AddTranslation(GameCulture.Russian, "Крюк фантома");
			elementsAwoken.GetBuff("PhantomHookBuff").Description.AddTranslation(GameCulture.Russian, "Не попадитесь под перекрёстный огонь");
			elementsAwoken.GetBuff("PutridRipperBuff").DisplayName.AddTranslation(GameCulture.Russian, "Мерзкий убийца");
			elementsAwoken.GetBuff("PutridRipperBuff").Description.AddTranslation(GameCulture.Russian, "Лапы как ножи, плевок как кислота");
			elementsAwoken.GetBuff("ScorpionMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Скорпион");
			elementsAwoken.GetBuff("ScorpionMinionBuff").Description.AddTranslation(GameCulture.Russian, "Снип снап");
			elementsAwoken.GetBuff("SoulSkull").DisplayName.AddTranslation(GameCulture.Russian, "Душа-череп");
			elementsAwoken.GetBuff("SoulSkull").Description.AddTranslation(GameCulture.Russian, "Пробуждённый из пустоты, череп выдыхает «Огонь душ», который накладывает «Инферно душ»");
			elementsAwoken.GetBuff("ToyRobotBuff").DisplayName.AddTranslation(GameCulture.Russian, "Робот-игрушка");
			elementsAwoken.GetBuff("ToyRobotBuff").Description.AddTranslation(GameCulture.Russian, "Он сам заводится!");
			elementsAwoken.GetBuff("VolcanicTentacleBuff").DisplayName.AddTranslation(GameCulture.Russian, "Вулканическое щупальце");
			elementsAwoken.GetBuff("VolcanicTentacleBuff").Description.AddTranslation(GameCulture.Russian, "Оно цепляется за вас");
			elementsAwoken.GetBuff("CrowBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ворона");
			elementsAwoken.GetBuff("CrowBuff").Description.AddTranslation(GameCulture.Russian, "Грациозно парит сквозь небеса");
			elementsAwoken.GetBuff("ElementalDragonBunnyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Элементальный драко-кролик");
			elementsAwoken.GetBuff("ElementalDragonBunnyBuff").Description.AddTranslation(GameCulture.Russian, "Он радостно прыгает вокруг вас");
			elementsAwoken.GetBuff("CalamityBannerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Знамя бедствия");
			elementsAwoken.GetBuff("CalamityBannerBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 7.5 раза");
			elementsAwoken.GetBuff("ChaosBannerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Знамя хаоса");
			elementsAwoken.GetBuff("ChaosBannerBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 5 раз");
			elementsAwoken.GetBuff("DeletionMark").DisplayName.AddTranslation(GameCulture.Russian, "Будет отключён");
			elementsAwoken.GetBuff("FlareShield").DisplayName.AddTranslation(GameCulture.Russian, "Щит вспышки");
			elementsAwoken.GetBuff("FlareShieldCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка Драконьего защитника");
			elementsAwoken.GetBuff("FlareShieldCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать Драконий защитник");
			elementsAwoken.GetBuff("HavocBannerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Знамя опустошения");
			elementsAwoken.GetBuff("HavocBannerBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 2 раза");
			elementsAwoken.GetBuff("AncientStellateBuff").DisplayName.AddTranslation(GameCulture.Russian, "Древняя звезда");
			elementsAwoken.GetBuff("AncientStellateBuff").Description.AddTranslation(GameCulture.Russian, "Она ярко блестит");
			elementsAwoken.GetBuff("AwakenedBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пробуждённый");
			elementsAwoken.GetBuff("AwakenedBuff").Description.AddTranslation(GameCulture.Russian, "Оно пробудилось");
			elementsAwoken.GetBuff("BabyShadeWyrmBuff").DisplayName.AddTranslation(GameCulture.Russian, "Теневой червь-малыш");
			elementsAwoken.GetBuff("BabyShadeWyrmBuff").Description.AddTranslation(GameCulture.Russian, "В отличии от обычных теневых червей он не пытается затянуть вас в огромную, бесконечную пустоту");
			elementsAwoken.GetBuff("CelestialWatcherBuff").DisplayName.AddTranslation(GameCulture.Russian, "Павший звездочёт");
			elementsAwoken.GetBuff("CelestialWatcherBuff").Description.AddTranslation(GameCulture.Russian, "Павший звездочёт следит за вами");
			elementsAwoken.GetBuff("ChamchamRatBuff").DisplayName.AddTranslation(GameCulture.Russian, "Мышь Чамчам");
			elementsAwoken.GetBuff("LilOrange").DisplayName.AddTranslation(GameCulture.Russian, "Мелкий апельсин");
			elementsAwoken.GetBuff("LilOrange").Description.AddTranslation(GameCulture.Russian, "Маленький апельсин не отходит от вас");
			elementsAwoken.GetBuff("PossessedHandBuff").DisplayName.AddTranslation(GameCulture.Russian, "Одержимая рука");
			elementsAwoken.GetBuff("PossessedHandBuff").Description.AddTranslation(GameCulture.Russian, "От неё сбежало даже собственное тело");
			elementsAwoken.GetBuff("TurboDogeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Турбо Доге");
			elementsAwoken.GetBuff("TurboDogeBuff").Description.AddTranslation(GameCulture.Russian, "Ньйооом");
			elementsAwoken.GetBuff("VoidCrawler").DisplayName.AddTranslation(GameCulture.Russian, "Пустотный ползун");
			elementsAwoken.GetBuff("VoidCrawler").Description.AddTranslation(GameCulture.Russian, "Не порежьтесь клинками, когда он прижимается к вам");
			elementsAwoken.GetBuff("WyvernPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Виверна");
			elementsAwoken.GetBuff("WyvernPetBuff").Description.AddTranslation(GameCulture.Russian, "Играючи, он проносится со свистом вокруг вас");
			elementsAwoken.GetBuff("BandageBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лечение");
			elementsAwoken.GetBuff("BandageBuff").Description.AddTranslation(GameCulture.Russian, "Восстанавливает 75 здоровья за 10 секунд");
			elementsAwoken.GetBuff("BullseyeBuff").DisplayName.AddTranslation(GameCulture.Russian, "В яблочко!");
			elementsAwoken.GetBuff("BullseyeBuff").Description.AddTranslation(GameCulture.Russian, "Шанс критического удара увеличен на 15%\nСтрелковый урон увеличен на 25%");
			elementsAwoken.GetBuff("CalamityPotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Бедствие");
			elementsAwoken.GetBuff("CalamityPotionBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 10 раз");
			elementsAwoken.GetBuff("ChaosPotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Хаос");
			elementsAwoken.GetBuff("ChaosPotionBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 7.5 раза");
			elementsAwoken.GetBuff("DemonSkinBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кожа демона");
			elementsAwoken.GetBuff("DemonSkinBuff").Description.AddTranslation(GameCulture.Russian, "Защита увеличена на 3, скорость передвижения и ближнего урона увеличены на 10%");
			elementsAwoken.GetBuff("DiscordantBuff").DisplayName.AddTranslation(GameCulture.Russian, "Раздор");
			elementsAwoken.GetBuff("DiscordantBuff").Description.AddTranslation(GameCulture.Russian, "Вашему телу получается принять раздор");
			elementsAwoken.GetBuff("Energized").DisplayName.AddTranslation(GameCulture.Russian, "Возбужденный");
			elementsAwoken.GetBuff("Energized").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения выше на 50%\nСкорость регенерации здоровья увеличена на 5");
			elementsAwoken.GetBuff("HavocPotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Опустошение");
			elementsAwoken.GetBuff("HavocPotionBuff").Description.AddTranslation(GameCulture.Russian, "Появление монстров увеличено в 4 раза");
			elementsAwoken.GetBuff("HeartyMeal").DisplayName.AddTranslation(GameCulture.Russian, "Обильная трапеза");
			elementsAwoken.GetBuff("HeartyMeal").Description.AddTranslation(GameCulture.Russian, "Восстанавливает 20 здоровья за 10 секунд");
			elementsAwoken.GetBuff("HellFuryBuff").DisplayName.AddTranslation(GameCulture.Russian, "Адский гнев");
			elementsAwoken.GetBuff("HellFuryBuff").Description.AddTranslation(GameCulture.Russian, "Урон повышен 20%, но получаемый игроком урон повышен вдвое");
			elementsAwoken.GetBuff("LuminiteBuff").DisplayName.AddTranslation(GameCulture.Russian, "Небесное усиление");
			elementsAwoken.GetBuff("LuminiteBuff").Description.AddTranslation(GameCulture.Russian, "Дарует силы Лунного лорда\nЗащита повышена на 8, урон повышен на 15%");
			elementsAwoken.GetBuff("MedicineCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка медицины");
			elementsAwoken.GetBuff("MedicineCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать предметы медицины");
			elementsAwoken.GetBuff("NanowrapBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лечение");
			elementsAwoken.GetBuff("NanowrapBuff").Description.AddTranslation(GameCulture.Russian, "Восстанавливает 100 здоровья за 10 секунд");
			elementsAwoken.GetBuff("SalveBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лечение");
			elementsAwoken.GetBuff("SalveBuff").Description.AddTranslation(GameCulture.Russian, "Восстанавливает 50 здоровья за 10 секунд");
			elementsAwoken.GetBuff("SanityRegenerationBuff").DisplayName.AddTranslation(GameCulture.Russian, "Восстановление рассудка");
			elementsAwoken.GetBuff("SanityRegenerationBuff").Description.AddTranslation(GameCulture.Russian, "Повышенная регенерация рассудка");
			elementsAwoken.GetBuff("SilkySerumBuff").DisplayName.AddTranslation(GameCulture.Russian, "Шелковая сыворотка");
			elementsAwoken.GetBuff("SilkySerumBuff").Description.AddTranslation(GameCulture.Russian, "Понижен контактный урон и урон от падения меньше в два раза");
			elementsAwoken.GetBuff("VoidJellyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пустотное желе");
			elementsAwoken.GetBuff("VoidJellyBuff").Description.AddTranslation(GameCulture.Russian, "Урон повышен на 15%");
			elementsAwoken.GetBuff("DarkenedSkies").DisplayName.AddTranslation(GameCulture.Russian, "Потемневшие небеса");
			elementsAwoken.GetBuff("DarkenedSkies").Description.AddTranslation(GameCulture.Russian, "Молнии стреляют с неба\nБури появляются чаще\nПобедите Регарот, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("Hypothermia").DisplayName.AddTranslation(GameCulture.Russian, "Гипотермия");
			elementsAwoken.GetBuff("Hypothermia").Description.AddTranslation(GameCulture.Russian, "Температура стремительно падает\nСкорость передвижения понижена на 5%\nНа вас накладываются случайные ледяные отрицательные эффекты\nЧасто идет град с ливнем\nБудучи в семи блоках от лавы или костра убирает этот эффект\nПобедите Пермафроста, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("InfernacesWrath").DisplayName.AddTranslation(GameCulture.Russian, "Ярость Инфернэйса");
			elementsAwoken.GetBuff("InfernacesWrath").Description.AddTranslation(GameCulture.Russian, "Метеоры падают с неба\nКогда вы попадаете в ад, Защитники Инфернэйс могут атаковать вас\nПобедите Инфернэйс, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("Psychosis").DisplayName.AddTranslation(GameCulture.Russian, "Психоз");
			elementsAwoken.GetBuff("Psychosis").Description.AddTranslation(GameCulture.Russian, "Сила пустоты тянет вас вниз\nЗащита понижена на 10 и на 5% понижено сопротивление урону\nМогут быть галлюцинации\nПобедите пустотного левиафана, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("ScorpionBreakout").DisplayName.AddTranslation(GameCulture.Russian, "Нашествие скорпионов");
			elementsAwoken.GetBuff("ScorpionBreakout").Description.AddTranslation(GameCulture.Russian, "Террария кишит скорпионами\nПобедите Картула, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("StormSurge").DisplayName.AddTranslation(GameCulture.Russian, "Штормовой всплеск");
			elementsAwoken.GetBuff("StormSurge").Description.AddTranslation(GameCulture.Russian, "Водяные торнадо прорастают из земли\nДожди появляются чаще\nПобедите Аквауса, чтобы убрать этот эффект\nВы можете выключить эффект в настройках мода");
			elementsAwoken.GetBuff("StatueBuffAmadis").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие Amadis");
			elementsAwoken.GetBuff("StatueBuffAmadis").Description.AddTranslation(GameCulture.Russian, "Скорость и урон ближнего боя выше на 15%\nЗдоровье понижено на 30%");
			elementsAwoken.GetBuff("StatueBuffBurst").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие Burst");
			elementsAwoken.GetBuff("StatueBuffBurst").Description.AddTranslation(GameCulture.Russian, "Стрелковый урон повышен на 15%\nСкорость передвижения ниже на 15%");
			elementsAwoken.GetBuff("StatueBuffGenihWat").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие Genih Wat");
			elementsAwoken.GetBuff("StatueBuffGenihWat").Description.AddTranslation(GameCulture.Russian, "Магический урон выше на 15%\nСкорость регенерации маны выше на 5\nВраги более агрессивные\nВраги появляются чаще");
			elementsAwoken.GetBuff("StatueBuffOinite").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие Oinite");
			elementsAwoken.GetBuff("StatueBuffOinite").Description.AddTranslation(GameCulture.Russian, "Идеальный баланс, как всё и должно быть\nВремя всех эффектов повышено вдвое");
			elementsAwoken.GetBuff("StatueBuffOrange").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие ThatOneJuicyOrange_");
			elementsAwoken.GetBuff("StatueBuffOrange").Description.AddTranslation(GameCulture.Russian, "Урон повышен на 15%\nПолучаемый игроком урон повышен на 50%\nПериод послезельевой болезни увеличен");
			elementsAwoken.GetBuff("StatueBuffRanipla").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие Ranipla");
			elementsAwoken.GetBuff("StatueBuffRanipla").Description.AddTranslation(GameCulture.Russian, "Даже если это не имеет значения, просто сделай это\nСкорость повышена на 25%\nУрон призывателя повышен на 15%\nВремя полета и высота прыжка снижены на 25%");
		}
	}
}
