using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.TheSpirit.NPCs
{
    internal class TheSpiritNpc
    {
        public static void Setup()
        {
            Npc();
        }

        private static void Npc()
        {
            Mod spirit = ModLoader.GetMod("SpiritMod");
            
            spirit.GetNPC("AcidCrawler").DisplayName.AddTranslation(GameCulture.Russian,"Кислотный ползун");
            spirit.GetNPC("Alien").DisplayName.AddTranslation(GameCulture.Russian,"Чужой");
            spirit.GetNPC("AntlionAssassin").DisplayName.AddTranslation(GameCulture.Russian,"Муравьиный лев-ассасин");
            spirit.GetNPC("AntlionRider").DisplayName.AddTranslation(GameCulture.Russian,"Муравьиный лев-наездник");
            spirit.GetNPC("Automaton").DisplayName.AddTranslation(GameCulture.Russian,"Ящщер-автоматон");
            spirit.GetNPC("Beholder").DisplayName.AddTranslation(GameCulture.Russian,"Созерцатель");
            spirit.GetNPC("BlizzardNimbus").DisplayName.AddTranslation(GameCulture.Russian,"Снежное облако");
            spirit.GetNPC("BoneHarpy").DisplayName.AddTranslation(GameCulture.Russian,"Древний посланник");
            spirit.GetNPC("CaptiveMask").DisplayName.AddTranslation(GameCulture.Russian,"Маска узника");
            spirit.GetNPC("CavernCrawler").DisplayName.AddTranslation(GameCulture.Russian,"Пещерный ползун");
            spirit.GetNPC("CrimsonTrapper").DisplayName.AddTranslation(GameCulture.Russian,"Артериальный хвататель");
            spirit.GetNPC("CrystalDrifter").DisplayName.AddTranslation(GameCulture.Russian,"Кристальный дрифтер");
            spirit.GetNPC("CursedBall").DisplayName.AddTranslation(GameCulture.Russian,"Проклятая сфера");
            spirit.GetNPC("DeadArcher").DisplayName.AddTranslation(GameCulture.Russian,"Мёртвый снайпер");
            spirit.GetNPC("DiseasedBat").DisplayName.AddTranslation(GameCulture.Russian,"Заражённая летучая мышь");
            spirit.GetNPC("DiseasedSlime").DisplayName.AddTranslation(GameCulture.Russian,"Заражённый слизень");
            spirit.GetNPC("ExplosiveBarrel").DisplayName.AddTranslation(GameCulture.Russian,"Взрывная бочка");
            spirit.GetNPC("FallenAngel").DisplayName.AddTranslation(GameCulture.Russian,"Падший ангел");
            spirit.GetNPC("FelDemon").DisplayName.AddTranslation(GameCulture.Russian,"Демон скверны");
            spirit.GetNPC("FieryTrident").DisplayName.AddTranslation(GameCulture.Russian,"Огненный трезубец");
            spirit.GetNPC("ForgottenOne").DisplayName.AddTranslation(GameCulture.Russian,"Забытый");
            spirit.GetNPC("GElemental").DisplayName.AddTranslation(GameCulture.Russian,"Жеодный элементаль");
            spirit.GetNPC("GladiatorSpirit").DisplayName.AddTranslation(GameCulture.Russian,"Дух гладиатора");
            spirit.GetNPC("GraniteCore").DisplayName.AddTranslation(GameCulture.Russian,"Трещащее ядро");
            spirit.GetNPC("GraniteMimic").DisplayName.AddTranslation(GameCulture.Russian,"Гранитный мимик");
            spirit.GetNPC("GraniteSlime").DisplayName.AddTranslation(GameCulture.Russian,"Гранитный слизень");
            spirit.GetNPC("GrassBall").DisplayName.AddTranslation(GameCulture.Russian,"Гнев старых богов");
            spirit.GetNPC("HellEater").DisplayName.AddTranslation(GameCulture.Russian,"Чревоугодник");
            spirit.GetNPC("Hornetfish").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-шершень");
            spirit.GetNPC("JeweledBat").DisplayName.AddTranslation(GameCulture.Russian,"Драгоценная летучая мышь");
            spirit.GetNPC("JeweledSlime").DisplayName.AddTranslation(GameCulture.Russian,"Драгоценный слизень");
            spirit.GetNPC("LostMime").DisplayName.AddTranslation(GameCulture.Russian,"Потерянный мим");
            spirit.GetNPC("MarbleMimic").DisplayName.AddTranslation(GameCulture.Russian,"Мраморный мимик");
            spirit.GetNPC("Masticator").DisplayName.AddTranslation(GameCulture.Russian,"Жеватель");
            spirit.GetNPC("Mecromancer").DisplayName.AddTranslation(GameCulture.Russian,"Мехромант");
            spirit.GetNPC("Midknight").DisplayName.AddTranslation(GameCulture.Russian,"Полночный рыцарь");
            spirit.GetNPC("Mineroid").DisplayName.AddTranslation(GameCulture.Russian,"Орбитит");
            spirit.GetNPC("Nightmare").DisplayName.AddTranslation(GameCulture.Russian,"Пробудившийся кошмар");
            spirit.GetNPC("Observer").DisplayName.AddTranslation(GameCulture.Russian,"Наблюдатель");
            spirit.GetNPC("PagodaGhostHostile").DisplayName.AddTranslation(GameCulture.Russian,"Потревоженный Юрей");
            spirit.GetNPC("PagodaGhostPassive").DisplayName.AddTranslation(GameCulture.Russian,"Юрей");
            spirit.GetNPC("PinkSlimer").DisplayName.AddTranslation(GameCulture.Russian,"Сияющий слизень");
            spirit.GetNPC("SamuraiHostile").DisplayName.AddTranslation(GameCulture.Russian,"Призрачный самурай");
            spirit.GetNPC("SamuraiPassive").DisplayName.AddTranslation(GameCulture.Russian,"Призрачный самурай");
            spirit.GetNPC("ShadowMimic").DisplayName.AddTranslation(GameCulture.Russian,"Теневой мимик");
            spirit.GetNPC("ShadowPup").DisplayName.AddTranslation(GameCulture.Russian,"Теневой щенок");
            spirit.GetNPC("Spewer").DisplayName.AddTranslation(GameCulture.Russian,"Вздуватель");
            spirit.GetNPC("Spitfly").DisplayName.AddTranslation(GameCulture.Russian,"Плевомуха");
            spirit.GetNPC("SporeWheezer").DisplayName.AddTranslation(GameCulture.Russian,"Споровой хрипун");
            spirit.GetNPC("SunElemental").DisplayName.AddTranslation(GameCulture.Russian,"Солнечный элементаль");
            spirit.GetNPC("Teratoma").DisplayName.AddTranslation(GameCulture.Russian,"Путрома");
            spirit.GetNPC("Valkyrie").DisplayName.AddTranslation(GameCulture.Russian,"Валькирия");
            spirit.GetNPC("Vilemoth").DisplayName.AddTranslation(GameCulture.Russian,"Гнойная муха");
            spirit.GetNPC("VileWasp").DisplayName.AddTranslation(GameCulture.Russian,"Надоедливая муха");
            spirit.GetNPC("Wheezer").DisplayName.AddTranslation(GameCulture.Russian,"Хрипун");
            spirit.GetNPC("WinterbornMagic").DisplayName.AddTranslation(GameCulture.Russian,"Зимнерожденный-вестник");
            spirit.GetNPC("WinterbornMelee").DisplayName.AddTranslation(GameCulture.Russian,"Зимнерождённый");
            spirit.GetNPC("WitherBall").DisplayName.AddTranslation(GameCulture.Russian,"Иссушающая сфера");
            spirit.GetNPC("AstralAmalgram").DisplayName.AddTranslation(GameCulture.Russian,"Астральное слияние");
            spirit.GetNPC("CogTrapperBody").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный танцор");
            spirit.GetNPC("CogTrapperHead").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный танцор");
            spirit.GetNPC("CogTrapperTail").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный танцор");
            spirit.GetNPC("DeepspaceHopper").DisplayName.AddTranslation(GameCulture.Russian,"Шоковый прыгун");
            spirit.GetNPC("GloopGloop").DisplayName.AddTranslation(GameCulture.Russian,"Слизь");
            spirit.GetNPC("SpaceShield").DisplayName.AddTranslation(GameCulture.Russian,"Астральный щит");
            spirit.GetNPC("BloodGazer").DisplayName.AddTranslation(GameCulture.Russian,"Кровавый гейзер");
            spirit.GetNPC("BottomFeeder").DisplayName.AddTranslation(GameCulture.Russian,"Донный пожиратель");
            spirit.GetNPC("FleshHound").DisplayName.AddTranslation(GameCulture.Russian,"Гончая из плоти");
            spirit.GetNPC("Occultist").DisplayName.AddTranslation(GameCulture.Russian,"Оккультист");
            spirit.GetNPC("Phantom").DisplayName.AddTranslation(GameCulture.Russian,"Фантом");
            spirit.GetNPC("Bloomshroom").DisplayName.AddTranslation(GameCulture.Russian,"Цветочный гриб");
            spirit.GetNPC("Glitterfly").DisplayName.AddTranslation(GameCulture.Russian,"Блестящая муха");
            spirit.GetNPC("GlowToad").DisplayName.AddTranslation(GameCulture.Russian,"Сияющая жаба");
            spirit.GetNPC("Lumantis").DisplayName.AddTranslation(GameCulture.Russian,"Сияющий богомол");
            spirit.GetNPC("LunarSlime").DisplayName.AddTranslation(GameCulture.Russian,"Слизень-звездочёт");
            spirit.GetNPC("MadHatter").DisplayName.AddTranslation(GameCulture.Russian,"Безумный шляпник");
            spirit.GetNPC("AncientFlyer").DisplayName.AddTranslation(GameCulture.Russian,"Ископаемая птица");
            spirit.GetNPC("Atlas").DisplayName.AddTranslation(GameCulture.Russian,"Атлант");
            spirit.GetNPC("AtlasArmLeft").DisplayName.AddTranslation(GameCulture.Russian,"Рука Атланта");
            spirit.GetNPC("AtlasArmRight").DisplayName.AddTranslation(GameCulture.Russian,"Рука Атланта");
            spirit.GetNPC("CobbledEye").DisplayName.AddTranslation(GameCulture.Russian,"Мощёный глаз");
            spirit.GetNPC("CobbledEye2").DisplayName.AddTranslation(GameCulture.Russian,"Мощёный глаз");
            spirit.GetNPC("CobbledEye3").DisplayName.AddTranslation(GameCulture.Russian,"Мощёный глаз");
            spirit.GetNPC("Dusking").DisplayName.AddTranslation(GameCulture.Russian,"Помрачитель");
            spirit.GetNPC("ShadowBall").DisplayName.AddTranslation(GameCulture.Russian,"Полутеневая сфера");
            spirit.GetNPC("Shadowflamer").DisplayName.AddTranslation(GameCulture.Russian,"Полутеневой череп");
            spirit.GetNPC("FrostSaucer").DisplayName.AddTranslation(GameCulture.Russian,"Снежный подстрекатель");
            spirit.GetNPC("Infernon").DisplayName.AddTranslation(GameCulture.Russian,"Инфернон");
            spirit.GetNPC("InfernonSkull").DisplayName.AddTranslation(GameCulture.Russian,"Череп Инфернуса");
            spirit.GetNPC("InfernonSkullMini").DisplayName.AddTranslation(GameCulture.Russian,"Череп Инфернона");
            spirit.GetNPC("InfernoSkull").DisplayName.AddTranslation(GameCulture.Russian,"Череп Инфернуса");
            spirit.GetNPC("MoonJellyMedium").DisplayName.AddTranslation(GameCulture.Russian,"Лунный волшебник");
            spirit.GetNPC("CaptiveSpirit").DisplayName.AddTranslation(GameCulture.Russian,"Дух узника");
            spirit.GetNPC("Overseer").DisplayName.AddTranslation(GameCulture.Russian,"Надзиратель");
            spirit.GetNPC("ReachBoss").DisplayName.AddTranslation(GameCulture.Russian,"Проклятье разгневанных лоз");
            spirit.GetNPC("ReachBoss1").DisplayName.AddTranslation(GameCulture.Russian,"Оболочка разгневанных лоз");
            spirit.GetNPC("ChildofScarabeus").DisplayName.AddTranslation(GameCulture.Russian,"Дитя Скарабея");
            spirit.GetNPC("Scarab").DisplayName.AddTranslation(GameCulture.Russian,"Скарабей");
            spirit.GetNPC("Scarabeus").DisplayName.AddTranslation(GameCulture.Russian,"Скарабей");
            spirit.GetNPC("Starfarer").DisplayName.AddTranslation(GameCulture.Russian,"Звёздоплаватель");
            spirit.GetNPC("LaserBase").DisplayName.AddTranslation(GameCulture.Russian,"Лазерный запускатель");
            spirit.GetNPC("SteamRaiderBody").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный странник");
            spirit.GetNPC("SteamRaiderBody2").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный странник");
            spirit.GetNPC("SteamRaiderHead").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный странник");
            spirit.GetNPC("SteamRaiderHeadDeath").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный странник");
            spirit.GetNPC("SteamRaiderTail").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный странник");
            spirit.GetNPC("SuicideLaser").DisplayName.AddTranslation(GameCulture.Russian,"Лазерный бомбардировщик");
            spirit.GetNPC("TailProbe").DisplayName.AddTranslation(GameCulture.Russian,"Звёздоплаватель");
            spirit.GetNPC("AtlanticCod").DisplayName.AddTranslation(GameCulture.Russian,"Атлантическая треска");
            spirit.GetNPC("Blossmoon").DisplayName.AddTranslation(GameCulture.Russian,"Цветущая луна");
            spirit.GetNPC("Cavefish").DisplayName.AddTranslation(GameCulture.Russian,"Бронированная пещерная рыба");
            spirit.GetNPC("Cleft").DisplayName.AddTranslation(GameCulture.Russian,"Щельевой прыгун");
            spirit.GetNPC("CrismonTigerfish").DisplayName.AddTranslation(GameCulture.Russian,"Багряная рыба-тигр");
            spirit.GetNPC("Damselfish").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-ласточка");
            spirit.GetNPC("Ebonkoi").DisplayName.AddTranslation(GameCulture.Russian,"Эбонитовая кои");
            spirit.GetNPC("FishCrate").DisplayName.AddTranslation(GameCulture.Russian,"Упаковочный ящик");
            spirit.GetNPC("Floater").DisplayName.AddTranslation(GameCulture.Russian,"Люминесцентный летун");
            spirit.GetNPC("Floater1").DisplayName.AddTranslation(GameCulture.Russian,"Люминесцентный летун");
            spirit.GetNPC("FrostMinnow").DisplayName.AddTranslation(GameCulture.Russian,"Морозный пескарь");
            spirit.GetNPC("GaleSnail").DisplayName.AddTranslation(GameCulture.Russian,"Штормовая улитка");
            spirit.GetNPC("GildJelly").DisplayName.AddTranslation(GameCulture.Russian,"Позолоченное желе");
            spirit.GetNPC("GoldenCarp").DisplayName.AddTranslation(GameCulture.Russian,"Золотой карп");
            spirit.GetNPC("GoldLumoth").DisplayName.AddTranslation(GameCulture.Russian,"Золотой люмот");
            spirit.GetNPC("Gulper").DisplayName.AddTranslation(GameCulture.Russian,"Глотатель");
            spirit.GetNPC("HailSnail").DisplayName.AddTranslation(GameCulture.Russian,"Градовая улитка");
            spirit.GetNPC("Hemoglob").DisplayName.AddTranslation(GameCulture.Russian,"Гемокомок");
            spirit.GetNPC("Lumoth").DisplayName.AddTranslation(GameCulture.Russian,"Сияющий мотылёк");
            spirit.GetNPC("Luvdisc").DisplayName.AddTranslation(GameCulture.Russian,"Страстная рыба");
            spirit.GetNPC("Maggotfly").DisplayName.AddTranslation(GameCulture.Russian,"Личинка мухи");
            spirit.GetNPC("NeonTetra").DisplayName.AddTranslation(GameCulture.Russian,"Неоновая тетра");
            spirit.GetNPC("Prismite").DisplayName.AddTranslation(GameCulture.Russian,"Призмит");
            spirit.GetNPC("RedSnapper").DisplayName.AddTranslation(GameCulture.Russian,"Красный луциан");
            spirit.GetNPC("Rotslug").DisplayName.AddTranslation(GameCulture.Russian,"Гнилой слизняк");
            spirit.GetNPC("SpecularFish").DisplayName.AddTranslation(GameCulture.Russian,"Зеркальная рыба");
            spirit.GetNPC("Vibeshroom").DisplayName.AddTranslation(GameCulture.Russian,"Дрожегриб");
            spirit.GetNPC("BlueAlgae1").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("BlueAlgae2").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("BlueAlgae3").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("GreenAlgae1").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("GreenAlgae2").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("GreenAlgae3").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("PurpleAlgae1").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("PurpleAlgae2").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("PurpleAlgae3").DisplayName.AddTranslation(GameCulture.Russian,"Биолюминесцентные водоросли");
            spirit.GetNPC("BlazingRattler").DisplayName.AddTranslation(GameCulture.Russian,"Пылающий гремучий змей");
            spirit.GetNPC("DungeonCubeBlue").DisplayName.AddTranslation(GameCulture.Russian,"Куб темницы");
            spirit.GetNPC("DungeonCubeGreen").DisplayName.AddTranslation(GameCulture.Russian,"Куб темницы");
            spirit.GetNPC("DungeonCubePink").DisplayName.AddTranslation(GameCulture.Russian,"Куб темницы");
            spirit.GetNPC("Illusionist").DisplayName.AddTranslation(GameCulture.Russian,"Вурдалак");
            spirit.GetNPC("IllusionistSpectre").DisplayName.AddTranslation(GameCulture.Russian,"Фантом вурдалака");
            spirit.GetNPC("PlagueDoctor").DisplayName.AddTranslation(GameCulture.Russian,"Тёмный алхимик");
            spirit.GetNPC("SpectralSkull").DisplayName.AddTranslation(GameCulture.Russian,"Спектральный череп");
            spirit.GetNPC("GoldCrateMimic").DisplayName.AddTranslation(GameCulture.Russian,"Золотой ящик-мимик");
            spirit.GetNPC("IronCrateMimic").DisplayName.AddTranslation(GameCulture.Russian,"Железный ящик-мимик");
            spirit.GetNPC("WoodCrateMimic").DisplayName.AddTranslation(GameCulture.Russian,"Деревянный ящик-мимик");
            spirit.GetNPC("ElectricEel").DisplayName.AddTranslation(GameCulture.Russian,"Электрический угорь");
            spirit.GetNPC("OceanSlime").DisplayName.AddTranslation(GameCulture.Russian,"Кокосовый слизень");
            spirit.GetNPC("PinkJelly").DisplayName.AddTranslation(GameCulture.Russian,"Парусница");
            spirit.GetNPC("SwollenFish").DisplayName.AddTranslation(GameCulture.Russian,"Раздутая рыба");
            spirit.GetNPC("AngryGremlin").DisplayName.AddTranslation(GameCulture.Russian,"Злой гремлин");
            spirit.GetNPC("BlossomHound").DisplayName.AddTranslation(GameCulture.Russian,"Цветущая гончая");
            spirit.GetNPC("ForestWraith").DisplayName.AddTranslation(GameCulture.Russian,"Вересковый дух");
            spirit.GetNPC("GrassVine").DisplayName.AddTranslation(GameCulture.Russian,"Росянковый охотник");
            spirit.GetNPC("Gremlin").DisplayName.AddTranslation(GameCulture.Russian,"Гремлин");
            spirit.GetNPC("GroveCaster").DisplayName.AddTranslation(GameCulture.Russian,"Шаман диких лесов");
            spirit.GetNPC("Noxophyll").DisplayName.AddTranslation(GameCulture.Russian,"Ноксофилл");
            spirit.GetNPC("Reachman").DisplayName.AddTranslation(GameCulture.Russian,"Одичалый охотник");
            spirit.GetNPC("ReachmanPassive").DisplayName.AddTranslation(GameCulture.Russian,"Одичалый охотник");
            spirit.GetNPC("ReachObserver").DisplayName.AddTranslation(GameCulture.Russian,"Страж диких лесов");
            spirit.GetNPC("ReachShaman").DisplayName.AddTranslation(GameCulture.Russian,"Одичалый спиритуалист");
            spirit.GetNPC("ReachSlime").DisplayName.AddTranslation(GameCulture.Russian,"Вересковый слизень");
            spirit.GetNPC("ThornStalker").DisplayName.AddTranslation(GameCulture.Russian,"Колючий преследователь");
            spirit.GetNPC("ReachWorm1").DisplayName.AddTranslation(GameCulture.Russian,"Малинниковый копатель");
            spirit.GetNPC("ReachWorm2").DisplayName.AddTranslation(GameCulture.Russian,"Малинниковый копатель");
            spirit.GetNPC("ReachWorm3").DisplayName.AddTranslation(GameCulture.Russian,"Малинниковый копатель");
            spirit.GetNPC("AncientDemon").DisplayName.AddTranslation(GameCulture.Russian,"Древний призрак");
            spirit.GetNPC("HauntedBook").DisplayName.AddTranslation(GameCulture.Russian,"Древний том");
            spirit.GetNPC("Hedron").DisplayName.AddTranslation(GameCulture.Russian,"Хэдрон");
            spirit.GetNPC("NetherBane").DisplayName.AddTranslation(GameCulture.Russian,"Проклятие преисподней");
            spirit.GetNPC("SeerBat").DisplayName.AddTranslation(GameCulture.Russian,"Духовная летучая мышь");
            spirit.GetNPC("SoulCrusher").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель душ");
            spirit.GetNPC("SoulOrb").DisplayName.AddTranslation(GameCulture.Russian,"Духовная сфера");
            spirit.GetNPC("SpiritGhoul").DisplayName.AddTranslation(GameCulture.Russian,"Теневой вурдалак");
            spirit.GetNPC("SpiritMimic").DisplayName.AddTranslation(GameCulture.Russian,"Духовный мимик");
            spirit.GetNPC("SpiritMummy").DisplayName.AddTranslation(GameCulture.Russian,"Сумрачная мумия");
            spirit.GetNPC("SpiritSkull").DisplayName.AddTranslation(GameCulture.Russian,"Духовный череп");
            spirit.GetNPC("SpiritVulture").DisplayName.AddTranslation(GameCulture.Russian,"Духовный летун");
            spirit.GetNPC("UnstableWisp").DisplayName.AddTranslation(GameCulture.Russian,"Неустойчивый огонёк");
            spirit.GetNPC("WanderingSoul").DisplayName.AddTranslation(GameCulture.Russian,"Блуждающая душа");
            spirit.GetNPC("Crocomount").DisplayName.AddTranslation(GameCulture.Russian,"Крокозавр");
            spirit.GetNPC("KakamoraParachuter").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский планерист");
            spirit.GetNPC("KakamoraRider").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский наездник");
            spirit.GetNPC("KakamoraRunner").DisplayName.AddTranslation(GameCulture.Russian,"Какамора");
            spirit.GetNPC("KakamoraShaman").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский шаман");
            spirit.GetNPC("KakamoraShielder").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский защитник");
            spirit.GetNPC("KakamoraShielderRare").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский страж");
            spirit.GetNPC("LargeCrustecean").DisplayName.AddTranslation(GameCulture.Russian,"Пузырьковый дикарь");
            spirit.GetNPC("MangoJelly").DisplayName.AddTranslation(GameCulture.Russian,"Манговая физалия");
            spirit.GetNPC("Rylheian").DisplayName.AddTranslation(GameCulture.Russian,"Р’льехиан");
            spirit.GetNPC("SpearKakamora").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский метатель");
            spirit.GetNPC("SwordKakamora").DisplayName.AddTranslation(GameCulture.Russian,"Какаморианский мечник");
            spirit.GetNPC("Adventurer").DisplayName.AddTranslation(GameCulture.Russian,"Искатель приключений");
            spirit.GetNPC("BoundAdventurer").DisplayName.AddTranslation(GameCulture.Russian,"Пойманный авантюрист");
            spirit.GetNPC("BoundGambler").DisplayName.AddTranslation(GameCulture.Russian,"Связанный мошенник");
            spirit.GetNPC("BoundRogue").DisplayName.AddTranslation(GameCulture.Russian,"Связанный бандит");
            spirit.GetNPC("Gambler").DisplayName.AddTranslation(GameCulture.Russian,"Азартный игрок");
            spirit.GetNPC("LoneTrapper").DisplayName.AddTranslation(GameCulture.Russian,"Одинокий охотник");
            spirit.GetNPC("Martian").DisplayName.AddTranslation(GameCulture.Russian,"Марсианский учёный");
            spirit.GetNPC("Rogue").DisplayName.AddTranslation(GameCulture.Russian,"Бандит");
            spirit.GetNPC("RuneWizard").DisplayName.AddTranslation(GameCulture.Russian,"Зачарователь");
            spirit.GetNPC("BlizzardBandit").DisplayName.AddTranslation(GameCulture.Russian,"Бандит метели");
            spirit.GetNPC("CavernBandit").DisplayName.AddTranslation(GameCulture.Russian,"Бандит пещер");
            spirit.GetNPC("MycelialBotanist").DisplayName.AddTranslation(GameCulture.Russian,"Мицелиальный ботаник");
            spirit.GetNPC("SunFlower").DisplayName.AddTranslation(GameCulture.Russian,"Солнечный цветок");
            spirit.GetNPC("DepthTrencher").DisplayName.AddTranslation(GameCulture.Russian,"Глубокорыхлитель");
            spirit.GetNPC("ShellBane").DisplayName.AddTranslation(GameCulture.Russian,"Проклятие панциря");
            spirit.GetNPC("SulfurElemental").DisplayName.AddTranslation(GameCulture.Russian,"Лавовый элементаль");
        }
    }
}