using Terraria.Localization;

namespace CalamityRuTranslate.CalamityMod.Buffs
{
	internal static class CalamityBuffs
	{
		public static void Setup()
		{
			Buffs();
		}
		private static void Buffs()
		{
// ==================================================================================================================
					// Buffs
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("PopoBuff").DisplayName.AddTranslation(GameCulture.Russian,"Попо");
			ModCompatibility.CalamityMod.GetBuff("PopoBuff").Description.AddTranslation(GameCulture.Russian,"Теперь вы снеговик!");
			ModCompatibility.CalamityMod.GetBuff("PopoNoselessBuff").DisplayName.AddTranslation(GameCulture.Russian,"Безносый Попо");
			ModCompatibility.CalamityMod.GetBuff("PopoNoselessBuff").Description.AddTranslation(GameCulture.Russian,"Ваш нос был украден!");
// ==================================================================================================================
					// Alcohol
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AlcoholPoisoning").DisplayName.AddTranslation(GameCulture.Russian,"Алкогольное отравление");
			ModCompatibility.CalamityMod.GetBuff("AlcoholPoisoning").Description.AddTranslation(GameCulture.Russian,"Вы слишком много выпили и теперь умираете");
			ModCompatibility.CalamityMod.GetBuff("BloodyMaryBuff").DisplayName.AddTranslation(GameCulture.Russian,"Кровавая Мэри");
			ModCompatibility.CalamityMod.GetBuff("BloodyMaryBuff").Description.AddTranslation(GameCulture.Russian,"Урон, шанс критического удара, скорость передвижения и скорость атаки ближнего боя увеличены во время Кровавой луны, регенерация здоровья и защита снижены");
			ModCompatibility.CalamityMod.GetBuff("CaribbeanRumBuff").DisplayName.AddTranslation(GameCulture.Russian,"Карибский ром");
			ModCompatibility.CalamityMod.GetBuff("CaribbeanRumBuff").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья, скорость передвижения и время полёта крыльев увеличены, вы парящий и защита снижена");
			ModCompatibility.CalamityMod.GetBuff("CinnamonRollBuff").DisplayName.AddTranslation(GameCulture.Russian,"Коричный ролл");
			ModCompatibility.CalamityMod.GetBuff("CinnamonRollBuff").Description.AddTranslation(GameCulture.Russian,"Скорость регенерации маны и урон огненного оружия увеличены, защита снижена");
			ModCompatibility.CalamityMod.GetBuff("EverclearBuff").DisplayName.AddTranslation(GameCulture.Russian,"Эверклеар");
			ModCompatibility.CalamityMod.GetBuff("EverclearBuff").Description.AddTranslation(GameCulture.Russian,"Урон увеличен на 25%, регенерация здоровья снижена на 10 и защита на 40");
			ModCompatibility.CalamityMod.GetBuff("EvergreenGinBuff").DisplayName.AddTranslation(GameCulture.Russian,"Вечнозелёный джин");
			ModCompatibility.CalamityMod.GetBuff("EvergreenGinBuff").Description.AddTranslation(GameCulture.Russian,"Урон природного оружия и сопротивление урону увеличены, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("FabsolVodkaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Потрясение");
			ModCompatibility.CalamityMod.GetBuff("FabsolVodkaBuff").Description.AddTranslation(GameCulture.Russian,"Вы чувствуете себя невероятно");
			ModCompatibility.CalamityMod.GetBuff("FireballBuff").DisplayName.AddTranslation(GameCulture.Russian,"Файерболл");
			ModCompatibility.CalamityMod.GetBuff("FireballBuff").Description.AddTranslation(GameCulture.Russian,"Урон огненного оружия увеличен, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("GrapeBeerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Виноградное пиво");
			ModCompatibility.CalamityMod.GetBuff("GrapeBeerBuff").Description.AddTranslation(GameCulture.Russian,"Защита и скорость передвижения снижены");
			ModCompatibility.CalamityMod.GetBuff("MargaritaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маргарита");
			ModCompatibility.CalamityMod.GetBuff("MargaritaBuff").Description.AddTranslation(GameCulture.Russian,"Снижена длительность большинства дебаффов, защита и регенерация здоровья снижены");
			ModCompatibility.CalamityMod.GetBuff("MoonshineBuff").DisplayName.AddTranslation(GameCulture.Russian,"Самогон");
			ModCompatibility.CalamityMod.GetBuff("MoonshineBuff").Description.AddTranslation(GameCulture.Russian,"Защита и сопротивление урону увеличены, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("MoscowMuleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Московский мул");
			ModCompatibility.CalamityMod.GetBuff("MoscowMuleBuff").Description.AddTranslation(GameCulture.Russian,"Урон, шанс критического удара и отбрасывание увеличены, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("RedWineBuff").DisplayName.AddTranslation(GameCulture.Russian,"Красное вино");
			ModCompatibility.CalamityMod.GetBuff("RedWineBuff").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("RumBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ром");
			ModCompatibility.CalamityMod.GetBuff("RumBuff").Description.AddTranslation(GameCulture.Russian,"Скорость передвижения и регенерация здоровья увеличены, защита снижена");
			ModCompatibility.CalamityMod.GetBuff("ScrewdriverBuff").DisplayName.AddTranslation(GameCulture.Russian,"Отвёртка");
			ModCompatibility.CalamityMod.GetBuff("ScrewdriverBuff").Description.AddTranslation(GameCulture.Russian,"Урон пронзающих снарядов увеличен, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("StarBeamRyeBuff").DisplayName.AddTranslation(GameCulture.Russian,"Стар Бим Рай");
			ModCompatibility.CalamityMod.GetBuff("StarBeamRyeBuff").Description.AddTranslation(GameCulture.Russian,"Максимальный запас маны и магический урон увеличены. Защита, расход маны и регенерация здоровья снижены");
			ModCompatibility.CalamityMod.GetBuff("TequilaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Текила");
			ModCompatibility.CalamityMod.GetBuff("TequilaBuff").Description.AddTranslation(GameCulture.Russian,"Урон, шанс критического удара, сопротивление урону, защита и отбрасывание увеличены в дневное время суток, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("TequilaSunriseBuff").DisplayName.AddTranslation(GameCulture.Russian,"Текила Санрайз");
			ModCompatibility.CalamityMod.GetBuff("TequilaSunriseBuff").Description.AddTranslation(GameCulture.Russian,"Урон, шанс критического удара, сопротивление урону, защита и отбрасывание увеличены в дневное время суток, регенерация здоровья снижена");
			ModCompatibility.CalamityMod.GetBuff("Trippy").DisplayName.AddTranslation(GameCulture.Russian,"Триповый");
			ModCompatibility.CalamityMod.GetBuff("Trippy").Description.AddTranslation(GameCulture.Russian,"Вы видите этот мир таким, какой он есть на самом деле... Также ваш урон увеличен на 50%");
			ModCompatibility.CalamityMod.GetBuff("VodkaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Водка");
			ModCompatibility.CalamityMod.GetBuff("VodkaBuff").Description.AddTranslation(GameCulture.Russian,"Шанс критического удара и отбрасывание увеличены, регенерация здоровья и защита снижены");
			ModCompatibility.CalamityMod.GetBuff("WhiskeyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Виски");
			ModCompatibility.CalamityMod.GetBuff("WhiskeyBuff").Description.AddTranslation(GameCulture.Russian,"Шанс критического удара и отбрасывание увеличены, защита снижена");
			ModCompatibility.CalamityMod.GetBuff("WhiteWineBuff").DisplayName.AddTranslation(GameCulture.Russian,"Белое вино");
			ModCompatibility.CalamityMod.GetBuff("WhiteWineBuff").Description.AddTranslation(GameCulture.Russian,"Магический урон и регенерация здоровья увеличены и защита снижена");
// ==================================================================================================================
					// Cooldowns
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitPlatesBroken").DisplayName.AddTranslation(GameCulture.Russian,"Сломанные пластины глубоководного водолазного костюма");
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitPlatesBroken").Description.AddTranslation(GameCulture.Russian,"Пластины восстанавливаются");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMadnessCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка безумия бездны");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMadnessCooldown").Description.AddTranslation(GameCulture.Russian,"Ваше безумие бездны перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMirrorCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка уклонения бездны");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMirrorCooldown").Description.AddTranslation(GameCulture.Russian,"Ваш уворот зеркала бездны перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("BloodflareBloodFrenzyCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка кровавого неистовства");
			ModCompatibility.CalamityMod.GetBuff("BloodflareBloodFrenzyCooldown").Description.AddTranslation(GameCulture.Russian,"Ваше кровавое неистовство перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("BloodflareSoulCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка душ кровавой вспышки");
			ModCompatibility.CalamityMod.GetBuff("BloodflareSoulCooldown").Description.AddTranslation(GameCulture.Russian,"Ваши души перезаряжаются");
			ModCompatibility.CalamityMod.GetBuff("BrimflameFrenzyCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка серного неистовства");
			ModCompatibility.CalamityMod.GetBuff("BrimflameFrenzyCooldown").Description.AddTranslation(GameCulture.Russian,"Ваше использование серной магии истощило вас");
			ModCompatibility.CalamityMod.GetBuff("ConcoctionCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка смеси");
			ModCompatibility.CalamityMod.GetBuff("ConcoctionCooldown").Description.AddTranslation(GameCulture.Russian,"Возрождение перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("DraconicSurgeCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка драконьего всплеска");
			ModCompatibility.CalamityMod.GetBuff("DraconicSurgeCooldown").Description.AddTranslation(GameCulture.Russian,"Таинственная сила препятствует поглощению драконической энергии");
			ModCompatibility.CalamityMod.GetBuff("EclipseMirrorCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка уклонения затмения");
			ModCompatibility.CalamityMod.GetBuff("EclipseMirrorCooldown").Description.AddTranslation(GameCulture.Russian,"Ваш уворот зеркала затмения перезаряжается");
            ModCompatibility.CalamityMod.GetBuff("EnergyShellCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка энергетического панциря");
            ModCompatibility.CalamityMod.GetBuff("EnergyShellCooldown").Description.AddTranslation(GameCulture.Russian, "Ваш энергетический панцирь перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("EvasionScarfCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка избегающего шарфа");
            ModCompatibility.CalamityMod.GetBuff("EvasionScarfCooldown").Description.AddTranslation(GameCulture.Russian, "Ваш уворот перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("FleshTotemCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка тотема плоти");
			ModCompatibility.CalamityMod.GetBuff("FleshTotemCooldown").Description.AddTranslation(GameCulture.Russian,"Эффект тотема плоти перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("GodSlayerCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка богоубийцы");
			ModCompatibility.CalamityMod.GetBuff("GodSlayerCooldown").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья сокращена вдвое; эффект богоубийцы перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("IceShieldBrokenBuff").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка ледяного щита");
			ModCompatibility.CalamityMod.GetBuff("IceShieldBrokenBuff").Description.AddTranslation(GameCulture.Russian,"Щит восстанавливается");
			ModCompatibility.CalamityMod.GetBuff("InkBombCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка чернильной бомбы");
			ModCompatibility.CalamityMod.GetBuff("InkBombCooldown").Description.AddTranslation(GameCulture.Russian,"Ваша чернильная бомба перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("PlagueBlackoutCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка чумного отключения");
			ModCompatibility.CalamityMod.GetBuff("PlagueBlackoutCooldown").Description.AddTranslation(GameCulture.Russian,"Ваша способность чумного отключения перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("PrismaticCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Призматическая перезарядка");
			ModCompatibility.CalamityMod.GetBuff("PrismaticCooldown").Description.AddTranslation(GameCulture.Russian,"Ваша лазерная атака перезаряжается");
            ModCompatibility.CalamityMod.GetBuff("ResilienceCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка устойчивости");
            ModCompatibility.CalamityMod.GetBuff("ResilienceCooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете вновь призвать реликвию устойчивости");
			ModCompatibility.CalamityMod.GetBuff("SandCloakCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка песчаного плаща");
			ModCompatibility.CalamityMod.GetBuff("SandCloakCooldown").Description.AddTranslation(GameCulture.Russian,"Ваш песчаный плащ перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("ScarfCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка шарфа");
			ModCompatibility.CalamityMod.GetBuff("ScarfCooldown").Description.AddTranslation(GameCulture.Russian,"Ваш уворот перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("TarragonCloakCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка плаща Таррагона");
			ModCompatibility.CalamityMod.GetBuff("TarragonCloakCooldown").Description.AddTranslation(GameCulture.Russian,"Ваш плащ перезаряжается");
			ModCompatibility.CalamityMod.GetBuff("TarragonImmunityCooldown").DisplayName.AddTranslation(GameCulture.Russian,"Перезарядка неуязвимости Таррагона");
			ModCompatibility.CalamityMod.GetBuff("TarragonImmunityCooldown").Description.AddTranslation(GameCulture.Russian,"Ваша неуязвимость перезаряжается");
// ==================================================================================================================
					// DamageOverTime
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AbyssalFlames").DisplayName.AddTranslation(GameCulture.Russian,"Огонь бездны");
			ModCompatibility.CalamityMod.GetBuff("AbyssalFlames").Description.AddTranslation(GameCulture.Russian,"Ваша душа поглощается");
			ModCompatibility.CalamityMod.GetBuff("AstralInfectionDebuff").DisplayName.AddTranslation(GameCulture.Russian,"Астральная инфекция");
			ModCompatibility.CalamityMod.GetBuff("AstralInfectionDebuff").Description.AddTranslation(GameCulture.Russian,"Ваша плоть плавится");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneFlames").DisplayName.AddTranslation(GameCulture.Russian,"Серные огни");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneFlames").Description.AddTranslation(GameCulture.Russian,"Быстрая потеря здоровья");
			ModCompatibility.CalamityMod.GetBuff("BurningBlood").DisplayName.AddTranslation(GameCulture.Russian,"Пылающая кровь");
			ModCompatibility.CalamityMod.GetBuff("BurningBlood").Description.AddTranslation(GameCulture.Russian,"Ваша кровь горит");
			ModCompatibility.CalamityMod.GetBuff("CragsLava").DisplayName.AddTranslation(GameCulture.Russian, "Иссушающая лава");
			ModCompatibility.CalamityMod.GetBuff("CragsLava").Description.AddTranslation(GameCulture.Russian,"Серная лава иссушает вашу плоть");
			ModCompatibility.CalamityMod.GetBuff("CrushDepth").DisplayName.AddTranslation(GameCulture.Russian,"Давление глубин");
			ModCompatibility.CalamityMod.GetBuff("CrushDepth").Description.AddTranslation(GameCulture.Russian,"Давление воды");
			ModCompatibility.CalamityMod.GetBuff("DemonFlames").DisplayName.AddTranslation(GameCulture.Russian,"Пламя демона");
			ModCompatibility.CalamityMod.GetBuff("DemonFlames").Description.AddTranslation(GameCulture.Russian, "Очередной горящий дебафф");
			ModCompatibility.CalamityMod.GetBuff("GodSlayerInferno").DisplayName.AddTranslation(GameCulture.Russian,"Пламя богоубийцы");
			ModCompatibility.CalamityMod.GetBuff("GodSlayerInferno").Description.AddTranslation(GameCulture.Russian,"Ваша плоть сгорает");
			ModCompatibility.CalamityMod.GetBuff("HeavyBleeding").DisplayName.AddTranslation(GameCulture.Russian,"Сильное кровотечение");
			ModCompatibility.CalamityMod.GetBuff("HeavyBleeding").Description.AddTranslation(GameCulture.Russian,"Вы теряете много крови");
			ModCompatibility.CalamityMod.GetBuff("HolyFlames").DisplayName.AddTranslation(GameCulture.Russian,"Святые огни");
			ModCompatibility.CalamityMod.GetBuff("HolyFlames").Description.AddTranslation(GameCulture.Russian,"Растворение от святого света");
			ModCompatibility.CalamityMod.GetBuff("HolyInferno").DisplayName.AddTranslation(GameCulture.Russian,"Святое инферно");
			ModCompatibility.CalamityMod.GetBuff("HolyInferno").Description.AddTranslation(GameCulture.Russian,"Вы отошли слишком далеко от Осквернённой богини!");
			ModCompatibility.CalamityMod.GetBuff("LethalLavaBurn").DisplayName.AddTranslation(GameCulture.Russian,"Смертельный ожог лавы");
			ModCompatibility.CalamityMod.GetBuff("LethalLavaBurn").Description.AddTranslation(GameCulture.Russian,"Потеря здоровья");
			ModCompatibility.CalamityMod.GetBuff("Nightwither").DisplayName.AddTranslation(GameCulture.Russian,"Ночное иссушение");
			ModCompatibility.CalamityMod.GetBuff("Nightwither").Description.AddTranslation(GameCulture.Russian,"Испепелён лунными лучами");
			ModCompatibility.CalamityMod.GetBuff("Plague").DisplayName.AddTranslation(GameCulture.Russian,"Чума");
			ModCompatibility.CalamityMod.GetBuff("Plague").Description.AddTranslation(GameCulture.Russian,"Гниение изнутри");
			ModCompatibility.CalamityMod.GetBuff("Shadowflame").DisplayName.AddTranslation(GameCulture.Russian,"Теневое пламя");
			ModCompatibility.CalamityMod.GetBuff("Shadowflame").Description.AddTranslation(GameCulture.Russian,"Потеря здоровья");
			ModCompatibility.CalamityMod.GetBuff("ShellfishEating").DisplayName.AddTranslation(GameCulture.Russian,"Хлопки моллюска");
			ModCompatibility.CalamityMod.GetBuff("ShellfishEating").Description.AddTranslation(GameCulture.Russian,"Фестиваль моллюсков");
			ModCompatibility.CalamityMod.GetBuff("Shred").DisplayName.AddTranslation(GameCulture.Russian,"Шинковка");
			ModCompatibility.CalamityMod.GetBuff("Shred").Description.AddTranslation(GameCulture.Russian,"Кровь");
			ModCompatibility.CalamityMod.GetBuff("SnapClamDebuff").DisplayName.AddTranslation(GameCulture.Russian,"Стиснутый");
			ModCompatibility.CalamityMod.GetBuff("SnapClamDebuff").Description.AddTranslation(GameCulture.Russian,"Хлопок моллюска");
			ModCompatibility.CalamityMod.GetBuff("SulphuricPoisoning").DisplayName.AddTranslation(GameCulture.Russian,"Сернистое отравление");
			ModCompatibility.CalamityMod.GetBuff("SulphuricPoisoning").Description.AddTranslation(GameCulture.Russian,"Кислотная вода прожигает вашу плоть");
			ModCompatibility.CalamityMod.GetBuff("Vaporfied").DisplayName.AddTranslation(GameCulture.Russian,"Запаренный");
			ModCompatibility.CalamityMod.GetBuff("Vaporfied").Description.AddTranslation(GameCulture.Russian,"Пар");
			ModCompatibility.CalamityMod.GetBuff("VulnerabilityHex").DisplayName.AddTranslation(GameCulture.Russian,"Проклятье уязвимости");
			ModCompatibility.CalamityMod.GetBuff("VulnerabilityHex").Description.AddTranslation(GameCulture.Russian,"Вы слабак");
// ==================================================================================================================
					// Mounts
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AlicornBuff").DisplayName.AddTranslation(GameCulture.Russian,"Аликорн");
			ModCompatibility.CalamityMod.GetBuff("AlicornBuff").Description.AddTranslation(GameCulture.Russian,"Вы победили Пожирателя Богов в пьяном виде, вы действительно невероятны!");
			ModCompatibility.CalamityMod.GetBuff("AndromedaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Андромеда");
			ModCompatibility.CalamityMod.GetBuff("AndromedaBuff").Description.AddTranslation(GameCulture.Russian,"Вы управляете частью истории");
			ModCompatibility.CalamityMod.GetBuff("AndromedaSmallBuff").DisplayName.AddTranslation(GameCulture.Russian,"Андромеда");
			ModCompatibility.CalamityMod.GetBuff("AndromedaSmallBuff").Description.AddTranslation(GameCulture.Russian,"Вы управляете малой частью истории");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneMount").DisplayName.AddTranslation(GameCulture.Russian,"Ездовая серороза");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneMount").Description.AddTranslation(GameCulture.Russian,"Сиденье поджарено. На этом всё");
			ModCompatibility.CalamityMod.GetBuff("BumbledogeMount").DisplayName.AddTranslation(GameCulture.Russian,"Бамблдог");
			ModCompatibility.CalamityMod.GetBuff("BumbledogeMount").Description.AddTranslation(GameCulture.Russian,"Подожди секунду. Это неправильно...");
			ModCompatibility.CalamityMod.GetBuff("GazeOfCrysthamyrBuff").DisplayName.AddTranslation(GameCulture.Russian,"Взгляд Кристамира");
			ModCompatibility.CalamityMod.GetBuff("GazeOfCrysthamyrBuff").Description.AddTranslation(GameCulture.Russian,"Вы едете верхом на теневом драконе");
			ModCompatibility.CalamityMod.GetBuff("OnyxExcavatorBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ониксовый землекоп");
			ModCompatibility.CalamityMod.GetBuff("OnyxExcavatorBuff").Description.AddTranslation(GameCulture.Russian,"Бур");
			ModCompatibility.CalamityMod.GetBuff("SquishyBeanBuff").DisplayName.AddTranslation(GameCulture.Russian,"Болотистый боб");
			ModCompatibility.CalamityMod.GetBuff("SquishyBeanBuff").Description.AddTranslation(GameCulture.Russian,"БОБОВЫЙ ЧЕЛОВЕК. БОБ ДЕЛАЕТ, БОБ УЖЕ ТУТ");
			ModCompatibility.CalamityMod.GetBuff("TundraLeashBuff").DisplayName.AddTranslation(GameCulture.Russian,"Злая собака");
			ModCompatibility.CalamityMod.GetBuff("TundraLeashBuff").Description.AddTranslation(GameCulture.Russian,"Вы едете верхом на злой собаке");
// ==================================================================================================================
					// Pets
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AkatoYharonBuff").DisplayName.AddTranslation(GameCulture.Russian,"Акато");
			ModCompatibility.CalamityMod.GetBuff("AkatoYharonBuff").Description.AddTranslation(GameCulture.Russian,"Похоже, тебе придётся позаботиться об этом сейчас");
			ModCompatibility.CalamityMod.GetBuff("AstrophageBuff").DisplayName.AddTranslation(GameCulture.Russian,"Астрофаг");
			ModCompatibility.CalamityMod.GetBuff("AstrophageBuff").Description.AddTranslation(GameCulture.Russian,"Маленький астральный жучок");
			ModCompatibility.CalamityMod.GetBuff("BabyGhostBellBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький призрачный колокольчик");
			ModCompatibility.CalamityMod.GetBuff("BabyGhostBellBuff").Description.AddTranslation(GameCulture.Russian,"Будь осторожен, чтобы не лопнуть пузырь");
			ModCompatibility.CalamityMod.GetBuff("BearBuff").DisplayName.AddTranslation(GameCulture.Russian,"Bear");
			ModCompatibility.CalamityMod.GetBuff("BearBuff").Description.AddTranslation(GameCulture.Russian,"Ангел-хранитель следует за вами");
			ModCompatibility.CalamityMod.GetBuff("BendyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Туман фантазий");
			ModCompatibility.CalamityMod.GetBuff("BendyBuff").Description.AddTranslation(GameCulture.Russian,"Кси верит в тебя Ю");
			ModCompatibility.CalamityMod.GetBuff("BloodBound").DisplayName.AddTranslation(GameCulture.Russian,"Кровавая связь");
			ModCompatibility.CalamityMod.GetBuff("BloodBound").Description.AddTranslation(GameCulture.Russian,"Вы должно быть отчаянно нуждаетесь в компании");
			ModCompatibility.CalamityMod.GetBuff("BrimlingBuff").DisplayName.AddTranslation(GameCulture.Russian,"Пепельничок");
			ModCompatibility.CalamityMod.GetBuff("BrimlingBuff").Description.AddTranslation(GameCulture.Russian,"Защищай её или страдай в агонии");
			ModCompatibility.CalamityMod.GetBuff("ChibiiBuff").DisplayName.AddTranslation(GameCulture.Russian,"Чиби Пожиратель");
			ModCompatibility.CalamityMod.GetBuff("ChibiiBuff").Description.AddTranslation(GameCulture.Russian,"Что? Вы ждали кого-то другого?");
			ModCompatibility.CalamityMod.GetBuff("DannyDevito").DisplayName.AddTranslation(GameCulture.Russian,"Дэнни Девито");
			ModCompatibility.CalamityMod.GetBuff("DannyDevito").Description.AddTranslation(GameCulture.Russian,"Мусорщик следует за вами");
			ModCompatibility.CalamityMod.GetBuff("FlakPetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Зенитный отшельник");
			ModCompatibility.CalamityMod.GetBuff("FlakPetBuff").Description.AddTranslation(GameCulture.Russian,"Маленький кислотный жучок");
			ModCompatibility.CalamityMod.GetBuff("Fox").DisplayName.AddTranslation(GameCulture.Russian,"Питомец лиса");
			ModCompatibility.CalamityMod.GetBuff("Fox").Description.AddTranslation(GameCulture.Russian,"Питомец лиса? ПИТОМЕЦ ЛИСА");
			ModCompatibility.CalamityMod.GetBuff("FurtasticDuoBuff").DisplayName.AddTranslation(GameCulture.Russian,"Пушистический дуэт");
			ModCompatibility.CalamityMod.GetBuff("FurtasticDuoBuff").Description.AddTranslation(GameCulture.Russian,"Они только что сделали это! Пушистический дуэт будет сопровождать вас!");
			ModCompatibility.CalamityMod.GetBuff("Kendra").DisplayName.AddTranslation(GameCulture.Russian,"Кендра");
			ModCompatibility.CalamityMod.GetBuff("Kendra").Description.AddTranslation(GameCulture.Russian,"Верный друг сопровождает вас");
            ModCompatibility.CalamityMod.GetBuff("LadBuff").DisplayName.AddTranslation(GameCulture.Russian, "Отец");
            ModCompatibility.CalamityMod.GetBuff("LadBuff").Description.AddTranslation(GameCulture.Russian, "Отец многих парит вокруг вас");
			ModCompatibility.CalamityMod.GetBuff("LeviBuff").DisplayName.AddTranslation(GameCulture.Russian,"Леви");
			ModCompatibility.CalamityMod.GetBuff("LeviBuff").Description.AddTranslation(GameCulture.Russian,"Маленькая и милая");
			ModCompatibility.CalamityMod.GetBuff("PlaguebringerBabBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленькая Разносчица чумы");
			ModCompatibility.CalamityMod.GetBuff("PlaguebringerBabBuff").Description.AddTranslation(GameCulture.Russian,"Маленькая Разносчица чумы видит вас как королеву");
			ModCompatibility.CalamityMod.GetBuff("RadiatorBuff").DisplayName.AddTranslation(GameCulture.Russian,"Излучатель");
			ModCompatibility.CalamityMod.GetBuff("RadiatorBuff").Description.AddTranslation(GameCulture.Russian,"Радиоактивный, но очаровательный");
			ModCompatibility.CalamityMod.GetBuff("RotomBuff").DisplayName.AddTranslation(GameCulture.Russian,"Электрический баламут");
			ModCompatibility.CalamityMod.GetBuff("RotomBuff").Description.AddTranslation(GameCulture.Russian,"Молния никогда не ударяет дважды в одно и то же место");
			ModCompatibility.CalamityMod.GetBuff("SCalPetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Высшая Каламитас");
			ModCompatibility.CalamityMod.GetBuff("SCalPetBuff").Description.AddTranslation(GameCulture.Russian,"Наблюдая за вами с величайшей катастрофической энергией... Как очаровательно");
			ModCompatibility.CalamityMod.GetBuff("SirenLightPetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Дух океана");
			ModCompatibility.CalamityMod.GetBuff("SirenLightPetBuff").Description.AddTranslation(GameCulture.Russian,"Маленькая и милая");
			ModCompatibility.CalamityMod.GetBuff("SparksBuff").DisplayName.AddTranslation(GameCulture.Russian,"Спаркс");
			ModCompatibility.CalamityMod.GetBuff("SparksBuff").Description.AddTranslation(GameCulture.Russian,"Кушает бабочек");
			ModCompatibility.CalamityMod.GetBuff("ThirdSageBuff").DisplayName.AddTranslation(GameCulture.Russian,"Третий Мудрец");
			ModCompatibility.CalamityMod.GetBuff("ThirdSageBuff").Description.AddTranslation(GameCulture.Russian,"А? Не может быть, чтобы это было демоном");
// ==================================================================================================================
					// Placeables
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("BlueSpeedCandle").DisplayName.AddTranslation(GameCulture.Russian,"Гибкий");
			ModCompatibility.CalamityMod.GetBuff("BlueSpeedCandle").Description.AddTranslation(GameCulture.Russian,"Плавающее пламя поднимает настроение");
			ModCompatibility.CalamityMod.GetBuff("ChaosCandleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Свеча хаоса");
			ModCompatibility.CalamityMod.GetBuff("ChaosCandleBuff").Description.AddTranslation(GameCulture.Russian,"Скорость появления врагов вокруг свечи увеличена!");
			ModCompatibility.CalamityMod.GetBuff("CorruptionEffigyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Чучело искажения");
			ModCompatibility.CalamityMod.GetBuff("CorruptionEffigyBuff").Description.AddTranslation(GameCulture.Russian,"Искажение наделяет вас силой");
			ModCompatibility.CalamityMod.GetBuff("CrimsonEffigyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Чучело багрянца");
			ModCompatibility.CalamityMod.GetBuff("CrimsonEffigyBuff").Description.AddTranslation(GameCulture.Russian,"Багрянец наделяет вас силой");
			ModCompatibility.CalamityMod.GetBuff("EffigyOfDecayBuff").DisplayName.AddTranslation(GameCulture.Russian,"Чучело разложения");
			ModCompatibility.CalamityMod.GetBuff("EffigyOfDecayBuff").Description.AddTranslation(GameCulture.Russian,"Сернистые воды наделяют вас силой");
			ModCompatibility.CalamityMod.GetBuff("PinkHealthCandle").DisplayName.AddTranslation(GameCulture.Russian,"Энергия");
			ModCompatibility.CalamityMod.GetBuff("PinkHealthCandle").Description.AddTranslation(GameCulture.Russian,"Его яркий свет наполняет окружающих надеждой");
			ModCompatibility.CalamityMod.GetBuff("PurpleDefenseCandle").DisplayName.AddTranslation(GameCulture.Russian,"Несокрушимость");
			ModCompatibility.CalamityMod.GetBuff("PurpleDefenseCandle").Description.AddTranslation(GameCulture.Russian,"Ни дождь, ни ветер не могут погасить его вечное пламя");
			ModCompatibility.CalamityMod.GetBuff("TranquilityCandleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Свеча успокоения");
			ModCompatibility.CalamityMod.GetBuff("TranquilityCandleBuff").Description.AddTranslation(GameCulture.Russian,"Скорость появления врагов вокруг свечи снижена!");
			ModCompatibility.CalamityMod.GetBuff("YellowDamageCandle").DisplayName.AddTranslation(GameCulture.Russian,"Злоба");
			ModCompatibility.CalamityMod.GetBuff("YellowDamageCandle").Description.AddTranslation(GameCulture.Russian,"Его ненавистное свечение мерцает от ярости");
// ==================================================================================================================
					// Potions
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AbyssalWeapon").DisplayName.AddTranslation(GameCulture.Russian,"Оружие бездны");
			ModCompatibility.CalamityMod.GetBuff("AbyssalWeapon").Description.AddTranslation(GameCulture.Russian,"Оружие ближнего боя накладывает «Огонь бездны», скорость передвижения увеличена на 15%");
			ModCompatibility.CalamityMod.GetBuff("AnechoicCoatingBuff").DisplayName.AddTranslation(GameCulture.Russian,"Безэховая краска");
			ModCompatibility.CalamityMod.GetBuff("AnechoicCoatingBuff").Description.AddTranslation(GameCulture.Russian,"Радиус обнаружения у существ бездны снижен");
			ModCompatibility.CalamityMod.GetBuff("ArmorCrumbling").DisplayName.AddTranslation(GameCulture.Russian,"Разрушение брони");
			ModCompatibility.CalamityMod.GetBuff("ArmorCrumbling").Description.AddTranslation(GameCulture.Russian,"Ближние и разбойные атаки разрушают броню врага");
			ModCompatibility.CalamityMod.GetBuff("ArmorShattering").DisplayName.AddTranslation(GameCulture.Russian,"Сокрушение брони");
			ModCompatibility.CalamityMod.GetBuff("ArmorShattering").Description.AddTranslation(GameCulture.Russian,"Ближние и разбойные атаки разрушают броню врага");
			ModCompatibility.CalamityMod.GetBuff("AstralInjectionBuff").DisplayName.AddTranslation(GameCulture.Russian,"Астральная инъекция");
			ModCompatibility.CalamityMod.GetBuff("AstralInjectionBuff").Description.AddTranslation(GameCulture.Russian,"Экстремальное восстановление маны");
			ModCompatibility.CalamityMod.GetBuff("BaguetteBuff").DisplayName.AddTranslation(GameCulture.Russian,"Багет");
			ModCompatibility.CalamityMod.GetBuff("BaguetteBuff").Description.AddTranslation(GameCulture.Russian,"Если бы я только знала... ~Циррус");
			ModCompatibility.CalamityMod.GetBuff("BloodfinBoost").DisplayName.AddTranslation(GameCulture.Russian,"Усиление кровавого плавника");
			ModCompatibility.CalamityMod.GetBuff("BloodfinBoost").Description.AddTranslation(GameCulture.Russian,"Не позволяй крови попасть вам в голову");
			ModCompatibility.CalamityMod.GetBuff("BoundingBuff").DisplayName.AddTranslation(GameCulture.Russian,"Прыгучесть");
			ModCompatibility.CalamityMod.GetBuff("BoundingBuff").Description.AddTranslation(GameCulture.Russian,"Высота прыжка и скорость прыжка увеличены, сопротивление к урону от падения");
			ModCompatibility.CalamityMod.GetBuff("Cadence").DisplayName.AddTranslation(GameCulture.Russian,"Ритм");
			ModCompatibility.CalamityMod.GetBuff("Cadence").Description.AddTranslation(GameCulture.Russian,"Ваше сердце чисто");
			ModCompatibility.CalamityMod.GetBuff("CalciumBuff").DisplayName.AddTranslation(GameCulture.Russian,"Кальций");
			ModCompatibility.CalamityMod.GetBuff("CalciumBuff").Description.AddTranslation(GameCulture.Russian,"Вы невосприимчивы к урону от падения");
			ModCompatibility.CalamityMod.GetBuff("CeaselessHunger").DisplayName.AddTranslation(GameCulture.Russian,"Нескончаемый голод");
			ModCompatibility.CalamityMod.GetBuff("CeaselessHunger").Description.AddTranslation(GameCulture.Russian,"Вы поглощаете все предметы");
			ModCompatibility.CalamityMod.GetBuff("DraconicSurgeBuff").DisplayName.AddTranslation(GameCulture.Russian,"Драконий всплеск");
			ModCompatibility.CalamityMod.GetBuff("DraconicSurgeBuff").Description.AddTranslation(GameCulture.Russian,"Сила дракона течёт в ваших жилах");
			ModCompatibility.CalamityMod.GetBuff("GravityNormalizerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Нормализация гравитации");
			ModCompatibility.CalamityMod.GetBuff("GravityNormalizerBuff").Description.AddTranslation(GameCulture.Russian,"Гравитация в космосе нормализована, невосприимчивость к «Искажению»");
			ModCompatibility.CalamityMod.GetBuff("HolyWrathBuff").DisplayName.AddTranslation(GameCulture.Russian,"Священный гнев");
			ModCompatibility.CalamityMod.GetBuff("HolyWrathBuff").Description.AddTranslation(GameCulture.Russian,"Урон, скорость передвижения и время полёта увеличены; все атаки накладывают «Святые огни»");
			ModCompatibility.CalamityMod.GetBuff("Invincible").DisplayName.AddTranslation(GameCulture.Russian,"Неуязвимый");
			ModCompatibility.CalamityMod.GetBuff("Invincible").Description.AddTranslation(GameCulture.Russian,"Неуязвимость к урону и большинству дебаффов");
			ModCompatibility.CalamityMod.GetBuff("Omniscience").DisplayName.AddTranslation(GameCulture.Russian,"Всеведение");
			ModCompatibility.CalamityMod.GetBuff("Omniscience").Description.AddTranslation(GameCulture.Russian,"Вы можете видеть всё");
			ModCompatibility.CalamityMod.GetBuff("PenumbraBuff").DisplayName.AddTranslation(GameCulture.Russian,"Полутень");
			ModCompatibility.CalamityMod.GetBuff("PenumbraBuff").Description.AddTranslation(GameCulture.Russian,"Скрытность восстанавливается на 15% быстрее во время движения\nНочью, скрытность дополнительно восстанавливается на 15% быстрее пока вы стоите на месте\nОба показателя увеличиваются до 20% во время Солнечного затмения");
			ModCompatibility.CalamityMod.GetBuff("PhotosynthesisBuff").DisplayName.AddTranslation(GameCulture.Russian,"Фотосинтез");
			ModCompatibility.CalamityMod.GetBuff("PhotosynthesisBuff").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья ускорена, сильнее в дневное время, сердца восстанавливают больше здоровья");
			ModCompatibility.CalamityMod.GetBuff("ProfanedRageBuff").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённая ярость");
			ModCompatibility.CalamityMod.GetBuff("ProfanedRageBuff").Description.AddTranslation(GameCulture.Russian,"Шанс критического удара, скорость передвижения и время полёта увеличены, вы получаете больше ярости при получение урона");
			ModCompatibility.CalamityMod.GetBuff("Revivify").DisplayName.AddTranslation(GameCulture.Russian,"Возрождение");
			ModCompatibility.CalamityMod.GetBuff("Revivify").Description.AddTranslation(GameCulture.Russian,"Вы исцеляетесь на часть урона, который вы получили");
			ModCompatibility.CalamityMod.GetBuff("ShadowBuff").DisplayName.AddTranslation(GameCulture.Russian,"Тень");
			ModCompatibility.CalamityMod.GetBuff("ShadowBuff").Description.AddTranslation(GameCulture.Russian,"Вы невидимы, некоторые разбойные оружия дают и получают усиления, скорость восстановления скрытности увеличено");
			ModCompatibility.CalamityMod.GetBuff("Soaring").DisplayName.AddTranslation(GameCulture.Russian,"Парение");
			ModCompatibility.CalamityMod.GetBuff("Soaring").Description.AddTranslation(GameCulture.Russian,"Время полёта крыльев и скорость увеличены\nИстинные удары ближнего боя восстанавливают время полёта крыльев");
			ModCompatibility.CalamityMod.GetBuff("SulphurskinBuff").DisplayName.AddTranslation(GameCulture.Russian,"Сернистая кожа");
			ModCompatibility.CalamityMod.GetBuff("SulphurskinBuff").Description.AddTranslation(GameCulture.Russian,"Сернистые воды оказывают на вас меньшее воздействие");
			ModCompatibility.CalamityMod.GetBuff("TeslaBuff").DisplayName.AddTranslation(GameCulture.Russian,"Электричество Теслы");
			ModCompatibility.CalamityMod.GetBuff("TeslaBuff").Description.AddTranslation(GameCulture.Russian,"Вызывает ауру электричества");
			ModCompatibility.CalamityMod.GetBuff("TitanScale").DisplayName.AddTranslation(GameCulture.Russian,"Титановая чешуя");
			ModCompatibility.CalamityMod.GetBuff("TitanScale").Description.AddTranslation(GameCulture.Russian,"Вы чувствуете себя танком");
			ModCompatibility.CalamityMod.GetBuff("TriumphBuff").DisplayName.AddTranslation(GameCulture.Russian,"Триумф");
			ModCompatibility.CalamityMod.GetBuff("TriumphBuff").Description.AddTranslation(GameCulture.Russian,"Контактный урон от врага снижен, чем меньше здоровье врага, тем больше сокращение");
			ModCompatibility.CalamityMod.GetBuff("YharimPower").DisplayName.AddTranslation(GameCulture.Russian,"Сила Ярима");
			ModCompatibility.CalamityMod.GetBuff("YharimPower").Description.AddTranslation(GameCulture.Russian,"Вы чувствуете, что можете разбить мир пополам... своими голыми руками!");
			ModCompatibility.CalamityMod.GetBuff("Zen").DisplayName.AddTranslation(GameCulture.Russian,"Дзен");
			ModCompatibility.CalamityMod.GetBuff("Zen").Description.AddTranslation(GameCulture.Russian,"Скорость появления врагов снижена");
			ModCompatibility.CalamityMod.GetBuff("Zerg").DisplayName.AddTranslation(GameCulture.Russian,"Зерг");
			ModCompatibility.CalamityMod.GetBuff("Zerg").Description.AddTranslation(GameCulture.Russian,"Скорость появления врагов увеличена");
// ==================================================================================================================
					// StatBuffs
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AbsoluteRage").DisplayName.AddTranslation(GameCulture.Russian,"Абсолютная ярость");
			ModCompatibility.CalamityMod.GetBuff("AbsoluteRage").Description.AddTranslation(GameCulture.Russian,"Гнев ожесточает сердце. Максимальный запас здоровья увеличен на 5%");
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitBuff").DisplayName.AddTranslation(GameCulture.Russian,"Глубоководный водолазный костюм");
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitBuff").Description.AddTranslation(GameCulture.Russian,"Вы сделаны из металла");
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitPlates").DisplayName.AddTranslation(GameCulture.Russian,"Пластины глубоководного водолазного костюма");
			ModCompatibility.CalamityMod.GetBuff("AbyssalDivingSuitPlates").Description.AddTranslation(GameCulture.Russian,"Пластины будут поглощать 15% урона");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMadness").DisplayName.AddTranslation(GameCulture.Russian,"Безумие бездны");
			ModCompatibility.CalamityMod.GetBuff("AbyssalMadness").Description.AddTranslation(GameCulture.Russian,"Урон, шанс критического удара, и агрессивность/дистанция атаки щупалец увеличены");
			ModCompatibility.CalamityMod.GetBuff("AdrenalineMode").DisplayName.AddTranslation(GameCulture.Russian,"Режим адреналина");
			ModCompatibility.CalamityMod.GetBuff("AdrenalineMode").Description.AddTranslation(GameCulture.Russian,"Урон увеличен на 200%\nМожет быть увеличен другими предметами до 245%");
			ModCompatibility.CalamityMod.GetBuff("Afflicted").DisplayName.AddTranslation(GameCulture.Russian,"Страдающий");
			ModCompatibility.CalamityMod.GetBuff("Afflicted").Description.AddTranslation(GameCulture.Russian,"Усилен потусторонними духами");
			ModCompatibility.CalamityMod.GetBuff("AmidiasBlessing").DisplayName.AddTranslation(GameCulture.Russian,"Благословение Амидиаса");
			ModCompatibility.CalamityMod.GetBuff("AmidiasBlessing").Description.AddTranslation(GameCulture.Russian,"Амидиас благословил вас\nПозволяет дышать под водой, даже в бездне!\nПросто не получи удар...");
			ModCompatibility.CalamityMod.GetBuff("BloodflareBloodFrenzy").DisplayName.AddTranslation(GameCulture.Russian,"Кровавое неистовство");
			ModCompatibility.CalamityMod.GetBuff("BloodflareBloodFrenzy").Description.AddTranslation(GameCulture.Russian,"Контактный урон снижен и характеристики ближнего боя значительно увеличены");
			ModCompatibility.CalamityMod.GetBuff("BloodyBoost").DisplayName.AddTranslation(GameCulture.Russian,"Кровавое усиление");
			ModCompatibility.CalamityMod.GetBuff("BloodyBoost").Description.AddTranslation(GameCulture.Russian,"Атакующие и защитные характеристики увеличены\nЛечебные зелья даруют больше здоровья");
			ModCompatibility.CalamityMod.GetBuff("BossZen").DisplayName.AddTranslation(GameCulture.Russian,"Босс Дзен");
			ModCompatibility.CalamityMod.GetBuff("BossZen").Description.AddTranslation(GameCulture.Russian,"Активный босс снижает скорость появления...намного");
			ModCompatibility.CalamityMod.GetBuff("BrimflameFrenzyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Серное неистовство");
			ModCompatibility.CalamityMod.GetBuff("BrimflameFrenzyBuff").Description.AddTranslation(GameCulture.Russian,"Тёмная магия усиливает ваши атаки ценой вашей жизни");
			ModCompatibility.CalamityMod.GetBuff("ChiBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ци");
			ModCompatibility.CalamityMod.GetBuff("ChiBuff").Description.AddTranslation(GameCulture.Russian,"Ваша следующая атака усилена и вы более устойчивы к урону");
			ModCompatibility.CalamityMod.GetBuff("CosmicFreeze").DisplayName.AddTranslation(GameCulture.Russian,"Космическая заморозка");
			ModCompatibility.CalamityMod.GetBuff("CosmicFreeze").Description.AddTranslation(GameCulture.Russian,"Вы чувствуете себя так же холодно, как пустое пространство космоса");
			ModCompatibility.CalamityMod.GetBuff("ElysianGuard").DisplayName.AddTranslation(GameCulture.Russian,"Неземной страж");
			ModCompatibility.CalamityMod.GetBuff("ElysianGuard").Description.AddTranslation(GameCulture.Russian,"Скорость передвижения снижена, остальные характеристики усилены");
			ModCompatibility.CalamityMod.GetBuff("Encased").DisplayName.AddTranslation(GameCulture.Russian,"Заключён");
			ModCompatibility.CalamityMod.GetBuff("Encased").Description.AddTranslation(GameCulture.Russian,"Защита увеличена на 30 и сопротивление урону на 30%, но...");
			ModCompatibility.CalamityMod.GetBuff("EvasionScarfBoost").DisplayName.AddTranslation(GameCulture.Russian,"Усиление избегающего шарфа");
			ModCompatibility.CalamityMod.GetBuff("EvasionScarfBoost").Description.AddTranslation(GameCulture.Russian,"Урон и шанс критического удара увеличены на 10%, и скорость атаки ближнего боя на 15%");
			ModCompatibility.CalamityMod.GetBuff("GraxDefense").DisplayName.AddTranslation(GameCulture.Russian,"Усиление Гракса");
			ModCompatibility.CalamityMod.GetBuff("GraxDefense").Description.AddTranslation(GameCulture.Russian,"Ваша защита и мышцы сильны");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneAtkBuff").DisplayName.AddTranslation(GameCulture.Russian,"Святая сила");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneAtkBuff").Description.AddTranslation(GameCulture.Russian,"Урон миньонов увеличен на 15%");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneDefBuff").DisplayName.AddTranslation(GameCulture.Russian,"Святая защита");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneDefBuff").Description.AddTranslation(GameCulture.Russian,"Защита увеличена на 7 и сопротивление урону на 7%");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneRegenBuff").DisplayName.AddTranslation(GameCulture.Russian,"Святая регенерация");
			ModCompatibility.CalamityMod.GetBuff("HallowedRuneRegenBuff").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья");
			ModCompatibility.CalamityMod.GetBuff("IceShieldBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ледяной щит");
			ModCompatibility.CalamityMod.GetBuff("IceShieldBuff").Description.AddTranslation(GameCulture.Russian,"Поглощает 20% урона от следующего полученного вами удара, затем разрушается");
			ModCompatibility.CalamityMod.GetBuff("KamiBuff").DisplayName.AddTranslation(GameCulture.Russian,"Инъекция Ками");
			ModCompatibility.CalamityMod.GetBuff("KamiBuff").Description.AddTranslation(GameCulture.Russian,"Скорость передвижения и урон увеличены");
			ModCompatibility.CalamityMod.GetBuff("Molten").DisplayName.AddTranslation(GameCulture.Russian,"Расплавленный");
			ModCompatibility.CalamityMod.GetBuff("Molten").Description.AddTranslation(GameCulture.Russian,"Сопротивление к эффектам холода");
			ModCompatibility.CalamityMod.GetBuff("Mushy").DisplayName.AddTranslation(GameCulture.Russian,"Слащавый");
			ModCompatibility.CalamityMod.GetBuff("Mushy").Description.AddTranslation(GameCulture.Russian,"Защита и регенерация здоровья увеличены");
			ModCompatibility.CalamityMod.GetBuff("PolarisBuff").DisplayName.AddTranslation(GameCulture.Russian,"Полярное усиление");
			ModCompatibility.CalamityMod.GetBuff("PolarisBuff").Description.AddTranslation(GameCulture.Russian,"Полярная звезда усиливает ваше оружие");
			ModCompatibility.CalamityMod.GetBuff("ProfanedCrystalBuff").DisplayName.AddTranslation(GameCulture.Russian,"Преданность");
			ModCompatibility.CalamityMod.GetBuff("ProfanedCrystalBuff").Description.AddTranslation(GameCulture.Russian,"Осквернённая душа внутри была осквернена могущественной магией высшей ведьмы");
			ModCompatibility.CalamityMod.GetBuff("RageMode").DisplayName.AddTranslation(GameCulture.Russian,"Режим ярости");
			ModCompatibility.CalamityMod.GetBuff("RageMode").Description.AddTranslation(GameCulture.Russian,"Урон увеличен на 50%. Может быть увеличен другими предметами до 110%");
			ModCompatibility.CalamityMod.GetBuff("ReaverRage").DisplayName.AddTranslation(GameCulture.Russian,"Ярость Разорителя");
			ModCompatibility.CalamityMod.GetBuff("ReaverRage").Description.AddTranslation(GameCulture.Russian,"Вы злой");
			ModCompatibility.CalamityMod.GetBuff("ScarfMeleeBoost").DisplayName.AddTranslation(GameCulture.Russian,"Усиление шарфа");
			ModCompatibility.CalamityMod.GetBuff("ScarfMeleeBoost").Description.AddTranslation(GameCulture.Russian,"Урон увеличен на 10%, шанс критического удара на 5%, и скорость атаки ближнего боя на 5%");
			ModCompatibility.CalamityMod.GetBuff("ShellBoost").DisplayName.AddTranslation(GameCulture.Russian,"Ракушечное повышение скорости");
			ModCompatibility.CalamityMod.GetBuff("ShellBoost").Description.AddTranslation(GameCulture.Russian,"Скорость увеличена");
			ModCompatibility.CalamityMod.GetBuff("SilvaRevival").DisplayName.AddTranslation(GameCulture.Russian,"Неуязвимость леса");
			ModCompatibility.CalamityMod.GetBuff("SilvaRevival").Description.AddTranslation(GameCulture.Russian,"Вы неуязвимы");
			ModCompatibility.CalamityMod.GetBuff("SirenBobs").DisplayName.AddTranslation(GameCulture.Russian,"Водный элементаль");
			ModCompatibility.CalamityMod.GetBuff("SirenBobs").Description.AddTranslation(GameCulture.Russian,"Теперь вы водный элементаль");
			ModCompatibility.CalamityMod.GetBuff("SirenWaterSpeed").DisplayName.AddTranslation(GameCulture.Russian,"Благословение океана");
			ModCompatibility.CalamityMod.GetBuff("SirenWaterSpeed").Description.AddTranslation(GameCulture.Russian,"Максимальная скорость передвижения и ускорение увеличены на 15%");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorAtkBuff").DisplayName.AddTranslation(GameCulture.Russian,"Духовная сила");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorAtkBuff").Description.AddTranslation(GameCulture.Russian,"Урон миньонов увеличен на 10%");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorDefBuff").DisplayName.AddTranslation(GameCulture.Russian,"Духовная защита");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorDefBuff").Description.AddTranslation(GameCulture.Russian,"Защита увеличена на 5 и сопротивление урону на 5%");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorRegenBuff").DisplayName.AddTranslation(GameCulture.Russian,"Духовная регенерация");
			ModCompatibility.CalamityMod.GetBuff("SpiritGeneratorRegenBuff").Description.AddTranslation(GameCulture.Russian,"Регенерация здоровья");
			ModCompatibility.CalamityMod.GetBuff("TarragonCloak").DisplayName.AddTranslation(GameCulture.Russian,"Плащ Таррагона");
			ModCompatibility.CalamityMod.GetBuff("TarragonCloak").Description.AddTranslation(GameCulture.Russian,"Контактный урон снижен");
			ModCompatibility.CalamityMod.GetBuff("TarragonImmunity").DisplayName.AddTranslation(GameCulture.Russian,"Неуязвимость Таррагона");
			ModCompatibility.CalamityMod.GetBuff("TarragonImmunity").Description.AddTranslation(GameCulture.Russian,"Вы неуязвимы");
			ModCompatibility.CalamityMod.GetBuff("TarraLifeRegen").DisplayName.AddTranslation(GameCulture.Russian,"Тарра жизнь");
			ModCompatibility.CalamityMod.GetBuff("TarraLifeRegen").Description.AddTranslation(GameCulture.Russian,"Быстрое исцеление");
			ModCompatibility.CalamityMod.GetBuff("TyrantsFury").DisplayName.AddTranslation(GameCulture.Russian,"Бешенство Тирана");
			ModCompatibility.CalamityMod.GetBuff("TyrantsFury").Description.AddTranslation(GameCulture.Russian,"Урон ближнего боя увеличен на 30% и шанс критического удара на 10%");
			ModCompatibility.CalamityMod.GetBuff("XerocRage").DisplayName.AddTranslation(GameCulture.Russian,"Неземная ярость");
			ModCompatibility.CalamityMod.GetBuff("XerocRage").Description.AddTranslation(GameCulture.Russian,"Ярость космоса");
			ModCompatibility.CalamityMod.GetBuff("XerocWrath").DisplayName.AddTranslation(GameCulture.Russian,"Неземной гнев");
			ModCompatibility.CalamityMod.GetBuff("XerocWrath").Description.AddTranslation(GameCulture.Russian,"Гнев космоса");
// ==================================================================================================================
					// StatDebuffs
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AndromedaCripple").DisplayName.AddTranslation(GameCulture.Russian,"Неполадки Андромеды");
			ModCompatibility.CalamityMod.GetBuff("AndromedaCripple").Description.AddTranslation(GameCulture.Russian,"Вы медленные");
			ModCompatibility.CalamityMod.GetBuff("ArmorCrunch").DisplayName.AddTranslation(GameCulture.Russian,"Треск брони");
			ModCompatibility.CalamityMod.GetBuff("ArmorCrunch").Description.AddTranslation(GameCulture.Russian,"Ваша броня разнесена в клочья");
			ModCompatibility.CalamityMod.GetBuff("BurntOut").DisplayName.AddTranslation(GameCulture.Russian,"Сгоревший");
			ModCompatibility.CalamityMod.GetBuff("BurntOut").Description.AddTranslation(GameCulture.Russian,"Вы сгорели, а ваши стражи менее эффективны");
			ModCompatibility.CalamityMod.GetBuff("Clamity").DisplayName.AddTranslation(GameCulture.Russian,"Кламити");
			ModCompatibility.CalamityMod.GetBuff("Clamity").Description.AddTranslation(GameCulture.Russian,"Моллюски были разозлены!");
			ModCompatibility.CalamityMod.GetBuff("DeathModeCold").DisplayName.AddTranslation(GameCulture.Russian,"Морозящая погода");
			ModCompatibility.CalamityMod.GetBuff("DeathModeCold").Description.AddTranslation(GameCulture.Russian,"Погода замедляет ваше передвижение, когда вы замерзаете до смерти. Вам нужно искать экипировку, которая защитит вас от холода");
			ModCompatibility.CalamityMod.GetBuff("DeathModeHot").DisplayName.AddTranslation(GameCulture.Russian,"Перегрев");
			ModCompatibility.CalamityMod.GetBuff("DeathModeHot").Description.AddTranslation(GameCulture.Russian,"Непреодолимая жара ослабляет функции вашего тела. Вам нужно искать экипировку, которая защитит вас от жары");
			ModCompatibility.CalamityMod.GetBuff("Enraged").DisplayName.AddTranslation(GameCulture.Russian,"Разъярённый");
			ModCompatibility.CalamityMod.GetBuff("Enraged").Description.AddTranslation(GameCulture.Russian,"Весь получаемый урон увеличен на 25%");
			ModCompatibility.CalamityMod.GetBuff("Eutrophication").DisplayName.AddTranslation(GameCulture.Russian,"Эвтрофикация");
			ModCompatibility.CalamityMod.GetBuff("Eutrophication").Description.AddTranslation(GameCulture.Russian,"Чрезмерное количество питательных веществ ограничивает ваше передвижение");
			ModCompatibility.CalamityMod.GetBuff("ExoFreeze").DisplayName.AddTranslation(GameCulture.Russian,"Экзо заморозка");
			ModCompatibility.CalamityMod.GetBuff("ExoFreeze").Description.AddTranslation(GameCulture.Russian,"Не можете двигаться");
			ModCompatibility.CalamityMod.GetBuff("ExtremeGrav").DisplayName.AddTranslation(GameCulture.Russian,"Экстремальная гравитация");
			ModCompatibility.CalamityMod.GetBuff("ExtremeGrav").Description.AddTranslation(GameCulture.Russian,"Ваше время полёта снижено на 50%, а бесконечный полёт отключён");
			ModCompatibility.CalamityMod.GetBuff("ExtremeGravity").DisplayName.AddTranslation(GameCulture.Russian,"Безумие Икара");
			ModCompatibility.CalamityMod.GetBuff("ExtremeGravity").Description.AddTranslation(GameCulture.Russian,"Время полёта снижено на 75%, а бесконечный полёт отключён");
			ModCompatibility.CalamityMod.GetBuff("FishAlert").DisplayName.AddTranslation(GameCulture.Russian,"Рыбья тревога");
			ModCompatibility.CalamityMod.GetBuff("FishAlert").Description.AddTranslation(GameCulture.Russian,"Существа бездны заметили вас!");
			ModCompatibility.CalamityMod.GetBuff("FrozenLungs").DisplayName.AddTranslation(GameCulture.Russian,"Замороженные лёгкие");
			ModCompatibility.CalamityMod.GetBuff("FrozenLungs").Description.AddTranslation(GameCulture.Russian,"Ледяные воды ограничивают ваше дыхание");
			ModCompatibility.CalamityMod.GetBuff("GlacialState").DisplayName.AddTranslation(GameCulture.Russian,"Ледниковое состояние");
			ModCompatibility.CalamityMod.GetBuff("GlacialState").Description.AddTranslation(GameCulture.Russian,"Не можете двигаться и защита разрушена");
			ModCompatibility.CalamityMod.GetBuff("Irradiated").DisplayName.AddTranslation(GameCulture.Russian,"Облучённый");
			ModCompatibility.CalamityMod.GetBuff("Irradiated").Description.AddTranslation(GameCulture.Russian,"Ваша кожа горит");
			ModCompatibility.CalamityMod.GetBuff("KamiDebuff").DisplayName.AddTranslation(GameCulture.Russian,"Грипп Ками");
			ModCompatibility.CalamityMod.GetBuff("KamiDebuff").Description.AddTranslation(GameCulture.Russian,"Беззащитный и умирающий");
			ModCompatibility.CalamityMod.GetBuff("MarkedforDeath").DisplayName.AddTranslation(GameCulture.Russian,"Отмеченный");
			ModCompatibility.CalamityMod.GetBuff("MarkedforDeath").Description.AddTranslation(GameCulture.Russian,"Сопротивление урону снижено");
			ModCompatibility.CalamityMod.GetBuff("PearlAura").DisplayName.AddTranslation(GameCulture.Russian,"Жемчужная аура");
			ModCompatibility.CalamityMod.GetBuff("PearlAura").Description.AddTranslation(GameCulture.Russian,"Замедлился");
            ModCompatibility.CalamityMod.GetBuff("ProfanedWeakness").DisplayName.AddTranslation(GameCulture.Russian, "Осквернённая слабость");
            ModCompatibility.CalamityMod.GetBuff("ProfanedWeakness").Description.AddTranslation(GameCulture.Russian, "Вы наносите меньше урона");
			ModCompatibility.CalamityMod.GetBuff("SilvaStun").DisplayName.AddTranslation(GameCulture.Russian,"Оглушение леса");
			ModCompatibility.CalamityMod.GetBuff("SilvaStun").Description.AddTranslation(GameCulture.Russian,"Не можете двигаться");
			ModCompatibility.CalamityMod.GetBuff("TemporalSadness").DisplayName.AddTranslation(GameCulture.Russian,"Временная грусть");
			ModCompatibility.CalamityMod.GetBuff("TemporalSadness").Description.AddTranslation(GameCulture.Russian,"Вы плачете");
			ModCompatibility.CalamityMod.GetBuff("TeslaFreeze").DisplayName.AddTranslation(GameCulture.Russian,"Гальваническая коррозия");
			ModCompatibility.CalamityMod.GetBuff("TeslaFreeze").Description.AddTranslation(GameCulture.Russian,"Ваши конечности начали ржаветь");
			ModCompatibility.CalamityMod.GetBuff("TimeSlow").DisplayName.AddTranslation(GameCulture.Russian,"Искажение времени");
			ModCompatibility.CalamityMod.GetBuff("TimeSlow").Description.AddTranslation(GameCulture.Russian,"Время замедлено");
			ModCompatibility.CalamityMod.GetBuff("WarCleave").DisplayName.AddTranslation(GameCulture.Russian,"Боевое рассечение");
			ModCompatibility.CalamityMod.GetBuff("WarCleave").Description.AddTranslation(GameCulture.Russian,"Защита и сопротивление снижены");
			ModCompatibility.CalamityMod.GetBuff("Warped").DisplayName.AddTranslation(GameCulture.Russian,"Деформирован");
			ModCompatibility.CalamityMod.GetBuff("Warped").Description.AddTranslation(GameCulture.Russian,"Движение деформируется");
			ModCompatibility.CalamityMod.GetBuff("WeakPetrification").DisplayName.AddTranslation(GameCulture.Russian,"Слабое окаменение");
			ModCompatibility.CalamityMod.GetBuff("WeakPetrification").Description.AddTranslation(GameCulture.Russian,"Ваше вертикальное передвижение ослаблено");
			ModCompatibility.CalamityMod.GetBuff("WhisperingDeath").DisplayName.AddTranslation(GameCulture.Russian,"Шепчущая смерть");
			ModCompatibility.CalamityMod.GetBuff("WhisperingDeath").Description.AddTranslation(GameCulture.Russian,"Приближается смерть; защита, сила атаки и регенерация здоровья снижены");
// ==================================================================================================================
					// Summon
// ==================================================================================================================
			ModCompatibility.CalamityMod.GetBuff("AerospecSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Валькирия");
			ModCompatibility.CalamityMod.GetBuff("AerospecSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Валькирия будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("ApexSharkBuff").DisplayName.AddTranslation(GameCulture.Russian,"Древняя ископаемая акула");
			ModCompatibility.CalamityMod.GetBuff("ApexSharkBuff").Description.AddTranslation(GameCulture.Russian,"Древняя, но такая опасная");
			ModCompatibility.CalamityMod.GetBuff("AquaticStar").DisplayName.AddTranslation(GameCulture.Russian,"Акватическая звезда");
			ModCompatibility.CalamityMod.GetBuff("AquaticStar").Description.AddTranslation(GameCulture.Russian,"Акватическая звезда будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("AstrageldonBuff").DisplayName.AddTranslation(GameCulture.Russian,"Астральное желе");
			ModCompatibility.CalamityMod.GetBuff("AstrageldonBuff").Description.AddTranslation(GameCulture.Russian,"Маленький слизень астрагельдона будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("AstralProbeBuff").DisplayName.AddTranslation(GameCulture.Russian,"Астральный зонд");
			ModCompatibility.CalamityMod.GetBuff("AstralProbeBuff").Description.AddTranslation(GameCulture.Russian,"Астральный зонд будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("AtaxiaSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Гидротермическое жерло");
			ModCompatibility.CalamityMod.GetBuff("AtaxiaSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Гидротермическое жерло будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("BelladonnaSpiritBuff").DisplayName.AddTranslation(GameCulture.Russian,"Дух белладонны");
			ModCompatibility.CalamityMod.GetBuff("BelladonnaSpiritBuff").Description.AddTranslation(GameCulture.Russian,"Милый лесной дух следует за вами");
			ModCompatibility.CalamityMod.GetBuff("BlackHawkBuff").DisplayName.AddTranslation(GameCulture.Russian,"Чёрный ястреб");
			ModCompatibility.CalamityMod.GetBuff("BlackHawkBuff").Description.AddTranslation(GameCulture.Russian,"Истребитель будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("BloodClot").DisplayName.AddTranslation(GameCulture.Russian,"Тромб");
			ModCompatibility.CalamityMod.GetBuff("BloodClot").Description.AddTranslation(GameCulture.Russian,"Тромб будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("BloodDragonsBuff").DisplayName.AddTranslation(GameCulture.Russian,"Драконы-скелеты");
			ModCompatibility.CalamityMod.GetBuff("BloodDragonsBuff").Description.AddTranslation(GameCulture.Russian,"Большая счастливая семья");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Серный элементаль");
			ModCompatibility.CalamityMod.GetBuff("BrimstoneWaifu").Description.AddTranslation(GameCulture.Russian,"Серный элементаль будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("BrittleStar").DisplayName.AddTranslation(GameCulture.Russian,"Хрупкая звезда");
			ModCompatibility.CalamityMod.GetBuff("BrittleStar").Description.AddTranslation(GameCulture.Russian,"Хрупкая звезда будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("Calamari").DisplayName.AddTranslation(GameCulture.Russian,"Кальмары");
			ModCompatibility.CalamityMod.GetBuff("Calamari").Description.AddTranslation(GameCulture.Russian,"Кальмар будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CalamitasEyes").DisplayName.AddTranslation(GameCulture.Russian,"Гибельные глаза");
			ModCompatibility.CalamityMod.GetBuff("CalamitasEyes").Description.AddTranslation(GameCulture.Russian,"Каламитас и её братья будут защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CausticStaffBuff").DisplayName.AddTranslation(GameCulture.Russian,"Едкий дракон");
			ModCompatibility.CalamityMod.GetBuff("CausticStaffBuff").Description.AddTranslation(GameCulture.Russian,"Маленький дракон джунглей следует за вами");
			ModCompatibility.CalamityMod.GetBuff("CinderBlossomBuff").DisplayName.AddTranslation(GameCulture.Russian,"Пепельный цветок");
			ModCompatibility.CalamityMod.GetBuff("CinderBlossomBuff").Description.AddTranslation(GameCulture.Russian,"Горячий, обжигающий цветок парит рядом с вами");
			ModCompatibility.CalamityMod.GetBuff("CloudyWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Облачный элементаль");
			ModCompatibility.CalamityMod.GetBuff("CloudyWaifu").Description.AddTranslation(GameCulture.Russian,"Облачный элементаль будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("ColdDivinityBuff").DisplayName.AddTranslation(GameCulture.Russian,"Холодная божественность");
			ModCompatibility.CalamityMod.GetBuff("ColdDivinityBuff").Description.AddTranslation(GameCulture.Russian,"Магия древнего ледяного замка помогает вам");
			ModCompatibility.CalamityMod.GetBuff("Corroslime").DisplayName.AddTranslation(GameCulture.Russian,"Искажённый слизень");
			ModCompatibility.CalamityMod.GetBuff("Corroslime").Description.AddTranslation(GameCulture.Russian,"Искажённый слизень будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CorvidHarbringerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ворон");
			ModCompatibility.CalamityMod.GetBuff("CorvidHarbringerBuff").Description.AddTranslation(GameCulture.Russian,"Могущественный ворон будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CosmicEnergy").DisplayName.AddTranslation(GameCulture.Russian,"Космическая энергия");
			ModCompatibility.CalamityMod.GetBuff("CosmicEnergy").Description.AddTranslation(GameCulture.Russian,"Космическая энергия будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CosmicViperEngineBuff").DisplayName.AddTranslation(GameCulture.Russian,"Космический Вайпер");
			ModCompatibility.CalamityMod.GetBuff("CosmicViperEngineBuff").Description.AddTranslation(GameCulture.Russian,"Космический боевой корабль будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("CosmilampBuff").DisplayName.AddTranslation(GameCulture.Russian,"Космилампа");
			ModCompatibility.CalamityMod.GetBuff("CosmilampBuff").Description.AddTranslation(GameCulture.Russian,"Космилампа будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("Crimslime").DisplayName.AddTranslation(GameCulture.Russian,"Багряный слизень");
			ModCompatibility.CalamityMod.GetBuff("Crimslime").Description.AddTranslation(GameCulture.Russian,"Багряный слизень будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("DaedalusSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Кристалл Дедала");
			ModCompatibility.CalamityMod.GetBuff("DaedalusSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Кристалл Дедала будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("DankCreeperBuff").DisplayName.AddTranslation(GameCulture.Russian,"Промозглый ползун");
			ModCompatibility.CalamityMod.GetBuff("DankCreeperBuff").Description.AddTranslation(GameCulture.Russian,"Промозглый ползун будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("DazzlingStabberBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ослепительный закалыватель");
			ModCompatibility.CalamityMod.GetBuff("DazzlingStabberBuff").Description.AddTranslation(GameCulture.Russian,"Будь настороже");
			ModCompatibility.CalamityMod.GetBuff("DemonshadeSetDevilBuff").DisplayName.AddTranslation(GameCulture.Russian,"Красный дьявол");
			ModCompatibility.CalamityMod.GetBuff("DemonshadeSetDevilBuff").Description.AddTranslation(GameCulture.Russian,"Красный дьявол будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("DormantBrimseekerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Серный искатель");
			ModCompatibility.CalamityMod.GetBuff("DormantBrimseekerBuff").Description.AddTranslation(GameCulture.Russian,"Ему что-то нужно от вас?");
			ModCompatibility.CalamityMod.GetBuff("ElementalAxeBuff").DisplayName.AddTranslation(GameCulture.Russian,"Элементальный топор");
			ModCompatibility.CalamityMod.GetBuff("ElementalAxeBuff").Description.AddTranslation(GameCulture.Russian,"Элементальный топор будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("EndoCooperBuff").DisplayName.AddTranslation(GameCulture.Russian,"Эндо Купер");
			ModCompatibility.CalamityMod.GetBuff("EndoCooperBuff").Description.AddTranslation(GameCulture.Russian,"Восходящий Купер будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("EndoHydraBuff").DisplayName.AddTranslation(GameCulture.Russian,"Эндогидра");
			ModCompatibility.CalamityMod.GetBuff("EndoHydraBuff").Description.AddTranslation(GameCulture.Russian,"Эндогидра будет защищать вас... по какой-то причине");
			ModCompatibility.CalamityMod.GetBuff("FrostBlossomBuff").DisplayName.AddTranslation(GameCulture.Russian,"Цветущий мороз");
			ModCompatibility.CalamityMod.GetBuff("FrostBlossomBuff").Description.AddTranslation(GameCulture.Russian,"Холодный, колючий цветок парит рядом с вами");
			ModCompatibility.CalamityMod.GetBuff("FuelCellBundleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленькая Разносчица чумы");
			ModCompatibility.CalamityMod.GetBuff("FuelCellBundleBuff").Description.AddTranslation(GameCulture.Russian,"Маленькая чумная пчёлка следует за вами");
			ModCompatibility.CalamityMod.GetBuff("FungalClumpBuff").DisplayName.AddTranslation(GameCulture.Russian,"Грибной комок");
			ModCompatibility.CalamityMod.GetBuff("FungalClumpBuff").Description.AddTranslation(GameCulture.Russian,"Грибной комок будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("GammaHeadBuff").DisplayName.AddTranslation(GameCulture.Russian,"Гамма гидра");
			ModCompatibility.CalamityMod.GetBuff("GammaHeadBuff").Description.AddTranslation(GameCulture.Russian,"...");
			ModCompatibility.CalamityMod.GetBuff("GastricBelcherBuff").DisplayName.AddTranslation(GameCulture.Russian,"Желудочная аберрация");
			ModCompatibility.CalamityMod.GetBuff("GastricBelcherBuff").Description.AddTranslation(GameCulture.Russian,"Акватическая аберрация будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("GladiatorSwords").DisplayName.AddTranslation(GameCulture.Russian,"Гладиаторские мечи");
			ModCompatibility.CalamityMod.GetBuff("GladiatorSwords").Description.AddTranslation(GameCulture.Russian,"Гладиаторские мечи будут защищать вас");
			ModCompatibility.CalamityMod.GetBuff("HauntedDishesBuff").DisplayName.AddTranslation(GameCulture.Russian,"Одержимые тарелки");
			ModCompatibility.CalamityMod.GetBuff("HauntedDishesBuff").Description.AddTranslation(GameCulture.Russian,"Одержимые тарелки будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("HermitCrab").DisplayName.AddTranslation(GameCulture.Russian,"Рак-отшельник");
			ModCompatibility.CalamityMod.GetBuff("HermitCrab").Description.AddTranslation(GameCulture.Russian,"Рак-отшельник будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("Herring").DisplayName.AddTranslation(GameCulture.Russian,"Селёдка");
			ModCompatibility.CalamityMod.GetBuff("Herring").Description.AddTranslation(GameCulture.Russian,"Селёдка будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("HotE").DisplayName.AddTranslation(GameCulture.Russian,"Сердце элементов");
			ModCompatibility.CalamityMod.GetBuff("HotE").Description.AddTranslation(GameCulture.Russian,"Все элементали будут защищать вас");
			ModCompatibility.CalamityMod.GetBuff("HowlTrio").DisplayName.AddTranslation(GameCulture.Russian,"Сердце Хаула");
			ModCompatibility.CalamityMod.GetBuff("HowlTrio").Description.AddTranslation(GameCulture.Russian,"Хаул защищает вас, Кальцифер освещает ваш путь, Пугало-Репка следует за вами");
			ModCompatibility.CalamityMod.GetBuff("IceClasper").DisplayName.AddTranslation(GameCulture.Russian,"Ледяной клещ");
			ModCompatibility.CalamityMod.GetBuff("IceClasper").Description.AddTranslation(GameCulture.Russian,"Ледяной клещ будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("IgneousExaltationBuff").DisplayName.AddTranslation(GameCulture.Russian,"Магматический клинок");
			ModCompatibility.CalamityMod.GetBuff("IgneousExaltationBuff").Description.AddTranslation(GameCulture.Russian,"Клинок вращается вокруг вас");
			ModCompatibility.CalamityMod.GetBuff("MagicHatBuff").DisplayName.AddTranslation(GameCulture.Russian,"Магическая шляпа");
			ModCompatibility.CalamityMod.GetBuff("MagicHatBuff").Description.AddTranslation(GameCulture.Russian,"Шляпа несёт вашу душу, связанную контрактом");
			ModCompatibility.CalamityMod.GetBuff("Mechworm").DisplayName.AddTranslation(GameCulture.Russian,"Механический червь");
			ModCompatibility.CalamityMod.GetBuff("Mechworm").Description.AddTranslation(GameCulture.Russian,"Механический червь будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("MidnightSunBuff").DisplayName.AddTranslation(GameCulture.Russian,"НЛО полуночного солнца");
			ModCompatibility.CalamityMod.GetBuff("MidnightSunBuff").Description.AddTranslation(GameCulture.Russian,"Странное НЛО наблюдает за вами и это ставит вас в неловкое положение");
			ModCompatibility.CalamityMod.GetBuff("MountedScannerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Смонтированный сканер");
			ModCompatibility.CalamityMod.GetBuff("MountedScannerBuff").Description.AddTranslation(GameCulture.Russian,"Могущественная техника окружает вас");
			ModCompatibility.CalamityMod.GetBuff("MutatedTruffleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький Старый Герцог");
			ModCompatibility.CalamityMod.GetBuff("MutatedTruffleBuff").Description.AddTranslation(GameCulture.Russian,"Юный Герцог будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("Phantom").DisplayName.AddTranslation(GameCulture.Russian,"Фантом");
			ModCompatibility.CalamityMod.GetBuff("Phantom").Description.AddTranslation(GameCulture.Russian,"Фантом будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("PlaguebringerSummonBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленькая разносчица чумы");
			ModCompatibility.CalamityMod.GetBuff("PlaguebringerSummonBuff").Description.AddTranslation(GameCulture.Russian,"Разносчица чумы будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("PlaguePrincessBuff").DisplayName.AddTranslation(GameCulture.Russian,"Вирили");
			ModCompatibility.CalamityMod.GetBuff("PlaguePrincessBuff").Description.AddTranslation(GameCulture.Russian,"Жаль, что вы не можете её обнять");
			ModCompatibility.CalamityMod.GetBuff("PlantationBuff").DisplayName.AddTranslation(GameCulture.Russian,"Плантация");
			ModCompatibility.CalamityMod.GetBuff("PlantationBuff").Description.AddTranslation(GameCulture.Russian,"Миниатюрная плантера будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("PoleWarperBuff").DisplayName.AddTranslation(GameCulture.Russian,"Деформатор полюса");
			ModCompatibility.CalamityMod.GetBuff("PoleWarperBuff").Description.AddTranslation(GameCulture.Russian,"Чувственные магниты притягиваются к вам");
			ModCompatibility.CalamityMod.GetBuff("ProfanedBabs").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённая душа");
			ModCompatibility.CalamityMod.GetBuff("ProfanedBabs").Description.AddTranslation(GameCulture.Russian,"Целитель исцелит ваши раны!");
			ModCompatibility.CalamityMod.GetBuff("RadiantResolutionBuff").DisplayName.AddTranslation(GameCulture.Russian,"Цикличная одержимость");
			ModCompatibility.CalamityMod.GetBuff("RadiantResolutionBuff").Description.AddTranslation(GameCulture.Russian,"Излучающая аура защищает вас");
			ModCompatibility.CalamityMod.GetBuff("ReaverSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Сфера Разорителя");
			ModCompatibility.CalamityMod.GetBuff("ReaverSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Сфера Разорителя будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("ResurrectionButterflyBuff").DisplayName.AddTranslation(GameCulture.Russian,"Бабочка воскрешения");
			ModCompatibility.CalamityMod.GetBuff("ResurrectionButterflyBuff").Description.AddTranslation(GameCulture.Russian,"Спи под цветущей вишней, красно-белая бабочка");
			ModCompatibility.CalamityMod.GetBuff("RustyDroneBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ржавый дрон");
			ModCompatibility.CalamityMod.GetBuff("RustyDroneBuff").Description.AddTranslation(GameCulture.Russian,"Жалкий хрупкий дрон наблюдает за вами");
			ModCompatibility.CalamityMod.GetBuff("Sandnado").DisplayName.AddTranslation(GameCulture.Russian,"Песчаный торнадо");
			ModCompatibility.CalamityMod.GetBuff("Sandnado").Description.AddTranslation(GameCulture.Russian,"Песчаный торнадо будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("SandyHealingWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Редкий песчаный элементаль");
			ModCompatibility.CalamityMod.GetBuff("SandyHealingWaifu").Description.AddTranslation(GameCulture.Russian,"Песчаный элементаль будет исцелять вас");
			ModCompatibility.CalamityMod.GetBuff("SandyWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Песчаный элементаль");
			ModCompatibility.CalamityMod.GetBuff("SandyWaifu").Description.AddTranslation(GameCulture.Russian,"Песчаный элементаль будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("ScabRipperBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький кровавый ползун");
			ModCompatibility.CalamityMod.GetBuff("ScabRipperBuff").Description.AddTranslation(GameCulture.Russian,"Маленький кровавый ползун будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("ShellfishBuff").DisplayName.AddTranslation(GameCulture.Russian,"Моллюск");
			ModCompatibility.CalamityMod.GetBuff("ShellfishBuff").Description.AddTranslation(GameCulture.Russian,"Моллюск будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("SilvaSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Лесной кристалл");
			ModCompatibility.CalamityMod.GetBuff("SilvaSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Кристалл будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("SiriusBuff").DisplayName.AddTranslation(GameCulture.Russian,"Сириус");
			ModCompatibility.CalamityMod.GetBuff("SiriusBuff").Description.AddTranslation(GameCulture.Russian,"Слишком яркий, но это помогает вам");
			ModCompatibility.CalamityMod.GetBuff("SnakeEyesBuff").DisplayName.AddTranslation(GameCulture.Russian,"Змеиные глаза");
			ModCompatibility.CalamityMod.GetBuff("SnakeEyesBuff").Description.AddTranslation(GameCulture.Russian,"Всегда наблюдает...");
			ModCompatibility.CalamityMod.GetBuff("SolarSpirit").DisplayName.AddTranslation(GameCulture.Russian,"Солнечный дух");
			ModCompatibility.CalamityMod.GetBuff("SolarSpirit").Description.AddTranslation(GameCulture.Russian,"Солнечный дух будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("SolarSpiritGod").DisplayName.AddTranslation(GameCulture.Russian,"Дух солнечного бога");
			ModCompatibility.CalamityMod.GetBuff("SolarSpiritGod").Description.AddTranslation(GameCulture.Russian,"Дух солнечного бога будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("SquirrelSquireBuff").DisplayName.AddTranslation(GameCulture.Russian,"Белка-оруженосец");
			ModCompatibility.CalamityMod.GetBuff("SquirrelSquireBuff").Description.AddTranslation(GameCulture.Russian,"Белка-оруженосец будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("StaffOfNecrosteocytesBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький скелет");
			ModCompatibility.CalamityMod.GetBuff("StaffOfNecrosteocytesBuff").Description.AddTranslation(GameCulture.Russian,"Скелет наблюдает за вами");
			ModCompatibility.CalamityMod.GetBuff("StarSwallowerBuff").DisplayName.AddTranslation(GameCulture.Russian,"Поглотитель звёзд");
			ModCompatibility.CalamityMod.GetBuff("StarSwallowerBuff").Description.AddTranslation(GameCulture.Russian,"Мммм мда");
			ModCompatibility.CalamityMod.GetBuff("StatigelSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький Бог слизней");
			ModCompatibility.CalamityMod.GetBuff("StatigelSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Бог слизней будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("StormjawBuff").DisplayName.AddTranslation(GameCulture.Russian,"Маленький Штормовой лев");
			ModCompatibility.CalamityMod.GetBuff("StormjawBuff").Description.AddTranslation(GameCulture.Russian,"Маленький Штормовой лев будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("TacticalPlagueEngineBuff").DisplayName.AddTranslation(GameCulture.Russian,"Тактический чумной двигатель");
			ModCompatibility.CalamityMod.GetBuff("TacticalPlagueEngineBuff").Description.AddTranslation(GameCulture.Russian,"Гигантский чумной истребитель следует за вами");
            ModCompatibility.CalamityMod.GetBuff("TundraFlameBlossomsBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пламенные цветки тундры");
            ModCompatibility.CalamityMod.GetBuff("TundraFlameBlossomsBuff").Description.AddTranslation(GameCulture.Russian, "Идеальный унисон равновесия и красоты");
			ModCompatibility.CalamityMod.GetBuff("VictideSummonSetBuff").DisplayName.AddTranslation(GameCulture.Russian,"Ёж");
			ModCompatibility.CalamityMod.GetBuff("VictideSummonSetBuff").Description.AddTranslation(GameCulture.Russian,"Ёж будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("VileFeederBuff").DisplayName.AddTranslation(GameCulture.Russian,"Гнусный кормилец");
			ModCompatibility.CalamityMod.GetBuff("VileFeederBuff").Description.AddTranslation(GameCulture.Russian,"Маленький пожиратель душ будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("WaterWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Анахита");
			ModCompatibility.CalamityMod.GetBuff("WaterWaifu").Description.AddTranslation(GameCulture.Russian,"Анахита будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("WulfrumDroidBuff").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый дроид");
			ModCompatibility.CalamityMod.GetBuff("WulfrumDroidBuff").Description.AddTranslation(GameCulture.Russian,"Вульфрумовый дроид будет защищать вас");
			ModCompatibility.CalamityMod.GetBuff("YharonKindleBuff").DisplayName.AddTranslation(GameCulture.Russian,"Сын Ярона");
			ModCompatibility.CalamityMod.GetBuff("YharonKindleBuff").Description.AddTranslation(GameCulture.Russian,"Сын Ярона будет защищать вас");
        }
    }
}
