using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ShadowsOfAbaddon.Buffs
{
	internal class SacredToolsBuffs
	{
		public static void Setup()
		{
			SacredToolsBuffs.Buffs();
		}
		private static void Buffs()
		{
			Mod sacredTools = ModLoader.GetMod("SacredTools");
			
			sacredTools.GetBuff("AbaddonDebuffDefense").DisplayName.AddTranslation(GameCulture.Russian, "Проклятье Абаддона - Заморозка");
			sacredTools.GetBuff("AbaddonDebuffDefense").Description.AddTranslation(GameCulture.Russian, "Вы не в состоянии двигаться");
			sacredTools.GetBuff("AbaddonDebuffOffense").DisplayName.AddTranslation(GameCulture.Russian, "Проклятье Абаддона - Слабость");
			sacredTools.GetBuff("AbaddonDebuffOffense").Description.AddTranslation(GameCulture.Russian, "Наносимый по вам урон увеличен на 50%");
			sacredTools.GetBuff("AhristaCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка эликсира Ахристы");
			sacredTools.GetBuff("AhristaCooldown").Description.AddTranslation(GameCulture.Russian, "Использование эликсира Ахристы невозможно");
			sacredTools.GetBuff("AhristaRegen").DisplayName.AddTranslation(GameCulture.Russian, "Эликсир Ахристы - Регенерация здоровья");
			sacredTools.GetBuff("AhristaRegen").Description.AddTranslation(GameCulture.Russian, "Постепенно восстанавливает здоровье");
			sacredTools.GetBuff("AntheePet").DisplayName.AddTranslation(GameCulture.Russian, "Память");
			sacredTools.GetBuff("AntheePet").Description.AddTranslation(GameCulture.Russian, "Память о Анте всё ещё с вами...");
			sacredTools.GetBuff("AraghurDefense").DisplayName.AddTranslation(GameCulture.Russian, "Бессмертие");
			sacredTools.GetBuff("AraghurDefense").Description.AddTranslation(GameCulture.Russian, "Получаемый урон уменьшен на 50%");
			sacredTools.GetBuff("AraneasDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Взгляд Императрицы");
			sacredTools.GetBuff("AraneasDebuff").Description.AddTranslation(GameCulture.Russian, "Вернитесь в гнездо, сейчас же!");
			sacredTools.GetBuff("AraneasDebuff2").DisplayName.AddTranslation(GameCulture.Russian, "Взгляд Императрицы");
			sacredTools.GetBuff("AraneasDebuff2").Description.AddTranslation(GameCulture.Russian, "'Ну ты слушать не хотел...'");
			sacredTools.GetBuff("AsthralDrone").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый дрон");
			sacredTools.GetBuff("AsthralDrone").Description.AddTranslation(GameCulture.Russian, "Азралититовый дрон сражается за вас");
			sacredTools.GetBuff("AsthralHealDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Частичное разложение");
			sacredTools.GetBuff("AsthralHealDebuff").Description.AddTranslation(GameCulture.Russian, "Использование азралититового лечебного эликсира невозможно");
			sacredTools.GetBuff("AsthralRegen").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая регенерция");
			sacredTools.GetBuff("AsthralRegen").Description.AddTranslation(GameCulture.Russian, "Увеличивает скорость восстановления здоровья");
			sacredTools.GetBuff("AsthralShip").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый корабль");
			sacredTools.GetBuff("AsthralShip").Description.AddTranslation(GameCulture.Russian, "УВОЛЕН");
			sacredTools.GetBuff("BaruBuff").DisplayName.AddTranslation(GameCulture.Russian, "Бару-поглощение");
			sacredTools.GetBuff("BaruBuff").Description.AddTranslation(GameCulture.Russian, "Вытягивает жизнь противников");
			sacredTools.GetBuff("BaruDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Бару-поглощение");
			sacredTools.GetBuff("BaruDebuff").Description.AddTranslation(GameCulture.Russian, "Потеря здоровья");
			sacredTools.GetBuff("Bloodlust").DisplayName.AddTranslation(GameCulture.Russian, "Резня");
			sacredTools.GetBuff("Bloodlust").Description.AddTranslation(GameCulture.Russian, "Увеличивает шанс выпадения сердца на 20%");
			sacredTools.GetBuff("BloodlustRegen").DisplayName.AddTranslation(GameCulture.Russian, "Жажда крови");
			sacredTools.GetBuff("BloodlustRegen").Description.AddTranslation(GameCulture.Russian, "Увеличивает скорость восстановления здоровья");
			sacredTools.GetBuff("Branded").DisplayName.AddTranslation(GameCulture.Russian, "Заклейменный");
			sacredTools.GetBuff("Branded").Description.AddTranslation(GameCulture.Russian, "Притягивает пламя");
			sacredTools.GetBuff("BulletKin").DisplayName.AddTranslation(GameCulture.Russian, "Пулевой собрат");
			sacredTools.GetBuff("BulletKin").Description.AddTranslation(GameCulture.Russian, "Родился из твоей пушки, и ты ему вроде как нравишься");
			sacredTools.GetBuff("BuzzyBeetle").DisplayName.AddTranslation(GameCulture.Russian, "Жужжащий жук");
			sacredTools.GetBuff("BuzzyBeetle").Description.AddTranslation(GameCulture.Russian, "Милый жучок следует за вами");
			sacredTools.GetBuff("CALCIUM").DisplayName.AddTranslation(GameCulture.Russian, "Кальций");
			sacredTools.GetBuff("CALCIUM").Description.AddTranslation(GameCulture.Russian, "Наслаждайся новыми спутниками");
			sacredTools.GetBuff("ChibiAraghur").DisplayName.AddTranslation(GameCulture.Russian, "Чиби Арагур");
			sacredTools.GetBuff("ChibiAraghur").Description.AddTranslation(GameCulture.Russian, "'Мне это отвратительно'");
			sacredTools.GetBuff("ChibiJensen").DisplayName.AddTranslation(GameCulture.Russian, "Чиби Дженсен");
			sacredTools.GetBuff("ChibiJensen").Description.AddTranslation(GameCulture.Russian, "Она все еще тебя не любит");
			sacredTools.GetBuff("ChibiVoxa").DisplayName.AddTranslation(GameCulture.Russian, "Чиби Вихрина");
			sacredTools.GetBuff("ChibiVoxa").Description.AddTranslation(GameCulture.Russian, "Ей нужен торт, срочно");
			sacredTools.GetBuff("ChickenMount").DisplayName.AddTranslation(GameCulture.Russian, "Скелет курицы");
			sacredTools.GetBuff("ChickenMount").Description.AddTranslation(GameCulture.Russian, "Вперед, куриная кость!");
			sacredTools.GetBuff("Commanding").DisplayName.AddTranslation(GameCulture.Russian, "Командир");
			sacredTools.GetBuff("Commanding").Description.AddTranslation(GameCulture.Russian, "Увеличивает максимальное количество стражей");
			sacredTools.GetBuff("CrimsonMinion").DisplayName.AddTranslation(GameCulture.Russian, "Кримини");
			sacredTools.GetBuff("CrimsonMinion").Description.AddTranslation(GameCulture.Russian, "Маленькая кримера следует за вами");
			sacredTools.GetBuff("CrimsonSigil").DisplayName.AddTranslation(GameCulture.Russian, "Багровый сигил");
			sacredTools.GetBuff("CrimsonSigil").Description.AddTranslation(GameCulture.Russian, "Повседневная жизнь с багровой мерзостью");
			sacredTools.GetBuff("CursePurple").DisplayName.AddTranslation(GameCulture.Russian, "Магическая усталость");
			sacredTools.GetBuff("CursePurple").Description.AddTranslation(GameCulture.Russian, "Снижает магический урон на 20%");
			sacredTools.GetBuff("DaresBuff").DisplayName.AddTranslation(GameCulture.Russian, "Щит смелости");
			sacredTools.GetBuff("DaresBuff").Description.AddTranslation(GameCulture.Russian, "Увеличивает оборонительные возможности");
			sacredTools.GetBuff("DarkflameHound").DisplayName.AddTranslation(GameCulture.Russian, "Гончая темного пламени");
			sacredTools.GetBuff("DarkflameHound").Description.AddTranslation(GameCulture.Russian, "*Гав*");
			sacredTools.GetBuff("Darklit").DisplayName.AddTranslation(GameCulture.Russian, "Дарклит");
			sacredTools.GetBuff("Darklit").Description.AddTranslation(GameCulture.Russian, "Увеличивает характеристики");
			sacredTools.GetBuff("DarkPresence").DisplayName.AddTranslation(GameCulture.Russian, "Темное присутствие");
			sacredTools.GetBuff("DarkPresence").Description.AddTranslation(GameCulture.Russian, "'Оно голодное...'");
			sacredTools.GetBuff("DarkStar").DisplayName.AddTranslation(GameCulture.Russian, "Темная звезда");
			sacredTools.GetBuff("DarkStar").Description.AddTranslation(GameCulture.Russian, "Темноте в темноте в темноте в темноте в темноте в темноте в темноте в-...");
			sacredTools.GetBuff("Dawnlight").DisplayName.AddTranslation(GameCulture.Russian, "Рассветный свет");
			sacredTools.GetBuff("Dawnlight").Description.AddTranslation(GameCulture.Russian, "Увеличивает характеристики днем");
			sacredTools.GetBuff("DecreeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ледяная мощь");
			sacredTools.GetBuff("DecreeBuff").Description.AddTranslation(GameCulture.Russian, "Силы льда двигаются в ваших венах");
			sacredTools.GetBuff("DespairFlame").DisplayName.AddTranslation(GameCulture.Russian, "Пламя отчаяния");
			sacredTools.GetBuff("DespairFlame").Description.AddTranslation(GameCulture.Russian, "Преследуемый горящими кошмарами");
			sacredTools.GetBuff("DespairObserver").DisplayName.AddTranslation(GameCulture.Russian, "Обозреватель отчаяния");
			sacredTools.GetBuff("DespairObserver").Description.AddTranslation(GameCulture.Russian, "Обозреватель отчаяния сражается за вас");
			sacredTools.GetBuff("DoemDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие-Доэм");
			sacredTools.GetBuff("DoemDebuff").Description.AddTranslation(GameCulture.Russian, "Наносимый вам урон увеличен на 100%");
			sacredTools.GetBuff("DraconicBlaze").DisplayName.AddTranslation(GameCulture.Russian, "Пламя дракона");
			sacredTools.GetBuff("DraconicBlaze").Description.AddTranslation(GameCulture.Russian, "Темный огонь поглощает вас");
			sacredTools.GetBuff("DraconiumSkin").DisplayName.AddTranslation(GameCulture.Russian, "Дракониумовая кожа");
			sacredTools.GetBuff("DraconiumSkin").Description.AddTranslation(GameCulture.Russian, "Значительно увеличивает защиту и сопротивление урону");
			sacredTools.GetBuff("DreadCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Ужаснопламенная усталость");
			sacredTools.GetBuff("DreadCooldown").Description.AddTranslation(GameCulture.Russian, "Использование Ужаснопламенной ауры невозможно");
			sacredTools.GetBuff("DreadfireAura").DisplayName.AddTranslation(GameCulture.Russian, "Ужаснопламенная аура");
			sacredTools.GetBuff("DreadfireAura").Description.AddTranslation(GameCulture.Russian, "Пламя террора ночи усиляют ваше волшебство");
			sacredTools.GetBuff("DurafnirCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Погашенное пламя");
			sacredTools.GetBuff("DurafnirCooldown").Description.AddTranslation(GameCulture.Russian, "Выпуск огней невозможен");
			sacredTools.GetBuff("EerieRegen").DisplayName.AddTranslation(GameCulture.Russian, "Зловещая регенерация");
			sacredTools.GetBuff("EerieRegen").Description.AddTranslation(GameCulture.Russian, "Увеличивает скорость восстановления здоровья");
			sacredTools.GetBuff("ErazorFall").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие связывания");
			sacredTools.GetBuff("ErazorFall").Description.AddTranslation(GameCulture.Russian, "Любые действия невозможны");
			sacredTools.GetBuff("ErazorJump").DisplayName.AddTranslation(GameCulture.Russian, "Грация и гравитация");
			sacredTools.GetBuff("ErazorJump").Description.AddTranslation(GameCulture.Russian, "Вас толкает вверх");
			sacredTools.GetBuff("Eroded").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовое разрушение");
			sacredTools.GetBuff("Eroded").Description.AddTranslation(GameCulture.Russian, "Ваш разум отравлен яростью");
			sacredTools.GetBuff("ErodedIchor").DisplayName.AddTranslation(GameCulture.Russian, "Разрушающий ихор");
			sacredTools.GetBuff("ErodedIchor").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье и ваша защита ослаблена");
			sacredTools.GetBuff("FireBreath").DisplayName.AddTranslation(GameCulture.Russian, "Огненное дыхание");
			sacredTools.GetBuff("FireBreath").Description.AddTranslation(GameCulture.Russian, "Это блюдо настолько острое, что вы теперь дышите огнем");
			sacredTools.GetBuff("FireMaggot").DisplayName.AddTranslation(GameCulture.Russian, "Огненный червь");
			sacredTools.GetBuff("FireMaggot").Description.AddTranslation(GameCulture.Russian, "Ну, оно похоже на червя");
			sacredTools.GetBuff("FlariumCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Усталость феникса");
			sacredTools.GetBuff("FlariumCooldown").Description.AddTranslation(GameCulture.Russian, "Возрождение невозможно");
			sacredTools.GetBuff("FlariumFlurry").DisplayName.AddTranslation(GameCulture.Russian, "Прорыв яркого пламени");
			sacredTools.GetBuff("FlariumFlurry").Description.AddTranslation(GameCulture.Russian, "Ваше сиятельство");
			sacredTools.GetBuff("FrostMinion").DisplayName.AddTranslation(GameCulture.Russian, "Морозная виверна");
			sacredTools.GetBuff("FrostMinion").Description.AddTranslation(GameCulture.Russian, "Морозная виверна сражается за вас");
			sacredTools.GetBuff("FrostWrath").DisplayName.AddTranslation(GameCulture.Russian, "Пламя обморожения");
			sacredTools.GetBuff("FrostWrath").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			sacredTools.GetBuff("FruitBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лампа фрукта жизни");
			sacredTools.GetBuff("FruitBuff").Description.AddTranslation(GameCulture.Russian, "Увеличивает скорость восстановления здоровья");
			sacredTools.GetBuff("GehennaBuff1").DisplayName.AddTranslation(GameCulture.Russian, "Удар Геенны");
			sacredTools.GetBuff("GehennaBuff1").Description.AddTranslation(GameCulture.Russian, "Уровень 1");
			sacredTools.GetBuff("GehennaBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Удар геенны");
			sacredTools.GetBuff("GehennaBuff2").Description.AddTranslation(GameCulture.Russian, "Уровень 2");
			sacredTools.GetBuff("GehennaBuff3").DisplayName.AddTranslation(GameCulture.Russian, "Удар геенны");
			sacredTools.GetBuff("GehennaBuff3").Description.AddTranslation(GameCulture.Russian, "Уровень 3");
			sacredTools.GetBuff("GreenHarpyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Гарпия");
			sacredTools.GetBuff("GreenHarpyBuff").Description.AddTranslation(GameCulture.Russian, "Гарпия сражается за вас");
			sacredTools.GetBuff("Haldez").DisplayName.AddTranslation(GameCulture.Russian, "Халдез");
			sacredTools.GetBuff("Haldez").Description.AddTranslation(GameCulture.Russian, "Дух дракона следует за вами");
			sacredTools.GetBuff("HarpyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Королевская гарпия");
			sacredTools.GetBuff("HarpyBuff").Description.AddTranslation(GameCulture.Russian, "Королевская гарпия следует за вами");
			sacredTools.GetBuff("hBuff").DisplayName.AddTranslation(GameCulture.Russian, "h");
			sacredTools.GetBuff("hBuff").Description.AddTranslation(GameCulture.Russian, "Урон по боссам увеличен на 5%");
			sacredTools.GetBuff("HeavyBleed").DisplayName.AddTranslation(GameCulture.Russian, "Сильное кровотечение");
			sacredTools.GetBuff("HeavyBleed").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			sacredTools.GetBuff("Inked").DisplayName.AddTranslation(GameCulture.Russian, "Зачернилен");
			sacredTools.GetBuff("Inked").Description.AddTranslation(GameCulture.Russian, "Скорость передвижение снижена");
			sacredTools.GetBuff("KrysteaCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка эликсира Кристеи");
			sacredTools.GetBuff("KrysteaCooldown").Description.AddTranslation(GameCulture.Russian, "Использование эликсира Кристеи невозможно");
			sacredTools.GetBuff("KrysteaRegen").DisplayName.AddTranslation(GameCulture.Russian, "Эликсир Кристеи - Восстановление маны");
			sacredTools.GetBuff("KrysteaRegen").Description.AddTranslation(GameCulture.Russian, "Значительно увеличивает восстановление маны");
			sacredTools.GetBuff("LamiaSong").DisplayName.AddTranslation(GameCulture.Russian, "Песня Ламии");
			sacredTools.GetBuff("LamiaSong").Description.AddTranslation(GameCulture.Russian, "Вы парализованы");
			sacredTools.GetBuff("LapisShield1").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый щит");
			sacredTools.GetBuff("LapisShield1").Description.AddTranslation(GameCulture.Russian, "Защита увеличена на 3");
			sacredTools.GetBuff("LapisShield2").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый щит");
			sacredTools.GetBuff("LapisShield2").Description.AddTranslation(GameCulture.Russian, "Защита увеличена на 6");
			sacredTools.GetBuff("LapisShield3").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый щит");
			sacredTools.GetBuff("LapisShield3").Description.AddTranslation(GameCulture.Russian, "Защита увеличена на 9");
			sacredTools.GetBuff("LeviFreeze").DisplayName.AddTranslation(GameCulture.Russian, "Заморозка левиафана");
			sacredTools.GetBuff("LeviFreeze").Description.AddTranslation(GameCulture.Russian, "Не в состоянии двигаться");
			sacredTools.GetBuff("LeviPurge").DisplayName.AddTranslation(GameCulture.Russian, "Очистка левиафана");
			sacredTools.GetBuff("LeviPurge").Description.AddTranslation(GameCulture.Russian, "Вы были очищены");
			sacredTools.GetBuff("LunarCharge").DisplayName.AddTranslation(GameCulture.Russian, "Таймер Нованиэля");
			sacredTools.GetBuff("LunarCharge").Description.AddTranslation(GameCulture.Russian, "Закончте битву, пока не стало слишком поздно");
			sacredTools.GetBuff("LunarianAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура уничтожения");
			sacredTools.GetBuff("LunarianAura").Description.AddTranslation(GameCulture.Russian, "Трусы будут уничтожены");
			sacredTools.GetBuff("LunarMinion").DisplayName.AddTranslation(GameCulture.Russian, "Лунный кристалл");
			sacredTools.GetBuff("LunarMinion").Description.AddTranslation(GameCulture.Russian, "Вы командуете сворой кристаллов");
			sacredTools.GetBuff("MoonBurn").DisplayName.AddTranslation(GameCulture.Russian, "Лунное инферно");
			sacredTools.GetBuff("MoonBurn").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			sacredTools.GetBuff("MoonlightDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Ночная рапсодия");
			sacredTools.GetBuff("MoonlightDebuff").Description.AddTranslation(GameCulture.Russian, "Взрывается при контакте");
			sacredTools.GetBuff("MoonlightRhapsody").DisplayName.AddTranslation(GameCulture.Russian, "Ночная рапсодия");
			sacredTools.GetBuff("MoonlightRhapsody").Description.AddTranslation(GameCulture.Russian, "Аура лунного света окружает вас");
			sacredTools.GetBuff("Moonlit").DisplayName.AddTranslation(GameCulture.Russian, "Лунолит");
			sacredTools.GetBuff("Moonlit").Description.AddTranslation(GameCulture.Russian, "Увеличивает характеристики ночью");
			sacredTools.GetBuff("MooshCart").DisplayName.AddTranslation(GameCulture.Russian, "Вагонетка Муухомора");
			sacredTools.GetBuff("MooshCart").Description.AddTranslation(GameCulture.Russian, "101");
			sacredTools.GetBuff("Mople").DisplayName.AddTranslation(GameCulture.Russian, "Мопи");
			sacredTools.GetBuff("Mople").Description.AddTranslation(GameCulture.Russian, "Маленький дух следует за вами");
			sacredTools.GetBuff("MummyHand").DisplayName.AddTranslation(GameCulture.Russian, "Голова мумии");
			sacredTools.GetBuff("MummyHand").Description.AddTranslation(GameCulture.Russian, "Голова мумии сражается за вас");
			sacredTools.GetBuff("NetherBuff").DisplayName.AddTranslation(GameCulture.Russian, "Адская аура");
			sacredTools.GetBuff("NetherBuff").Description.AddTranslation(GameCulture.Russian, "Незер усиляет противников!");
			sacredTools.GetBuff("NickyPet").DisplayName.AddTranslation(GameCulture.Russian, "Вставьте ник питомца");
			sacredTools.GetBuff("NickyPet").Description.AddTranslation(GameCulture.Russian, "И кто это такой?");
			sacredTools.GetBuff("NightmareFog").DisplayName.AddTranslation(GameCulture.Russian, "Кошмарный туман");
			sacredTools.GetBuff("NightmareFog").Description.AddTranslation(GameCulture.Russian, "Ваше тело рвется");
			sacredTools.GetBuff("NightmareFueled").DisplayName.AddTranslation(GameCulture.Russian, "Заправлен кошмарами");
			sacredTools.GetBuff("NightmareFueled").Description.AddTranslation(GameCulture.Russian, "Вы намного сильнее обычного человека");
			sacredTools.GetBuff("NoFlare").DisplayName.AddTranslation(GameCulture.Russian, "Иммунитет вспышки");
			sacredTools.GetBuff("NoFlare").Description.AddTranslation(GameCulture.Russian, "Временная защита от Выжигающего инферно");
			sacredTools.GetBuff("NoLunar").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие луны");
			sacredTools.GetBuff("NoLunar").Description.AddTranslation(GameCulture.Russian, "Невозможно использовать лунную эмблему");
			sacredTools.GetBuff("NovanielArmor").DisplayName.AddTranslation(GameCulture.Russian, "Потресканная броня");
			sacredTools.GetBuff("NovanielArmor").Description.AddTranslation(GameCulture.Russian, "Ваша броня уменьшена вдвое");
			sacredTools.GetBuff("NovanielDeath").DisplayName.AddTranslation(GameCulture.Russian, "Небесный Суд");
			sacredTools.GetBuff("NovanielDeath").Description.AddTranslation(GameCulture.Russian, "Твоя судьба предрешена");
			sacredTools.GetBuff("NovanielFallCurse").DisplayName.AddTranslation(GameCulture.Russian, "Усиленная гравитация");
			sacredTools.GetBuff("NovanielFallCurse").Description.AddTranslation(GameCulture.Russian, "Вас тянет к земле сильнее");
			sacredTools.GetBuff("NovanielWeapon").DisplayName.AddTranslation(GameCulture.Russian, "Деформированное оружие");
			sacredTools.GetBuff("NovanielWeapon").Description.AddTranslation(GameCulture.Russian, "Ваше оружие ослаблено");
			sacredTools.GetBuff("NumberOne").DisplayName.AddTranslation(GameCulture.Russian, "Разрыв");
			sacredTools.GetBuff("NumberOne").Description.AddTranslation(GameCulture.Russian, "'Here's a little lesson in trickery'\nУрон по противникам увеличен на 10%");
			sacredTools.GetBuff("ObsidianCurse").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие обсидиана");
			sacredTools.GetBuff("ObsidianCurse").Description.AddTranslation(GameCulture.Russian, "Ваше руки покрыты обсидианом");
			sacredTools.GetBuff("ObsiMinion").DisplayName.AddTranslation(GameCulture.Russian, "Элементаль вспышки");
			sacredTools.GetBuff("ObsiMinion").Description.AddTranslation(GameCulture.Russian, "Элементаль вспышки сражается за вас");
			sacredTools.GetBuff("Option").DisplayName.AddTranslation(GameCulture.Russian, "'Альтернатива'");
			sacredTools.GetBuff("Option").Description.AddTranslation(GameCulture.Russian, "'Альтернатива' усиливает вашу огневую мощь");
			sacredTools.GetBuff("PhaseFlames").DisplayName.AddTranslation(GameCulture.Russian, "Огни отчаяния");
			sacredTools.GetBuff("PhaseFlames").Description.AddTranslation(GameCulture.Russian, "Вы поглощены кошмарами");
			sacredTools.GetBuff("PhoenixStrength").DisplayName.AddTranslation(GameCulture.Russian, "Возврождение");
			sacredTools.GetBuff("PhoenixStrength").Description.AddTranslation(GameCulture.Russian, "Вы ощущаете силу Феникса");
			sacredTools.GetBuff("PrimordiaCurse").DisplayName.AddTranslation(GameCulture.Russian, "Присутствие ипостаси");
			sacredTools.GetBuff("PrimordiaCurse").Description.AddTranslation(GameCulture.Russian, "Древнее проклятие лежит на вас");
			sacredTools.GetBuff("PumpMinion").DisplayName.AddTranslation(GameCulture.Russian, "Свеченыш");
			sacredTools.GetBuff("PumpMinion").Description.AddTranslation(GameCulture.Russian, "Испуг на барабане");
			sacredTools.GetBuff("PupPet").DisplayName.AddTranslation(GameCulture.Russian, "Лающий щенок смерти");
			sacredTools.GetBuff("PupPet").Description.AddTranslation(GameCulture.Russian, "'Гаф! Гаф!'");
			sacredTools.GetBuff("QuasarDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Разлом кванта");
			sacredTools.GetBuff("QuasarDebuff").Description.AddTranslation(GameCulture.Russian, "Кунаи квазара наносят 50% дополнительного урона");
			sacredTools.GetBuff("RalseiBuff").DisplayName.AddTranslation(GameCulture.Russian, "Принц тьмы");
			sacredTools.GetBuff("RalseiBuff").Description.AddTranslation(GameCulture.Russian, "Сила пушистого мальчика переполняет вас");
			sacredTools.GetBuff("RedVenom").DisplayName.AddTranslation(GameCulture.Russian, "Красный яд");
			sacredTools.GetBuff("RedVenom").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			sacredTools.GetBuff("RobustMuscles").DisplayName.AddTranslation(GameCulture.Russian, "Крепкая мускулатура");
			sacredTools.GetBuff("RobustMuscles").Description.AddTranslation(GameCulture.Russian, "Метательное ускорений увеличено");
			sacredTools.GetBuff("Sandnado").DisplayName.AddTranslation(GameCulture.Russian, "Песконадо");
			sacredTools.GetBuff("Sandnado").Description.AddTranslation(GameCulture.Russian, "Песконадо сражается за вас");
			sacredTools.GetBuff("SatelliteBuff").DisplayName.AddTranslation(GameCulture.Russian, "Спутник");
			sacredTools.GetBuff("SatelliteBuff").Description.AddTranslation(GameCulture.Russian, "'Сигнал принят. Выбрана функция уничтожения...'");
			sacredTools.GetBuff("SeraphSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать темного серафима");
			sacredTools.GetBuff("SeraphSigil").Description.AddTranslation(GameCulture.Russian, "Проклятие было принято...");
			sacredTools.GetBuff("SerpentAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура серафима");
			sacredTools.GetBuff("SerpentAura").Description.AddTranslation(GameCulture.Russian, "Вы не можете поглотить целебные эффекты");
			sacredTools.GetBuff("SerpentAuraCounter").DisplayName.AddTranslation(GameCulture.Russian, "Аура змея");
			sacredTools.GetBuff("SerpentAuraCounter").Description.AddTranslation(GameCulture.Russian, "Жара вокруг растет");
			sacredTools.GetBuff("SerpentAuraStacked").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие змея");
			sacredTools.GetBuff("SerpentAuraStacked").Description.AddTranslation(GameCulture.Russian, "'От смерти не убежать!'");
			sacredTools.GetBuff("SerpentMinion").DisplayName.AddTranslation(GameCulture.Russian, "Змей вспышки");
			sacredTools.GetBuff("SerpentMinion").Description.AddTranslation(GameCulture.Russian, "Змей вспышки сражается за вас");
			sacredTools.GetBuff("SerpentMount").DisplayName.AddTranslation(GameCulture.Russian, "Блестящий змей");
			sacredTools.GetBuff("SerpentMount").Description.AddTranslation(GameCulture.Russian, "Вы катаетесь на спине блестящего змея");
			sacredTools.GetBuff("SerpentWrath").DisplayName.AddTranslation(GameCulture.Russian, "Выжигающие инферно");
			sacredTools.GetBuff("SerpentWrath").Description.AddTranslation(GameCulture.Russian, "Вы загораетесь от сумасшедшей жары");
			sacredTools.GetBuff("Shadowflare").DisplayName.AddTranslation(GameCulture.Russian, "Пламя темной вспышки");
			sacredTools.GetBuff("Shadowflare").Description.AddTranslation(GameCulture.Russian, "Ваши жизненные силы поглощаются");
			sacredTools.GetBuff("ShadowflareVortex").DisplayName.AddTranslation(GameCulture.Russian, "Вихрь темной вспышки");
			sacredTools.GetBuff("ShadowflareVortex").Description.AddTranslation(GameCulture.Russian, "Вы зашли в вихрь без должной защиты");
			sacredTools.GetBuff("ShardErosion").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая ярость");
			sacredTools.GetBuff("ShardErosion").Description.AddTranslation(GameCulture.Russian, "Ярость поглощает крупицы разума");
			sacredTools.GetBuff("Singe").DisplayName.AddTranslation(GameCulture.Russian, "Ожог");
			sacredTools.GetBuff("Singe").Description.AddTranslation(GameCulture.Russian, "Вы обгорели");
			sacredTools.GetBuff("SniperState").DisplayName.AddTranslation(GameCulture.Russian, "Поза снайпера");
			sacredTools.GetBuff("SniperState").Description.AddTranslation(GameCulture.Russian, "Вы закреплены на одном месте");
			sacredTools.GetBuff("Soulburn").DisplayName.AddTranslation(GameCulture.Russian, "Ожог души");
			sacredTools.GetBuff("Soulburn").Description.AddTranslation(GameCulture.Russian, "Эссенция вашего существования подверглась нападению");
			sacredTools.GetBuff("SpiritLink").DisplayName.AddTranslation(GameCulture.Russian, "Душевная связь");
			sacredTools.GetBuff("SpiritLink").Description.AddTranslation(GameCulture.Russian, "Связаны неразрушимыми узами");
			sacredTools.GetBuff("Static").DisplayName.AddTranslation(GameCulture.Russian, "Статический ток");
			sacredTools.GetBuff("Static").Description.AddTranslation(GameCulture.Russian, "Вас замкнули");
			sacredTools.GetBuff("SumeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Желание Жить");
			sacredTools.GetBuff("SumeBuff").Description.AddTranslation(GameCulture.Russian, "Вы не признали поражение");
			sacredTools.GetBuff("SumeDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Склизкая усталость");
			sacredTools.GetBuff("SumeDebuff").Description.AddTranslation(GameCulture.Russian, "Невозможно воскреснуть");
			sacredTools.GetBuff("SunSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать солнца");
			sacredTools.GetBuff("SunSigil").Description.AddTranslation(GameCulture.Russian, "Вас озаряет яркий свет");
			sacredTools.GetBuff("SyrupBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сироп серьезного Сирусианца");
			sacredTools.GetBuff("SyrupBuff").Description.AddTranslation(GameCulture.Russian, "'Я - скорость!'\nУвеличивает скорость передвижения на 50%");
			sacredTools.GetBuff("TabbySlime").DisplayName.AddTranslation(GameCulture.Russian, "Полосатый слайм");
			sacredTools.GetBuff("TabbySlime").Description.AddTranslation(GameCulture.Russian, "Не забудь покормить его");
			sacredTools.GetBuff("ThrownBuff").DisplayName.AddTranslation(GameCulture.Russian, "Фокусировка Ниндзи");
			sacredTools.GetBuff("ThrownBuff").Description.AddTranslation(GameCulture.Russian, "Метательные характеристики увеличены");
			sacredTools.GetBuff("TowerSurmounting").DisplayName.AddTranslation(GameCulture.Russian, "Преодоление башни");
			sacredTools.GetBuff("TowerSurmounting").Description.AddTranslation(GameCulture.Russian, "Увеличивает дальность прыжка и время полета");
			sacredTools.GetBuff("Toxic").DisplayName.AddTranslation(GameCulture.Russian, "Токсичная болезнь");
			sacredTools.GetBuff("Toxic").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			sacredTools.GetBuff("Umbra").DisplayName.AddTranslation(GameCulture.Russian, "Тень");
			sacredTools.GetBuff("Umbra").Description.AddTranslation(GameCulture.Russian, "Мой меч будет твоим проводником");
			sacredTools.GetBuff("WindBuff").DisplayName.AddTranslation(GameCulture.Russian, "Един с вихрем");
			sacredTools.GetBuff("WindBuff").Description.AddTranslation(GameCulture.Russian, "Ветер словно проходит сквозь тебя...");
			sacredTools.GetBuff("Wither").DisplayName.AddTranslation(GameCulture.Russian, "Иссушение");
			sacredTools.GetBuff("Wither").Description.AddTranslation(GameCulture.Russian, "Ваша душа иссушается!");
			sacredTools.GetBuff("Sacrifice1").DisplayName.AddTranslation(GameCulture.Russian, "Жертвоприношение мага - уровень 1");
			sacredTools.GetBuff("Sacrifice1").Description.AddTranslation(GameCulture.Russian, "Потребление маны увеличено на 20%");
			sacredTools.GetBuff("Sacrifice2").DisplayName.AddTranslation(GameCulture.Russian, "Жертвоприношение мага - уровень 2");
			sacredTools.GetBuff("Sacrifice2").Description.AddTranslation(GameCulture.Russian, "Потребление маны увеличено на 40%");
			sacredTools.GetBuff("Sacrifice3").DisplayName.AddTranslation(GameCulture.Russian, "Жертвоприношение мага - уровень 3");
			sacredTools.GetBuff("Sacrifice3").Description.AddTranslation(GameCulture.Russian, "Потребление маны увеличено на 60%");
			sacredTools.GetBuff("Sacrifice4").DisplayName.AddTranslation(GameCulture.Russian, "Жертвоприношение мага - уровень 4");
			sacredTools.GetBuff("Sacrifice4").Description.AddTranslation(GameCulture.Russian, "Потребление маны увеличено на 80%");
			sacredTools.GetBuff("Sacrifice5").DisplayName.AddTranslation(GameCulture.Russian, "Жертвоприношение мага - уровень 5");
			sacredTools.GetBuff("Sacrifice5").Description.AddTranslation(GameCulture.Russian, "Потребление маны увеличено на 100%");
			sacredTools.GetBuff("NubaDamageI").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Урон I");
			sacredTools.GetBuff("NubaDamageI").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 5%");
			sacredTools.GetBuff("NubaDamageII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Урон II");
			sacredTools.GetBuff("NubaDamageII").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 10%");
			sacredTools.GetBuff("NubaDamageIII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Урон III");
			sacredTools.GetBuff("NubaDamageIII").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 15%");
			sacredTools.GetBuff("NubaDamageIV").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Урон IV");
			sacredTools.GetBuff("NubaDamageIV").Description.AddTranslation(GameCulture.Russian, "Урон увеличен на 20%");
			sacredTools.GetBuff("NubaDefenseI").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Защита I");
			sacredTools.GetBuff("NubaDefenseI").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону увеличено на 2%");
			sacredTools.GetBuff("NubaDefenseII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Защита II");
			sacredTools.GetBuff("NubaDefenseII").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону увеличено на 4%");
			sacredTools.GetBuff("NubaDefenseIII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Защита III");
			sacredTools.GetBuff("NubaDefenseIII").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону увеличено на 8%");
			sacredTools.GetBuff("NubaDefenseIV").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Защита IV");
			sacredTools.GetBuff("NubaDefenseIV").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону увеличено на 16%");
			sacredTools.GetBuff("NubaHealthI").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Здоровье I");
			sacredTools.GetBuff("NubaHealthI").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья увеличена на 2");
			sacredTools.GetBuff("NubaHealthII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Здоровье II");
			sacredTools.GetBuff("NubaHealthII").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья увеличена на 4");
			sacredTools.GetBuff("NubaHealthIII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Здоровье III");
			sacredTools.GetBuff("NubaHealthIII").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья увеличена на 6");
			sacredTools.GetBuff("NubaHealthIV").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Здоровье IV");
			sacredTools.GetBuff("NubaHealthIV").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья увеличена на 8");
			sacredTools.GetBuff("NubaManaI").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Мана I");
			sacredTools.GetBuff("NubaManaI").Description.AddTranslation(GameCulture.Russian, "Регенерация маны увеличена на 5");
			sacredTools.GetBuff("NubaManaII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Мана II");
			sacredTools.GetBuff("NubaManaII").Description.AddTranslation(GameCulture.Russian, "Регенерация маны увеличена на 10");
			sacredTools.GetBuff("NubaManaIII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Мана III");
			sacredTools.GetBuff("NubaManaIII").Description.AddTranslation(GameCulture.Russian, "Регенерация маны увеличена на 15");
			sacredTools.GetBuff("NubaManaIV").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Мана IV");
			sacredTools.GetBuff("NubaManaIV").Description.AddTranslation(GameCulture.Russian, "Регенерация маны увеличена на 20");
			sacredTools.GetBuff("NubaSpeedI").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Скорость I");
			sacredTools.GetBuff("NubaSpeedI").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения увеличена на 10%");
			sacredTools.GetBuff("NubaSpeedII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Скорость II");
			sacredTools.GetBuff("NubaSpeedII").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения увеличена на 20%");
			sacredTools.GetBuff("NubaSpeedIII").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Скорость III");
			sacredTools.GetBuff("NubaSpeedIII").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения увеличена на 25%");
			sacredTools.GetBuff("NubaSpeedIV").DisplayName.AddTranslation(GameCulture.Russian, "Туманное пламя - Скорость IV");
			sacredTools.GetBuff("NubaSpeedIV").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения увеличена на 30%");
			sacredTools.GetBuff("PerkisasBuff1").DisplayName.AddTranslation(GameCulture.Russian, "Драконья жадность - I");
			sacredTools.GetBuff("PerkisasBuff1").Description.AddTranslation(GameCulture.Russian, "Атакуйте врагов, чтобы увеличить уровень");
			sacredTools.GetBuff("PerkisasBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Драконья жадность - II");
			sacredTools.GetBuff("PerkisasBuff2").Description.AddTranslation(GameCulture.Russian, "Атакуйте врагов, чтобы увеличить уровень");
			sacredTools.GetBuff("PerkisasBuff3").DisplayName.AddTranslation(GameCulture.Russian, "Драконья жадность - III");
			sacredTools.GetBuff("PerkisasBuff3").Description.AddTranslation(GameCulture.Russian, "Атакуйте врагов, чтобы увеличить уровень");
			sacredTools.GetBuff("PerkisasBuff4").DisplayName.AddTranslation(GameCulture.Russian, "Драконья жадность - IV");
			sacredTools.GetBuff("PerkisasBuff4").Description.AddTranslation(GameCulture.Russian, "Атакуйте врагов, чтобы увеличить уровень");
			sacredTools.GetBuff("PerkisasBuff5").DisplayName.AddTranslation(GameCulture.Russian, "Драконья жадность - V");
			sacredTools.GetBuff("PerkisasBuff5").Description.AddTranslation(GameCulture.Russian, "Следующая атака освободит ярость Перкисаса");
			sacredTools.GetBuff("Skill_FuryForged_Cooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка - Кованая ярость");
			sacredTools.GetBuff("Skill_FuryForged_Cooldown").Description.AddTranslation(GameCulture.Russian, "Вы не можете использовать скилл Кованой ярости'");
		}
	}
}
