// using System.Reflection;
// using CalamityRuTranslate.Common;
// using CalamityRuTranslate.Common.Utilities;
// using CalamityRuTranslate.Core.MonoMod;
// using MonoMod.Cil;
// using StarsAbove.NPCs;
// using Terraria.ModLoader;
//
// namespace CalamityRuTranslate.Mods.TheStarsAbove.MonoMod;
//
// [JITWhenModsEnabled("StarsAbove")]
// public class ArbitrationPatch : ILPatcher
// {
//     public override bool AutoLoad => ModsCall.StarsAbove != null && TranslationHelper.IsRussianLanguage;
//
//     public override MethodInfo ModifiedMethod => typeof(Arbitration).GetCachedMethod(nameof(Arbitration.AI));
//
//     public override ILContext.Manipulator PatchMethod { get; } = il =>
//     {
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы");
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 2);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 3);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 4);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 5);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 6);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 7);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 8);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 9);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 10);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 11);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 12);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 13);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 14);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 15);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 16);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 17);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 18);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 19);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 20);
//         TranslationHelper.ModifyIL(il, "Threads of Fate", "Нити судьбы", 21);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота");
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 2);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 3);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 4);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 5);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 6);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 7);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 8);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 9);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 10);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 11);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 12);
//         TranslationHelper.ModifyIL(il, "The Void Consumes All", "Всепоглощающая пустота", 13);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес");
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 2);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 3);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 4);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 5);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 6);
//         TranslationHelper.ModifyIL(il, "A World Rent Asunder", "Разорванный мир");
//         TranslationHelper.ModifyIL(il, "A World Rent Asunder", "Разорванный мир", 2);
//         TranslationHelper.ModifyIL(il, "Surpassing Infinity", "За пределами бесконечности");
//         TranslationHelper.ModifyIL(il, "Surpassing Infinity", "За пределами бесконечности", 2);
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение");
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение", 2);
//         TranslationHelper.ModifyIL(il, "The Flood Of Light", "Поток Света");
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом");
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 2);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 3);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 4);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 5);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 6);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 7);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 8);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 9);
//         TranslationHelper.ModifyIL(il, "Beneath a Bleak Sky", "Под мрачным небом", 10);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber", "Корусантская сабля");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 2);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 3);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 4);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 5);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь");
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 2);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 3);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 4);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 5);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня");
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи");
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 2);
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 3);
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 4);
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 5);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II");
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 2);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 3);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 4);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 5);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов");
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ");
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II");
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция");
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 2);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 3);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 4);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 5);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 6);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 7);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 8);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 9);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 10);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 11);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 12);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 13);
//         TranslationHelper.ModifyIL(il, "The Bitter End", "Горький конец");
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика");
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 2);
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 3);
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 4);
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 5);
//         TranslationHelper.ModifyIL(il, "Absolute Fire III", "Абсолютный огонь III");
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III");
//         TranslationHelper.ModifyIL(il, "Terror Unleashed", "Освобождённый ужас");
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция");
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 2);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 3);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 4);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 5);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 6);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 7);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 8);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 9);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 10);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса");
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 2);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 3);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 4);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 5);
//         TranslationHelper.ModifyIL(il, "Ink Over", "Вездесущие чернила");
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир");
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир", 2);
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир", 3);
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир", 4);
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир", 5);
//         TranslationHelper.ModifyIL(il, "Hello, World", "Привет, Мир", 6);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение");
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 2);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 3);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 4);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 5);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 6);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 7);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 8);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 9);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 10);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 11);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 12);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение", 13);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис");
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 2);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 3);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 4);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 5);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 6);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 7);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 8);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 9);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 10);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 11);
//         TranslationHelper.ModifyIL(il, "Synaptic Syntax", "Синаптический синтаксис", 12);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия");
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 2);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 3);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 4);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 5);
//         TranslationHelper.ModifyIL(il, "Ars Laevateinn", "Арс Леватейн");
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги");
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 2);
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 3);
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 4);
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 5);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза");
//         TranslationHelper.ModifyIL(il, "Absolute Thunder IV", "Абсолютная гроза IV");
//         TranslationHelper.ModifyIL(il, "Quintuplecast", "Пятикратное заклинание");
//         TranslationHelper.ModifyIL(il, "Absolute Holy", "Абсолютная святость");
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо");
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики");
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики", 2);
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики", 3);
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики", 4);
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики", 5);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения");
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 2);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 3);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 4);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 5);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 6);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 7);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 8);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 9);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 10);
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения", 11);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность");
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 2);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 3);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 4);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 5);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 6);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 7);
//         TranslationHelper.ModifyIL(il, "To The Limit", "Круша лимиты");
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия");
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия", 2);
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия", 3);
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия", 4);
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия", 5);
//         TranslationHelper.ModifyIL(il, "Titanomachy", "Титаномахия", 6);
//         TranslationHelper.ModifyIL(il, "SOUL Extraction", "Извлечение ДУШИ");
//         TranslationHelper.ModifyIL(il, "Light Rampant", "Раздолье света");
//         TranslationHelper.ModifyIL(il, "Radiant Braver", "Сияющий храбрец");
//         TranslationHelper.ModifyIL(il, "Radiant Desperado", "Сияющий отчаянный");
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь");
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 2);
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 3);
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 4);
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 5);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара");
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 2);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 3);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 4);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 5);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур");
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 2);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 3);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 4);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 5);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание");
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 2);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 3);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 4);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 5);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 6);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 7);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 8);
//         TranslationHelper.ModifyIL(il, "Abrasion", "Стирание", 9);
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис");
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис", 2);
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис", 3);
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис", 4);
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв");
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 2);
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 3);
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 4);
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 5);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос");
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат");
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ");
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 2);
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 3);
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 4);
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 5);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос");
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 2);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 3);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 4);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 5);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 6);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 7);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через Хаос", 8);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок");
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 2);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 3);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 4);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 5);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 6);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 7);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через Порядок", 8);
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал");
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал", 2);
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал", 3);
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал", 4);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой");
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 2);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 3);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 4);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 5);
//         TranslationHelper.ModifyIL(il, "Concentrativity", "Концентративность");
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона");
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона", 2);
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона", 3);
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона", 4);
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности");
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности", 2);
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности", 3);
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности", 4);
//     };
// }