// using System.Reflection;
// using CalamityRuTranslate.Common;
// using CalamityRuTranslate.Common.Utilities;
// using CalamityRuTranslate.Core.MonoMod;
// using MonoMod.Cil;
// using StarsAbove.NPCs;
// using Terraria.ModLoader;
//
// namespace CalamityRuTranslate.Mods.TheStarsAbove.MonoMod;
//
// [JITWhenModsEnabled("StarsAbove")]
// public class NalhaunPatch : ILPatcher
// {
//     public override bool AutoLoad => ModsCall.StarsAbove != null && TranslationHelper.IsRussianLanguage;
//
//     public override MethodInfo ModifiedMethod => typeof(Nalhaun).GetCachedMethod(nameof(Nalhaun.AI));
//
//     public override ILContext.Manipulator PatchMethod { get; } = il =>
//     {
//         TranslationHelper.ModifyIL(il, "You fall to the Burnished King...", "Вы пали перед Воронёным королём...");
//         TranslationHelper.ModifyIL(il, "Ars Laevateinn prepares to strike!", "Арс Леватейн готовится к удару!");
//         TranslationHelper.ModifyIL(il, "Nalhaun is protected by a shield of frost!", "Налхан защищён щитом мороза!");
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос");
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 2);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 3);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 4);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 5);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 6);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 7);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 8);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 9);
//         TranslationHelper.ModifyIL(il, "Transplacement", "Перенос", 10);
//         TranslationHelper.ModifyIL(il, "Concentrativity", "Концентративность");
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад");
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 2);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 3);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 4);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 5);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 6);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 7);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 8);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 9);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 10);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 11);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 12);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 13);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 14);
//         TranslationHelper.ModifyIL(il, "Heavensfall", "Небесный водопад", 15);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес");
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 2);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 3);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 4);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 5);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 6);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 7);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 8);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 9);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 10);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 11);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 12);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 13);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 14);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 15);
//         TranslationHelper.ModifyIL(il, "A World Rent Asunder", "Разорванный мир");
//         TranslationHelper.ModifyIL(il, "A World Rent Asunder", "Разорванный мир", 2);
//         TranslationHelper.ModifyIL(il, "Surpassing Infinity", "За пределами бесконечности");
//         TranslationHelper.ModifyIL(il, "Surpassing Infinity", "За пределами бесконечности", 2);
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение");
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение", 2);
//         TranslationHelper.ModifyIL(il, "The Flood Of Light", "Поток Света");
//         TranslationHelper.ModifyIL(il, "The Flood Of Light", "Поток Света", 2);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber", "Корусантская сабля");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 2);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 3);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 4);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 5);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 6);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 7);
//         TranslationHelper.ModifyIL(il, "Blazing Skies", "Пылающее небо");
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня");
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 2);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 3);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 4);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 5);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 6);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 7);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 8);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня", 9);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II");
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 2);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 3);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 4);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 5);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 6);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 7);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 8);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов");
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 2);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 3);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 4);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 5);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 6);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 7);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов", 8);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ");
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ", 2);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ", 3);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ", 4);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ", 5);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ", 6);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II");
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 2);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 3);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 4);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 5);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 6);
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II", 7);
//         TranslationHelper.ModifyIL(il, "The Bitter End", "Горький конец");
//         TranslationHelper.ModifyIL(il, "The Bitter End", "Горький конец", 2);
//         TranslationHelper.ModifyIL(il, "The Bitter End", "Горький конец", 3);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок");
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 2);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 3);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 4);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 5);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 6);
//         TranslationHelper.ModifyIL(il, "Shadowblade", "Теневой клинок", 7);
//         TranslationHelper.ModifyIL(il, "Absolute Fire III", "Абсолютный огонь III");
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III");
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III", 2);
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III", 3);
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III", 4);
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III", 5);
//         TranslationHelper.ModifyIL(il, "Terror Unleashed", "Освобождённый ужас");
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь");
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 2);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 3);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 4);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 5);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 6);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 7);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 8);
//         TranslationHelper.ModifyIL(il, "Brain Drain", "Заумь", 9);
//         TranslationHelper.ModifyIL(il, "Ars Laevateinn", "Арс Леватейн");
//         TranslationHelper.ModifyIL(il, "Ars Laevateinn", "Арс Леватейн", 2);
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени");
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени", 2);
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени", 3);
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени", 4);
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени", 5);
//         TranslationHelper.ModifyIL(il, "The Sword of Flames", "Меч пламени", 6);
//         TranslationHelper.ModifyIL(il, "To Ashes", "И пепла не останется");
//         TranslationHelper.ModifyIL(il, "To Ashes", "И пепла не останется", 2);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза");
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза", 2);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза", 3);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза", 4);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза", 5);
//         TranslationHelper.ModifyIL(il, "Absolute Thunder IV", "Абсолютная гроза IV");
//         TranslationHelper.ModifyIL(il, "Quintuplecast", "Пятикратное заклинание");
//         TranslationHelper.ModifyIL(il, "Absolute Holy", "Абсолютная святость");
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо");
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 2);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 3);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 4);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 5);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 6);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 7);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 8);
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо", 9);
//         TranslationHelper.ModifyIL(il, "SOUL Extraction", "Извлечение ДУШИ");
//         TranslationHelper.ModifyIL(il, "Light Rampant", "Раздолье света");
//         TranslationHelper.ModifyIL(il, "Radiant Braver", "Сияющий храбрец");
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв");
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 2);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 3);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 4);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 5);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 6);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 7);
//         TranslationHelper.ModifyIL(il, "Shadowblast", "Теневой взрыв", 8);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат");
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 2);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 3);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 4);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 5);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 6);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 7);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 8);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 9);
//         TranslationHelper.ModifyIL(il, "Absolute Summoning", "Абсолютный призыв");
//     };
// }