// using System.Reflection;
// using CalamityRuTranslate.Common;
// using CalamityRuTranslate.Common.Utilities;
// using CalamityRuTranslate.Core.MonoMod;
// using MonoMod.Cil;
// using StarsAbove;
// using Terraria.ModLoader;
//
// namespace CalamityRuTranslate.Mods.TheStarsAbove.MonoMod;
//
// [JITWhenModsEnabled("StarsAbove")]
// public class StarsAboveDialogueSystemPatch : Patch<ILContext.Manipulator>
// {
//     public override bool AutoLoad => ModsCall.StarsAbove != null && TranslationHelper.IsRussianLanguage;
//
//     public override MethodInfo ModifiedMethod => typeof(StarsAboveDialogueSystem).GetCachedMethod(nameof(StarsAboveDialogueSystem.SetupDialogueSystem));
//
//     protected override ILContext.Manipulator PatchMethod { get; } = il =>
//     {
//         TranslationHelper.ModifyIL(il, "Greetings! I am Asphodene- a Starfarer, and in turn, that makes you my Starbearer.", "");
//         TranslationHelper.ModifyIL(il, "I will lend you my strength so that we may defeat the threats to this world together.", "");
//         TranslationHelper.ModifyIL(il, "You can use the Spatial Disk I've given you to access the Stellar Array, which provides you with powerful abilities after defeating bosses. Nice, right?", "");
//         TranslationHelper.ModifyIL(il, "I've added the 'Bifrost' to your inventory. There's a lot to go over, but in short, it'll let you traverse the galaxy when used. We can talk more about it later.", "");
//         TranslationHelper.ModifyIL(il, "Also, I'll supply you with Essences when I can. Think of them as memories of other worlds. You can combine them with materials to create powerful Aspected Weapons.", "");
//         TranslationHelper.ModifyIL(il, "Right. My power is yours. Let's show this world what we can do.", "");
//         TranslationHelper.ModifyIL(il, "It's nice to meet you. My name is Eridani.. a Starfarer. You, in turn, are my Starbearer.", "");
//         TranslationHelper.ModifyIL(il, "Through this contract, we must work together to bring justice to those willing to harm this world.", "");
//         TranslationHelper.ModifyIL(il, "You can use the Spatial Disk I've given you to access the Stellar Array. It will become stronger after defeating bosses, and will grant you strength in return.", "");
//         TranslationHelper.ModifyIL(il, "I've added the Bifrost to your inventory. At a later date, I can explain what it does, but in short, it will allow traversal of the universe.", "");
//         TranslationHelper.ModifyIL(il, "Furthermore, I will grant you Essences. Essences are otherworldy memories that you can combine with this world's materials to forge Aspected Weapons.", "");
//         TranslationHelper.ModifyIL(il, "My strength is yours... I will not let you down.", "");
//         TranslationHelper.ModifyIL(il, "Sorry, ", "");
//         TranslationHelper.ModifyIL(il, ". Nothing to comment on right now.", "");
//         TranslationHelper.ModifyIL(il, "Sorry, there's not much on my mind as of late.", "");
//         TranslationHelper.ModifyIL(il, "Apologies, ", "");
//         TranslationHelper.ModifyIL(il, ".. there's not much to comment on at the moment.", "");
//         TranslationHelper.ModifyIL(il, "Sorry. There's not much to say right now...", "");
//         TranslationHelper.ModifyIL(il, "My sister likely despises the undead rising every night.", "");
//         TranslationHelper.ModifyIL(il, "What about me? ", "");
//         TranslationHelper.ModifyIL(il, "As long as they have money, it's a benefit to us, right?", "");
//         TranslationHelper.ModifyIL(il, "Those disgusting creatures rising from the earth every night...", "");
//         TranslationHelper.ModifyIL(il, "Ew. Let's dispatch of them quickly. And- be mindful of your hygiene after.", "");
//         TranslationHelper.ModifyIL(il, "It's fine to relax, but you can't forget our end goal, now.", "");
//         TranslationHelper.ModifyIL(il, "Rest is important.. Take as much time as you need.", "");
//         TranslationHelper.ModifyIL(il, "Honestly, I prefer the flashy weapons. A little 'extra' never hurt anyone.", "");
//         TranslationHelper.ModifyIL(il, "Unless you were on the receiving end. ", "");
//         TranslationHelper.ModifyIL(il, "Weapon looks? They matter, but utility far outweighs cosmetic value.", "");
//         TranslationHelper.ModifyIL(il, "Sometimes, though... The choice is difficult. You get what I mean, right?", "");
//         TranslationHelper.ModifyIL(il, "What is a 'Starfarer' you ask? Hmm, there's a lot to go over.", "");
//         TranslationHelper.ModifyIL(il, "In short, we're the manifestation of the universe's will to vanquish threats...?", "");
//         TranslationHelper.ModifyIL(il, "Sorry. I think my memory's a little foggy. Just know I'm on your side, whatever may come.", "");
//         TranslationHelper.ModifyIL(il, "What is a 'Starfarer'? Let me see...", "");
//         TranslationHelper.ModifyIL(il, "Using your terms, we would be referred to as a sort of demigod. The universe calls us into action when needed.", "");
//         TranslationHelper.ModifyIL(il, "That wasn't very helpful? Sorry. I feel like my memories are foggy. Don't fret, though- I'm with you all the way.", "");
//         TranslationHelper.ModifyIL(il, "Don't forget about the Stellar Array!", "");
//         TranslationHelper.ModifyIL(il, "Don't forget about the Stellar Array!", "", 2);
//         TranslationHelper.ModifyIL(il, "It would be a shame if you did. I made it for you, after all.", "");
//         TranslationHelper.ModifyIL(il, "It would be a shame if you did. I made it for you, after all.", "", 2);
//         TranslationHelper.ModifyIL(il, "Have you been utilizing the Stellar Array? It'll help. Wait, forget I said that. Of course you know it'll help...", "");
//         TranslationHelper.ModifyIL(il, "Hmm...", "");
//         TranslationHelper.ModifyIL(il, "Ah, it's nothing. Keep up the good work.", "");
//         TranslationHelper.ModifyIL(il, "...Hm.", "");
//         TranslationHelper.ModifyIL(il, "Ah.. it's nothing.", "");
//         TranslationHelper.ModifyIL(il, "! I have this idea about a weapon..   ", "");
//         TranslationHelper.ModifyIL(il, "Wait.   ", "");
//         TranslationHelper.ModifyIL(il, "Uh.. Never mind. Forget I said anything.  ", "");
//         TranslationHelper.ModifyIL(il, "It would be far too large, to boot. And then there's the whole heating problem... ", "");
//         TranslationHelper.ModifyIL(il, "So, there's this weapon idea I was thinking of, ", "");
//         TranslationHelper.ModifyIL(il, "Wait.. Actually.. Forget it. Never mind.  ", "");
//         TranslationHelper.ModifyIL(il, "Even if we got past the energy cost, we'd have to deal with the weight... ", "");
//         TranslationHelper.ModifyIL(il, "Aren't some of these townspeople kind of awful?", "");
//         TranslationHelper.ModifyIL(il, "Everything costs so much! And they all have a monopoly!!", "");
//         TranslationHelper.ModifyIL(il, "These merchants are definitely upselling their wares for far too much!", "");
//         TranslationHelper.ModifyIL(il, "Do you think they'd notice if we shortchanged them, just a little? We shouldn't do that? I know... ...I know.", "");
//         TranslationHelper.ModifyIL(il, "Have you been utilizing the Stellar Array?", "");
//         TranslationHelper.ModifyIL(il, "So, what's next on the agenda? Let's see..", "");
//         TranslationHelper.ModifyIL(il, "Have you been working on your town? Up for some mining? Ready for the next boss?", "");
//         TranslationHelper.ModifyIL(il, "It's up to you. I'll be here.", "");
//         TranslationHelper.ModifyIL(il, "Mind if I suggest your next move? Um...", "");
//         TranslationHelper.ModifyIL(il, "If you need more town space, there's that. You might also need some more ores, unless you're ready for the next boss?", "");
//         TranslationHelper.ModifyIL(il, "Just suggestions. I trust your judgement.", "");
//         TranslationHelper.ModifyIL(il, "Hmm. Maybe I should think of cooler lines to say.", "");
//         TranslationHelper.ModifyIL(il, "I feel like I'm missing something important.. ", "");
//         TranslationHelper.ModifyIL(il, "I feel like I'm missing something important.. ", "", 2);
//         TranslationHelper.ModifyIL(il, "Ah well. No use worrying about what you can't solve, right?", "");
//         TranslationHelper.ModifyIL(il, "Using the Stellar Novas is rather tiring. ", "");
//         TranslationHelper.ModifyIL(il, "There's a lot of stories about heroes borrowing powers from others, but they never tell you how hard it is on the other side...", "");
//         TranslationHelper.ModifyIL(il, "It's bothering me, but.. It doesn't look like we can solve it now.", "");
//         TranslationHelper.ModifyIL(il, "Ah- I wonder what Eri is doing right about now?", "");
//         TranslationHelper.ModifyIL(il, "I wonder how my sister is faring?  ", "");
//         TranslationHelper.ModifyIL(il, "I'm liking your outfit! I guess we do think alike.", "");
//         TranslationHelper.ModifyIL(il, "Maybe lose the shoes. ", "");
//         TranslationHelper.ModifyIL(il, "Is your armor up to par? Looks-wise, it's... passable.", "");
//         TranslationHelper.ModifyIL(il, "Um, I'll pre-emptively say this: Say anything about my outfit and..", "");
//         TranslationHelper.ModifyIL(il, "I'll probably cry. ", "");
//         TranslationHelper.ModifyIL(il, "What? It's the truth. ", "");
//         TranslationHelper.ModifyIL(il, "After all this is over with, how do you feel about joining me? Think of all the good times we've had already!", "");
//         TranslationHelper.ModifyIL(il, "Uh, yeah. A lot of it was just fighting things.", "");
//         TranslationHelper.ModifyIL(il, "But hey- that was fun too, wasn't it?", "");
//         TranslationHelper.ModifyIL(il, "I could use your aid in the days to come... You wouldn't mind joining me, no?", "");
//         TranslationHelper.ModifyIL(il, "..Maybe we should come back to this conversation. We've still got a long way to go.", "");
//         TranslationHelper.ModifyIL(il, "You're getting pretty strong! Think you can beat me in a fight?", "");
//         TranslationHelper.ModifyIL(il, "That was a joke. You probably could.", "");
//         TranslationHelper.ModifyIL(il, "You just keep getting stronger, huh? I'll have to work harder to keep up.", "");
//         TranslationHelper.ModifyIL(il, "Or not. Theoretically, if we fought, I'd probably win. Don't you think?", "");
//         TranslationHelper.ModifyIL(il, "Don't get any funny ideas, though. We're decidedly on the same team.", "");
//         TranslationHelper.ModifyIL(il, "(I wonder if they caught my bluff.) ", "");
//         TranslationHelper.ModifyIL(il, "I can barely imagine where some of these monsters have come from.", "");
//         TranslationHelper.ModifyIL(il, "Some lich somewhere ate a few bad mushrooms and just went to town, huh? Or maybe a portal to a dimension of primordial soup?", "");
//         TranslationHelper.ModifyIL(il, "Whoever keeps coming up with these foes has no shortage of imagination..", "");
//         TranslationHelper.ModifyIL(il, "Truly... The Hallowed is just a big facade.", "");
//         TranslationHelper.ModifyIL(il, "For such a pretty biome, it REALLY wants to kill you.", "");
//         TranslationHelper.ModifyIL(il, "Strip away the Hallowed's mask, and it may even be harsher than the Underworld itself.", "");
//         TranslationHelper.ModifyIL(il, "If you're off to farm Souls, stay safe. Even the best can can be caught off-guard.", "");
//         TranslationHelper.ModifyIL(il, "We've come a long way..  don't you think?", "");
//         TranslationHelper.ModifyIL(il, "That doesn't mean it's time to stop!", "");
//         TranslationHelper.ModifyIL(il, "Looking back on this journey.. We've come far.", "");
//         TranslationHelper.ModifyIL(il, "And yet, we have so much more to accomplish.", "");
//         TranslationHelper.ModifyIL(il, "This endless light is awful... There must be some way to stop it.", "");
//         TranslationHelper.ModifyIL(il, "Perseus told us to use the 'Progenitor's Wish.' Perhaps it holds the key?", "");
//         TranslationHelper.ModifyIL(il, "This everlasting light is dreadful...", "");
//         TranslationHelper.ModifyIL(il, "Perseus gave us the 'Progenitor's Wish.' I feel that it may hold the key to solving this mystery.", "");
//         TranslationHelper.ModifyIL(il, ", you've made it! This place is the Observatory Hyperborea; our base of operations, if you will.", "");
//         TranslationHelper.ModifyIL(il, "There are quite a few Observatories around the galaxy, but we call this one home. It's not the source of our power, but acts like a magnifying glass of sorts.", "");
//         TranslationHelper.ModifyIL(il, "Here, we can search the universe for heavy concentrations of mana, which is usually a bad sign. Think of it like clouds before a storm.", "");
//         TranslationHelper.ModifyIL(il, "Enough about us. You're probably wondering what YOU can do in the Observatory, right? Let me tell you. ", "");
//         TranslationHelper.ModifyIL(il, "By accessing the Gateway, you can travel to other worlds. I'm sure you can already see the practical purpose of that.", "");
//         TranslationHelper.ModifyIL(il, "There may not be many worlds open right now, but I have a feeling when we defeat powerful foes, more places will be available. Good luck!", "");
//         TranslationHelper.ModifyIL(il, ", welcome. This place is the Observatory Hyperborea; both Asphodene and I live here.", "");
//         TranslationHelper.ModifyIL(il, "There are a few Observatories located around the galaxy, but this is ours. Its main function is an amplifier for our power, to an extent.", "");
//         TranslationHelper.ModifyIL(il, "Here, we can search the universe for heavy concentrations of mana, which is kind of like an omen for trouble. It works out more than you'd think.", "");
//         TranslationHelper.ModifyIL(il, "You're probably wondering about what you can use this Observatory for, right? Let's see...", "");
//         TranslationHelper.ModifyIL(il, "By accessing the Gateway, you can travel to other worlds. I needn't elaborate on the utility of that, right?", "");
//         TranslationHelper.ModifyIL(il, "There may not be many worlds open right now, but I have a feeling when we defeat powerful foes, more worlds will open.. Hopefully.", "");
//         TranslationHelper.ModifyIL(il, "Yeah, I wondered when you would ask about the crates and stuff around the Observatory. Well, unlike the original owners, we need to eat, obviously.", "");
//         TranslationHelper.ModifyIL(il, "Wait, did you seriously think we didn't have to eat? That would be awful.    ", "");
//         TranslationHelper.ModifyIL(il, "Oh, the crates around the Observatory? It's mostly food. Did you think we didn't have to eat? We'd be missing out on a lot.", "");
//         TranslationHelper.ModifyIL(il, "As long as we plan on staying here, we'll need supplies. Lucky for us, the galaxy has no shortage of abandoned planets to loot. I mean... they're not using it anymore.", "");
//         TranslationHelper.ModifyIL(il, "It's about time I explained Cosmic Voyages. Do you see that blue thing in the Observatory? If you step on it, it'll create a Gateway that you can use the Bifrost on.", "");
//         TranslationHelper.ModifyIL(il, "Once you're on the voyage, you can't break or place anything. Also, you can't fly or mount. If you'd like to get around, try conventional methods, like a grappling hook.", "");
//         TranslationHelper.ModifyIL(il, "You have to use the Bifrost at the Gateway to return to the Observatory. Take care that  you don't get stuck, because.. Self-explanatory. How about keeping a Magic Mirror handy?", "");
//         TranslationHelper.ModifyIL(il, "Remember that you're visiting harsh places and not everything is friendly. You'll most likely be inflicted with some sort of Environmental  Turmoil, which will affect your stats.", "");
//         TranslationHelper.ModifyIL(il, "This is important: any abilities that have become stronger after defeating foes will be significantly weaker. It's the downside of travelling so far away from the Observatory.", "");
//         TranslationHelper.ModifyIL(il, "Once you've initiated the Voyage, it'll take a little while until you can go on another one. Make every journey count. Good luck out there!", "");
//         TranslationHelper.ModifyIL(il, "Okay. I'm going to brief you on Cosmic Voyages. Do you see that blue platform? Stepping on it will create a Gateway that you can use the Bifrost on to initiate transit.", "");
//         TranslationHelper.ModifyIL(il, "You can't break or place blocks during the Voyage. Mounts and flying are also a no-go. You'll have to resort to things like a grappling hook to navigate.", "");
//         TranslationHelper.ModifyIL(il, "If you'd like to return to the Observatory, you have to use the Bifrost near the Gateway. Take care to not get trapped away from the Gateway, or bring a Magic Mirror.", "");
//         TranslationHelper.ModifyIL(il, "Remember that you're visiting harsh locales and not everything is friendly. You'll most likely be inflicted with a kind of Environmental Turmoil, which will affect your physique.", "");
//         TranslationHelper.ModifyIL(il, "After you begin a Cosmic Voyage, you'll have to wait a little while until you can initiate another. You should make every excursion count.", "");
//         TranslationHelper.ModifyIL(il, "There's one last thing. Anything that has become stronger after defeating powerful foes will be weaker. It's an unfortunate side-effect of travelling so far away from the Observatory.", "");
//         TranslationHelper.ModifyIL(il, "You're wondering how you can breathe? Simple. The Bifrost is protecting you!", "");
//         TranslationHelper.ModifyIL(il, "It draws ambient mana from nearby planets to sustain bodily functions. You can't tell me that doesn't sound neat- just don't fall too far from solid ground.", "");
//         TranslationHelper.ModifyIL(il, "Eh? You're wondering how you can breathe? Ah, that would be the Bifrost you used to reach the Observatory. Right.. I should've probably explained that.", "");
//         TranslationHelper.ModifyIL(il, "It draws ambient mana from nearby planets and converts it to aether. It should prove ample enough for your journey. Just remember that 'down' is a perspective thing.", "");
//         TranslationHelper.ModifyIL(il, "You've defeated the Slime King, huh? Good job.", "");
//         TranslationHelper.ModifyIL(il, "It may have been rather weak, but it's a surefire step forwards nevertheless.", "");
//         TranslationHelper.ModifyIL(il, "Did anyone else see that ninja thing? Was it just me?", "");
//         TranslationHelper.ModifyIL(il, "Somehow.. it was strong enough to unlock a part of the Stellar Array! Check it out later, OK?", "");
//         TranslationHelper.ModifyIL(il, "...Well, that's all for now. Keep it up.", "");
//         TranslationHelper.ModifyIL(il, "It may have seemed weak, but the Slime King was truly quite the threat.", "");
//         TranslationHelper.ModifyIL(il, "Let's hope it stays dead.", "");
//         TranslationHelper.ModifyIL(il, "Something about this foe has unlocked a part of the Stellar Array. Perhaps it was fiercer than usual?", "");
//         TranslationHelper.ModifyIL(il, "However, if it does return, you should be able to easily defeat it anew.", "");
//         TranslationHelper.ModifyIL(il, "'Eye of Cthulhu'?", "");
//         TranslationHelper.ModifyIL(il, "Doesn't that imply there would be more of this 'Cthulhu'?", "");
//         TranslationHelper.ModifyIL(il, "If it ever reared its head, it would be quite the formidable foe indeed.", "");
//         TranslationHelper.ModifyIL(il, "Let's prepare for that occasion... Just in case.", "");
//         TranslationHelper.ModifyIL(il, "Hey.. defeating that foe was enough! Looks like an ability in the Stellar Array is ready.", "");
//         TranslationHelper.ModifyIL(il, "For how fearsome it looked, the Eye of Cthulhu wasn't too terrible, was it?", "");
//         TranslationHelper.ModifyIL(il, "It seems to have shed its skin to display quite an array of teeth. If I didn't know better, it looked like it was trying to prove something. Weirdo.", "");
//         TranslationHelper.ModifyIL(il, "I have a suspicion that it's materials can be utilized later on. Simply keep it in mind.", "");
//         TranslationHelper.ModifyIL(il, "In other news.. an ability in the Stellar Array is now available. Use it well.", "");
//         TranslationHelper.ModifyIL(il, "Huh. I guess there really was more 'Cthulhu.' Somehow, it doesn't suprise me as much as I would have thought.", "");
//         TranslationHelper.ModifyIL(il, "Glad we stopped that thing before it lived up to its name. ", "");
//         TranslationHelper.ModifyIL(il, "Those materials are... something... Wow. How bloody.", "");
//         TranslationHelper.ModifyIL(il, "Hey, the weapons that you can make from it look pretty powerful! What do you think?", "");
//         TranslationHelper.ModifyIL(il, "In other news... Looks like an ability has unlocked in the Stellar Array! You should definitely consider it.", "");
//         TranslationHelper.ModifyIL(il, "Another organ of this 'Cthulhu' and it attacked with magical manipulation... Also- yuck?", "");
//         TranslationHelper.ModifyIL(il, "This 'Eater of Worlds' was just a big worm. I'm kind of disappointed. Let's file a complaint with whichever clown named this thing.", "");
//         TranslationHelper.ModifyIL(il, "Looks like it unlocked an ability in the Stellar Array. Look it over when you're free.", "");
//         TranslationHelper.ModifyIL(il, "Well, I guess I should have expected something like this within the Jungle.", "");
//         TranslationHelper.ModifyIL(il, "Good work. Looks like another ability is unlocked in the Stellar Array as well.", "");
//         TranslationHelper.ModifyIL(il, "Seriously? A giant bee... Somehow, I might prefer it over smaller insects... Easier to hit, you know.", "");
//         TranslationHelper.ModifyIL(il, "Ahem. At the very least, it unlocked an ability in the Stellar Array", "");
//         TranslationHelper.ModifyIL(il, "The Clothier was truly a gigantic evil skeleton monster.. Cute. At the very least, you have access to the Dungeon now.", "");
//         TranslationHelper.ModifyIL(il, "And with this, another ability is unlocked in the Stellar Array.", "");
//         TranslationHelper.ModifyIL(il, "Well, that's all for now!", "");
//         TranslationHelper.ModifyIL(il, "That poor soul, cursed to become Skeletron. It seems his departure has granted us access to the Dungeon. This may be in bad taste, but...", "");
//         TranslationHelper.ModifyIL(il, "If the embodiment of your emotions is a huge evil skeleton monster... maybe the curse wasn't the sole factor.", "");
//         TranslationHelper.ModifyIL(il, "If anyone asks, you didn't hear that from me.", "");
//         TranslationHelper.ModifyIL(il, "Whoa.. I've never seen anything like this.. ever. The entire world seems to be bursting with new magical energy. ", "");
//         TranslationHelper.ModifyIL(il, "It looks like the Wall of Flesh was either guarding or preventing something drastic from happening. That's my take on it.", "");
//         TranslationHelper.ModifyIL(il, "Just to let you know, there's another upgrade in the Stellar Array now. It seems to be more powerful than the ones you've used before.", "");
//         TranslationHelper.ModifyIL(il, "Also, it seems to have dropped something.. Whatever it is, it feels.. familiar. Did I forget about something? No, that isn't it. Please be careful.", "");
//         TranslationHelper.ModifyIL(il, "Wow.. the world itself seems to have been drastically altered after the defeat of the Wall of Flesh...", "");
//         TranslationHelper.ModifyIL(il, "I've never seen anything like it. What was this thing hiding...?", "");
//         TranslationHelper.ModifyIL(il, "This power seems to have activated the first Tier 2 ability in the Stellar Array. I hope you can utilize it well.", "");
//         TranslationHelper.ModifyIL(il, "Something else dropped from it. I'm not sure what it is, but it feels like I should know. Please be mindful of the danger...", "");
//         TranslationHelper.ModifyIL(il, "So someone went and made two Eyes instead of one? Good for them, but in my opinion, the design is kind of ruined already.", "");
//         TranslationHelper.ModifyIL(il, "If you're going to make a robot eye, try and hide the obvious weak spot where the iris is. Well, I don't create giant evil robotic eyes, so maybe they know something..?", "");
//         TranslationHelper.ModifyIL(il, "It looks as if another upgrade is available in the Stellar Array. That's it for now.", "");
//         TranslationHelper.ModifyIL(il, "That's it for now.", "");
//         TranslationHelper.ModifyIL(il, "Well, those mechanical facsimiles are dead. We're not rating boss monsters, or anything, but... I'm going to have to dock some points.", "");
//         TranslationHelper.ModifyIL(il, "I'm giving it a 5/10. The sheet metal plating was a good start, but why would you ever even think about using flesh for the exterior? Whatever.", "");
//         TranslationHelper.ModifyIL(il, "It looks as if yet another upgrade is available in the Stellar Array. How serendipitous.", "");
//         TranslationHelper.ModifyIL(il, "It looks as if yet another upgrade is available in the Stellar Array. How serendipitous.", "", 2);
//         TranslationHelper.ModifyIL(il, "It looks as if yet another upgrade is available in the Stellar Array. How serendipitous.", "", 3);
//         TranslationHelper.ModifyIL(il, "That's all for now.", "");
//         TranslationHelper.ModifyIL(il, "'The Destroyer...' I'm not one to talk, but if you name something 'The Destroyer' I'm gonna expect more than a big worm.", "");
//         TranslationHelper.ModifyIL(il, "Its absurd length was just a detriment to its strength. I hope whoever makes these things is taking note.", "");
//         TranslationHelper.ModifyIL(il, "It looks as if another upgrade is available in the Stellar Array. That's all, ", "");
//         TranslationHelper.ModifyIL(il, "It looks as if another upgrade is available in the Stellar Array. That's all, ", "", 2);
//         TranslationHelper.ModifyIL(il, "That's everything, ", "");
//         TranslationHelper.ModifyIL(il, "I guess the Destroyer was more bark than bite, huh. Maybe too much of the budget was spent on the design aspect.", "");
//         TranslationHelper.ModifyIL(il, "Whatever the case, it's gone now, so no use comtemplating it.", "");
//         TranslationHelper.ModifyIL(il, "Well, that's everything. Unless you wanted to chat?", "");
//         TranslationHelper.ModifyIL(il, "You've done it! Skeletron Prime has been defeated. I can definitely say it was a step up from 'Version 1.0.'", "");
//         TranslationHelper.ModifyIL(il, "The appendages were a smart idea, but it still lacked a proper body. A shame.", "");
//         TranslationHelper.ModifyIL(il, "Well, that's everything I wanted to say, ", "");
//         TranslationHelper.ModifyIL(il, "And that takes care of Skeletron Prime. It certainly looked the part... if you're a total edgelord.", "");
//         TranslationHelper.ModifyIL(il, "If you took offense, I apologize. You can be as edgy as you want. Uh, I mean.. anyways... ", "");
//         TranslationHelper.ModifyIL(il, "That's all for now, ", "");
//         TranslationHelper.ModifyIL(il, "That's all for now, ", "", 2);
//         TranslationHelper.ModifyIL(il, "That's all for now, ", "", 3);
//         TranslationHelper.ModifyIL(il, "Actually.. It looks like you've bested all the Mechanical Bosses! This is definitely a step forward.", "");
//         TranslationHelper.ModifyIL(il, "This victory has lead to another upgrade in- you guessed it, the Stellar Array. ", "");
//         TranslationHelper.ModifyIL(il, "It seems that was the last of the Mechanical Bosses. This is a great step forward! ", "");
//         TranslationHelper.ModifyIL(il, "This victory has brought another upgrade to the Stellar Array. ", "");
//         TranslationHelper.ModifyIL(il, "And there it goes.. the terror of the jungle, Plantera. Congratulations on your victory. ", "");
//         TranslationHelper.ModifyIL(il, "I sense the Dungeon has changed... and the Jungle Temple is now available. It's your choice what to tackle next.", "");
//         TranslationHelper.ModifyIL(il, "Another upgrade is now available in the Stellar Array.  ", "");
//         TranslationHelper.ModifyIL(il, "That marks the end of Plantera. Very good work. You should be able to access the Jungle Temple now.", "");
//         TranslationHelper.ModifyIL(il, "I also believe there's new materials to be found within the Dungeon. Great for us, not so much for them. Tough luck.", "");
//         TranslationHelper.ModifyIL(il, "Another upgrade has been unlocked in the Stellar Array.", "");
//         TranslationHelper.ModifyIL(il, "You've done it! Golem is no more. You're unstoppable.  ", "");
//         TranslationHelper.ModifyIL(il, "Something about our next enemy feels.. dangerous. It seems spatial energy has congregated around the Dungeon's entrance.", "");
//         TranslationHelper.ModifyIL(il, "Another upgrade is now available in the Stellar Array. Looks pretty strong.", "");
//         TranslationHelper.ModifyIL(il, ". Stay prepared.", "");
//         TranslationHelper.ModifyIL(il, "The Lizhard Temple's beast Golem is confirmed dead.  In terms of mechanical beasts, I'm kind of.. disappointed? ", "");
//         TranslationHelper.ModifyIL(il, "Something strange has appeared in front of the Dungeon. It seems otherwordly in nature... Be prepared for anything.", "");
//         TranslationHelper.ModifyIL(il, "Another upgrade is now available in the Stellar Array. It will surely be useful.", "");
//         TranslationHelper.ModifyIL(il, ". Stay safe.", "");
//         TranslationHelper.ModifyIL(il, "Such a powerful creature hiding deep within the Ocean.. Luckily, you avoided being turned into fish food. ", "");
//         TranslationHelper.ModifyIL(il, "Where did that saying even come from..? What IS fish food? More important questions left unanswered...", "");
//         TranslationHelper.ModifyIL(il, "Duke Fishron has been defeated. That was a close one, but you've o-fish-ally won. ...", "");
//         TranslationHelper.ModifyIL(il, "I might have fished too hard for that one. You know what..? Let's leave the puns to Asphodene. I guess there's a certain skill to it.", "");
//         TranslationHelper.ModifyIL(il, "It is as I feared... The Celestial Pillars have appeared upon this land. They herald the coming of the end.. The Moon Lord.", "");
//         TranslationHelper.ModifyIL(il, "Don't lose hope, though. We can beat this. The experiences you had.. The battles you've fought.. they will culminate in this ultimate encounter.", "");
//         TranslationHelper.ModifyIL(il, "At the very least, you have another ability ready in the Stellar Array. It will definitely help.", "");
//         TranslationHelper.ModifyIL(il, "Be ready for anything. This will be the fight of our lives.", "");
//         TranslationHelper.ModifyIL(il, "I knew it.. the Celestial Pillars have descended. This does not bode well for this world.", "");
//         TranslationHelper.ModifyIL(il, "All hope is not lost, however. If there is anyone who could confront the Moon Lord, it is you. I will be by your side.", "");
//         TranslationHelper.ModifyIL(il, "At the very least, the Stellar Array has a new ability available. Let us hope it will come in handy. ", "");
//         TranslationHelper.ModifyIL(il, "The ultimate battle approaches... Steel yourself.", "");
//         TranslationHelper.ModifyIL(il, "! You've done it! The Moon Lord.. has been vanquished! You have done this world a great service. ", "");
//         TranslationHelper.ModifyIL(il, "We've come a long way. You have grown stronger than I have ever imagined. However, I can sense it isn't over yet.", "");
//         TranslationHelper.ModifyIL(il, "The defeat of the Moon Lord has upgraded your Stellar Array twice! Such power...", "");
//         TranslationHelper.ModifyIL(il, "The Moon Lord's defeat has strengthened your Stellar Array. A reward well deserved.", "");
//         TranslationHelper.ModifyIL(il, "The light has grown incredibly harsh. This power... it's somehow like yours..  ", "");
//         TranslationHelper.ModifyIL(il, "The Moon Lord has been defeated.. What a wonderful victory. ", "");
//         TranslationHelper.ModifyIL(il, "You have grown incredibly strong.. This world owes you for its survival. And yet.. I feel something is off.", "");
//         TranslationHelper.ModifyIL(il, "The Moon Lord has granted us two new abilities in the Stellar Array. The power is.. overwhelming.", "");
//         TranslationHelper.ModifyIL(il, "I fear our journey isn't over yet. We must press onwards. A new ability in the Stellar Array may help with that.", "");
//         TranslationHelper.ModifyIL(il, "The light has grown incredibly harsh. Something about it.. It reminds me of.. you? ", "");
//         TranslationHelper.ModifyIL(il, "I see we were wrong.. The Warrior thought he was saving the universe, but it was truly the lies of the First Starfarer.. How cruel.", "");
//         TranslationHelper.ModifyIL(il, "The Warrior of Light.. The original Starbearer has been led astray. He managed to get away, but... Night has returned to this world, finally!", "");
//         TranslationHelper.ModifyIL(il, "We finally have the last piece of the puzzle. The First Starfarer showed her hand, and this means we have a chance.", "");
//         TranslationHelper.ModifyIL(il, "Once you've collected all the Mnemonic Traces, use it within the Observatory. It will take us straight to the First Starfarer.", "");
//         TranslationHelper.ModifyIL(il, "I probably don't need to tell you this, but she's not going to parley. Prepare for a hard fight.. Perhaps the hardest fight so far.", "");
//         TranslationHelper.ModifyIL(il, "The Warrior of Light has strengthened your Stellar Array. Hopefully it'll be enough... ", "");
//         TranslationHelper.ModifyIL(il, "You have brought down the Warrior of Light. He's managed to escape, but nighttime has returned to this world regardless.", "");
//         TranslationHelper.ModifyIL(il, "It seems we were misguided. The Warrior believed he was saving the universe, but it was, in truth, all lies from his Starfarer.", "");
//         TranslationHelper.ModifyIL(il, "With this final Mnemonic Trace.. I see.. It all makes sense now. ", "");
//         TranslationHelper.ModifyIL(il, ", I need to you combine all of the Mnemonic Traces together.", "");
//         TranslationHelper.ModifyIL(il, "It will lead us directly to the First Starfarer through the Observatory. After that.. We must defeat her. At any cost. Prepare yourself well.", "");
//         TranslationHelper.ModifyIL(il, "Anyways... The radiance of the Warrior has upgraded the Stellar Array. That's definitely a boon.", "");
//         TranslationHelper.ModifyIL(il, "Remember: the First Starfarer. We can not let this opportunity slip away. This will likely be the fight of our lives.. Prepare yourself well.", "");
//         TranslationHelper.ModifyIL(il, ".. You've defeated so many powerful foes... You must be nearing the pinnacle of your powers!", "");
//         TranslationHelper.ModifyIL(il, "I've granted you a special ability in the Stellar Array. Use it wisely.", "");
//         TranslationHelper.ModifyIL(il, "And, a special gift. This is the crystallized power of the Starfarers. The weapon born from it will be incredibly powerful!", "");
//         TranslationHelper.ModifyIL(il, "The enemies of this world shudder when they feel your presence.. You are the hero of this land.", "");
//         TranslationHelper.ModifyIL(il, "I'm proud. You have become  stronger than I would have ever imagined..", "");
//         TranslationHelper.ModifyIL(il, "This is a gift from me to you. It's a special ability in the Stellar Array. Use it well.", "");
//         TranslationHelper.ModifyIL(il, "One more thing. The crystallized power of the Starfarers.. It should be able to make an incredibly strong weapon.", "");
//         TranslationHelper.ModifyIL(il, "You've done it. This world is free.. All that threatens it is no more. Seriously, this is a incredible achievement.", "");
//         TranslationHelper.ModifyIL(il, "Don't worry. I'm not going anywhere yet. Who knows what might crop up? ", "");
//         TranslationHelper.ModifyIL(il, "I have an Essence for you... It is the strongest Essence I have. Be sure to treat the finished product with care.", "");
//         TranslationHelper.ModifyIL(il, "Your overwhelming power has activated the final ability within the Stellar Array. It's done.. finally!", "");
//         TranslationHelper.ModifyIL(il, "You've done it, ", "");
//         TranslationHelper.ModifyIL(il, ". Seriously.. I can't believe it. Everything threatening this world has been bested by your hand.", "");
//         TranslationHelper.ModifyIL(il, "I'll stay for now, though. Just in case anything else appears, though. It's not like I'd miss you or anything.", "");
//         TranslationHelper.ModifyIL(il, "This is a first.. Your own strength has activated the final. ability in the Stellar Array. Finally. Nothing else to unlock.", "");
//         TranslationHelper.ModifyIL(il, "Lastly... This Essence that I have given you.. It is the strongest weapon I know. Good luck creating it, ", "");
//         TranslationHelper.ModifyIL(il, "I see... Please, excuse my test. I know it was crude, but it's the only way I know how to judge someone. ", "");
//         TranslationHelper.ModifyIL(il, "I see... Please, excuse my test. I know it was crude, but it's the only way I know how to judge someone. ", "", 2);
//         TranslationHelper.ModifyIL(il, "In reality, I should have known. My sisters would never choose unwisely. ", "");
//         TranslationHelper.ModifyIL(il, "In reality, I should have known. My sisters would never choose unwisely. ", "", 2);
//         TranslationHelper.ModifyIL(il, "Huh? Sister? ...No way... ", "");
//         TranslationHelper.ModifyIL(il, "I apologize, Asphodene. This should help. ", "");
//         TranslationHelper.ModifyIL(il, "Ring any bells?  ", "");
//         TranslationHelper.ModifyIL(il, "Ring any bells?  ", "", 2);
//         TranslationHelper.ModifyIL(il, "Perseus... We seriously have to stop meeting like this. ", "");
//         TranslationHelper.ModifyIL(il, "Please, ", "");
//         TranslationHelper.ModifyIL(il, "Please, ", "", 2);
//         TranslationHelper.ModifyIL(il, ", let me explain. In tandem with our galaxy's myriad worlds, there exists Starfarers to aid their denizens. You are familiar with what we do.", "");
//         TranslationHelper.ModifyIL(il, ", let me explain. In tandem with our galaxy's myriad worlds, there exists Starfarers to aid their denizens. You are familiar with what we do.", "", 2);
//         TranslationHelper.ModifyIL(il, "However, the First Starfarer's nominee was... unfitting for their role. This is the First Starbearer. Their morals dissolved as time went on...", "");
//         TranslationHelper.ModifyIL(il, "However, the First Starfarer's nominee was... unfitting for their role. This is the First Starbearer. Their morals dissolved as time went on...", "", 2);
//         TranslationHelper.ModifyIL(il, "Now, they continue to roam the galaxy, the Starfarer a thrall to their chosen one's agenda. They 'pursue good' through any means necessary, often with casualties.", "");
//         TranslationHelper.ModifyIL(il, "Now, they continue to roam the galaxy, the Starfarer a thrall to their chosen one's agenda. They 'pursue good' through any means necessary, often with casualties.", "", 2);
//         TranslationHelper.ModifyIL(il, "This is all conjecture, but the destruction is very real. It should go unsaid that we can't let this continue. I'll need your help in the future.", "");
//         TranslationHelper.ModifyIL(il, "This is all conjecture, but the destruction is very real. It should go unsaid that we can't let this continue. I'll need your help in the future.", "", 2);
//         TranslationHelper.ModifyIL(il, "Asphodene doesn't know it, but she's missing her true power. I can share it with her. She should now be able to cast Stellar Novas.", "");
//         TranslationHelper.ModifyIL(il, "...It is done. I must continue to track the First Starbearer. I know you will save this galaxy. Good luck- we will meet again.", "");
//         TranslationHelper.ModifyIL(il, "...It is done. I must continue to track the First Starbearer. I know you will save this galaxy. Good luck- we will meet again.", "", 2);
//         TranslationHelper.ModifyIL(il, "I know he's a loner, but.. I wish we could have spoken more. Stay safe, Perseus. ", "");
//         TranslationHelper.ModifyIL(il, "I can feel my power returning- and my hair's gone all shiny! This power should be an amazing boon going forward. ", "");
//         TranslationHelper.ModifyIL(il, "My Stellar Nova is called Theofania Inanis. Perhaps we will be able to utilize more once we become stronger.", "");
//         TranslationHelper.ModifyIL(il, "My Stellar Nova is called Theofania Inanis. Perhaps we will be able to utilize more once we become stronger.", "", 2);
//         TranslationHelper.ModifyIL(il, "After binding the Stellar Nova Key, you should be able to equip the Stellar Nova through the Spatial Disk, like usual.", "");
//         TranslationHelper.ModifyIL(il, "After binding the Stellar Nova Key, you should be able to equip the Stellar Nova through the Spatial Disk, like usual.", "", 2);
//         TranslationHelper.ModifyIL(il, "You should have some Prismatic Cores already. With their power, you can upgrade Stellar Novas with crafting.", "");
//         TranslationHelper.ModifyIL(il, "This is important. You need Stellar Nova energy to cast Novas. You gain Nova energy in combat. It depletes outside of combat.", "");
//         TranslationHelper.ModifyIL(il, "OK. A lot has happened, but this is a huge step forward for us. Please use the Novas well! Bye for now.", "");
//         TranslationHelper.ModifyIL(il, "Did you just say... 'sister'? You've got to be kidding... ", "");
//         TranslationHelper.ModifyIL(il, "I apologize, Eridani. This should help. ", "");
//         TranslationHelper.ModifyIL(il, "Perseus.. We haven't talked in ages.. ", "");
//         TranslationHelper.ModifyIL(il, "Eridani doesn't know it, but she's missing her true power. I can share it with her. She should now be able to cast Stellar Novas.", "");
//         TranslationHelper.ModifyIL(il, "Perseus was never one for sticking around. I wish we could have spoken more... This power is familiar, but I need to get used to it. ", "");
//         TranslationHelper.ModifyIL(il, "With Prismatic Cores, you can craft upgrades to the Stellar Nova. You can affix them in the menu directly.", "");
//         TranslationHelper.ModifyIL(il, "Don't forget: You need Stellar Nova Energy to cast Stellar Novas. You can only accrue Energy in combat.", "");
//         TranslationHelper.ModifyIL(il, "That's about it.. I know it's a lot to process, but please use the Novas well. That's all for now.", "");
//         TranslationHelper.ModifyIL(il, "...Did my hair just change color?  ", "");
//         TranslationHelper.ModifyIL(il, "So that was the Burnished King. His blade was incredibly powerful, not to mention the magic at his disposal. It was a triumph you survived that.", "");
//         TranslationHelper.ModifyIL(il, "From what Perseus told me, it looks like the Burnished King was defeated by the First Starbearer. ", "");
//         TranslationHelper.ModifyIL(il, "As for why he told US to fight, I don't know. However.. I found this shard of power after the battle. I'll let you hold on to it. Anyways..", "");
//         TranslationHelper.ModifyIL(il, "I think we can reuse his attacks as a weapon in our arsenal, as a new Stellar Nova. Maybe because of the Starbearer's influence?", "");
//         TranslationHelper.ModifyIL(il, "Let's not forget. We've also unlocked a new Stellar Array ability. his is a great victory!", "");
//         TranslationHelper.ModifyIL(il, "The Burnished King has fallen. What a powerful foe. I shudder to think how we would have fared had we fought him in his prime.", "");
//         TranslationHelper.ModifyIL(il, "From what Perseus told me, The Burnished King was laid low by the First Starbearer ages ago. ", "");
//         TranslationHelper.ModifyIL(il, "As for why he told us to fight him, I don't know. However.. I found this shard after the battle. I'll let you hold on to it. Anyways..", "");
//         TranslationHelper.ModifyIL(il, "His weapon, Ars Laevateinn. We can use it for ourselves, as a Stellar Nova. Maybe because of the Starbearer's influence?", "");
//         TranslationHelper.ModifyIL(il, "One more thing. We've gained a new Stellar Array power. That should be everything. ", "");
//         TranslationHelper.ModifyIL(il, "Penthesilea, was it? She was quite the challenge. What a unique way of casting magic. ", "");
//         TranslationHelper.ModifyIL(il, "Her magic overflows with spatial power. It looks like the First Starbearer's  influence is here, meaning we can use a new Stellar Nova.", "");
//         TranslationHelper.ModifyIL(il, "The battle left behind this mysterious object. You can hold on to it for now.  ", "");
//         TranslationHelper.ModifyIL(il, "You've bested the Witch of Ink. She was quite the magic user, no? It's truly a shame she was hostile. ", "");
//         TranslationHelper.ModifyIL(il, "Her powerful magic... We can use it for ourselves as a new Nova. It must be from the remnants of the First Starbearer Perseus mentioned...", "");
//         TranslationHelper.ModifyIL(il, "The battle left behind this mysterious shard. I'll entrust it to you.  ", "");
//         TranslationHelper.ModifyIL(il, "That foe was truly fearful. I'm glad you were able to defeat it... Who knows what chaos it would bring if left unchecked?", "");
//         TranslationHelper.ModifyIL(il, "We can re-appropriate its strength, I think. It can become a new Stellar Nova, thanks to the First Starbearer's influence. Let's use it well.", "");
//         TranslationHelper.ModifyIL(il, "It looks like another item has appeared. You can have it- it's probably better off in your hands, anyways. ", "");
//         TranslationHelper.ModifyIL(il, "You have defeated that monstrocity! The world is better because of your deeds. If we failed, the world itself may have been consumed by the void.", "");
//         TranslationHelper.ModifyIL(il, "We can use his overwhelming strength... It has manifested as a new Stellar Nova, thanks to the First Starbearer's influence. ", "");
//         TranslationHelper.ModifyIL(il, "It looks like another shard has appeared. I'll leave it to you.  ", "");
//         TranslationHelper.ModifyIL(il, "It.. it's over. Tsukiyomi has vanished. We're still missing so many clues... She doesn't seem evil... so what caused her to do what she did?", "");
//         TranslationHelper.ModifyIL(il, "Hopefully one day, we'll find the answers to the questions we seek.   ", "");
//         TranslationHelper.ModifyIL(il, "I've gathered some of the leftover residue from the fight. It will likely have use as a stand-in to an Essence, for creating a  weapon.", "");
//         TranslationHelper.ModifyIL(il, "With this victory.. the universe is safe. There may be more evils ahead, but know that nothing is insurmountable. We've come this far.", "");
//         TranslationHelper.ModifyIL(il, "We've finally done it. Tsukiyomi's defeat has been confirmed. She's gone, but hopefully our troubles with her are at an end.", "");
//         TranslationHelper.ModifyIL(il, "What ails me is her motives... She did horrible things... but was it malice, or a greater purpose...? I hope we find the answer.", "");
//         TranslationHelper.ModifyIL(il, "I've gone through the work of absorbing some residue energy and have turned it into the Spatial Memoriam. You can use it like an Essence.", "");
//         TranslationHelper.ModifyIL(il, "The universe is safe. There is still work to do, but take heart; if we've come this far, nothing can stop us now.", "");
//         TranslationHelper.ModifyIL(il, "That's that. Queen Slime is defeated. What have we learned today? Apparently there's a royal court of slimes, and the King Slime wasn't just an outlier. ", "");
//         TranslationHelper.ModifyIL(il, "That doesn't even make any sense. They're slime. I literally, actually, seriously don't even think slime has the capacity to think. ", "");
//         TranslationHelper.ModifyIL(il, "Who knows.   ", "");
//         TranslationHelper.ModifyIL(il, "Right, we've defeated the Queen Slime. To be honest, I'm slightly curious: why are there 'kings' and 'queens' of the slime world? ", "");
//         TranslationHelper.ModifyIL(il, "How much power do the royal slimes even have? Are they legitimate rulers? ", "");
//         TranslationHelper.ModifyIL(il, "Does the royal slime court send their subjects to attack random people? Do they even have the right to own property?", "");
//         TranslationHelper.ModifyIL(il, "Fight back, oppressed slimes! Take back your freedom!", "");
//         TranslationHelper.ModifyIL(il, "Great work- the Empress of Light is no more. Nobody else is going to say it, so I will-  did it have a big nose, or was it smiling? I couldn't tell.  ", "");
//         TranslationHelper.ModifyIL(il, "Maybe if she stood still at all... ", "");
//         TranslationHelper.ModifyIL(il, "Congratulations, you've bested the Empress of Light. Let's leave the bugs alone now, okay?   ", "");
//         TranslationHelper.ModifyIL(il, "If I had a nickel for bosses summoned with insects... We fought that rather large fish, right? That's two. Not very much, is it. I was hoping for a trend. ", "");
//         TranslationHelper.ModifyIL(il, "If I had a nickel for bosses summoned with insects... We fought that rather large fish, right? That's two. Not very much, is it. I was hoping for a trend. Maybe we can count the Queen Bee?", "");
//         TranslationHelper.ModifyIL(il, "Somehow... I feel like there's yet another boss we'll have to use an insect to summon. That's going to be rather bothersome. ", "");
//         TranslationHelper.ModifyIL(il, "Okay, we've taken care of that strange abomination.  I have no idea where it even came from.   ", "");
//         TranslationHelper.ModifyIL(il, "I'm getting rather hungry- how about we go find something to eat so that we don't starve...? Pfft. ", "");
//         TranslationHelper.ModifyIL(il, "Great work- you've defeated that strange deer thing.   ", "");
//         TranslationHelper.ModifyIL(il, "It was a little terrifying, but luckily it seems its previous prey was confined to the ground. Looks like we had home turf advantage here. ", "");
//         TranslationHelper.ModifyIL(il, "You've defeated that evil serpent. I do wonder, though... Where did it come from?", "");
//         TranslationHelper.ModifyIL(il, "Looking closely, it seems to have been an aquatic monster.. once upon a time. So.. why was it in the desert?", "");
//         TranslationHelper.ModifyIL(il, "This world's secrets are still a mystery to us. Anyway, good job regardless.", "");
//         TranslationHelper.ModifyIL(il, "You've bested the scourge of the sands. As for its origin, your guess is as good as mine. However...", "");
//         TranslationHelper.ModifyIL(il, "It definitely was not made for tunneling. Instead, I'd postulate it was originally an aquatic beast. So.. what was it doing here? This world still holds many secrets...", "");
//         TranslationHelper.ModifyIL(il, "Anywho... you fought bravely. I believe the loot will serve us well.", "");
//         TranslationHelper.ModifyIL(il, "Okay.. so that just happened. Now that I've got a better look at the corpse of this mushroom crab thing, the truth is revealed- and it's not pretty.", "");
//         TranslationHelper.ModifyIL(il, "It looks like the fungus have reanimated the crab's corpse, and paraded it around like a marionette. That's.. disgusting.", "");
//         TranslationHelper.ModifyIL(il, "Whatever. No need to dawdle on that not-so-fun-fact. It's dead! Good job on that, by the way.", "");
//         TranslationHelper.ModifyIL(il, "Crabulon is no more. When I first laid eyes on it, I assumed it was some sort of mutated sea beast, akin to the Desert Scourge.", "");
//         TranslationHelper.ModifyIL(il, "However... the reality is much more sinister. It looks to me as if parasitic mushrooms were using this giant crab as a host to feed themselves more efficiently.", "");
//         TranslationHelper.ModifyIL(il, "Now that I'm reflecting on it, I feel sick. Thanks for putting an end to it.", "");
//         TranslationHelper.ModifyIL(il, "The Hive Mind has been defeated. It isn't the only source of the Corruption, but killing it definitely didn't do the Corruption any favors.", "");
//         TranslationHelper.ModifyIL(il, "That's about it for now. ", "");
//         TranslationHelper.ModifyIL(il, "You've rid the world of the Hive Mind. While it isn't the main vector for the Corruption's influence, stifling it has probably helped alleviate some evil.", "");
//         TranslationHelper.ModifyIL(il, "Let's keep on the lookout for any more threats the Corruption bears.", "");
//         TranslationHelper.ModifyIL(il, "You've bested the Perforator Hive. I wonder what causes the Crimson to coalese its evil in the form of spongy, fleshy monsters.", "");
//         TranslationHelper.ModifyIL(il, "It hungered for pure soil, no doubt wanting to spread the world's evil further. Of course, it isn't doing any of that anymore.", "");
//         TranslationHelper.ModifyIL(il, "You've beat the Perforator Hive, and those abhorrent worms that joined it in combat. I'm not sure, but seeing fleshy things seriously makes my skin crawl.", "");
//         TranslationHelper.ModifyIL(il, "Well, everything living is made of flesh. Ugh, you know what I mean...", "");
//         TranslationHelper.ModifyIL(il, "The Slime God is no more! It turns out that those huge red and purple slimes weren't actually part of the Slime God, but just strong minions.", "");
//         TranslationHelper.ModifyIL(il, "I'm glad we've defeated it, but I seriously doubt this defeat means the end of all slimes. Sadly, there's just.. so many of them. ", "");
//         TranslationHelper.ModifyIL(il, "Wait a second.. Why am I worried? They explode in like three seconds! I mean, if we keep killing them, they'll go extinct!", "");
//         TranslationHelper.ModifyIL(il, "In a few centuries or so... Ugh.  ", "");
//         TranslationHelper.ModifyIL(il, "Finally. The Slime God has been slain. Of course, this doesn't mean the end of slime as we know it. Seriously, they're just everywhere.", "");
//         TranslationHelper.ModifyIL(il, "I'm pretty sure they can split to make more. ...I'm no expert on the etymology of slimes or anything.", "");
//         TranslationHelper.ModifyIL(il, "It couldn't be a bad way to pass the time, though. Maybe I'll do some light reading. ", "");
//         TranslationHelper.ModifyIL(il, "You've defeated Cryogen! And.. it turns out, 'Cryogen' was a prison for the Archmage. ", "");
//         TranslationHelper.ModifyIL(il, "From what the Archmage can tell us, it seems he was imprisoned in Cryogen by the Jungle Tyrant Yharim. If I recall correctly, we've heard about him before.", "");
//         TranslationHelper.ModifyIL(il, "Whoever they are, it seems they've caused this world no shortage of troubles. Hopefully, we can begin to unravel more of this mystery as we venture forth.", "");
//         TranslationHelper.ModifyIL(il, "Cryogen has been slain. And out from its corpse arrives this Archmage. From what he has to say, he was trapped there by an evil king...", "");
//         TranslationHelper.ModifyIL(il, "Yharim, the Jungle Tyrant. Their reputation precedes them.. I have a feeling that they've been the source for all this world's many ailments.", "");
//         TranslationHelper.ModifyIL(il, "We must endeavor to unravel more of this story. I trust you're in agreement. ", "");
//         TranslationHelper.ModifyIL(il, "The Aquatic Scourge is no more, huh? So my hypothesis was correct; the Desert Scourge was displaced and dried... and we just fought its ancestor.", "");
//         TranslationHelper.ModifyIL(il, "The Sea King told us of what transpired. Yharim's forces are powerful indeed.. We have to stop their rampant evil! ", "");
//         TranslationHelper.ModifyIL(il, "The Aquatic Scourge is defeated. So this is what the Desert Scourge could have been, had the ocean not been reduced to a desert.", "");
//         TranslationHelper.ModifyIL(il, "From what the Sea King tells us, that was another one of Yharim's doings. They bring destruction wherever they roam... We must put an end to them.", "");
//         TranslationHelper.ModifyIL(il, "You've defeated the Brimstone Elemental. It seems they were once a revered goddess of the Underworld's mighty civilization, before Calamitas rent it asunder.", "");
//         TranslationHelper.ModifyIL(il, "I say we confront her sooner, than later. She must be incredibly powerful, but.. We have to do something, at least. ", "");
//         TranslationHelper.ModifyIL(il, "The fire-borne spirit is no more. The land of brimstone must have been powerful, to worship this spirit as such. We merely fought her at her weakest.", "");
//         TranslationHelper.ModifyIL(il, "If what we know is correct, Calamitas was the eventual end of the brimstone kingdom. While I want to put an end to her rampages, we must become stronger first.", "");
//         TranslationHelper.ModifyIL(il, "...Calamitas is no more. Or, so we thought. What we faced was naught but a replica of the real thing. Even so, it was an incredibly powerful foe.", "");
//         TranslationHelper.ModifyIL(il, "We must endeavor to get stronger. We have to! With things like this roaming the world, who else can stop them..? ", "");
//         TranslationHelper.ModifyIL(il, "We've defeated Calamitas... but.. It was naught but a clone of the real foe. Even as a duplicate, it stood as one of our toughest challenges yet.", "");
//         TranslationHelper.ModifyIL(il, "Who knows what the real thing can do.. We have to become stronger.  ", "");
//         TranslationHelper.ModifyIL(il, "Finally, we've bested Anahita and her Leviathan. What a thrilling battle... You've fought bravely, even when the fight looked insurmountable.", "");
//         TranslationHelper.ModifyIL(il, "Hopefully, what we've obtained from their remains shall help us in the future. Man, we're on a roll! ", "");
//         TranslationHelper.ModifyIL(il, "You've defeated the Leviathan and Anahita. A battle well fought- when the Leviathan appeared, I feared the worst. ", "");
//         TranslationHelper.ModifyIL(il, "I'll try not to doubt you in the future. After all, you've got my help.  ", "");
//         TranslationHelper.ModifyIL(il, "I am helping, right? Right...  ", "");
//         TranslationHelper.ModifyIL(il, "We've done in Astrum Aureus. It's a good reminder that the Astral Infection consumes indiscriminately. Even modern mechanics aren't safe from it.", "");
//         TranslationHelper.ModifyIL(il, "Even so, it's solid proof that we're getting stronger. Can you imagine fighting that right after we fought Skeletron? Exactly!", "");
//         TranslationHelper.ModifyIL(il, "That's that. Astrum Aureus is dead. Even as the Astral Infection made a perversion of the original, it beat with a heart of iron still.", "");
//         TranslationHelper.ModifyIL(il, "The Astral Infection... It's dangerous. At least we've made some good progress, though. Don't forget that. ", "");
//         TranslationHelper.ModifyIL(il, "Nice, you've bested the Plaguebringer Goliath. The ingenuity of man never ceases to amaze, even if their knowledge usually is imparted in hyper-active death machines.", "");
//         TranslationHelper.ModifyIL(il, "Well, what can you do. There's people like us here to take care of that part.  ", "");
//         TranslationHelper.ModifyIL(il, "Seriously.. what's with the Jungle? At least the Plaguebringer Goliath is dead. Even so, I can't shake it out of my mind. I can't handle bugs, like.. at all.", "");
//         TranslationHelper.ModifyIL(il, "Bugs, bugs..  They continue to rear their ugly heads wherever I look..! ", "");
//         TranslationHelper.ModifyIL(il, "Whoops.. I was venting a little. Let's just move on. Good job defeating that foe. ", "");
//         TranslationHelper.ModifyIL(il, "The Ravager is gone from this world. It was concieved in retaliation against the conquests of the Jungle Tyrant, but it evidently did little in that regard.", "");
//         TranslationHelper.ModifyIL(il, "At the very least, we could finally let it rest. If this is what humans were led to, what truly happened all those years ago that could lead to such desperation?", "");
//         TranslationHelper.ModifyIL(il, "We've defeated the Ravager. Once upon a time, it served as a grim last resort employed against the Jungle Tyrant. Now it can finally rest.", "");
//         TranslationHelper.ModifyIL(il, "Even in death, it stalked without purpose. I'm glad we bested it, but its existence does nothing but give credence to the tales of Yharim's overwhelming might.", "");
//         TranslationHelper.ModifyIL(il, "We've defeated Astrum Deus. Astrum Deus is- or was- one of the many gods that ruled over the universe. As far as I can remember, it was gone before I was born.", "");
//         TranslationHelper.ModifyIL(il, "However... Astrum Deus can regenerate itself. Through assimilating life around its corpse, it can eventually return to the cosmos. It's kin to the story of the ouroboros.", "");
//         TranslationHelper.ModifyIL(il, "Let's return to what I said earlier. Astrum Deus was a GOD. What we fought was much weaker. What in the world was able to defeat a deity of that caliber?", "");
//         TranslationHelper.ModifyIL(il, "This was a well fought victory... Even so, stay vigilant. I have a feeling our culprit is closer than we think.", "");
//         TranslationHelper.ModifyIL(il, "Great work. You've defeated Astrum Deus. I have some personal knowledge, so allow me to share... ", "");
//         TranslationHelper.ModifyIL(il, "Astrum Deus is one of many cosmic deities. It disappeared before I was born, but knowledge states that it can assimilate life near its corpse to regenerate itself.", "");
//         TranslationHelper.ModifyIL(il, "So, that begs the question.. What could be walking this mortal plane able to befall an actual, literal god? What we fought was but a child in comparison.", "");
//         TranslationHelper.ModifyIL(il, "Let's shelve that train of thought. While I have my fears, this is our victory. Congratulations. ", "");
//         TranslationHelper.ModifyIL(il, "Here's another Essence you can use. It'll make a Ranged-type weapon with unique properties. Something tells me it's cursed, so..", "");
//         TranslationHelper.ModifyIL(il, "Good luck with that one!", "");
//         TranslationHelper.ModifyIL(il, "Here's a Ranged-type essence. It looks like every fourth shot has increased offensive properties. Whatever the reason, it's powerful.", "");
//         TranslationHelper.ModifyIL(il, "Here is another Essence for you. This one's from a goddess of the Underworld, or so I'm told. It seems to be a melee weapon. ", "");
//         TranslationHelper.ModifyIL(il, "Keep up the good work!", "");
//         TranslationHelper.ModifyIL(il, "Here you are: another Essence. This one will create a Summon-type weapon. I trust you know what that means? ...", "");
//         TranslationHelper.ModifyIL(il, "I'm telling you to try it out.", "");
//         TranslationHelper.ModifyIL(il, "You knew that? Never mind then.", "");
//         TranslationHelper.ModifyIL(il, "Here is another Essence for you. Apparently, this originates from 'Midgard.' It looks to be a rather powerful melee weapon. ", "");
//         TranslationHelper.ModifyIL(il, "That's it for now. Keep up the good work!", "");
//         TranslationHelper.ModifyIL(il, "I have quite the unique Essence for you. It looks to be a chainsaw imbued with the strength of a dog god.. Or so it seems.", "");
//         TranslationHelper.ModifyIL(il, "Whatever it may be, it should prove useful to you. Ignore the fact that it talks.", "");
//         TranslationHelper.ModifyIL(il, "Another Essence for you. This firey sword is classified as Magic. It seems to explode when sufficiently charged.", "");
//         TranslationHelper.ModifyIL(il, "I trust you'll know what to do.", "");
//         TranslationHelper.ModifyIL(il, "I've gotten an Essence for you. This one will create a Magic-type weapon. Apparently, proper timing is needed to better utilize this weapon.", "");
//         TranslationHelper.ModifyIL(il, "I have no doubts you can get a handle on it easily. Okay, saying 'no doubts' would be a lie. Maybe 1/4th of a doubt.", "");
//         TranslationHelper.ModifyIL(il, "An Essence, for you. This powerful Melee heirloom is said to cleave the way for those less fortunate.", "");
//         TranslationHelper.ModifyIL(il, "Good luck in crafting it.", "");
//         TranslationHelper.ModifyIL(il, "This Essence is used to craft an upgrade to Death in Four Acts. It will most likely boast incredible Ranged power.", "");
//         TranslationHelper.ModifyIL(il, "This Essence is a personal creation of mine! It creates a Magic weapon that lets you enter the 'Butterfly Trance' and gain special bonuses!", "");
//         TranslationHelper.ModifyIL(il, "Please, use it if you can. I can always use more data!", "");
//         TranslationHelper.ModifyIL(il, "The weapon made from this Essence is based around music.. Timing your swings will be critical in using this to its fullest.", "");
//         TranslationHelper.ModifyIL(il, "Also.. Doesn't it make you feel like rapping?", "");
//         TranslationHelper.ModifyIL(il, "This Essence creates a Ranged gun that perpetuates itself after killing foes! Feel the heat!!", "");
//         TranslationHelper.ModifyIL(il, "Ahem. Please consider it in your arsenal.", "");
//         TranslationHelper.ModifyIL(il, "This Essence will create a legendary weapon made for slaying dragons. Jump into the air and pierce your foes with its strength.", "");
//         TranslationHelper.ModifyIL(il, "It's a Melee weapon, so craft it if you can fit it in your arsenal.", "");
//         TranslationHelper.ModifyIL(il, "This Essence is a Ranged weapon that defeats foes with a swarm of powerful nanites. Truly fearful.", "");
//         TranslationHelper.ModifyIL(il, "If your gear supports it, try crafting this weapon!", "");
//         TranslationHelper.ModifyIL(il, "This Magic weapon will gain critical chance when shooting, and each crit will deal increased damage. It's powerful stuff.", "");
//         TranslationHelper.ModifyIL(il, "Consider it if you're able.", "");
//         TranslationHelper.ModifyIL(il, "This Essence is another Ranged weapon that allows for powerful charged attacks. Fully charged, it splits and hits multiple foes!", "");
//         TranslationHelper.ModifyIL(il, "Hey. Aren't we getting too many Ranged weapons? I'll try and find something else next time.", "");
//         TranslationHelper.ModifyIL(il, "This Ranged weapon allows you to enter a Melee stance, dealing more damage to foes you've hit with arrows. It should be quite engaging.", "");
//         TranslationHelper.ModifyIL(il, "This is a legendary Melee artifact! The weapon this Essence crafts can inflict a crippling debuff on any foe!", "");
//         TranslationHelper.ModifyIL(il, "This powerful Melee relic allows for the expidenture of Mana to teleport and deal powerful damage. It's a new favorite of mine.", "");
//         TranslationHelper.ModifyIL(il, "This Essence will create a support item this time. It'll give powerful buffs to you and your friends if you can keep it up.", "");
//         TranslationHelper.ModifyIL(il, "This weapon is made straight from the power of the Moon Lord and its spatial pillars. It'll do good in your hands.", "");
//         TranslationHelper.ModifyIL(il, "The Warrior of Light has inspired this Essence. It appears to be a key to a gateway of infinite weapons, doing Summon damage.", "");
//         TranslationHelper.ModifyIL(il, "If you feel inspired, try an evil laugh when firing.", "");
//         TranslationHelper.ModifyIL(il, "From the Warrior of Light.. this Essence allows for the usage of Limit Break. It's an incredibly strong Magic weapon.", "");
//         TranslationHelper.ModifyIL(il, "'The Light will cleanse your sins!' Or something like that. ", "");
//         TranslationHelper.ModifyIL(il, "This Essence creates a Ranged weapon with a high Mana cost, and an incredibly high critical damage modifier.", "");
//         TranslationHelper.ModifyIL(il, "Exploitable? Surely. Theorycraft is all you.", "");
//         TranslationHelper.ModifyIL(il, "This weapon can switch between Ranged and Magic. If you time its reload correctly, it always does critical damage.", "");
//         TranslationHelper.ModifyIL(il, "I'm sure you can think of something that works around that... ", "");
//         TranslationHelper.ModifyIL(il, "This is a Summon weapon. It seems to have very unique scaling properties, and attacks incredibly quickly.", "");
//         TranslationHelper.ModifyIL(il, "It's also a reflection of your heart... or something. I don't really get that stuff.", "");
//         TranslationHelper.ModifyIL(il, "This powerful weapon allows you to use Skill Orbs to unleash special moves. It also has a super-powered burst window. It's a Melee weapon.", "");
//         TranslationHelper.ModifyIL(il, "You'd be well off with it in your hands.. but it does mean you have to get up close. I don't envy you.", "");
//         TranslationHelper.ModifyIL(il, "This is a Summoner weapon, but you'll use it like a Melee weapon. It has the power to swap places instantly with a set place.", "");
//         TranslationHelper.ModifyIL(il, "While dangerous, it looks to be pretty powerful. Surely you won't get hit.. right?", "");
//         TranslationHelper.ModifyIL(il, "This is a Summon weapon. Holding it summons two cannons to orbit you, and you can fire from both of them. Each of them apply a different debuff.", "");
//         TranslationHelper.ModifyIL(il, "The important part is using the other weapon to trigger the other weapon's debuff. You can figure it out.", "");
//         TranslationHelper.ModifyIL(il, "This is a pretty unique weapon. When using it, it'll follow-up your attacks, and become stronger when you spend Mana.", "");
//         TranslationHelper.ModifyIL(il, "Here's another Summon weapon. You can attack normally with it, but striking foes with the Timepieces empowers the weapon's attacks.", "");
//         TranslationHelper.ModifyIL(il, "Did I mention you can go back in time? It's powerful, for sure. ", "");
//         TranslationHelper.ModifyIL(il, "This Essence hails from a world embroiled in conflict... It boasts incredible power, but if you get too overzealous, it'll start to hurt you.", "");
//         TranslationHelper.ModifyIL(il, "This Essence allows for the creation of unique dual blades which offer varying effects, and allows you to leave your body to overwhelm foes.", "");
//         TranslationHelper.ModifyIL(il, "This Essence creates a Melee weapon that can swap between sword, scythe, or gun. You will be able to use it in nearly any situation!", "");
//         TranslationHelper.ModifyIL(il, "This Essence is utilized in the creation of a Melee Weapon. What sets it apart is the ability to manifest as a sword, scythe, or gun. ", "");
//         TranslationHelper.ModifyIL(il, "Okay, here's a new Essence for you. It's a huge Melee lance that can be swap between a lance form and a gun form. It looks to be pretty strong!", "");
//         TranslationHelper.ModifyIL(il, "Here's a new weapon for you to craft. This lance can swap between close and long range, and it can also be charged to great effect.", "");
//         TranslationHelper.ModifyIL(il, ", take this Essence. This Melee weapon has an incredible burst, but the refractory period may be dangerous.. Give it a shot, though!", "");
//         TranslationHelper.ModifyIL(il, "This is for you, ", "");
//         TranslationHelper.ModifyIL(il, ". It's a super-powered Melee weapon that has an incredible burst phase, followed by a weakness phase. Good luck using it.", "");
//         TranslationHelper.ModifyIL(il, "Here's another Essence you can use! It has incredible synergy with Summons and gets stronger as you do, so if you plan on  fighting with allies, this is it!", "");
//         TranslationHelper.ModifyIL(il, "I have another Essence for you. This weapon is a Summon weapon that works in harmony with minions, and it gets stronger as you do.", "");
//         TranslationHelper.ModifyIL(il, "Right, I have an Essence for you. It's a Summon weapon that conjures this mysterious sentient star. It's.. too cute. Anyways..., ", "");
//         TranslationHelper.ModifyIL(il, "It looks to be a powerful weapon, but you'll have to collect the Star Bits for full effect- meaning getting in the  way of danger. Good luck..!", "");
//         TranslationHelper.ModifyIL(il, "I have another Essence for you to use. This Summon-type wand calls forth this adorable little sentient star, and it just looks so.. squishable..", "");
//         TranslationHelper.ModifyIL(il, "...Looking past that. You'll have to get up close to use the Star Bits, but they do quite a number on foes if you can land them.", "");
//         TranslationHelper.ModifyIL(il, "Okay. I've got another Essence for you. This Melee weapon can swap between five different stances, granting powerful buffs in the process.", "");
//         TranslationHelper.ModifyIL(il, "I've given you another Essence. This is a Melee weapon that can morph between five different forms, changing the weapon's usage. Interesting.", "");
//         TranslationHelper.ModifyIL(il, "Here's a Magic-type Essence. It'll make a scythe with incredible reach and balances between light and dark. Now THAT sounds cool. Right? Right.", "");
//         TranslationHelper.ModifyIL(il, "Here is another Essence. For you. This is a Summon weapon that will transform you as well as summon crystal shards that weaken and attack nearby foes.", "");
//         TranslationHelper.ModifyIL(il, "Hmm.. It's the Essence of Hope, but is there something else lurking beneath the surface? Who knows.. ", "");
//         TranslationHelper.ModifyIL(il, "Here's another Essence for your use. This powerful Melee blade can deal powerful damage to all foes in your vicinity. How useful is that?", "");
//         TranslationHelper.ModifyIL(il, "Right... Here's another Essence. This Melee weapon allows you to damage all nearby foes in a huge area. It should be quite useful.", "");
//         TranslationHelper.ModifyIL(il, "Here's another Essence you can prepare to use, from Penthesilea's strength. With its magical paint, we should be able to best powerful foes.", "");
//         TranslationHelper.ModifyIL(il, "This is another Essence you can master. It will allow you to use Penthesilea's ink to supress foes and strike bosses powerfully.", "");
//         TranslationHelper.ModifyIL(il, "Here you go: an essence for usage in crafting. It looks like it'll apply powerful bouts of flame and frost alike. Not how I'd want to go out, personally.", "");
//         TranslationHelper.ModifyIL(il, "Okay, I have another Essence for your battles. It summons a mystical fox that burns your enemies with icy energy. They might even deserve it, too.", "");
//         TranslationHelper.ModifyIL(il, "Whoa, this is a powerful Essence. It's potential seems to be magnified based on your Aspected Damage Type. How about giving it a go?", "");
//         TranslationHelper.ModifyIL(il, "It looks like this next Essence is a strong one. Aspected Damage Type seems to empower the weapon further... ", "");
//         TranslationHelper.ModifyIL(il, "Okay..! Time for another Essence! This looks to be a Ranged weapon with high damange output at close range. ", "");
//         TranslationHelper.ModifyIL(il, "I've located another Essence for your use. It seems this Ranged-type weapon is hyperfocused on movement. How about pairing it with some mobility tools..?", "");
//         TranslationHelper.ModifyIL(il, "This new Essence is great! It's a Ranged weapon with crazy high explosive potential. Just point it towards the bad guys.", "");
//         TranslationHelper.ModifyIL(il, "Another Essence is yours. It's a strong Ranged weapon with incredibly good room-clearing power. How about that?", "");
//         TranslationHelper.ModifyIL(il, "I have a new Essence for you. This is a magical Summon-type weapon that seems to scale with your own potential. Interesting..!", "");
//         TranslationHelper.ModifyIL(il, "Here's another Essence for you to use. It looks to be a Summon-type weapon that grows in strength with the use of more minion summons.", "");
//         TranslationHelper.ModifyIL(il, "A Magic Essence is here this time. With cosmic energy, you can blast foes away with superpowered light. Sounds good to me!", "");
//         TranslationHelper.ModifyIL(il, "Here's a Magic-type Essence. With the power of the stars, you can melt even the strongest of foes. Give it a try..?", "");
//         TranslationHelper.ModifyIL(il, "This Melee-type Essence should help. It looks to be a multiple-purpose power-suit with myriad attacks. Now that sounds cool!", "");
//         TranslationHelper.ModifyIL(il, "A Melee Essence is here this time. With its strength, you can create a multifaceted weapon that swaps its arsenal instantly in combat.", "");
//         TranslationHelper.ModifyIL(il, ", I have an Essence for you! It seems to create a Magic-type weapon with powerful piercing damage... It sounds rather helpful.", "");
//         TranslationHelper.ModifyIL(il, ", I have an Essence for you. Looks like it'll become a Summon-type weapon... and it gains strength from grazing danger? You'll have to try it.", "");
//         TranslationHelper.ModifyIL(il, "Okay- I've found another Essence you can use... I think. The only thing I can tell is that it makes a Ranged weapon. The rest is up to you.", "");
//         TranslationHelper.ModifyIL(il, "This is another powerful Essence. Looks like it's a Melee weapon, and it has the potential to execute foes. Don't underestimate it.", "");
//         TranslationHelper.ModifyIL(il, "Okay- I've got it. Here's a Ranged-type Essence.. it looks to be something pretty powerful! Good luck.", "");
//         TranslationHelper.ModifyIL(il, "Time for another essence- this time it's a Ranged-type weapon. Seems to be pretty powerful at general destruction.", "");
//         TranslationHelper.ModifyIL(il, ", it's good to see you again. I'm not here to ask for your help- instead, I have a gift for you.", "");
//         TranslationHelper.ModifyIL(il, "You have proven yourself as a true warrior; as such, you should have a weapon befitting your strength. So, I bestow", "");
//         TranslationHelper.ModifyIL(il, "this weapon unto you. Good luck, and good hunting.  ", "");
//         TranslationHelper.ModifyIL(il, "A Summon weapon's essence is here. It looks suspiciously like a whip... but it also can summon minions? Now that's peak.", "");
//         TranslationHelper.ModifyIL(il, "What? 'Peak?' It's new age lingo- You've definitely heard it before. You know? Like.. mountain peak? The top.. of something? Never mind.", "");
//         TranslationHelper.ModifyIL(il, "Here's another weapon. Looks to be a summon-type whip that can deploy spider-robots to attack foes.", "");
//         TranslationHelper.ModifyIL(il, "They're spiders... but not real spiders. Yep- thinking like that will stop the fight or flight response. Take notes!", "");
//         TranslationHelper.ModifyIL(il, "Okay- this is a Melee weapon! My instincts tell me it's perfect for high-defense foes. What are you waiting for?", "");
//         TranslationHelper.ModifyIL(il, "This is a Melee weapon. It has pretty good anti-armor properties- you can definitely put that to good use.", "");
//         TranslationHelper.ModifyIL(il, "This Melee blade can harness the power of the elements themselves. Just having it in your hands is quite something!", "");
//         TranslationHelper.ModifyIL(il, "Another weapon is here. It seems to be a Melee weapon- one that uses the power of the elements to attack foes.", "");
//         TranslationHelper.ModifyIL(il, "This looks to be a Magic weapon. With its power, you can call down entire stars to defeat your foes!", "");
//         TranslationHelper.ModifyIL(il, "You're worried you'll run out eventually? Yeah.. no.", "");
//         TranslationHelper.ModifyIL(il, "This Magic-type staff will be incredibly helpful, if I do say so myself. It has the strength to conjure entire stars!", "");
//         TranslationHelper.ModifyIL(il, "As long as they aren't REAL stars. There would be... a few problems.", "");
//         TranslationHelper.ModifyIL(il, "This looks to be... a Magic weapon. Strange- it feels like an entire armory is contained in this Essence. How's that possible?", "");
//         TranslationHelper.ModifyIL(il, "Well, I'll let you figure that one out. Get to it- I'm curious too, you know?", "");
//         TranslationHelper.ModifyIL(il, "Here's another weapon- Magic, it seems. There's something strange about it- this Essence seems to hold the strength of myriad weapons together.", "");
//         TranslationHelper.ModifyIL(il, "Here's a Magic weapon for your usage. Looks to me like it's pretty complicated- you're up to the task though, right? ", "");
//         TranslationHelper.ModifyIL(il, "Here's another unique Magic weapon. Looks to be rather complicated, so good luck using it. Don't forget the ABCs- always be casting!", "");
//         TranslationHelper.ModifyIL(il, "Although, I'm not too sure that it applies here.   ", "");
//         TranslationHelper.ModifyIL(il, "Right.. Here's a Ranged-type weapon Essence.  I hope you've built up your chemical tolerance- it seems to utilize chemical energy to deal powerful damage.", "");
//         TranslationHelper.ModifyIL(il, "This Essence sources a Ranged weapon. It has a high focus on tight mobility, meaning it'll put you into the front lines. The strength should compensate.", "");
//         TranslationHelper.ModifyIL(il, "Behold- a new Essence! It's Melee damage this time. It has some incredible lifesteal powers- but also seems to drain your health on use? How about giving it a go? ", "");
//         TranslationHelper.ModifyIL(il, "A Melee-type Essence is prepared this time. It seems to me like it sacrifies your health for powerful area-of-effect damage. Use it well, but know the risks. ", "");
//         TranslationHelper.ModifyIL(il, "Here's a Summon weapon. It's.. Well, it's a whip, but it has some unique magical properties. It has good striking power, too! ", "");
//         TranslationHelper.ModifyIL(il, "Right, here's a Summon-type whip. It has some magic capability, but it's a bit random in its casting. Try and use it well. ", "");
//         TranslationHelper.ModifyIL(il, "Listen close, ", "");
//         TranslationHelper.ModifyIL(il, "! Or not. This Magic weapon is a giant horn, but get this: you can whack people with it! Rad! ", "");
//         TranslationHelper.ModifyIL(il, "Be careful with this Essence- for some reason, it discharges static electricity all the time.  ", "");
//         TranslationHelper.ModifyIL(il, "It'll create a Summon weapon.Hopefully the electric properties carry over- it's sure to give our foes a shock. ", "");
//         TranslationHelper.ModifyIL(il, "Careful with this Essence- Apparently, only the worthy can wield it at full strength.  ", "");
//         TranslationHelper.ModifyIL(il, "An ancient civilization's magnum opus, it seems. Don't underestimate its destructive power. ", "");
//         TranslationHelper.ModifyIL(il, "This Essence leads to a truly powerful weapon. It bears remnants of an ancient, advanced civilization. ", "");
//         TranslationHelper.ModifyIL(il, "Evidently, they bore proficiency in spatial manipulation. I'd like you to give it a try, but it might reject the unworthy. ", "");
//         TranslationHelper.ModifyIL(il, "At this point, I wonder if there was a weapon you weren't worthy to wield. Yes, I'm praising you. ", "");
//         TranslationHelper.ModifyIL(il, "We meet again, ", "");
//         TranslationHelper.ModifyIL(il, "We meet again, ", "", 2);
//         TranslationHelper.ModifyIL(il, "We meet again, ", "", 3);
//         TranslationHelper.ModifyIL(il, ". I need your help.  ", "");
//         TranslationHelper.ModifyIL(il, "I've given you the 'Ancient Shard' With it, you can call forth a powerful foe, the Burnished King. ", "");
//         TranslationHelper.ModifyIL(il, "If my hypothesis is correct, he may be an important step towards confronting the First Starbearer, and stopping his rampage.", "");
//         TranslationHelper.ModifyIL(il, "Prepare yourself: this fight will not be easy.  ", "");
//         TranslationHelper.ModifyIL(il, ". Again, I need your assistance.  ", "");
//         TranslationHelper.ModifyIL(il, "This is the 'Unsullied Canvas.' It will draw the Witch of Ink out of hiding. ", "");
//         TranslationHelper.ModifyIL(il, "This is another important step in the pursuit of the the First Starbearer. ", "");
//         TranslationHelper.ModifyIL(il, "This is another important step in the pursuit of the the First Starbearer. ", "", 2);
//         TranslationHelper.ModifyIL(il, "Please prepare yourself. This will be a hard fight.  ", "");
//         TranslationHelper.ModifyIL(il, ". Again, I have another foe for you to defeat.  ", "");
//         TranslationHelper.ModifyIL(il, "I've given you the 'Beating Crux' When used, it will call forth a powerful demon. ", "");
//         TranslationHelper.ModifyIL(il, "Prepare yourself well.   ", "");
//         TranslationHelper.ModifyIL(il, ", you can tell as well as I that the situation has turned dire.  ", "");
//         TranslationHelper.ModifyIL(il, "The First Starbearer's gaze has been turned to you, and his power has blanketed the world in overwhelming Light. ", "");
//         TranslationHelper.ModifyIL(il, "I have given you the 'Progenitor's Wish.' It will serve as a way to draw him out. From then on, it will be your strength against his determination.", "");
//         TranslationHelper.ModifyIL(il, "Please, you must win this fight. The stakes have never been higher...  ", "");
//     };
// }