// using System.Reflection;
// using CalamityRuTranslate.Common;
// using CalamityRuTranslate.Common.Utilities;
// using CalamityRuTranslate.Core.MonoMod;
// using MonoMod.Cil;
// using StarsAbove.NPCs;
// using Terraria.ModLoader;
//
// namespace CalamityRuTranslate.Mods.TheStarsAbove.MonoMod;
//
// [JITWhenModsEnabled("StarsAbove")]
// public class Tsukiyomi2Patch : Patch<ILContext.Manipulator>
// {
//     public override bool AutoLoad => ModsCall.StarsAbove != null && TranslationHelper.IsRussianLanguage;
//
//     public override MethodInfo ModifiedMethod => typeof(Tsukiyomi2).GetCachedMethod(nameof(Tsukiyomi2.AI));
//
//     protected override ILContext.Manipulator PatchMethod { get; } = il =>
//     {
//         TranslationHelper.ModifyIL(il, "The Spatial Disk begins to resonate. Left click to interact.", "Пространственный диск резонирует. Нажмите ЛКМ для взаимодействия.");
//         TranslationHelper.ModifyIL(il, "The galaxy stands still once more...", "Галактика вновь замерла...");
//         TranslationHelper.ModifyIL(il, "You've been colored with ink!", "Вас раскрасили чернилами!");
//         TranslationHelper.ModifyIL(il, "Cosmic energy begins to coalese around you!", "Вокруг вас собирается космическая энергия!");
//         TranslationHelper.ModifyIL(il, "Concentrativity", "Концентративность");
//         TranslationHelper.ModifyIL(il, "Concentrativity", "Концентративность", 2);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы");
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 2);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 3);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 4);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 5);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 6);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 7);
//         TranslationHelper.ModifyIL(il, "Hypertuned Threads of Fate", "Суперструны судьбы", 8);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый");
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 2);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 3);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 4);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 5);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 6);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 7);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 8);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 9);
//         TranslationHelper.ModifyIL(il, "Elechos Unforgotten", "Электо Незабытый", 10);
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение");
//         TranslationHelper.ModifyIL(il, "Ascendance", "Вознесение", 2);
//         TranslationHelper.ModifyIL(il, "The Flood Of Light", "Поток света");
//         TranslationHelper.ModifyIL(il, "The Flood Of Light", "Поток света", 2);
//         TranslationHelper.ModifyIL(il, "Aetherial Subduction", "Эфирная субдукция");
//         TranslationHelper.ModifyIL(il, "Aetherial Subduction", "Эфирная субдукция", 2);
//         TranslationHelper.ModifyIL(il, "Aetherial Subduction", "Эфирная субдукция", 3);
//         TranslationHelper.ModifyIL(il, "Aetherial Subduction", "Эфирная субдукция", 4);
//         TranslationHelper.ModifyIL(il, "Aetherial Subduction", "Эфирная субдукция", 5);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber", "Корусантская сабля");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II");
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 2);
//         TranslationHelper.ModifyIL(il, "Coruscant Saber II", "Корусантская сабля II", 3);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь");
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 2);
//         TranslationHelper.ModifyIL(il, "Blotted Whims", "Запятнанная блажь", 3);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter", "Освящённая резня");
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи");
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 2);
//         TranslationHelper.ModifyIL(il, "Perfect Strokes", "Идеальные штрихи", 3);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II");
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 2);
//         TranslationHelper.ModifyIL(il, "Sanctified Slaughter II", "Освящённая резня II", 3);
//         TranslationHelper.ModifyIL(il, "Thousand Strikes", "Тысяча ударов");
//         TranslationHelper.ModifyIL(il, "Thousand Strikes ", "Тысяча ударов ");
//         TranslationHelper.ModifyIL(il, "Blazing Skies II", "Пылающее небо II");
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция");
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 2);
//         TranslationHelper.ModifyIL(il, "Ablation", "Абляция", 3);
//         TranslationHelper.ModifyIL(il, "The Bitter End", "Горький конец");
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика");
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 2);
//         TranslationHelper.ModifyIL(il, "Synaptic Static", "Синаптическая статика", 3);
//         TranslationHelper.ModifyIL(il, "Absolute Fire III", "Абсолютный огонь III");
//         TranslationHelper.ModifyIL(il, "Absolute Blizzard III", "Абсолютная метель III");
//         TranslationHelper.ModifyIL(il, "Terror Unleashed", "Освобождённый ужас");
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция");
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 2);
//         TranslationHelper.ModifyIL(il, "Total Isolation", "Полная изоляция", 3);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса");
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 2);
//         TranslationHelper.ModifyIL(il, "A Dash of Chaos", "Рывок хаоса", 3);
//         TranslationHelper.ModifyIL(il, "Ink Over", "Вездесущие чернила");
//         TranslationHelper.ModifyIL(il, "Pandaemonium", "Пандемониум");
//         TranslationHelper.ModifyIL(il, "Pandaemonium", "Пандемониум", 2);
//         TranslationHelper.ModifyIL(il, "Pandaemonium", "Пандемониум", 3);
//         TranslationHelper.ModifyIL(il, "Pandaemonium", "Пандемониум", 4);
//         TranslationHelper.ModifyIL(il, "Pandaemonium", "Пандемониум", 5);
//         TranslationHelper.ModifyIL(il, "Suppuration", "Нагноение");
//         TranslationHelper.ModifyIL(il, "Macrocosmos", "Макрокосмос");
//         TranslationHelper.ModifyIL(il, "Macrocosmos", "Макрокосмос", 2);
//         TranslationHelper.ModifyIL(il, "Macrocosmos", "Макрокосмос", 3);
//         TranslationHelper.ModifyIL(il, "Macrocosmos", "Макрокосмос", 4);
//         TranslationHelper.ModifyIL(il, "Macrocosmos", "Макрокосмос", 5);
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос");
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос", 2);
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос", 3);
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос", 4);
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос", 5);
//         TranslationHelper.ModifyIL(il, "Microcosmos", "Микрокосмос", 6);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия");
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 2);
//         TranslationHelper.ModifyIL(il, "Gravitational Anomaly", "Гравитационная аномалия", 3);
//         TranslationHelper.ModifyIL(il, "Ars Laevateinn", "Арс Леватейн");
//         TranslationHelper.ModifyIL(il, "Blade of the End", "");
//         TranslationHelper.ModifyIL(il, "Blade of the End", "", 2);
//         TranslationHelper.ModifyIL(il, "Blade of the End", "", 3);
//         TranslationHelper.ModifyIL(il, "Blade of the End", "", 4);
//         TranslationHelper.ModifyIL(il, "Blade of the End", "", 5);
//         TranslationHelper.ModifyIL(il, "Blade of the End", "", 6);
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги");
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 2);
//         TranslationHelper.ModifyIL(il, "Painted Attendants", "Нарисованные слуги", 3);
//         TranslationHelper.ModifyIL(il, "Aegis of Frost", "Эгида мороза");
//         TranslationHelper.ModifyIL(il, "Absolute Thunder IV", "Абсолютная гроза IV");
//         TranslationHelper.ModifyIL(il, "Quintuplecast", "Пятикратное заклинание");
//         TranslationHelper.ModifyIL(il, "Absolute Holy", "Абсолютная святость");
//         TranslationHelper.ModifyIL(il, "Crack The Sky", "Расколоть небо");
//         TranslationHelper.ModifyIL(il, "Linear Mystics", "Линейные мистики");
//         TranslationHelper.ModifyIL(il, "Overflow Error", "Ошибка переполнения");
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес");
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 2);
//         TranslationHelper.ModifyIL(il, "Rend Heaven", "Разрыв небес", 3);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность");
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 2);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 3);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 4);
//         TranslationHelper.ModifyIL(il, "Splattered Sundering", "Забрызганная скованность", 5);
//         TranslationHelper.ModifyIL(il, "To The Limit", "Круша лимиты");
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия");
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия", 2);
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия", 3);
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия", 4);
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия", 5);
//         TranslationHelper.ModifyIL(il, "Hypertuned Titanomachy", "Супернастроенная титаномахия", 6);
//         TranslationHelper.ModifyIL(il, "SOUL Extraction", "Извлечение ДУШИ");
//         TranslationHelper.ModifyIL(il, "Light Rampant", "Раздолье света");
//         TranslationHelper.ModifyIL(il, "Radiant Braver", "Сияющий храбрец");
//         TranslationHelper.ModifyIL(il, "Radiant Desperado", "Сияющий отчаянный");
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь");
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 2);
//         TranslationHelper.ModifyIL(il, "Meteor Shower", "Метеоритный дождь", 3);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV");
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 2);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 3);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 4);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 5);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 6);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 7);
//         TranslationHelper.ModifyIL(il, "Malefic IV", "Малефицизм IV", 8);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара");
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 2);
//         TranslationHelper.ModifyIL(il, "Quasar Forthcoming", "Пришествие квазара", 3);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур");
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 2);
//         TranslationHelper.ModifyIL(il, "Spilled Violet", "Пролитый пурпур", 3);
//         TranslationHelper.ModifyIL(il, "Starfield", "Звёздное поле");
//         TranslationHelper.ModifyIL(il, "Starfield", "Звёздное поле", 2);
//         TranslationHelper.ModifyIL(il, "Starfield", "Звёздное поле", 3);
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис");
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис", 2);
//         TranslationHelper.ModifyIL(il, "Theofania Inanis", "Теофаниа Инанис", 3);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират");
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 2);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 3);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 4);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 5);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 6);
//         TranslationHelper.ModifyIL(il, "Anosios Triumverate", "Нечестивый триумвират", 7);
//         TranslationHelper.ModifyIL(il, "Thousand Blades", "Тысяча клинков");
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв");
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 2);
//         TranslationHelper.ModifyIL(il, "Spatial Rip", "Пространственный разрыв", 3);
//         TranslationHelper.ModifyIL(il, "Gateway", "Врата");
//         TranslationHelper.ModifyIL(il, "Gateway", "Врата", 2);
//         TranslationHelper.ModifyIL(il, "Gateway", "Врата", 3);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат");
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 2);
//         TranslationHelper.ModifyIL(il, "Recall", "Возврат", 3);
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ");
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 2);
//         TranslationHelper.ModifyIL(il, "Relinquish", "Отказ", 3);
//         TranslationHelper.ModifyIL(il, "Total Transpose", "Полная транспозиция");
//         TranslationHelper.ModifyIL(il, "Galaxias", "Галаксия");
//         TranslationHelper.ModifyIL(il, "Galaxias", "Галаксия", 2);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через хаос");
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через хаос", 2);
//         TranslationHelper.ModifyIL(il, "Order through Chaos", "Порядок через хаос", 3);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через порядок");
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через порядок", 2);
//         TranslationHelper.ModifyIL(il, "Chaos through Order", "Хаос через порядок", 3);
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал");
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал", 2);
//         TranslationHelper.ModifyIL(il, "Starlit Channeling", "Звёздный канал", 3);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой");
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 2);
//         TranslationHelper.ModifyIL(il, "Galactic Swarm", "Галактический рой", 3);
//         TranslationHelper.ModifyIL(il, "A World Rent Asunder", "Разорванный мир");
//         TranslationHelper.ModifyIL(il, "Surpassing Infinity", "За пределами бесконечности");
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона");
//         TranslationHelper.ModifyIL(il, "The Garden of Avalon", "Сад Авалона", 2);
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности");
//         TranslationHelper.ModifyIL(il, "Nebula Channeling", "Канал туманности", 2);
//     };
// }