// using System.Reflection;
// using CalamityRuTranslate.Common;
// using CalamityRuTranslate.Common.Utilities;
// using CalamityRuTranslate.Core.MonoMod;
// using MonoMod.Cil;
// using StarsAbove;
// using Terraria.ModLoader;
//
// namespace CalamityRuTranslate.Mods.TheStarsAbove.MonoMod;
//
// [JITWhenModsEnabled("StarsAbove")]
// public class VNScenesPatch : Patch<ILContext.Manipulator>
// {
//     public override bool AutoLoad => ModsCall.StarsAbove != null && TranslationHelper.IsRussianLanguage;
//
//     public override MethodInfo ModifiedMethod => typeof(VNScenes).GetCachedMethod(nameof(VNScenes.SetupVNSystem));
//
//     protected override ILContext.Manipulator PatchMethod { get; } = il =>
//     {
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 4);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 6);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 8);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 10);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 12);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 14);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 16);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 18);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 22);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 25);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 35);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 37);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 39);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 41);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 43);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 45);
//         TranslationHelper.ModifyIL(il, "Asphodene", "Асфодена", 47);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 2);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 4);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 6);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 8);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 10);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 12);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 14);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 16);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 20);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 23);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 33);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 35);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 37);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 39);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 41);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 43);
//         TranslationHelper.ModifyIL(il, "Eridani", "Эридани", 45);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 2);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 4);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 7);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 10);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 12);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 14);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 16);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 18);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 20);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 22);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 24);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 26);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 28);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 31);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 34);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 36);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 38);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 40);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 42);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 44);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 46);
//         TranslationHelper.ModifyIL(il, "Perseus", "Персей", 48);
//         TranslationHelper.ModifyIL(il, "This is all conjecture, but the destruction is very real. It should go unsaid that we can't let this continue. I'll need your help in the future.", "");
//         TranslationHelper.ModifyIL(il, "This is all conjecture, but the destruction is very real. It should go unsaid that we can't let this continue. I'll need your help in the future.", "", 2);
//         TranslationHelper.ModifyIL(il, "Please, let me explain, Starbearer. In tandem with our galaxy's myriad worlds, there exists Starfarers to aid their denizens. You are familiar with what we do.", "");
//         TranslationHelper.ModifyIL(il, "Please, let me explain, Starbearer. In tandem with our galaxy's myriad worlds, there exists Starfarers to aid their denizens. You are familiar with what we do.", "", 2);
//         TranslationHelper.ModifyIL(il, "I'm good, thanks.", "Не нужно, но спасибо.");
//         TranslationHelper.ModifyIL(il, "I'm good, thanks.", "Не нужно, но спасибо.", 2);
//         TranslationHelper.ModifyIL(il, "I'm good, thanks.", "Не нужно, но спасибо.", 3);
//         TranslationHelper.ModifyIL(il, "I'm good, thanks.", "Не нужно, но спасибо.", 4);
//         TranslationHelper.ModifyIL(il, "I'd like the full explanation.", "Предпочту полное объяснение.");
//         TranslationHelper.ModifyIL(il, "I'd like the full explanation.", "Предпочту полное объяснение.", 2);
//         TranslationHelper.ModifyIL(il, "I'd like the full explanation.", "Предпочту полное объяснение.", 3);
//         TranslationHelper.ModifyIL(il, "I'd like the full explanation.", "Предпочту полное объяснение.", 4);
//         TranslationHelper.ModifyIL(il, "However, the First Starfarer's nominee was... unfitting for their role. This is the First Starbearer. From what I know, they seem to have lost their mind and morals.", "");
//         TranslationHelper.ModifyIL(il, "However, the First Starfarer's nominee was... unfitting for their role. This is the First Starbearer. From what I know, they seem to have lost their mind and morals.", "", 2);
//         TranslationHelper.ModifyIL(il, "After binding the Stellar Nova Key, you should be able to equip the Stellar Nova through the Spatial Disk, like usual.", "");
//         TranslationHelper.ModifyIL(il, "After binding the Stellar Nova Key, you should be able to equip the Stellar Nova through the Spatial Disk, like usual.", "", 2);
//         TranslationHelper.ModifyIL(il, "I see... Please, excuse my test. I know it was crude, but it's the only way I know how to judge someone. ", "");
//         TranslationHelper.ModifyIL(il, "I see... Please, excuse my test. I know it was crude, but it's the only way I know how to judge someone. ", "", 2);
//         TranslationHelper.ModifyIL(il, "In reality, I should have known. My sisters would never choose unwisely.  ", "");
//         TranslationHelper.ModifyIL(il, "In reality, I should have known. My sisters would never choose unwisely.  ", "", 2);
//         TranslationHelper.ModifyIL(il, "Now, they continue to roam the galaxy, the Starfarer a thrall to their chosen one's whims. They 'pursue good' through any means necessary, often with casualties.", "");
//         TranslationHelper.ModifyIL(il, "Now, they continue to roam the galaxy, the Starfarer a thrall to their chosen one's whims. They 'pursue good' through any means necessary, often with casualties.", "", 2);
//         TranslationHelper.ModifyIL(il, "As we are conduits of energy, we choose a Starbearer to act as our envoy. They- or you, as it were- work kind of like a magnifying glass.", "");
//         TranslationHelper.ModifyIL(il, "As we are conduits of energy, we choose a Starbearer to act as our envoy. They- or you, as it were- work kind of like a magnifying glass.", "", 2);
//         TranslationHelper.ModifyIL(il, "That is all for now. I must continue to track the First Starbearer. Good luck- I will have need of you soon. ", "");
//         TranslationHelper.ModifyIL(il, "That is all for now. I must continue to track the First Starbearer. Good luck- I will have need of you soon. ", "", 2);
//         TranslationHelper.ModifyIL(il, "She doesn't know it, but I've already bequeathed the power to her the second you've won our duel. ", "");
//         TranslationHelper.ModifyIL(il, "She doesn't know it, but I've already bequeathed the power to her the second you've won our duel. ", "", 2);
//         TranslationHelper.ModifyIL(il, "Click me to start the test dialogue again.", "");
//         TranslationHelper.ModifyIL(il, "This is the second choice.", "");
//         TranslationHelper.ModifyIL(il, "Greetings! I am Asphodene- a Starfarer, and in turn, that makes you my Starbearer.  ", "");
//         TranslationHelper.ModifyIL(il, "I will lend you my strength so that we may defeat the threats to this world together.  ", "");
//         TranslationHelper.ModifyIL(il, "There's more in it for you, though. If you'd like, I can give you the description of what I can help you with. I recommend it! ", "");
//         TranslationHelper.ModifyIL(il, "Okay, where to start... The Spatial Disk you used to form the contract can be used to access the Stellar Array, which provides abilities after defeating bosses. Nice, right?", "");
//         TranslationHelper.ModifyIL(il, "The Spatial Disk can do a lot of other things, but for now, the Stellar Array is the most important. Remember to check it often!", "");
//         TranslationHelper.ModifyIL(il, "One last thing.. I can turn energy from other worlds into direct power in the form of Essences. Combining these with other materials should be enough to create powerful Aspected Weapons.", "");
//         TranslationHelper.ModifyIL(il, "Right, my power is yours. Let's show this world what we can do.  ", "");
//         TranslationHelper.ModifyIL(il, "Well, in that case... My power is yours. Let's show this world what we can do. ", "");
//         TranslationHelper.ModifyIL(il, "It's nice to meet you. My name is Eridani.. a Starfarer. You, in turn, are my Starbearer. ", "");
//         TranslationHelper.ModifyIL(il, "Through this contract, we must work together to bring justice to those willing to harm this world. ", "");
//         TranslationHelper.ModifyIL(il, "If you are willing, I can give a description of what I can provide you with. Personally, I recommend it- knowledge is power, after all. ", "");
//         TranslationHelper.ModifyIL(il, "Right. Let's begin. With the Spatial Disk you used, you can access the Stellar Array. With the defeat of powerful foes, it will grant you strength.", "");
//         TranslationHelper.ModifyIL(il, "The Spatial Disk has plenty of other uses, but by my hypothesis we don't have access to them yet. Hopefully, as we get stronger, more facets of the Disk will open up to us.", "");
//         TranslationHelper.ModifyIL(il, "Umm.. what next..? Right. I can turn latent energy from other worlds into crystallized power- an Essence, if you will. You can turn these Essences into Aspected Weapons.", "");
//         TranslationHelper.ModifyIL(il, "That should be everything. My strength is yours... I won't let you down.  ", "");
//         TranslationHelper.ModifyIL(il, "In that case.. My power is yours. Let's show this world what we can do. ", "");
//         TranslationHelper.ModifyIL(il, "Huh? Sister? No way...  ", "");
//         TranslationHelper.ModifyIL(il, "I apologize, Asphodene. This should help. Ring any bells? ", "");
//         TranslationHelper.ModifyIL(il, "Dude. We have GOT to stop meeting like this. The nerve...! ", "");
//         TranslationHelper.ModifyIL(il, "As it stands now, you have little chance of besting them. However, while Asphodene doesn't know it, all Starfarers have an ace up their sleeve: the Stellar Nova.", "");
//         TranslationHelper.ModifyIL(il, "I know he's a loner, but.. I wish we could have spoken more. Stay safe, Perseus. ", "");
//         TranslationHelper.ModifyIL(il, "Huh, he was right. I do feel stronger- and my hair's gone all shiny! This power should be an amazing boon going forward. ", "");
//         TranslationHelper.ModifyIL(il, "Looks like my Stellar Nova is called 'Theofania Inanis.' Perhaps we'll get to use some more once we get stronger? ", "");
//         TranslationHelper.ModifyIL(il, "You should have some Prismatic Cores already. With their power, I theorize you can upgrade Stellar Novas with crafting.", "");
//         TranslationHelper.ModifyIL(il, "This is important. You need Stellar Nova energy to cast Novas. You gain Nova energy in combat. It depletes outside of combat.", "");
//         TranslationHelper.ModifyIL(il, "OK. A lot has happened, but this is a huge step forward for us. Please use the Novas well! Bye for now.", "");
//         TranslationHelper.ModifyIL(il, "Did you just say... 'sister'? You've got to be kidding... ", "");
//         TranslationHelper.ModifyIL(il, "I apologize, Eridani. This should help. Ring any bells? ", "");
//         TranslationHelper.ModifyIL(il, "We haven't talked in ages- and you show up now...?  ", "");
//         TranslationHelper.ModifyIL(il, "As it stands now, you have little chance of besting them. However, while Eridani doesn't know it, all Starfarers have an ace up their sleeve: the Stellar Nova.", "");
//         TranslationHelper.ModifyIL(il, "Perseus was never one for sticking around. I wish we could have spoken more... This power is incredible, but I need to get used to it. ", "");
//         TranslationHelper.ModifyIL(il, "My Stellar Nova is called 'Theofania Inanis.' Perhaps we will be able to utilize more once we become stronger.", "");
//         TranslationHelper.ModifyIL(il, "With Prismatic Cores, you can craft upgrades to the Stellar Nova, I believe. You can affix them in the menu directly.", "");
//         TranslationHelper.ModifyIL(il, "Don't forget: You need Stellar Nova Energy to cast Stellar Novas. You can only accrue Energy in combat.", "");
//         TranslationHelper.ModifyIL(il, "That's about it.. I know it's a lot to process, but please use the Novas well. That's all for now.", "");
//         TranslationHelper.ModifyIL(il, "...Did my hair just change color?  ", "");
//     };
// }