using Terraria.Localization;

namespace CalamityRuTranslate.CalamityMod.NPCs
{
	internal static class CalamityNpc
	{
		public static void Setup()
		{
			Npc();
		}
		private static void Npc()
		{
			ModCompatibility.CalamityMod.GetNPC("Bloatfish").DisplayName.AddTranslation(GameCulture.Russian,"Раздутая рыба");
			ModCompatibility.CalamityMod.GetNPC("BobbitWormHead").DisplayName.AddTranslation(GameCulture.Russian, "Волнистый червь");
			ModCompatibility.CalamityMod.GetNPC("BobbitWormSegment").DisplayName.AddTranslation(GameCulture.Russian, "Волнистый червь");
			ModCompatibility.CalamityMod.GetNPC("BoxJellyfish").DisplayName.AddTranslation(GameCulture.Russian,"Кубомедуза");
			ModCompatibility.CalamityMod.GetNPC("ChaoticPuffer").DisplayName.AddTranslation(GameCulture.Russian,"Хаотический иглобрюх");
			ModCompatibility.CalamityMod.GetNPC("ColossalSquid").DisplayName.AddTranslation(GameCulture.Russian, "Громадный кальмар");
			ModCompatibility.CalamityMod.GetNPC("Cuttlefish").DisplayName.AddTranslation(GameCulture.Russian,"Каракатица");
			ModCompatibility.CalamityMod.GetNPC("DevilFish").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-дьявол");
			ModCompatibility.CalamityMod.GetNPC("DevilFishAlt").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-дьявол");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmBody").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmBodyAlt").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmBodyAltHuge").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmBodyHuge").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmHead").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmHeadHuge").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmTail").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("EidolonWyrmTailHuge").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный змей");
			ModCompatibility.CalamityMod.GetNPC("GiantSquid").DisplayName.AddTranslation(GameCulture.Russian,"Гигантский кальмар");
            ModCompatibility.CalamityMod.GetNPC("GulperEelBody").DisplayName.AddTranslation(GameCulture.Russian, "Большеротый угорь");
            ModCompatibility.CalamityMod.GetNPC("GulperEelBodyAlt").DisplayName.AddTranslation(GameCulture.Russian, "Большеротый угорь");
			ModCompatibility.CalamityMod.GetNPC("GulperEelHead").DisplayName.AddTranslation(GameCulture.Russian, "Большеротый угорь");
			ModCompatibility.CalamityMod.GetNPC("GulperEelTail").DisplayName.AddTranslation(GameCulture.Russian, "Большеротый угорь");
			ModCompatibility.CalamityMod.GetNPC("Laserfish").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-лазер");
			ModCompatibility.CalamityMod.GetNPC("LuminousCorvina").DisplayName.AddTranslation(GameCulture.Russian, "Люминесцентный горбыль");
			ModCompatibility.CalamityMod.GetNPC("MirageJelly").DisplayName.AddTranslation(GameCulture.Russian,"Миражная медуза");
			ModCompatibility.CalamityMod.GetNPC("MorayEel").DisplayName.AddTranslation(GameCulture.Russian,"Мурена");
			ModCompatibility.CalamityMod.GetNPC("OarfishBody").DisplayName.AddTranslation(GameCulture.Russian,"Ремень-рыба");
			ModCompatibility.CalamityMod.GetNPC("OarfishHead").DisplayName.AddTranslation(GameCulture.Russian,"Ремень-рыба");
			ModCompatibility.CalamityMod.GetNPC("OarfishTail").DisplayName.AddTranslation(GameCulture.Russian,"Ремень-рыба");
			ModCompatibility.CalamityMod.GetNPC("Reaper").DisplayName.AddTranslation(GameCulture.Russian, "Акула-жнец");
            ModCompatibility.CalamityMod.GetNPC("ToxicMinnow").DisplayName.AddTranslation(GameCulture.Russian,"Ядовитый пескарь");
            ModCompatibility.CalamityMod.GetNPC("Viperfish").DisplayName.AddTranslation(GameCulture.Russian,"Рыба-гадюка");
            ModCompatibility.CalamityMod.GetNPC("AcidEel").DisplayName.AddTranslation(GameCulture.Russian,"Кислотный угорь");
			ModCompatibility.CalamityMod.GetNPC("BloodwormFleeing").DisplayName.AddTranslation(GameCulture.Russian,"Кровавый червь");
			ModCompatibility.CalamityMod.GetNPC("BloodwormNormal").DisplayName.AddTranslation(GameCulture.Russian,"Кровавый червь");
			ModCompatibility.CalamityMod.GetNPC("CragmawMire").DisplayName.AddTranslation(GameCulture.Russian,"Болотистый скалозев");
			ModCompatibility.CalamityMod.GetNPC("FlakBaby").DisplayName.AddTranslation(GameCulture.Russian,"Маленький краб зенитного огня");
			ModCompatibility.CalamityMod.GetNPC("FlakCrab").DisplayName.AddTranslation(GameCulture.Russian,"Краб зенитного огня");
			ModCompatibility.CalamityMod.GetNPC("GammaSlime").DisplayName.AddTranslation(GameCulture.Russian,"Гамма-слизень");
			ModCompatibility.CalamityMod.GetNPC("NuclearTerror").DisplayName.AddTranslation(GameCulture.Russian,"Ядерный террор");
			ModCompatibility.CalamityMod.GetNPC("NuclearToad").DisplayName.AddTranslation(GameCulture.Russian,"Ядерная жаба");
			ModCompatibility.CalamityMod.GetNPC("Orthocera").DisplayName.AddTranslation(GameCulture.Russian,"Ортоцераса");
			ModCompatibility.CalamityMod.GetNPC("IrradiatedSlime").DisplayName.AddTranslation(GameCulture.Russian,"Облучённый слизень");
			ModCompatibility.CalamityMod.GetNPC("Radiator").DisplayName.AddTranslation(GameCulture.Russian,"Излучатель");
			ModCompatibility.CalamityMod.GetNPC("Skyfin").DisplayName.AddTranslation(GameCulture.Russian,"Небесный плавник");
			ModCompatibility.CalamityMod.GetNPC("SulfurousSkater").DisplayName.AddTranslation(GameCulture.Russian,"Сернистая водомерка");
			ModCompatibility.CalamityMod.GetNPC("Trilobite").DisplayName.AddTranslation(GameCulture.Russian,"Трилобит");
			ModCompatibility.CalamityMod.GetNPC("WaterLeech").DisplayName.AddTranslation(GameCulture.Russian,"Водяная пиявка");
			ModCompatibility.CalamityMod.GetNPC("AquaticParasite").DisplayName.AddTranslation(GameCulture.Russian,"Акватический паразит");
			ModCompatibility.CalamityMod.GetNPC("AquaticScourgeBody").DisplayName.AddTranslation(GameCulture.Russian,"Акватический бич");
			ModCompatibility.CalamityMod.GetNPC("AquaticScourgeBodyAlt").DisplayName.AddTranslation(GameCulture.Russian,"Акватический бич");
			ModCompatibility.CalamityMod.GetNPC("AquaticScourgeHead").DisplayName.AddTranslation(GameCulture.Russian,"Акватический бич");
			ModCompatibility.CalamityMod.GetNPC("AquaticScourgeTail").DisplayName.AddTranslation(GameCulture.Russian,"Акватический бич");
			ModCompatibility.CalamityMod.GetNPC("AquaticSeekerBody").DisplayName.AddTranslation(GameCulture.Russian,"Акватический искатель");
			ModCompatibility.CalamityMod.GetNPC("AquaticSeekerHead").DisplayName.AddTranslation(GameCulture.Russian,"Акватический искатель");
			ModCompatibility.CalamityMod.GetNPC("AquaticSeekerTail").DisplayName.AddTranslation(GameCulture.Russian,"Акватический искатель");
			ModCompatibility.CalamityMod.GetNPC("AquaticUrchin").DisplayName.AddTranslation(GameCulture.Russian,"Акватический ёж");
			ModCompatibility.CalamityMod.GetNPC("Aries").DisplayName.AddTranslation(GameCulture.Russian,"Овен");
			ModCompatibility.CalamityMod.GetNPC("AstralachneaGround").DisplayName.AddTranslation(GameCulture.Russian,"Астралонея");
			ModCompatibility.CalamityMod.GetNPC("AstralachneaWall").DisplayName.AddTranslation(GameCulture.Russian,"Астралонея");
			ModCompatibility.CalamityMod.GetNPC("AstralProbe").DisplayName.AddTranslation(GameCulture.Russian,"Астральный зонд");
			ModCompatibility.CalamityMod.GetNPC("AstralSlime").DisplayName.AddTranslation(GameCulture.Russian,"Астральный слизень");
			ModCompatibility.CalamityMod.GetNPC("Atlas").DisplayName.AddTranslation(GameCulture.Russian,"Атлант");
			ModCompatibility.CalamityMod.GetNPC("BigSightseer").DisplayName.AddTranslation(GameCulture.Russian,"Большой путешественник");
			ModCompatibility.CalamityMod.GetNPC("AstralSeekerSpit").DisplayName.AddTranslation(GameCulture.Russian,"Плюющийся искатель");
			ModCompatibility.CalamityMod.GetNPC("EnchantedNightcrawler").DisplayName.AddTranslation(GameCulture.Russian,"Зачарованный ночной ползун");
			ModCompatibility.CalamityMod.GetNPC("FusionFeeder").DisplayName.AddTranslation(GameCulture.Russian,"Питатель реакций");
			ModCompatibility.CalamityMod.GetNPC("Hadarian").DisplayName.AddTranslation(GameCulture.Russian,"Хадариан");
			ModCompatibility.CalamityMod.GetNPC("Hive").DisplayName.AddTranslation(GameCulture.Russian,"Улей");
			ModCompatibility.CalamityMod.GetNPC("Hiveling").DisplayName.AddTranslation(GameCulture.Russian,"Ульевик");
			ModCompatibility.CalamityMod.GetNPC("Mantis").DisplayName.AddTranslation(GameCulture.Russian,"Богомол");
			ModCompatibility.CalamityMod.GetNPC("Nova").DisplayName.AddTranslation(GameCulture.Russian,"Нова");
			ModCompatibility.CalamityMod.GetNPC("SmallSightseer").DisplayName.AddTranslation(GameCulture.Russian,"Малый путешественник");
			ModCompatibility.CalamityMod.GetNPC("StellarCulex").DisplayName.AddTranslation(GameCulture.Russian,"Звёздный москит");
			ModCompatibility.CalamityMod.GetNPC("Twinkler").DisplayName.AddTranslation(GameCulture.Russian,"Мерцатель");
			ModCompatibility.CalamityMod.GetNPC("AstrumAureus").DisplayName.AddTranslation(GameCulture.Russian,"Аструм Ареус");
			ModCompatibility.CalamityMod.GetNPC("AureusSpawn").DisplayName.AddTranslation(GameCulture.Russian,"Отродье Ареуса");
			ModCompatibility.CalamityMod.GetNPC("AstrumDeusBodySpectral").DisplayName.AddTranslation(GameCulture.Russian,"Аструм Деус");
			ModCompatibility.CalamityMod.GetNPC("AstrumDeusHeadSpectral").DisplayName.AddTranslation(GameCulture.Russian,"Аструм Деус");
			ModCompatibility.CalamityMod.GetNPC("AstrumDeusTailSpectral").DisplayName.AddTranslation(GameCulture.Russian,"Аструм Деус");
			ModCompatibility.CalamityMod.GetNPC("Brimling").DisplayName.AddTranslation(GameCulture.Russian,"Серняш");
			ModCompatibility.CalamityMod.GetNPC("BrimstoneElemental").DisplayName.AddTranslation(GameCulture.Russian,"Серный элементаль");
			ModCompatibility.CalamityMod.GetNPC("Bumblefuck").DisplayName.AddTranslation(GameCulture.Russian,"Псевдодракон");
			ModCompatibility.CalamityMod.GetNPC("Bumblefuck2").DisplayName.AddTranslation(GameCulture.Russian,"Драконий роевик");
			ModCompatibility.CalamityMod.GetNPC("Calamitas").DisplayName.AddTranslation(GameCulture.Russian,"Каламитас");
			ModCompatibility.CalamityMod.GetNPC("CalamitasRun").DisplayName.AddTranslation(GameCulture.Russian,"Катаклизм");
			ModCompatibility.CalamityMod.GetNPC("CalamitasRun2").DisplayName.AddTranslation(GameCulture.Russian,"Катастрофа");
			ModCompatibility.CalamityMod.GetNPC("CalamitasRun3").DisplayName.AddTranslation(GameCulture.Russian,"Каламитас");
			ModCompatibility.CalamityMod.GetNPC("LifeSeeker").DisplayName.AddTranslation(GameCulture.Russian,"Искатель жизни");
			ModCompatibility.CalamityMod.GetNPC("SoulSeeker").DisplayName.AddTranslation(GameCulture.Russian,"Искатель душ");
			ModCompatibility.CalamityMod.GetNPC("CeaselessVoid").DisplayName.AddTranslation(GameCulture.Russian,"Нескончаемая пустота");
			ModCompatibility.CalamityMod.GetNPC("DarkEnergy").DisplayName.AddTranslation(GameCulture.Russian,"Тёмная энергия");
			ModCompatibility.CalamityMod.GetNPC("DarkEnergy2").DisplayName.AddTranslation(GameCulture.Russian,"Тёмная энергия");
			ModCompatibility.CalamityMod.GetNPC("DarkEnergy3").DisplayName.AddTranslation(GameCulture.Russian,"Тёмная энергия");
			ModCompatibility.CalamityMod.GetNPC("CrabShroom").DisplayName.AddTranslation(GameCulture.Russian,"Крабовый гриб");
			ModCompatibility.CalamityMod.GetNPC("CrabulonIdle").DisplayName.AddTranslation(GameCulture.Russian,"Крабулон");
			ModCompatibility.CalamityMod.GetNPC("CalamityEye").DisplayName.AddTranslation(GameCulture.Russian,"Глаз бедствия");
			ModCompatibility.CalamityMod.GetNPC("CharredSlime").DisplayName.AddTranslation(GameCulture.Russian,"Обугленный слизень");
			ModCompatibility.CalamityMod.GetNPC("CultistAssassin").DisplayName.AddTranslation(GameCulture.Russian,"Культист-ассасин");
			ModCompatibility.CalamityMod.GetNPC("DespairStone").DisplayName.AddTranslation(GameCulture.Russian, "Камень отчаяния");
			ModCompatibility.CalamityMod.GetNPC("Scryllar").DisplayName.AddTranslation(GameCulture.Russian,"Скриллар");
			ModCompatibility.CalamityMod.GetNPC("ScryllarRage").DisplayName.AddTranslation(GameCulture.Russian,"Скриллар");
			ModCompatibility.CalamityMod.GetNPC("SoulSlurper").DisplayName.AddTranslation(GameCulture.Russian,"Поглотитель душ");
			ModCompatibility.CalamityMod.GetNPC("Cryocore").DisplayName.AddTranslation(GameCulture.Russian,"Криоядро");
			ModCompatibility.CalamityMod.GetNPC("Cryocore2").DisplayName.AddTranslation(GameCulture.Russian,"Криоядро");
			ModCompatibility.CalamityMod.GetNPC("Cryogen").DisplayName.AddTranslation(GameCulture.Russian,"Криоген");
			ModCompatibility.CalamityMod.GetNPC("CryogenIce").DisplayName.AddTranslation(GameCulture.Russian,"Щит Криогена");
			ModCompatibility.CalamityMod.GetNPC("IceMass").DisplayName.AddTranslation(GameCulture.Russian,"Дух авроры");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeBody").DisplayName.AddTranslation(GameCulture.Russian,"Пустынный бич");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeHead").DisplayName.AddTranslation(GameCulture.Russian,"Пустынный Бич");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeTail").DisplayName.AddTranslation(GameCulture.Russian,"Пустынный Бич");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeBodySmall").DisplayName.AddTranslation(GameCulture.Russian,"Младший пустынный бич");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeHeadSmall").DisplayName.AddTranslation(GameCulture.Russian,"Младший пустынный бич");
			ModCompatibility.CalamityMod.GetNPC("DesertScourgeTailSmall").DisplayName.AddTranslation(GameCulture.Russian,"Младший пустынный бич");
			ModCompatibility.CalamityMod.GetNPC("DriedSeekerBody").DisplayName.AddTranslation(GameCulture.Russian,"Обезвоженный искатель");
			ModCompatibility.CalamityMod.GetNPC("DriedSeekerHead").DisplayName.AddTranslation(GameCulture.Russian,"Обезвоженный искатель");
			ModCompatibility.CalamityMod.GetNPC("DriedSeekerTail").DisplayName.AddTranslation(GameCulture.Russian,"Обезвоженный искатель");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsBody").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsHead").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsTail").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsBody2").DisplayName.AddTranslation(GameCulture.Russian,"Космический защитник");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsHead2").DisplayName.AddTranslation(GameCulture.Russian,"Космический защитник");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsTail2").DisplayName.AddTranslation(GameCulture.Russian,"Космический защитник");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsBodyS").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsHeadS").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("DevourerofGodsTailS").DisplayName.AddTranslation(GameCulture.Russian,"Пожиратель Богов");
			ModCompatibility.CalamityMod.GetNPC("GreatSandShark").DisplayName.AddTranslation(GameCulture.Russian, "Великая песчаная акула");
			ModCompatibility.CalamityMod.GetNPC("DankCreeper").DisplayName.AddTranslation(GameCulture.Russian,"Промозглый ползун");
			ModCompatibility.CalamityMod.GetNPC("DarkHeart").DisplayName.AddTranslation(GameCulture.Russian,"Тёмное сердце");
			ModCompatibility.CalamityMod.GetNPC("HiveBlob").DisplayName.AddTranslation(GameCulture.Russian,"Шар Улья");
			ModCompatibility.CalamityMod.GetNPC("HiveBlob2").DisplayName.AddTranslation(GameCulture.Russian,"Шар Улья");
			ModCompatibility.CalamityMod.GetNPC("HiveCyst").DisplayName.AddTranslation(GameCulture.Russian,"Киста Улья");
			ModCompatibility.CalamityMod.GetNPC("HiveMind").DisplayName.AddTranslation(GameCulture.Russian,"Разум Улья");
			ModCompatibility.CalamityMod.GetNPC("HiveMindP2").DisplayName.AddTranslation(GameCulture.Russian,"Разум Улья");
			ModCompatibility.CalamityMod.GetNPC("AquaticAberration").DisplayName.AddTranslation(GameCulture.Russian,"Акватическая аномалия");
			ModCompatibility.CalamityMod.GetNPC("Leviathan").DisplayName.AddTranslation(GameCulture.Russian,"Левиафан");
			ModCompatibility.CalamityMod.GetNPC("LeviathanStart").DisplayName.AddTranslation(GameCulture.Russian,"???");
			ModCompatibility.CalamityMod.GetNPC("Parasea").DisplayName.AddTranslation(GameCulture.Russian,"Парацея");
			ModCompatibility.CalamityMod.GetNPC("Siren").DisplayName.AddTranslation(GameCulture.Russian,"Анахита");
			ModCompatibility.CalamityMod.GetNPC("SirenIce").DisplayName.AddTranslation(GameCulture.Russian,"Ледяной щит");
			ModCompatibility.CalamityMod.GetNPC("AeroSlime").DisplayName.AddTranslation(GameCulture.Russian,"Аэрослизень");
			ModCompatibility.CalamityMod.GetNPC("AngryDog").DisplayName.AddTranslation(GameCulture.Russian,"Злая собака");
			ModCompatibility.CalamityMod.GetNPC("ArmoredDiggerBody").DisplayName.AddTranslation(GameCulture.Russian,"Бронированный копатель");
			ModCompatibility.CalamityMod.GetNPC("ArmoredDiggerHead").DisplayName.AddTranslation(GameCulture.Russian,"Бронированный копатель");
			ModCompatibility.CalamityMod.GetNPC("ArmoredDiggerTail").DisplayName.AddTranslation(GameCulture.Russian,"Бронированный копатель");
			ModCompatibility.CalamityMod.GetNPC("BlightedEye").DisplayName.AddTranslation(GameCulture.Russian,"Гибельный глаз");
			ModCompatibility.CalamityMod.GetNPC("BloomSlime").DisplayName.AddTranslation(GameCulture.Russian,"Цветущий слизень");
			ModCompatibility.CalamityMod.GetNPC("Bohldohr").DisplayName.AddTranslation(GameCulture.Russian,"Бурхыжнек");
			ModCompatibility.CalamityMod.GetNPC("Cnidrion").DisplayName.AddTranslation(GameCulture.Russian,"Гидроид");
			ModCompatibility.CalamityMod.GetNPC("CosmicElemental").DisplayName.AddTranslation(GameCulture.Russian,"Космический элементаль");
			ModCompatibility.CalamityMod.GetNPC("CrawlerAmber").DisplayName.AddTranslation(GameCulture.Russian,"Янтарный ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerAmethyst").DisplayName.AddTranslation(GameCulture.Russian,"Аметистовый ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerCrystal").DisplayName.AddTranslation(GameCulture.Russian,"Кристальный ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerDiamond").DisplayName.AddTranslation(GameCulture.Russian,"Алмазный ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerEmerald").DisplayName.AddTranslation(GameCulture.Russian,"Изумрудный ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerRuby").DisplayName.AddTranslation(GameCulture.Russian,"Рубиновый ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerSapphire").DisplayName.AddTranslation(GameCulture.Russian,"Сапфировый ползун");
			ModCompatibility.CalamityMod.GetNPC("CrawlerTopaz").DisplayName.AddTranslation(GameCulture.Russian,"Топазовый ползун");
			ModCompatibility.CalamityMod.GetNPC("CrimulanBlightSlime").DisplayName.AddTranslation(GameCulture.Russian,"Кримтановый гибельный слизень");
			ModCompatibility.CalamityMod.GetNPC("Cryon").DisplayName.AddTranslation(GameCulture.Russian,"Крион");
			ModCompatibility.CalamityMod.GetNPC("CryoSlime").DisplayName.AddTranslation(GameCulture.Russian,"Криослизень");
			ModCompatibility.CalamityMod.GetNPC("EbonianBlightSlime").DisplayName.AddTranslation(GameCulture.Russian,"Эбонитовый гибельный слизень");
			ModCompatibility.CalamityMod.GetNPC("Eidolist").DisplayName.AddTranslation(GameCulture.Russian,"Фантолист");
			ModCompatibility.CalamityMod.GetNPC("FearlessGoldfishWarrior").DisplayName.AddTranslation(GameCulture.Russian,"Бесстрашная золотая рыбка-воин");
            ModCompatibility.CalamityMod.GetNPC("Frogfish").DisplayName.AddTranslation(GameCulture.Russian, "Морской чёрт");
			ModCompatibility.CalamityMod.GetNPC("HeatSpirit").DisplayName.AddTranslation(GameCulture.Russian,"Дух тепла");
			ModCompatibility.CalamityMod.GetNPC("Horse").DisplayName.AddTranslation(GameCulture.Russian,"Земляной элементаль");
			ModCompatibility.CalamityMod.GetNPC("IceClasper").DisplayName.AddTranslation(GameCulture.Russian,"Ледяной клещ");
			ModCompatibility.CalamityMod.GetNPC("ImpiousImmolator").DisplayName.AddTranslation(GameCulture.Russian,"Нечестивый жертвенник");
			ModCompatibility.CalamityMod.GetNPC("KingSlimeJewel").DisplayName.AddTranslation(GameCulture.Russian,"Королевская драгоценность");
            ModCompatibility.CalamityMod.GetNPC("MantisShrimp").DisplayName.AddTranslation(GameCulture.Russian, "Богомол-креветка");
			ModCompatibility.CalamityMod.GetNPC("OverloadedSoldier").DisplayName.AddTranslation(GameCulture.Russian,"Перегруженный солдат");
			ModCompatibility.CalamityMod.GetNPC("PerennialSlime").DisplayName.AddTranslation(GameCulture.Russian,"Многолетний слизень");
			ModCompatibility.CalamityMod.GetNPC("PhantomDebris").DisplayName.AddTranslation(GameCulture.Russian,"Призрачный мусор");
			ModCompatibility.CalamityMod.GetNPC("PhantomSpirit").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный дух");
			ModCompatibility.CalamityMod.GetNPC("PhantomSpiritL").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный дух");
			ModCompatibility.CalamityMod.GetNPC("PhantomSpiritM").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный дух");
			ModCompatibility.CalamityMod.GetNPC("PhantomSpiritS").DisplayName.AddTranslation(GameCulture.Russian,"Фантомный дух");
			ModCompatibility.CalamityMod.GetNPC("Piggy").DisplayName.AddTranslation(GameCulture.Russian,"Поросёнок");
			ModCompatibility.CalamityMod.GetNPC("Pitbull").DisplayName.AddTranslation(GameCulture.Russian,"Питбуль");
			ModCompatibility.CalamityMod.GetNPC("PlagueBee").DisplayName.AddTranslation(GameCulture.Russian,"Чумной крушитель");
			ModCompatibility.CalamityMod.GetNPC("PlagueBeeLarge").DisplayName.AddTranslation(GameCulture.Russian,"Чумной крушитель");
			ModCompatibility.CalamityMod.GetNPC("PlaguedDerpling").DisplayName.AddTranslation(GameCulture.Russian,"Чумная блоха");
			ModCompatibility.CalamityMod.GetNPC("PlaguedFlyingFox").DisplayName.AddTranslation(GameCulture.Russian,"Плавитель");
			ModCompatibility.CalamityMod.GetNPC("PlaguedJungleSlime").DisplayName.AddTranslation(GameCulture.Russian, "Ядовитый слизень");
			ModCompatibility.CalamityMod.GetNPC("PlaguedTortoise").DisplayName.AddTranslation(GameCulture.Russian,"Чумной панцирь");
			ModCompatibility.CalamityMod.GetNPC("ProfanedEnergyBody").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённая энергия");
			ModCompatibility.CalamityMod.GetNPC("ProfanedEnergyLantern").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённая энергия");
			ModCompatibility.CalamityMod.GetNPC("SandTortoise").DisplayName.AddTranslation(GameCulture.Russian,"Песчаная черепаха");
			ModCompatibility.CalamityMod.GetNPC("ScornEater").DisplayName.AddTranslation(GameCulture.Russian, "Презренный пожиратель");
            ModCompatibility.CalamityMod.GetNPC("SeaUrchin").DisplayName.AddTranslation(GameCulture.Russian, "Морской ёж");
			ModCompatibility.CalamityMod.GetNPC("ShockstormShuttle").DisplayName.AddTranslation(GameCulture.Russian,"Шаттл шокового шторма");
			ModCompatibility.CalamityMod.GetNPC("StormlionCharger").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой лев");
			ModCompatibility.CalamityMod.GetNPC("SunBat").DisplayName.AddTranslation(GameCulture.Russian,"Солнечная мышь");
			ModCompatibility.CalamityMod.GetNPC("Sunskater").DisplayName.AddTranslation(GameCulture.Russian,"Солнечная водомерка");
			ModCompatibility.CalamityMod.GetNPC("SuperDummyNPC").DisplayName.AddTranslation(GameCulture.Russian,"Сверхманекен");
			ModCompatibility.CalamityMod.GetNPC("ThiccWaifu").DisplayName.AddTranslation(GameCulture.Russian,"Облачный элементаль");
			ModCompatibility.CalamityMod.GetNPC("WulfrumDrone").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый дрон");
			ModCompatibility.CalamityMod.GetNPC("WulfrumGyrator").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый вращатель");
			ModCompatibility.CalamityMod.GetNPC("WulfrumHovercraft").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый автолёт");
			ModCompatibility.CalamityMod.GetNPC("WulfrumPylon").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый пилон");
			ModCompatibility.CalamityMod.GetNPC("WulfrumRover").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый скиталец");
			ModCompatibility.CalamityMod.GetNPC("WulfrumSlime").DisplayName.AddTranslation(GameCulture.Russian,"Вульфрумовый слизень");
			ModCompatibility.CalamityMod.GetNPC("OldDuke").DisplayName.AddTranslation(GameCulture.Russian,"Старый Герцог");
			ModCompatibility.CalamityMod.GetNPC("OldDukeSharkron").DisplayName.AddTranslation(GameCulture.Russian,"Сернистый акулон");
			ModCompatibility.CalamityMod.GetNPC("OldDukeToothBall").DisplayName.AddTranslation(GameCulture.Russian, "Зубастый шар");
			ModCompatibility.CalamityMod.GetNPC("PerforatorBodyLarge").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorBodyMedium").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorBodySmall").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorCyst").DisplayName.AddTranslation(GameCulture.Russian,"Киста Перфораторов");
			ModCompatibility.CalamityMod.GetNPC("PerforatorHeadLarge").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorHeadMedium").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorHeadSmall").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorHive").DisplayName.AddTranslation(GameCulture.Russian,"Улей перфораторов");
			ModCompatibility.CalamityMod.GetNPC("PerforatorTailLarge").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorTailMedium").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PerforatorTailSmall").DisplayName.AddTranslation(GameCulture.Russian,"Перфоратор");
			ModCompatibility.CalamityMod.GetNPC("PlagueBeeG").DisplayName.AddTranslation(GameCulture.Russian, "Чумной крушитель");
			ModCompatibility.CalamityMod.GetNPC("PlagueBeeLargeG").DisplayName.AddTranslation(GameCulture.Russian, "Чумной крушитель");
			ModCompatibility.CalamityMod.GetNPC("PlaguebringerGoliath").DisplayName.AddTranslation(GameCulture.Russian,"Разносчица чумы, Голиаф");
			ModCompatibility.CalamityMod.GetNPC("PlaguebringerShade").DisplayName.AddTranslation(GameCulture.Russian,"Разносчица чумы");
			ModCompatibility.CalamityMod.GetNPC("PlagueHomingMissile").DisplayName.AddTranslation(GameCulture.Russian,"Чумная самонаводящаяся ракета");
			ModCompatibility.CalamityMod.GetNPC("PlagueMine").DisplayName.AddTranslation(GameCulture.Russian,"Чумная мина");
			ModCompatibility.CalamityMod.GetNPC("PhantomFuckYou").DisplayName.AddTranslation(GameCulture.Russian,"Фантом");
			ModCompatibility.CalamityMod.GetNPC("Polterghast").DisplayName.AddTranslation(GameCulture.Russian,"Полтергаст");
			ModCompatibility.CalamityMod.GetNPC("PolterghastHook").DisplayName.AddTranslation(GameCulture.Russian,"Крюк Полтергаста");
			ModCompatibility.CalamityMod.GetNPC("PolterPhantom").DisplayName.AddTranslation(GameCulture.Russian, "Полтергаст");
			ModCompatibility.CalamityMod.GetNPC("ProfanedGuardianBoss").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("ProfanedGuardianBoss2").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("ProfanedGuardianBoss3").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("Providence").DisplayName.AddTranslation(GameCulture.Russian,"Провиденс, Осквернённая Богиня");
			ModCompatibility.CalamityMod.GetNPC("ProvSpawnDefense").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("ProvSpawnHealer").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("ProvSpawnOffense").DisplayName.AddTranslation(GameCulture.Russian,"Осквернённый страж");
			ModCompatibility.CalamityMod.GetNPC("FlamePillar").DisplayName.AddTranslation(GameCulture.Russian,"Огненный столб");
			ModCompatibility.CalamityMod.GetNPC("RavagerBody").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerClawLeft").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerClawRight").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerHead").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerHead2").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerLegLeft").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RavagerLegRight").DisplayName.AddTranslation(GameCulture.Russian,"Разрушитель");
			ModCompatibility.CalamityMod.GetNPC("RockPillar").DisplayName.AddTranslation(GameCulture.Russian,"Каменный столб");
			ModCompatibility.CalamityMod.GetNPC("CosmicLantern").DisplayName.AddTranslation(GameCulture.Russian,"Космический фонарь");
			ModCompatibility.CalamityMod.GetNPC("Signus").DisplayName.AddTranslation(GameCulture.Russian,"Сигнус, Посланник Пожирателя");
			ModCompatibility.CalamityMod.GetNPC("SignusBomb").DisplayName.AddTranslation(GameCulture.Russian,"Космическая мина");
			ModCompatibility.CalamityMod.GetNPC("SlimeGod").DisplayName.AddTranslation(GameCulture.Russian,"Эбонитовый Бог слизней");
			ModCompatibility.CalamityMod.GetNPC("SlimeGodCore").DisplayName.AddTranslation(GameCulture.Russian,"Бог слизней");
			ModCompatibility.CalamityMod.GetNPC("SlimeGodRun").DisplayName.AddTranslation(GameCulture.Russian,"Кримтановый Бог слизней");
			ModCompatibility.CalamityMod.GetNPC("SlimeGodRunSplit").DisplayName.AddTranslation(GameCulture.Russian,"Кримтановый Бог слизней");
			ModCompatibility.CalamityMod.GetNPC("SlimeGodSplit").DisplayName.AddTranslation(GameCulture.Russian,"Эбонитовый Бог слизней");
			ModCompatibility.CalamityMod.GetNPC("SlimeSpawnCorrupt").DisplayName.AddTranslation(GameCulture.Russian,"Искажённый слизень");
			ModCompatibility.CalamityMod.GetNPC("SlimeSpawnCorrupt2").DisplayName.AddTranslation(GameCulture.Russian,"Искажённый слизень");
			ModCompatibility.CalamityMod.GetNPC("SlimeSpawnCrimson").DisplayName.AddTranslation(GameCulture.Russian,"Багряный слизень");
			ModCompatibility.CalamityMod.GetNPC("SlimeSpawnCrimson2").DisplayName.AddTranslation(GameCulture.Russian,"Багряный слизень");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverBody").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverBodyNaked").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverHead").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverHeadNaked").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverTail").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("StormWeaverTailNaked").DisplayName.AddTranslation(GameCulture.Russian,"Штормовой Ткач");
			ModCompatibility.CalamityMod.GetNPC("AnthozoanCrab").DisplayName.AddTranslation(GameCulture.Russian,"Коралловый краб");
            ModCompatibility.CalamityMod.GetNPC("BelchingCoral").DisplayName.AddTranslation(GameCulture.Russian,"Изрыгающий коралл");
            ModCompatibility.CalamityMod.GetNPC("Catfish").DisplayName.AddTranslation(GameCulture.Russian,"Сом");
            ModCompatibility.CalamityMod.GetNPC("Flounder").DisplayName.AddTranslation(GameCulture.Russian,"Камбала");
            ModCompatibility.CalamityMod.GetNPC("Gnasher").DisplayName.AddTranslation(GameCulture.Russian,"Грифовая черепаха");
            ModCompatibility.CalamityMod.GetNPC("Mauler").DisplayName.AddTranslation(GameCulture.Russian,"Мучитель");
            ModCompatibility.CalamityMod.GetNPC("MicrobialCluster").DisplayName.AddTranslation(GameCulture.Russian,"Сгусток микроорганизмов");
            ModCompatibility.CalamityMod.GetNPC("Trasher").DisplayName.AddTranslation(GameCulture.Russian,"Мусорщик");
            ModCompatibility.CalamityMod.GetNPC("BlindedAngler").DisplayName.AddTranslation(GameCulture.Russian,"Слепой удильщик");
			ModCompatibility.CalamityMod.GetNPC("Clam").DisplayName.AddTranslation(GameCulture.Russian,"Моллюск");
			ModCompatibility.CalamityMod.GetNPC("EutrophicRay").DisplayName.AddTranslation(GameCulture.Russian,"Эвтрофный скат");
			ModCompatibility.CalamityMod.GetNPC("GhostBell").DisplayName.AddTranslation(GameCulture.Russian,"Призрачный колокольчик");
			ModCompatibility.CalamityMod.GetNPC("GhostBellSmall").DisplayName.AddTranslation(GameCulture.Russian,"Маленький призрачный колокольчик");
			ModCompatibility.CalamityMod.GetNPC("GiantClam").DisplayName.AddTranslation(GameCulture.Russian,"Гигантский Моллюск");
			ModCompatibility.CalamityMod.GetNPC("PrismTurtle").DisplayName.AddTranslation(GameCulture.Russian,"Призмоспин");
			ModCompatibility.CalamityMod.GetNPC("SeaFloaty").DisplayName.AddTranslation(GameCulture.Russian,"Морской поплавок");
			ModCompatibility.CalamityMod.GetNPC("SeaMinnow").DisplayName.AddTranslation(GameCulture.Russian,"Морской пескарь");
			ModCompatibility.CalamityMod.GetNPC("SeaSerpent1").DisplayName.AddTranslation(GameCulture.Russian,"Морской змей");
			ModCompatibility.CalamityMod.GetNPC("SeaSerpent2").DisplayName.AddTranslation(GameCulture.Russian,"Морской змей");
			ModCompatibility.CalamityMod.GetNPC("SeaSerpent3").DisplayName.AddTranslation(GameCulture.Russian,"Морской змей");
			ModCompatibility.CalamityMod.GetNPC("SeaSerpent4").DisplayName.AddTranslation(GameCulture.Russian,"Морской змей");
			ModCompatibility.CalamityMod.GetNPC("SeaSerpent5").DisplayName.AddTranslation(GameCulture.Russian,"Морской змей");
			ModCompatibility.CalamityMod.GetNPC("SCalWormBody").DisplayName.AddTranslation(GameCulture.Russian,"Могильщик");
			ModCompatibility.CalamityMod.GetNPC("SCalWormHead").DisplayName.AddTranslation(GameCulture.Russian,"Могильщик");
			ModCompatibility.CalamityMod.GetNPC("SCalWormTail").DisplayName.AddTranslation(GameCulture.Russian,"Могильщик");
			ModCompatibility.CalamityMod.GetNPC("SCalWormBodyWeak").DisplayName.AddTranslation(GameCulture.Russian,"Серное сердце");
			ModCompatibility.CalamityMod.GetNPC("SCalWormHeart").DisplayName.AddTranslation(GameCulture.Russian,"Серное сердце");
			ModCompatibility.CalamityMod.GetNPC("SoulSeekerSupreme").DisplayName.AddTranslation(GameCulture.Russian,"Искатель душ");
			ModCompatibility.CalamityMod.GetNPC("SupremeCalamitas").DisplayName.AddTranslation(GameCulture.Russian,"Высшая Каламитас");
			ModCompatibility.CalamityMod.GetNPC("SupremeCataclysm").DisplayName.AddTranslation(GameCulture.Russian,"Высший Катаклизм");
			ModCompatibility.CalamityMod.GetNPC("SupremeCatastrophe").DisplayName.AddTranslation(GameCulture.Russian,"Высший Катастрофа");
			ModCompatibility.CalamityMod.GetNPC("DetonatingFlare").DisplayName.AddTranslation(GameCulture.Russian,"Взрывающиеся огни");
			ModCompatibility.CalamityMod.GetNPC("DetonatingFlare2").DisplayName.AddTranslation(GameCulture.Russian,"Взрывающиеся огни");
			ModCompatibility.CalamityMod.GetNPC("Yharon").DisplayName.AddTranslation(GameCulture.Russian,"Дракон Джунглей, Ярон");
			ModCompatibility.CalamityMod.GetNPC("DILF").DisplayName.AddTranslation(GameCulture.Russian,"Архимаг");
			ModCompatibility.CalamityMod.GetNPC("FAP").DisplayName.AddTranslation(GameCulture.Russian,"Пьяная принцесса");
			ModCompatibility.CalamityMod.GetNPC("SEAHOE").DisplayName.AddTranslation(GameCulture.Russian,"Морской король");
			ModCompatibility.CalamityMod.GetNPC("THIEF").DisplayName.AddTranslation(GameCulture.Russian,"Бандит");
		}
	}
}
