using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ThoriumMod.Buffs
{
	internal class ThoriumBuffs
	{
		public static void Setup()
		{
			Buffs();
		}
		private static void Buffs()
		{
			Mod thorium = ModLoader.GetMod("ThoriumMod");
			
			thorium.GetBuff("AbyssalShell").DisplayName.AddTranslation(GameCulture.Russian, "Глубоководный панцирь");
			thorium.GetBuff("AbyssalShell").Description.AddTranslation(GameCulture.Russian, "Теперь вам почти ничего не навредит!");
			thorium.GetBuff("AbyssalShellWeak").DisplayName.AddTranslation(GameCulture.Russian, "Давление глубин");
			thorium.GetBuff("AbyssalShellWeak").Description.AddTranslation(GameCulture.Russian, "Урон, защита, и скорость передвижения значительно снижены");
			thorium.GetBuff("AquaAffinity").DisplayName.AddTranslation(GameCulture.Russian, "Родство с водой");
			thorium.GetBuff("AquaAffinity").Description.AddTranslation(GameCulture.Russian, "Пока вы в воде, скорость передвижения повышена");
			thorium.GetBuff("Aquamancer").DisplayName.AddTranslation(GameCulture.Russian, "Аквамант");
			thorium.GetBuff("Aquamancer").Description.AddTranslation(GameCulture.Russian, "Ваш магический урон и скорость чтения заклинаний в значительной степени повышены");
			thorium.GetBuff("AquaticAptitude").DisplayName.AddTranslation(GameCulture.Russian, "Поощрение воды");
			thorium.GetBuff("AquaticAptitude").Description.AddTranslation(GameCulture.Russian, "Окружающая вода усиливает вас!");
			thorium.GetBuff("ArtilleryBuff").DisplayName.AddTranslation(GameCulture.Russian, "Артиллерия");
			thorium.GetBuff("ArtilleryBuff").Description.AddTranslation(GameCulture.Russian, "Увеличивает ваше максимальное количество стражей");
			thorium.GetBuff("AssassinBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ассасин");
			thorium.GetBuff("AssassinBuff").Description.AddTranslation(GameCulture.Russian, "Вне боя критические метательные атаки наносят в 4 раза больше урона");
			thorium.GetBuff("BatRepellentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Репеллент: Летучие мыши");
			thorium.GetBuff("BatRepellentBuff").Description.AddTranslation(GameCulture.Russian, "Большинство летучих мышей становятся дружелюбными");
			thorium.GetBuff("BeetleCarapace").DisplayName.AddTranslation(GameCulture.Russian, "Жучий панцирь");
			thorium.GetBuff("BeetleCarapace").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышено. Также вы отражаете часть урона");
			thorium.GetBuff("BerserkSoul").DisplayName.AddTranslation(GameCulture.Russian, "Душа берсерка");
			thorium.GetBuff("BerserkSoul").Description.AddTranslation(GameCulture.Russian, "Если этот противник умрет, наружу вырвется агрессивный дух");
			thorium.GetBuff("BlightFever").DisplayName.AddTranslation(GameCulture.Russian, "Лихорадка");
			thorium.GetBuff("BlightFever").Description.AddTranslation(GameCulture.Russian, "\t оставил на этом существе свою печать...");
			thorium.GetBuff("BloodRush").DisplayName.AddTranslation(GameCulture.Russian, "Ускоренное сердцебиение");
			thorium.GetBuff("BloodRush").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения и добычи повышены на 15%");
			thorium.GetBuff("BouncingFlameBuff").DisplayName.AddTranslation(GameCulture.Russian, "Цепное пламя");
			thorium.GetBuff("BouncingFlameBuff").Description.AddTranslation(GameCulture.Russian, "Ваши огненные эффекты распространяются на ближайших врагов");
			thorium.GetBuff("Bubbled").DisplayName.AddTranslation(GameCulture.Russian, "Запузырен");
			thorium.GetBuff("Bubbled").Description.AddTranslation(GameCulture.Russian, "Вы улетаете!");
			thorium.GetBuff("CactusJuice").DisplayName.AddTranslation(GameCulture.Russian, "Колючий и вкусный");
			thorium.GetBuff("CactusJuice").Description.AddTranslation(GameCulture.Russian, "Вы невосприимчивы к большинству эффектов влияющих на характеристики");
			thorium.GetBuff("CalmWaters").DisplayName.AddTranslation(GameCulture.Russian, "Незапятнанные воды");
			thorium.GetBuff("CalmWaters").Description.AddTranslation(GameCulture.Russian, "Без скверного присутствия Абиссиона тут стало будто легче дышать");
			thorium.GetBuff("CannotChain").DisplayName.AddTranslation(GameCulture.Russian, "Наэлектризован!");
			thorium.GetBuff("CannotChain").Description.AddTranslation(GameCulture.Russian, "Не попадет под влияние цепных молний");
			thorium.GetBuff("ChaosState").DisplayName.AddTranslation(GameCulture.Russian, "Состояние хаоса: Телепортация");
			thorium.GetBuff("ChaosState").Description.AddTranslation(GameCulture.Russian, "Ваше тело все еще восстанавливается от эффекта зеркала");
			thorium.GetBuff("Charmed").DisplayName.AddTranslation(GameCulture.Russian, "Очарован");
			thorium.GetBuff("Charmed").Description.AddTranslation(GameCulture.Russian, "Этот враг не может устоять перед вашей привлекательностью!");
			thorium.GetBuff("Chill").DisplayName.AddTranslation(GameCulture.Russian, "Озноб");
			thorium.GetBuff("Chill").Description.AddTranslation(GameCulture.Russian, "Становится прохладно");
			thorium.GetBuff("ChokingDepths").DisplayName.AddTranslation(GameCulture.Russian, "Удушающая аура");
			thorium.GetBuff("ChokingDepths").Description.AddTranslation(GameCulture.Russian, "Присутствие скверны загрязняет окружающий воздух, отравляя его");
			thorium.GetBuff("ChosenMight").DisplayName.AddTranslation(GameCulture.Russian, "Опора реальности");
			thorium.GetBuff("ChosenMight").Description.AddTranslation(GameCulture.Russian, "Этот мир находится под вашей защитой. Не позволяйте никому забыть этого...");
			thorium.GetBuff("Christmas").DisplayName.AddTranslation(GameCulture.Russian, "Рождество!");
			thorium.GetBuff("Christmas").Description.AddTranslation(GameCulture.Russian, "Ну, считается что сейчас Рождество...");
			thorium.GetBuff("CleanBubble").DisplayName.AddTranslation(GameCulture.Russian, "Освежающий пузырь");
			thorium.GetBuff("CleanBubble").Description.AddTranslation(GameCulture.Russian, "Вдыхание пузыря наполнило ваши легкие дополнительным запасом воздуха!");
			thorium.GetBuff("CobblerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Полированная обувь");
			thorium.GetBuff("CobblerBuff").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения, ускорение бега и высота прыжка повышены");
			thorium.GetBuff("Conflagrate").DisplayName.AddTranslation(GameCulture.Russian, "Служа другим, сгораю сам");
			thorium.GetBuff("Conflagrate").Description.AddTranslation(GameCulture.Russian, "Ваши внутренности горят, но вы наносите больше урона");
			thorium.GetBuff("Corporeal").DisplayName.AddTranslation(GameCulture.Russian, "Материальный");
			thorium.GetBuff("Corporeal").Description.AddTranslation(GameCulture.Russian, "Ваш браслет духа перезаряжается");
			thorium.GetBuff("Corrosion").DisplayName.AddTranslation(GameCulture.Russian, "Коррозия");
			thorium.GetBuff("Corrosion").Description.AddTranslation(GameCulture.Russian, "Урон по вам повышен. Вы периодически теряете здоровье");
			thorium.GetBuff("CounterAttack").DisplayName.AddTranslation(GameCulture.Russian, "Контрудар");
			thorium.GetBuff("CounterAttack").Description.AddTranslation(GameCulture.Russian, "Самое время ударить!");
			thorium.GetBuff("CreativityDrop").DisplayName.AddTranslation(GameCulture.Russian, "Креативность");
			thorium.GetBuff("CreativityDrop").Description.AddTranslation(GameCulture.Russian, "Базовый шанс выпадения вдохновения удвоен");
			thorium.GetBuff("CursedHurtle").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый взмах");
			thorium.GetBuff("CursedHurtle").Description.AddTranslation(GameCulture.Russian, "Вращение выходит из под контроля!");
			thorium.GetBuff("DarknessWithin").DisplayName.AddTranslation(GameCulture.Russian, "Тьма внутри нас");
			thorium.GetBuff("DarknessWithin").Description.AddTranslation(GameCulture.Russian, "Только сильнейшие враги смогут утолить ваш голод...");
			thorium.GetBuff("DashBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кинетический аккумулятор");
			thorium.GetBuff("DashBuff").Description.AddTranslation(GameCulture.Russian, "Позволяет двойным нажатием A или D совершить рывок");
			thorium.GetBuff("DemonBloodExhaust").DisplayName.AddTranslation(GameCulture.Russian, "Кровавая жатва");
			thorium.GetBuff("DemonBloodExhaust").Description.AddTranslation(GameCulture.Russian, "В настоящее время нельзя хранить заряды крови");
			thorium.GetBuff("DemonicDance").DisplayName.AddTranslation(GameCulture.Russian, "Демонический танец");
			thorium.GetBuff("DemonicDance").Description.AddTranslation(GameCulture.Russian, "Магический урон повышен на 20%");
			thorium.GetBuff("DepthBreath").DisplayName.AddTranslation(GameCulture.Russian, "Глубина: Дыхание");
			thorium.GetBuff("DepthBreath").Description.AddTranslation(GameCulture.Russian, "Вы можете дышать под водой");
			thorium.GetBuff("DepthDamage").DisplayName.AddTranslation(GameCulture.Russian, "Глубина: Урон");
			thorium.GetBuff("DepthDamage").Description.AddTranslation(GameCulture.Russian, "Урон повышен на 10%");
			thorium.GetBuff("DepthSpeed").DisplayName.AddTranslation(GameCulture.Russian, "Глубина: Скорость");
			thorium.GetBuff("DepthSpeed").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения повышена на 10%");
			thorium.GetBuff("Destabilized").DisplayName.AddTranslation(GameCulture.Russian, "Дестабилизирован");
			thorium.GetBuff("Destabilized").Description.AddTranslation(GameCulture.Russian, "Ваше существование подобно коту Шредингера");
			thorium.GetBuff("DevilSoul").DisplayName.AddTranslation(GameCulture.Russian, "Хватка дьявола");
			thorium.GetBuff("DevilSoul").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона воскресит вас с 100 единицами здоровья");
			thorium.GetBuff("DevilTired").DisplayName.AddTranslation(GameCulture.Russian, "Дьявол истощен");
			thorium.GetBuff("DevilTired").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона убьет вас...");
			thorium.GetBuff("DRLimit").DisplayName.AddTranslation(GameCulture.Russian, "Лимит сопротивления урону");
			thorium.GetBuff("DRLimit").Description.AddTranslation(GameCulture.Russian, "Эффект Thorium Mod'а ограничен 35% сопротивления урону\nНайдите другие оригинальные/модовые предметы чтобы и дальше повысить сопротивление урону");
			thorium.GetBuff("EarwormBuff").DisplayName.AddTranslation(GameCulture.Russian, "Навязчивая мелодия");
			thorium.GetBuff("EarwormBuff").Description.AddTranslation(GameCulture.Russian, "Длительность эффектов вашего вдохновения повышена на 25%");
			thorium.GetBuff("EmergencyAir").DisplayName.AddTranslation(GameCulture.Russian, "Аварийный воздушный баллон");
			thorium.GetBuff("EmergencyAir").Description.AddTranslation(GameCulture.Russian, "При критическом значении, запас вашего воздуха мгновенно пополнится");
			thorium.GetBuff("Enchanted").DisplayName.AddTranslation(GameCulture.Russian, "Зачарован");
			thorium.GetBuff("Enchanted").Description.AddTranslation(GameCulture.Russian, "Ваши магические способности улучшены");
			thorium.GetBuff("EnchantedArmorBuff").DisplayName.AddTranslation(GameCulture.Russian, "Зачарованная броня");
			thorium.GetBuff("EnchantedArmorBuff").Description.AddTranslation(GameCulture.Russian, "Вы носите комплект магической брони");
			thorium.GetBuff("EnemyFrozen").DisplayName.AddTranslation(GameCulture.Russian, "Замерший");
			thorium.GetBuff("EnemyFrozen").Description.AddTranslation(GameCulture.Russian, "Скорость передвижения этого противника заметно снижена");
			thorium.GetBuff("EscapeRocketBuff").DisplayName.AddTranslation(GameCulture.Russian, "Система аварийного спасения");
			thorium.GetBuff("EscapeRocketBuff").Description.AddTranslation(GameCulture.Russian, "Движки на полную мощность!");
			thorium.GetBuff("ExplodePrevent").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв готовится");
			thorium.GetBuff("ExplodePrevent").Description.AddTranslation(GameCulture.Russian, "Вы еще не можете устроить взрыв...");
			thorium.GetBuff("ExplosionCoating").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение метательного оружия: Взрывы");
			thorium.GetBuff("ExplosionCoating").Description.AddTranslation(GameCulture.Russian, "Метательное оружие имеет шанс вызвать взрыв, что поджигает ближайших врагов");
			thorium.GetBuff("FishRepellentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Репеллент: Рыба");
			thorium.GetBuff("FishRepellentBuff").Description.AddTranslation(GameCulture.Russian, "Большинство рыб становятся дружелюбными");
			thorium.GetBuff("FleshFrenzy").DisplayName.AddTranslation(GameCulture.Russian, "Сумасшествие плоти");
			thorium.GetBuff("FleshFrenzy").Description.AddTranslation(GameCulture.Russian, "Симбиот повысил ваш урон на 10%");
			thorium.GetBuff("Frenzy").DisplayName.AddTranslation(GameCulture.Russian, "Безумие");
			thorium.GetBuff("Frenzy").Description.AddTranslation(GameCulture.Russian, "Скорость ваших атак повышена на 8%");
			thorium.GetBuff("FrostCoating").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение метательного оружия: Глубокая заморозка");
			thorium.GetBuff("FrostCoating").Description.AddTranslation(GameCulture.Russian, "Метательное оружие имеет шанс значительно затруднить движение пораженных врагов");
			thorium.GetBuff("FrostHeart").DisplayName.AddTranslation(GameCulture.Russian, "Оледеневшее сердце");
			thorium.GetBuff("FrostHeart").Description.AddTranslation(GameCulture.Russian, "Здоровье возвращается...");
			thorium.GetBuff("Full").DisplayName.AddTranslation(GameCulture.Russian, "Сытый желудок");
			thorium.GetBuff("Full").Description.AddTranslation(GameCulture.Russian, "Не съем больше ни кусочка!");
			thorium.GetBuff("Gateway").DisplayName.AddTranslation(GameCulture.Russian, "Портал");
			thorium.GetBuff("Gateway").Description.AddTranslation(GameCulture.Russian, "Ваши врата где-то...");
			thorium.GetBuff("GhastlySoul").DisplayName.AddTranslation(GameCulture.Russian, "Призрачная душа");
			thorium.GetBuff("GhastlySoul").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона вернет вас домой");
			thorium.GetBuff("GhastlyTired").DisplayName.AddTranslation(GameCulture.Russian, "Призрачное истощение");
			thorium.GetBuff("GhastlyTired").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона убьет вас...");
			thorium.GetBuff("GorganCoating").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение метательного оружия: Горгоновый сок");
			thorium.GetBuff("GorganCoating").Description.AddTranslation(GameCulture.Russian, "Метательное оружие имеет шанс заковать противника в камень");
			thorium.GetBuff("Gouge").DisplayName.AddTranslation(GameCulture.Russian, "Кровоток");
			thorium.GetBuff("Gouge").Description.AddTranslation(GameCulture.Russian, "Жизнь проносится перед глазами...");
			thorium.GetBuff("Grace").DisplayName.AddTranslation(GameCulture.Russian, "Грация");
			thorium.GetBuff("Grace").Description.AddTranslation(GameCulture.Russian, "Ваша способность двигаться стала куда лучше");
			thorium.GetBuff("GraniteSurge").DisplayName.AddTranslation(GameCulture.Russian, "Гранитный скачок");
			thorium.GetBuff("GraniteSurge").Description.AddTranslation(GameCulture.Russian, "Переполнение энергией наносит вашему телу урон и снижает защиту");
			thorium.GetBuff("GravityDamage").DisplayName.AddTranslation(GameCulture.Russian, "Поправка по гравитации");
			thorium.GetBuff("GravityDamage").Description.AddTranslation(GameCulture.Russian, "Урон в дальнем бою повышен на 15%");
			thorium.GetBuff("Grimshadow").DisplayName.AddTranslation(GameCulture.Russian, "Фантомное присутствие");
			thorium.GetBuff("Grimshadow").Description.AddTranslation(GameCulture.Russian, "Что-то таится в тьме...");
			thorium.GetBuff("Grimshadow2").DisplayName.AddTranslation(GameCulture.Russian, "Фантомное присутствие");
			thorium.GetBuff("Grimshadow2").Description.AddTranslation(GameCulture.Russian, "Что-то таится в тьме...");
			thorium.GetBuff("Grimshadow3").DisplayName.AddTranslation(GameCulture.Russian, "Фантомное присутствие");
			thorium.GetBuff("Grimshadow3").Description.AddTranslation(GameCulture.Russian, "По воде идет рябь...");
			thorium.GetBuff("Halloween").DisplayName.AddTranslation(GameCulture.Russian, "Хэллоуин!");
			thorium.GetBuff("Halloween").Description.AddTranslation(GameCulture.Russian, "Ну, считается что сейчас Хэллоуин...");
			thorium.GetBuff("Hallucination").DisplayName.AddTranslation(GameCulture.Russian, "Галюцинации");
			thorium.GetBuff("Hallucination").Description.AddTranslation(GameCulture.Russian, "Что-то не так...");
			thorium.GetBuff("Hexed").DisplayName.AddTranslation(GameCulture.Russian, "Заколдован");
			thorium.GetBuff("Hexed").Description.AddTranslation(GameCulture.Russian, "Вы превратились в лягушку!");
			thorium.GetBuff("Honey").DisplayName.AddTranslation(GameCulture.Russian, "Мед");
			thorium.GetBuff("Honey").Description.AddTranslation(GameCulture.Russian, "Пчелы просто ОБОЖАЮТ мед...");
			thorium.GetBuff("HydrationBuff").DisplayName.AddTranslation(GameCulture.Russian, "Гидратация");
			thorium.GetBuff("HydrationBuff").Description.AddTranslation(GameCulture.Russian, "Ваше истощение быстрее проходит. Очки техники восстанавливаются быстрее");
			thorium.GetBuff("IlluminatedNPC").DisplayName.AddTranslation(GameCulture.Russian, "Подсвеченный");
			thorium.GetBuff("IlluminatedNPC").Description.AddTranslation(GameCulture.Russian, "Этот враг горит приятным светом");
			thorium.GetBuff("IncandescentBurn").DisplayName.AddTranslation(GameCulture.Russian, "Раскаленное пламя");
			thorium.GetBuff("IncandescentBurn").Description.AddTranslation(GameCulture.Russian, "Потеря здоровья");
			thorium.GetBuff("Insanity").DisplayName.AddTranslation(GameCulture.Russian, "Безумие");
			thorium.GetBuff("Insanity").Description.AddTranslation(GameCulture.Russian, "Вы наносите урон ближайшим противникам");
			thorium.GetBuff("InsectRepellentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Репеллент: Насекомые");
			thorium.GetBuff("InsectRepellentBuff").Description.AddTranslation(GameCulture.Russian, "Большинство насекомых становятся дружелюбными");
			thorium.GetBuff("InspirationReach").DisplayName.AddTranslation(GameCulture.Russian, "Пламенная речь");
			thorium.GetBuff("InspirationReach").Description.AddTranslation(GameCulture.Russian, "Радиус подбора нот вдохновения повышен");
			thorium.GetBuff("Karma").DisplayName.AddTranslation(GameCulture.Russian, "Карма");
			thorium.GetBuff("Karma").Description.AddTranslation(GameCulture.Russian, "Тебя слили!");
			thorium.GetBuff("LegacyBurn").DisplayName.AddTranslation(GameCulture.Russian, "Огонь наследия");
			thorium.GetBuff("LegacyBurn").Description.AddTranslation(GameCulture.Russian, "Если этот враг умрет, будет высвобождена вредящая энергия");
			thorium.GetBuff("LichActive").DisplayName.AddTranslation(GameCulture.Russian, "Полный крестраж");
			thorium.GetBuff("LichActive").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона воскресит вас с 20 единицами здоровья");
			thorium.GetBuff("LichNotActive").DisplayName.AddTranslation(GameCulture.Russian, "Крестраж без души");
			thorium.GetBuff("LichNotActive").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона убьет вас...");
			thorium.GetBuff("LifeTransfusion").DisplayName.AddTranslation(GameCulture.Russian, "Жизненная трансфузия");
			thorium.GetBuff("LifeTransfusion").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья отключена");
			thorium.GetBuff("LifeWaterRegen").DisplayName.AddTranslation(GameCulture.Russian, "Дар живительной воды");
			thorium.GetBuff("LifeWaterRegen").Description.AddTranslation(GameCulture.Russian, "Максимальный запас здоровья и регенерация увеличены");
			thorium.GetBuff("LightCurse").DisplayName.AddTranslation(GameCulture.Russian, "Легкое проклятие");
			thorium.GetBuff("LightCurse").Description.AddTranslation(GameCulture.Russian, "Этого врага медленно уничтожает чистая тьма");
			thorium.GetBuff("LimbSnatch").DisplayName.AddTranslation(GameCulture.Russian, "Крепкая хватка");
			thorium.GetBuff("LimbSnatch").Description.AddTranslation(GameCulture.Russian, "Оно на твоем лице! Аагх!");
			thorium.GetBuff("Liquefied").DisplayName.AddTranslation(GameCulture.Russian, "Сжиженный");
			thorium.GetBuff("Liquefied").Description.AddTranslation(GameCulture.Russian, "Защита и скорость передвижения уменьшены");
			thorium.GetBuff("MagickStaffDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Стихийный распад");
			thorium.GetBuff("MagickStaffDebuff").Description.AddTranslation(GameCulture.Russian, "Расколот низшими элементами Террарии");
			thorium.GetBuff("Magma").DisplayName.AddTranslation(GameCulture.Russian, "Магма");
			thorium.GetBuff("Magma").Description.AddTranslation(GameCulture.Russian, "Вы получаете дополнительный урон от огненных эффектов");
			thorium.GetBuff("MajorEnchanted").DisplayName.AddTranslation(GameCulture.Russian, "Перечарован");
			thorium.GetBuff("MajorEnchanted").Description.AddTranslation(GameCulture.Russian, "Ваши магические способности значительно улучшены");
			thorium.GetBuff("Melting").DisplayName.AddTranslation(GameCulture.Russian, "Распад");
			thorium.GetBuff("Melting").Description.AddTranslation(GameCulture.Russian, "Вы быстро теряете здоровье");
			thorium.GetBuff("MetamorphosisBad").DisplayName.AddTranslation(GameCulture.Russian, "Метаморфоза");
			thorium.GetBuff("MetamorphosisBad").Description.AddTranslation(GameCulture.Russian, "Ваша сила достигает абсолютного пика!");
			thorium.GetBuff("MetamorphosisGood").DisplayName.AddTranslation(GameCulture.Russian, "Освобожденный");
			thorium.GetBuff("MetamorphosisGood").Description.AddTranslation(GameCulture.Russian, "Скорость атаки и урон повышены на 30%");
			thorium.GetBuff("MetamorphosisRealBad").DisplayName.AddTranslation(GameCulture.Russian, "Восстановление");
			thorium.GetBuff("MetamorphosisRealBad").Description.AddTranslation(GameCulture.Russian, "Ваше тело не привыкло к этой форме...");
			thorium.GetBuff("MidnightOil").DisplayName.AddTranslation(GameCulture.Russian, "Сумеречное масло");
			thorium.GetBuff("MidnightOil").Description.AddTranslation(GameCulture.Russian, "Враги не заинтересованы в вас");
			thorium.GetBuff("Mycelium").DisplayName.AddTranslation(GameCulture.Russian, "Грибной рост");
			thorium.GetBuff("Mycelium").Description.AddTranslation(GameCulture.Russian, "Эта цель заражена мицелием");
			thorium.GetBuff("MyceliumVeins").DisplayName.AddTranslation(GameCulture.Russian, "Грибные жилы");
			thorium.GetBuff("MyceliumVeins").Description.AddTranslation(GameCulture.Russian, "Скорость метания повышена на 10%");
			thorium.GetBuff("Napalm").DisplayName.AddTranslation(GameCulture.Russian, "Напалм");
			thorium.GetBuff("Napalm").Description.AddTranslation(GameCulture.Russian, "Жар нетерпим...");
			thorium.GetBuff("Nightshade").DisplayName.AddTranslation(GameCulture.Russian, "Паслен");
			thorium.GetBuff("Nightshade").Description.AddTranslation(GameCulture.Russian, "Вы получаете дополнительный урон от отравляющих эффектов");
			thorium.GetBuff("NinjaBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ловкость рук");
			thorium.GetBuff("NinjaBuff").Description.AddTranslation(GameCulture.Russian, "Скорость метания, скорость передвижения и шанс критического удара повышены");
			thorium.GetBuff("OceansBuffer").DisplayName.AddTranslation(GameCulture.Russian, "Океанический буфер");
			thorium.GetBuff("OceansBuffer").Description.AddTranslation(GameCulture.Russian, "Превращает весь урон в исцеление");
			thorium.GetBuff("OceansBufferExhaust").DisplayName.AddTranslation(GameCulture.Russian, "Истощение: Океанический буфер");
			thorium.GetBuff("OceansBufferExhaust").Description.AddTranslation(GameCulture.Russian, "Ваш океанический буфер в настоящее время перезаряжается");
			thorium.GetBuff("OmniVision").DisplayName.AddTranslation(GameCulture.Russian, "Абсолютное зрение");
			thorium.GetBuff("OmniVision").Description.AddTranslation(GameCulture.Russian, "Этот враг находится под взглядом ассасина");
			thorium.GetBuff("Oozed").DisplayName.AddTranslation(GameCulture.Russian, "Просочившись");
			thorium.GetBuff("Oozed").Description.AddTranslation(GameCulture.Russian, "Движение значительно уменьшено");
			thorium.GetBuff("Overcharge").DisplayName.AddTranslation(GameCulture.Russian, "Нестабильность");
			thorium.GetBuff("Overcharge").Description.AddTranslation(GameCulture.Russian, "Магический урон и шанс критического удара сильно повышены. Ваше тело медленно испаряется");
			thorium.GetBuff("OverGrowth").DisplayName.AddTranslation(GameCulture.Russian, "Беспорядочный рост");
			thorium.GetBuff("OverGrowth").Description.AddTranslation(GameCulture.Russian, "Ваша регенерация и скорость регенерации здоровья значительно повышены");
			thorium.GetBuff("Paralyzed").DisplayName.AddTranslation(GameCulture.Russian, "Парализован");
			thorium.GetBuff("Paralyzed").Description.AddTranslation(GameCulture.Russian, "Враг не может двигаться!");
			thorium.GetBuff("ParryStance").DisplayName.AddTranslation(GameCulture.Russian, "Стойка для парирования");
			thorium.GetBuff("ParryStance").Description.AddTranslation(GameCulture.Russian, "Получаемый урон снижен на 10%");
			thorium.GetBuff("Petrify").DisplayName.AddTranslation(GameCulture.Russian, "Окаменение");
			thorium.GetBuff("Petrify").Description.AddTranslation(GameCulture.Russian, "Этот враг окаменел!");
			thorium.GetBuff("PoisonHeart").DisplayName.AddTranslation(GameCulture.Russian, "Порченные сердца");
			thorium.GetBuff("PoisonHeart").Description.AddTranslation(GameCulture.Russian, "Выпадающие сердца лечат лишь на половину и отравляют вас");
			thorium.GetBuff("Sanguine").DisplayName.AddTranslation(GameCulture.Russian, "Жизнерадостный");
			thorium.GetBuff("Sanguine").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышено на 10%. Восстановление здоровья значительно увеличено");
			thorium.GetBuff("SchmelzeDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Расплавленная ярость");
			thorium.GetBuff("SchmelzeDebuff").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			thorium.GetBuff("SeasonsGreeting").DisplayName.AddTranslation(GameCulture.Russian, "Приятная атмосфера");
			thorium.GetBuff("SeasonsGreeting").Description.AddTranslation(GameCulture.Russian, "Регенерация здоровья, маны и вдохновения повышены");
			thorium.GetBuff("Shackled").DisplayName.AddTranslation(GameCulture.Russian, "Скованный");
			thorium.GetBuff("Shackled").Description.AddTranslation(GameCulture.Russian, "Вы привязаны к ближайшей 'королевской дочке'");
			thorium.GetBuff("SilverTongue").DisplayName.AddTranslation(GameCulture.Russian, "Серебряный язык");
			thorium.GetBuff("SilverTongue").Description.AddTranslation(GameCulture.Russian, "'Используйте этот серебряный язык, чтобы обмануть владельцев магазинов!'");
			thorium.GetBuff("Singed").DisplayName.AddTranslation(GameCulture.Russian, "Опаленный");
			thorium.GetBuff("Singed").Description.AddTranslation(GameCulture.Russian, "Неприятный ожог...");
			thorium.GetBuff("SkeletonRepellentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Репеллент: Скелеты");
			thorium.GetBuff("SkeletonRepellentBuff").Description.AddTranslation(GameCulture.Russian, "Большинство скелетов становятся дружелюбными");
			thorium.GetBuff("SlagfuryStandBuffTired").DisplayName.AddTranslation(GameCulture.Russian, "Литая ярость");
			thorium.GetBuff("SlagfuryStandBuffTired").Description.AddTranslation(GameCulture.Russian, "Сила шлакового яростня восстанавливается...");
			thorium.GetBuff("SnakeBite").DisplayName.AddTranslation(GameCulture.Russian, "Змеиный укус");
			thorium.GetBuff("SnakeBite").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			thorium.GetBuff("SoulHarvest").DisplayName.AddTranslation(GameCulture.Russian, "Жатва душ");
			thorium.GetBuff("SoulHarvest").Description.AddTranslation(GameCulture.Russian, "Ваше скорость передвижения и скорость метания значительно улучшены");
			thorium.GetBuff("SporeCoating").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение метательного оружия: Споры");
			thorium.GetBuff("SporeCoating").Description.AddTranslation(GameCulture.Russian, "Метательное оружие имеет шанс заразить врагов мицелием");
			thorium.GetBuff("Spored").DisplayName.AddTranslation(GameCulture.Russian, "Опылен");
			thorium.GetBuff("Spored").Description.AddTranslation(GameCulture.Russian, "Если этот противник умрет, из него высвободится больше спор");
			thorium.GetBuff("Staggered").DisplayName.AddTranslation(GameCulture.Russian, "Ошеломление");
			thorium.GetBuff("Staggered").Description.AddTranslation(GameCulture.Russian, "У тебя слишком кружится голова, чтобы прыгать правильно");
			thorium.GetBuff("Stunned").DisplayName.AddTranslation(GameCulture.Russian, "Оглушен");
			thorium.GetBuff("Stunned").Description.AddTranslation(GameCulture.Russian, "Этот враг оглушен и не может двигаться");
			thorium.GetBuff("Sunder").DisplayName.AddTranslation(GameCulture.Russian, "Расколотый");
			thorium.GetBuff("Sunder").Description.AddTranslation(GameCulture.Russian, "Защита значительно уменьшена");
			thorium.GetBuff("TastyJelly").DisplayName.AddTranslation(GameCulture.Russian, "Вкусное желе");
			thorium.GetBuff("TastyJelly").Description.AddTranslation(GameCulture.Russian, "Восстановление здоровья значительно повышено");
			thorium.GetBuff("TerrariumMix").DisplayName.AddTranslation(GameCulture.Russian, "Ответный удар Террарии");
			thorium.GetBuff("TerrariumMix").Description.AddTranslation(GameCulture.Russian, "Расколот элементами Террарии");
			thorium.GetBuff("TerrariumRegen").DisplayName.AddTranslation(GameCulture.Russian, "Поцелуй Террарии");
			thorium.GetBuff("TerrariumRegen").Description.AddTranslation(GameCulture.Russian, "Силы Террарии оберегают вас");
			thorium.GetBuff("TouchOfOmnicide").DisplayName.AddTranslation(GameCulture.Russian, "Касание Омницида");
			thorium.GetBuff("TouchOfOmnicide").Description.AddTranslation(GameCulture.Russian, "Остановите конец света, пока не стало слишком поздно!");
			thorium.GetBuff("ToxicCoating").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение метательного оружия: Токсины");
			thorium.GetBuff("ToxicCoating").Description.AddTranslation(GameCulture.Russian, "Метательное оружие имеет шанс отравить врагов");
			thorium.GetBuff("TrueStrike").DisplayName.AddTranslation(GameCulture.Russian, "Истинный удар");
			thorium.GetBuff("TrueStrike").Description.AddTranslation(GameCulture.Russian, "Ваше метательное оружие имеет 100% шанс нанести критический удар");
			thorium.GetBuff("TrueStrikeTired").DisplayName.AddTranslation(GameCulture.Russian, "Критически истощен");
			thorium.GetBuff("TrueStrikeTired").Description.AddTranslation(GameCulture.Russian, "Ваш метательный урон уменьшен на 10%");
			thorium.GetBuff("Tuned").DisplayName.AddTranslation(GameCulture.Russian, "Гармонизирован");
			thorium.GetBuff("Tuned").Description.AddTranslation(GameCulture.Russian, "Вы получаете на 10% больше урона");
			thorium.GetBuff("ViscountDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие вампира");
			thorium.GetBuff("ViscountDebuff").Description.AddTranslation(GameCulture.Russian, "Вас насильно превратили в слабую летучую мышь!");
			thorium.GetBuff("WidowsKiss").DisplayName.AddTranslation(GameCulture.Russian, "Поцелуй вдовы");
			thorium.GetBuff("WidowsKiss").Description.AddTranslation(GameCulture.Russian, "В ваше тело выпущен смертельный токсин!");
			thorium.GetBuff("WindBurst").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв ветра");
			thorium.GetBuff("WindBurst").Description.AddTranslation(GameCulture.Russian, "Скорость ваших инструментов повышена на 15%");
			thorium.GetBuff("Wither").DisplayName.AddTranslation(GameCulture.Russian, "Иссушение");
			thorium.GetBuff("Wither").Description.AddTranslation(GameCulture.Russian, "ИССУШИСЬ!!!");
			thorium.GetBuff("ZombieRepellentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Репеллент: Зомби");
			thorium.GetBuff("ZombieRepellentBuff").Description.AddTranslation(GameCulture.Russian, "Большинство зомби становятся дружелюбными");
			thorium.GetBuff("ShockAbsorbtion").DisplayName.AddTranslation(GameCulture.Russian, "Амортизация");
			thorium.GetBuff("ShockAbsorbtion").Description.AddTranslation(GameCulture.Russian, "Весь урон повышен на 15%");
			thorium.GetBuff("Soloist").DisplayName.AddTranslation(GameCulture.Russian, "Бесконечное творчество");
			thorium.GetBuff("Soloist").Description.AddTranslation(GameCulture.Russian, "Ваш музыкальный талант не имеет себе равных");
			thorium.GetBuff("SoloistDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Блокировка креативности");
			thorium.GetBuff("SoloistDebuff").Description.AddTranslation(GameCulture.Russian, "Не могу дать волю своему творчеству");
			thorium.GetBuff("AegisAura").DisplayName.AddTranslation(GameCulture.Russian, "Защитная энергия");
			thorium.GetBuff("AegisAura").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышено на 5%");
			thorium.GetBuff("AloeJuice").DisplayName.AddTranslation(GameCulture.Russian, "Энергия алоэ");
			thorium.GetBuff("AloeJuice").Description.AddTranslation(GameCulture.Russian, "Медленное восстановление здоровья");
			thorium.GetBuff("AngelBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленький Херувим");
			thorium.GetBuff("AngelBuff").Description.AddTranslation(GameCulture.Russian, "От вашего плеча до линии фланга!");
			thorium.GetBuff("Awake").DisplayName.AddTranslation(GameCulture.Russian, "Пробужденный");
			thorium.GetBuff("Awake").Description.AddTranslation(GameCulture.Russian, "Не могу войти в сон...");
			thorium.GetBuff("BloodBoost").DisplayName.AddTranslation(GameCulture.Russian, "Кровавое разрушение");
			thorium.GetBuff("BloodBoost").Description.AddTranslation(GameCulture.Russian, "Союзники усиливают ваши эффекты при попадании");
			thorium.GetBuff("BloomBoost").DisplayName.AddTranslation(GameCulture.Russian, "Форсированное цветение");
			thorium.GetBuff("BloomBoost").Description.AddTranslation(GameCulture.Russian, "Вы восстанавливаете здоровье и имеете повышенную защиту");
			thorium.GetBuff("BoneArmor").DisplayName.AddTranslation(GameCulture.Russian, "Костяная броня");
			thorium.GetBuff("BoneArmor").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышено на 15%");
			thorium.GetBuff("BulwarkBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пузырный бастион");
			thorium.GetBuff("BulwarkBuff").Description.AddTranslation(GameCulture.Russian, "Следующая атака по вам нанесет 0 урона");
			thorium.GetBuff("CelestialDamage").DisplayName.AddTranslation(GameCulture.Russian, "Лучезарная звезда");
			thorium.GetBuff("CelestialDamage").Description.AddTranslation(GameCulture.Russian, "Лучезарный урон повышен на 25%");
			thorium.GetBuff("CelestialHeal").DisplayName.AddTranslation(GameCulture.Russian, "Исцеляющая звезда");
			thorium.GetBuff("CelestialHeal").Description.AddTranslation(GameCulture.Russian, "Целительные заклинания исцеляют дополнительные 2 очка здоровья");
			thorium.GetBuff("ConsumingShadow").DisplayName.AddTranslation(GameCulture.Russian, "Поглощая тени");
			thorium.GetBuff("ConsumingShadow").Description.AddTranslation(GameCulture.Russian, "Получение дополнительного урона от теневых дебаффов");
			thorium.GetBuff("Cured").DisplayName.AddTranslation(GameCulture.Russian, "Исцеленный");
			thorium.GetBuff("Cured").Description.AddTranslation(GameCulture.Russian, "Большинство наносящих урон эффектов были развеяны");
			thorium.GetBuff("DarkContagion").DisplayName.AddTranslation(GameCulture.Russian, "Темная инфекция");
			thorium.GetBuff("DarkContagion").Description.AddTranslation(GameCulture.Russian, "Вы поражены заразным темным проклятием");
			thorium.GetBuff("DevilBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленький Дьявол");
			thorium.GetBuff("DevilBuff").Description.AddTranslation(GameCulture.Russian, "От вашего плеча до линии фронта!");
			thorium.GetBuff("DistortedTime").DisplayName.AddTranslation(GameCulture.Russian, "Искаженная реальность");
			thorium.GetBuff("DistortedTime").Description.AddTranslation(GameCulture.Russian, "Поток времени находится под сильным давлением");
			thorium.GetBuff("DistortedTimeBoost").DisplayName.AddTranslation(GameCulture.Russian, "Искаженное время");
			thorium.GetBuff("DistortedTimeBoost").Description.AddTranslation(GameCulture.Russian, "Поток времени находится под сильным давлением");
			thorium.GetBuff("DistortedTimeEnemy").DisplayName.AddTranslation(GameCulture.Russian, "Искаженное время");
			thorium.GetBuff("DistortedTimeEnemy").Description.AddTranslation(GameCulture.Russian, "Время замедляет этого врага");
			thorium.GetBuff("DragonHeart").DisplayName.AddTranslation(GameCulture.Russian, "Сердце дракона");
			thorium.GetBuff("DragonHeart").Description.AddTranslation(GameCulture.Russian, "Урон повышен на 15%");
			thorium.GetBuff("DreamBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сновидец");
			thorium.GetBuff("DreamBuff").Description.AddTranslation(GameCulture.Russian, "Невосприимчив к почти всем повреждениям");
			thorium.GetBuff("DreamCatcherBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ловец снов");
			thorium.GetBuff("DreamCatcherBuff").Description.AddTranslation(GameCulture.Russian, "Получение смертельного урона восстановит ваш максимальный запас здоровья");
			thorium.GetBuff("DreamCatcherDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Пойманный сон");
			thorium.GetBuff("DreamCatcherDebuff").Description.AddTranslation(GameCulture.Russian, "Во сне вы не можете возродиться");
			thorium.GetBuff("EffigyRegen").DisplayName.AddTranslation(GameCulture.Russian, "Чучело");
			thorium.GetBuff("EffigyRegen").Description.AddTranslation(GameCulture.Russian, "Враги, пораженные темной энергией, исцеляют вас");
			thorium.GetBuff("EquilibriumHeal").DisplayName.AddTranslation(GameCulture.Russian, "Уравновешенность");
			thorium.GetBuff("EquilibriumHeal").Description.AddTranslation(GameCulture.Russian, "Восстановление здоровья");
			thorium.GetBuff("Gaurdian").DisplayName.AddTranslation(GameCulture.Russian, "Ангел-хранитель");
			thorium.GetBuff("Gaurdian").Description.AddTranslation(GameCulture.Russian, "Спиритуалист защищает вас от смертельного урона");
			thorium.GetBuff("GaurdianBad").DisplayName.AddTranslation(GameCulture.Russian, "Истощение Хранителя");
			thorium.GetBuff("GaurdianBad").Description.AddTranslation(GameCulture.Russian, "Вы не можете принять дар спиритуалиста");
			thorium.GetBuff("GuardianDamage").DisplayName.AddTranslation(GameCulture.Russian, "Хранитель: Месть");
			thorium.GetBuff("GuardianDamage").Description.AddTranslation(GameCulture.Russian, "Урон повышен на 15%");
			thorium.GetBuff("GuardianDefense").DisplayName.AddTranslation(GameCulture.Russian, "Хранитель: Защита");
			thorium.GetBuff("GuardianDefense").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышено на 30%");
			thorium.GetBuff("GuardianRegen").DisplayName.AddTranslation(GameCulture.Russian, "Хранитель: Восстановление");
			thorium.GetBuff("GuardianRegen").Description.AddTranslation(GameCulture.Russian, "Восстановление здоровья значительно повышено");
			thorium.GetBuff("HealerDefenseAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура: Сопротивление урону");
			thorium.GetBuff("HealerDefenseAura").Description.AddTranslation(GameCulture.Russian, "Ваш союзник увеличивает ваше сопротивление урону на 12%");
			thorium.GetBuff("HealerPotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Крепкое зелье");
			thorium.GetBuff("HealerPotionBuff").Description.AddTranslation(GameCulture.Russian, "Получение 1 дополнительного исцеления");
			thorium.GetBuff("HealerRegenAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура: Восстановление здоровья");
			thorium.GetBuff("HealerRegenAura").Description.AddTranslation(GameCulture.Russian, "Ваш союзник способствует восстановлению вашего здоровья");
			thorium.GetBuff("HealingLoss").DisplayName.AddTranslation(GameCulture.Russian, "Вне связи");
			thorium.GetBuff("HealingLoss").Description.AddTranslation(GameCulture.Russian, "Ваш бонус исцеления эффективен только на 33%");
			thorium.GetBuff("HealingMastery").DisplayName.AddTranslation(GameCulture.Russian, "Мастерство исцеления");
			thorium.GetBuff("HealingMastery").Description.AddTranslation(GameCulture.Russian, "Восстановление маны, бонус исцеления и скорость исцеления повышены");
			thorium.GetBuff("HolyAuraTired").DisplayName.AddTranslation(GameCulture.Russian, "Святая аура");
			thorium.GetBuff("HolyAuraTired").Description.AddTranslation(GameCulture.Russian, "Защитная аура окружает ваш курсор");
			thorium.GetBuff("HolyBonus").DisplayName.AddTranslation(GameCulture.Russian, "Святая сила");
			thorium.GetBuff("HolyBonus").Description.AddTranslation(GameCulture.Russian, "Целительные заклинания исцеляют дополнительное здоровье");
			thorium.GetBuff("HolyDefense").DisplayName.AddTranslation(GameCulture.Russian, "Святая защита");
			thorium.GetBuff("HolyDefense").Description.AddTranslation(GameCulture.Russian, "Ваша защита увеличена на 20");
			thorium.GetBuff("HolyGlare").DisplayName.AddTranslation(GameCulture.Russian, "Святой свет");
			thorium.GetBuff("HolyGlare").Description.AddTranslation(GameCulture.Russian, "Да очистит святой свет нечистого!");
			thorium.GetBuff("HolyShine").DisplayName.AddTranslation(GameCulture.Russian, "Аура: Святое сияние");
			thorium.GetBuff("HolyShine").Description.AddTranslation(GameCulture.Russian, "Ваши атакующие и защитные характеристики значительно повышены");
			thorium.GetBuff("KarmicConvergance").DisplayName.AddTranslation(GameCulture.Russian, "Кармическая конвергенция");
			thorium.GetBuff("KarmicConvergance").Description.AddTranslation(GameCulture.Russian, "Лучезарный урон повышен");
			thorium.GetBuff("LifeSpiritBuff").DisplayName.AddTranslation(GameCulture.Russian, "Дух жизни");
			thorium.GetBuff("LifeSpiritBuff").Description.AddTranslation(GameCulture.Russian, "Слишком ярок, чтобы смотреть прямо");
			thorium.GetBuff("MistBulwark").DisplayName.AddTranslation(GameCulture.Russian, "Напитанный туманом бастион");
			thorium.GetBuff("MistBulwark").Description.AddTranslation(GameCulture.Russian, "Максимальный запас здоровья повышен на 50");
			thorium.GetBuff("Mortality").DisplayName.AddTranslation(GameCulture.Russian, "Смертность");
			thorium.GetBuff("Mortality").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону, урон и скорость передвижения уменьшены");
			thorium.GetBuff("NullZoneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Нуль-зона");
			thorium.GetBuff("NullZoneBuff").Description.AddTranslation(GameCulture.Russian, "Получаемый снарядами урон снижен на 20%");
			thorium.GetBuff("Ointment").DisplayName.AddTranslation(GameCulture.Russian, "Перевязанный");
			thorium.GetBuff("Ointment").Description.AddTranslation(GameCulture.Russian, "Восстановление здоровья");
			thorium.GetBuff("PheonixBuff").DisplayName.AddTranslation(GameCulture.Russian, "Феникс");
			thorium.GetBuff("PheonixBuff").Description.AddTranslation(GameCulture.Russian, "Величественное существо наблюдает за вами и вашими союзниками");
			thorium.GetBuff("PurifiedRegen").DisplayName.AddTranslation(GameCulture.Russian, "Чистая регенерация");
			thorium.GetBuff("PurifiedRegen").Description.AddTranslation(GameCulture.Russian, "Восстановление здоровья");
			thorium.GetBuff("QuickRecovery").DisplayName.AddTranslation(GameCulture.Russian, "Быстрое восстановление");
			thorium.GetBuff("QuickRecovery").Description.AddTranslation(GameCulture.Russian, "Скорость восстановления здоровья повышена на 25%");
			thorium.GetBuff("RadiantBoost").DisplayName.AddTranslation(GameCulture.Russian, "Люминесцентная энергия");
			thorium.GetBuff("RadiantBoost").Description.AddTranslation(GameCulture.Russian, "Лучезарный урон повышен на 10%");
			thorium.GetBuff("Rebound").DisplayName.AddTranslation(GameCulture.Russian, "Отдача");
			thorium.GetBuff("Rebound").Description.AddTranslation(GameCulture.Russian, "Время пытается вернуть свой ход");
			thorium.GetBuff("RoseWind").DisplayName.AddTranslation(GameCulture.Russian, "Розовый пузырь");
			thorium.GetBuff("RoseWind").Description.AddTranslation(GameCulture.Russian, "Таинственная сила защищает и лечит вас");
			thorium.GetBuff("RoseWindBad").DisplayName.AddTranslation(GameCulture.Russian, "Лопнувший пузырь");
			thorium.GetBuff("RoseWindBad").Description.AddTranslation(GameCulture.Russian, "Ваш пузырь перезаряжается...");
			thorium.GetBuff("Savior").DisplayName.AddTranslation(GameCulture.Russian, "Освобожденный");
			thorium.GetBuff("Savior").Description.AddTranslation(GameCulture.Russian, "Ваша базовая скорость передвижения повышена. Вы не получаете урон");
			thorium.GetBuff("SerpentsBubble").DisplayName.AddTranslation(GameCulture.Russian, "Змеиный пузырь");
			thorium.GetBuff("SerpentsBubble").Description.AddTranslation(GameCulture.Russian, "Вы получаете 2 дополнительных очка здоровья от исцелений. Сопротивление урону повышено на 10%");
			thorium.GetBuff("ShieldDroneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Защитный дрон");
			thorium.GetBuff("ShieldDroneBuff").Description.AddTranslation(GameCulture.Russian, "От вашего плеча до краев линий фронта!");
			thorium.GetBuff("SmiteFire").DisplayName.AddTranslation(GameCulture.Russian, "Карающее пламя");
			thorium.GetBuff("SmiteFire").Description.AddTranslation(GameCulture.Russian, "Вам наносится урон!");
			thorium.GetBuff("SoulEssence").DisplayName.AddTranslation(GameCulture.Russian, "Сущность души");
			thorium.GetBuff("SpeedBurst").DisplayName.AddTranslation(GameCulture.Russian, "Взрывное ускорение");
			thorium.GetBuff("SpeedBurst").Description.AddTranslation(GameCulture.Russian, "Исцеление союзника повышает вашу скорость передвижения и скорость лечения");
			thorium.GetBuff("SpiritualConnection").DisplayName.AddTranslation(GameCulture.Russian, "Духовная связь");
			thorium.GetBuff("SpiritualConnection").Description.AddTranslation(GameCulture.Russian, "Ваши лечебные заклинания исцеляют дополнительное здоровье");
			thorium.GetBuff("Stabilized").DisplayName.AddTranslation(GameCulture.Russian, "Стабилизированный");
			thorium.GetBuff("Stabilized").Description.AddTranslation(GameCulture.Russian, "Не попадет под действие цепного целительного эффекта");
			thorium.GetBuff("TangyHeal").DisplayName.AddTranslation(GameCulture.Russian, "Резкое исцеление");
			thorium.GetBuff("TangyHeal").Description.AddTranslation(GameCulture.Russian, "Скорость восстановления здоровья повышена");
			thorium.GetBuff("TheDream").DisplayName.AddTranslation(GameCulture.Russian, "Мечта");
			thorium.GetBuff("TheDream").Description.AddTranslation(GameCulture.Russian, "Мир - это осознанная реальность...");
			thorium.GetBuff("TwilightBoost").DisplayName.AddTranslation(GameCulture.Russian, "Сумеречное ускорение");
			thorium.GetBuff("TwilightBoost").Description.AddTranslation(GameCulture.Russian, "Союзник усиливает ваши эффекты при попадании");
			thorium.GetBuff("VoidForm").DisplayName.AddTranslation(GameCulture.Russian, "Поглощая шепот");
			thorium.GetBuff("VoidForm").Description.AddTranslation(GameCulture.Russian, "Власть приходит за плату");
			thorium.GetBuff("BallBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кибернетическая сфера");
			thorium.GetBuff("BallBuff").Description.AddTranslation(GameCulture.Russian, "Сферическая!");
			thorium.GetBuff("BatBuffGood").DisplayName.AddTranslation(GameCulture.Russian, "Подарок вампира");
			thorium.GetBuff("BatBuffGood").Description.AddTranslation(GameCulture.Russian, "Вы превратились в летучую мышь!");
			thorium.GetBuff("BathtubCartBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ванна-мобиль");
			thorium.GetBuff("BathtubCartBuff").Description.AddTranslation(GameCulture.Russian, "Мойтесь даже на ходу!");
			thorium.GetBuff("BeetleTFBuff").DisplayName.AddTranslation(GameCulture.Russian, "Жук");
			thorium.GetBuff("BeetleTFBuff").Description.AddTranslation(GameCulture.Russian, "Вы превратились в жука, способного к полету");
			thorium.GetBuff("BroomMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Волшебная метла");
			thorium.GetBuff("BroomMountBuff").Description.AddTranslation(GameCulture.Russian, "Знак любви 'Мастер-спарк'");
			thorium.GetBuff("CarMount").DisplayName.AddTranslation(GameCulture.Russian, "Пустотная колесница");
			thorium.GetBuff("CarMount").Description.AddTranslation(GameCulture.Russian, "Кто знал, что это можно приручить?");
			thorium.GetBuff("DragonMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Злой дракон");
			thorium.GetBuff("DragonMountBuff").Description.AddTranslation(GameCulture.Russian, "Попробуйте игнорировать запах дыма...");
			thorium.GetBuff("EnemyCrabBuff").DisplayName.AddTranslation(GameCulture.Russian, "Крабик");
			thorium.GetBuff("EnemyCrabBuff").Description.AddTranslation(GameCulture.Russian, "Трепещите, морские обитатели!");
			thorium.GetBuff("FrogBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лягушка");
			thorium.GetBuff("FrogBuff").Description.AddTranslation(GameCulture.Russian, "Вы превратились в прыгучую лягушку");
			thorium.GetBuff("GoldfishTFBuff").DisplayName.AddTranslation(GameCulture.Russian, "Золотая рыбка");
			thorium.GetBuff("GoldfishTFBuff").Description.AddTranslation(GameCulture.Russian, "Вы приобрели жабры и отличный вкус");
			thorium.GetBuff("InfernalHoundBuff").DisplayName.AddTranslation(GameCulture.Russian, "Инфернальная гончая");
			thorium.GetBuff("InfernalHoundBuff").Description.AddTranslation(GameCulture.Russian, "Беги, подгоняемый яростью ада!");
			thorium.GetBuff("MaggotTFBuff").DisplayName.AddTranslation(GameCulture.Russian, "Литая личинка");
			thorium.GetBuff("MaggotTFBuff").Description.AddTranslation(GameCulture.Russian, "Вы превратились в маленького огненного червя");
			thorium.GetBuff("MimicFormBuff").DisplayName.AddTranslation(GameCulture.Russian, "Подражатель");
			thorium.GetBuff("MimicFormBuff").Description.AddTranslation(GameCulture.Russian, "Вы превратились в сундук-подражатель");
			thorium.GetBuff("OldDebt").DisplayName.AddTranslation(GameCulture.Russian, "Знакомое лицо");
			thorium.GetBuff("OldDebt").Description.AddTranslation(GameCulture.Russian, "Старый долг выплачивается... а теперь спасите мир!");
			thorium.GetBuff("RagMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Апокалипсис");
			thorium.GetBuff("RagMountBuff").Description.AddTranslation(GameCulture.Russian, "Вы знаменуете конец света...");
			thorium.GetBuff("RocketCartBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ракетная тележка");
			thorium.GetBuff("RocketCartBuff").Description.AddTranslation(GameCulture.Russian, "Это не безопасно...");
			thorium.GetBuff("SpectralFangBuff").DisplayName.AddTranslation(GameCulture.Russian, "Спектральный тигр");
			thorium.GetBuff("SpectralFangBuff").Description.AddTranslation(GameCulture.Russian, "Даже в смерти он все такой же хороший компаньон");
			thorium.GetBuff("SquirrelBuff").DisplayName.AddTranslation(GameCulture.Russian, "Белка");
			thorium.GetBuff("SquirrelBuff").Description.AddTranslation(GameCulture.Russian, "Вы превратились в белку");
			thorium.GetBuff("StarvedMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Голодный зверь");
			thorium.GetBuff("StarvedMountBuff").Description.AddTranslation(GameCulture.Russian, "Этот зверь пускает слюни в своем вечном голоде");
			thorium.GetBuff("SuperAnvilBuff").DisplayName.AddTranslation(GameCulture.Russian, "Супер наковальня");
			thorium.GetBuff("SuperAnvilBuff").Description.AddTranslation(GameCulture.Russian, "Тяжелее, чем вес ваших ответственности");
			thorium.GetBuff("WargMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Боевой варг");
			thorium.GetBuff("WargMountBuff").Description.AddTranslation(GameCulture.Russian, "Вступи в бой на своем черном варге!");
			thorium.GetBuff("WhaleMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кит");
			thorium.GetBuff("WhaleMountBuff").Description.AddTranslation(GameCulture.Russian, "Это действительно стоило того?");
			thorium.GetBuff("WyvernMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Виверна");
			thorium.GetBuff("WyvernMountBuff").Description.AddTranslation(GameCulture.Russian, "Почувствуй ветер в своих волосах!");
			thorium.GetBuff("Enrage").DisplayName.AddTranslation(GameCulture.Russian, "Ярость!");
			thorium.GetBuff("Enrage").Description.AddTranslation(GameCulture.Russian, "Этот противник наносит на 15% больше урона при контакте");
			thorium.GetBuff("Protection").DisplayName.AddTranslation(GameCulture.Russian, "Защита");
			thorium.GetBuff("Protection").Description.AddTranslation(GameCulture.Russian, "Этот противник получает на 25% меньше урона");
			thorium.GetBuff("QuickFire").DisplayName.AddTranslation(GameCulture.Russian, "Скорострел");
			thorium.GetBuff("QuickFire").Description.AddTranslation(GameCulture.Russian, "Этот противник стреляет быстрее, чем обычно");
			thorium.GetBuff("Regeneration").DisplayName.AddTranslation(GameCulture.Russian, "Регенерация");
			thorium.GetBuff("Regeneration").Description.AddTranslation(GameCulture.Russian, "Этот противник восстанавливает здоровье");
			thorium.GetBuff("AbyssalWhistleBuff").DisplayName.AddTranslation(GameCulture.Russian, "Глубинный кролик");
			thorium.GetBuff("AbyssalWhistleBuff").Description.AddTranslation(GameCulture.Russian, "Этот бедный малыш может быть последним из своего вида...");
			thorium.GetBuff("BabyBaliBuff").DisplayName.AddTranslation(GameCulture.Russian, "Экзотическая майна");
			thorium.GetBuff("BabyBaliBuff").Description.AddTranslation(GameCulture.Russian, "Этот особенный птенец любит тебя!");
			thorium.GetBuff("BioFeederBuff").DisplayName.AddTranslation(GameCulture.Russian, "Био-кормушка");
			thorium.GetBuff("BioFeederBuff").Description.AddTranslation(GameCulture.Russian, "Что за странное маленькое создание...");
			thorium.GetBuff("BlisterBuff").DisplayName.AddTranslation(GameCulture.Russian, "Летающий волдырь");
			thorium.GetBuff("BlisterBuff").Description.AddTranslation(GameCulture.Russian, "Он не оставит тебя в покое!");
			thorium.GetBuff("BoneBoyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Беспомощный череп");
			thorium.GetBuff("BoneBoyBuff").Description.AddTranslation(GameCulture.Russian, "Этому бывшему скелету нужна твоя помощь!");
			thorium.GetBuff("ClownfishPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Рыба-клоун");
			thorium.GetBuff("ClownfishPetBuff").Description.AddTranslation(GameCulture.Russian, "Не смейся над ним...");
			thorium.GetBuff("DrachmaBuff").DisplayName.AddTranslation(GameCulture.Russian, "Любопытный коинлинг");
			thorium.GetBuff("DrachmaBuff").Description.AddTranslation(GameCulture.Russian, "Драхмы в наши дни не очень полезны...");
			thorium.GetBuff("Experiment3Buff").DisplayName.AddTranslation(GameCulture.Russian, "Эксперимент #3");
			thorium.GetBuff("Experiment3Buff").Description.AddTranslation(GameCulture.Russian, "Будь рад, что он еще не взрослый...");
			thorium.GetBuff("FerretBuff").DisplayName.AddTranslation(GameCulture.Russian, "Хорек");
			thorium.GetBuff("FerretBuff").Description.AddTranslation(GameCulture.Russian, "Этот маленький парень просто обожает двигаться!");
			thorium.GetBuff("HolyGoatBuff").DisplayName.AddTranslation(GameCulture.Russian, "Святая коза");
			thorium.GetBuff("HolyGoatBuff").Description.AddTranslation(GameCulture.Russian, "Он светится золотом, так что и так неплохо!");
			thorium.GetBuff("JellyPet").DisplayName.AddTranslation(GameCulture.Russian, "Медуза в пузыре");
			thorium.GetBuff("JellyPet").Description.AddTranslation(GameCulture.Russian, "Посмотрите как она летает вокруг!");
			thorium.GetBuff("LilMogBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленький мугл");
			thorium.GetBuff("LilMogBuff").Description.AddTranslation(GameCulture.Russian, "Он милый, не правда ли?");
			thorium.GetBuff("LittlePhylacteryBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленький некромант");
			thorium.GetBuff("LittlePhylacteryBuff").Description.AddTranslation(GameCulture.Russian, "Этот маленький парень намного сильнее чем кажется...");
			thorium.GetBuff("LockBoxBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сундучок Дэйви Джонса!");
			thorium.GetBuff("LockBoxBuff").Description.AddTranslation(GameCulture.Russian, "Полный бесконечным количеством монет!");
			thorium.GetBuff("LostFairyBuff").DisplayName.AddTranslation(GameCulture.Russian, "На охоте");
			thorium.GetBuff("LostFairyBuff").Description.AddTranslation(GameCulture.Russian, "Вы пытаетесь найти чьего-то потерянного друга...");
			thorium.GetBuff("LostFairyBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Цепляющая фея");
			thorium.GetBuff("LostFairyBuff2").Description.AddTranslation(GameCulture.Russian, "Фея следует за вами!");
			thorium.GetBuff("LostMartianBuff").DisplayName.AddTranslation(GameCulture.Russian, "Отчаянный инопланетянин");
			thorium.GetBuff("LostMartianBuff").Description.AddTranslation(GameCulture.Russian, "У этого пришельца осталось немного времени...");
			thorium.GetBuff("MaidBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленькая горничная");
			thorium.GetBuff("MaidBuff").Description.AddTranslation(GameCulture.Russian, "Ну, здесь не то чтобы надо убираться...");
			thorium.GetBuff("OmegaBuff").DisplayName.AddTranslation(GameCulture.Russian, "Омега Драйв");
			thorium.GetBuff("OmegaBuff").Description.AddTranslation(GameCulture.Russian, "ИСПАРИТЕЛЬНАЯ МАТРИЦА: ОНЛАЙН");
			thorium.GetBuff("PickleBuff").DisplayName.AddTranslation(GameCulture.Russian, "Совершенно Обычная Собака");
			thorium.GetBuff("PickleBuff").Description.AddTranslation(GameCulture.Russian, "или же...?");
			thorium.GetBuff("PinkSlimeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Розовый слизень");
			thorium.GetBuff("PinkSlimeBuff").Description.AddTranslation(GameCulture.Russian, "Это так мило!");
			thorium.GetBuff("ShineDust").DisplayName.AddTranslation(GameCulture.Russian, "Сияющий друг");
			thorium.GetBuff("ShineDust").Description.AddTranslation(GameCulture.Russian, "Это довольно мило...");
			thorium.GetBuff("SkunkBuff").DisplayName.AddTranslation(GameCulture.Russian, "Скунс");
			thorium.GetBuff("SkunkBuff").Description.AddTranslation(GameCulture.Russian, "Не пугай его, не то пожалеешь...");
			thorium.GetBuff("SnowyOwlBuff").DisplayName.AddTranslation(GameCulture.Russian, "Потерянная снежная сова");
			thorium.GetBuff("SnowyOwlBuff").Description.AddTranslation(GameCulture.Russian, "Видимо кто-то не получил свою почту...");
			thorium.GetBuff("SupportLanternBuff").DisplayName.AddTranslation(GameCulture.Russian, "Восстановительный фонарь");
			thorium.GetBuff("SupportLanternBuff").Description.AddTranslation(GameCulture.Russian, "Он постоянно излучает успокаивающую ауру");
			thorium.GetBuff("TortleScuteBuff").DisplayName.AddTranslation(GameCulture.Russian, "Черепаший мудрец");
			thorium.GetBuff("TortleScuteBuff").Description.AddTranslation(GameCulture.Russian, "Мудр не по годам");
			thorium.GetBuff("WyvernPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Виверна-волчонок");
			thorium.GetBuff("WyvernPetBuff").Description.AddTranslation(GameCulture.Russian, "Он может быть и молод, но старается как может!");
			thorium.GetBuff("BannerConfusion").DisplayName.AddTranslation(GameCulture.Russian, "Коллективный разум");
			thorium.GetBuff("BannerConfusion").Description.AddTranslation(GameCulture.Russian, "Призванные существа могут запутать врагов");
			thorium.GetBuff("BannerDamage").DisplayName.AddTranslation(GameCulture.Russian, "Боевое знамя");
			thorium.GetBuff("BannerDamage").Description.AddTranslation(GameCulture.Russian, "Призванные существа наносят 5 дополнительного урона");
			thorium.GetBuff("BannerDefense").DisplayName.AddTranslation(GameCulture.Russian, "Воинственное знамя");
			thorium.GetBuff("BannerDefense").Description.AddTranslation(GameCulture.Russian, "Сопротивление урону повышается на 3% за каждое призванное существо");
			thorium.GetBuff("BannerFalcon").DisplayName.AddTranslation(GameCulture.Russian, "Сокол");
			thorium.GetBuff("BannerFalcon").Description.AddTranslation(GameCulture.Russian, "Ближайшие призванные существа могут нанести дополнительный урон");
			thorium.GetBuff("BannerGhost").DisplayName.AddTranslation(GameCulture.Russian, "Жертвенное чучело");
			thorium.GetBuff("BannerGhost").Description.AddTranslation(GameCulture.Russian, "Ближайшие убийства призывают помогающих призраков");
			thorium.GetBuff("BannerLifeRegen").DisplayName.AddTranslation(GameCulture.Russian, "Знамя боевого духа");
			thorium.GetBuff("BannerLifeRegen").Description.AddTranslation(GameCulture.Russian, "Атаки прислужников могут исцелить вас");
			thorium.GetBuff("BannerPower").DisplayName.AddTranslation(GameCulture.Russian, "Знамя мощи");
			thorium.GetBuff("BannerPower").Description.AddTranslation(GameCulture.Russian, "Один из ваших стражей усилен");
			thorium.GetBuff("Beholding").DisplayName.AddTranslation(GameCulture.Russian, "Созерцание");
			thorium.GetBuff("Beholding").Description.AddTranslation(GameCulture.Russian, "Созерцающий покажет и уничтожит ваших противников");
			thorium.GetBuff("BlackCaneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Оружие Ли");
			thorium.GetBuff("BlackCaneBuff").Description.AddTranslation(GameCulture.Russian, "Любимое оружие Ли сражается за вас, даже когда его истинный хозяин в могиле...");
			thorium.GetBuff("BlobfishBuff").DisplayName.AddTranslation(GameCulture.Russian, "Рыба-капля");
			thorium.GetBuff("BlobfishBuff").Description.AddTranslation(GameCulture.Russian, "Это мило? Или же уродливо? Вам решать....");
			thorium.GetBuff("BloodDrinker").DisplayName.AddTranslation(GameCulture.Russian, "Кровопийца");
			thorium.GetBuff("BloodDrinker").Description.AddTranslation(GameCulture.Russian, "Его жажда крови ненасытна");
			thorium.GetBuff("BloodMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый зомби");
			thorium.GetBuff("BloodMinionBuff").Description.AddTranslation(GameCulture.Russian, "Пока его кормят, он вас не побеспокоит...");
			thorium.GetBuff("BloodPact").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый пакт");
			thorium.GetBuff("BloodPact").Description.AddTranslation(GameCulture.Russian, "Просто заключил договор с демоном...");
			thorium.GetBuff("ButterflyMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Рой бабочек");
			thorium.GetBuff("ButterflyMinionBuff").Description.AddTranslation(GameCulture.Russian, "Собравшись вместе, бабочки представляют для врагов нешуточную угрозу");
			thorium.GetBuff("Command").DisplayName.AddTranslation(GameCulture.Russian, "Аура сплочения");
			thorium.GetBuff("Command").Description.AddTranslation(GameCulture.Russian, "Существа, призванные под этим эффектом, наносят на 10% больше урона");
			thorium.GetBuff("CorrodeSlimeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Искажака");
			thorium.GetBuff("CorrodeSlimeBuff").Description.AddTranslation(GameCulture.Russian, "У защитников нет шансов против орды этих малышей!");
			thorium.GetBuff("CorruptMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Душевик");
			thorium.GetBuff("CorruptMinionBuff").Description.AddTranslation(GameCulture.Russian, "Не все обитатели искажения хотят есть души...");
			thorium.GetBuff("CrimsonMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Кровавая гончая");
			thorium.GetBuff("CrimsonMinionBuff").Description.AddTranslation(GameCulture.Russian, "Несмотря на отсутствие рта, гончая всегда найдет способ наесться...");
			thorium.GetBuff("DarkRisenBuff").DisplayName.AddTranslation(GameCulture.Russian, "Темное воскрешение");
			thorium.GetBuff("DarkRisenBuff").Description.AddTranslation(GameCulture.Russian, "Да он хоть сейчас готов начать свою скелетную рейв-вечеринку!");
			thorium.GetBuff("DinoBuff").DisplayName.AddTranslation(GameCulture.Russian, "Буйство");
			thorium.GetBuff("DinoBuff").Description.AddTranslation(GameCulture.Russian, "Эти динозавры сходят с ума!");
			thorium.GetBuff("DragonMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Литой дракон");
			thorium.GetBuff("DragonMinionBuff").Description.AddTranslation(GameCulture.Russian, "У ваших врагов нет ни шанса");
			thorium.GetBuff("EnchantedShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Зачарованный барьер");
			thorium.GetBuff("EnchantedShieldBuff").Description.AddTranslation(GameCulture.Russian, "Вы защищены магическим барьером");
			thorium.GetBuff("EnchantedTomeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Гримуар");
			thorium.GetBuff("EnchantedTomeBuff").Description.AddTranslation(GameCulture.Russian, "Стреляющая заклинаниями книга помогает вам");
			thorium.GetBuff("EnigmaMinion").DisplayName.AddTranslation(GameCulture.Russian, "Энигма");
			thorium.GetBuff("EnigmaMinion").Description.AddTranslation(GameCulture.Russian, "Свет огибает сложную энигму...");
			thorium.GetBuff("HailBomberBuff").DisplayName.AddTranslation(GameCulture.Russian, "Градо-подрывник");
			thorium.GetBuff("HailBomberBuff").Description.AddTranslation(GameCulture.Russian, "Не бойся, они не пострадали... наверное");
			thorium.GetBuff("HatchlingBuff").DisplayName.AddTranslation(GameCulture.Russian, "Птенец");
			thorium.GetBuff("HatchlingBuff").Description.AddTranslation(GameCulture.Russian, "Этот птенец считает вас своей матерью!");
			thorium.GetBuff("IceFairyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ледяная фея");
			thorium.GetBuff("IceFairyBuff").Description.AddTranslation(GameCulture.Russian, "Лучше бы вашим врагам принести на бой шубу!");
			thorium.GetBuff("LadyLightBuff").DisplayName.AddTranslation(GameCulture.Russian, "Звездная искра");
			thorium.GetBuff("LadyLightBuff").Description.AddTranslation(GameCulture.Russian, "Сверкает в неистовстве!");
			thorium.GetBuff("MantisMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Бритвенный богомол");
			thorium.GetBuff("MantisMinionBuff").Description.AddTranslation(GameCulture.Russian, "Мужчины, берегитесь!");
			thorium.GetBuff("MeteorHeadStaff").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритная голова");
			thorium.GetBuff("MeteorHeadStaff").Description.AddTranslation(GameCulture.Russian, "Метеоритная голова решила работать с вами");
			thorium.GetBuff("MeteorShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Астральный барьер");
			thorium.GetBuff("MeteorShieldBuff").Description.AddTranslation(GameCulture.Russian, "Вы защищены астральным барьером");
			thorium.GetBuff("MoltenBannerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Литое знамя");
			thorium.GetBuff("MoltenBannerBuff").Description.AddTranslation(GameCulture.Russian, "Призванные существа были усилены мощным жаром");
			thorium.GetBuff("MushroomArmy").DisplayName.AddTranslation(GameCulture.Russian, "Грибная армия");
			thorium.GetBuff("MushroomArmy").Description.AddTranslation(GameCulture.Russian, "Командуйте военными силами грибов!");
			thorium.GetBuff("NebulaMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Зеркальное отражение");
			thorium.GetBuff("NebulaMinionBuff").Description.AddTranslation(GameCulture.Russian, "Зеркальное изображение помогает вам");
			thorium.GetBuff("OdinEyeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Око Одина");
			thorium.GetBuff("OdinEyeBuff").Description.AddTranslation(GameCulture.Russian, "Могучий глаз готов обрушить на ваших врагов электрическую бурю!");
			thorium.GetBuff("RosySlimeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Розовый слизень");
			thorium.GetBuff("RosySlimeBuff").Description.AddTranslation(GameCulture.Russian, "Почти столь же демоническая, как сама Пинки");
			thorium.GetBuff("SaplingBuff").DisplayName.AddTranslation(GameCulture.Russian, "Верный росток");
			thorium.GetBuff("SaplingBuff").Description.AddTranslation(GameCulture.Russian, "Ради спасения мира, этот малыш выкладывается на полную");
			thorium.GetBuff("SeahorseBuff").DisplayName.AddTranslation(GameCulture.Russian, "Морской конек");
			thorium.GetBuff("SeahorseBuff").Description.AddTranslation(GameCulture.Russian, "И на пути у нас пузыри!");
			thorium.GetBuff("SlagMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Литой уголек");
			thorium.GetBuff("SlagMinionBuff").Description.AddTranslation(GameCulture.Russian, "Тепло, испускаемое им, неизмеримо...");
			thorium.GetBuff("SteamgunnerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Стимпанковский дрон");
			thorium.GetBuff("SteamgunnerBuff").Description.AddTranslation(GameCulture.Russian, "У дрона всего одна задача: СТРЕЛЯТЬ");
			thorium.GetBuff("TigerMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Малыш-котенок");
			thorium.GetBuff("TigerMinionBuff").Description.AddTranslation(GameCulture.Russian, "Укусы и царапины станут их погибелью");
			thorium.GetBuff("BloodLotus").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый лотос");
			thorium.GetBuff("BloodLotus").Description.AddTranslation(GameCulture.Russian, "Выпускает крадущий здоровье поток");
			thorium.GetBuff("LastStandBuff").DisplayName.AddTranslation(GameCulture.Russian, "Последний бой");
			thorium.GetBuff("LastStandBuff").Description.AddTranslation(GameCulture.Russian, "Скорость метания и урон повышены на 30%, но ведь все имеет свою цену...");
			thorium.GetBuff("ThrowingSpeed").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв скорости");
			thorium.GetBuff("ThrowingSpeed").Description.AddTranslation(GameCulture.Russian, "Ваша скорость метания была повышена на 15%");
			thorium.GetBuff("ValkyrieBladeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Клинок валькирии");
			thorium.GetBuff("ValkyrieBladeBuff").Description.AddTranslation(GameCulture.Russian, "У этого клинка есть своя воля...");
		}
	}
}
