using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using CalamityRuTranslate.Utilities;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityRuTranslate.Vanilla
{
    public class PrefixRussianOverhoul : GlobalItem
    {
        //Мужской, Женский, Средний, Множественный
        private static string[][] _prefixes = {
            new [] {"Искусный ", "Искусная ", "Искусное ", "Искусные "},
            new [] {"Проворный ", "Проворная ", "Проворное ", "Проворные "},
            new [] {"Яростный ", "Яростная ", "Яростное ", "Яростные "},
            new [] {"Надоедливый ", "Надоедливая ", "Надоедливое ", "Надоедливые "},
            new [] {"Таинственный ", "Таинственная ", "Таинственное ", "Таинственные "},
            new [] {"Укреплённый ", "Укреплённая ", "Укреплённое ", "Укреплённые "},
            new [] {"Отвратительный ", "Отвратительная ", "Отвратительное ", "Отвратительные "},
            new [] {"Неудобный ", "Неудобная ", "Неудобное ", "Неудобные "},
            new [] {"Юркий ", "Юркая ", "Юркое ", "Юркие "},
            new [] {"Сломанный ", "Сломанная ", "Сломанное ", "Сломанные "},
            new [] {"Громоздкий ", "Громоздкая ", "Громоздкое ", "Громоздкие "},
            new [] {"Небесный ", "Небесная ", "Небесное ", "Небесные "},
            new [] {"Повреждённый ", "Повреждённая ", "Повреждённое ", "Повреждённые "},
            new [] {"Опасный ", "Опасная ", "Опасное ", "Опасные "},
            new [] {"Смертоносный ", "Смертоносная ", "Смертоносное ", "Смертоносные "},
            new [] {"Смертоносный ", "Смертоносная ", "Смертоносное ", "Смертоносные "},
            new [] {"Демонический ", "Демоническая ", "Демоническое ", "Демонические "},
            new [] {"Безумный ", "Безумная ", "Безумное ", "Безумные "},
            new [] {"Притуплённый ", "Притуплённая ", "Притуплённое ", "Притуплённые "},
            new [] {"Стремительный ", "Стремительная ", "Стремительное ", "Стремительные "},
            new [] {"Неистовый ", "Неистовая ", "Неистовое ", "Неистовые "},
            new [] {"Буйный ", "Буйная ", "Буйное ", "Буйные "},
            new [] {"Яростный ", "Яростная ", "Яростное ", "Яростные "},
            new [] {"Праведный ", "Праведная ", "Праведное ", "Праведные "},
            new [] {"Охранный ", "Охранная ", "Охранное ", "Охранные "},
            new [] {"Твёрдый ", "Твёрдая ", "Твёрдое ", "Твёрдые "},
            new [] {"Стремительный ", "Стремительная ", "Стремительное ", "Стремительные "},
            new [] {"Поспешный ", "Поспешная ", "Поспешное ", "Поспешные "},
            new [] {"Тяжёлый ", "Тяжёлая ", "Тяжёлое ", "Тяжёлые "},
            new [] {"Пагубный ", "Пагубная ", "Пагубное ", "Пагубные "},
            new [] {"Никчёмный ", "Никчёмная ", "Никчёмное ", "Никчёмные "},
            new [] {"Непригодный ", "Непригодная ", "Непригодное ", "Непригодные "},
            new [] {"Мощный ", "Мощная ", "Мощное ", "Мощные "},
            new [] {"Устрашающий ", "Устрашающая ", "Устрашающее ", "Устрашающие "},
            new [] {"Отважный ", "Отважная ", "Отважное ", "Отважные "},
            new [] {"Зазубренный ", "Зазубренная ", "Зазубренное ", "Зазубренные "},
            new [] {"Заточенный ", "Заточенная ", "Заточенное ", "Заточенные "},
            new [] {"Большой ", "Большая ", "Большое ", "Большие "},
            new [] {"Лентяйский ", "Лентяйская ", "Лентяйское ", "Лентяйские "},
            new [] {"Легендарный ", "Легендарная ", "Легендарное ", "Легендарные "},
            new [] {"Апатичный ", "Апатичная ", "Апатичное ", "Апатичные "},
            new [] {"Лёгкий ", "Лёгкая ", "Лёгкое ", "Лёгкие "},
            new [] {"Везучий ", "Везучая ", "Везучее ", "Везучие "},
            new [] {"Маниакальный ", "Маниакальная ", "Маниакальное ", "Маниакальные "},
            new [] {"Массивный ", "Массивная ", "Массивное ", "Массивные "},
            new [] {"Умелый ", "Умелая ", "Умелое ", "Умелые "},
            new [] {"Грозный ", "Грозная ", "Грозное ", "Грозные "},
            new [] {"Убийственный ", "Убийственная ", "Убийственное ", "Убийственные "},
            new [] {"Мистический ", "Мистическая ", "Мистическое ", "Мистические "},
            new [] {"Загадочный ", "Загадочная ", "Загадочное ", "Загадочные "},
            new [] {"Пакостный ", "Пакостная ", "Пакостное ", "Пакостные "},
            new [] {"Шустрый ", "Шустрая ", "Шустрое ", "Шустрые "},
            new [] {"Заострённый ", "Заострённая ", "Заострённое ", "Заострённые "},
            new [] {"Мощный ", "Мощная ", "Мощное ", "Мощные "},
            new [] {"Точный ", "Точная ", "Точное ", "Точные "},
            new [] {"Быстрый ", "Быстрая ", "Быстрое ", "Быстрые "},
            new [] {"Быстрый ", "Быстрая ", "Быстрое ", "Быстрые "},
            new [] {"Скоростной ", "Скоростная ", "Скоростное ", "Скоростные "},
            new [] {"Безудержный ", "Безудержная ", "Безудержное ", "Безудержные "},
            new [] {"Безжалостный ", "Безжалостная ", "Безжалостное ", "Безжалостные "},
            new [] {"Кровожадный ", "Кровожадная ", "Кровожадное ", "Кровожадные "},
            new [] {"Позорный ", "Позорная ", "Позорное ", "Позорные "},
            new [] {"Острый ", "Острая ", "Острое ", "Острые "},
            new [] {"Некачественный ", "Некачественная ", "Некачественное ", "Некачественные "},
            new [] {"Меткий ", "Меткая ", "Меткое ", "Меткие "},
            new [] {"Медлительный ", "Медлительная ", "Медлительное ", "Медлительные "},
            new [] {"Вялый ", "Вялая ", "Вялое ", "Вялые "},
            new [] {"Маленький ", "Маленькая ", "Маленькое ", "Маленькие "},
            new [] {"Шипастый ", "Шипастая ", "Шипастое ", "Шипастые "},
            new [] {"Надёжный ", "Надёжная ", "Надёжное ", "Надёжные "},
            new [] {"Усиленный ", "Усиленная ", "Усиленное ", "Усиленные "},
            new [] {"Превосходный ", "Превосходная ", "Превосходное ", "Превосходные "},
            new [] {"Запретный ", "Запретная ", "Запретное ", "Запретные "},
            new [] {"Ужасный ", "Ужасная ", "Ужасное ", "Ужасные "},
            new [] {"Крошечный ", "Крошечная ", "Крошечное ", "Крошечные "},
            new [] {"Неудачный ", "Неудачная ", "Неудачное ", "Неудачные "},
            new [] {"Неприятный ", "Неприятная ", "Неприятное ", "Неприятные "},
            new [] {"Нереальный ", "Нереальная ", "Нереальное", "Нереальные "},
            new [] {"Жестокий ", "Жестокая ", "Жестокое ", "Жестокие "},
            new [] {"Оберегающий ", "Оберегающая ", "Оберегающее ", "Оберегающие "},
            new [] {"Слабый ", "Слабая ", "Слабое ", "Слабые "},
            new [] {"Дикий ", "Дикая ", "Дикое ", "Дикие "},
            new [] {"Пылкий ", "Пылкая ", "Пылкое ", "Пылкие "}
        };

        private static List<int> _typeW = new List<int>
        {
            ItemID.BoneGlove,
            ItemID.LuckyHorseshoe,
            ItemID.Ruler,
            ItemID.BlizzardinaBottle,
            ItemID.HighTestFishingLine,
            ItemID.AnglerEarring,
            ItemID.FrogLeg,
            ItemID.LaserRuler,
            ItemID.BalloonPufferfish,
            ItemID.RedString,
            ItemID.OrangeString,
            ItemID.YellowString,
            ItemID.LimeString,
            ItemID.GreenString,
            ItemID.TealString,
            ItemID.CyanString,
            ItemID.SkyBlueString,
            ItemID.BlueString,
            ItemID.PurpleString,
            ItemID.VioletString,
            ItemID.PinkString,
            ItemID.BrownString,
            ItemID.WhiteString,
            ItemID.RainbowString,
            ItemID.BlackString,
            ItemID.SandstorminaBottle,
            ItemID.FartinaJar,
            ItemID.HandWarmer,
            ItemID.Toolbox,
            ItemID.ObsidianRose,
            ItemID.PortableCementMixer,
            ItemID.GoblinTech,
            ItemID.MechanicalLens,
            ItemID.ObsidianHorseshoe,
            ItemID.MoonCharm,
            ItemID.SorcererEmblem,
            ItemID.WarriorEmblem,
            ItemID.RangerEmblem,
            ItemID.TitanGlove,
            ItemID.Blindfold,
            ItemID.TrifoldMap,
            ItemID.SandstorminaBalloon,
            ItemID.BlizzardinaBalloon,
            ItemID.FartInABalloon,
            ItemID.SummonerEmblem,
            ItemID.YoYoGlove,
            ItemID.NeptunesShell,
            ItemID.DiscountCard,
            ItemID.LuckyCoin,
            ItemID.PowerGlove,
            ItemID.CountercurseMantra,
            ItemID.AvengerEmblem,
            ItemID.Hoverboard,
            ItemID.CelestialEmblem,
            ItemID.MoonShell,
            ItemID.StarVeil,
            ItemID.MechanicalGlove,
            ItemID.DestroyerEmblem,
            ItemID.FireGauntlet,
            ItemID.BundleofBalloons,
            ItemID.CelestialShell,
            ItemID.BejeweledValkyrieWing,
            ItemID.LeinforsWings,
            ItemID.WingsNebula,
            ItemID.CobaltChainsaw,
            ItemID.MythrilChainsaw,
            ItemID.AdamantiteChainsaw,
            ItemID.FleshGrinder,
            ItemID.BloodLustCluster,
            ItemID.PalladiumChainsaw,
            ItemID.OrichalcumChainsaw,
            ItemID.TitaniumChainsaw,
            ItemID.ChlorophyteChainsaw,
            ItemID.SawtoothShark,
            ItemID.ButchersChainsaw,
            ItemID.CactusPickaxe,
            ItemID.TinPickaxe,
            ItemID.CopperPickaxe,
            ItemID.IronPickaxe,
            ItemID.LeadPickaxe,
            ItemID.SilverPickaxe,
            ItemID.BonePickaxe,
            ItemID.TungstenPickaxe,
            ItemID.CnadyCanePickaxe,
            ItemID.GoldPickaxe,
            ItemID.PlatinumPickaxe,
            ItemID.NightmarePickaxe,
            ItemID.DeathbringerPickaxe,
            ItemID.MoltenPickaxe,
            ItemID.ReaverShark,
            ItemID.CobaltPickaxe,
            ItemID.PalladiumPickaxe,
            ItemID.MythrilPickaxe,
            ItemID.OrichalcumPickaxe,
            ItemID.AdamantitePickaxe,
            ItemID.TitaniumPickaxe,
            ItemID.ChlorophytePickaxe,
            ItemID.SpectrePickaxe,
            ItemID.ShroomiteDiggingClaw,
            ItemID.VortexPickaxe,
            ItemID.NebulaPickaxe,
            ItemID.SolarFlarePickaxe,
            ItemID.StardustPickaxe,
            ItemID.Minishark,
            ItemID.Blowpipe,
            ItemID.Sickle,
            ItemID.Vilethorn,
            ItemID.SnowballCannon,
            ItemID.DD2LightningAuraT2Popper,
            ItemID.ZombieArm,
            ItemID.BladedGlove,
            ItemID.TheRottedFork,
            ItemID.TheMeatball,
            ItemID.Katana,
            ItemID.TaxCollectorsStickOfDoom,
            ItemID.CrimsonYoyo,
            ItemID.SpaceGun,
            ItemID.Muramasa,
            ItemID.ClockworkAssaultRifle,
            ItemID.Swordfish,
            ItemID.JungleYoyo,
            ItemID.DyeTradersScimitar,
            ItemID.WaspGun,
            ItemID.Starfury,
            ItemID.Valor,
            ItemID.BlueMoon,
            ItemID.PurpleClubberfish,
            ItemID.BookStaff,
            ItemID.Megashark,
            ItemID.MagicMissile,
            ItemID.LaserRifle,
            ItemID.CobaltNaginata,
            ItemID.BookofSkulls,
            ItemID.Sandgun,
            ItemID.MoltenFury,
            ItemID.MagicalHarp,
            ItemID.PalladiumPike,
            ItemID.Sunfury,
            ItemID.DemonScythe,
            ItemID.MythrilHalberd,
            ItemID.SlapHand,
            ItemID.OrichalcumHalberd,
            ItemID.AdamantiteGlaive,
            ItemID.PiranhaGun,
            ItemID.Flamelash,
            ItemID.Marrow,
            ItemID.KOCannon,
            ItemID.ElectrosphereLauncher,
            ItemID.ShadowFlameHexDoll,
            ItemID.NightsEdge,
            ItemID.IceSickle,
            ItemID.DD2FlameburstTowerT2Popper,
            ItemID.CandyCornRifle,
            ItemID.RainbowGun,
            ItemID.Xenopopper,
            ItemID.MedusaHead,
            ItemID.MonkStaffT2,
            ItemID.ToxicFlask,
            ItemID.ChlorophyteSaber,
            ItemID.MagnetSphere,
            ItemID.Cutlass,
            ItemID.Frostbrand,
            ItemID.ChargedBlasterCannon,
            ItemID.VortexBeater,
            ItemID.DartRifle,
            ItemID.StarCannon,
            ItemID.DeathSickle,
            ItemID.DD2ExplosiveTrapT2Popper,
            ItemID.DaoofPow,
            ItemID.ScourgeoftheCorruptor,
            ItemID.ApprenticeStaffT3,
            ItemID.SnowmanCannon,
            ItemID.DD2BallistraTowerT2Popper,
            ItemID.ObsidianSwordfish,
            ItemID.BubbleGun,
            ItemID.MonkStaffT3,
            ItemID.TrueNightsEdge,
            ItemID.LastPrism,
            ItemID.LunarFlareBook,
            ItemID.StarWrath,
            ItemID.DayBreak,
            
        };
        
        private static List<int> _typeU = new List<int>
        {
            ItemID.CloudinaBottle,
            ItemID.PanicNecklace,
            ItemID.WeatherRadio,
            ItemID.CordageGuide,
            ItemID.FishermansGuide,
            ItemID.TsunamiInABottle,
            ItemID.SharkToothNecklace,
            ItemID.JellyfishNecklace,
            ItemID.SweetheartNecklace,
            ItemID.PocketMirror,
            ItemID.DivingGear,
            ItemID.CloudinaBalloon,
            ItemID.ArmorBracing,
            ItemID.GoldRing,
            ItemID.CoinRing,
            ItemID.CharmofMyths,
            ItemID.GreedyRing,
            ItemID.PygmyNecklace,
            ItemID.Yoraiz0rWings,
            ItemID.Spear,
            ItemID.WoodYoyo,
            ItemID.Rally,
            ItemID.AntlionClaw,
            ItemID.RedRyder,
            ItemID.Blowgun,
            ItemID.DarkLance,
            ItemID.Uzi,
            ItemID.FalconBlade,
            ItemID.HelFire,
            ItemID.DD2SquireDemonSword,
            ItemID.DD2BetsyBow,
            ItemID.MushroomSpear,
            ItemID.Tsunami,
            ItemID.FireworksLauncher,
            ItemID.ValkyrieYoyo,
            ItemID.SpiritFlame,
            ItemID.SolarEruption,
            ItemID.NebulaBlaze,
            ItemID.SniperRifle,
            
        };
        
        private static List<int> _typePl = new List<int>
        {
            ItemID.BrainOfConfusion,
            ItemID.CopperWatch,
            ItemID.SilverWatch,
            ItemID.TinWatch,
            ItemID.TungstenWatch,
            ItemID.GoldWatch,
            ItemID.HermesBoots,
            ItemID.Flipper,
            ItemID.Shackle,
            ItemID.PlatinumWatch,
            ItemID.IceSkates,
            ItemID.ClimbingClaws,
            ItemID.ShoeSpikes,
            ItemID.FlurryBoots,
            ItemID.SailfishBoots,
            ItemID.BrainOfConfusion,
            ItemID.MagicCuffs,
            ItemID.RocketBoots,
            ItemID.FeralClaws,
            ItemID.SpectreBoots,
            ItemID.WaterWalkingBoots,
            ItemID.FastClock,
            ItemID.Vitamins,
            ItemID.ObsidianWaterWalkingBoots,
            ItemID.FinWings,
            ItemID.DemonWings,
            ItemID.AngelWings,
            ItemID.ButterflyWings,
            ItemID.FairyWings,
            ItemID.HarpyWings,
            ItemID.BoneWings,
            ItemID.FlameWings,
            ItemID.FrozenWings,
            ItemID.LightningBoots,
            ItemID.LeafWings,
            ItemID.BatWings,
            ItemID.BeeWings,
            ItemID.FestiveWings,
            ItemID.CelestialCuffs,
            ItemID.PutridScent,
            ItemID.LavaWaders,
            ItemID.Tabi,
            ItemID.TatteredFairyWings,
            ItemID.SpookyWings,
            ItemID.FrostsparkBoots,
            ItemID.BeetleWings,
            ItemID.FlowerBoots,
            ItemID.GhostWings,
            ItemID.SteampunkWings,
            ItemID.MasterNinjaGear,
            ItemID.FishronWings,
            ItemID.MothronWings,
            ItemID.BetsyWings,
            ItemID.RedsWings,
            ItemID.DTownsWings,
            ItemID.WillsWings,
            ItemID.CrownosWings,
            ItemID.CenxsWings,
            ItemID.JimsWings,
            ItemID.SkiphsWings,
            ItemID.LokisWings,
            ItemID.ArkhalisWings,
            ItemID.WingsSolar,
            ItemID.WingsStardust,
            ItemID.StylistKilLaKillScissorsIWish,
            ItemID.VampireKnives,
            ItemID.ChainGuillotines,
            ItemID.FetidBaghnakhs,
            
        };

        public override void ModifyTooltips(Item item, List<TooltipLine> tooltips)
        {
            if (Translation.IsRussianLanguage && ProjectTRuConfig.Instance.NewVanillaTranslation)
            {
                TooltipLine tooltipLine = tooltips.FirstOrDefault(x => x.Name == "ItemName");
                if(tooltipLine != null && item.prefix > 0)
                {
                    for (int i = 0; i < _prefixes.Length; i++)
                    {
                        if(_prefixes[i][0] == Regex.Split(tooltipLine.text, item.Name)[0])
                        {
                            tooltipLine.text = GetGenderedPrefix(_prefixes[i], item.type) + item.Name.ToLower();
                            return;
                        }
                    }
                }
            }
        }

        private string GetGenderedPrefix(string[] prefix, int id)
        {
            if (_typeW.Contains(id))
            {
                return prefix[1];
            }

            if (_typeU.Contains(id))
            {
                return prefix[2];
            }
            
            if (_typePl.Contains(id))
            {
                return prefix[3];
            }

            return prefix[0];
        }
    }
}