using System.Collections.Generic;
using CalamityRuTranslate.Mods.FargowiltasSouls;
using CalamityRuTranslate.Utilities;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityRuTranslate.Vanilla
{
    public class RussianPrefixOverhaul : GlobalItem
    {
        //Мужской, Женский, Средний, Множественный
        private static string[][] _prefixes = {
            new [] {"Искусный", "Искусная", "Искусное", "Искусные"},
            new [] {"Проворный", "Проворная", "Проворное", "Проворные"},
            new [] {"Надоедливый", "Надоедливая", "Надоедливое", "Надоедливые"},
            new [] {"Таинственный", "Таинственная", "Таинственное", "Таинственные"},
            new [] {"Укреплённый", "Укреплённая", "Укреплённое", "Укреплённые"},
            new [] {"Отвратительный", "Отвратительная", "Отвратительное", "Отвратительные"},
            new [] {"Неудобный", "Неудобная", "Неудобное", "Неудобные"},
            new [] {"Юркий", "Юркая", "Юркое", "Юркие"},
            new [] {"Сломанный", "Сломанная", "Сломанное", "Сломанные"},
            new [] {"Громоздкий", "Громоздкая", "Громоздкое", "Громоздкие"},
            new [] {"Небесный", "Небесная", "Небесное", "Небесные"},
            new [] {"Повреждённый", "Повреждённая", "Повреждённое", "Повреждённые"},
            new [] {"Опасный", "Опасная", "Опасное", "Опасные"},
            new [] {"Смертоносный", "Смертоносная", "Смертоносное", "Смертоносные"},
            new [] {"Демонический", "Демоническая", "Демоническое", "Демонические"},
            new [] {"Безумный", "Безумная", "Безумное", "Безумные"},
            new [] {"Притуплённый", "Притуплённая", "Притуплённое", "Притуплённые"},
            new [] {"Стремительный", "Стремительная", "Стремительное", "Стремительные"},
            new [] {"Неистовый", "Неистовая", "Неистовое", "Неистовые"},
            new [] {"Буйный", "Буйная", "Буйное", "Буйные"},
            new [] {"Яростный", "Яростная", "Яростное", "Яростные"},
            new [] {"Праведный", "Праведная", "Праведное", "Праведные"},
            new [] {"Охранный", "Охранная", "Охранное", "Охранные"},
            new [] {"Твёрдый", "Твёрдая", "Твёрдое", "Твёрдые"},
            new [] {"Поспешный", "Поспешная", "Поспешное", "Поспешные"},
            new [] {"Тяжёлый", "Тяжёлая", "Тяжёлое", "Тяжёлые"},
            new [] {"Пагубный", "Пагубная", "Пагубное", "Пагубные"},
            new [] {"Никчёмный", "Никчёмная", "Никчёмное", "Никчёмные"},
            new [] {"Непригодный", "Непригодная", "Непригодное", "Непригодные"},
            new [] {"Мощный", "Мощная", "Мощное", "Мощные"},
            new [] {"Устрашающий", "Устрашающая", "Устрашающее", "Устрашающие"},
            new [] {"Отважный", "Отважная", "Отважное", "Отважные"},
            new [] {"Зазубренный", "Зазубренная", "Зазубренное", "Зазубренные"},
            new [] {"Заточенный", "Заточенная", "Заточенное", "Заточенные"},
            new [] {"Большой", "Большая", "Большое", "Большие"},
            new [] {"Лентяйский", "Лентяйская", "Лентяйское", "Лентяйские"},
            new [] {"Легендарный", "Легендарная", "Легендарное", "Легендарные"},
            new [] {"Апатичный", "Апатичная", "Апатичное", "Апатичные"},
            new [] {"Лёгкий", "Лёгкая", "Лёгкое", "Лёгкие"},
            new [] {"Везучий", "Везучая", "Везучее", "Везучие"},
            new [] {"Маниакальный", "Маниакальная", "Маниакальное", "Маниакальные"},
            new [] {"Массивный", "Массивная", "Массивное", "Массивные"},
            new [] {"Умелый", "Умелая", "Умелое", "Умелые"},
            new [] {"Грозный", "Грозная", "Грозное", "Грозные"},
            new [] {"Убийственный", "Убийственная", "Убийственное", "Убийственные"},
            new [] {"Мистический", "Мистическая", "Мистическое", "Мистические"},
            new [] {"Загадочный", "Загадочная", "Загадочное", "Загадочные"},
            new [] {"Пакостный", "Пакостная", "Пакостное", "Пакостные"},
            new [] {"Шустрый", "Шустрая", "Шустрое", "Шустрые"},
            new [] {"Заострённый", "Заострённая", "Заострённое", "Заострённые"},
            new [] {"Точный", "Точная", "Точное", "Точные"},
            new [] {"Быстрый", "Быстрая", "Быстрое", "Быстрые"},
            new [] {"Скоростной", "Скоростная", "Скоростное", "Скоростные"},
            new [] {"Безудержный", "Безудержная", "Безудержное", "Безудержные"},
            new [] {"Безжалостный", "Безжалостная", "Безжалостное", "Безжалостные"},
            new [] {"Кровожадный", "Кровожадная", "Кровожадное", "Кровожадные"},
            new [] {"Позорный", "Позорная", "Позорное", "Позорные"},
            new [] {"Острый", "Острая", "Острое", "Острые"},
            new [] {"Некачественный", "Некачественная", "Некачественное", "Некачественные"},
            new [] {"Меткий", "Меткая", "Меткое", "Меткие"},
            new [] {"Медлительный", "Медлительная", "Медлительное", "Медлительные"},
            new [] {"Вялый", "Вялая", "Вялое", "Вялые"},
            new [] {"Маленький", "Маленькая", "Маленькое", "Маленькие"},
            new [] {"Шипастый", "Шипастая", "Шипастое", "Шипастые"},
            new [] {"Надёжный", "Надёжная", "Надёжное", "Надёжные"},
            new [] {"Усиленный", "Усиленная", "Усиленное", "Усиленные"},
            new [] {"Превосходный", "Превосходная", "Превосходное", "Превосходные"},
            new [] {"Запретный", "Запретная", "Запретное", "Запретные"},
            new [] {"Ужасный", "Ужасная", "Ужасное", "Ужасные"},
            new [] {"Крошечный", "Крошечная", "Крошечное", "Крошечные"},
            new [] {"Неудачный", "Неудачная", "Неудачное", "Неудачные"},
            new [] {"Неприятный", "Неприятная", "Неприятное", "Неприятные"},
            new [] {"Нереальный", "Нереальная", "Нереальное", "Нереальные"},
            new [] {"Жестокий", "Жестокая", "Жестокое", "Жестокие"},
            new [] {"Оберегающий", "Оберегающая", "Оберегающее", "Оберегающие"},
            new [] {"Слабый", "Слабая", "Слабое", "Слабые"},
            new [] {"Дикий", "Дикая", "Дикое", "Дикие"},
            new [] {"Пылкий", "Пылкая", "Пылкое", "Пылкие"},
            new [] {"Безупречный", "Безупречная", "Безупречное", "Безупречные"},
            new [] {"Обтекаемый", "Обтекаемая", "Обтекаемое", "Обтекаемые"},
            new [] {"Увесистый", "Увесистая", "Увесистое", "Увесистые"},
            new [] {"Могучий", "Могучая", "Могучее", "Могучие"},
            new [] {"Выдающийся", "Выдающаяся", "Выдающееся", "Выдающиеся"},
            new [] {"Свирепый", "Свирепая", "Свирепое", "Свирепые"},
            new [] {"Убойный", "Убойная", "Убойное", "Убойные"},
            new [] {"Радикальный", "Радикальная", "Радикальное", "Радикальные"},
            new [] {"Грубый", "Грубая", "Грубое", "Грубые"},
            new [] {"Хрупкий", "Хрупкая", "Хрупкое", "Хрупкие"},
            new [] {"Несбалансированный", "Несбалансированная", "Несбалансированное", "Несбалансированные"},
            new [] {"Тихий", "Тихая", "Тихое", "Тихие"},
            new [] {"Скрытый", "Скрытая", "Скрытое", "Скрытые"},
            new [] {"Замаскированный", "Замаскированная", "Замаскированное", "Замаскированные"},
            new [] {"Безмолвный", "Безмолвная", "Безмолвное", "Безмолвные"}
        };
        
        //Женский
        private static List<int?> _typeW = new List<int?>
        {
            ItemID.BoneGlove,
            ItemID.LuckyHorseshoe,
            ItemID.Ruler,
            ItemID.BlizzardinaBottle,
            ItemID.HighTestFishingLine,
            ItemID.AnglerEarring,
            ItemID.FrogLeg,
            ItemID.LaserRuler,
            ItemID.BalloonPufferfish,
            ItemID.RedString,
            ItemID.OrangeString,
            ItemID.YellowString,
            ItemID.LimeString,
            ItemID.GreenString,
            ItemID.TealString,
            ItemID.CyanString,
            ItemID.SkyBlueString,
            ItemID.BlueString,
            ItemID.PurpleString,
            ItemID.VioletString,
            ItemID.PinkString,
            ItemID.BrownString,
            ItemID.WhiteString,
            ItemID.RainbowString,
            ItemID.BlackString,
            ItemID.SandstorminaBottle,
            ItemID.FartinaJar,
            ItemID.HandWarmer,
            ItemID.Toolbox,
            ItemID.ObsidianRose,
            ItemID.PortableCementMixer,
            ItemID.GoblinTech,
            ItemID.MechanicalLens,
            ItemID.ObsidianHorseshoe,
            ItemID.MoonCharm,
            ItemID.SorcererEmblem,
            ItemID.WarriorEmblem,
            ItemID.RangerEmblem,
            ItemID.TitanGlove,
            ItemID.Blindfold,
            ItemID.TrifoldMap,
            ItemID.SandstorminaBalloon,
            ItemID.BlizzardinaBalloon,
            ItemID.FartInABalloon,
            ItemID.SummonerEmblem,
            ItemID.YoYoGlove,
            ItemID.NeptunesShell,
            ItemID.DiscountCard,
            ItemID.LuckyCoin,
            ItemID.PowerGlove,
            ItemID.CountercurseMantra,
            ItemID.AvengerEmblem,
            ItemID.Hoverboard,
            ItemID.CelestialEmblem,
            ItemID.MoonShell,
            ItemID.StarVeil,
            ItemID.MechanicalGlove,
            ItemID.DestroyerEmblem,
            ItemID.FireGauntlet,
            ItemID.BundleofBalloons,
            ItemID.CelestialShell,
            ItemID.BejeweledValkyrieWing,
            ItemID.LeinforsWings,
            ItemID.WingsNebula,
            ItemID.CobaltChainsaw,
            ItemID.MythrilChainsaw,
            ItemID.AdamantiteChainsaw,
            ItemID.FleshGrinder,
            ItemID.BloodLustCluster,
            ItemID.PalladiumChainsaw,
            ItemID.OrichalcumChainsaw,
            ItemID.TitaniumChainsaw,
            ItemID.ChlorophyteChainsaw,
            ItemID.SawtoothShark,
            ItemID.ButchersChainsaw,
            ItemID.CactusPickaxe,
            ItemID.TinPickaxe,
            ItemID.CopperPickaxe,
            ItemID.IronPickaxe,
            ItemID.LeadPickaxe,
            ItemID.SilverPickaxe,
            ItemID.BonePickaxe,
            ItemID.TungstenPickaxe,
            ItemID.CnadyCanePickaxe,
            ItemID.GoldPickaxe,
            ItemID.PlatinumPickaxe,
            ItemID.NightmarePickaxe,
            ItemID.DeathbringerPickaxe,
            ItemID.MoltenPickaxe,
            ItemID.ReaverShark,
            ItemID.CobaltPickaxe,
            ItemID.PalladiumPickaxe,
            ItemID.MythrilPickaxe,
            ItemID.OrichalcumPickaxe,
            ItemID.AdamantitePickaxe,
            ItemID.TitaniumPickaxe,
            ItemID.ChlorophytePickaxe,
            ItemID.SpectrePickaxe,
            ItemID.ShroomiteDiggingClaw,
            ItemID.VortexPickaxe,
            ItemID.NebulaPickaxe,
            ItemID.SolarFlarePickaxe,
            ItemID.StardustPickaxe,
            ItemID.Minishark,
            ItemID.Blowpipe,
            ItemID.Sickle,
            ItemID.Vilethorn,
            ItemID.SnowballCannon,
            ItemID.DD2LightningAuraT2Popper,
            ItemID.ZombieArm,
            ItemID.BladedGlove,
            ItemID.TheRottedFork,
            ItemID.TheMeatball,
            ItemID.Katana,
            ItemID.TaxCollectorsStickOfDoom,
            ItemID.CrimsonYoyo,
            ItemID.SpaceGun,
            ItemID.Muramasa,
            ItemID.ClockworkAssaultRifle,
            ItemID.Swordfish,
            ItemID.JungleYoyo,
            ItemID.DyeTradersScimitar,
            ItemID.WaspGun,
            ItemID.Starfury,
            ItemID.Valor,
            ItemID.BlueMoon,
            ItemID.PurpleClubberfish,
            ItemID.BookStaff,
            ItemID.Megashark,
            ItemID.MagicMissile,
            ItemID.LaserRifle,
            ItemID.CobaltNaginata,
            ItemID.BookofSkulls,
            ItemID.Sandgun,
            ItemID.MoltenFury,
            ItemID.MagicalHarp,
            ItemID.PalladiumPike,
            ItemID.Sunfury,
            ItemID.DemonScythe,
            ItemID.MythrilHalberd,
            ItemID.SlapHand,
            ItemID.OrichalcumHalberd,
            ItemID.AdamantiteGlaive,
            ItemID.PiranhaGun,
            ItemID.Flamelash,
            ItemID.Marrow,
            ItemID.KOCannon,
            ItemID.ElectrosphereLauncher,
            ItemID.ShadowFlameHexDoll,
            ItemID.NightsEdge,
            ItemID.IceSickle,
            ItemID.DD2FlameburstTowerT2Popper,
            ItemID.CandyCornRifle,
            ItemID.RainbowGun,
            ItemID.Xenopopper,
            ItemID.MedusaHead,
            ItemID.MonkStaffT2,
            ItemID.ToxicFlask,
            ItemID.ChlorophyteSaber,
            ItemID.MagnetSphere,
            ItemID.Cutlass,
            ItemID.Frostbrand,
            ItemID.ChargedBlasterCannon,
            ItemID.VortexBeater,
            ItemID.DartRifle,
            ItemID.StarCannon,
            ItemID.DeathSickle,
            ItemID.DD2ExplosiveTrapT2Popper,
            ItemID.DaoofPow,
            ItemID.ScourgeoftheCorruptor,
            ItemID.ApprenticeStaffT3,
            ItemID.SnowmanCannon,
            ItemID.DD2BallistraTowerT2Popper,
            ItemID.ObsidianSwordfish,
            ItemID.BubbleGun,
            ItemID.MonkStaffT3,
            ItemID.TrueNightsEdge,
            ItemID.LastPrism,
            ItemID.LunarFlareBook,
            ItemID.StarWrath,
            ItemID.DayBreak,
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ApprenticesEssence"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BarbariansEssence"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("OccultistsEssence"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SharpshootersEssence"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CosmoForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("EarthForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("LifeForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NatureForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ShadowForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SpiritForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TerraForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TimberForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WillForce"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AgitatingLens"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CelestialRune"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DubiousCircuitry"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("IceQueensCrown"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PumpkingsCape"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ReinforcedPlating"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SaucerControlConsole"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SinisterIcon"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SqueakyToy"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SupremeDeathbringerFairy"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ArchWizardsSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ColossusSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ConjuristsSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DimensionSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("EternitySoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FlightMasterySoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("GladiatorsSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MasochistSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SnipersSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SupersonicSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TerrariaSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TrawlerSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("UniverseSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WorldShaperSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BoneZone"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DestroyerGun"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FishStick"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FleshHand"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("Mahoguny"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TophatSquirrelWeapon"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PiranhaGunSummon"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WaspGunSummon"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DestroyerGun2"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DragonBreath2"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("HellZone"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SlimeSword"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ComputationOrb"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ParadoxWolfSoul"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MissDrakovisFishingPole"),
        };
        //Средний
        private static List<int?> _typeU = new List<int?>
        {
            ItemID.CloudinaBottle,
            ItemID.PanicNecklace,
            ItemID.WeatherRadio,
            ItemID.CordageGuide,
            ItemID.FishermansGuide,
            ItemID.TsunamiInABottle,
            ItemID.SharkToothNecklace,
            ItemID.JellyfishNecklace,
            ItemID.SweetheartNecklace,
            ItemID.PocketMirror,
            ItemID.DivingGear,
            ItemID.CloudinaBalloon,
            ItemID.ArmorBracing,
            ItemID.GoldRing,
            ItemID.CoinRing,
            ItemID.CharmofMyths,
            ItemID.GreedyRing,
            ItemID.PygmyNecklace,
            ItemID.Yoraiz0rWings,
            ItemID.Spear,
            ItemID.WoodYoyo,
            ItemID.Rally,
            ItemID.AntlionClaw,
            ItemID.RedRyder,
            ItemID.Blowgun,
            ItemID.DarkLance,
            ItemID.Uzi,
            ItemID.FalconBlade,
            ItemID.HelFire,
            ItemID.DD2SquireDemonSword,
            ItemID.DD2BetsyBow,
            ItemID.MushroomSpear,
            ItemID.Tsunami,
            ItemID.FireworksLauncher,
            ItemID.ValkyrieYoyo,
            ItemID.SpiritFlame,
            ItemID.SolarEruption,
            ItemID.NebulaBlaze,
            ItemID.SniperRifle,
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AdamantiteEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AncientCobaltEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AncientShadowEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AnglerEnchantment"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ApprenticeEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BeeEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BeetleEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BorealWoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CactusEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ChlorophyteEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CobaltEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CopperEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CrimsonEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DarkArtistEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("EbonwoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ForbiddenEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FossilEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FrostEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("GladiatorEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("GoldEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("HallowEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("HuntressEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("IronEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("JungleEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("LeadEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MeteorEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MinerEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MoltenEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MonkEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MythrilEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NebulaEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NecroEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NinjaEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ObsidianEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("OrichalcumEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PalladiumEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PalmWoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PearlwoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PlatinumEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PumpkinEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("RainEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("RedRidingEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("RichMahoganyEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ShadewoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ShadowEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ShinobiEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ShroomiteEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SilverEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SnowEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SolarEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SpectreEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SpiderEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SpookyEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SquireEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("StardustEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TikiEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TinEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TitaniumEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TungstenEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TurtleEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ValhallaKnightEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("VortexEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WizardEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WoodEnchant"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BetsysHeart"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("ConcentratedRainbowMatter"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("CorruptHeart"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("GuttedHeart"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("HeartoftheMasochist"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NecromanticBrew"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PungentEyeball"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("PureHeart"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("QueenStinger"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SparklingAdoration"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TimsConcoction"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("WyvernFeather"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("BrainStaff"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("DragonBreath"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TheSmallSting"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SparklingLove"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TheBigSting"),
        };
        //Множественный
        private static List<int?> _typePl = new List<int?>
        {
            ItemID.BrainOfConfusion,
            ItemID.CopperWatch,
            ItemID.SilverWatch,
            ItemID.TinWatch,
            ItemID.TungstenWatch,
            ItemID.GoldWatch,
            ItemID.HermesBoots,
            ItemID.Flipper,
            ItemID.Shackle,
            ItemID.PlatinumWatch,
            ItemID.IceSkates,
            ItemID.ClimbingClaws,
            ItemID.ShoeSpikes,
            ItemID.FlurryBoots,
            ItemID.SailfishBoots,
            ItemID.BrainOfConfusion,
            ItemID.MagicCuffs,
            ItemID.RocketBoots,
            ItemID.FeralClaws,
            ItemID.SpectreBoots,
            ItemID.WaterWalkingBoots,
            ItemID.FastClock,
            ItemID.Vitamins,
            ItemID.ObsidianWaterWalkingBoots,
            ItemID.FinWings,
            ItemID.DemonWings,
            ItemID.AngelWings,
            ItemID.ButterflyWings,
            ItemID.FairyWings,
            ItemID.HarpyWings,
            ItemID.BoneWings,
            ItemID.FlameWings,
            ItemID.FrozenWings,
            ItemID.LightningBoots,
            ItemID.LeafWings,
            ItemID.BatWings,
            ItemID.BeeWings,
            ItemID.FestiveWings,
            ItemID.CelestialCuffs,
            ItemID.PutridScent,
            ItemID.LavaWaders,
            ItemID.Tabi,
            ItemID.TatteredFairyWings,
            ItemID.SpookyWings,
            ItemID.FrostsparkBoots,
            ItemID.BeetleWings,
            ItemID.FlowerBoots,
            ItemID.GhostWings,
            ItemID.SteampunkWings,
            ItemID.MasterNinjaGear,
            ItemID.FishronWings,
            ItemID.MothronWings,
            ItemID.BetsyWings,
            ItemID.RedsWings,
            ItemID.DTownsWings,
            ItemID.WillsWings,
            ItemID.CrownosWings,
            ItemID.CenxsWings,
            ItemID.JimsWings,
            ItemID.SkiphsWings,
            ItemID.LokisWings,
            ItemID.ArkhalisWings,
            ItemID.WingsSolar,
            ItemID.WingsStardust,
            ItemID.StylistKilLaKillScissorsIWish,
            ItemID.VampireKnives,
            ItemID.ChainGuillotines,
            ItemID.FetidBaghnakhs,
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("AeolusBoots"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("EurusSock"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("FusedLens"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("MutantAntibodies"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("NymphsPerfume"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("SandsofTime"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("TwinRangs"),
            CoreFargowiltasSoulsTranslation.FargoSouls?.ItemType("GeminiGlaives"),
        };
        
        public override bool Autoload(ref string name)
        {
            On.Terraria.Item.AffixName += delegate(On.Terraria.Item.orig_AffixName orig, Item self)
            {
                if (!ProjectTRuConfig.Instance.NewVanillaTranslation && !Translation.IsRussianLanguage)
                    return orig.Invoke(self);

                if (self.prefix >= Lang.prefix.Length)
                    return self.Name;
                
                string prefix = Lang.prefix[self.prefix].Value;
                if (prefix == string.Empty)
                    return self.Name;

                for (int i = 0; i < _prefixes.Length; i++)
                {
                    if(_prefixes[i][0] == prefix)
                        return GetGenderedPrefix(_prefixes[i], self.type) + " " + self.Name.ToLower();
                }

                return prefix + " " + self.Name;
            };
            return base.Autoload(ref name);
        }

        private string GetGenderedPrefix(string[] prefix, int id)
        {
            if (_typeW.Contains(id))
                return prefix[1];

            if (_typeU.Contains(id))
                return prefix[2];

            if (_typePl.Contains(id))
                return prefix[3];

            return prefix[0];
        }
    }
}