using System.Collections.Generic;
using CalamityRuTranslate.Common;
using CalamityRuTranslate.Utilities;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace CalamityRuTranslate.Vanilla
{
    public class RussianPrefixOverhaul : GlobalItem
    {
        //Мужской, Женский, Средний, Множественный
        private static string[][] _prefixes = {
            new [] {"Искусный", "Искусная", "Искусное", "Искусные"},
            new [] {"Проворный", "Проворная", "Проворное", "Проворные"},
            new [] {"Надоедливый", "Надоедливая", "Надоедливое", "Надоедливые"},
            new [] {"Таинственный", "Таинственная", "Таинственное", "Таинственные"},
            new [] {"Укреплённый", "Укреплённая", "Укреплённое", "Укреплённые"},
            new [] {"Отвратительный", "Отвратительная", "Отвратительное", "Отвратительные"},
            new [] {"Неудобный", "Неудобная", "Неудобное", "Неудобные"},
            new [] {"Юркий", "Юркая", "Юркое", "Юркие"},
            new [] {"Сломанный", "Сломанная", "Сломанное", "Сломанные"},
            new [] {"Громоздкий", "Громоздкая", "Громоздкое", "Громоздкие"},
            new [] {"Небесный", "Небесная", "Небесное", "Небесные"},
            new [] {"Повреждённый", "Повреждённая", "Повреждённое", "Повреждённые"},
            new [] {"Опасный", "Опасная", "Опасное", "Опасные"},
            new [] {"Смертоносный", "Смертоносная", "Смертоносное", "Смертоносные"},
            new [] {"Демонический", "Демоническая", "Демоническое", "Демонические"},
            new [] {"Безумный", "Безумная", "Безумное", "Безумные"},
            new [] {"Притуплённый", "Притуплённая", "Притуплённое", "Притуплённые"},
            new [] {"Стремительный", "Стремительная", "Стремительное", "Стремительные"},
            new [] {"Неистовый", "Неистовая", "Неистовое", "Неистовые"},
            new [] {"Буйный", "Буйная", "Буйное", "Буйные"},
            new [] {"Яростный", "Яростная", "Яростное", "Яростные"},
            new [] {"Праведный", "Праведная", "Праведное", "Праведные"},
            new [] {"Охранный", "Охранная", "Охранное", "Охранные"},
            new [] {"Твёрдый", "Твёрдая", "Твёрдое", "Твёрдые"},
            new [] {"Поспешный", "Поспешная", "Поспешное", "Поспешные"},
            new [] {"Тяжёлый", "Тяжёлая", "Тяжёлое", "Тяжёлые"},
            new [] {"Пагубный", "Пагубная", "Пагубное", "Пагубные"},
            new [] {"Никчёмный", "Никчёмная", "Никчёмное", "Никчёмные"},
            new [] {"Непригодный", "Непригодная", "Непригодное", "Непригодные"},
            new [] {"Мощный", "Мощная", "Мощное", "Мощные"},
            new [] {"Устрашающий", "Устрашающая", "Устрашающее", "Устрашающие"},
            new [] {"Отважный", "Отважная", "Отважное", "Отважные"},
            new [] {"Зазубренный", "Зазубренная", "Зазубренное", "Зазубренные"},
            new [] {"Заточенный", "Заточенная", "Заточенное", "Заточенные"},
            new [] {"Большой", "Большая", "Большое", "Большие"},
            new [] {"Лентяйский", "Лентяйская", "Лентяйское", "Лентяйские"},
            new [] {"Легендарный", "Легендарная", "Легендарное", "Легендарные"},
            new [] {"Апатичный", "Апатичная", "Апатичное", "Апатичные"},
            new [] {"Лёгкий", "Лёгкая", "Лёгкое", "Лёгкие"},
            new [] {"Везучий", "Везучая", "Везучее", "Везучие"},
            new [] {"Маниакальный", "Маниакальная", "Маниакальное", "Маниакальные"},
            new [] {"Массивный", "Массивная", "Массивное", "Массивные"},
            new [] {"Умелый", "Умелая", "Умелое", "Умелые"},
            new [] {"Грозный", "Грозная", "Грозное", "Грозные"},
            new [] {"Убийственный", "Убийственная", "Убийственное", "Убийственные"},
            new [] {"Мистический", "Мистическая", "Мистическое", "Мистические"},
            new [] {"Загадочный", "Загадочная", "Загадочное", "Загадочные"},
            new [] {"Пакостный", "Пакостная", "Пакостное", "Пакостные"},
            new [] {"Шустрый", "Шустрая", "Шустрое", "Шустрые"},
            new [] {"Заострённый", "Заострённая", "Заострённое", "Заострённые"},
            new [] {"Точный", "Точная", "Точное", "Точные"},
            new [] {"Быстрый", "Быстрая", "Быстрое", "Быстрые"},
            new [] {"Скоростной", "Скоростная", "Скоростное", "Скоростные"},
            new [] {"Безудержный", "Безудержная", "Безудержное", "Безудержные"},
            new [] {"Безжалостный", "Безжалостная", "Безжалостное", "Безжалостные"},
            new [] {"Кровожадный", "Кровожадная", "Кровожадное", "Кровожадные"},
            new [] {"Позорный", "Позорная", "Позорное", "Позорные"},
            new [] {"Острый", "Острая", "Острое", "Острые"},
            new [] {"Некачественный", "Некачественная", "Некачественное", "Некачественные"},
            new [] {"Меткий", "Меткая", "Меткое", "Меткие"},
            new [] {"Медлительный", "Медлительная", "Медлительное", "Медлительные"},
            new [] {"Вялый", "Вялая", "Вялое", "Вялые"},
            new [] {"Маленький", "Маленькая", "Маленькое", "Маленькие"},
            new [] {"Шипастый", "Шипастая", "Шипастое", "Шипастые"},
            new [] {"Надёжный", "Надёжная", "Надёжное", "Надёжные"},
            new [] {"Усиленный", "Усиленная", "Усиленное", "Усиленные"},
            new [] {"Превосходный", "Превосходная", "Превосходное", "Превосходные"},
            new [] {"Запретный", "Запретная", "Запретное", "Запретные"},
            new [] {"Ужасный", "Ужасная", "Ужасное", "Ужасные"},
            new [] {"Крошечный", "Крошечная", "Крошечное", "Крошечные"},
            new [] {"Неудачный", "Неудачная", "Неудачное", "Неудачные"},
            new [] {"Неприятный", "Неприятная", "Неприятное", "Неприятные"},
            new [] {"Нереальный", "Нереальная", "Нереальное", "Нереальные"},
            new [] {"Жестокий", "Жестокая", "Жестокое", "Жестокие"},
            new [] {"Оберегающий", "Оберегающая", "Оберегающее", "Оберегающие"},
            new [] {"Слабый", "Слабая", "Слабое", "Слабые"},
            new [] {"Дикий", "Дикая", "Дикое", "Дикие"},
            new [] {"Пылкий", "Пылкая", "Пылкое", "Пылкие"},
            new [] {"Безупречный", "Безупречная", "Безупречное", "Безупречные"},
            new [] {"Обтекаемый", "Обтекаемая", "Обтекаемое", "Обтекаемые"},
            new [] {"Увесистый", "Увесистая", "Увесистое", "Увесистые"},
            new [] {"Могучий", "Могучая", "Могучее", "Могучие"},
            new [] {"Выдающийся", "Выдающаяся", "Выдающееся", "Выдающиеся"},
            new [] {"Свирепый", "Свирепая", "Свирепое", "Свирепые"},
            new [] {"Убойный", "Убойная", "Убойное", "Убойные"},
            new [] {"Радикальный", "Радикальная", "Радикальное", "Радикальные"},
            new [] {"Грубый", "Грубая", "Грубое", "Грубые"},
            new [] {"Хрупкий", "Хрупкая", "Хрупкое", "Хрупкие"},
            new [] {"Несбалансированный", "Несбалансированная", "Несбалансированное", "Несбалансированные"},
            new [] {"Тихий", "Тихая", "Тихое", "Тихие"},
            new [] {"Скрытый", "Скрытая", "Скрытое", "Скрытые"},
            new [] {"Замаскированный", "Замаскированная", "Замаскированное", "Замаскированные"},
            new [] {"Безмолвный", "Безмолвная", "Безмолвное", "Безмолвные"}
        };
        
        //Женский
        private static List<int?> _typeW = new List<int?>
        {
            ItemID.BoneGlove,
            ItemID.LuckyHorseshoe,
            ItemID.Ruler,
            ItemID.BlizzardinaBottle,
            ItemID.HighTestFishingLine,
            ItemID.AnglerEarring,
            ItemID.FrogLeg,
            ItemID.LaserRuler,
            ItemID.BalloonPufferfish,
            ItemID.RedString,
            ItemID.OrangeString,
            ItemID.YellowString,
            ItemID.LimeString,
            ItemID.GreenString,
            ItemID.TealString,
            ItemID.CyanString,
            ItemID.SkyBlueString,
            ItemID.BlueString,
            ItemID.PurpleString,
            ItemID.VioletString,
            ItemID.PinkString,
            ItemID.BrownString,
            ItemID.WhiteString,
            ItemID.RainbowString,
            ItemID.BlackString,
            ItemID.SandstorminaBottle,
            ItemID.FartinaJar,
            ItemID.HandWarmer,
            ItemID.Toolbox,
            ItemID.ObsidianRose,
            ItemID.PortableCementMixer,
            ItemID.GoblinTech,
            ItemID.MechanicalLens,
            ItemID.ObsidianHorseshoe,
            ItemID.MoonCharm,
            ItemID.SorcererEmblem,
            ItemID.WarriorEmblem,
            ItemID.RangerEmblem,
            ItemID.TitanGlove,
            ItemID.Blindfold,
            ItemID.TrifoldMap,
            ItemID.SandstorminaBalloon,
            ItemID.BlizzardinaBalloon,
            ItemID.FartInABalloon,
            ItemID.SummonerEmblem,
            ItemID.YoYoGlove,
            ItemID.NeptunesShell,
            ItemID.DiscountCard,
            ItemID.LuckyCoin,
            ItemID.PowerGlove,
            ItemID.CountercurseMantra,
            ItemID.AvengerEmblem,
            ItemID.Hoverboard,
            ItemID.CelestialEmblem,
            ItemID.MoonShell,
            ItemID.StarVeil,
            ItemID.MechanicalGlove,
            ItemID.DestroyerEmblem,
            ItemID.FireGauntlet,
            ItemID.BundleofBalloons,
            ItemID.CelestialShell,
            ItemID.BejeweledValkyrieWing,
            ItemID.LeinforsWings,
            ItemID.WingsNebula,
            ItemID.CobaltChainsaw,
            ItemID.MythrilChainsaw,
            ItemID.AdamantiteChainsaw,
            ItemID.FleshGrinder,
            ItemID.BloodLustCluster,
            ItemID.PalladiumChainsaw,
            ItemID.OrichalcumChainsaw,
            ItemID.TitaniumChainsaw,
            ItemID.ChlorophyteChainsaw,
            ItemID.SawtoothShark,
            ItemID.ButchersChainsaw,
            ItemID.CactusPickaxe,
            ItemID.TinPickaxe,
            ItemID.CopperPickaxe,
            ItemID.IronPickaxe,
            ItemID.LeadPickaxe,
            ItemID.SilverPickaxe,
            ItemID.BonePickaxe,
            ItemID.TungstenPickaxe,
            ItemID.CnadyCanePickaxe,
            ItemID.GoldPickaxe,
            ItemID.PlatinumPickaxe,
            ItemID.NightmarePickaxe,
            ItemID.DeathbringerPickaxe,
            ItemID.MoltenPickaxe,
            ItemID.ReaverShark,
            ItemID.CobaltPickaxe,
            ItemID.PalladiumPickaxe,
            ItemID.MythrilPickaxe,
            ItemID.OrichalcumPickaxe,
            ItemID.AdamantitePickaxe,
            ItemID.TitaniumPickaxe,
            ItemID.ChlorophytePickaxe,
            ItemID.SpectrePickaxe,
            ItemID.ShroomiteDiggingClaw,
            ItemID.VortexPickaxe,
            ItemID.NebulaPickaxe,
            ItemID.SolarFlarePickaxe,
            ItemID.StardustPickaxe,
            ItemID.Minishark,
            ItemID.Blowpipe,
            ItemID.Sickle,
            ItemID.Vilethorn,
            ItemID.SnowballCannon,
            ItemID.DD2LightningAuraT2Popper,
            ItemID.ZombieArm,
            ItemID.BladedGlove,
            ItemID.TheRottedFork,
            ItemID.TheMeatball,
            ItemID.Katana,
            ItemID.TaxCollectorsStickOfDoom,
            ItemID.CrimsonYoyo,
            ItemID.SpaceGun,
            ItemID.Muramasa,
            ItemID.ClockworkAssaultRifle,
            ItemID.Swordfish,
            ItemID.JungleYoyo,
            ItemID.DyeTradersScimitar,
            ItemID.WaspGun,
            ItemID.Starfury,
            ItemID.Valor,
            ItemID.BlueMoon,
            ItemID.PurpleClubberfish,
            ItemID.BookStaff,
            ItemID.Megashark,
            ItemID.MagicMissile,
            ItemID.LaserRifle,
            ItemID.CobaltNaginata,
            ItemID.BookofSkulls,
            ItemID.Sandgun,
            ItemID.MoltenFury,
            ItemID.MagicalHarp,
            ItemID.PalladiumPike,
            ItemID.Sunfury,
            ItemID.DemonScythe,
            ItemID.MythrilHalberd,
            ItemID.SlapHand,
            ItemID.OrichalcumHalberd,
            ItemID.AdamantiteGlaive,
            ItemID.PiranhaGun,
            ItemID.Flamelash,
            ItemID.Marrow,
            ItemID.KOCannon,
            ItemID.ElectrosphereLauncher,
            ItemID.ShadowFlameHexDoll,
            ItemID.NightsEdge,
            ItemID.IceSickle,
            ItemID.DD2FlameburstTowerT2Popper,
            ItemID.CandyCornRifle,
            ItemID.RainbowGun,
            ItemID.Xenopopper,
            ItemID.MedusaHead,
            ItemID.MonkStaffT2,
            ItemID.ToxicFlask,
            ItemID.ChlorophyteSaber,
            ItemID.MagnetSphere,
            ItemID.Cutlass,
            ItemID.Frostbrand,
            ItemID.ChargedBlasterCannon,
            ItemID.VortexBeater,
            ItemID.DartRifle,
            ItemID.StarCannon,
            ItemID.DeathSickle,
            ItemID.DD2ExplosiveTrapT2Popper,
            ItemID.DaoofPow,
            ItemID.ScourgeoftheCorruptor,
            ItemID.ApprenticeStaffT3,
            ItemID.SnowmanCannon,
            ItemID.DD2BallistraTowerT2Popper,
            ItemID.ObsidianSwordfish,
            ItemID.BubbleGun,
            ItemID.MonkStaffT3,
            ItemID.TrueNightsEdge,
            ItemID.LastPrism,
            ItemID.LunarFlareBook,
            ItemID.StarWrath,
            ItemID.DayBreak,
            ModsCall.FargoSouls?.ItemType("ApprenticesEssence"),
            ModsCall.FargoSouls?.ItemType("BarbariansEssence"),
            ModsCall.FargoSouls?.ItemType("OccultistsEssence"),
            ModsCall.FargoSouls?.ItemType("SharpshootersEssence"),
            ModsCall.FargoSouls?.ItemType("CosmoForce"),
            ModsCall.FargoSouls?.ItemType("EarthForce"),
            ModsCall.FargoSouls?.ItemType("LifeForce"),
            ModsCall.FargoSouls?.ItemType("NatureForce"),
            ModsCall.FargoSouls?.ItemType("ShadowForce"),
            ModsCall.FargoSouls?.ItemType("SpiritForce"),
            ModsCall.FargoSouls?.ItemType("TerraForce"),
            ModsCall.FargoSouls?.ItemType("TimberForce"),
            ModsCall.FargoSouls?.ItemType("WillForce"),
            ModsCall.FargoSouls?.ItemType("AgitatingLens"),
            ModsCall.FargoSouls?.ItemType("CelestialRune"),
            ModsCall.FargoSouls?.ItemType("DubiousCircuitry"),
            ModsCall.FargoSouls?.ItemType("IceQueensCrown"),
            ModsCall.FargoSouls?.ItemType("PumpkingsCape"),
            ModsCall.FargoSouls?.ItemType("ReinforcedPlating"),
            ModsCall.FargoSouls?.ItemType("SaucerControlConsole"),
            ModsCall.FargoSouls?.ItemType("SinisterIcon"),
            ModsCall.FargoSouls?.ItemType("SqueakyToy"),
            ModsCall.FargoSouls?.ItemType("SupremeDeathbringerFairy"),
            ModsCall.FargoSouls?.ItemType("ArchWizardsSoul"),
            ModsCall.FargoSouls?.ItemType("ColossusSoul"),
            ModsCall.FargoSouls?.ItemType("ConjuristsSoul"),
            ModsCall.FargoSouls?.ItemType("DimensionSoul"),
            ModsCall.FargoSouls?.ItemType("EternitySoul"),
            ModsCall.FargoSouls?.ItemType("FlightMasterySoul"),
            ModsCall.FargoSouls?.ItemType("GladiatorsSoul"),
            ModsCall.FargoSouls?.ItemType("MasochistSoul"),
            ModsCall.FargoSouls?.ItemType("SnipersSoul"),
            ModsCall.FargoSouls?.ItemType("SupersonicSoul"),
            ModsCall.FargoSouls?.ItemType("TerrariaSoul"),
            ModsCall.FargoSouls?.ItemType("TrawlerSoul"),
            ModsCall.FargoSouls?.ItemType("UniverseSoul"),
            ModsCall.FargoSouls?.ItemType("WorldShaperSoul"),
            ModsCall.FargoSouls?.ItemType("BoneZone"),
            ModsCall.FargoSouls?.ItemType("DestroyerGun"),
            ModsCall.FargoSouls?.ItemType("FishStick"),
            ModsCall.FargoSouls?.ItemType("FleshHand"),
            ModsCall.FargoSouls?.ItemType("Mahoguny"),
            ModsCall.FargoSouls?.ItemType("TophatSquirrelWeapon"),
            ModsCall.FargoSouls?.ItemType("PiranhaGunSummon"),
            ModsCall.FargoSouls?.ItemType("WaspGunSummon"),
            ModsCall.FargoSouls?.ItemType("DestroyerGun2"),
            ModsCall.FargoSouls?.ItemType("DragonBreath2"),
            ModsCall.FargoSouls?.ItemType("HellZone"),
            ModsCall.FargoSouls?.ItemType("SlimeSword"),
            ModsCall.FargoSouls?.ItemType("ComputationOrb"),
            ModsCall.FargoSouls?.ItemType("ParadoxWolfSoul"),
            ModsCall.FargoSouls?.ItemType("MissDrakovisFishingPole"),
            ModsCall.Calamity?.ItemType("Affliction"),
            ModsCall.Calamity?.ItemType("AlchemicalFlask"),
            ModsCall.Calamity?.ItemType("AlluringBait"),
            ModsCall.Calamity?.ItemType("AmbrosialAmpoule"),
            ModsCall.Calamity?.ItemType("AmidiasSpark"),
            ModsCall.Calamity?.ItemType("AquaticEmblem"),
            ModsCall.Calamity?.ItemType("AsgardianAegis"),
            ModsCall.Calamity?.ItemType("AsgardsValor"),
            ModsCall.Calamity?.ItemType("BloodstainedGlove"),
            ModsCall.Calamity?.ItemType("CalamityRing"),
            ModsCall.Calamity?.ItemType("CelestialJewel"),
            ModsCall.Calamity?.ItemType("CoinofDeceit"),
            ModsCall.Calamity?.ItemType("CorruptFlask"),
            ModsCall.Calamity?.ItemType("CrawCarapace"),
            ModsCall.Calamity?.ItemType("CrimsonFlask"),
            ModsCall.Calamity?.ItemType("CrownJewel"),
            ModsCall.Calamity?.ItemType("DaedalusEmblem"),
            ModsCall.Calamity?.ItemType("DragonScales"),
            ModsCall.Calamity?.ItemType("ElectriciansGlove"),
            ModsCall.Calamity?.ItemType("ElementalGauntlet"),
            ModsCall.Calamity?.ItemType("ElysianAegis"),
            ModsCall.Calamity?.ItemType("EnchantedPearl"),
            ModsCall.Calamity?.ItemType("FeatherCrown"),
            ModsCall.Calamity?.ItemType("FilthyGlove"),
            ModsCall.Calamity?.ItemType("FrostFlare"),
            ModsCall.Calamity?.ItemType("Gehenna"),
            ModsCall.Calamity?.ItemType("GiantPearl"),
            ModsCall.Calamity?.ItemType("GloveOfPrecision"),
            ModsCall.Calamity?.ItemType("GloveOfRecklessness"),
            ModsCall.Calamity?.ItemType("HallowedRune"),
            ModsCall.Calamity?.ItemType("HideofAstrumDeus"),
            ModsCall.Calamity?.ItemType("HoneyDew"),
            ModsCall.Calamity?.ItemType("InkBomb"),
            ModsCall.Calamity?.ItemType("Laudanum"),
            ModsCall.Calamity?.ItemType("LeviathanAmbergris"),
            ModsCall.Calamity?.ItemType("LivingDew"),
            ModsCall.Calamity?.ItemType("MoonstoneCrown"),
            ModsCall.Calamity?.ItemType("Nanotech"),
            ModsCall.Calamity?.ItemType("OldDie"),
            ModsCall.Calamity?.ItemType("PlaguedFuelPack"),
            ModsCall.Calamity?.ItemType("RadiantOoze"),
            ModsCall.Calamity?.ItemType("RogueEmblem"),
            ModsCall.Calamity?.ItemType("SandCloak"),
            ModsCall.Calamity?.ItemType("ScuttlersJewel"),
            ModsCall.Calamity?.ItemType("SeaShell"),
            ModsCall.Calamity?.ItemType("SigilofCalamitas"),
            ModsCall.Calamity?.ItemType("SpectralVeil"),
            ModsCall.Calamity?.ItemType("Sponge"),
            ModsCall.Calamity?.ItemType("UnstablePrism"),
            ModsCall.Calamity?.ItemType("VoidofExtinction"),
            ModsCall.Calamity?.ItemType("DiscordianWings"),
            ModsCall.Calamity?.ItemType("SoulofCryogen"),
            ModsCall.Calamity?.ItemType("PolarisParrotfish"),
            ModsCall.Calamity?.ItemType("DragoonDrizzlefish"),
            ModsCall.Calamity?.ItemType("Spadefish"),
            ModsCall.Calamity?.ItemType("SparklingEmpress"),
            ModsCall.Calamity?.ItemType("AstralPickaxe"),
            ModsCall.Calamity?.ItemType("BeastialPickaxe"),
            ModsCall.Calamity?.ItemType("BlossomPickaxe"),
            ModsCall.Calamity?.ItemType("FlamebeakHampick"),
            ModsCall.Calamity?.ItemType("GallantPickaxe"),
            ModsCall.Calamity?.ItemType("GreatbayPickaxe"),
            ModsCall.Calamity?.ItemType("ShardlightPickaxe"),
            ModsCall.Calamity?.ItemType("SkyfringePickaxe"),
            ModsCall.Calamity?.ItemType("WulfrumPickaxe"),
            ModsCall.Calamity?.ItemType("GalvanizingGlaive"),
            ModsCall.Calamity?.ItemType("LaserRifle"),
            ModsCall.Calamity?.ItemType("PlasmaCaster"),
            ModsCall.Calamity?.ItemType("PulseRifle"),
            ModsCall.Calamity?.ItemType("SystemBane"),
            ModsCall.Calamity?.ItemType("TeslaCannon"),
            ModsCall.Calamity?.ItemType("AcidGun"),
            ModsCall.Calamity?.ItemType("ApoctosisArray"),
            ModsCall.Calamity?.ItemType("ArcticBearPaw"),
            ModsCall.Calamity?.ItemType("Atlantis"),
            ModsCall.Calamity?.ItemType("BloodBath"),
            ModsCall.Calamity?.ItemType("CalamitasInferno"),
            ModsCall.Calamity?.ItemType("CoralSpout"),
            ModsCall.Calamity?.ItemType("CosmicRainbow"),
            ModsCall.Calamity?.ItemType("Cryophobia"),
            ModsCall.Calamity?.ItemType("DarkSpark"),
            ModsCall.Calamity?.ItemType("Eternity"),
            ModsCall.Calamity?.ItemType("FlareBolt"),
            ModsCall.Calamity?.ItemType("FrigidflashBolt"),
            ModsCall.Calamity?.ItemType("FrostBolt"),
            ModsCall.Calamity?.ItemType("GleamingMagnolia"),
            ModsCall.Calamity?.ItemType("HeliumFlash"),
            ModsCall.Calamity?.ItemType("Hematemesis"),
            ModsCall.Calamity?.ItemType("MadAlchemistsCocktailGlove"),
            ModsCall.Calamity?.ItemType("MagnaCannon"),
            ModsCall.Calamity?.ItemType("ManaRose"),
            ModsCall.Calamity?.ItemType("NuclearFury"),
            ModsCall.Calamity?.ItemType("PhantasmalFury"),
            ModsCall.Calamity?.ItemType("PlasmaRifle"),
            ModsCall.Calamity?.ItemType("PrimordialAncient"),
            ModsCall.Calamity?.ItemType("PrimordialEarth"),
            ModsCall.Calamity?.ItemType("Purge"),
            ModsCall.Calamity?.ItemType("RecitationoftheBeast"),
            ModsCall.Calamity?.ItemType("RelicofRuin"),
            ModsCall.Calamity?.ItemType("SanguineFlare"),
            ModsCall.Calamity?.ItemType("SkyGlaze"),
            ModsCall.Calamity?.ItemType("StratusSphere"),
            ModsCall.Calamity?.ItemType("TheWand"),
            ModsCall.Calamity?.ItemType("Thunderstorm"),
            ModsCall.Calamity?.ItemType("Vehemenc"),
            ModsCall.Calamity?.ItemType("VitriolicViper"),
            ModsCall.Calamity?.ItemType("VividClarity"),
            ModsCall.Calamity?.ItemType("WintersFury"),
            ModsCall.Calamity?.ItemType("AncientShiv"),
            ModsCall.Calamity?.ItemType("Aorta"),
            ModsCall.Calamity?.ItemType("AstralPike"),
            ModsCall.Calamity?.ItemType("AstralScythe"),
            ModsCall.Calamity?.ItemType("Ataraxia"),
            ModsCall.Calamity?.ItemType("Avalanche"),
            ModsCall.Calamity?.ItemType("Basher"),
            ModsCall.Calamity?.ItemType("BloodyEdge"),
            ModsCall.Calamity?.ItemType("Brimlash"),
            ModsCall.Calamity?.ItemType("BrimlashBuster"),
            ModsCall.Calamity?.ItemType("BurntSienna"),
            ModsCall.Calamity?.ItemType("Carnage"),
            ModsCall.Calamity?.ItemType("CausticEdge"),
            ModsCall.Calamity?.ItemType("ColdheartIcicle"),
            ModsCall.Calamity?.ItemType("CosmicShiv"),
            ModsCall.Calamity?.ItemType("DiseasedPike"),
            ModsCall.Calamity?.ItemType("DragonRage"),
            ModsCall.Calamity?.ItemType("Earth"),
            ModsCall.Calamity?.ItemType("EarthenPike"),
            ModsCall.Calamity?.ItemType("ElementalShortsword"),
            ModsCall.Calamity?.ItemType("EssenceFlayer"),
            ModsCall.Calamity?.ItemType("EutrophicScimitar"),
            ModsCall.Calamity?.ItemType("ForsakenSaber"),
            ModsCall.Calamity?.ItemType("FourSeasonsGalaxia"),
            ModsCall.Calamity?.ItemType("FulgurationHalberd"),
            ModsCall.Calamity?.ItemType("HolidayHalberd"),
            ModsCall.Calamity?.ItemType("LifefruitScythe"),
            ModsCall.Calamity?.ItemType("Lucrecia"),
            ModsCall.Calamity?.ItemType("Mariana"),
            ModsCall.Calamity?.ItemType("Mourningstar"),
            ModsCall.Calamity?.ItemType("Murasama"),
            ModsCall.Calamity?.ItemType("PerfectDark"),
            ModsCall.Calamity?.ItemType("Quagmire"),
            ModsCall.Calamity?.ItemType("Shimmerspark"),
            ModsCall.Calamity?.ItemType("SolarFlare"),
            ModsCall.Calamity?.ItemType("SoulEdge"),
            ModsCall.Calamity?.ItemType("StormSaber"),
            ModsCall.Calamity?.ItemType("Terracotta"),
            ModsCall.Calamity?.ItemType("TerraEdge"),
            ModsCall.Calamity?.ItemType("TerraShiv"),
            ModsCall.Calamity?.ItemType("TheMicrowave"),
            ModsCall.Calamity?.ItemType("ThePlaguebringer"),
            ModsCall.Calamity?.ItemType("TitanArm"),
            ModsCall.Calamity?.ItemType("Trinity"),
            ModsCall.Calamity?.ItemType("TrueBloodyEdge"),
            ModsCall.Calamity?.ItemType("CausticEdge"),
            ModsCall.Calamity?.ItemType("TyphonsGreed"),
            ModsCall.Calamity?.ItemType("UrchinFlail"),
            ModsCall.Calamity?.ItemType("VirulentKatana"),
            ModsCall.Calamity?.ItemType("AMR"),
            ModsCall.Calamity?.ItemType("Animosity"),
            ModsCall.Calamity?.ItemType("BarracudaGun"),
            ModsCall.Calamity?.ItemType("BrimstoneFury"),
            ModsCall.Calamity?.ItemType("ChickenCannon"),
            ModsCall.Calamity?.ItemType("ClamorRifle"),
            ModsCall.Calamity?.ItemType("ClaretCannon"),
            ModsCall.Calamity?.ItemType("Contagion"),
            ModsCall.Calamity?.ItemType("CoralCannon"),
            ModsCall.Calamity?.ItemType("DodusHandcannon"),
            ModsCall.Calamity?.ItemType("EternalBlizzard"),
            ModsCall.Calamity?.ItemType("FetidEmesis"),
            ModsCall.Calamity?.ItemType("FirestormCannon"),
            ModsCall.Calamity?.ItemType("FlakToxicannon"),
            ModsCall.Calamity?.ItemType("FlurrystormCannon"),
            ModsCall.Calamity?.ItemType("Galeforce"),
            ModsCall.Calamity?.ItemType("HalibutCannon"),
            ModsCall.Calamity?.ItemType("Infinity"),
            ModsCall.Calamity?.ItemType("Karasawa"),
            ModsCall.Calamity?.ItemType("MagnomalyCannon"),
            ModsCall.Calamity?.ItemType("Malevolence"),
            ModsCall.Calamity?.ItemType("MineralMortar"),
            ModsCall.Calamity?.ItemType("Onyxia"),
            ModsCall.Calamity?.ItemType("PristineFury"),
            ModsCall.Calamity?.ItemType("RaidersGlory"),
            ModsCall.Calamity?.ItemType("SandstormGun"),
            ModsCall.Calamity?.ItemType("SpectralstormCannon"),
            ModsCall.Calamity?.ItemType("SpectreRifle"),
            ModsCall.Calamity?.ItemType("StarCannonEX"),
            ModsCall.Calamity?.ItemType("StarfleetMK2"),
            ModsCall.Calamity?.ItemType("StellarCannon"),
            ModsCall.Calamity?.ItemType("StormSurge"),
            ModsCall.Calamity?.ItemType("SulphuricAcidCannon"),
            ModsCall.Calamity?.ItemType("TheBallista"),
            ModsCall.Calamity?.ItemType("ThePack"),
            ModsCall.Calamity?.ItemType("Ultima"),
            ModsCall.Calamity?.ItemType("AcidicRainBarrel"),
            ModsCall.Calamity?.ItemType("BallisticPoisonBomb"),
            ModsCall.Calamity?.ItemType("BlastBarrel"),
            ModsCall.Calamity?.ItemType("BrackishFlask"),
            ModsCall.Calamity?.ItemType("Cinquedea"),
            ModsCall.Calamity?.ItemType("ConsecratedWater"),
            ModsCall.Calamity?.ItemType("ContaminatedBile"),
            ModsCall.Calamity?.ItemType("CrushsawCrasher"),
            ModsCall.Calamity?.ItemType("DeepSeaDumbbell"),
            ModsCall.Calamity?.ItemType("DesecratedWater"),
            ModsCall.Calamity?.ItemType("DuststormInABottle"),
            ModsCall.Calamity?.ItemType("FrostcrushValari"),
            ModsCall.Calamity?.ItemType("Hypothermia"),
            ModsCall.Calamity?.ItemType("Kylie"),
            ModsCall.Calamity?.ItemType("Lionfish"),
            ModsCall.Calamity?.ItemType("Penumbra"),
            ModsCall.Calamity?.ItemType("RadiantStar"),
            ModsCall.Calamity?.ItemType("ScarletDevil"),
            ModsCall.Calamity?.ItemType("SeafoamBomb"),
            ModsCall.Calamity?.ItemType("SealedSingularity"),
            ModsCall.Calamity?.ItemType("SlickCane"),
            ModsCall.Calamity?.ItemType("StarofDestruction"),
            ModsCall.Calamity?.ItemType("StormfrontRazor"),
            ModsCall.Calamity?.ItemType("Supernova"),
            ModsCall.Calamity?.ItemType("TimeBolt"),
            ModsCall.Calamity?.ItemType("Turbulance"),
            ModsCall.Calamity?.ItemType("AncientIceChunk"),
            ModsCall.Calamity?.ItemType("CadaverousCarrion"),
            ModsCall.Calamity?.ItemType("ColdDivinity"),
            ModsCall.Calamity?.ItemType("Cosmilamp"),
            ModsCall.Calamity?.ItemType("MagicalConch"),
            ModsCall.Calamity?.ItemType("ResurrectionButterfly"),
            ModsCall.Calamity?.ItemType("SarosPossession"),
        };
        //Средний
        private static List<int?> _typeU = new List<int?>
        {
            ItemID.CloudinaBottle,
            ItemID.PanicNecklace,
            ItemID.WeatherRadio,
            ItemID.CordageGuide,
            ItemID.FishermansGuide,
            ItemID.TsunamiInABottle,
            ItemID.SharkToothNecklace,
            ItemID.JellyfishNecklace,
            ItemID.SweetheartNecklace,
            ItemID.PocketMirror,
            ItemID.DivingGear,
            ItemID.CloudinaBalloon,
            ItemID.ArmorBracing,
            ItemID.GoldRing,
            ItemID.CoinRing,
            ItemID.CharmofMyths,
            ItemID.GreedyRing,
            ItemID.PygmyNecklace,
            ItemID.Yoraiz0rWings,
            ItemID.Spear,
            ItemID.WoodYoyo,
            ItemID.Rally,
            ItemID.AntlionClaw,
            ItemID.RedRyder,
            ItemID.Blowgun,
            ItemID.DarkLance,
            ItemID.Uzi,
            ItemID.FalconBlade,
            ItemID.HelFire,
            ItemID.DD2SquireDemonSword,
            ItemID.DD2BetsyBow,
            ItemID.MushroomSpear,
            ItemID.Tsunami,
            ItemID.FireworksLauncher,
            ItemID.ValkyrieYoyo,
            ItemID.SpiritFlame,
            ItemID.SolarEruption,
            ItemID.NebulaBlaze,
            ItemID.SniperRifle,
            ModsCall.FargoSouls?.ItemType("AdamantiteEnchant"),
            ModsCall.FargoSouls?.ItemType("AncientCobaltEnchant"),
            ModsCall.FargoSouls?.ItemType("AncientShadowEnchant"),
            ModsCall.FargoSouls?.ItemType("AnglerEnchantment"),
            ModsCall.FargoSouls?.ItemType("ApprenticeEnchant"),
            ModsCall.FargoSouls?.ItemType("BeeEnchant"),
            ModsCall.FargoSouls?.ItemType("BeetleEnchant"),
            ModsCall.FargoSouls?.ItemType("BorealWoodEnchant"),
            ModsCall.FargoSouls?.ItemType("CactusEnchant"),
            ModsCall.FargoSouls?.ItemType("ChlorophyteEnchant"),
            ModsCall.FargoSouls?.ItemType("CobaltEnchant"),
            ModsCall.FargoSouls?.ItemType("CopperEnchant"),
            ModsCall.FargoSouls?.ItemType("CrimsonEnchant"),
            ModsCall.FargoSouls?.ItemType("DarkArtistEnchant"),
            ModsCall.FargoSouls?.ItemType("EbonwoodEnchant"),
            ModsCall.FargoSouls?.ItemType("ForbiddenEnchant"),
            ModsCall.FargoSouls?.ItemType("FossilEnchant"),
            ModsCall.FargoSouls?.ItemType("FrostEnchant"),
            ModsCall.FargoSouls?.ItemType("GladiatorEnchant"),
            ModsCall.FargoSouls?.ItemType("GoldEnchant"),
            ModsCall.FargoSouls?.ItemType("HallowEnchant"),
            ModsCall.FargoSouls?.ItemType("HuntressEnchant"),
            ModsCall.FargoSouls?.ItemType("IronEnchant"),
            ModsCall.FargoSouls?.ItemType("JungleEnchant"),
            ModsCall.FargoSouls?.ItemType("LeadEnchant"),
            ModsCall.FargoSouls?.ItemType("MeteorEnchant"),
            ModsCall.FargoSouls?.ItemType("MinerEnchant"),
            ModsCall.FargoSouls?.ItemType("MoltenEnchant"),
            ModsCall.FargoSouls?.ItemType("MonkEnchant"),
            ModsCall.FargoSouls?.ItemType("MythrilEnchant"),
            ModsCall.FargoSouls?.ItemType("NebulaEnchant"),
            ModsCall.FargoSouls?.ItemType("NecroEnchant"),
            ModsCall.FargoSouls?.ItemType("NinjaEnchant"),
            ModsCall.FargoSouls?.ItemType("ObsidianEnchant"),
            ModsCall.FargoSouls?.ItemType("OrichalcumEnchant"),
            ModsCall.FargoSouls?.ItemType("PalladiumEnchant"),
            ModsCall.FargoSouls?.ItemType("PalmWoodEnchant"),
            ModsCall.FargoSouls?.ItemType("PearlwoodEnchant"),
            ModsCall.FargoSouls?.ItemType("PlatinumEnchant"),
            ModsCall.FargoSouls?.ItemType("PumpkinEnchant"),
            ModsCall.FargoSouls?.ItemType("RainEnchant"),
            ModsCall.FargoSouls?.ItemType("RedRidingEnchant"),
            ModsCall.FargoSouls?.ItemType("RichMahoganyEnchant"),
            ModsCall.FargoSouls?.ItemType("ShadewoodEnchant"),
            ModsCall.FargoSouls?.ItemType("ShadowEnchant"),
            ModsCall.FargoSouls?.ItemType("ShinobiEnchant"),
            ModsCall.FargoSouls?.ItemType("ShroomiteEnchant"),
            ModsCall.FargoSouls?.ItemType("SilverEnchant"),
            ModsCall.FargoSouls?.ItemType("SnowEnchant"),
            ModsCall.FargoSouls?.ItemType("SolarEnchant"),
            ModsCall.FargoSouls?.ItemType("SpectreEnchant"),
            ModsCall.FargoSouls?.ItemType("SpiderEnchant"),
            ModsCall.FargoSouls?.ItemType("SpookyEnchant"),
            ModsCall.FargoSouls?.ItemType("SquireEnchant"),
            ModsCall.FargoSouls?.ItemType("StardustEnchant"),
            ModsCall.FargoSouls?.ItemType("TikiEnchant"),
            ModsCall.FargoSouls?.ItemType("TinEnchant"),
            ModsCall.FargoSouls?.ItemType("TitaniumEnchant"),
            ModsCall.FargoSouls?.ItemType("TungstenEnchant"),
            ModsCall.FargoSouls?.ItemType("TurtleEnchant"),
            ModsCall.FargoSouls?.ItemType("ValhallaKnightEnchant"),
            ModsCall.FargoSouls?.ItemType("VortexEnchant"),
            ModsCall.FargoSouls?.ItemType("WizardEnchant"),
            ModsCall.FargoSouls?.ItemType("WoodEnchant"),
            ModsCall.FargoSouls?.ItemType("BetsysHeart"),
            ModsCall.FargoSouls?.ItemType("ConcentratedRainbowMatter"),
            ModsCall.FargoSouls?.ItemType("CorruptHeart"),
            ModsCall.FargoSouls?.ItemType("GuttedHeart"),
            ModsCall.FargoSouls?.ItemType("HeartoftheMasochist"),
            ModsCall.FargoSouls?.ItemType("NecromanticBrew"),
            ModsCall.FargoSouls?.ItemType("PungentEyeball"),
            ModsCall.FargoSouls?.ItemType("PureHeart"),
            ModsCall.FargoSouls?.ItemType("QueenStinger"),
            ModsCall.FargoSouls?.ItemType("SparklingAdoration"),
            ModsCall.FargoSouls?.ItemType("TimsConcoction"),
            ModsCall.FargoSouls?.ItemType("WyvernFeather"),
            ModsCall.FargoSouls?.ItemType("BrainStaff"),
            ModsCall.FargoSouls?.ItemType("DragonBreath"),
            ModsCall.FargoSouls?.ItemType("TheSmallSting"),
            ModsCall.FargoSouls?.ItemType("SparklingLove"),
            ModsCall.FargoSouls?.ItemType("TheBigSting"),
            ModsCall.Calamity?.ItemType("AbyssalDivingGear"),
            ModsCall.Calamity?.ItemType("AbyssalMirror"),
            ModsCall.Calamity?.ItemType("AncientFossil"),
            ModsCall.Calamity?.ItemType("AnechoicPlating"),
            ModsCall.Calamity?.ItemType("BlazingCore"),
            ModsCall.Calamity?.ItemType("BloodflareCore"),
            ModsCall.Calamity?.ItemType("CoreOfTheBloodGod"),
            ModsCall.Calamity?.ItemType("DarkSunRing"),
            ModsCall.Calamity?.ItemType("DraedonsHeart"),
            ModsCall.Calamity?.ItemType("EclipseMirror"),
            ModsCall.Calamity?.ItemType("EyeoftheStorm"),
            ModsCall.Calamity?.ItemType("HarpyRing"),
            ModsCall.Calamity?.ItemType("HeartofDarkness"),
            ModsCall.Calamity?.ItemType("HotE"),
            ModsCall.Calamity?.ItemType("HowlsHeart"),
            ModsCall.Calamity?.ItemType("LeadCore"),
            ModsCall.Calamity?.ItemType("LifeJelly"),
            ModsCall.Calamity?.ItemType("ManaJelly"),
            ModsCall.Calamity?.ItemType("MirageMirror"),
            ModsCall.Calamity?.ItemType("NebulousCore"),
            ModsCall.Calamity?.ItemType("NecklaceofVexation"),
            ModsCall.Calamity?.ItemType("PermafrostsConcoction"),
            ModsCall.Calamity?.ItemType("ReaperToothNecklace"),
            ModsCall.Calamity?.ItemType("SirensHeart"),
            ModsCall.Calamity?.ItemType("StarbusterCore"),
            ModsCall.Calamity?.ItemType("StatisBlessing"),
            ModsCall.Calamity?.ItemType("StatisCurse"),
            ModsCall.Calamity?.ItemType("TheAmalgam"),
            ModsCall.Calamity?.ItemType("TheCommunity"),
            ModsCall.Calamity?.ItemType("ToxicHeart"),
            ModsCall.Calamity?.ItemType("VitalJelly"),
            ModsCall.Calamity?.ItemType("VoltaicJelly"),
            ModsCall.Calamity?.ItemType("BurningSea"),
            ModsCall.Calamity?.ItemType("DivineRetribution"),
            ModsCall.Calamity?.ItemType("Effervescence"),
            ModsCall.Calamity?.ItemType("EyeofMagnus"),
            ModsCall.Calamity?.ItemType("FatesReveal"),
            ModsCall.Calamity?.ItemType("ForbiddenSun"),
            ModsCall.Calamity?.ItemType("HadopelagicEcho"),
            ModsCall.Calamity?.ItemType("Keelhaul"),
            ModsCall.Calamity?.ItemType("LightGodsBrilliance"),
            ModsCall.Calamity?.ItemType("MagneticMeltdown"),
            ModsCall.Calamity?.ItemType("RougeSlash"),
            ModsCall.Calamity?.ItemType("SirensSong"),
            ModsCall.Calamity?.ItemType("UndinesRetribution"),
            ModsCall.Calamity?.ItemType("Aftershock"),
            ModsCall.Calamity?.ItemType("Brimlance"),
            ModsCall.Calamity?.ItemType("Devastation"),
            ModsCall.Calamity?.ItemType("DevilsDevastation"),
            ModsCall.Calamity?.ItemType("DraconicDestruction"),
            ModsCall.Calamity?.ItemType("ExsanguinationLance"),
            ModsCall.Calamity?.ItemType("GoldplumeSpear"),
            ModsCall.Calamity?.ItemType("HellionFlowerSpear"),
            ModsCall.Calamity?.ItemType("LionHeart"),
            ModsCall.Calamity?.ItemType("MarniteSpear"),
            ModsCall.Calamity?.ItemType("RedSun"),
            ModsCall.Calamity?.ItemType("SpatialLance"),
            ModsCall.Calamity?.ItemType("StarnightLance"),
            ModsCall.Calamity?.ItemType("StellarContemptMelee"),
            ModsCall.Calamity?.ItemType("TerraLance"),
            ModsCall.Calamity?.ItemType("TheEyeofCalamitas"),
            ModsCall.Calamity?.ItemType("Tumbleweed"),
            ModsCall.Calamity?.ItemType("UrchinSpear"),
            ModsCall.Calamity?.ItemType("Whirlpool"),
            ModsCall.Calamity?.ItemType("AcesHigh"),
            ModsCall.Calamity?.ItemType("Aeries"),
            ModsCall.Calamity?.ItemType("Alluvion"),
            ModsCall.Calamity?.ItemType("AstrealDefeat"),
            ModsCall.Calamity?.ItemType("BrimstoneFlamesprayer"),
            ModsCall.Calamity?.ItemType("CleansingBlaze"),
            ModsCall.Calamity?.ItemType("DaemonsFlame"),
            ModsCall.Calamity?.ItemType("DragonsBreath"),
            ModsCall.Calamity?.ItemType("ElementalEruption"),
            ModsCall.Calamity?.ItemType("PlanetaryAnnihilation"),
            ModsCall.Calamity?.ItemType("SeasSearing"),
            ModsCall.Calamity?.ItemType("BouncingEyeball"),
            ModsCall.Calamity?.ItemType("EclipsesFall"),
            ModsCall.Calamity?.ItemType("Equanimity"),
            ModsCall.Calamity?.ItemType("IchorSpear"),
            ModsCall.Calamity?.ItemType("ProfanedTrident"),
            ModsCall.Calamity?.ItemType("ShatteredSun"),
            ModsCall.Calamity?.ItemType("SpearofDestiny"),
            ModsCall.Calamity?.ItemType("SpearofPaleolith"),
            ModsCall.Calamity?.ItemType("StellarContemptRogue"),
            ModsCall.Calamity?.ItemType("Valediction"),
            ModsCall.Calamity?.ItemType("GammaHeart"),
            ModsCall.Calamity?.ItemType("IgneousExaltation"),
            ModsCall.Calamity?.ItemType("PrototypeAndromechaRing"),
        };
        //Множественный
        private static List<int?> _typePl = new List<int?>
        {
            ItemID.BrainOfConfusion,
            ItemID.CopperWatch,
            ItemID.SilverWatch,
            ItemID.TinWatch,
            ItemID.TungstenWatch,
            ItemID.GoldWatch,
            ItemID.HermesBoots,
            ItemID.Flipper,
            ItemID.Shackle,
            ItemID.PlatinumWatch,
            ItemID.IceSkates,
            ItemID.ClimbingClaws,
            ItemID.ShoeSpikes,
            ItemID.FlurryBoots,
            ItemID.SailfishBoots,
            ItemID.BrainOfConfusion,
            ItemID.MagicCuffs,
            ItemID.RocketBoots,
            ItemID.FeralClaws,
            ItemID.SpectreBoots,
            ItemID.WaterWalkingBoots,
            ItemID.FastClock,
            ItemID.Vitamins,
            ItemID.ObsidianWaterWalkingBoots,
            ItemID.FinWings,
            ItemID.DemonWings,
            ItemID.AngelWings,
            ItemID.ButterflyWings,
            ItemID.FairyWings,
            ItemID.HarpyWings,
            ItemID.BoneWings,
            ItemID.FlameWings,
            ItemID.FrozenWings,
            ItemID.LightningBoots,
            ItemID.LeafWings,
            ItemID.BatWings,
            ItemID.BeeWings,
            ItemID.FestiveWings,
            ItemID.CelestialCuffs,
            ItemID.PutridScent,
            ItemID.LavaWaders,
            ItemID.Tabi,
            ItemID.TatteredFairyWings,
            ItemID.SpookyWings,
            ItemID.FrostsparkBoots,
            ItemID.BeetleWings,
            ItemID.FlowerBoots,
            ItemID.GhostWings,
            ItemID.SteampunkWings,
            ItemID.MasterNinjaGear,
            ItemID.FishronWings,
            ItemID.MothronWings,
            ItemID.BetsyWings,
            ItemID.RedsWings,
            ItemID.DTownsWings,
            ItemID.WillsWings,
            ItemID.CrownosWings,
            ItemID.CenxsWings,
            ItemID.JimsWings,
            ItemID.SkiphsWings,
            ItemID.LokisWings,
            ItemID.ArkhalisWings,
            ItemID.WingsSolar,
            ItemID.WingsStardust,
            ItemID.StylistKilLaKillScissorsIWish,
            ItemID.VampireKnives,
            ItemID.ChainGuillotines,
            ItemID.FetidBaghnakhs,
            ModsCall.FargoSouls?.ItemType("AeolusBoots"),
            ModsCall.FargoSouls?.ItemType("EurusSock"),
            ModsCall.FargoSouls?.ItemType("FusedLens"),
            ModsCall.FargoSouls?.ItemType("MutantAntibodies"),
            ModsCall.FargoSouls?.ItemType("NymphsPerfume"),
            ModsCall.FargoSouls?.ItemType("SandsofTime"),
            ModsCall.FargoSouls?.ItemType("TwinRangs"),
            ModsCall.FargoSouls?.ItemType("GeminiGlaives"),
            ModsCall.Calamity?.ItemType("AngelTreads"),
            ModsCall.Calamity?.ItemType("DarkGodsSheath"),
            ModsCall.Calamity?.ItemType("IronBoots"),
            ModsCall.Calamity?.ItemType("SilencingSheath"),
            ModsCall.Calamity?.ItemType("StressPills"),
            ModsCall.Calamity?.ItemType("Popo"),
            ModsCall.Calamity?.ItemType("CelestialTracers"),
            ModsCall.Calamity?.ItemType("DrewsWings"),
            ModsCall.Calamity?.ItemType("ElysianTracers"),
            ModsCall.Calamity?.ItemType("ElysianWings"),
            ModsCall.Calamity?.ItemType("HadarianWings"),
            ModsCall.Calamity?.ItemType("InfinityBoots"),
            ModsCall.Calamity?.ItemType("SilvaWings"),
            ModsCall.Calamity?.ItemType("SkylineWings"),
            ModsCall.Calamity?.ItemType("StarlightWings"),
            ModsCall.Calamity?.ItemType("TarragonWings"),
            ModsCall.Calamity?.ItemType("XerocWings"),
            ModsCall.Calamity?.ItemType("SnakeEyes"),
            ModsCall.Calamity?.ItemType("DemonicPitchfork"),
            ModsCall.Calamity?.ItemType("Miasma"),
            ModsCall.Calamity?.ItemType("ShiftingSands"),
            ModsCall.Calamity?.ItemType("SlitheringEels"),
            ModsCall.Calamity?.ItemType("TearsofHeaven"),
            ModsCall.Calamity?.ItemType("Tradewinds"),
            ModsCall.Calamity?.ItemType("Viscera"),
            ModsCall.Calamity?.ItemType("EmpyreanKnives"),
            ModsCall.Calamity?.ItemType("MandibleClaws"),
            ModsCall.Calamity?.ItemType("MantisClaws"),
            ModsCall.Calamity?.ItemType("MonstrousKnives"),
            ModsCall.Calamity?.ItemType("MycelialClaws"),
            ModsCall.Calamity?.ItemType("RoyalKnivesMelee"),
            ModsCall.Calamity?.ItemType("TenebreusTides"),
            ModsCall.Calamity?.ItemType("TheBurningSky"),
            ModsCall.Calamity?.ItemType("TheEmpyrean"),
            ModsCall.Calamity?.ItemType("EmpyreanKnivesThrown"),
            ModsCall.Calamity?.ItemType("JawsOfOblivion"),
            ModsCall.Calamity?.ItemType("LeviathanTeeth"),
            ModsCall.Calamity?.ItemType("RoyalKnives"),
            ModsCall.Calamity?.ItemType("SkyfinBombers"),
            ModsCall.Calamity?.ItemType("TerrorTalons"),
            ModsCall.Calamity?.ItemType("TotalityBreakers"),
        };
        
        public override bool Autoload(ref string name)
        {
            On.Terraria.Item.AffixName += delegate(On.Terraria.Item.orig_AffixName orig, Item self)
            {
                if (!ProjectTRuConfig.Instance.NewVanillaTranslation || !Translation.IsRussianLanguage)
                    return orig.Invoke(self);

                if (self.prefix >= Lang.prefix.Length)
                    return self.Name;
                
                string prefix = Lang.prefix[self.prefix].Value;
                if (prefix == string.Empty)
                    return self.Name;

                for (int i = 0; i < _prefixes.Length; i++)
                {
                    if(_prefixes[i][0] == prefix)
                        return GetGenderedPrefix(_prefixes[i], self.type) + " " + self.Name.ToLower();
                }

                return prefix + " " + self.Name;
            };
            return base.Autoload(ref name);
        }

        private string GetGenderedPrefix(string[] prefix, int id)
        {
            if (_typeW.Contains(id))
                return prefix[1];

            if (_typeU.Contains(id))
                return prefix[2];

            if (_typePl.Contains(id))
                return prefix[3];

            return prefix[0];
        }
    }
}