using System.Collections.Generic;
using CalamityRuTranslate.Common;
using Terraria.ID;

namespace CalamityRuTranslate.Vanilla
{
    public class RussianPrefixOverhaul
    {
        //Мужской, Женский, Средний, Множественный
        public static string[][] Prefixes = {
            new [] {"Тупой", "Тупая", "Тупое", "Тупые"},
			new [] {"Несчастный", "Несчастная", "Несчастное", "Несчастные"},
			new [] {"Громоздкий", "Громоздкая", "Громоздкое", "Громоздкие"},
			new [] {"Позорный", "Позорная", "Позорное", "Позорные"},
			new [] {"Тяжёлый", "Тяжёлая", "Тяжёлое", "Тяжёлые"},
			new [] {"Лёгкий", "Лёгкая", "Лёгкое", "Лёгкие"},
			new [] {"Прицельный", "Прицельная", "Прицельное", "Прицельные"},
			new [] {"Скоростной", "Скоростная", "Скоростное", "Скоростные"},
			new [] {"Стремительный", "Стремительная", "Стремительное", "Стремительные"},
			new [] {"Пугающий", "Пугающая", "Пугающее", "Пугающие"},
			new [] {"Смертоносный", "Смертоносная", "Смертоносное", "Смертоносные"},
			new [] {"Стойкий", "Стойкая", "Стойкое", "Стойкие"},
			new [] {"Отвратительный", "Отвратительная", "Отвратительное", "Отвратительные"},
			new [] {"Сонный", "Сонная", "Сонное", "Сонные"},
			new [] {"Неудобный", "Неудобная", "Неудобное", "Неудобные"},
			new [] {"Мощный", "Мощная", "Мощное", "Мощные"},
			new [] {"Мистический", "Мистическая", "Мистическое", "Мистические"},
			new [] {"Искусный", "Искусная", "Искусное", "Искусные"},
			new [] {"Мастерский", "Мастерская", "Мастерское", "Мастерские"},
			new [] {"Неумелый", "Неумелая", "Неумелое", "Неумелые"},
			new [] {"Массивный", "Массивная", "Массивное", "Массивные"},
			new [] {"Неотёсанный", "Неотёсанная", "Неотёсанное", "Неотёсанные"},
			new [] {"Сумасшедший", "Сумасшедшая", "Сумасшедшее", "Сумасшедшие"},
			new [] {"Интенсивный", "Интенсивная", "Интенсивное", "Интенсивные"},
			new [] {"Запретный", "Запретная", "Запретное", "Запретные"},
			new [] {"Неземной", "Неземная", "Неземное", "Неземные"},
			new [] {"Яростный", "Яростная", "Яростное", "Яростные"},
			new [] {"Заточенный", "Заточенная", "Заточенное", "Заточенные"},
			new [] {"Превосходный", "Превосходная", "Превосходное", "Превосходные"},
			new [] {"Сильный", "Сильная", "Сильное", "Сильные"},
			new [] {"Сломанный", "Сломанная", "Сломанное", "Сломанные"},
			new [] {"Опасный", "Опасная", "Опасное", "Опасные"},
			new [] {"Повреждённый", "Повреждённая", "Повреждённое", "Повреждённые"},
			new [] {"Дрянной", "Дрянная", "Дрянное", "Дрянные"},
			new [] {"Быстрый", "Быстрая", "Быстрое", "Быстрые"},
			new [] {"Проворный", "Проворная", "Проворное", "Проворные"},
			new [] {"Шустрый", "Шустрая", "Шустрое", "Шустрые"},
			new [] {"Убийственный", "Убийственная", "Убийственное", "Убийственные"},
			new [] {"Медленный", "Медленная", "Медленное", "Медленные"},
			new [] {"Вялый", "Вялая", "Вялое", "Вялые"},
			new [] {"Ленивый", "Ленивая", "Ленивое", "Ленивые"},
			new [] {"Свирепый", "Свирепая", "Свирепое", "Свирепые"},
			new [] {"Досаждающий", "Досаждающая", "Досаждающее", "Досаждающие"},
			new [] {"Мерзкий", "Мерзкая", "Мерзкое", "Мерзкие"},
			new [] {"Маниакальный", "Маниакальная", "Маниакальное", "Маниакальные"},
			new [] {"Пагубный", "Пагубная", "Пагубное", "Пагубные"},
			new [] {"Крепкий", "Крепкая", "Крепкое", "Крепкие"},
			new [] {"Неприятный", "Неприятная", "Неприятное", "Неприятные"},
			new [] {"Слабый", "Слабая", "Слабое", "Слабые"},
			new [] {"Безжалостный", "Безжалостная", "Безжалостное", "Безжалостные"},
			new [] {"Бешеный", "Бешеная", "Бешеное", "Бешеные"},
			new [] {"Божественный", "Божественная", "Божественное", "Божественные"},
			new [] {"Острый", "Острая", "Острое", "Острые"},
			new [] {"Демонический", "Демоническая", "Демоническое", "Демонические"},
			new [] {"Страстный", "Страстная", "Страстное", "Страстные"},
			new [] {"Жёсткий", "Жёсткая", "Жёсткое", "Жёсткие"},
			new [] {"Защитный", "Защитная", "Защитное", "Защитные"},
			new [] {"Бронированный", "Бронированная", "Бронированное", "Бронированные"},
			new [] {"Охранный", "Охранная", "Охранное", "Охранные"},
			new [] {"Загадочный", "Загадочная", "Загадочное", "Загадочные"},
			new [] {"Точный", "Точная", "Точное", "Точные"},
			new [] {"Везучий", "Везучая", "Везучее", "Везучие"},
			new [] {"Зазубренный", "Зазубренная", "Зазубренное", "Зазубренные"},
			new [] {"Заострённый", "Заострённая", "Заострённое", "Заострённые"},
			new [] {"Шипованный", "Шипованная", "Шипованное", "Шипованные"},
			new [] {"Злящий", "Злящая", "Злящее", "Злящие"},
			new [] {"Грозный", "Грозная", "Грозное", "Грозные"},
			new [] {"Юркий", "Юркая", "Юркое", "Юркие"},
			new [] {"Рассекающий", "Рассекающая", "Рассекающее", "Рассекающие"},
			new [] {"Дикий", "Дикая", "Дикое", "Дикие"},
			new [] {"Опрометчивый", "Опрометчивая", "Опрометчивое", "Опрометчивые"},
			new [] {"Бесстрашный", "Бесстрашная", "Бесстрашное", "Бесстрашные"},
			new [] {"Крохотный", "Крохотная", "Крохотное", "Крохотные"},
			new [] {"Жестокий", "Жестокая", "Жестокое", "Жестокие"},
			new [] {"Легендарный", "Легендарная", "Легендарное", "Легендарные"},
			new [] {"Нереальный", "Нереальная", "Нереальное", "Нереальные"},
			new [] {"Мифический", "Мифическая", "Мифическое", "Мифические"},
			new [] {"Ужасный", "Ужасная", "Ужасное", "Ужасные"},
			new [] {"Маленький", "Маленькая", "Маленькое", "Маленькие"},
			new [] {"Безупречный", "Безупречная", "Безупречное", "Безупречные"},
            new [] {"Обтекаемый", "Обтекаемая", "Обтекаемое", "Обтекаемые"},
            new [] {"Увесистый", "Увесистая", "Увесистое", "Увесистые"},
            new [] {"Могучий", "Могучая", "Могучее", "Могучие"},
            new [] {"Выдающийся", "Выдающаяся", "Выдающееся", "Выдающиеся"},
            new [] {"Свирепый", "Свирепая", "Свирепое", "Свирепые"},
            new [] {"Убойный", "Убойная", "Убойное", "Убойные"},
            new [] {"Радикальный", "Радикальная", "Радикальное", "Радикальные"},
            new [] {"Грубый", "Грубая", "Грубое", "Грубые"},
            new [] {"Хрупкий", "Хрупкая", "Хрупкое", "Хрупкие"},
            new [] {"Несбалансированный", "Несбалансированная", "Несбалансированное", "Несбалансированные"},
            new [] {"Тихий", "Тихая", "Тихое", "Тихие"},
            new [] {"Скрытый", "Скрытая", "Скрытое", "Скрытые"},
            new [] {"Замаскированный", "Замаскированная", "Замаскированное", "Замаскированные"},
            new [] {"Безмолвный", "Безмолвная", "Безмолвное", "Безмолвные"},
            new [] {"Громкий", "Громкая", "Громкое", "Громкие"},
            new [] {"Сверхзвуковой", "Сверхзвуковая", "Сверхзвуковое", "Сверхзвуковые"},
            new [] {"Динамичный", "Динамичная", "Динамичное", "Динамичные"},
            new [] {"Благозвучный", "Благозвучная", "Благозвучное", "Благозвучные"},
            new [] {"Мелодичный", "Мелодичная", "Мелодичное", "Мелодичные"},
            new [] {"Вдохновляющий", "Вдохновляющая", "Вдохновляющее", "Вдохновляющие"},
            new [] {"Приглушённый", "Приглушённая", "Приглушённое", "Приглушённые"},
            new [] {"Нескладный", "Нескладная", "Нескладное", "Нескладные"},
            new [] {"Бессвязный", "Бессвязная", "Бессвязное", "Бессвязные"},
            new [] {"Настроенный", "Настроенная", "Настроенное", "Настроенные"},
            new [] {"Гудящий", "Гудящая", "Гудящее", "Гудящие"},
            new [] {"Сказочный", "Сказочная", "Сказочное", "Сказочные"},
            new [] {"Негодующий", "Негодующая", "Негодующее", "Негодующие"},
            new [] {"Горящий", "Горящая", "Горящее", "Горящие"},
            new [] {"Жертвенный", "Жертвенная", "Жертвенное", "Жертвенные"},
            new [] {"Злопамятный", "Злопамятная", "Злопамятное", "Злопамятные"},
            new [] {"Жаждущий", "Жаждущая", "Жаждущее", "Жаждущие"},
            new [] {"Эфемерный", "Эфемерная", "Эфемерное", "Эфемерные"},
            new [] {"Адский", "Адская", "Адское", "Адские"},
            new [] {"Порченный", "Порченная", "Порченное", "Порченные"},
            new [] {"Предательский", "Предательская", "Предательское", "Предательские"},
            new [] {"Иссушающий", "Иссушающая", "Иссушающее", "Иссушающие"},
            new [] {"Гонимый", "Гонимая", "Гонимое", "Гонимые"},
            new [] {"Блудливый", "Блудливая", "Блудливое", "Блудливые"}
            
        };
        //Женский
        public static List<int?> TypeW = new List<int?>
        {
            //Акссесуары
			ItemID.CopperWatch,
			ItemID.SilverWatch,
			ItemID.GoldWatch,
			ItemID.LuckyHorseshoe,
			ItemID.GuideVoodooDoll,
			ItemID.ObsidianHorseshoe,
			ItemID.SorcererEmblem,
			ItemID.WarriorEmblem,
			ItemID.RangerEmblem,
			ItemID.NeptunesShell,
			ItemID.TitanGlove,
			ItemID.MusicBoxOverworldDay,
			ItemID.MusicBoxEerie,
			ItemID.MusicBoxNight,
			ItemID.MusicBoxTitle,
			ItemID.MusicBoxUnderground,
			ItemID.MusicBoxBoss1,
			ItemID.MusicBoxJungle,
			ItemID.MusicBoxCorruption,
			ItemID.MusicBoxUndergroundCorruption,
			ItemID.MusicBoxTheHallow,
			ItemID.MusicBoxBoss2,
			ItemID.MusicBoxUndergroundHallow,
			ItemID.MusicBoxBoss3,
			ItemID.MusicBox,
			ItemID.RedsWings,
			ItemID.TinWatch,
			ItemID.TungstenWatch,
			ItemID.PlatinumWatch,
			ItemID.DiscountCard,
			ItemID.LuckyCoin,
			ItemID.SandstorminaBottle,
			ItemID.MoonShell,
			ItemID.StarVeil,
			ItemID.Blindfold,
			ItemID.TrifoldMap,
			ItemID.PowerGlove,
			ItemID.CountercurseMantra,
			ItemID.AvengerEmblem,
			ItemID.MechanicalGlove,
			ItemID.SandstorminaBalloon,
			ItemID.BlizzardinaBottle,
			ItemID.BlizzardinaBalloon,
			ItemID.BundleofBalloons,
			ItemID.BlueHorseshoeBalloon,
			ItemID.WhiteHorseshoeBalloon,
			ItemID.YellowHorseshoeBalloon,
			ItemID.DestroyerEmblem,
			ItemID.ClothierVoodooDoll,
			ItemID.ObsidianRose,
			ItemID.FireGauntlet,
			ItemID.MusicBoxSnow,
			ItemID.MusicBoxCrimson,
			ItemID.MusicBoxBoss4,
			ItemID.MusicBoxAltOverworldDay,
			ItemID.MusicBoxRain,
			ItemID.MusicBoxIce,
			ItemID.MusicBoxDesert,
			ItemID.MusicBoxDungeon,
			ItemID.MusicBoxPlantera,
			ItemID.MusicBoxBoss5,
			ItemID.MusicBoxTemple,
			ItemID.MusicBoxEclipse,
			ItemID.MusicBoxMushrooms,
			ItemID.MusicBoxPumpkinMoon,
			ItemID.MusicBoxAltUnderground,
			ItemID.MusicBoxFrostMoon,
			ItemID.PortableCementMixer,
			ItemID.CelestialEmblem,
			ItemID.MysteriousCape,
			ItemID.RedCape,
			ItemID.WinterCape,
			ItemID.HighTestFishingLine,
			ItemID.AnglerEarring,
			ItemID.GingerBeard,
			ItemID.MusicBoxUndergroundCrimson,
			ItemID.LaserRuler,
			ItemID.SummonerEmblem,
			ItemID.MusicBoxLunarBoss,
			ItemID.CelestialShell,
			ItemID.GoblinTech,
			ItemID.BejeweledValkyrieWing,
			ItemID.MusicBoxMartians,
			ItemID.MusicBoxPirates,
			ItemID.MusicBoxHell,
			ItemID.BoneGlove,
			ItemID.BalloonHorseshoeFart,
			ItemID.BalloonHorseshoeHoney,
			ItemID.BalloonHorseshoeSharkron,
			ItemID.RedString,
			ItemID.OrangeString,
			ItemID.YellowString,
			ItemID.LimeString,
			ItemID.GreenString,
			ItemID.TealString,
			ItemID.CyanString,
			ItemID.SkyBlueString,
			ItemID.BlueString,
			ItemID.PurpleString,
			ItemID.VioletString,
			ItemID.PinkString,
			ItemID.BrownString,
			ItemID.WhiteString,
			ItemID.RainbowString,
			ItemID.BlackString,
			ItemID.YoyoBag,
			ItemID.MusicBoxTowers,
			ItemID.MusicBoxGoblins,
			ItemID.WingsNebula,
			ItemID.Yoraiz0rDarkness,
			ItemID.PartyBundleOfBalloonsAccessory,
			ItemID.MusicBoxSandstorm,
			ItemID.MusicBoxDD2,
			ItemID.BerserkerGlove,
			ItemID.AncientChisel,
			ItemID.MusicBoxOceanAlt,
			ItemID.MusicBoxSlimeRain,
			ItemID.MusicBoxSpaceAlt,
			ItemID.MusicBoxTownDay,
			ItemID.MusicBoxTownNight,
			ItemID.MusicBoxWindyDay,
			ItemID.MusicBoxDayRemix,
			ItemID.PortableStool,
			ItemID.MusicBoxTitleAlt,
			ItemID.MusicBoxStorm,
			ItemID.MusicBoxGraveyard,
			ItemID.MusicBoxUndergroundJungle,
			ItemID.MusicBoxJungleNight,
			ItemID.GhostarsWings,
			ItemID.LongRainbowTrailWings,
			ItemID.MusicBoxQueenSlime,
			ItemID.MusicBoxEmpressOfLight,
			ItemID.EmpressFlightBooster,
			ItemID.MusicBoxDukeFishron,
			ItemID.MusicBoxMorningRain,
			ItemID.MusicBoxConsoleTitle,
			ItemID.MusicBoxUndergroundDesert,
			ItemID.MusicBoxOWRain,
			ItemID.MusicBoxOWDay,
			ItemID.MusicBoxOWNight,
			ItemID.MusicBoxOWUnderground,
			ItemID.MusicBoxOWDesert,
			ItemID.MusicBoxOWOcean,
			ItemID.MusicBoxOWMushroom,
			ItemID.MusicBoxOWDungeon,
			ItemID.MusicBoxOWSpace,
			ItemID.MusicBoxOWUnderworld,
			ItemID.MusicBoxOWSnow,
			ItemID.MusicBoxOWCorruption,
			ItemID.MusicBoxOWUndergroundCorruption,
			ItemID.MusicBoxOWCrimson,
			ItemID.MusicBoxOWUndergroundCrimson,
			ItemID.MusicBoxOWUndergroundSnow,
			ItemID.MusicBoxOWUndergroundHallow,
			ItemID.MusicBoxOWBloodMoon,
			ItemID.MusicBoxOWBoss2,
			ItemID.MusicBoxOWBoss1,
			ItemID.MusicBoxOWInvasion,
			ItemID.MusicBoxOWTowers,
			ItemID.MusicBoxOWMoonLord,
			ItemID.MusicBoxOWPlantera,
			ItemID.MusicBoxOWJungle,
			ItemID.MusicBoxOWWallOfFlesh,
			ItemID.MusicBoxOWHallow,
			ItemID.MusicBoxCredits,
			ItemID.WilsonBeardShort,
			ItemID.WilsonBeardLong,
			ItemID.WilsonBeardMagnificent,
			ItemID.MusicBoxDeerclops,
			//Оружие
			ItemID.IronPickaxe,
			ItemID.Vilethorn,
			ItemID.Starfury,
			ItemID.Minishark,
			ItemID.NightmarePickaxe,
			ItemID.MagicMissile,
			ItemID.MoltenFury,
			ItemID.MoltenPickaxe,
			ItemID.SpaceGun,
			ItemID.Muramasa,
			ItemID.BreathingReed,
			ItemID.Flamelash,
			ItemID.Sandgun,
			ItemID.DemonScythe,
			ItemID.NightsEdge,
			ItemID.Blowpipe,
			ItemID.ClockworkAssaultRifle,
			ItemID.MagicalHarp,
			ItemID.LaserRifle,
			ItemID.Megashark,
			ItemID.Cutlass,
			ItemID.TrueNightsEdge,
			ItemID.Frostbrand,
			ItemID.CobaltPickaxe,
			ItemID.MythrilPickaxe,
			ItemID.AdamantitePickaxe,
			ItemID.DeathbringerPickaxe,
			ItemID.BloodLustCluster,
			ItemID.CactusPickaxe,
			ItemID.PiranhaGun,
			ItemID.PalladiumPickaxe,
			ItemID.OrichalcumPickaxe,
			ItemID.TitaniumPickaxe,
			ItemID.ChlorophyteSaber,
			ItemID.ChlorophytePickaxe,
			ItemID.SniperRifle,
			ItemID.RainbowGun,
			ItemID.MagnetSphere,
			ItemID.ZombieArm,
			ItemID.IceSickle,
			ItemID.BookofSkulls,
			ItemID.SnowballCannon,
			ItemID.BonePickaxe,
			ItemID.DeathSickle,
			ItemID.SpectrePickaxe,
			ItemID.CandyCornRifle,
			ItemID.BladedGlove,
			ItemID.CnadyCanePickaxe,
			ItemID.ChainGun,
			ItemID.Razorpine,
			ItemID.SnowmanCannon,
			ItemID.Katana,
			ItemID.Rockfish,
			ItemID.PurpleClubberfish,
			ItemID.ReaverShark,
			ItemID.BubbleGun,
			ItemID.VortexPickaxe,
			ItemID.NebulaPickaxe,
			ItemID.SolarFlarePickaxe,
			ItemID.ChargedBlasterCannon,
			ItemID.ShadowFlameHexDoll,
			ItemID.WandofSparking,
			ItemID.MedusaHead,
			ItemID.TaxCollectorsStickOfDoom,
			ItemID.StardustPickaxe,
			ItemID.PlatinumPickaxe,
			ItemID.TungstenPickaxe,
			ItemID.LeadPickaxe,
			ItemID.TinPickaxe,
			ItemID.CopperPickaxe,
			ItemID.SilverPickaxe,
			ItemID.GoldPickaxe,
			ItemID.LastPrism,
			ItemID.NebulaBlaze,
			ItemID.LunarFlareBook,
			ItemID.BluePhasesaber,
			ItemID.RedPhasesaber,
			ItemID.GreenPhasesaber,
			ItemID.PurplePhasesaber,
			ItemID.WhitePhasesaber,
			ItemID.YellowPhasesaber,
			ItemID.DD2FlameburstTowerT2Popper,
			ItemID.DD2BallistraTowerT2Popper,
			ItemID.DD2LightningAuraT2Popper,
			ItemID.DD2ExplosiveTrapT2Popper,
			ItemID.BookStaff,
			ItemID.DD2BetsyBow,
			ItemID.Celeb2,
			ItemID.FossilPickaxe,
			ItemID.OrangePhasesaber,
			ItemID.SharpTears,
			ItemID.GravediggerShovel,
			ItemID.FairyQueenRangedItem,
			ItemID.EmpressBlade,
			ItemID.LucyTheAxe,
			ItemID.HamBat,
			ItemID.BatBat,
            ModsCall.FargoSouls?.ItemType("ApprenticesEssence"),
            ModsCall.FargoSouls?.ItemType("BarbariansEssence"),
            ModsCall.FargoSouls?.ItemType("OccultistsEssence"),
            ModsCall.FargoSouls?.ItemType("SharpshootersEssence"),
            ModsCall.FargoSouls?.ItemType("CosmoForce"),
            ModsCall.FargoSouls?.ItemType("EarthForce"),
            ModsCall.FargoSouls?.ItemType("LifeForce"),
            ModsCall.FargoSouls?.ItemType("NatureForce"),
            ModsCall.FargoSouls?.ItemType("ShadowForce"),
            ModsCall.FargoSouls?.ItemType("SpiritForce"),
            ModsCall.FargoSouls?.ItemType("TerraForce"),
            ModsCall.FargoSouls?.ItemType("TimberForce"),
            ModsCall.FargoSouls?.ItemType("WillForce"),
            ModsCall.FargoSouls?.ItemType("AgitatingLens"),
            ModsCall.FargoSouls?.ItemType("CelestialRune"),
            ModsCall.FargoSouls?.ItemType("DubiousCircuitry"),
            ModsCall.FargoSouls?.ItemType("IceQueensCrown"),
            ModsCall.FargoSouls?.ItemType("PumpkingsCape"),
            ModsCall.FargoSouls?.ItemType("ReinforcedPlating"),
            ModsCall.FargoSouls?.ItemType("SaucerControlConsole"),
            ModsCall.FargoSouls?.ItemType("SinisterIcon"),
            ModsCall.FargoSouls?.ItemType("SqueakyToy"),
            ModsCall.FargoSouls?.ItemType("SupremeDeathbringerFairy"),
            ModsCall.FargoSouls?.ItemType("ArchWizardsSoul"),
            ModsCall.FargoSouls?.ItemType("ColossusSoul"),
            ModsCall.FargoSouls?.ItemType("ConjuristsSoul"),
            ModsCall.FargoSouls?.ItemType("DimensionSoul"),
            ModsCall.FargoSouls?.ItemType("EternitySoul"),
            ModsCall.FargoSouls?.ItemType("FlightMasterySoul"),
            ModsCall.FargoSouls?.ItemType("GladiatorsSoul"),
            ModsCall.FargoSouls?.ItemType("MasochistSoul"),
            ModsCall.FargoSouls?.ItemType("SnipersSoul"),
            ModsCall.FargoSouls?.ItemType("SupersonicSoul"),
            ModsCall.FargoSouls?.ItemType("TerrariaSoul"),
            ModsCall.FargoSouls?.ItemType("TrawlerSoul"),
            ModsCall.FargoSouls?.ItemType("UniverseSoul"),
            ModsCall.FargoSouls?.ItemType("WorldShaperSoul"),
            ModsCall.FargoSouls?.ItemType("BoneZone"),
            ModsCall.FargoSouls?.ItemType("DestroyerGun"),
            ModsCall.FargoSouls?.ItemType("FishStick"),
            ModsCall.FargoSouls?.ItemType("FleshHand"),
            ModsCall.FargoSouls?.ItemType("Mahoguny"),
            ModsCall.FargoSouls?.ItemType("TophatSquirrelWeapon"),
            ModsCall.FargoSouls?.ItemType("PiranhaGunSummon"),
            ModsCall.FargoSouls?.ItemType("WaspGunSummon"),
            ModsCall.FargoSouls?.ItemType("DestroyerGun2"),
            ModsCall.FargoSouls?.ItemType("DragonBreath2"),
            ModsCall.FargoSouls?.ItemType("HellZone"),
            ModsCall.FargoSouls?.ItemType("SlimeSword"),
            ModsCall.FargoSouls?.ItemType("ComputationOrb"),
            ModsCall.FargoSouls?.ItemType("ParadoxWolfSoul"),
            ModsCall.FargoSouls?.ItemType("MissDrakovisFishingPole"),
            ModsCall.Calamity?.ItemType("Affliction"),
            ModsCall.Calamity?.ItemType("AlchemicalFlask"),
            ModsCall.Calamity?.ItemType("AlluringBait"),
            ModsCall.Calamity?.ItemType("AmbrosialAmpoule"),
            ModsCall.Calamity?.ItemType("AmidiasSpark"),
            ModsCall.Calamity?.ItemType("AquaticEmblem"),
            ModsCall.Calamity?.ItemType("AsgardianAegis"),
            ModsCall.Calamity?.ItemType("AsgardsValor"),
            ModsCall.Calamity?.ItemType("BloodstainedGlove"),
            ModsCall.Calamity?.ItemType("CalamityRing"),
            ModsCall.Calamity?.ItemType("CelestialJewel"),
            ModsCall.Calamity?.ItemType("CoinofDeceit"),
            ModsCall.Calamity?.ItemType("CorruptFlask"),
            ModsCall.Calamity?.ItemType("CrawCarapace"),
            ModsCall.Calamity?.ItemType("CrimsonFlask"),
            ModsCall.Calamity?.ItemType("CrownJewel"),
            ModsCall.Calamity?.ItemType("DaedalusEmblem"),
            ModsCall.Calamity?.ItemType("DragonScales"),
            ModsCall.Calamity?.ItemType("ElectriciansGlove"),
            ModsCall.Calamity?.ItemType("ElementalGauntlet"),
            ModsCall.Calamity?.ItemType("ElysianAegis"),
            ModsCall.Calamity?.ItemType("EnchantedPearl"),
            ModsCall.Calamity?.ItemType("FeatherCrown"),
            ModsCall.Calamity?.ItemType("FilthyGlove"),
            ModsCall.Calamity?.ItemType("FrostFlare"),
            ModsCall.Calamity?.ItemType("Gehenna"),
            ModsCall.Calamity?.ItemType("GiantPearl"),
            ModsCall.Calamity?.ItemType("GloveOfPrecision"),
            ModsCall.Calamity?.ItemType("GloveOfRecklessness"),
            ModsCall.Calamity?.ItemType("HallowedRune"),
            ModsCall.Calamity?.ItemType("HideofAstrumDeus"),
            ModsCall.Calamity?.ItemType("HoneyDew"),
            ModsCall.Calamity?.ItemType("InkBomb"),
            ModsCall.Calamity?.ItemType("Laudanum"),
            ModsCall.Calamity?.ItemType("LeviathanAmbergris"),
            ModsCall.Calamity?.ItemType("LivingDew"),
            ModsCall.Calamity?.ItemType("MoonstoneCrown"),
            ModsCall.Calamity?.ItemType("Nanotech"),
            ModsCall.Calamity?.ItemType("OldDie"),
            ModsCall.Calamity?.ItemType("PlaguedFuelPack"),
            ModsCall.Calamity?.ItemType("RadiantOoze"),
            ModsCall.Calamity?.ItemType("RogueEmblem"),
            ModsCall.Calamity?.ItemType("SandCloak"),
            ModsCall.Calamity?.ItemType("ScuttlersJewel"),
            ModsCall.Calamity?.ItemType("SeaShell"),
            ModsCall.Calamity?.ItemType("SigilofCalamitas"),
            ModsCall.Calamity?.ItemType("SpectralVeil"),
            ModsCall.Calamity?.ItemType("Sponge"),
            ModsCall.Calamity?.ItemType("VoidofExtinction"),
            ModsCall.Calamity?.ItemType("DiscordianWings"),
            ModsCall.Calamity?.ItemType("SoulofCryogen"),
            ModsCall.Calamity?.ItemType("PolarisParrotfish"),
            ModsCall.Calamity?.ItemType("DragoonDrizzlefish"),
            ModsCall.Calamity?.ItemType("Spadefish"),
            ModsCall.Calamity?.ItemType("SparklingEmpress"),
            ModsCall.Calamity?.ItemType("AstralPickaxe"),
            ModsCall.Calamity?.ItemType("BeastialPickaxe"),
            ModsCall.Calamity?.ItemType("BlossomPickaxe"),
            ModsCall.Calamity?.ItemType("FlamebeakHampick"),
            ModsCall.Calamity?.ItemType("GallantPickaxe"),
            ModsCall.Calamity?.ItemType("GreatbayPickaxe"),
            ModsCall.Calamity?.ItemType("ShardlightPickaxe"),
            ModsCall.Calamity?.ItemType("SkyfringePickaxe"),
            ModsCall.Calamity?.ItemType("WulfrumPickaxe"),
            ModsCall.Calamity?.ItemType("GalvanizingGlaive"),
            ModsCall.Calamity?.ItemType("LaserRifle"),
            ModsCall.Calamity?.ItemType("PlasmaCaster"),
            ModsCall.Calamity?.ItemType("PulseRifle"),
            ModsCall.Calamity?.ItemType("SystemBane"),
            ModsCall.Calamity?.ItemType("TeslaCannon"),
            ModsCall.Calamity?.ItemType("AcidGun"),
            ModsCall.Calamity?.ItemType("ApoctosisArray"),
            ModsCall.Calamity?.ItemType("ArcticBearPaw"),
            ModsCall.Calamity?.ItemType("Atlantis"),
            ModsCall.Calamity?.ItemType("BloodBath"),
            ModsCall.Calamity?.ItemType("CalamitasInferno"),
            ModsCall.Calamity?.ItemType("CoralSpout"),
            ModsCall.Calamity?.ItemType("CosmicRainbow"),
            ModsCall.Calamity?.ItemType("Cryophobia"),
            ModsCall.Calamity?.ItemType("DarkSpark"),
            ModsCall.Calamity?.ItemType("Eternity"),
            ModsCall.Calamity?.ItemType("FlareBolt"),
            ModsCall.Calamity?.ItemType("FrigidflashBolt"),
            ModsCall.Calamity?.ItemType("FrostBolt"),
            ModsCall.Calamity?.ItemType("GleamingMagnolia"),
            ModsCall.Calamity?.ItemType("HeliumFlash"),
            ModsCall.Calamity?.ItemType("Hematemesis"),
            ModsCall.Calamity?.ItemType("MadAlchemistsCocktailGlove"),
            ModsCall.Calamity?.ItemType("MagnaCannon"),
            ModsCall.Calamity?.ItemType("ManaRose"),
            ModsCall.Calamity?.ItemType("NuclearFury"),
            ModsCall.Calamity?.ItemType("PhantasmalFury"),
            ModsCall.Calamity?.ItemType("PlasmaRifle"),
            ModsCall.Calamity?.ItemType("PrimordialAncient"),
            ModsCall.Calamity?.ItemType("PrimordialEarth"),
            ModsCall.Calamity?.ItemType("Purge"),
            ModsCall.Calamity?.ItemType("RecitationoftheBeast"),
            ModsCall.Calamity?.ItemType("RelicofRuin"),
            ModsCall.Calamity?.ItemType("SanguineFlare"),
            ModsCall.Calamity?.ItemType("SkyGlaze"),
            ModsCall.Calamity?.ItemType("StratusSphere"),
            ModsCall.Calamity?.ItemType("TheWand"),
            ModsCall.Calamity?.ItemType("Thunderstorm"),
            ModsCall.Calamity?.ItemType("Vehemenc"),
            ModsCall.Calamity?.ItemType("VitriolicViper"),
            ModsCall.Calamity?.ItemType("VividClarity"),
            ModsCall.Calamity?.ItemType("WintersFury"),
            ModsCall.Calamity?.ItemType("AncientShiv"),
            ModsCall.Calamity?.ItemType("Aorta"),
            ModsCall.Calamity?.ItemType("AstralPike"),
            ModsCall.Calamity?.ItemType("AstralScythe"),
            ModsCall.Calamity?.ItemType("Ataraxia"),
            ModsCall.Calamity?.ItemType("Avalanche"),
            ModsCall.Calamity?.ItemType("Basher"),
            ModsCall.Calamity?.ItemType("BloodyEdge"),
            ModsCall.Calamity?.ItemType("Brimlash"),
            ModsCall.Calamity?.ItemType("BrimlashBuster"),
            ModsCall.Calamity?.ItemType("BurntSienna"),
            ModsCall.Calamity?.ItemType("Carnage"),
            ModsCall.Calamity?.ItemType("CausticEdge"),
            ModsCall.Calamity?.ItemType("ColdheartIcicle"),
            ModsCall.Calamity?.ItemType("CosmicShiv"),
            ModsCall.Calamity?.ItemType("DiseasedPike"),
            ModsCall.Calamity?.ItemType("DragonRage"),
            ModsCall.Calamity?.ItemType("Earth"),
            ModsCall.Calamity?.ItemType("EarthenPike"),
            ModsCall.Calamity?.ItemType("ElementalShortsword"),
            ModsCall.Calamity?.ItemType("EssenceFlayer"),
            ModsCall.Calamity?.ItemType("EutrophicScimitar"),
            ModsCall.Calamity?.ItemType("ForsakenSaber"),
            ModsCall.Calamity?.ItemType("FourSeasonsGalaxia"),
            ModsCall.Calamity?.ItemType("FulgurationHalberd"),
            ModsCall.Calamity?.ItemType("HolidayHalberd"),
            ModsCall.Calamity?.ItemType("LifefruitScythe"),
            ModsCall.Calamity?.ItemType("Lucrecia"),
            ModsCall.Calamity?.ItemType("Mariana"),
            ModsCall.Calamity?.ItemType("Mourningstar"),
            ModsCall.Calamity?.ItemType("Murasama"),
            ModsCall.Calamity?.ItemType("PerfectDark"),
            ModsCall.Calamity?.ItemType("Quagmire"),
            ModsCall.Calamity?.ItemType("Shimmerspark"),
            ModsCall.Calamity?.ItemType("SolarFlare"),
            ModsCall.Calamity?.ItemType("SoulEdge"),
            ModsCall.Calamity?.ItemType("StormSaber"),
            ModsCall.Calamity?.ItemType("Terracotta"),
            ModsCall.Calamity?.ItemType("TerraEdge"),
            ModsCall.Calamity?.ItemType("TerraShiv"),
            ModsCall.Calamity?.ItemType("TheMicrowave"),
            ModsCall.Calamity?.ItemType("ThePlaguebringer"),
            ModsCall.Calamity?.ItemType("TitanArm"),
            ModsCall.Calamity?.ItemType("Trinity"),
            ModsCall.Calamity?.ItemType("TrueBloodyEdge"),
            ModsCall.Calamity?.ItemType("TrueCausticEdge"),
            ModsCall.Calamity?.ItemType("TyphonsGreed"),
            ModsCall.Calamity?.ItemType("UrchinFlail"),
            ModsCall.Calamity?.ItemType("VirulentKatana"),
            ModsCall.Calamity?.ItemType("AMR"),
            ModsCall.Calamity?.ItemType("Animosity"),
            ModsCall.Calamity?.ItemType("BarracudaGun"),
            ModsCall.Calamity?.ItemType("BrimstoneFury"),
            ModsCall.Calamity?.ItemType("ChickenCannon"),
            ModsCall.Calamity?.ItemType("ClamorRifle"),
            ModsCall.Calamity?.ItemType("ClaretCannon"),
            ModsCall.Calamity?.ItemType("Contagion"),
            ModsCall.Calamity?.ItemType("CoralCannon"),
            ModsCall.Calamity?.ItemType("DodusHandcannon"),
            ModsCall.Calamity?.ItemType("EternalBlizzard"),
            ModsCall.Calamity?.ItemType("FetidEmesis"),
            ModsCall.Calamity?.ItemType("FirestormCannon"),
            ModsCall.Calamity?.ItemType("FlakToxicannon"),
            ModsCall.Calamity?.ItemType("FlurrystormCannon"),
            ModsCall.Calamity?.ItemType("Galeforce"),
            ModsCall.Calamity?.ItemType("HalibutCannon"),
            ModsCall.Calamity?.ItemType("Infinity"),
            ModsCall.Calamity?.ItemType("Karasawa"),
            ModsCall.Calamity?.ItemType("MagnomalyCannon"),
            ModsCall.Calamity?.ItemType("Malevolence"),
            ModsCall.Calamity?.ItemType("MineralMortar"),
            ModsCall.Calamity?.ItemType("Onyxia"),
            ModsCall.Calamity?.ItemType("PristineFury"),
            ModsCall.Calamity?.ItemType("RaidersGlory"),
            ModsCall.Calamity?.ItemType("SandstormGun"),
            ModsCall.Calamity?.ItemType("SpectralstormCannon"),
            ModsCall.Calamity?.ItemType("SpectreRifle"),
            ModsCall.Calamity?.ItemType("StarCannonEX"),
            ModsCall.Calamity?.ItemType("StarfleetMK2"),
            ModsCall.Calamity?.ItemType("StellarCannon"),
            ModsCall.Calamity?.ItemType("StormSurge"),
            ModsCall.Calamity?.ItemType("SulphuricAcidCannon"),
            ModsCall.Calamity?.ItemType("TheBallista"),
            ModsCall.Calamity?.ItemType("ThePack"),
            ModsCall.Calamity?.ItemType("Ultima"),
            ModsCall.Calamity?.ItemType("AcidicRainBarrel"),
            ModsCall.Calamity?.ItemType("BallisticPoisonBomb"),
            ModsCall.Calamity?.ItemType("BlastBarrel"),
            ModsCall.Calamity?.ItemType("BrackishFlask"),
            ModsCall.Calamity?.ItemType("Cinquedea"),
            ModsCall.Calamity?.ItemType("ConsecratedWater"),
            ModsCall.Calamity?.ItemType("ContaminatedBile"),
            ModsCall.Calamity?.ItemType("CrushsawCrasher"),
            ModsCall.Calamity?.ItemType("DeepSeaDumbbell"),
            ModsCall.Calamity?.ItemType("DesecratedWater"),
            ModsCall.Calamity?.ItemType("DuststormInABottle"),
            ModsCall.Calamity?.ItemType("FrostcrushValari"),
            ModsCall.Calamity?.ItemType("Hypothermia"),
            ModsCall.Calamity?.ItemType("Kylie"),
            ModsCall.Calamity?.ItemType("Lionfish"),
            ModsCall.Calamity?.ItemType("Penumbra"),
            ModsCall.Calamity?.ItemType("RadiantStar"),
            ModsCall.Calamity?.ItemType("ScarletDevil"),
            ModsCall.Calamity?.ItemType("SeafoamBomb"),
            ModsCall.Calamity?.ItemType("SealedSingularity"),
            ModsCall.Calamity?.ItemType("SlickCane"),
            ModsCall.Calamity?.ItemType("StarofDestruction"),
            ModsCall.Calamity?.ItemType("StormfrontRazor"),
            ModsCall.Calamity?.ItemType("Supernova"),
            ModsCall.Calamity?.ItemType("TimeBolt"),
            ModsCall.Calamity?.ItemType("Turbulance"),
            ModsCall.Calamity?.ItemType("AncientIceChunk"),
            ModsCall.Calamity?.ItemType("CadaverousCarrion"),
            ModsCall.Calamity?.ItemType("ColdDivinity"),
            ModsCall.Calamity?.ItemType("Cosmilamp"),
            ModsCall.Calamity?.ItemType("MagicalConch"),
            ModsCall.Calamity?.ItemType("ResurrectionButterfly"),
            ModsCall.Calamity?.ItemType("SarosPossession"),
            ModsCall.Calamity?.ItemType("GruesomeEminence"),
            ModsCall.Calamity?.ItemType("Heresy"),
            ModsCall.Calamity?.ItemType("RainbowPartyCannon"),
            ModsCall.Calamity?.ItemType("Rancor"),
            ModsCall.Calamity?.ItemType("T1000"),
            ModsCall.Calamity?.ItemType("PhosphorescentGauntlet"),
            ModsCall.Calamity?.ItemType("Violence"),
            ModsCall.Calamity?.ItemType("FleshOfInfidelity"),
            ModsCall.Calamity?.ItemType("Perdition"),
            ModsCall.Calamity?.ItemType("DuneHopper"),
            ModsCall.Calamity?.ItemType("SearedPan"),
            ModsCall.Calamity?.ItemType("OccultSkullCrown"),
            ModsCall.Calamity?.ItemType("GloriousEnd"),
            ModsCall.Calamity?.ItemType("ArtAttack"),
            ModsCall.Calamity?.ItemType("ScorchedEarth"),
        };
        //Средний
        public static List<int?> TypeU = new List<int?>
        {
            //Акссесуары
			ItemID.CloudinaBottle,
			ItemID.DivingGear,
			ItemID.CloudinaBalloon,
			ItemID.ArmorBracing,
			ItemID.TigerClimbingGear,
			ItemID.Tabi,
			ItemID.MasterNinjaGear,
			ItemID.PygmyNecklace,
			ItemID.PanicNecklace,
			ItemID.JellyfishNecklace,
			ItemID.SweetheartNecklace,
			ItemID.JellyfishDivingGear,
			ItemID.ArcticDivingGear,
			ItemID.DiamondRing,
			ItemID.GoldRing,
			ItemID.CoinRing,
			ItemID.GreedyRing,
			ItemID.WeatherRadio,
			ItemID.CordageGuide,
			ItemID.TsunamiInABottle,
			ItemID.SharkToothNecklace,
			ItemID.PocketMirror,
			ItemID.FrogGear,
			ItemID.StingerNecklace,
			ItemID.DontStarveShaderItem,
			//Оружие
			ItemID.Blowgun,
			ItemID.Uzi,
			ItemID.FalconBlade,
			ItemID.Tsunami,
			ItemID.PainterPaintballGun,
			ItemID.StylistKilLaKillScissorsIWish,
			ItemID.FireworksLauncher,
			ItemID.SpiritFlame,
			ItemID.DD2SquireDemonSword,
			ItemID.FairyQueenMagicItem,
			ItemID.TentacleSpike,
            ModsCall.FargoSouls?.ItemType("AdamantiteEnchant"),
            ModsCall.FargoSouls?.ItemType("AncientCobaltEnchant"),
            ModsCall.FargoSouls?.ItemType("AncientShadowEnchant"),
            ModsCall.FargoSouls?.ItemType("AnglerEnchantment"),
            ModsCall.FargoSouls?.ItemType("ApprenticeEnchant"),
            ModsCall.FargoSouls?.ItemType("BeeEnchant"),
            ModsCall.FargoSouls?.ItemType("BeetleEnchant"),
            ModsCall.FargoSouls?.ItemType("BorealWoodEnchant"),
            ModsCall.FargoSouls?.ItemType("CactusEnchant"),
            ModsCall.FargoSouls?.ItemType("ChlorophyteEnchant"),
            ModsCall.FargoSouls?.ItemType("CobaltEnchant"),
            ModsCall.FargoSouls?.ItemType("CopperEnchant"),
            ModsCall.FargoSouls?.ItemType("CrimsonEnchant"),
            ModsCall.FargoSouls?.ItemType("DarkArtistEnchant"),
            ModsCall.FargoSouls?.ItemType("EbonwoodEnchant"),
            ModsCall.FargoSouls?.ItemType("ForbiddenEnchant"),
            ModsCall.FargoSouls?.ItemType("FossilEnchant"),
            ModsCall.FargoSouls?.ItemType("FrostEnchant"),
            ModsCall.FargoSouls?.ItemType("GladiatorEnchant"),
            ModsCall.FargoSouls?.ItemType("GoldEnchant"),
            ModsCall.FargoSouls?.ItemType("HallowEnchant"),
            ModsCall.FargoSouls?.ItemType("HuntressEnchant"),
            ModsCall.FargoSouls?.ItemType("IronEnchant"),
            ModsCall.FargoSouls?.ItemType("JungleEnchant"),
            ModsCall.FargoSouls?.ItemType("LeadEnchant"),
            ModsCall.FargoSouls?.ItemType("MeteorEnchant"),
            ModsCall.FargoSouls?.ItemType("MinerEnchant"),
            ModsCall.FargoSouls?.ItemType("MoltenEnchant"),
            ModsCall.FargoSouls?.ItemType("MonkEnchant"),
            ModsCall.FargoSouls?.ItemType("MythrilEnchant"),
            ModsCall.FargoSouls?.ItemType("NebulaEnchant"),
            ModsCall.FargoSouls?.ItemType("NecroEnchant"),
            ModsCall.FargoSouls?.ItemType("NinjaEnchant"),
            ModsCall.FargoSouls?.ItemType("ObsidianEnchant"),
            ModsCall.FargoSouls?.ItemType("OrichalcumEnchant"),
            ModsCall.FargoSouls?.ItemType("PalladiumEnchant"),
            ModsCall.FargoSouls?.ItemType("PalmWoodEnchant"),
            ModsCall.FargoSouls?.ItemType("PearlwoodEnchant"),
            ModsCall.FargoSouls?.ItemType("PlatinumEnchant"),
            ModsCall.FargoSouls?.ItemType("PumpkinEnchant"),
            ModsCall.FargoSouls?.ItemType("RainEnchant"),
            ModsCall.FargoSouls?.ItemType("RedRidingEnchant"),
            ModsCall.FargoSouls?.ItemType("RichMahoganyEnchant"),
            ModsCall.FargoSouls?.ItemType("ShadewoodEnchant"),
            ModsCall.FargoSouls?.ItemType("ShadowEnchant"),
            ModsCall.FargoSouls?.ItemType("ShinobiEnchant"),
            ModsCall.FargoSouls?.ItemType("ShroomiteEnchant"),
            ModsCall.FargoSouls?.ItemType("SilverEnchant"),
            ModsCall.FargoSouls?.ItemType("SnowEnchant"),
            ModsCall.FargoSouls?.ItemType("SolarEnchant"),
            ModsCall.FargoSouls?.ItemType("SpectreEnchant"),
            ModsCall.FargoSouls?.ItemType("SpiderEnchant"),
            ModsCall.FargoSouls?.ItemType("SpookyEnchant"),
            ModsCall.FargoSouls?.ItemType("SquireEnchant"),
            ModsCall.FargoSouls?.ItemType("StardustEnchant"),
            ModsCall.FargoSouls?.ItemType("TikiEnchant"),
            ModsCall.FargoSouls?.ItemType("TinEnchant"),
            ModsCall.FargoSouls?.ItemType("TitaniumEnchant"),
            ModsCall.FargoSouls?.ItemType("TungstenEnchant"),
            ModsCall.FargoSouls?.ItemType("TurtleEnchant"),
            ModsCall.FargoSouls?.ItemType("ValhallaKnightEnchant"),
            ModsCall.FargoSouls?.ItemType("VortexEnchant"),
            ModsCall.FargoSouls?.ItemType("WizardEnchant"),
            ModsCall.FargoSouls?.ItemType("WoodEnchant"),
            ModsCall.FargoSouls?.ItemType("BetsysHeart"),
            ModsCall.FargoSouls?.ItemType("ConcentratedRainbowMatter"),
            ModsCall.FargoSouls?.ItemType("CorruptHeart"),
            ModsCall.FargoSouls?.ItemType("GuttedHeart"),
            ModsCall.FargoSouls?.ItemType("HeartoftheMasochist"),
            ModsCall.FargoSouls?.ItemType("NecromanticBrew"),
            ModsCall.FargoSouls?.ItemType("PungentEyeball"),
            ModsCall.FargoSouls?.ItemType("PureHeart"),
            ModsCall.FargoSouls?.ItemType("QueenStinger"),
            ModsCall.FargoSouls?.ItemType("SparklingAdoration"),
            ModsCall.FargoSouls?.ItemType("TimsConcoction"),
            ModsCall.FargoSouls?.ItemType("WyvernFeather"),
            ModsCall.FargoSouls?.ItemType("BrainStaff"),
            ModsCall.FargoSouls?.ItemType("DragonBreath"),
            ModsCall.FargoSouls?.ItemType("TheSmallSting"),
            ModsCall.FargoSouls?.ItemType("SparklingLove"),
            ModsCall.FargoSouls?.ItemType("TheBigSting"),
            ModsCall.Calamity?.ItemType("AbyssalDivingGear"),
            ModsCall.Calamity?.ItemType("AbyssalMirror"),
            ModsCall.Calamity?.ItemType("AncientFossil"),
            ModsCall.Calamity?.ItemType("AnechoicPlating"),
            ModsCall.Calamity?.ItemType("BlazingCore"),
            ModsCall.Calamity?.ItemType("BloodflareCore"),
            ModsCall.Calamity?.ItemType("CoreOfTheBloodGod"),
            ModsCall.Calamity?.ItemType("DarkSunRing"),
            ModsCall.Calamity?.ItemType("DraedonsHeart"),
            ModsCall.Calamity?.ItemType("EclipseMirror"),
            ModsCall.Calamity?.ItemType("EyeoftheStorm"),
            ModsCall.Calamity?.ItemType("HarpyRing"),
            ModsCall.Calamity?.ItemType("HeartofDarkness"),
            ModsCall.Calamity?.ItemType("HotE"),
            ModsCall.Calamity?.ItemType("HowlsHeart"),
            ModsCall.Calamity?.ItemType("LeadCore"),
            ModsCall.Calamity?.ItemType("LifeJelly"),
            ModsCall.Calamity?.ItemType("ManaJelly"),
            ModsCall.Calamity?.ItemType("MirageMirror"),
            ModsCall.Calamity?.ItemType("NebulousCore"),
            ModsCall.Calamity?.ItemType("NecklaceofVexation"),
            ModsCall.Calamity?.ItemType("PermafrostsConcoction"),
            ModsCall.Calamity?.ItemType("ReaperToothNecklace"),
            ModsCall.Calamity?.ItemType("SirensHeart"),
            ModsCall.Calamity?.ItemType("StarbusterCore"),
            ModsCall.Calamity?.ItemType("StatisBlessing"),
            ModsCall.Calamity?.ItemType("StatisCurse"),
            ModsCall.Calamity?.ItemType("TheAmalgam"),
            ModsCall.Calamity?.ItemType("TheCommunity"),
            ModsCall.Calamity?.ItemType("ToxicHeart"),
            ModsCall.Calamity?.ItemType("VitalJelly"),
            ModsCall.Calamity?.ItemType("VoltaicJelly"),
            ModsCall.Calamity?.ItemType("BurningSea"),
            ModsCall.Calamity?.ItemType("DivineRetribution"),
            ModsCall.Calamity?.ItemType("Effervescence"),
            ModsCall.Calamity?.ItemType("EyeofMagnus"),
            ModsCall.Calamity?.ItemType("FatesReveal"),
            ModsCall.Calamity?.ItemType("ForbiddenSun"),
            ModsCall.Calamity?.ItemType("HadopelagicEcho"),
            ModsCall.Calamity?.ItemType("Keelhaul"),
            ModsCall.Calamity?.ItemType("LightGodsBrilliance"),
            ModsCall.Calamity?.ItemType("MagneticMeltdown"),
            ModsCall.Calamity?.ItemType("RougeSlash"),
            ModsCall.Calamity?.ItemType("SirensSong"),
            ModsCall.Calamity?.ItemType("UndinesRetribution"),
            ModsCall.Calamity?.ItemType("Aftershock"),
            ModsCall.Calamity?.ItemType("Brimlance"),
            ModsCall.Calamity?.ItemType("Devastation"),
            ModsCall.Calamity?.ItemType("DevilsDevastation"),
            ModsCall.Calamity?.ItemType("DraconicDestruction"),
            ModsCall.Calamity?.ItemType("ExsanguinationLance"),
            ModsCall.Calamity?.ItemType("GoldplumeSpear"),
            ModsCall.Calamity?.ItemType("HellionFlowerSpear"),
            ModsCall.Calamity?.ItemType("LionHeart"),
            ModsCall.Calamity?.ItemType("MarniteSpear"),
            ModsCall.Calamity?.ItemType("RedSun"),
            ModsCall.Calamity?.ItemType("SpatialLance"),
            ModsCall.Calamity?.ItemType("StarnightLance"),
            ModsCall.Calamity?.ItemType("StellarContemptMelee"),
            ModsCall.Calamity?.ItemType("TerraLance"),
            ModsCall.Calamity?.ItemType("TheEyeofCalamitas"),
            ModsCall.Calamity?.ItemType("Tumbleweed"),
            ModsCall.Calamity?.ItemType("UrchinSpear"),
            ModsCall.Calamity?.ItemType("Whirlpool"),
            ModsCall.Calamity?.ItemType("AcesHigh"),
            ModsCall.Calamity?.ItemType("Alluvion"),
            ModsCall.Calamity?.ItemType("AstrealDefeat"),
            ModsCall.Calamity?.ItemType("BrimstoneFlamesprayer"),
            ModsCall.Calamity?.ItemType("CleansingBlaze"),
            ModsCall.Calamity?.ItemType("DaemonsFlame"),
            ModsCall.Calamity?.ItemType("DragonsBreath"),
            ModsCall.Calamity?.ItemType("ElementalEruption"),
            ModsCall.Calamity?.ItemType("PlanetaryAnnihilation"),
            ModsCall.Calamity?.ItemType("SeasSearing"),
            ModsCall.Calamity?.ItemType("BouncingEyeball"),
            ModsCall.Calamity?.ItemType("EclipsesFall"),
            ModsCall.Calamity?.ItemType("Equanimity"),
            ModsCall.Calamity?.ItemType("IchorSpear"),
            ModsCall.Calamity?.ItemType("ProfanedTrident"),
            ModsCall.Calamity?.ItemType("ShatteredSun"),
            ModsCall.Calamity?.ItemType("SpearofDestiny"),
            ModsCall.Calamity?.ItemType("SpearofPaleolith"),
            ModsCall.Calamity?.ItemType("StellarContemptRogue"),
            ModsCall.Calamity?.ItemType("Valediction"),
            ModsCall.Calamity?.ItemType("GammaHeart"),
            ModsCall.Calamity?.ItemType("IgneousExaltation"),
            ModsCall.Calamity?.ItemType("PrototypeAndromechaRing"),
            ModsCall.Calamity?.ItemType("SamuraiBadge"),
            ModsCall.Calamity?.ItemType("SandSharkToothNecklace"),
            ModsCall.Calamity?.ItemType("ShatteredCommunity"),
            ModsCall.Calamity?.ItemType("RemsRevenge"),
            ModsCall.Calamity?.ItemType("Calamity"),
            ModsCall.Calamity?.ItemType("UnstablePrism"),
            ModsCall.Calamity?.ItemType("UniversalGenesis"),
        };
        //Множественный
        public static List<int?> TypePl = new List<int?>
        {
            //Акссесуары
			ItemID.CopperWatch,
			ItemID.SilverWatch,
			ItemID.GoldWatch,
			ItemID.HermesBoots,
			ItemID.RocketBoots,
			ItemID.Flipper,
			ItemID.FeralClaws,
			ItemID.Shackle,
			ItemID.SpectreBoots,
			ItemID.DemonWings,
			ItemID.AngelWings,
			ItemID.TinWatch,
			ItemID.TungstenWatch,
			ItemID.PlatinumWatch,
			ItemID.ButterflyWings,
			ItemID.FairyWings,
			ItemID.HarpyWings,
			ItemID.BoneWings,
			ItemID.FlameWings,
			ItemID.FrozenWings,
			ItemID.GhostWings,
			ItemID.WaterWalkingBoots,
			ItemID.Vitamins,
			ItemID.LightningBoots,
			ItemID.ObsidianWaterWalkingBoots,
			ItemID.LavaWaders,
			ItemID.SteampunkWings,
			ItemID.IceSkates,
			ItemID.ClimbingClaws,
			ItemID.ShoeSpikes,
			ItemID.HoneyComb,
			ItemID.LeafWings,
			ItemID.BatWings,
			ItemID.BeeWings,
			ItemID.FlurryBoots,
			ItemID.DTownsWings,
			ItemID.WillsWings,
			ItemID.CrownosWings,
			ItemID.CenxsWings,
			ItemID.MagicCuffs,
			ItemID.TatteredFairyWings,
			ItemID.SpookyWings,
			ItemID.FrostsparkBoots,
			ItemID.FestiveWings,
			ItemID.HandWarmer,
			ItemID.CelestialCuffs,
			ItemID.BeetleWings,
			ItemID.FrogLeg,
			ItemID.FinWings,
			ItemID.FishronWings,
			ItemID.MothronWings,
			ItemID.PutridScent,
			ItemID.FleshKnuckles,
			ItemID.FlowerBoots,
			ItemID.SailfishBoots,
			ItemID.YoYoGlove,
			ItemID.WingsSolar,
			ItemID.WingsStardust,
			ItemID.Yoraiz0rWings,
			ItemID.JimsWings,
			ItemID.SkiphsWings,
			ItemID.LokisWings,
			ItemID.AnglerTackleBag,
			ItemID.BetsyWings,
			ItemID.ArkhalisWings,
			ItemID.AmphibianBoots,
			ItemID.FairyBoots,
			ItemID.FrogFlipper,
			ItemID.FrogWebbing,
			ItemID.SandBoots,
			ItemID.SpectreGoggles,
			ItemID.FoodBarbarianWings,
			ItemID.GroxTheGreatWings,
			ItemID.FlameWakerBoots,
			ItemID.RainbowWings,
			ItemID.HellfireTreads,
			ItemID.CreativeWings,
			ItemID.TerrasparkBoots,
			ItemID.LavaproofTackleBag,
			ItemID.GlassSlipper,
			//Оружие
			ItemID.CursedFlames,
			ItemID.ShroomiteDiggingClaw,
            ModsCall.FargoSouls?.ItemType("AeolusBoots"),
            ModsCall.FargoSouls?.ItemType("EurusSock"),
            ModsCall.FargoSouls?.ItemType("FusedLens"),
            ModsCall.FargoSouls?.ItemType("MutantAntibodies"),
            ModsCall.FargoSouls?.ItemType("NymphsPerfume"),
            ModsCall.FargoSouls?.ItemType("SandsofTime"),
            ModsCall.FargoSouls?.ItemType("TwinRangs"),
            ModsCall.FargoSouls?.ItemType("GeminiGlaives"),
            ModsCall.Calamity?.ItemType("AngelTreads"),
            ModsCall.Calamity?.ItemType("DarkGodsSheath"),
            ModsCall.Calamity?.ItemType("IronBoots"),
            ModsCall.Calamity?.ItemType("SilencingSheath"),
            ModsCall.Calamity?.ItemType("StressPills"),
            ModsCall.Calamity?.ItemType("Popo"),
            ModsCall.Calamity?.ItemType("CelestialTracers"),
            ModsCall.Calamity?.ItemType("DrewsWings"),
            ModsCall.Calamity?.ItemType("ElysianTracers"),
            ModsCall.Calamity?.ItemType("ElysianWings"),
            ModsCall.Calamity?.ItemType("HadarianWings"),
            ModsCall.Calamity?.ItemType("InfinityBoots"),
            ModsCall.Calamity?.ItemType("SilvaWings"),
            ModsCall.Calamity?.ItemType("SkylineWings"),
            ModsCall.Calamity?.ItemType("StarlightWings"),
            ModsCall.Calamity?.ItemType("TarragonWings"),
            ModsCall.Calamity?.ItemType("XerocWings"),
            ModsCall.Calamity?.ItemType("SnakeEyes"),
            ModsCall.Calamity?.ItemType("Miasma"),
            ModsCall.Calamity?.ItemType("ShiftingSands"),
            ModsCall.Calamity?.ItemType("SlitheringEels"),
            ModsCall.Calamity?.ItemType("TearsofHeaven"),
            ModsCall.Calamity?.ItemType("Tradewinds"),
            ModsCall.Calamity?.ItemType("Viscera"),
            ModsCall.Calamity?.ItemType("EmpyreanKnives"),
            ModsCall.Calamity?.ItemType("MandibleClaws"),
            ModsCall.Calamity?.ItemType("MantisClaws"),
            ModsCall.Calamity?.ItemType("MonstrousKnives"),
            ModsCall.Calamity?.ItemType("MycelialClaws"),
            ModsCall.Calamity?.ItemType("RoyalKnivesMelee"),
            ModsCall.Calamity?.ItemType("TenebreusTides"),
            ModsCall.Calamity?.ItemType("TheBurningSky"),
            ModsCall.Calamity?.ItemType("TheEmpyrean"),
            ModsCall.Calamity?.ItemType("EmpyreanKnivesThrown"),
            ModsCall.Calamity?.ItemType("JawsOfOblivion"),
            ModsCall.Calamity?.ItemType("LeviathanTeeth"),
            ModsCall.Calamity?.ItemType("RoyalKnives"),
            ModsCall.Calamity?.ItemType("SkyfinBombers"),
            ModsCall.Calamity?.ItemType("TerrorTalons"),
            ModsCall.Calamity?.ItemType("TotalityBreakers"),
            ModsCall.Calamity?.ItemType("FleshOfInfidelity"),
            ModsCall.Calamity?.ItemType("FlowersOfMortality"),
        };

        public static string GetGenderedPrefix(string[] prefix, int id)
        {
            if (TypeW.Contains(id))
                return prefix[1];

            if (TypeU.Contains(id))
                return prefix[2];

            if (TypePl.Contains(id))
                return prefix[3];

            return prefix[0];
        }
    }
}