using CalamityRuTranslate.Common;
using CalamityRuTranslate.Utilities;
using Mono.Cecil.Cil;
using MonoMod.Cil;

namespace CalamityRuTranslate.Vanilla
{
    public class DrawInfoAccsIL : ILEdit
    {
        public override bool Autoload() => Translation.IsRussianLanguage;

        public override void Load() => IL.Terraria.Main.DrawInfoAccs += ChangeDrawInfoAccs;

        public override void Unload() => IL.Terraria.Main.DrawInfoAccs -= ChangeDrawInfoAccs;

        private void ChangeDrawInfoAccs(ILContext il)
        {
            ILCursor cursor = new ILCursor(il);

            for (int j = 0; j < 1; j++)
            {
                if (!cursor.TryGotoNext(i => i.MatchLdcI4(12)))
                    return;
            }
            
            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldc_I4, 1000);
            
            cursor = new ILCursor(il);
            
            for (int j = 0; j < 3; j++)
            {
                if (!cursor.TryGotoNext(i => i.MatchLdcI4(12)))
                    return;
            }
            
            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldc_I4, 0);
            
            cursor = new ILCursor(il);
            
            if (!cursor.TryGotoNext(i => i.MatchLdstr("AM")))
                return;

            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldstr, "");
            
            cursor = new ILCursor(il);
            
            if (!cursor.TryGotoNext(i => i.MatchLdstr("PM")))
                return;

            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldstr, "");
        }
    }

    public class GetNewNPCNameIL : ILEdit
    {
        public override bool Autoload() => Translation.IsRussianLanguage;
        
        public override void Load() => IL.Terraria.NPC.getNewNPCName += TranslationTownNpcName;

        public override void Unload() => IL.Terraria.NPC.getNewNPCName -= TranslationTownNpcName;
        
        private void TranslationTownNpcName(ILContext il)
        {
            Translation.ILTranslate(il, "A.N.D.Y", Translation.EncodeToUtf16("Э.Н.Д.И"));
            Translation.ILTranslate(il, "Abdosir", Translation.EncodeToUtf16("Абдозир"));
            Translation.ILTranslate(il, "Abibe", Translation.EncodeToUtf16("Абиб"));
            Translation.ILTranslate(il, "Abigail", Translation.EncodeToUtf16("Эбигейл"));
            Translation.ILTranslate(il, "Abraham", Translation.EncodeToUtf16("Абрахам"));
            Translation.ILTranslate(il, "Abram", Translation.EncodeToUtf16("Абрам"));
            Translation.ILTranslate(il, "Ada", Translation.EncodeToUtf16("Ада"));
            Translation.ILTranslate(il, "Adam", Translation.EncodeToUtf16("Адам"));
            Translation.ILTranslate(il, "Aedan", Translation.EncodeToUtf16("Айдан"));
            Translation.ILTranslate(il, "Agaric", Translation.EncodeToUtf16("Агарик"));
            Translation.ILTranslate(il, "Agnew", Translation.EncodeToUtf16("Агню"));
            Translation.ILTranslate(il, "Ahinadab", Translation.EncodeToUtf16("Ахинадав"));
            Translation.ILTranslate(il, "Ahirom", Translation.EncodeToUtf16("Ахиром"));
            Translation.ILTranslate(il, "Akbar", Translation.EncodeToUtf16("Акбар"));
            Translation.ILTranslate(il, "Alalia", Translation.EncodeToUtf16("Алалия"));
            Translation.ILTranslate(il, "Alalia", Translation.EncodeToUtf16("Алалия"), 2);
            Translation.ILTranslate(il, "Alasdair", Translation.EncodeToUtf16("Аластер"));
            Translation.ILTranslate(il, "Alfred", Translation.EncodeToUtf16("Альфред"));
            Translation.ILTranslate(il, "Alfred", Translation.EncodeToUtf16("Альфред"), 2);
            Translation.ILTranslate(il, "Allison", Translation.EncodeToUtf16("Эллисон"));
            Translation.ILTranslate(il, "Alpha", Translation.EncodeToUtf16("Альфа"));
            Translation.ILTranslate(il, "Alura", Translation.EncodeToUtf16("Алура"));
            Translation.ILTranslate(il, "Amanita", Translation.EncodeToUtf16("Аманита"));
            Translation.ILTranslate(il, "Amy", Translation.EncodeToUtf16("Эми"));
            Translation.ILTranslate(il, "Amy", Translation.EncodeToUtf16("Эми"), 2);
            Translation.ILTranslate(il, "Andre", Translation.EncodeToUtf16("Андре"));
            Translation.ILTranslate(il, "Andrew", Translation.EncodeToUtf16("Эндрю"));
            Translation.ILTranslate(il, "Annabel", Translation.EncodeToUtf16("Аннабель"));
            Translation.ILTranslate(il, "Aphraim", Translation.EncodeToUtf16("Эфрем"));
            Translation.ILTranslate(il, "Arback", Translation.EncodeToUtf16("Арбак"));
            Translation.ILTranslate(il, "Arddun", Translation.EncodeToUtf16("Арддун"));
            Translation.ILTranslate(il, "Ariella", Translation.EncodeToUtf16("Ариэлла"));
            Translation.ILTranslate(il, "Arthur", Translation.EncodeToUtf16("Артур"));
            Translation.ILTranslate(il, "Arwyn", Translation.EncodeToUtf16("Аруин"));
            Translation.ILTranslate(il, "Asher", Translation.EncodeToUtf16("Эшер"));
            Translation.ILTranslate(il, "Autumn", Translation.EncodeToUtf16("Отум"));
            Translation.ILTranslate(il, "Bailey", Translation.EncodeToUtf16("Бэйли"));
            Translation.ILTranslate(il, "Bambi", Translation.EncodeToUtf16("Бэмби"));
            Translation.ILTranslate(il, "Barney", Translation.EncodeToUtf16("Барни"));
            Translation.ILTranslate(il, "Bart", Translation.EncodeToUtf16("Барт"));
            Translation.ILTranslate(il, "Batnoam", Translation.EncodeToUtf16("Батном"));
            Translation.ILTranslate(il, "Bazdin", Translation.EncodeToUtf16("Бэйздин"));
            Translation.ILTranslate(il, "Beldin", Translation.EncodeToUtf16("Бельдин"));
            Translation.ILTranslate(il, "Benjamin", Translation.EncodeToUtf16("Бенджамин"));
            Translation.ILTranslate(il, "Berwyn", Translation.EncodeToUtf16("Беруин"));
            Translation.ILTranslate(il, "Beta", Translation.EncodeToUtf16("Бета"));
            Translation.ILTranslate(il, "Biah", Translation.EncodeToUtf16("Байя"));
            Translation.ILTranslate(il, "Billy Marrows", Translation.EncodeToUtf16("Билли Позвоночник"));
            Translation.ILTranslate(il, "Billy", Translation.EncodeToUtf16("Билли"));
            Translation.ILTranslate(il, "Black Beard", Translation.EncodeToUtf16("Чёрная Борода"));
            Translation.ILTranslate(il, "Blanton", Translation.EncodeToUtf16("Блэнтон"));
            Translation.ILTranslate(il, "Bobby", Translation.EncodeToUtf16("Бобби"));
            Translation.ILTranslate(il, "Bodashtart", Translation.EncodeToUtf16("Бодаштарт"));
            Translation.ILTranslate(il, "Boften", Translation.EncodeToUtf16("Бофтен"));
            Translation.ILTranslate(il, "Bohemas", Translation.EncodeToUtf16("Богемас"));
            Translation.ILTranslate(il, "Bones McGee", Translation.EncodeToUtf16("Костяной Макги"));
            Translation.ILTranslate(il, "Bradley", Translation.EncodeToUtf16("Брэдли"));
            Translation.ILTranslate(il, "Brandon", Translation.EncodeToUtf16("Брэндон"));
            Translation.ILTranslate(il, "Brett", Translation.EncodeToUtf16("Брэтт"));
            Translation.ILTranslate(il, "Bri", Translation.EncodeToUtf16("Бри"));
            Translation.ILTranslate(il, "Brian", Translation.EncodeToUtf16("Брайан"));
            Translation.ILTranslate(il, "Brianne", Translation.EncodeToUtf16("Брианна"));
            Translation.ILTranslate(il, "Brimst", Translation.EncodeToUtf16("Бримст"));
            Translation.ILTranslate(il, "Bronson", Translation.EncodeToUtf16("Бронсон"));
            Translation.ILTranslate(il, "Brooke", Translation.EncodeToUtf16("Брук"));
            Translation.ILTranslate(il, "Bruno", Translation.EncodeToUtf16("Бруно"));
            Translation.ILTranslate(il, "Bryce", Translation.EncodeToUtf16("Брайс"));
            Translation.ILTranslate(il, "Bunny", Translation.EncodeToUtf16("Заинька"));
            Translation.ILTranslate(il, "Caelia", Translation.EncodeToUtf16("Келия"));
            Translation.ILTranslate(il, "Caitlin", Translation.EncodeToUtf16("Катлин"));
            Translation.ILTranslate(il, "Calista", Translation.EncodeToUtf16("Калиста"));
            Translation.ILTranslate(il, "Calvin", Translation.EncodeToUtf16("Кельвин"));
            Translation.ILTranslate(il, "Candy", Translation.EncodeToUtf16("Карамелька"));
            Translation.ILTranslate(il, "Captain Bullywort", Translation.EncodeToUtf16("Капитан Булливорт"));
            Translation.ILTranslate(il, "Captain Morgan", Translation.EncodeToUtf16("Капитан Морган"));
            Translation.ILTranslate(il, "Captain Stoney Dirt", Translation.EncodeToUtf16("Капитан Грязный Камень"));
            Translation.ILTranslate(il, "Carlo", Translation.EncodeToUtf16("Карло"));
            Translation.ILTranslate(il, "Carly", Translation.EncodeToUtf16("Карли"));
            Translation.ILTranslate(il, "Carroll", Translation.EncodeToUtf16("Кэрролл"));
            Translation.ILTranslate(il, "Cedric", Translation.EncodeToUtf16("Седрик"));
            Translation.ILTranslate(il, "Celestia", Translation.EncodeToUtf16("Селестия"));
            Translation.ILTranslate(il, "Chanterelle", Translation.EncodeToUtf16("Лисичка"));
            Translation.ILTranslate(il, "Charles", Translation.EncodeToUtf16("Чарльз"));
            Translation.ILTranslate(il, "Cherry", Translation.EncodeToUtf16("Черри"));
            Translation.ILTranslate(il, "Chester", Translation.EncodeToUtf16("Честер"));
            Translation.ILTranslate(il, "Chryseis", Translation.EncodeToUtf16("Хризис"));
            Translation.ILTranslate(il, "Ci", Translation.EncodeToUtf16("Си"));
            Translation.ILTranslate(il, "Claire", Translation.EncodeToUtf16("Клэр"));
            Translation.ILTranslate(il, "Cleveland", Translation.EncodeToUtf16("Кливленд"));
            Translation.ILTranslate(il, "Clive", Translation.EncodeToUtf16("Клайв"));
            Translation.ILTranslate(il, "Cody", Translation.EncodeToUtf16("Коди"));
            Translation.ILTranslate(il, "Cole", Translation.EncodeToUtf16("Коул"));
            Translation.ILTranslate(il, "Colin", Translation.EncodeToUtf16("Колин"));
            Translation.ILTranslate(il, "Connor", Translation.EncodeToUtf16("Коннор"));
            Translation.ILTranslate(il, "Cornelia", Translation.EncodeToUtf16("Корнелия"));
            Translation.ILTranslate(il, "Cremini", Translation.EncodeToUtf16("Шампиньон"));
            Translation.ILTranslate(il, "Cynthia", Translation.EncodeToUtf16("Синтия"));
            Translation.ILTranslate(il, "Cyril", Translation.EncodeToUtf16("Сайрил"));
            Translation.ILTranslate(il, "Dalamar", Translation.EncodeToUtf16("Даламар"));
            Translation.ILTranslate(il, "Dalek", Translation.EncodeToUtf16("Далек"));
            Translation.ILTranslate(il, "Danel", Translation.EncodeToUtf16("Данел"));
            Translation.ILTranslate(il, "Daniel", Translation.EncodeToUtf16("Дэниел"));
            Translation.ILTranslate(il, "Danny", Translation.EncodeToUtf16("Дэнни"));
            Translation.ILTranslate(il, "Dante", Translation.EncodeToUtf16("Данте"));
            Translation.ILTranslate(il, "Darius", Translation.EncodeToUtf16("Дарий"));
            Translation.ILTranslate(il, "Darnell", Translation.EncodeToUtf16("Дарнелл"));
            Translation.ILTranslate(il, "Darren", Translation.EncodeToUtf16("Даррен"));
            Translation.ILTranslate(il, "Darryl", Translation.EncodeToUtf16("Деррил"));
            Translation.ILTranslate(il, "Darur", Translation.EncodeToUtf16("Дарур"));
            Translation.ILTranslate(il, "Darz", Translation.EncodeToUtf16("Дарз"));
            Translation.ILTranslate(il, "David", Translation.EncodeToUtf16("Дэвид"));
            Translation.ILTranslate(il, "Dawn", Translation.EncodeToUtf16("Заря"));
            Translation.ILTranslate(il, "Dazzle", Translation.EncodeToUtf16("Очаровашка"));
            Translation.ILTranslate(il, "DeAndre", Translation.EncodeToUtf16("ДеАндре"));
            Translation.ILTranslate(il, "Delta", Translation.EncodeToUtf16("Дельта"));
            Translation.ILTranslate(il, "Demetrius", Translation.EncodeToUtf16("Деметрий"));
            Translation.ILTranslate(il, "DeShawn", Translation.EncodeToUtf16("ДеШон"));
            Translation.ILTranslate(il, "Destiny", Translation.EncodeToUtf16("Дестини"));
            Translation.ILTranslate(il, "Dias", Translation.EncodeToUtf16("Диас"));
            Translation.ILTranslate(il, "Dolbere", Translation.EncodeToUtf16("Долбер"));
            Translation.ILTranslate(il, "Dolgen", Translation.EncodeToUtf16("Долген"));
            Translation.ILTranslate(il, "Dolgrim", Translation.EncodeToUtf16("Долгрим"));
            Translation.ILTranslate(il, "Dominique", Translation.EncodeToUtf16("Доминик"));
            Translation.ILTranslate(il, "Duerthen", Translation.EncodeToUtf16("Дюрфен"));
            Translation.ILTranslate(il, "Dulais", Translation.EncodeToUtf16("Дулаш"));
            Translation.ILTranslate(il, "Durim", Translation.EncodeToUtf16("Дурим"));
            Translation.ILTranslate(il, "Durnok", Translation.EncodeToUtf16("Дурнок"));
            Translation.ILTranslate(il, "Dwyer", Translation.EncodeToUtf16("Дуайер"));
            Translation.ILTranslate(il, "Dylan", Translation.EncodeToUtf16("Дилан"));
            Translation.ILTranslate(il, "Edgar", Translation.EncodeToUtf16("Эдгар"));
            Translation.ILTranslate(il, "Edmund", Translation.EncodeToUtf16("Эдмунд"));
            Translation.ILTranslate(il, "Edmund", Translation.EncodeToUtf16("Эдмунд"), 2);
            Translation.ILTranslate(il, "Edward", Translation.EncodeToUtf16("Эдвард"));
            Translation.ILTranslate(il, "Edwin", Translation.EncodeToUtf16("Эдвин"));
            Translation.ILTranslate(il, "Eladon", Translation.EncodeToUtf16("Эладон"));
            Translation.ILTranslate(il, "Ella", Translation.EncodeToUtf16("Элла"));
            Translation.ILTranslate(il, "Ellen", Translation.EncodeToUtf16("Эллен"));
            Translation.ILTranslate(il, "Elric", Translation.EncodeToUtf16("Элрик"));
            Translation.ILTranslate(il, "Elysia", Translation.EncodeToUtf16("Элизия"));
            Translation.ILTranslate(il, "Emeline", Translation.EncodeToUtf16("Эмелин"));
            Translation.ILTranslate(il, "Emerenta", Translation.EncodeToUtf16("Эмерента"));
            Translation.ILTranslate(il, "Emily", Translation.EncodeToUtf16("Эмили"));
            Translation.ILTranslate(il, "Emma", Translation.EncodeToUtf16("Эмма"));
            Translation.ILTranslate(il, "Enoki", Translation.EncodeToUtf16("Опёнок"));
            Translation.ILTranslate(il, "Enzo", Translation.EncodeToUtf16("Энцо"));
            Translation.ILTranslate(il, "Esmeralda", Translation.EncodeToUtf16("Эсмеральда"));
            Translation.ILTranslate(il, "Esreadel", Translation.EncodeToUtf16("Эсридель"));
            Translation.ILTranslate(il, "Eugene", Translation.EncodeToUtf16("Юджин"));
            Translation.ILTranslate(il, "Eustace", Translation.EncodeToUtf16("Юстас"));
            Translation.ILTranslate(il, "Evvie", Translation.EncodeToUtf16("Ивви"));
            Translation.ILTranslate(il, "Fahd", Translation.EncodeToUtf16("Фад"));
            Translation.ILTranslate(il, "Fantasia", Translation.EncodeToUtf16("Фантазия"));
            Translation.ILTranslate(il, "Fantasy", Translation.EncodeToUtf16("Фантазёрка"));
            Translation.ILTranslate(il, "Faye", Translation.EncodeToUtf16("Фэй"));
            Translation.ILTranslate(il, "Felicitae", Translation.EncodeToUtf16("Фелисити"));
            Translation.ILTranslate(il, "Fender", Translation.EncodeToUtf16("Фендер"));
            Translation.ILTranslate(il, "Fidelia", Translation.EncodeToUtf16("Фиделия"));
            Translation.ILTranslate(il, "Fikod", Translation.EncodeToUtf16("Фикод"));
            Translation.ILTranslate(il, "Fillmore", Translation.EncodeToUtf16("Филлмор"));
            Translation.ILTranslate(il, "Finn", Translation.EncodeToUtf16("Финн"));
            Translation.ILTranslate(il, "Fitz", Translation.EncodeToUtf16("Фитц"));
            Translation.ILTranslate(il, "Fizban", Translation.EncodeToUtf16("Физбан"));
            Translation.ILTranslate(il, "Fjell", Translation.EncodeToUtf16("Фьёль"));
            Translation.ILTranslate(il, "Flora", Translation.EncodeToUtf16("Флора"));
            Translation.ILTranslate(il, "Frank", Translation.EncodeToUtf16("Фрэнк"));
            Translation.ILTranslate(il, "Frederick", Translation.EncodeToUtf16("Фредерик"));
            Translation.ILTranslate(il, "Gallius", Translation.EncodeToUtf16("Галлий"));
            Translation.ILTranslate(il, "Gamma", Translation.EncodeToUtf16("Гамма"));
            Translation.ILTranslate(il, "Garrett", Translation.EncodeToUtf16("Гарретт"));
            Translation.ILTranslate(il, "Garval", Translation.EncodeToUtf16("Гарвал"));
            Translation.ILTranslate(il, "Gboto", Translation.EncodeToUtf16("Гбото"));
            Translation.ILTranslate(il, "Gearroid", Translation.EncodeToUtf16("Геррод"));
            Translation.ILTranslate(il, "Gilbert", Translation.EncodeToUtf16("Гилберт"));
            Translation.ILTranslate(il, "Gimli", Translation.EncodeToUtf16("Гимли"));
            Translation.ILTranslate(il, "Gimut", Translation.EncodeToUtf16("Гимут"));
            Translation.ILTranslate(il, "Ginger", Translation.EncodeToUtf16("Джинджер"));
            Translation.ILTranslate(il, "Glitter", Translation.EncodeToUtf16("Блёстка"));
            Translation.ILTranslate(il, "Gloomy Mays", Translation.EncodeToUtf16("Мрачный Мэйс"));
            Translation.ILTranslate(il, "Gnudar", Translation.EncodeToUtf16("Гнудар"));
            Translation.ILTranslate(il, "Graham", Translation.EncodeToUtf16("Грэм"));
            Translation.ILTranslate(il, "Grayson", Translation.EncodeToUtf16("Грейсон"));
            Translation.ILTranslate(il, "Greum", Translation.EncodeToUtf16("Грюм"));
            Translation.ILTranslate(il, "Grodax", Translation.EncodeToUtf16("Гродакс"));
            Translation.ILTranslate(il, "Grover", Translation.EncodeToUtf16("Гровер"));
            Translation.ILTranslate(il, "Guido", Translation.EncodeToUtf16("Гвидо"));
            Translation.ILTranslate(il, "Gunpowder Garry", Translation.EncodeToUtf16("Пороховой Гарри"));
            Translation.ILTranslate(il, "Gus", Translation.EncodeToUtf16("Гас"));
            Translation.ILTranslate(il, "Gwentor", Translation.EncodeToUtf16("Гвентор"));
            Translation.ILTranslate(il, "Hannah", Translation.EncodeToUtf16("Ханна"));
            Translation.ILTranslate(il, "Hannibal", Translation.EncodeToUtf16("Ганнибал"));
            Translation.ILTranslate(il, "Hanno", Translation.EncodeToUtf16("Ганнон"));
            Translation.ILTranslate(il, "Harley", Translation.EncodeToUtf16("Харли"));
            Translation.ILTranslate(il, "Harold", Translation.EncodeToUtf16("Гарольд"));
            Translation.ILTranslate(il, "Harrison", Translation.EncodeToUtf16("Гаррисон"));
            Translation.ILTranslate(il, "Hazel", Translation.EncodeToUtf16("Хэйзел"));
            Translation.ILTranslate(il, "Heather", Translation.EncodeToUtf16("Хэйзер"));
            Translation.ILTranslate(il, "Helen", Translation.EncodeToUtf16("Хелен"));
            Translation.ILTranslate(il, "Henry", Translation.EncodeToUtf16("Генри"));
            Translation.ILTranslate(il, "Herald", Translation.EncodeToUtf16("Геральд"));
            Translation.ILTranslate(il, "Herbert", Translation.EncodeToUtf16("Герберт"));
            Translation.ILTranslate(il, "Hirael", Translation.EncodeToUtf16("Хираэль"));
            Translation.ILTranslate(il, "Hiram", Translation.EncodeToUtf16("Хирам"));
            Translation.ILTranslate(il, "Holly", Translation.EncodeToUtf16("Холли"));
            Translation.ILTranslate(il, "Hope", Translation.EncodeToUtf16("Хоуп"));
            Translation.ILTranslate(il, "Howard", Translation.EncodeToUtf16("Говард"));
            Translation.ILTranslate(il, "Humphrey", Translation.EncodeToUtf16("Хамфри"));
            Translation.ILTranslate(il, "Iris", Translation.EncodeToUtf16("Айрис"));
            Translation.ILTranslate(il, "Isaac", Translation.EncodeToUtf16("Айзек"));
            Translation.ILTranslate(il, "Isabella", Translation.EncodeToUtf16("Изабелла"));
            Translation.ILTranslate(il, "Isis", Translation.EncodeToUtf16("Айзис"));
            Translation.ILTranslate(il, "Isis", Translation.EncodeToUtf16("Айзис"), 2);
            Translation.ILTranslate(il, "Ivan", Translation.EncodeToUtf16("Айвен"));
            Translation.ILTranslate(il, "Izzy", Translation.EncodeToUtf16("Иззи"));
            Translation.ILTranslate(il, "Jack Sellington", Translation.EncodeToUtf16("Джек Селлингтон"));
            Translation.ILTranslate(il, "Jack", Translation.EncodeToUtf16("Джек"));
            Translation.ILTranslate(il, "Jack", Translation.EncodeToUtf16("Джек"), 2);
            Translation.ILTranslate(il, "Jacob", Translation.EncodeToUtf16("Джейкоб"));
            Translation.ILTranslate(il, "Jake", Translation.EncodeToUtf16("Джейк"));
            Translation.ILTranslate(il, "Jake", Translation.EncodeToUtf16("Джейк"), 2);
            Translation.ILTranslate(il, "Jalen", Translation.EncodeToUtf16("Джален"));
            Translation.ILTranslate(il, "Jamal", Translation.EncodeToUtf16("Джамал"));
            Translation.ILTranslate(il, "James", Translation.EncodeToUtf16("Джеймс"));
            Translation.ILTranslate(il, "James T. Beard", Translation.EncodeToUtf16("Джеймс Т. Борода"));
            Translation.ILTranslate(il, "Jamundi", Translation.EncodeToUtf16("Хамунди"));
            Translation.ILTranslate(il, "Jarut", Translation.EncodeToUtf16("Джарут"));
            Translation.ILTranslate(il, "Jeff", Translation.EncodeToUtf16("Джефф"));
            Translation.ILTranslate(il, "Jeffrey", Translation.EncodeToUtf16("Джеффри"));
            Translation.ILTranslate(il, "Jenna", Translation.EncodeToUtf16("Дженна"));
            Translation.ILTranslate(il, "Jenny", Translation.EncodeToUtf16("Дженни"));
            Translation.ILTranslate(il, "Jey", Translation.EncodeToUtf16("Джей"));
            Translation.ILTranslate(il, "Jimmy", Translation.EncodeToUtf16("Джимми"));
            Translation.ILTranslate(il, "Joe", Translation.EncodeToUtf16("Джо"));
            Translation.ILTranslate(il, "Johnny", Translation.EncodeToUtf16("Джонни"));
            Translation.ILTranslate(il, "Joseph", Translation.EncodeToUtf16("Джозеф"));
            Translation.ILTranslate(il, "Judith", Translation.EncodeToUtf16("Джудит"));
            Translation.ILTranslate(il, "Kaitlin", Translation.EncodeToUtf16("Кэтлин"));
            Translation.ILTranslate(il, "Kaitlyn", Translation.EncodeToUtf16("Кейтлин"));
            Translation.ILTranslate(il, "Kanmi", Translation.EncodeToUtf16("Канми"));
            Translation.ILTranslate(il, "Kappa", Translation.EncodeToUtf16("Каппа"));
            Translation.ILTranslate(il, "Katelyn", Translation.EncodeToUtf16("Кейтилин"));
            Translation.ILTranslate(il, "Katherine", Translation.EncodeToUtf16("Кейтрин"));
            Translation.ILTranslate(il, "Kathryn", Translation.EncodeToUtf16("Катрин"));
            Translation.ILTranslate(il, "Kati", Translation.EncodeToUtf16("Кати"));
            Translation.ILTranslate(il, "Katie", Translation.EncodeToUtf16("Кейти"));
            Translation.ILTranslate(il, "Kayla", Translation.EncodeToUtf16("Кайла"));
            Translation.ILTranslate(il, "Kayla", Translation.EncodeToUtf16("Кайла"), 2);
            Translation.ILTranslate(il, "Kevin", Translation.EncodeToUtf16("Кевин"));
            Translation.ILTranslate(il, "Knogs", Translation.EncodeToUtf16("Ногс"));
            Translation.ILTranslate(il, "Knub", Translation.EncodeToUtf16("Наб"));
            Translation.ILTranslate(il, "Kogi-ghi", Translation.EncodeToUtf16("Коги-гхи"));
            Translation.ILTranslate(il, "Konah", Translation.EncodeToUtf16("Кона"));
            Translation.ILTranslate(il, "Korrie", Translation.EncodeToUtf16("Корри"));
            Translation.ILTranslate(il, "Kyle", Translation.EncodeToUtf16("Кайл"));
            Translation.ILTranslate(il, "Kylie", Translation.EncodeToUtf16("Кайли"));
            Translation.ILTranslate(il, "Lambda", Translation.EncodeToUtf16("Лямбда"));
            Translation.ILTranslate(il, "Lauren", Translation.EncodeToUtf16("Лорен"));
            Translation.ILTranslate(il, "Leila", Translation.EncodeToUtf16("Лейла"));
            Translation.ILTranslate(il, "Leomund", Translation.EncodeToUtf16("Леомунд"));
            Translation.ILTranslate(il, "Leonardo", Translation.EncodeToUtf16("Леонардо"));
            Translation.ILTranslate(il, "Levi", Translation.EncodeToUtf16("Леви"));
            Translation.ILTranslate(il, "Lexus", Translation.EncodeToUtf16("Лексус"));
            Translation.ILTranslate(il, "Lilly", Translation.EncodeToUtf16("Лили"));
            Translation.ILTranslate(il, "Lincoln", Translation.EncodeToUtf16("Линкольн"));
            Translation.ILTranslate(il, "Lisa", Translation.EncodeToUtf16("Лиза"));
            Translation.ILTranslate(il, "Llewellyn", Translation.EncodeToUtf16("Ллеуэллин"));
            Translation.ILTranslate(il, "Lloyd", Translation.EncodeToUtf16("Ллойд"));
            Translation.ILTranslate(il, "Lloyd", Translation.EncodeToUtf16("Ллойд"), 2);
            Translation.ILTranslate(il, "Logan", Translation.EncodeToUtf16("Логан"));
            Translation.ILTranslate(il, "Lola", Translation.EncodeToUtf16("Лола"));
            Translation.ILTranslate(il, "Lorenzo", Translation.EncodeToUtf16("Лоренцо"));
            Translation.ILTranslate(il, "Lorraine", Translation.EncodeToUtf16("Лоррейн"));
            Translation.ILTranslate(il, "Louis", Translation.EncodeToUtf16("Луис"));
            Translation.ILTranslate(il, "Luca", Translation.EncodeToUtf16("Лука"));
            Translation.ILTranslate(il, "Luciano", Translation.EncodeToUtf16("Лучиано"));
            Translation.ILTranslate(il, "Ludo", Translation.EncodeToUtf16("Людо"));
            Translation.ILTranslate(il, "Luigi", Translation.EncodeToUtf16("Луиджи"));
            Translation.ILTranslate(il, "Luke", Translation.EncodeToUtf16("Люк"));
            Translation.ILTranslate(il, "Lunette", Translation.EncodeToUtf16("Люнетт"));
            Translation.ILTranslate(il, "Lydia", Translation.EncodeToUtf16("Лидия"));
            Translation.ILTranslate(il, "Lyndon", Translation.EncodeToUtf16("Линдон"));
            Translation.ILTranslate(il, "Madeline", Translation.EncodeToUtf16("Мэделин"));
            Translation.ILTranslate(il, "Maelor", Translation.EncodeToUtf16("Маэлор"));
            Translation.ILTranslate(il, "Magius", Translation.EncodeToUtf16("Магиус"));
            Translation.ILTranslate(il, "Maitake", Translation.EncodeToUtf16("Грифола"));
            Translation.ILTranslate(il, "Malik", Translation.EncodeToUtf16("Малик"));
            Translation.ILTranslate(il, "Mandible Calavera", Translation.EncodeToUtf16("Челюстной Калавера"));
            Translation.ILTranslate(il, "Marco", Translation.EncodeToUtf16("Марко"));
            Translation.ILTranslate(il, "Mario", Translation.EncodeToUtf16("Марио"));
            Translation.ILTranslate(il, "Marquis", Translation.EncodeToUtf16("Маркис"));
            Translation.ILTranslate(il, "Marshanna", Translation.EncodeToUtf16("Маршанна"));
            Translation.ILTranslate(il, "Martino", Translation.EncodeToUtf16("Мартино"));
            Translation.ILTranslate(il, "Marty", Translation.EncodeToUtf16("Марти"));
            Translation.ILTranslate(il, "Matty", Translation.EncodeToUtf16("Мэтти"));
            Translation.ILTranslate(il, "Maurice", Translation.EncodeToUtf16("Морис"));
            Translation.ILTranslate(il, "Mauro", Translation.EncodeToUtf16("Мауро"));
            Translation.ILTranslate(il, "Maxwell", Translation.EncodeToUtf16("Максвелл"));
            Translation.ILTranslate(il, "McKinly", Translation.EncodeToUtf16("Мак-Кинли"));
            Translation.ILTranslate(il, "Meliyah", Translation.EncodeToUtf16("Мелия"));
            Translation.ILTranslate(il, "Mercer", Translation.EncodeToUtf16("Мерсер"));
            Translation.ILTranslate(il, "Meredith", Translation.EncodeToUtf16("Мередит"));
            Translation.ILTranslate(il, "Merlyn", Translation.EncodeToUtf16("Мерлин"));
            Translation.ILTranslate(il, "Mervyn", Translation.EncodeToUtf16("Мервин"));
            Translation.ILTranslate(il, "Mika", Translation.EncodeToUtf16("Мика"));
            Translation.ILTranslate(il, "Miles", Translation.EncodeToUtf16("Майлз"));
            Translation.ILTranslate(il, "Millard", Translation.EncodeToUtf16("Миллард"));
            Translation.ILTranslate(il, "Milton", Translation.EncodeToUtf16("Милтон"));
            Translation.ILTranslate(il, "Minerva", Translation.EncodeToUtf16("Минерва"));
            Translation.ILTranslate(il, "Mobart", Translation.EncodeToUtf16("Мобарт"));
            Translation.ILTranslate(il, "Molly", Translation.EncodeToUtf16("Молли"));
            Translation.ILTranslate(il, "Morel", Translation.EncodeToUtf16("Сморчок"));
            Translation.ILTranslate(il, "Morthal", Translation.EncodeToUtf16("Морфал"));
            Translation.ILTranslate(il, "Mortimer", Translation.EncodeToUtf16("Мортимер"));
            Translation.ILTranslate(il, "Mrunok", Translation.EncodeToUtf16("Мрунок"));
            Translation.ILTranslate(il, "Mu", Translation.EncodeToUtf16("Мю"));
            Translation.ILTranslate(il, "Muscaria", Translation.EncodeToUtf16("Мухомор"));
            Translation.ILTranslate(il, "Nancy", Translation.EncodeToUtf16("Нэнси"));
            Translation.ILTranslate(il, "Nata", Translation.EncodeToUtf16("Ната"));
            Translation.ILTranslate(il, "Nathan", Translation.EncodeToUtf16("Нейтан"));
            Translation.ILTranslate(il, "Negurk", Translation.EncodeToUtf16("Негурк"));
            Translation.ILTranslate(il, "Nigel", Translation.EncodeToUtf16("Найджел"));
            Translation.ILTranslate(il, "Niner-7", Translation.EncodeToUtf16("Девятый-7"));
            Translation.ILTranslate(il, "Ningauble", Translation.EncodeToUtf16("Нингобль"));
            Translation.ILTranslate(il, "Nissa", Translation.EncodeToUtf16("Нисса"));
            Translation.ILTranslate(il, "No-Eyed Wiley", Translation.EncodeToUtf16("Безглазый Уайли"));
            Translation.ILTranslate(il, "Norkas", Translation.EncodeToUtf16("Норкас"));
            Translation.ILTranslate(il, "Norsun", Translation.EncodeToUtf16("Норсун"));
            Translation.ILTranslate(il, "Nort", Translation.EncodeToUtf16("Норт"));
            Translation.ILTranslate(il, "Nu", Translation.EncodeToUtf16("Ню"));
            Translation.ILTranslate(il, "Nuxatk", Translation.EncodeToUtf16("Нузатк"));
            Translation.ILTranslate(il, "Omega", Translation.EncodeToUtf16("Омега"));
            Translation.ILTranslate(il, "Omicron", Translation.EncodeToUtf16("Омикрон"));
            Translation.ILTranslate(il, "Opuni", Translation.EncodeToUtf16("Опуни"));
            Translation.ILTranslate(il, "Oten", Translation.EncodeToUtf16("Оутен"));
            Translation.ILTranslate(il, "Ovbere", Translation.EncodeToUtf16("Овбер"));
            Translation.ILTranslate(il, "Paris", Translation.EncodeToUtf16("Пэрис"));
            Translation.ILTranslate(il, "Pearl", Translation.EncodeToUtf16("Пёрл"));
            Translation.ILTranslate(il, "Petra", Translation.EncodeToUtf16("Петра"));
            Translation.ILTranslate(il, "Phi", Translation.EncodeToUtf16("Пи"));
            Translation.ILTranslate(il, "Phi", Translation.EncodeToUtf16("Пи"), 2);
            Translation.ILTranslate(il, "Phillip", Translation.EncodeToUtf16("Филлип"));
            Translation.ILTranslate(il, "Philosir", Translation.EncodeToUtf16("Филозир"));
            Translation.ILTranslate(il, "Phoebe", Translation.EncodeToUtf16("Фиби"));
            Translation.ILTranslate(il, "Pip", Translation.EncodeToUtf16("Пип"));
            Translation.ILTranslate(il, "Porcini", Translation.EncodeToUtf16("Боровик"));
            Translation.ILTranslate(il, "Ragz", Translation.EncodeToUtf16("Рагз"));
            Translation.ILTranslate(il, "Ralph", Translation.EncodeToUtf16("Ральф"));
            Translation.ILTranslate(il, "Raphael", Translation.EncodeToUtf16("Рафаэль"));
            Translation.ILTranslate(il, "Rattles Magoo", Translation.EncodeToUtf16("Гремящий Магу"));
            Translation.ILTranslate(il, "Rawleigh", Translation.EncodeToUtf16("Роули"));
            Translation.ILTranslate(il, "Red Beard", Translation.EncodeToUtf16("Рыжебородый"));
            Translation.ILTranslate(il, "Reginald", Translation.EncodeToUtf16("Реджинальд"));
            Translation.ILTranslate(il, "Reishi", Translation.EncodeToUtf16("Трутовик"));
            Translation.ILTranslate(il, "Rho", Translation.EncodeToUtf16("Ро"));
            Translation.ILTranslate(il, "Riley", Translation.EncodeToUtf16("Райли"));
            Translation.ILTranslate(il, "Rodney", Translation.EncodeToUtf16("Родни"));
            Translation.ILTranslate(il, "Rodrick", Translation.EncodeToUtf16("Родрик"));
            Translation.ILTranslate(il, "Roland", Translation.EncodeToUtf16("Роланд"));
            Translation.ILTranslate(il, "Romeo", Translation.EncodeToUtf16("Ромео"));
            Translation.ILTranslate(il, "Ronald", Translation.EncodeToUtf16("Рональд"));
            Translation.ILTranslate(il, "Rosalva", Translation.EncodeToUtf16("Розалва"));
            Translation.ILTranslate(il, "Rox", Translation.EncodeToUtf16("Рокс"));
            Translation.ILTranslate(il, "Roxanne", Translation.EncodeToUtf16("Роксана"));
            Translation.ILTranslate(il, "Ruby", Translation.EncodeToUtf16("Руби"));
            Translation.ILTranslate(il, "Rupert", Translation.EncodeToUtf16("Руперт"));
            Translation.ILTranslate(il, "Rutherford", Translation.EncodeToUtf16("Ратерфорд"));
            Translation.ILTranslate(il, "Ryan", Translation.EncodeToUtf16("Райан"));
            Translation.ILTranslate(il, "Sally", Translation.EncodeToUtf16("Салли"));
            Translation.ILTranslate(il, "Sammy", Translation.EncodeToUtf16("Сэмми"));
            Translation.ILTranslate(il, "Sargon", Translation.EncodeToUtf16("Саргон"));
            Translation.ILTranslate(il, "Sarx", Translation.EncodeToUtf16("Саркс"));
            Translation.ILTranslate(il, "Savannah", Translation.EncodeToUtf16("Саванна"));
            Translation.ILTranslate(il, "Scarlett", Translation.EncodeToUtf16("Скарлетт"));
            Translation.ILTranslate(il, "Scott", Translation.EncodeToUtf16("Скотт"));
            Translation.ILTranslate(il, "Sebastian", Translation.EncodeToUtf16("Себастьян"));
            Translation.ILTranslate(il, "Selah", Translation.EncodeToUtf16("Сэла"));
            Translation.ILTranslate(il, "Selene", Translation.EncodeToUtf16("Селена"));
            Translation.ILTranslate(il, "Selina", Translation.EncodeToUtf16("Селина"));
            Translation.ILTranslate(il, "Seonag", Translation.EncodeToUtf16("Шонаг"));
            Translation.ILTranslate(il, "Seth", Translation.EncodeToUtf16("Сет"));
            Translation.ILTranslate(il, "Seymour", Translation.EncodeToUtf16("Сеймур"));
            Translation.ILTranslate(il, "Shayna", Translation.EncodeToUtf16("Шайна"));
            Translation.ILTranslate(il, "Shea", Translation.EncodeToUtf16("Шия"));
            Translation.ILTranslate(il, "Sheena", Translation.EncodeToUtf16("Шина"));
            Translation.ILTranslate(il, "Shiitake", Translation.EncodeToUtf16("Лентинула"));
            Translation.ILTranslate(il, "Shimeji", Translation.EncodeToUtf16("Рядовка"));
            Translation.ILTranslate(il, "Shipton", Translation.EncodeToUtf16("Шиптон"));
            Translation.ILTranslate(il, "Shirlena", Translation.EncodeToUtf16("Ширлена"));
            Translation.ILTranslate(il, "Sigma", Translation.EncodeToUtf16("Сигма"));
            Translation.ILTranslate(il, "Sikarbaal", Translation.EncodeToUtf16("Сикарбаал"));
            Translation.ILTranslate(il, "Simon", Translation.EncodeToUtf16("Саймон"));
            Translation.ILTranslate(il, "Skellington", Translation.EncodeToUtf16("Скеллингтон"));
            Translation.ILTranslate(il, "Smador", Translation.EncodeToUtf16("Смадор"));
            Translation.ILTranslate(il, "Sophia", Translation.EncodeToUtf16("София"));
            Translation.ILTranslate(il, "Sparkle", Translation.EncodeToUtf16("Искорка"));
            Translation.ILTranslate(il, "Spencer", Translation.EncodeToUtf16("Спенсер"));
            Translation.ILTranslate(il, "Star", Translation.EncodeToUtf16("Звёздочка"));
            Translation.ILTranslate(il, "Stazen", Translation.EncodeToUtf16("Стацен"));
            Translation.ILTranslate(il, "Stefano", Translation.EncodeToUtf16("Стефано"));
            Translation.ILTranslate(il, "Stella", Translation.EncodeToUtf16("Стелла"));
            Translation.ILTranslate(il, "Steve", Translation.EncodeToUtf16("Стив"));
            Translation.ILTranslate(il, "Stezom", Translation.EncodeToUtf16("Стезом"));
            Translation.ILTranslate(il, "Sugar", Translation.EncodeToUtf16("Милашка"));
            Translation.ILTranslate(il, "Susana", Translation.EncodeToUtf16("Сюзанна"));
            Translation.ILTranslate(il, "Syn-X", Translation.EncodeToUtf16("Син-Х"));
            Translation.ILTranslate(il, "T-3E0", Translation.EncodeToUtf16("Т-3Е0"));
            Translation.ILTranslate(il, "Tabnit", Translation.EncodeToUtf16("Табнит"));
            Translation.ILTranslate(il, "Tagar", Translation.EncodeToUtf16("Тагар"));
            Translation.ILTranslate(il, "Tairona", Translation.EncodeToUtf16("Тайрона"));
            Translation.ILTranslate(il, "Tallulah", Translation.EncodeToUtf16("Таллула"));
            Translation.ILTranslate(il, "Tania", Translation.EncodeToUtf16("Таня"));
            Translation.ILTranslate(il, "Tanner", Translation.EncodeToUtf16("Таннер"));
            Translation.ILTranslate(il, "Tatiana", Translation.EncodeToUtf16("Татьяна"));
            Translation.ILTranslate(il, "Terra", Translation.EncodeToUtf16("Терра"));
            Translation.ILTranslate(il, "Terrance", Translation.EncodeToUtf16("Терренс"));
            Translation.ILTranslate(il, "Terrell", Translation.EncodeToUtf16("Террелл"));
            Translation.ILTranslate(il, "Tgerd", Translation.EncodeToUtf16("Тгерд"));
            Translation.ILTranslate(il, "Theodore", Translation.EncodeToUtf16("Теодор"));
            Translation.ILTranslate(il, "Theta", Translation.EncodeToUtf16("Тета"));
            Translation.ILTranslate(il, "Timmy", Translation.EncodeToUtf16("Тимми"));
            Translation.ILTranslate(il, "Tkanus", Translation.EncodeToUtf16("Тканус"));
            Translation.ILTranslate(il, "Tom", Translation.EncodeToUtf16("Том"));
            Translation.ILTranslate(il, "Tony", Translation.EncodeToUtf16("Тони"));
            Translation.ILTranslate(il, "Tordak", Translation.EncodeToUtf16("Тордак"));
            Translation.ILTranslate(il, "Trent", Translation.EncodeToUtf16("Трент"));
            Translation.ILTranslate(il, "Trevon", Translation.EncodeToUtf16("Тревон"));
            Translation.ILTranslate(il, "Trisha", Translation.EncodeToUtf16("Триша"));
            Translation.ILTranslate(il, "Trixy", Translation.EncodeToUtf16("Проказница"));
            Translation.ILTranslate(il, "Trogem", Translation.EncodeToUtf16("Трогем"));
            Translation.ILTranslate(il, "Tweed", Translation.EncodeToUtf16("Твид"));
            Translation.ILTranslate(il, "Tyler", Translation.EncodeToUtf16("Тайлер"));
            Translation.ILTranslate(il, "Tyrone", Translation.EncodeToUtf16("Тайрон"));
            Translation.ILTranslate(il, "U'wa", Translation.EncodeToUtf16("У'ва"));
            Translation.ILTranslate(il, "Upsilon", Translation.EncodeToUtf16("Ипсилон"));
            Translation.ILTranslate(il, "Urist", Translation.EncodeToUtf16("Урист"));
            Translation.ILTranslate(il, "Verity", Translation.EncodeToUtf16("Верити"));
            Translation.ILTranslate(il, "Vivian", Translation.EncodeToUtf16("Вивиан"));
            Translation.ILTranslate(il, "Walter", Translation.EncodeToUtf16("Уолтер"));
            Translation.ILTranslate(il, "Warren", Translation.EncodeToUtf16("Уоррен"));
            Translation.ILTranslate(il, "Wet Beard", Translation.EncodeToUtf16("Мокрая Борода"));
            Translation.ILTranslate(il, "Whitney", Translation.EncodeToUtf16("Уитни"));
            Translation.ILTranslate(il, "Wilbur", Translation.EncodeToUtf16("Уилбур"));
            Translation.ILTranslate(il, "Willie", Translation.EncodeToUtf16("Уилли"));
            Translation.ILTranslate(il, "Willy", Translation.EncodeToUtf16("Уилли"));
            Translation.ILTranslate(il, "Woodrow", Translation.EncodeToUtf16("Вудро"));
            Translation.ILTranslate(il, "Wyatt", Translation.EncodeToUtf16("Уайатт"));
            Translation.ILTranslate(il, "Xanadu", Translation.EncodeToUtf16("Занаду"));
            Translation.ILTranslate(il, "Xanos", Translation.EncodeToUtf16("Ксанос"));
            Translation.ILTranslate(il, "Xavier", Translation.EncodeToUtf16("Ксавьер"));
            Translation.ILTranslate(il, "Xirigua", Translation.EncodeToUtf16("Зиригуа"));
            Translation.ILTranslate(il, "Xon", Translation.EncodeToUtf16("Ксон"));
            Translation.ILTranslate(il, "Xylia", Translation.EncodeToUtf16("Силия"));
            Translation.ILTranslate(il, "Yehomilk", Translation.EncodeToUtf16("Йехомилк"));
            Translation.ILTranslate(il, "Yutpan", Translation.EncodeToUtf16("Ютпан"));
            Translation.ILTranslate(il, "Zach", Translation.EncodeToUtf16("Зак"));
            Translation.ILTranslate(il, "Zelda", Translation.EncodeToUtf16("Зельда"));
            Translation.ILTranslate(il, "Zeta", Translation.EncodeToUtf16("Дзета"));
            Translation.ILTranslate(il, "Zop'a", Translation.EncodeToUtf16("Зопа"));
            Translation.ILTranslate(il, "Zylphia", Translation.EncodeToUtf16("Зильфия"));
        }
    }
}