using CalamityRuTranslate.Common;
using CalamityRuTranslate.Common.Utilities;
using Mono.Cecil.Cil;
using MonoMod.Cil;

namespace CalamityRuTranslate.Vanilla
{
    public class DrawInfoAccsIL : ILEdit
    {
        public override bool Autoload() => TranslationUtils.IsRussianLanguage;

        public override void Load() => IL.Terraria.Main.DrawInfoAccs += ChangeDrawInfoAccs;

        public override void Unload() => IL.Terraria.Main.DrawInfoAccs -= ChangeDrawInfoAccs;

        private void ChangeDrawInfoAccs(ILContext il)
        {
            ILCursor cursor = new ILCursor(il);

            for (int j = 0; j < 1; j++)
            {
                if (!cursor.TryGotoNext(i => i.MatchLdcI4(12)))
                    return;
            }
            
            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldc_I4, 1000);
            
            cursor = new ILCursor(il);
            
            for (int j = 0; j < 3; j++)
            {
                if (!cursor.TryGotoNext(i => i.MatchLdcI4(12)))
                    return;
            }
            
            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldc_I4, 0);
            
            cursor = new ILCursor(il);
            
            if (!cursor.TryGotoNext(i => i.MatchLdstr("AM")))
                return;

            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldstr, "");
            
            cursor = new ILCursor(il);
            
            if (!cursor.TryGotoNext(i => i.MatchLdstr("PM")))
                return;

            cursor.Index++;
            cursor.Emit(OpCodes.Pop);
            cursor.Emit(OpCodes.Ldstr, "");
        }
    }

    public class GetNewNPCNameIL : ILEdit
    {
        public override bool Autoload() => TranslationUtils.IsRussianLanguage;
        
        public override void Load() => IL.Terraria.NPC.getNewNPCName += TranslationTownNpcName;

        public override void Unload() => IL.Terraria.NPC.getNewNPCName -= TranslationTownNpcName;
        
        private void TranslationTownNpcName(ILContext il)
        {
            TranslationUtils.ILTranslate(il, "A.N.D.Y", TranslationUtils.EncodeToUtf16("Э.Н.Д.И"));
            TranslationUtils.ILTranslate(il, "Abdosir", TranslationUtils.EncodeToUtf16("Абдозир"));
            TranslationUtils.ILTranslate(il, "Abibe", TranslationUtils.EncodeToUtf16("Абиб"));
            TranslationUtils.ILTranslate(il, "Abigail", TranslationUtils.EncodeToUtf16("Эбигейл"));
            TranslationUtils.ILTranslate(il, "Abraham", TranslationUtils.EncodeToUtf16("Абрахам"));
            TranslationUtils.ILTranslate(il, "Abram", TranslationUtils.EncodeToUtf16("Абрам"));
            TranslationUtils.ILTranslate(il, "Ada", TranslationUtils.EncodeToUtf16("Ада"));
            TranslationUtils.ILTranslate(il, "Adam", TranslationUtils.EncodeToUtf16("Адам"));
            TranslationUtils.ILTranslate(il, "Aedan", TranslationUtils.EncodeToUtf16("Айдан"));
            TranslationUtils.ILTranslate(il, "Agaric", TranslationUtils.EncodeToUtf16("Агарик"));
            TranslationUtils.ILTranslate(il, "Agnew", TranslationUtils.EncodeToUtf16("Агню"));
            TranslationUtils.ILTranslate(il, "Ahinadab", TranslationUtils.EncodeToUtf16("Ахинадав"));
            TranslationUtils.ILTranslate(il, "Ahirom", TranslationUtils.EncodeToUtf16("Ахиром"));
            TranslationUtils.ILTranslate(il, "Akbar", TranslationUtils.EncodeToUtf16("Акбар"));
            TranslationUtils.ILTranslate(il, "Alalia", TranslationUtils.EncodeToUtf16("Алалия"));
            TranslationUtils.ILTranslate(il, "Alalia", TranslationUtils.EncodeToUtf16("Алалия"), 2);
            TranslationUtils.ILTranslate(il, "Alasdair", TranslationUtils.EncodeToUtf16("Аластер"));
            TranslationUtils.ILTranslate(il, "Alfred", TranslationUtils.EncodeToUtf16("Альфред"));
            TranslationUtils.ILTranslate(il, "Alfred", TranslationUtils.EncodeToUtf16("Альфред"), 2);
            TranslationUtils.ILTranslate(il, "Allison", TranslationUtils.EncodeToUtf16("Эллисон"));
            TranslationUtils.ILTranslate(il, "Alpha", TranslationUtils.EncodeToUtf16("Альфа"));
            TranslationUtils.ILTranslate(il, "Alura", TranslationUtils.EncodeToUtf16("Алура"));
            TranslationUtils.ILTranslate(il, "Amanita", TranslationUtils.EncodeToUtf16("Аманита"));
            TranslationUtils.ILTranslate(il, "Amy", TranslationUtils.EncodeToUtf16("Эми"));
            TranslationUtils.ILTranslate(il, "Amy", TranslationUtils.EncodeToUtf16("Эми"), 2);
            TranslationUtils.ILTranslate(il, "Andre", TranslationUtils.EncodeToUtf16("Андре"));
            TranslationUtils.ILTranslate(il, "Andrew", TranslationUtils.EncodeToUtf16("Эндрю"));
            TranslationUtils.ILTranslate(il, "Annabel", TranslationUtils.EncodeToUtf16("Аннабель"));
            TranslationUtils.ILTranslate(il, "Aphraim", TranslationUtils.EncodeToUtf16("Эфрем"));
            TranslationUtils.ILTranslate(il, "Arback", TranslationUtils.EncodeToUtf16("Арбак"));
            TranslationUtils.ILTranslate(il, "Arddun", TranslationUtils.EncodeToUtf16("Арддун"));
            TranslationUtils.ILTranslate(il, "Ariella", TranslationUtils.EncodeToUtf16("Ариэлла"));
            TranslationUtils.ILTranslate(il, "Arthur", TranslationUtils.EncodeToUtf16("Артур"));
            TranslationUtils.ILTranslate(il, "Arwyn", TranslationUtils.EncodeToUtf16("Аруин"));
            TranslationUtils.ILTranslate(il, "Asher", TranslationUtils.EncodeToUtf16("Эшер"));
            TranslationUtils.ILTranslate(il, "Autumn", TranslationUtils.EncodeToUtf16("Отум"));
            TranslationUtils.ILTranslate(il, "Bailey", TranslationUtils.EncodeToUtf16("Бэйли"));
            TranslationUtils.ILTranslate(il, "Bambi", TranslationUtils.EncodeToUtf16("Бэмби"));
            TranslationUtils.ILTranslate(il, "Barney", TranslationUtils.EncodeToUtf16("Барни"));
            TranslationUtils.ILTranslate(il, "Bart", TranslationUtils.EncodeToUtf16("Барт"));
            TranslationUtils.ILTranslate(il, "Batnoam", TranslationUtils.EncodeToUtf16("Батном"));
            TranslationUtils.ILTranslate(il, "Bazdin", TranslationUtils.EncodeToUtf16("Бэйздин"));
            TranslationUtils.ILTranslate(il, "Beldin", TranslationUtils.EncodeToUtf16("Бельдин"));
            TranslationUtils.ILTranslate(il, "Benjamin", TranslationUtils.EncodeToUtf16("Бенджамин"));
            TranslationUtils.ILTranslate(il, "Berwyn", TranslationUtils.EncodeToUtf16("Беруин"));
            TranslationUtils.ILTranslate(il, "Beta", TranslationUtils.EncodeToUtf16("Бета"));
            TranslationUtils.ILTranslate(il, "Biah", TranslationUtils.EncodeToUtf16("Байя"));
            TranslationUtils.ILTranslate(il, "Billy Marrows", TranslationUtils.EncodeToUtf16("Билли Позвоночник"));
            TranslationUtils.ILTranslate(il, "Billy", TranslationUtils.EncodeToUtf16("Билли"));
            TranslationUtils.ILTranslate(il, "Black Beard", TranslationUtils.EncodeToUtf16("Чёрная Борода"));
            TranslationUtils.ILTranslate(il, "Blanton", TranslationUtils.EncodeToUtf16("Блэнтон"));
            TranslationUtils.ILTranslate(il, "Bobby", TranslationUtils.EncodeToUtf16("Бобби"));
            TranslationUtils.ILTranslate(il, "Bodashtart", TranslationUtils.EncodeToUtf16("Бодаштарт"));
            TranslationUtils.ILTranslate(il, "Boften", TranslationUtils.EncodeToUtf16("Бофтен"));
            TranslationUtils.ILTranslate(il, "Bohemas", TranslationUtils.EncodeToUtf16("Богемас"));
            TranslationUtils.ILTranslate(il, "Bones McGee", TranslationUtils.EncodeToUtf16("Костяной Макги"));
            TranslationUtils.ILTranslate(il, "Bradley", TranslationUtils.EncodeToUtf16("Брэдли"));
            TranslationUtils.ILTranslate(il, "Brandon", TranslationUtils.EncodeToUtf16("Брэндон"));
            TranslationUtils.ILTranslate(il, "Brett", TranslationUtils.EncodeToUtf16("Брэтт"));
            TranslationUtils.ILTranslate(il, "Bri", TranslationUtils.EncodeToUtf16("Бри"));
            TranslationUtils.ILTranslate(il, "Brian", TranslationUtils.EncodeToUtf16("Брайан"));
            TranslationUtils.ILTranslate(il, "Brianne", TranslationUtils.EncodeToUtf16("Брианна"));
            TranslationUtils.ILTranslate(il, "Brimst", TranslationUtils.EncodeToUtf16("Бримст"));
            TranslationUtils.ILTranslate(il, "Bronson", TranslationUtils.EncodeToUtf16("Бронсон"));
            TranslationUtils.ILTranslate(il, "Brooke", TranslationUtils.EncodeToUtf16("Брук"));
            TranslationUtils.ILTranslate(il, "Bruno", TranslationUtils.EncodeToUtf16("Бруно"));
            TranslationUtils.ILTranslate(il, "Bryce", TranslationUtils.EncodeToUtf16("Брайс"));
            TranslationUtils.ILTranslate(il, "Bunny", TranslationUtils.EncodeToUtf16("Заинька"));
            TranslationUtils.ILTranslate(il, "Caelia", TranslationUtils.EncodeToUtf16("Келия"));
            TranslationUtils.ILTranslate(il, "Caitlin", TranslationUtils.EncodeToUtf16("Катлин"));
            TranslationUtils.ILTranslate(il, "Calista", TranslationUtils.EncodeToUtf16("Калиста"));
            TranslationUtils.ILTranslate(il, "Calvin", TranslationUtils.EncodeToUtf16("Кельвин"));
            TranslationUtils.ILTranslate(il, "Candy", TranslationUtils.EncodeToUtf16("Карамелька"));
            TranslationUtils.ILTranslate(il, "Captain Bullywort", TranslationUtils.EncodeToUtf16("Капитан Булливорт"));
            TranslationUtils.ILTranslate(il, "Captain Morgan", TranslationUtils.EncodeToUtf16("Капитан Морган"));
            TranslationUtils.ILTranslate(il, "Captain Stoney Dirt", TranslationUtils.EncodeToUtf16("Капитан Грязный Камень"));
            TranslationUtils.ILTranslate(il, "Carlo", TranslationUtils.EncodeToUtf16("Карло"));
            TranslationUtils.ILTranslate(il, "Carly", TranslationUtils.EncodeToUtf16("Карли"));
            TranslationUtils.ILTranslate(il, "Carroll", TranslationUtils.EncodeToUtf16("Кэрролл"));
            TranslationUtils.ILTranslate(il, "Cedric", TranslationUtils.EncodeToUtf16("Седрик"));
            TranslationUtils.ILTranslate(il, "Celestia", TranslationUtils.EncodeToUtf16("Селестия"));
            TranslationUtils.ILTranslate(il, "Chanterelle", TranslationUtils.EncodeToUtf16("Лисичка"));
            TranslationUtils.ILTranslate(il, "Charles", TranslationUtils.EncodeToUtf16("Чарльз"));
            TranslationUtils.ILTranslate(il, "Cherry", TranslationUtils.EncodeToUtf16("Черри"));
            TranslationUtils.ILTranslate(il, "Chester", TranslationUtils.EncodeToUtf16("Честер"));
            TranslationUtils.ILTranslate(il, "Chryseis", TranslationUtils.EncodeToUtf16("Хризис"));
            TranslationUtils.ILTranslate(il, "Ci", TranslationUtils.EncodeToUtf16("Си"));
            TranslationUtils.ILTranslate(il, "Claire", TranslationUtils.EncodeToUtf16("Клэр"));
            TranslationUtils.ILTranslate(il, "Cleveland", TranslationUtils.EncodeToUtf16("Кливленд"));
            TranslationUtils.ILTranslate(il, "Clive", TranslationUtils.EncodeToUtf16("Клайв"));
            TranslationUtils.ILTranslate(il, "Cody", TranslationUtils.EncodeToUtf16("Коди"));
            TranslationUtils.ILTranslate(il, "Cole", TranslationUtils.EncodeToUtf16("Коул"));
            TranslationUtils.ILTranslate(il, "Colin", TranslationUtils.EncodeToUtf16("Колин"));
            TranslationUtils.ILTranslate(il, "Connor", TranslationUtils.EncodeToUtf16("Коннор"));
            TranslationUtils.ILTranslate(il, "Cornelia", TranslationUtils.EncodeToUtf16("Корнелия"));
            TranslationUtils.ILTranslate(il, "Cremini", TranslationUtils.EncodeToUtf16("Шампиньон"));
            TranslationUtils.ILTranslate(il, "Cynthia", TranslationUtils.EncodeToUtf16("Синтия"));
            TranslationUtils.ILTranslate(il, "Cyril", TranslationUtils.EncodeToUtf16("Сайрил"));
            TranslationUtils.ILTranslate(il, "Dalamar", TranslationUtils.EncodeToUtf16("Даламар"));
            TranslationUtils.ILTranslate(il, "Dalek", TranslationUtils.EncodeToUtf16("Далек"));
            TranslationUtils.ILTranslate(il, "Danel", TranslationUtils.EncodeToUtf16("Данел"));
            TranslationUtils.ILTranslate(il, "Daniel", TranslationUtils.EncodeToUtf16("Дэниел"));
            TranslationUtils.ILTranslate(il, "Danny", TranslationUtils.EncodeToUtf16("Дэнни"));
            TranslationUtils.ILTranslate(il, "Dante", TranslationUtils.EncodeToUtf16("Данте"));
            TranslationUtils.ILTranslate(il, "Darius", TranslationUtils.EncodeToUtf16("Дарий"));
            TranslationUtils.ILTranslate(il, "Darnell", TranslationUtils.EncodeToUtf16("Дарнелл"));
            TranslationUtils.ILTranslate(il, "Darren", TranslationUtils.EncodeToUtf16("Даррен"));
            TranslationUtils.ILTranslate(il, "Darryl", TranslationUtils.EncodeToUtf16("Деррил"));
            TranslationUtils.ILTranslate(il, "Darur", TranslationUtils.EncodeToUtf16("Дарур"));
            TranslationUtils.ILTranslate(il, "Darz", TranslationUtils.EncodeToUtf16("Дарз"));
            TranslationUtils.ILTranslate(il, "David", TranslationUtils.EncodeToUtf16("Дэвид"));
            TranslationUtils.ILTranslate(il, "Dawn", TranslationUtils.EncodeToUtf16("Заря"));
            TranslationUtils.ILTranslate(il, "Dazzle", TranslationUtils.EncodeToUtf16("Очаровашка"));
            TranslationUtils.ILTranslate(il, "DeAndre", TranslationUtils.EncodeToUtf16("ДеАндре"));
            TranslationUtils.ILTranslate(il, "Delta", TranslationUtils.EncodeToUtf16("Дельта"));
            TranslationUtils.ILTranslate(il, "Demetrius", TranslationUtils.EncodeToUtf16("Деметрий"));
            TranslationUtils.ILTranslate(il, "DeShawn", TranslationUtils.EncodeToUtf16("ДеШон"));
            TranslationUtils.ILTranslate(il, "Destiny", TranslationUtils.EncodeToUtf16("Дестини"));
            TranslationUtils.ILTranslate(il, "Dias", TranslationUtils.EncodeToUtf16("Диас"));
            TranslationUtils.ILTranslate(il, "Dolbere", TranslationUtils.EncodeToUtf16("Долбер"));
            TranslationUtils.ILTranslate(il, "Dolgen", TranslationUtils.EncodeToUtf16("Долген"));
            TranslationUtils.ILTranslate(il, "Dolgrim", TranslationUtils.EncodeToUtf16("Долгрим"));
            TranslationUtils.ILTranslate(il, "Dominique", TranslationUtils.EncodeToUtf16("Доминик"));
            TranslationUtils.ILTranslate(il, "Duerthen", TranslationUtils.EncodeToUtf16("Дюрфен"));
            TranslationUtils.ILTranslate(il, "Dulais", TranslationUtils.EncodeToUtf16("Дулаш"));
            TranslationUtils.ILTranslate(il, "Durim", TranslationUtils.EncodeToUtf16("Дурим"));
            TranslationUtils.ILTranslate(il, "Durnok", TranslationUtils.EncodeToUtf16("Дурнок"));
            TranslationUtils.ILTranslate(il, "Dwyer", TranslationUtils.EncodeToUtf16("Дуайер"));
            TranslationUtils.ILTranslate(il, "Dylan", TranslationUtils.EncodeToUtf16("Дилан"));
            TranslationUtils.ILTranslate(il, "Edgar", TranslationUtils.EncodeToUtf16("Эдгар"));
            TranslationUtils.ILTranslate(il, "Edmund", TranslationUtils.EncodeToUtf16("Эдмунд"));
            TranslationUtils.ILTranslate(il, "Edmund", TranslationUtils.EncodeToUtf16("Эдмунд"), 2);
            TranslationUtils.ILTranslate(il, "Edward", TranslationUtils.EncodeToUtf16("Эдвард"));
            TranslationUtils.ILTranslate(il, "Edwin", TranslationUtils.EncodeToUtf16("Эдвин"));
            TranslationUtils.ILTranslate(il, "Eladon", TranslationUtils.EncodeToUtf16("Эладон"));
            TranslationUtils.ILTranslate(il, "Ella", TranslationUtils.EncodeToUtf16("Элла"));
            TranslationUtils.ILTranslate(il, "Ellen", TranslationUtils.EncodeToUtf16("Эллен"));
            TranslationUtils.ILTranslate(il, "Elric", TranslationUtils.EncodeToUtf16("Элрик"));
            TranslationUtils.ILTranslate(il, "Elysia", TranslationUtils.EncodeToUtf16("Элизия"));
            TranslationUtils.ILTranslate(il, "Emeline", TranslationUtils.EncodeToUtf16("Эмелин"));
            TranslationUtils.ILTranslate(il, "Emerenta", TranslationUtils.EncodeToUtf16("Эмерента"));
            TranslationUtils.ILTranslate(il, "Emily", TranslationUtils.EncodeToUtf16("Эмили"));
            TranslationUtils.ILTranslate(il, "Emma", TranslationUtils.EncodeToUtf16("Эмма"));
            TranslationUtils.ILTranslate(il, "Enoki", TranslationUtils.EncodeToUtf16("Опёнок"));
            TranslationUtils.ILTranslate(il, "Enzo", TranslationUtils.EncodeToUtf16("Энцо"));
            TranslationUtils.ILTranslate(il, "Esmeralda", TranslationUtils.EncodeToUtf16("Эсмеральда"));
            TranslationUtils.ILTranslate(il, "Esreadel", TranslationUtils.EncodeToUtf16("Эсридель"));
            TranslationUtils.ILTranslate(il, "Eugene", TranslationUtils.EncodeToUtf16("Юджин"));
            TranslationUtils.ILTranslate(il, "Eustace", TranslationUtils.EncodeToUtf16("Юстас"));
            TranslationUtils.ILTranslate(il, "Evvie", TranslationUtils.EncodeToUtf16("Ивви"));
            TranslationUtils.ILTranslate(il, "Fahd", TranslationUtils.EncodeToUtf16("Фад"));
            TranslationUtils.ILTranslate(il, "Fantasia", TranslationUtils.EncodeToUtf16("Фантазия"));
            TranslationUtils.ILTranslate(il, "Fantasy", TranslationUtils.EncodeToUtf16("Фантазёрка"));
            TranslationUtils.ILTranslate(il, "Faye", TranslationUtils.EncodeToUtf16("Фэй"));
            TranslationUtils.ILTranslate(il, "Felicitae", TranslationUtils.EncodeToUtf16("Фелисити"));
            TranslationUtils.ILTranslate(il, "Fender", TranslationUtils.EncodeToUtf16("Фендер"));
            TranslationUtils.ILTranslate(il, "Fidelia", TranslationUtils.EncodeToUtf16("Фиделия"));
            TranslationUtils.ILTranslate(il, "Fikod", TranslationUtils.EncodeToUtf16("Фикод"));
            TranslationUtils.ILTranslate(il, "Fillmore", TranslationUtils.EncodeToUtf16("Филлмор"));
            TranslationUtils.ILTranslate(il, "Finn", TranslationUtils.EncodeToUtf16("Финн"));
            TranslationUtils.ILTranslate(il, "Fitz", TranslationUtils.EncodeToUtf16("Фитц"));
            TranslationUtils.ILTranslate(il, "Fizban", TranslationUtils.EncodeToUtf16("Физбан"));
            TranslationUtils.ILTranslate(il, "Fjell", TranslationUtils.EncodeToUtf16("Фьёль"));
            TranslationUtils.ILTranslate(il, "Flora", TranslationUtils.EncodeToUtf16("Флора"));
            TranslationUtils.ILTranslate(il, "Frank", TranslationUtils.EncodeToUtf16("Фрэнк"));
            TranslationUtils.ILTranslate(il, "Frederick", TranslationUtils.EncodeToUtf16("Фредерик"));
            TranslationUtils.ILTranslate(il, "Gallius", TranslationUtils.EncodeToUtf16("Галлий"));
            TranslationUtils.ILTranslate(il, "Gamma", TranslationUtils.EncodeToUtf16("Гамма"));
            TranslationUtils.ILTranslate(il, "Garrett", TranslationUtils.EncodeToUtf16("Гарретт"));
            TranslationUtils.ILTranslate(il, "Garval", TranslationUtils.EncodeToUtf16("Гарвал"));
            TranslationUtils.ILTranslate(il, "Gboto", TranslationUtils.EncodeToUtf16("Гбото"));
            TranslationUtils.ILTranslate(il, "Gearroid", TranslationUtils.EncodeToUtf16("Геррод"));
            TranslationUtils.ILTranslate(il, "Gilbert", TranslationUtils.EncodeToUtf16("Гилберт"));
            TranslationUtils.ILTranslate(il, "Gimli", TranslationUtils.EncodeToUtf16("Гимли"));
            TranslationUtils.ILTranslate(il, "Gimut", TranslationUtils.EncodeToUtf16("Гимут"));
            TranslationUtils.ILTranslate(il, "Ginger", TranslationUtils.EncodeToUtf16("Джинджер"));
            TranslationUtils.ILTranslate(il, "Glitter", TranslationUtils.EncodeToUtf16("Блёстка"));
            TranslationUtils.ILTranslate(il, "Gloomy Mays", TranslationUtils.EncodeToUtf16("Мрачный Мэйс"));
            TranslationUtils.ILTranslate(il, "Gnudar", TranslationUtils.EncodeToUtf16("Гнудар"));
            TranslationUtils.ILTranslate(il, "Graham", TranslationUtils.EncodeToUtf16("Грэм"));
            TranslationUtils.ILTranslate(il, "Grayson", TranslationUtils.EncodeToUtf16("Грейсон"));
            TranslationUtils.ILTranslate(il, "Greum", TranslationUtils.EncodeToUtf16("Грюм"));
            TranslationUtils.ILTranslate(il, "Grodax", TranslationUtils.EncodeToUtf16("Гродакс"));
            TranslationUtils.ILTranslate(il, "Grover", TranslationUtils.EncodeToUtf16("Гровер"));
            TranslationUtils.ILTranslate(il, "Guido", TranslationUtils.EncodeToUtf16("Гвидо"));
            TranslationUtils.ILTranslate(il, "Gunpowder Garry", TranslationUtils.EncodeToUtf16("Пороховой Гарри"));
            TranslationUtils.ILTranslate(il, "Gus", TranslationUtils.EncodeToUtf16("Гас"));
            TranslationUtils.ILTranslate(il, "Gwentor", TranslationUtils.EncodeToUtf16("Гвентор"));
            TranslationUtils.ILTranslate(il, "Hannah", TranslationUtils.EncodeToUtf16("Ханна"));
            TranslationUtils.ILTranslate(il, "Hannibal", TranslationUtils.EncodeToUtf16("Ганнибал"));
            TranslationUtils.ILTranslate(il, "Hanno", TranslationUtils.EncodeToUtf16("Ганнон"));
            TranslationUtils.ILTranslate(il, "Harley", TranslationUtils.EncodeToUtf16("Харли"));
            TranslationUtils.ILTranslate(il, "Harold", TranslationUtils.EncodeToUtf16("Гарольд"));
            TranslationUtils.ILTranslate(il, "Harrison", TranslationUtils.EncodeToUtf16("Гаррисон"));
            TranslationUtils.ILTranslate(il, "Hazel", TranslationUtils.EncodeToUtf16("Хэйзел"));
            TranslationUtils.ILTranslate(il, "Heather", TranslationUtils.EncodeToUtf16("Хэйзер"));
            TranslationUtils.ILTranslate(il, "Helen", TranslationUtils.EncodeToUtf16("Хелен"));
            TranslationUtils.ILTranslate(il, "Henry", TranslationUtils.EncodeToUtf16("Генри"));
            TranslationUtils.ILTranslate(il, "Herald", TranslationUtils.EncodeToUtf16("Геральд"));
            TranslationUtils.ILTranslate(il, "Herbert", TranslationUtils.EncodeToUtf16("Герберт"));
            TranslationUtils.ILTranslate(il, "Hirael", TranslationUtils.EncodeToUtf16("Хираэль"));
            TranslationUtils.ILTranslate(il, "Hiram", TranslationUtils.EncodeToUtf16("Хирам"));
            TranslationUtils.ILTranslate(il, "Holly", TranslationUtils.EncodeToUtf16("Холли"));
            TranslationUtils.ILTranslate(il, "Hope", TranslationUtils.EncodeToUtf16("Хоуп"));
            TranslationUtils.ILTranslate(il, "Howard", TranslationUtils.EncodeToUtf16("Говард"));
            TranslationUtils.ILTranslate(il, "Humphrey", TranslationUtils.EncodeToUtf16("Хамфри"));
            TranslationUtils.ILTranslate(il, "Iris", TranslationUtils.EncodeToUtf16("Айрис"));
            TranslationUtils.ILTranslate(il, "Isaac", TranslationUtils.EncodeToUtf16("Айзек"));
            TranslationUtils.ILTranslate(il, "Isabella", TranslationUtils.EncodeToUtf16("Изабелла"));
            TranslationUtils.ILTranslate(il, "Isis", TranslationUtils.EncodeToUtf16("Айзис"));
            TranslationUtils.ILTranslate(il, "Isis", TranslationUtils.EncodeToUtf16("Айзис"), 2);
            TranslationUtils.ILTranslate(il, "Ivan", TranslationUtils.EncodeToUtf16("Айвен"));
            TranslationUtils.ILTranslate(il, "Izzy", TranslationUtils.EncodeToUtf16("Иззи"));
            TranslationUtils.ILTranslate(il, "Jack Sellington", TranslationUtils.EncodeToUtf16("Джек Селлингтон"));
            TranslationUtils.ILTranslate(il, "Jack", TranslationUtils.EncodeToUtf16("Джек"));
            TranslationUtils.ILTranslate(il, "Jack", TranslationUtils.EncodeToUtf16("Джек"), 2);
            TranslationUtils.ILTranslate(il, "Jacob", TranslationUtils.EncodeToUtf16("Джейкоб"));
            TranslationUtils.ILTranslate(il, "Jake", TranslationUtils.EncodeToUtf16("Джейк"));
            TranslationUtils.ILTranslate(il, "Jake", TranslationUtils.EncodeToUtf16("Джейк"), 2);
            TranslationUtils.ILTranslate(il, "Jalen", TranslationUtils.EncodeToUtf16("Джален"));
            TranslationUtils.ILTranslate(il, "Jamal", TranslationUtils.EncodeToUtf16("Джамал"));
            TranslationUtils.ILTranslate(il, "James", TranslationUtils.EncodeToUtf16("Джеймс"));
            TranslationUtils.ILTranslate(il, "James T. Beard", TranslationUtils.EncodeToUtf16("Джеймс Т. Борода"));
            TranslationUtils.ILTranslate(il, "Jamundi", TranslationUtils.EncodeToUtf16("Хамунди"));
            TranslationUtils.ILTranslate(il, "Jarut", TranslationUtils.EncodeToUtf16("Джарут"));
            TranslationUtils.ILTranslate(il, "Jeff", TranslationUtils.EncodeToUtf16("Джефф"));
            TranslationUtils.ILTranslate(il, "Jeffrey", TranslationUtils.EncodeToUtf16("Джеффри"));
            TranslationUtils.ILTranslate(il, "Jenna", TranslationUtils.EncodeToUtf16("Дженна"));
            TranslationUtils.ILTranslate(il, "Jenny", TranslationUtils.EncodeToUtf16("Дженни"));
            TranslationUtils.ILTranslate(il, "Jey", TranslationUtils.EncodeToUtf16("Джей"));
            TranslationUtils.ILTranslate(il, "Jimmy", TranslationUtils.EncodeToUtf16("Джимми"));
            TranslationUtils.ILTranslate(il, "Joe", TranslationUtils.EncodeToUtf16("Джо"));
            TranslationUtils.ILTranslate(il, "Johnny", TranslationUtils.EncodeToUtf16("Джонни"));
            TranslationUtils.ILTranslate(il, "Joseph", TranslationUtils.EncodeToUtf16("Джозеф"));
            TranslationUtils.ILTranslate(il, "Judith", TranslationUtils.EncodeToUtf16("Джудит"));
            TranslationUtils.ILTranslate(il, "Kaitlin", TranslationUtils.EncodeToUtf16("Кэтлин"));
            TranslationUtils.ILTranslate(il, "Kaitlyn", TranslationUtils.EncodeToUtf16("Кейтлин"));
            TranslationUtils.ILTranslate(il, "Kanmi", TranslationUtils.EncodeToUtf16("Канми"));
            TranslationUtils.ILTranslate(il, "Kappa", TranslationUtils.EncodeToUtf16("Каппа"));
            TranslationUtils.ILTranslate(il, "Katelyn", TranslationUtils.EncodeToUtf16("Кейтилин"));
            TranslationUtils.ILTranslate(il, "Katherine", TranslationUtils.EncodeToUtf16("Кейтрин"));
            TranslationUtils.ILTranslate(il, "Kathryn", TranslationUtils.EncodeToUtf16("Катрин"));
            TranslationUtils.ILTranslate(il, "Kati", TranslationUtils.EncodeToUtf16("Кати"));
            TranslationUtils.ILTranslate(il, "Katie", TranslationUtils.EncodeToUtf16("Кейти"));
            TranslationUtils.ILTranslate(il, "Kayla", TranslationUtils.EncodeToUtf16("Кайла"));
            TranslationUtils.ILTranslate(il, "Kayla", TranslationUtils.EncodeToUtf16("Кайла"), 2);
            TranslationUtils.ILTranslate(il, "Kevin", TranslationUtils.EncodeToUtf16("Кевин"));
            TranslationUtils.ILTranslate(il, "Knogs", TranslationUtils.EncodeToUtf16("Ногс"));
            TranslationUtils.ILTranslate(il, "Knub", TranslationUtils.EncodeToUtf16("Наб"));
            TranslationUtils.ILTranslate(il, "Kogi-ghi", TranslationUtils.EncodeToUtf16("Коги-гхи"));
            TranslationUtils.ILTranslate(il, "Konah", TranslationUtils.EncodeToUtf16("Кона"));
            TranslationUtils.ILTranslate(il, "Korrie", TranslationUtils.EncodeToUtf16("Корри"));
            TranslationUtils.ILTranslate(il, "Kyle", TranslationUtils.EncodeToUtf16("Кайл"));
            TranslationUtils.ILTranslate(il, "Kylie", TranslationUtils.EncodeToUtf16("Кайли"));
            TranslationUtils.ILTranslate(il, "Lambda", TranslationUtils.EncodeToUtf16("Лямбда"));
            TranslationUtils.ILTranslate(il, "Lauren", TranslationUtils.EncodeToUtf16("Лорен"));
            TranslationUtils.ILTranslate(il, "Leila", TranslationUtils.EncodeToUtf16("Лейла"));
            TranslationUtils.ILTranslate(il, "Leomund", TranslationUtils.EncodeToUtf16("Леомунд"));
            TranslationUtils.ILTranslate(il, "Leonardo", TranslationUtils.EncodeToUtf16("Леонардо"));
            TranslationUtils.ILTranslate(il, "Levi", TranslationUtils.EncodeToUtf16("Леви"));
            TranslationUtils.ILTranslate(il, "Lexus", TranslationUtils.EncodeToUtf16("Лексус"));
            TranslationUtils.ILTranslate(il, "Lilly", TranslationUtils.EncodeToUtf16("Лили"));
            TranslationUtils.ILTranslate(il, "Lincoln", TranslationUtils.EncodeToUtf16("Линкольн"));
            TranslationUtils.ILTranslate(il, "Lisa", TranslationUtils.EncodeToUtf16("Лиза"));
            TranslationUtils.ILTranslate(il, "Llewellyn", TranslationUtils.EncodeToUtf16("Ллеуэллин"));
            TranslationUtils.ILTranslate(il, "Lloyd", TranslationUtils.EncodeToUtf16("Ллойд"));
            TranslationUtils.ILTranslate(il, "Lloyd", TranslationUtils.EncodeToUtf16("Ллойд"), 2);
            TranslationUtils.ILTranslate(il, "Logan", TranslationUtils.EncodeToUtf16("Логан"));
            TranslationUtils.ILTranslate(il, "Lola", TranslationUtils.EncodeToUtf16("Лола"));
            TranslationUtils.ILTranslate(il, "Lorenzo", TranslationUtils.EncodeToUtf16("Лоренцо"));
            TranslationUtils.ILTranslate(il, "Lorraine", TranslationUtils.EncodeToUtf16("Лоррейн"));
            TranslationUtils.ILTranslate(il, "Louis", TranslationUtils.EncodeToUtf16("Луис"));
            TranslationUtils.ILTranslate(il, "Luca", TranslationUtils.EncodeToUtf16("Лука"));
            TranslationUtils.ILTranslate(il, "Luciano", TranslationUtils.EncodeToUtf16("Лучиано"));
            TranslationUtils.ILTranslate(il, "Ludo", TranslationUtils.EncodeToUtf16("Людо"));
            TranslationUtils.ILTranslate(il, "Luigi", TranslationUtils.EncodeToUtf16("Луиджи"));
            TranslationUtils.ILTranslate(il, "Luke", TranslationUtils.EncodeToUtf16("Люк"));
            TranslationUtils.ILTranslate(il, "Lunette", TranslationUtils.EncodeToUtf16("Люнетт"));
            TranslationUtils.ILTranslate(il, "Lydia", TranslationUtils.EncodeToUtf16("Лидия"));
            TranslationUtils.ILTranslate(il, "Lyndon", TranslationUtils.EncodeToUtf16("Линдон"));
            TranslationUtils.ILTranslate(il, "Madeline", TranslationUtils.EncodeToUtf16("Мэделин"));
            TranslationUtils.ILTranslate(il, "Maelor", TranslationUtils.EncodeToUtf16("Маэлор"));
            TranslationUtils.ILTranslate(il, "Magius", TranslationUtils.EncodeToUtf16("Магиус"));
            TranslationUtils.ILTranslate(il, "Maitake", TranslationUtils.EncodeToUtf16("Грифола"));
            TranslationUtils.ILTranslate(il, "Malik", TranslationUtils.EncodeToUtf16("Малик"));
            TranslationUtils.ILTranslate(il, "Mandible Calavera", TranslationUtils.EncodeToUtf16("Челюстной Калавера"));
            TranslationUtils.ILTranslate(il, "Marco", TranslationUtils.EncodeToUtf16("Марко"));
            TranslationUtils.ILTranslate(il, "Mario", TranslationUtils.EncodeToUtf16("Марио"));
            TranslationUtils.ILTranslate(il, "Marquis", TranslationUtils.EncodeToUtf16("Маркис"));
            TranslationUtils.ILTranslate(il, "Marshanna", TranslationUtils.EncodeToUtf16("Маршанна"));
            TranslationUtils.ILTranslate(il, "Martino", TranslationUtils.EncodeToUtf16("Мартино"));
            TranslationUtils.ILTranslate(il, "Marty", TranslationUtils.EncodeToUtf16("Марти"));
            TranslationUtils.ILTranslate(il, "Matty", TranslationUtils.EncodeToUtf16("Мэтти"));
            TranslationUtils.ILTranslate(il, "Maurice", TranslationUtils.EncodeToUtf16("Морис"));
            TranslationUtils.ILTranslate(il, "Mauro", TranslationUtils.EncodeToUtf16("Мауро"));
            TranslationUtils.ILTranslate(il, "Maxwell", TranslationUtils.EncodeToUtf16("Максвелл"));
            TranslationUtils.ILTranslate(il, "McKinly", TranslationUtils.EncodeToUtf16("Мак-Кинли"));
            TranslationUtils.ILTranslate(il, "Meliyah", TranslationUtils.EncodeToUtf16("Мелия"));
            TranslationUtils.ILTranslate(il, "Mercer", TranslationUtils.EncodeToUtf16("Мерсер"));
            TranslationUtils.ILTranslate(il, "Meredith", TranslationUtils.EncodeToUtf16("Мередит"));
            TranslationUtils.ILTranslate(il, "Merlyn", TranslationUtils.EncodeToUtf16("Мерлин"));
            TranslationUtils.ILTranslate(il, "Mervyn", TranslationUtils.EncodeToUtf16("Мервин"));
            TranslationUtils.ILTranslate(il, "Mika", TranslationUtils.EncodeToUtf16("Мика"));
            TranslationUtils.ILTranslate(il, "Miles", TranslationUtils.EncodeToUtf16("Майлз"));
            TranslationUtils.ILTranslate(il, "Millard", TranslationUtils.EncodeToUtf16("Миллард"));
            TranslationUtils.ILTranslate(il, "Milton", TranslationUtils.EncodeToUtf16("Милтон"));
            TranslationUtils.ILTranslate(il, "Minerva", TranslationUtils.EncodeToUtf16("Минерва"));
            TranslationUtils.ILTranslate(il, "Mobart", TranslationUtils.EncodeToUtf16("Мобарт"));
            TranslationUtils.ILTranslate(il, "Molly", TranslationUtils.EncodeToUtf16("Молли"));
            TranslationUtils.ILTranslate(il, "Morel", TranslationUtils.EncodeToUtf16("Сморчок"));
            TranslationUtils.ILTranslate(il, "Morthal", TranslationUtils.EncodeToUtf16("Морфал"));
            TranslationUtils.ILTranslate(il, "Mortimer", TranslationUtils.EncodeToUtf16("Мортимер"));
            TranslationUtils.ILTranslate(il, "Mrunok", TranslationUtils.EncodeToUtf16("Мрунок"));
            TranslationUtils.ILTranslate(il, "Mu", TranslationUtils.EncodeToUtf16("Мю"));
            TranslationUtils.ILTranslate(il, "Muscaria", TranslationUtils.EncodeToUtf16("Мухомор"));
            TranslationUtils.ILTranslate(il, "Nancy", TranslationUtils.EncodeToUtf16("Нэнси"));
            TranslationUtils.ILTranslate(il, "Nata", TranslationUtils.EncodeToUtf16("Ната"));
            TranslationUtils.ILTranslate(il, "Nathan", TranslationUtils.EncodeToUtf16("Нейтан"));
            TranslationUtils.ILTranslate(il, "Negurk", TranslationUtils.EncodeToUtf16("Негурк"));
            TranslationUtils.ILTranslate(il, "Nigel", TranslationUtils.EncodeToUtf16("Найджел"));
            TranslationUtils.ILTranslate(il, "Niner-7", TranslationUtils.EncodeToUtf16("Девятый-7"));
            TranslationUtils.ILTranslate(il, "Ningauble", TranslationUtils.EncodeToUtf16("Нингобль"));
            TranslationUtils.ILTranslate(il, "Nissa", TranslationUtils.EncodeToUtf16("Нисса"));
            TranslationUtils.ILTranslate(il, "No-Eyed Wiley", TranslationUtils.EncodeToUtf16("Безглазый Уайли"));
            TranslationUtils.ILTranslate(il, "Norkas", TranslationUtils.EncodeToUtf16("Норкас"));
            TranslationUtils.ILTranslate(il, "Norsun", TranslationUtils.EncodeToUtf16("Норсун"));
            TranslationUtils.ILTranslate(il, "Nort", TranslationUtils.EncodeToUtf16("Норт"));
            TranslationUtils.ILTranslate(il, "Nu", TranslationUtils.EncodeToUtf16("Ню"));
            TranslationUtils.ILTranslate(il, "Nuxatk", TranslationUtils.EncodeToUtf16("Нузатк"));
            TranslationUtils.ILTranslate(il, "Omega", TranslationUtils.EncodeToUtf16("Омега"));
            TranslationUtils.ILTranslate(il, "Omicron", TranslationUtils.EncodeToUtf16("Омикрон"));
            TranslationUtils.ILTranslate(il, "Opuni", TranslationUtils.EncodeToUtf16("Опуни"));
            TranslationUtils.ILTranslate(il, "Oten", TranslationUtils.EncodeToUtf16("Оутен"));
            TranslationUtils.ILTranslate(il, "Ovbere", TranslationUtils.EncodeToUtf16("Овбер"));
            TranslationUtils.ILTranslate(il, "Paris", TranslationUtils.EncodeToUtf16("Пэрис"));
            TranslationUtils.ILTranslate(il, "Pearl", TranslationUtils.EncodeToUtf16("Пёрл"));
            TranslationUtils.ILTranslate(il, "Petra", TranslationUtils.EncodeToUtf16("Петра"));
            TranslationUtils.ILTranslate(il, "Phi", TranslationUtils.EncodeToUtf16("Пи"));
            TranslationUtils.ILTranslate(il, "Phi", TranslationUtils.EncodeToUtf16("Пи"), 2);
            TranslationUtils.ILTranslate(il, "Phillip", TranslationUtils.EncodeToUtf16("Филлип"));
            TranslationUtils.ILTranslate(il, "Philosir", TranslationUtils.EncodeToUtf16("Филозир"));
            TranslationUtils.ILTranslate(il, "Phoebe", TranslationUtils.EncodeToUtf16("Фиби"));
            TranslationUtils.ILTranslate(il, "Pip", TranslationUtils.EncodeToUtf16("Пип"));
            TranslationUtils.ILTranslate(il, "Porcini", TranslationUtils.EncodeToUtf16("Боровик"));
            TranslationUtils.ILTranslate(il, "Ragz", TranslationUtils.EncodeToUtf16("Рагз"));
            TranslationUtils.ILTranslate(il, "Ralph", TranslationUtils.EncodeToUtf16("Ральф"));
            TranslationUtils.ILTranslate(il, "Raphael", TranslationUtils.EncodeToUtf16("Рафаэль"));
            TranslationUtils.ILTranslate(il, "Rattles Magoo", TranslationUtils.EncodeToUtf16("Гремящий Магу"));
            TranslationUtils.ILTranslate(il, "Rawleigh", TranslationUtils.EncodeToUtf16("Роули"));
            TranslationUtils.ILTranslate(il, "Red Beard", TranslationUtils.EncodeToUtf16("Рыжебородый"));
            TranslationUtils.ILTranslate(il, "Reginald", TranslationUtils.EncodeToUtf16("Реджинальд"));
            TranslationUtils.ILTranslate(il, "Reishi", TranslationUtils.EncodeToUtf16("Трутовик"));
            TranslationUtils.ILTranslate(il, "Rho", TranslationUtils.EncodeToUtf16("Ро"));
            TranslationUtils.ILTranslate(il, "Riley", TranslationUtils.EncodeToUtf16("Райли"));
            TranslationUtils.ILTranslate(il, "Rodney", TranslationUtils.EncodeToUtf16("Родни"));
            TranslationUtils.ILTranslate(il, "Rodrick", TranslationUtils.EncodeToUtf16("Родрик"));
            TranslationUtils.ILTranslate(il, "Roland", TranslationUtils.EncodeToUtf16("Роланд"));
            TranslationUtils.ILTranslate(il, "Romeo", TranslationUtils.EncodeToUtf16("Ромео"));
            TranslationUtils.ILTranslate(il, "Ronald", TranslationUtils.EncodeToUtf16("Рональд"));
            TranslationUtils.ILTranslate(il, "Rosalva", TranslationUtils.EncodeToUtf16("Розалва"));
            TranslationUtils.ILTranslate(il, "Rox", TranslationUtils.EncodeToUtf16("Рокс"));
            TranslationUtils.ILTranslate(il, "Roxanne", TranslationUtils.EncodeToUtf16("Роксана"));
            TranslationUtils.ILTranslate(il, "Ruby", TranslationUtils.EncodeToUtf16("Руби"));
            TranslationUtils.ILTranslate(il, "Rupert", TranslationUtils.EncodeToUtf16("Руперт"));
            TranslationUtils.ILTranslate(il, "Rutherford", TranslationUtils.EncodeToUtf16("Ратерфорд"));
            TranslationUtils.ILTranslate(il, "Ryan", TranslationUtils.EncodeToUtf16("Райан"));
            TranslationUtils.ILTranslate(il, "Sally", TranslationUtils.EncodeToUtf16("Салли"));
            TranslationUtils.ILTranslate(il, "Sammy", TranslationUtils.EncodeToUtf16("Сэмми"));
            TranslationUtils.ILTranslate(il, "Sargon", TranslationUtils.EncodeToUtf16("Саргон"));
            TranslationUtils.ILTranslate(il, "Sarx", TranslationUtils.EncodeToUtf16("Саркс"));
            TranslationUtils.ILTranslate(il, "Savannah", TranslationUtils.EncodeToUtf16("Саванна"));
            TranslationUtils.ILTranslate(il, "Scarlett", TranslationUtils.EncodeToUtf16("Скарлетт"));
            TranslationUtils.ILTranslate(il, "Scott", TranslationUtils.EncodeToUtf16("Скотт"));
            TranslationUtils.ILTranslate(il, "Sebastian", TranslationUtils.EncodeToUtf16("Себастьян"));
            TranslationUtils.ILTranslate(il, "Selah", TranslationUtils.EncodeToUtf16("Сэла"));
            TranslationUtils.ILTranslate(il, "Selene", TranslationUtils.EncodeToUtf16("Селена"));
            TranslationUtils.ILTranslate(il, "Selina", TranslationUtils.EncodeToUtf16("Селина"));
            TranslationUtils.ILTranslate(il, "Seonag", TranslationUtils.EncodeToUtf16("Шонаг"));
            TranslationUtils.ILTranslate(il, "Seth", TranslationUtils.EncodeToUtf16("Сет"));
            TranslationUtils.ILTranslate(il, "Seymour", TranslationUtils.EncodeToUtf16("Сеймур"));
            TranslationUtils.ILTranslate(il, "Shayna", TranslationUtils.EncodeToUtf16("Шайна"));
            TranslationUtils.ILTranslate(il, "Shea", TranslationUtils.EncodeToUtf16("Шия"));
            TranslationUtils.ILTranslate(il, "Sheena", TranslationUtils.EncodeToUtf16("Шина"));
            TranslationUtils.ILTranslate(il, "Shiitake", TranslationUtils.EncodeToUtf16("Лентинула"));
            TranslationUtils.ILTranslate(il, "Shimeji", TranslationUtils.EncodeToUtf16("Рядовка"));
            TranslationUtils.ILTranslate(il, "Shipton", TranslationUtils.EncodeToUtf16("Шиптон"));
            TranslationUtils.ILTranslate(il, "Shirlena", TranslationUtils.EncodeToUtf16("Ширлена"));
            TranslationUtils.ILTranslate(il, "Sigma", TranslationUtils.EncodeToUtf16("Сигма"));
            TranslationUtils.ILTranslate(il, "Sikarbaal", TranslationUtils.EncodeToUtf16("Сикарбаал"));
            TranslationUtils.ILTranslate(il, "Simon", TranslationUtils.EncodeToUtf16("Саймон"));
            TranslationUtils.ILTranslate(il, "Skellington", TranslationUtils.EncodeToUtf16("Скеллингтон"));
            TranslationUtils.ILTranslate(il, "Smador", TranslationUtils.EncodeToUtf16("Смадор"));
            TranslationUtils.ILTranslate(il, "Sophia", TranslationUtils.EncodeToUtf16("София"));
            TranslationUtils.ILTranslate(il, "Sparkle", TranslationUtils.EncodeToUtf16("Искорка"));
            TranslationUtils.ILTranslate(il, "Spencer", TranslationUtils.EncodeToUtf16("Спенсер"));
            TranslationUtils.ILTranslate(il, "Star", TranslationUtils.EncodeToUtf16("Звёздочка"));
            TranslationUtils.ILTranslate(il, "Stazen", TranslationUtils.EncodeToUtf16("Стацен"));
            TranslationUtils.ILTranslate(il, "Stefano", TranslationUtils.EncodeToUtf16("Стефано"));
            TranslationUtils.ILTranslate(il, "Stella", TranslationUtils.EncodeToUtf16("Стелла"));
            TranslationUtils.ILTranslate(il, "Steve", TranslationUtils.EncodeToUtf16("Стив"));
            TranslationUtils.ILTranslate(il, "Stezom", TranslationUtils.EncodeToUtf16("Стезом"));
            TranslationUtils.ILTranslate(il, "Sugar", TranslationUtils.EncodeToUtf16("Милашка"));
            TranslationUtils.ILTranslate(il, "Susana", TranslationUtils.EncodeToUtf16("Сюзанна"));
            TranslationUtils.ILTranslate(il, "Syn-X", TranslationUtils.EncodeToUtf16("Син-Х"));
            TranslationUtils.ILTranslate(il, "T-3E0", TranslationUtils.EncodeToUtf16("Т-3Е0"));
            TranslationUtils.ILTranslate(il, "Tabnit", TranslationUtils.EncodeToUtf16("Табнит"));
            TranslationUtils.ILTranslate(il, "Tagar", TranslationUtils.EncodeToUtf16("Тагар"));
            TranslationUtils.ILTranslate(il, "Tairona", TranslationUtils.EncodeToUtf16("Тайрона"));
            TranslationUtils.ILTranslate(il, "Tallulah", TranslationUtils.EncodeToUtf16("Таллула"));
            TranslationUtils.ILTranslate(il, "Tania", TranslationUtils.EncodeToUtf16("Таня"));
            TranslationUtils.ILTranslate(il, "Tanner", TranslationUtils.EncodeToUtf16("Таннер"));
            TranslationUtils.ILTranslate(il, "Tatiana", TranslationUtils.EncodeToUtf16("Татьяна"));
            TranslationUtils.ILTranslate(il, "Terra", TranslationUtils.EncodeToUtf16("Терра"));
            TranslationUtils.ILTranslate(il, "Terrance", TranslationUtils.EncodeToUtf16("Терренс"));
            TranslationUtils.ILTranslate(il, "Terrell", TranslationUtils.EncodeToUtf16("Террелл"));
            TranslationUtils.ILTranslate(il, "Tgerd", TranslationUtils.EncodeToUtf16("Тгерд"));
            TranslationUtils.ILTranslate(il, "Theodore", TranslationUtils.EncodeToUtf16("Теодор"));
            TranslationUtils.ILTranslate(il, "Theta", TranslationUtils.EncodeToUtf16("Тета"));
            TranslationUtils.ILTranslate(il, "Timmy", TranslationUtils.EncodeToUtf16("Тимми"));
            TranslationUtils.ILTranslate(il, "Tkanus", TranslationUtils.EncodeToUtf16("Тканус"));
            TranslationUtils.ILTranslate(il, "Tom", TranslationUtils.EncodeToUtf16("Том"));
            TranslationUtils.ILTranslate(il, "Tony", TranslationUtils.EncodeToUtf16("Тони"));
            TranslationUtils.ILTranslate(il, "Tordak", TranslationUtils.EncodeToUtf16("Тордак"));
            TranslationUtils.ILTranslate(il, "Trent", TranslationUtils.EncodeToUtf16("Трент"));
            TranslationUtils.ILTranslate(il, "Trevon", TranslationUtils.EncodeToUtf16("Тревон"));
            TranslationUtils.ILTranslate(il, "Trisha", TranslationUtils.EncodeToUtf16("Триша"));
            TranslationUtils.ILTranslate(il, "Trixy", TranslationUtils.EncodeToUtf16("Проказница"));
            TranslationUtils.ILTranslate(il, "Trogem", TranslationUtils.EncodeToUtf16("Трогем"));
            TranslationUtils.ILTranslate(il, "Tweed", TranslationUtils.EncodeToUtf16("Твид"));
            TranslationUtils.ILTranslate(il, "Tyler", TranslationUtils.EncodeToUtf16("Тайлер"));
            TranslationUtils.ILTranslate(il, "Tyrone", TranslationUtils.EncodeToUtf16("Тайрон"));
            TranslationUtils.ILTranslate(il, "U'wa", TranslationUtils.EncodeToUtf16("У'ва"));
            TranslationUtils.ILTranslate(il, "Upsilon", TranslationUtils.EncodeToUtf16("Ипсилон"));
            TranslationUtils.ILTranslate(il, "Urist", TranslationUtils.EncodeToUtf16("Урист"));
            TranslationUtils.ILTranslate(il, "Verity", TranslationUtils.EncodeToUtf16("Верити"));
            TranslationUtils.ILTranslate(il, "Vivian", TranslationUtils.EncodeToUtf16("Вивиан"));
            TranslationUtils.ILTranslate(il, "Walter", TranslationUtils.EncodeToUtf16("Уолтер"));
            TranslationUtils.ILTranslate(il, "Warren", TranslationUtils.EncodeToUtf16("Уоррен"));
            TranslationUtils.ILTranslate(il, "Wet Beard", TranslationUtils.EncodeToUtf16("Мокрая Борода"));
            TranslationUtils.ILTranslate(il, "Whitney", TranslationUtils.EncodeToUtf16("Уитни"));
            TranslationUtils.ILTranslate(il, "Wilbur", TranslationUtils.EncodeToUtf16("Уилбур"));
            TranslationUtils.ILTranslate(il, "Willie", TranslationUtils.EncodeToUtf16("Уилли"));
            TranslationUtils.ILTranslate(il, "Willy", TranslationUtils.EncodeToUtf16("Уилли"));
            TranslationUtils.ILTranslate(il, "Woodrow", TranslationUtils.EncodeToUtf16("Вудро"));
            TranslationUtils.ILTranslate(il, "Wyatt", TranslationUtils.EncodeToUtf16("Уайатт"));
            TranslationUtils.ILTranslate(il, "Xanadu", TranslationUtils.EncodeToUtf16("Занаду"));
            TranslationUtils.ILTranslate(il, "Xanos", TranslationUtils.EncodeToUtf16("Ксанос"));
            TranslationUtils.ILTranslate(il, "Xavier", TranslationUtils.EncodeToUtf16("Ксавьер"));
            TranslationUtils.ILTranslate(il, "Xirigua", TranslationUtils.EncodeToUtf16("Зиригуа"));
            TranslationUtils.ILTranslate(il, "Xon", TranslationUtils.EncodeToUtf16("Ксон"));
            TranslationUtils.ILTranslate(il, "Xylia", TranslationUtils.EncodeToUtf16("Силия"));
            TranslationUtils.ILTranslate(il, "Yehomilk", TranslationUtils.EncodeToUtf16("Йехомилк"));
            TranslationUtils.ILTranslate(il, "Yutpan", TranslationUtils.EncodeToUtf16("Ютпан"));
            TranslationUtils.ILTranslate(il, "Zach", TranslationUtils.EncodeToUtf16("Зак"));
            TranslationUtils.ILTranslate(il, "Zelda", TranslationUtils.EncodeToUtf16("Зельда"));
            TranslationUtils.ILTranslate(il, "Zeta", TranslationUtils.EncodeToUtf16("Дзета"));
            TranslationUtils.ILTranslate(il, "Zop'a", TranslationUtils.EncodeToUtf16("Зопа"));
            TranslationUtils.ILTranslate(il, "Zylphia", TranslationUtils.EncodeToUtf16("Зильфия"));
        }
    }
}