using Microsoft.Xna.Framework;
using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ShadowsOfAbaddon.Tiles
{
	internal class SacredToolsTiles
	{
		public static void Setup()
		{
			SacredToolsTiles.Tiles();
		}
		
		private static void Tiles()
		{
			Mod sacredTools = ModLoader.GetMod("SacredTools");
			
			ModTile tile = TileLoader.GetTile(sacredTools.TileType("AbaddonStatue"));
			ModTranslation abaddonStatue = tile.CreateMapEntryName();
			abaddonStatue.AddTranslation(GameCulture.Russian, "Статуя Абаддона");
			tile.AddMapEntry(new Color(123, 123, 123), abaddonStatue);
			ModTile tile2 = TileLoader.GetTile(sacredTools.TileType("AntheeFountain"));
			ModTranslation antheeFountain = tile2.CreateMapEntryName();
			antheeFountain.AddTranslation(GameCulture.Russian, "Фонтан воспоминаний");
			tile2.AddMapEntry(new Color(123, 123, 123), antheeFountain);
			ModTile tile3 = TileLoader.GetTile(sacredTools.TileType("AraneasTrophy"));
			ModTranslation araneasTrophy = tile3.CreateMapEntryName();
			araneasTrophy.AddTranslation(GameCulture.Russian, "Трофей");
			tile3.AddMapEntry(new Color(120, 85, 60), araneasTrophy);
			ModTile tile4 = TileLoader.GetTile(sacredTools.TileType("Banners"));
			ModTranslation banners = tile4.CreateMapEntryName();
			banners.AddTranslation(GameCulture.Russian, "Знамя");
			tile4.AddMapEntry(new Color(13, 88, 130), banners);
			ModTile tile5 = TileLoader.GetTile(sacredTools.TileType("BendyCutout"));
			ModTranslation bendyCutout = tile5.CreateMapEntryName();
			bendyCutout.AddTranslation(GameCulture.Russian, "Бенди-картонка");
			tile5.AddMapEntry(new Color(123, 123, 123), bendyCutout);
			ModTile tile6 = TileLoader.GetTile(sacredTools.TileType("BismuthOre"));
			ModTranslation bismuthOre = tile6.CreateMapEntryName();
			bismuthOre.AddTranslation(GameCulture.Russian, "Висмут");
			tile6.AddMapEntry(new Color(186, 168, 132), bismuthOre);
			ModTile tile7 = TileLoader.GetTile(sacredTools.TileType("BoneThrone"));
			ModTranslation boneThrone = tile7.CreateMapEntryName();
			boneThrone.AddTranslation(GameCulture.Russian, "Костяной трон");
			tile7.AddMapEntry(new Color(123, 123, 123), boneThrone);
			ModTile tile8 = TileLoader.GetTile(sacredTools.TileType("CatLamp"));
			ModTranslation catLamp = tile8.CreateMapEntryName();
			catLamp.AddTranslation(GameCulture.Russian, "Кошачья лампа");
			tile8.AddMapEntry(new Color(202, 236, 231), catLamp);
			ModTile tile9 = TileLoader.GetTile(sacredTools.TileType("Cernium"));
			ModTranslation cernium = tile9.CreateMapEntryName();
			cernium.AddTranslation(GameCulture.Russian, "Церниум");
			tile9.AddMapEntry(new Color(180, 234, 237), cernium);
			ModTile tile10 = TileLoader.GetTile(sacredTools.TileType("Decoration_Bulb"));
			ModTranslation decorationBulb = tile10.CreateMapEntryName();
			decorationBulb.AddTranslation(GameCulture.Russian, "Декоративный бутон");
			tile10.AddMapEntry(new Color(203, 84, 152), decorationBulb);
			ModTile tile11 = TileLoader.GetTile(sacredTools.TileType("FishronPlush"));
			ModTranslation fishronPlush = tile11.CreateMapEntryName();
			fishronPlush.AddTranslation(GameCulture.Russian, "Плюшевый Рыброн");
			tile11.AddMapEntry(new Color(32, 224, 144), fishronPlush);
			ModTile tile12 = TileLoader.GetTile(sacredTools.TileType("FlameAnvil"));
			ModTranslation flameAnvil = tile12.CreateMapEntryName();
			flameAnvil.AddTranslation(GameCulture.Russian, "Пламенная наковальня");
			tile12.AddMapEntry(new Color(254, 121, 2), flameAnvil);
			ModTile tile13 = TileLoader.GetTile(sacredTools.TileType("FlameForge"));
			ModTranslation flameForge = tile13.CreateMapEntryName();
			flameForge.AddTranslation(GameCulture.Russian, "Пламенная кузня");
			tile13.AddMapEntry(new Color(14, 13, 29), flameForge);
			ModTile tile14 = TileLoader.GetTile(sacredTools.TileType("FlameSapling"));
			ModTranslation flameSapling = tile14.CreateMapEntryName();
			flameSapling.AddTranslation(GameCulture.Russian, "Саженец");
			tile14.AddMapEntry(new Color(195, 86, 0), flameSapling);
			ModTile tile15 = TileLoader.GetTile(sacredTools.TileType("FlareChest"));
			ModTranslation flareChest = tile15.CreateMapEntryName();
			flareChest.AddTranslation(GameCulture.Russian, "Сундук яркого пламени");
			tile15.AddMapEntry(new Color(200, 200, 200), flareChest);
			ModTile tile16 = TileLoader.GetTile(sacredTools.TileType("FlareDoorClosed"));
			ModTranslation flareDoorClosed = tile16.CreateMapEntryName();
			flareDoorClosed.AddTranslation(GameCulture.Russian, "Двери яркого пламени");
			tile16.AddMapEntry(new Color(200, 200, 200), flareDoorClosed);
			ModTile tile17 = TileLoader.GetTile(sacredTools.TileType("FlareDoorOpen"));
			ModTranslation flareDoorOpen = tile17.CreateMapEntryName();
			flareDoorOpen.AddTranslation(GameCulture.Russian, "Двери яркого пламени");
			tile17.AddMapEntry(new Color(200, 200, 200), flareDoorOpen);
			ModTile tile18 = TileLoader.GetTile(sacredTools.TileType("FlareTorch"));
			ModTranslation flareTorch = tile18.CreateMapEntryName();
			flareTorch.AddTranslation(GameCulture.Russian, "Факел");
			tile18.AddMapEntry(new Color(255, 191, 0), flareTorch);
			ModTile tile19 = TileLoader.GetTile(sacredTools.TileType("Flarium"));
			ModTranslation flarium = tile19.CreateMapEntryName();
			flarium.AddTranslation(GameCulture.Russian, "Яркое пламя");
			tile19.AddMapEntry(new Color(255, 191, 0), flarium);
			ModTile tile20 = TileLoader.GetTile(sacredTools.TileType("FlariumBanners"));
			ModTranslation flariumBanners = tile20.CreateMapEntryName();
			flariumBanners.AddTranslation(GameCulture.Russian, "Знамя");
			tile20.AddMapEntry(new Color(13, 88, 130), flariumBanners);
			ModTile tile21 = TileLoader.GetTile(sacredTools.TileType("FlariumBed"));
			ModTranslation flariumBed = tile21.CreateMapEntryName();
			flariumBed.AddTranslation(GameCulture.Russian, "Кровать яркого пламени");
			tile21.AddMapEntry(new Color(24, 19, 19), flariumBed);
			ModTile tile22 = TileLoader.GetTile(sacredTools.TileType("FlariumBookshelf"));
			ModTranslation flariumBookshelf = tile22.CreateMapEntryName();
			flariumBookshelf.AddTranslation(GameCulture.Russian, "Книжный шкаф яркого пламени");
			tile22.AddMapEntry(new Color(29, 27, 57), flariumBookshelf);
			ModTile tile23 = TileLoader.GetTile(sacredTools.TileType("FlariumCandelabra"));
			ModTranslation flariumCandelabra = tile23.CreateMapEntryName();
			flariumCandelabra.AddTranslation(GameCulture.Russian, "Канделябр яркого пламени");
			tile23.AddMapEntry(new Color(14, 13, 29), flariumCandelabra);
			ModTile tile24 = TileLoader.GetTile(sacredTools.TileType("FlariumCandle"));
			ModTranslation flariumCandle = tile24.CreateMapEntryName();
			flariumCandle.AddTranslation(GameCulture.Russian, "Свеча яркого пламени");
			tile24.AddMapEntry(new Color(255, 191, 0), flariumCandle);
			ModTile tile25 = TileLoader.GetTile(sacredTools.TileType("FlariumChair"));
			ModTranslation flariumChair = tile25.CreateMapEntryName();
			flariumChair.AddTranslation(GameCulture.Russian, "Стул яркого пламени");
			tile25.AddMapEntry(new Color(255, 191, 0), flariumChair);
			ModTile tile26 = TileLoader.GetTile(sacredTools.TileType("FlariumChandelier"));
			ModTranslation flariumChandelier = tile26.CreateMapEntryName();
			flariumChandelier.AddTranslation(GameCulture.Russian, "Люстра яркого пламени");
			tile26.AddMapEntry(new Color(255, 191, 0), flariumChandelier);
			ModTile tile27 = TileLoader.GetTile(sacredTools.TileType("FlariumCrate"));
			ModTranslation flariumCrate = tile27.CreateMapEntryName();
			flariumCrate.AddTranslation(GameCulture.Russian, "Ящик яркого пламени");
			tile27.AddMapEntry(new Color(14, 13, 29), flariumCrate);
			ModTile tile28 = TileLoader.GetTile(sacredTools.TileType("FlariumDresser"));
			ModTranslation flariumDresser = tile28.CreateMapEntryName();
			flariumDresser.AddTranslation(GameCulture.Russian, "Комод яркого пламени");
			tile28.AddMapEntry(new Color(14, 13, 29), flariumDresser);
			ModTile tile29 = TileLoader.GetTile(sacredTools.TileType("FlariumLamp"));
			ModTranslation flariumLamp = tile29.CreateMapEntryName();
			flariumLamp.AddTranslation(GameCulture.Russian, "Лампа яркого пламени");
			tile29.AddMapEntry(new Color(255, 191, 0), flariumLamp);
			ModTile tile30 = TileLoader.GetTile(sacredTools.TileType("FlariumTable"));
			ModTranslation flariumTable = tile30.CreateMapEntryName();
			flariumTable.AddTranslation(GameCulture.Russian, "Стол яркого пламени");
			tile30.AddMapEntry(new Color(29, 27, 57), flariumTable);
			ModTile tile31 = TileLoader.GetTile(sacredTools.TileType("FlariumWorkbench"));
			ModTranslation flariumWorkbench = tile31.CreateMapEntryName();
			flariumWorkbench.AddTranslation(GameCulture.Russian, "Верстак яркого пламени");
			tile31.AddMapEntry(new Color(14, 13, 29), flariumWorkbench);
			ModTile tile32 = TileLoader.GetTile(sacredTools.TileType("FrostSapling"));
			ModTranslation frostSapling = tile32.CreateMapEntryName();
			frostSapling.AddTranslation(GameCulture.Russian, "Саженец");
			tile32.AddMapEntry(new Color(75, 161, 186), frostSapling);
			ModTile tile33 = TileLoader.GetTile(sacredTools.TileType("FruitLantern"));
			ModTranslation fruitLantern = tile33.CreateMapEntryName();
			fruitLantern.AddTranslation(GameCulture.Russian, "Фонарь фрукта жизни");
			tile33.AddMapEntry(new Color(100, 156, 14), fruitLantern);
			ModTile tile34 = TileLoader.GetTile(sacredTools.TileType("FStatue"));
			ModTranslation fStatue = tile34.CreateMapEntryName();
			fStatue.AddTranslation(GameCulture.Russian, "Статуя");
			tile34.AddMapEntry(new Color(123, 123, 123), fStatue);
			ModTile tile35 = TileLoader.GetTile(sacredTools.TileType("FuryMonolith"));
			ModTranslation furyMonolith = tile35.CreateMapEntryName();
			furyMonolith.AddTranslation(GameCulture.Russian, "Герб кузни");
			tile35.AddMapEntry(new Color(246, 198, 47), furyMonolith);
			ModTile tile36 = TileLoader.GetTile(sacredTools.TileType("HarpyTrophy"));
			ModTranslation harpyTrophy = tile36.CreateMapEntryName();
			harpyTrophy.AddTranslation(GameCulture.Russian, "Трофей");
			tile36.AddMapEntry(new Color(120, 85, 60), harpyTrophy);
			ModTile tile37 = TileLoader.GetTile(sacredTools.TileType("HarpyTrophy2"));
			ModTranslation harpyTrophy2 = tile37.CreateMapEntryName();
			harpyTrophy2.AddTranslation(GameCulture.Russian, "Трофей");
			tile37.AddMapEntry(new Color(120, 85, 60), harpyTrophy2);
			ModTile tile38 = TileLoader.GetTile(sacredTools.TileType("LapisOre"));
			ModTranslation lapisOre = tile38.CreateMapEntryName();
			lapisOre.AddTranslation(GameCulture.Russian, "Лазурит");
			tile38.AddMapEntry(new Color(18, 22, 128), lapisOre);
			ModTile tile39 = TileLoader.GetTile(sacredTools.TileType("LunarAltar"));
			ModTranslation lunarAltar = tile39.CreateMapEntryName();
			lunarAltar.AddTranslation(GameCulture.Russian, "Тиридиевый инфузер");
			tile39.AddMapEntry(new Color(22, 21, 21), lunarAltar);
			ModTile tile40 = TileLoader.GetTile(sacredTools.TileType("LunarCrate"));
			ModTranslation lunarCrate = tile40.CreateMapEntryName();
			lunarCrate.AddTranslation(GameCulture.Russian, "Тиридиевое хранилище");
			tile40.AddMapEntry(new Color(22, 21, 21), lunarCrate);
			ModTile tile41 = TileLoader.GetTile(sacredTools.TileType("LunarTrophy"));
			ModTranslation lunarTrophy = tile41.CreateMapEntryName();
			lunarTrophy.AddTranslation(GameCulture.Russian, "Обелиск Лунариан");
			tile41.AddMapEntry(new Color(22, 21, 21), lunarTrophy);
			ModTile tile42 = TileLoader.GetTile(sacredTools.TileType("OblivionAltar"));
			ModTranslation oblivionAltar = tile42.CreateMapEntryName();
			oblivionAltar.AddTranslation(GameCulture.Russian, "Алтарь из адского камня");
			tile42.AddMapEntry(new Color(139, 23, 5), oblivionAltar);
			ModTile tile43 = TileLoader.GetTile(sacredTools.TileType("OblivionForge"));
			ModTranslation oblivionForge = tile43.CreateMapEntryName();
			oblivionForge.AddTranslation(GameCulture.Russian, "Кузня Забвения");
			tile43.AddMapEntry(new Color(43, 11, 88), oblivionForge);
			ModTile tile44 = TileLoader.GetTile(sacredTools.TileType("OblivionOreBlock"));
			ModTranslation oblivionOreBlock = tile44.CreateMapEntryName();
			oblivionOreBlock.AddTranslation(GameCulture.Russian, "Осколки Забвения");
			tile44.AddMapEntry(new Color(181, 53, 212), oblivionOreBlock);
			ModTile tile45 = TileLoader.GetTile(sacredTools.TileType("OblivionTrophy"));
			ModTranslation oblivionTrophy = tile45.CreateMapEntryName();
			oblivionTrophy.AddTranslation(GameCulture.Russian, "Трофей Абаддон");
			tile45.AddMapEntry(new Color(152, 56, 171), oblivionTrophy);
			ModTile tile46 = TileLoader.GetTile(sacredTools.TileType("PandolarSigil"));
			ModTranslation pandolarSigil = tile46.CreateMapEntryName();
			pandolarSigil.AddTranslation(GameCulture.Russian, "Пандоларский сигил");
			tile46.AddMapEntry(new Color(180, 234, 237), pandolarSigil);
			ModTile tile47 = TileLoader.GetTile(sacredTools.TileType("PrimordiaTrophy"));
			ModTranslation primordiaTrophy = tile47.CreateMapEntryName();
			primordiaTrophy.AddTranslation(GameCulture.Russian, "Трофей");
			tile47.AddMapEntry(new Color(120, 85, 60), primordiaTrophy);
			ModTile tile48 = TileLoader.GetTile(sacredTools.TileType("RainDrum"));
			ModTranslation rainDrum = tile48.CreateMapEntryName();
			rainDrum.AddTranslation(GameCulture.Russian, "Дождевой барабан");
			tile48.AddMapEntry(new Color(103, 118, 112), rainDrum);
			ModTile tile49 = TileLoader.GetTile(sacredTools.TileType("RoyalThrone"));
			ModTranslation royalThrone = tile49.CreateMapEntryName();
			royalThrone.AddTranslation(GameCulture.Russian, "Королевский трон");
			tile49.AddMapEntry(new Color(158, 0, 0), royalThrone);
			ModTile tile50 = TileLoader.GetTile(sacredTools.TileType("SerpentTrophy"));
			ModTranslation serpentTrophy = tile50.CreateMapEntryName();
			serpentTrophy.AddTranslation(GameCulture.Russian, "Змеиный обелиск");
			tile50.AddMapEntry(new Color(29, 27, 57), serpentTrophy);
			ModTile tile51 = TileLoader.GetTile(sacredTools.TileType("SerpentTrophy_Lame"));
			ModTranslation serpentTrophyLame = tile51.CreateMapEntryName();
			serpentTrophyLame.AddTranslation(GameCulture.Russian, "Трофей Арагура");
			tile51.AddMapEntry(new Color(204, 78, 40), serpentTrophyLame);
			ModTile tile52 = TileLoader.GetTile(sacredTools.TileType("SerpentTrophy_Lame"));
			ModTranslation spiderBanners = tile52.CreateMapEntryName();
			spiderBanners.AddTranslation(GameCulture.Russian, "Знамя");
			tile52.AddMapEntry(new Color(13, 88, 130), spiderBanners);
			ModTile tile53 = TileLoader.GetTile(sacredTools.TileType("TheFlamingBeanbag"));
			ModTranslation theFlamingBeanbag = tile53.CreateMapEntryName();
			theFlamingBeanbag.AddTranslation(GameCulture.Russian, "Пылающее кресло-мешок");
			tile53.AddMapEntry(new Color(191, 72, 19), theFlamingBeanbag);
			ModTile tile54 = TileLoader.GetTile(sacredTools.TileType("TrophyDecree"));
			ModTranslation trophyDecree = tile54.CreateMapEntryName();
			trophyDecree.AddTranslation(GameCulture.Russian, "Трофей");
			tile54.AddMapEntry(new Color(120, 85, 60), trophyDecree);
			ModTile tile55 = TileLoader.GetTile(sacredTools.TileType("TrophyErazor"));
			ModTranslation trophyErazor = tile55.CreateMapEntryName();
			trophyErazor.AddTranslation(GameCulture.Russian, "Трофей Ирейзора");
			tile55.AddMapEntry(new Color(23, 12, 64), trophyErazor);
			ModTile tile56 = TileLoader.GetTile(sacredTools.TileType("TrophyLunarians"));
			ModTranslation trophyLunarians = tile56.CreateMapEntryName();
			trophyLunarians.AddTranslation(GameCulture.Russian, "Трофей Потерянных близнецов");
			tile56.AddMapEntry(new Color(133, 55, 55), trophyLunarians);
			ModTile tile57 = TileLoader.GetTile(sacredTools.TileType("TrophyNihilus"));
			ModTranslation trophyNihilus = tile57.CreateMapEntryName();
			trophyNihilus.AddTranslation(GameCulture.Russian, "Трофей Нигилуса");
			tile57.AddMapEntry(new Color(255, 96, 117), trophyNihilus);
			ModTile tile58 = TileLoader.GetTile(sacredTools.TileType("TrophyPumpkin"));
			ModTranslation trophyPumpkin = tile58.CreateMapEntryName();
			trophyPumpkin.AddTranslation(GameCulture.Russian, "Трофей");
			tile58.AddMapEntry(new Color(120, 85, 60), trophyPumpkin);
			ModTile tile59 = TileLoader.GetTile(sacredTools.TileType("AsthralBed"));
			ModTranslation asthralBed = tile59.CreateMapEntryName();
			asthralBed.AddTranslation(GameCulture.Russian, "Азралтитовая кровать");
			tile59.AddMapEntry(new Color(23, 12, 64), asthralBed);
			ModTile tile60 = TileLoader.GetTile(sacredTools.TileType("AsthralBookshelf"));
			ModTranslation asthralBookshelf = tile60.CreateMapEntryName();
			asthralBookshelf.AddTranslation(GameCulture.Russian, "Азралтитовый книжный шкаф");
			tile60.AddMapEntry(new Color(23, 12, 64), asthralBookshelf);
			ModTile tile61 = TileLoader.GetTile(sacredTools.TileType("AsthralCandelabra"));
			ModTranslation asthralCandelabra = tile61.CreateMapEntryName();
			asthralCandelabra.AddTranslation(GameCulture.Russian, "Азралтитовый канделябр");
			tile61.AddMapEntry(new Color(23, 12, 64), asthralCandelabra);
			ModTile tile62 = TileLoader.GetTile(sacredTools.TileType("AsthralCandle"));
			ModTranslation asthralCandle = tile62.CreateMapEntryName();
			asthralCandle.AddTranslation(GameCulture.Russian, "Азралтитовая свеча");
			tile62.AddMapEntry(new Color(23, 12, 64), asthralCandle);
			ModTile tile63 = TileLoader.GetTile(sacredTools.TileType("AsthralChair"));
			ModTranslation asthralChair = tile63.CreateMapEntryName();
			asthralChair.AddTranslation(GameCulture.Russian, "Азралтитовый стул");
			tile63.AddMapEntry(new Color(23, 12, 64), asthralChair);
			ModTile tile64 = TileLoader.GetTile(sacredTools.TileType("AsthralChandelier"));
			ModTranslation asthralChandelier = tile64.CreateMapEntryName();
			asthralChandelier.AddTranslation(GameCulture.Russian, "Азралтитовая люстра");
			tile64.AddMapEntry(new Color(23, 12, 64), asthralChandelier);
			ModTile tile65 = TileLoader.GetTile(sacredTools.TileType("AsthralChestTile"));
			ModTranslation asthralChestTile = tile65.CreateMapEntryName();
			asthralChestTile.AddTranslation(GameCulture.Russian, "Азралтитовый сундук");
			tile65.AddMapEntry(new Color(23, 12, 64), asthralChestTile);
			ModTile tile66 = TileLoader.GetTile(sacredTools.TileType("AsthralDoorClosed"));
			ModTranslation asthralDoorClosed = tile66.CreateMapEntryName();
			asthralDoorClosed.AddTranslation(GameCulture.Russian, "Азралтитовые двери");
			tile66.AddMapEntry(new Color(23, 12, 64), asthralDoorClosed);
			ModTile tile67 = TileLoader.GetTile(sacredTools.TileType("AsthralDoorOpen"));
			ModTranslation asthralDoorOpen = tile67.CreateMapEntryName();
			asthralDoorOpen.AddTranslation(GameCulture.Russian, "Азралтитовые двери");
			tile67.AddMapEntry(new Color(23, 12, 64), asthralDoorOpen);
			ModTile tile68 = TileLoader.GetTile(sacredTools.TileType("AsthralDresser"));
			ModTranslation asthralDresser = tile68.CreateMapEntryName();
			asthralDresser.AddTranslation(GameCulture.Russian, "Азралтитовый комод");
			tile68.AddMapEntry(new Color(23, 12, 64), asthralDresser);
			ModTile tile69 = TileLoader.GetTile(sacredTools.TileType("AsthralLamp"));
			ModTranslation asthralLamp = tile69.CreateMapEntryName();
			asthralLamp.AddTranslation(GameCulture.Russian, "Азралтитовая лампа");
			tile69.AddMapEntry(new Color(23, 12, 64), asthralLamp);
			ModTile tile70 = TileLoader.GetTile(sacredTools.TileType("AsthralLantern"));
			ModTranslation asthralLantern = tile70.CreateMapEntryName();
			asthralLantern.AddTranslation(GameCulture.Russian, "Азралтитовый фонарь");
			tile70.AddMapEntry(new Color(23, 12, 64), asthralLantern);
			ModTile tile71 = TileLoader.GetTile(sacredTools.TileType("AsthralSofa"));
			ModTranslation asthralSofa = tile71.CreateMapEntryName();
			asthralSofa.AddTranslation(GameCulture.Russian, "Азралтитовый диван");
			tile71.AddMapEntry(new Color(23, 12, 64), asthralSofa);
			ModTile tile72 = TileLoader.GetTile(sacredTools.TileType("AsthralTable"));
			ModTranslation asthralTable = tile72.CreateMapEntryName();
			asthralTable.AddTranslation(GameCulture.Russian, "Азралтитовый стол");
			tile72.AddMapEntry(new Color(23, 12, 64), asthralTable);
			ModTile tile73 = TileLoader.GetTile(sacredTools.TileType("AsthralWorkbench"));
			ModTranslation asthralWorkbench = tile73.CreateMapEntryName();
			asthralWorkbench.AddTranslation(GameCulture.Russian, "Азралтитовый верстак");
			tile73.AddMapEntry(new Color(23, 12, 64), asthralWorkbench);
			ModTile tile74 = TileLoader.GetTile(sacredTools.TileType("AraneasEgg"));
			ModTranslation araneasEgg = tile74.CreateMapEntryName();
			araneasEgg.AddTranslation(GameCulture.Russian, "Загадочная статуя");
			tile74.AddMapEntry(new Color(81, 4, 34), araneasEgg);
			ModTile tile75 = TileLoader.GetTile(sacredTools.TileType("VenomiteOre"));
			ModTranslation venomiteOre = tile75.CreateMapEntryName();
			venomiteOre.AddTranslation(GameCulture.Russian, "Отравитная руда");
			tile75.AddMapEntry(new Color(81, 4, 34), venomiteOre);
			ModTile tile76 = TileLoader.GetTile(sacredTools.TileType("WeaverChest"));
			ModTranslation weaverChest = tile76.CreateMapEntryName();
			weaverChest.AddTranslation(GameCulture.Russian, "Ткацкий сундук");
			tile76.AddMapEntry(new Color(208, 139, 90), weaverChest);
			ModTile tile77 = TileLoader.GetTile(sacredTools.TileType("ArachnophobiaBox"));
			ModTranslation arachnophobiaBox = tile77.CreateMapEntryName();
			arachnophobiaBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile77.AddMapEntry(new Color(200, 200, 200), arachnophobiaBox);
			ModTile tile78 = TileLoader.GetTile(sacredTools.TileType("BeforeTheStormBox"));
			ModTranslation beforeTheStormBox = tile78.CreateMapEntryName();
			beforeTheStormBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile78.AddMapEntry(new Color(200, 200, 200), beforeTheStormBox);
			ModTile tile79 = TileLoader.GetTile(sacredTools.TileType("DanBox"));
			ModTranslation danBox = tile79.CreateMapEntryName();
			danBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile79.AddMapEntry(new Color(200, 200, 200), danBox);
			ModTile tile80 = TileLoader.GetTile(sacredTools.TileType("DarkBox"));
			ModTranslation darkBox = tile80.CreateMapEntryName();
			darkBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile80.AddMapEntry(new Color(200, 200, 200), darkBox);
			ModTile tile81 = TileLoader.GetTile(sacredTools.TileType("DecreeBox"));
			ModTranslation decreeBox = tile81.CreateMapEntryName();
			decreeBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile81.AddMapEntry(new Color(200, 200, 200), decreeBox);
			ModTile tile82 = TileLoader.GetTile(sacredTools.TileType("DepthsBox"));
			ModTranslation depthsBox = tile82.CreateMapEntryName();
			depthsBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile82.AddMapEntry(new Color(200, 200, 200), depthsBox);
			ModTile tile83 = TileLoader.GetTile(sacredTools.TileType("FinalBox"));
			ModTranslation finalBox = tile83.CreateMapEntryName();
			finalBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile83.AddMapEntry(new Color(200, 200, 200), finalBox);
			ModTile tile84 = TileLoader.GetTile(sacredTools.TileType("FlameBox"));
			ModTranslation flameBox = tile84.CreateMapEntryName();
			flameBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile84.AddMapEntry(new Color(200, 200, 200), flameBox);
			ModTile tile85 = TileLoader.GetTile(sacredTools.TileType("JensenBox"));
			ModTranslation jensenBox = tile85.CreateMapEntryName();
			jensenBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile85.AddMapEntry(new Color(200, 200, 200), jensenBox);
			ModTile tile86 = TileLoader.GetTile(sacredTools.TileType("LunarBox"));
			ModTranslation lunarBox = tile86.CreateMapEntryName();
			lunarBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile86.AddMapEntry(new Color(200, 200, 200), lunarBox);
			ModTile tile87 = TileLoader.GetTile(sacredTools.TileType("PrimordiaBox"));
			ModTranslation primordiaBox = tile87.CreateMapEntryName();
			primordiaBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile87.AddMapEntry(new Color(200, 200, 200), primordiaBox);
			ModTile tile88 = TileLoader.GetTile(sacredTools.TileType("QueenBox"));
			ModTranslation queenBox = tile88.CreateMapEntryName();
			queenBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile88.AddMapEntry(new Color(200, 200, 200), queenBox);
			ModTile tile89 = TileLoader.GetTile(sacredTools.TileType("ScorchedSandstormBox"));
			ModTranslation scorchedSandstormBox = tile89.CreateMapEntryName();
			scorchedSandstormBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile89.AddMapEntry(new Color(200, 200, 200), scorchedSandstormBox);
			ModTile tile90 = TileLoader.GetTile(sacredTools.TileType("SpookyBox"));
			ModTranslation spookyBox = tile90.CreateMapEntryName();
			spookyBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile90.AddMapEntry(new Color(200, 200, 200), spookyBox);
			ModTile tile91 = TileLoader.GetTile(sacredTools.TileType("TombOfFearBox"));
			ModTranslation tombOfFearBox = tile91.CreateMapEntryName();
			tombOfFearBox.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка");
			tile91.AddMapEntry(new Color(200, 200, 200), tombOfFearBox);
			ModTile tile92 = TileLoader.GetTile(sacredTools.TileType("DecreeObelisk"));
			ModTranslation decreeObelisk = tile92.CreateMapEntryName();
			decreeObelisk.AddTranslation(GameCulture.Russian, "Обелиск Дикри, морозного хищника");
			tile92.AddMapEntry(new Color(23, 12, 64), decreeObelisk);
			ModTile tile93 = TileLoader.GetTile(sacredTools.TileType("PumpboiObelisk"));
			ModTranslation pumpboiObelisk = tile93.CreateMapEntryName();
			pumpboiObelisk.AddTranslation(GameCulture.Russian, "Ужасный обелиск");
			tile93.AddMapEntry(new Color(23, 12, 64), pumpboiObelisk);
			ModTile tile94 = TileLoader.GetTile(sacredTools.TileType("AbaddonPainting"));
			ModTranslation abaddonPainting = tile94.CreateMapEntryName();
			abaddonPainting.AddTranslation(GameCulture.Russian, "НЕ СМЕЙ ИГНОРИРОВАТЬ МЕНЯ, СМЕРТНЫЙ!");
			tile94.AddMapEntry(new Color(76, 45, 8), abaddonPainting);
			ModTile tile95 = TileLoader.GetTile(sacredTools.TileType("Daryl"));
			ModTranslation daryl = tile95.CreateMapEntryName();
			daryl.AddTranslation(GameCulture.Russian, "Картина");
			tile95.AddMapEntry(new Color(76, 45, 8), daryl);
			ModTile tile96 = TileLoader.GetTile(sacredTools.TileType("Deepfreeze"));
			ModTranslation deepfreeze = tile96.CreateMapEntryName();
			deepfreeze.AddTranslation(GameCulture.Russian, "Картина");
			tile96.AddMapEntry(new Color(76, 45, 8), deepfreeze);
			ModTile tile97 = TileLoader.GetTile(sacredTools.TileType("GodOfTerraria"));
			ModTranslation godOfTerraria = tile97.CreateMapEntryName();
			godOfTerraria.AddTranslation(GameCulture.Russian, "Картина");
			tile97.AddMapEntry(new Color(76, 45, 8), godOfTerraria);
			ModTile tile98 = TileLoader.GetTile(sacredTools.TileType("Kappa"));
			ModTranslation kappa = tile98.CreateMapEntryName();
			kappa.AddTranslation(GameCulture.Russian, "Картина");
			tile98.AddMapEntry(new Color(76, 45, 8), kappa);
			ModTile tile99 = TileLoader.GetTile(sacredTools.TileType("KipSmug"));
			ModTranslation kipSmug = tile99.CreateMapEntryName();
			kipSmug.AddTranslation(GameCulture.Russian, "Картина");
			tile99.AddMapEntry(new Color(76, 45, 8), kipSmug);
			ModTile tile100 = TileLoader.GetTile(sacredTools.TileType("LunaticCultistPainting"));
			ModTranslation lunaticCultistPainting = tile100.CreateMapEntryName();
			lunaticCultistPainting.AddTranslation(GameCulture.Russian, "Картина");
			tile100.AddMapEntry(new Color(76, 45, 8), lunaticCultistPainting);
			ModTile tile101 = TileLoader.GetTile(sacredTools.TileType("MoodPainting"));
			ModTranslation moodPainting = tile101.CreateMapEntryName();
			moodPainting.AddTranslation(GameCulture.Russian, "Картина");
			tile101.AddMapEntry(new Color(76, 45, 8), moodPainting);
			ModTile tile102 = TileLoader.GetTile(sacredTools.TileType("Polarius"));
			ModTranslation polarius = tile102.CreateMapEntryName();
			polarius.AddTranslation(GameCulture.Russian, "Картина");
			tile102.AddMapEntry(new Color(76, 45, 8), polarius);
			ModTile tile103 = TileLoader.GetTile(sacredTools.TileType("StrangeMap"));
			ModTranslation strangeMap = tile103.CreateMapEntryName();
			strangeMap.AddTranslation(GameCulture.Russian, "Странная карта");
			tile103.AddMapEntry(new Color(142, 134, 112), strangeMap);
			ModTile tile104 = TileLoader.GetTile(sacredTools.TileType("Warmth"));
			ModTranslation warmth = tile104.CreateMapEntryName();
			warmth.AddTranslation(GameCulture.Russian, "Картина");
			tile104.AddMapEntry(new Color(76, 45, 8), warmth);
			ModTile tile105 = TileLoader.GetTile(sacredTools.TileType("DeadBush"));
			ModTranslation deadBush = tile105.CreateMapEntryName();
			deadBush.AddTranslation(GameCulture.Russian, "Мертвый кустарник");
			tile105.AddMapEntry(new Color(126, 97, 74), deadBush);
			ModTile tile106 = TileLoader.GetTile(sacredTools.TileType("Enduflora"));
			ModTranslation enduflora = tile106.CreateMapEntryName();
			enduflora.AddTranslation(GameCulture.Russian, "Стойкоцвет");
			tile106.AddMapEntry(new Color(28, 24, 43), enduflora);
			ModTile tile107 = TileLoader.GetTile(sacredTools.TileType("Illumifern"));
			ModTranslation illumifern = tile107.CreateMapEntryName();
			illumifern.AddTranslation(GameCulture.Russian, "Иллюзорный папоротник");
			tile107.AddMapEntry(new Color(79, 127, 165), illumifern);
			ModTile tile108 = TileLoader.GetTile(sacredTools.TileType("LivingRoot"));
			ModTranslation livingRoot = tile108.CreateMapEntryName();
			livingRoot.AddTranslation(GameCulture.Russian, "Живой корень");
			tile108.AddMapEntry(new Color(79, 127, 165), livingRoot);
			ModTile tile109 = TileLoader.GetTile(sacredTools.TileType("ManaFruit"));
			ModTranslation manaFruit = tile109.CreateMapEntryName();
			manaFruit.AddTranslation(GameCulture.Russian, "Фрукт маны");
			tile109.AddMapEntry(new Color(100, 156, 14), manaFruit);
			ModTile tile110 = TileLoader.GetTile(sacredTools.TileType("Welkinbell"));
			ModTranslation welkinbell = tile110.CreateMapEntryName();
			welkinbell.AddTranslation(GameCulture.Russian, "Небозвон");
			tile110.AddMapEntry(new Color(180, 234, 237), welkinbell);
		}
	}
}
