using System.Collections.Generic;
using CalamityRuTranslate.Common.DataStructures;
using Microsoft.Xna.Framework;

namespace CalamityRuTranslate.Catalogs;

internal static class CalamityCatalog
{
    internal static readonly List<string> Projectiles = new()
    {
        "BelchingCoralSpike",
        "CrabBoulder",
        "CragmawAcidDrop",
        "CragmawBeam",
        "CragmawExplosion",
        "CragmawSpike",
        "CragmawVibeCheckChain",
        "CrimsonSpike",
        "DraedonLaser",
        "EarthRockBig",
        "EarthRockSmall",
        "FlakAcid",
        "FlameBurstHostile",
        "GammaAcid",
        "GammaBeam",
        "GammaRayBurst",
        "HorsWaterBlast",
        "InkBombHostile",
        "InkPoisonCloud",
        "MantisRing",
        "MaulerAcidBubble",
        "MaulerAcidDrop",
        "NuclearBulletLarge",
        "NuclearBulletMedium",
        "NuclearToadGoo",
        "OrthoceraStream",
        "PearlBurst",
        "PearlRain",
        "PufferExplosion",
        "StormMarkHostile",
        "SulphuricAcidBubble",
        "SulphuricAcidMist",
        "TornadoHostile",
        "ToxicMinnowCloud",
        "TrilobiteSpike",
        "ApolloChargeTelegraph",
        "ApolloFireball",
        "ApolloRocket",
        "AresDeathBeamStart",
        "AresDeathBeamTelegraph",
        "AresGaussNukeProjectile",
        "AresGaussNukeProjectileBoom",
        "AresGaussNukeProjectileSpark",
        "AresLaserBeamStart",
        "AresPlasmaBolt",
        "AresPlasmaFireball",
        "AresTeslaOrb",
        "ArtemisChargeTelegraph",
        "ArtemisDeathrayTelegraph",
        "ArtemisLaser",
        "ArtemisSpinLaserbeam",
        "AstralFlame",
        "AstralGodRay",
        "AstralLaser",
        "AstralShot2",
        "BigFlare",
        "BigFlare2",
        "BirbAura",
        "BirbAuraFlare",
        "BloodGeyser",
        "BrimstoneBall",
        "BrimstoneBarrage",
        "BrimstoneFire",
        "BrimstoneHellblast",
        "BrimstoneHellblast2",
        "BrimstoneHellfireball",
        "BrimstoneMonster",
        "BrimstoneRay",
        "BrimstoneTargetRay",
        "BrimstoneWave",
        "BrokenApolloLens",
        "BrokenArtemisLens",
        "DarkEnergyBall",
        "DarkEnergyBall2",
        "DarkOrb",
        "DestroyerCursedLaser",
        "DestroyerElectricLaser",
        "DeusMine",
        "DeusRitualDrama",
        "DoGBeam",
        "DoGBeamPortal",
        "DoGDeath",
        "DoGDeathBoom",
        "DoGFire",
        "DoGP1EndPortal",
        "DoGTeleportRift",
        "DraedonSummonLaser",
        "DyingSun",
        "EssenceDust",
        "Flare",
        "FlareBomb",
        "FlareDust",
        "FlareDust2",
        "Flarenado",
        "FrostMist",
        "GreatSandBlast",
        "HealOrbProv",
        "HellfireExplosion",
        "HiveBombGoliath",
        "HolyAura",
        "HolyBlast",
        "HolyBomb",
        "HolyBurnOrb",
        "HolyExplosionBoom",
        "HolyFire",
        "HolyFire2",
        "HolyFlare",
        "HolyLight",
        "HolySpear",
        "IceBlast",
        "IceBomb",
        "IceRain",
        "IchorBlob",
        "IchorShot",
        "Infernado",
        "Infernado2",
        "InfernadoRevenge",
        "JewelProjectile",
        "LeviathanBomb",
        "LeviathanSpawner",
        "MajesticSparkle",
        "MoltenBlast",
        "MoltenBlob",
        "MushBomb",
        "MushBombFall",
        "OldDukeGore",
        "OldDukeSummonDrop",
        "OldDukeToothBallSpike",
        "OldDukeVortex",
        "PeanutRocket",
        "OverlyDramaticDukeSummoner",
        "PhantomBlast",
        "PhantomBlast2",
        "PhantomGhostShot",
        "PhantomHookShot",
        "PhantomMine",
        "PhantomShot",
        "PhantomShot2",
        "PlagueExplosion",
        "PlagueStingerGoliath",
        "PlagueStingerGoliathV2",
        "ProfanedSpear",
        "ProvidenceCrystal",
        "ProvidenceCrystalShard",
        "ProvidenceHolyRay",
        "RavagerFlame",
        "RedLightning",
        "RedLightningFeather",
        "SandBlast",
        "SandPoisonCloud",
        "SandPoisonCloudOldDuke",
        "SandTooth",
        "SCalRitualDrama",
        "ScavengerLaser",
        "ScavengerNuke",
        "ShadeNimbusHostile",
        "ShaderainHostile",
        "ShadowflameFireball",
        "Shadowflamethrower",
        "SignusScythe",
        "SirenSong",
        "SkyFlare",
        "SkyFlareRevenge",
        "SporeGasPlantera",
        "SupremeCataclysmFist",
        "SupremeCatastropheSlash",
        "SwirlingFire",
        "ThanatosBeamStart",
        "ThanatosBeamTelegraph",
        "ThanatosLaser",
        "ToxicCloud",
        "VileClot",
        "WaterSpear",
        "YharonFireball",
        "YharonFireball2",
        "AcidDrop",
        "BrimstoneGeyser",
        "GeyserTelegraph",
        "HotSteam",
        "LavaChunk",
        "MurkySteam",
        "LightningMark",
        "ThermalSteam",
        "SmokeTelegraph",
        "SCalBrimstoneFireblast",
        "SCalBrimstoneGigablast",
        "StormWeaverFrostWaveTelegraph",
        "UnstableCrimulanGlob",
        "UnstableEbonianGlob",
        "YharonBulletHellVortex",
        "AstralMeteorProj",
        "LightningCloud",
    };

    internal static readonly List<TileData> Tiles = new()
    {
        new TileData("ArenaTile", "", new Color(128, 0, 0)),
        new TileData("AgedSecurityChestTile", "", new Color(130, 119, 115), true),
        new TileData("ChargingStation", "", new Color(67, 72, 81)),
        new TileData("DraedonLabTurret", "", new Color(67, 72, 81)),
        new TileData("InactivePowerCellFactory", "", new Color(67, 72, 81)),
        new TileData("LabHologramProjector", "", new Color(99, 131, 199)),
        new TileData("PowerCellFactory", "", new Color(67, 72, 81)),
        new TileData("SecurityChestTile", "", new Color(130, 119, 115), true),
        new TileData("CodebreakerTile", "", new Color(92, 107, 112)),
        new TileData("RoxTile", "", new Color(13, 88, 130)),
        new TileData("SulphurousCrateTile", "", new Color(47, 79, 79)),
        new TileData("SulphurousTorch", "", new Color(253, 221, 3)),
        new TileData("AbyssalPots", "", new Color(47, 79, 79)),
        new TileData("AcidWoodTreeSapling", "", new Color(113, 90, 71)),
        new TileData("LumenylCrystals", "", new Color(0, 150, 200)),
        new TileData("PlantyMush", "", new Color(84, 102, 39)),
        new TileData("RustyChestTile", "", new Color(113, 90, 71), true),
        new TileData("SteamGeyser1", "", new Color(103, 65, 64)),
        new TileData("SteamGeyser2", "", new Color(103, 65, 64)),
        new TileData("SteamGeyser3", "", new Color(103, 65, 64)),
        new TileData("SulphuricFossil1", "", new Color(113, 90, 71)),
        new TileData("SulphuricFossil2", "", new Color(113, 90, 71)),
        new TileData("SulphuricFossil3", "", new Color(113, 90, 71)),
        new TileData("SulphurousColumn", "", new Color(150, 100, 50)),
        new TileData("SulphurousPots", "", new Color(226, 205, 101)),
        new TileData("SulphurousRib1", "", new Color(57, 48, 83)),
        new TileData("SulphurousRib2", "", new Color(57, 48, 83)),
        new TileData("SulphurousRib3", "", new Color(57, 48, 83)),
        new TileData("SulphurousRib4", "", new Color(57, 48, 83)),
        new TileData("SulphurousRib5", "", new Color(57, 48, 83)),
        new TileData("SulphurousVines", "", new Color(0, 50, 0)),
        new TileData("ViperVines", "", new Color(0, 50, 0)),
        new TileData("SulphurousStalacmite1", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalacmite2", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalacmite3", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalacmite4", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalacmite5", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalacmite6", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite1", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite2", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite3", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite4", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite5", "", new Color(57, 48, 83)),
        new TileData("SulphurousStalactite6", "", new Color(57, 48, 83)),
        new TileData("AstralBeacon", "", new Color(128, 128, 158)),
        new TileData("AstralChestLocked", "chestAstral", new Color(174, 129, 92), true),
        new TileData("AstralChestLocked", "chestAstral_Locked", new Color(174, 129, 92), "AstralChest_Locked"),
        new TileData("AstralCrateTile", "", new Color(47, 66, 90)),
        new TileData("AstralTreeSapling", "", new Color(200, 200, 200)),
        new TileData("NovaeSlag", "", new Color(133, 69, 115)),
        new TileData("CelestialRemains", "", new Color(59, 50, 77)),
        new TileData("AstralPalmSapling", "", new Color(200, 200, 200)),
        new TileData("AstralSnowTreeSapling", "", new Color(200, 200, 200)),
        new TileData("BrimstoneCrateTile", "", new Color(128, 0, 0)),
        new TileData("AgedLaboratoryConsole", "", new Color(82, 67, 66)),
        new TileData("AgedLaboratoryContainmentBox", "", new Color(82, 67, 66)),
        new TileData("AgedLaboratoryDisplay", "", Color.DarkSlateGray),
        new TileData("AgedLaboratoryDoorClosed", "", Color.DarkSlateGray),
        new TileData("AgedLaboratoryDoorOpen", "", Color.DarkSlateGray),
        new TileData("AgedLaboratoryElectricPanel", "", Color.DimGray),
        new TileData("AgedLaboratoryScreen", "", Color.DarkGray),
        new TileData("AgedLaboratoryServer", "", new Color(82, 67, 66)),
        new TileData("AgedLaboratoryTerminal", "", Color.DarkSlateGray),
        new TileData("AgedReinforcedCrate", "", Color.DimGray),
        new TileData("LaboratoryConsole", "", new Color(82, 67, 66)),
        new TileData("LaboratoryContainmentBox", "", new Color(82, 67, 66)),
        new TileData("LaboratoryDisplay", "", Color.DarkSlateGray),
        new TileData("LaboratoryDoorClosed", "", Color.DarkSlateGray),
        new TileData("LaboratoryDoorOpen", "", Color.DarkSlateGray),
        new TileData("LaboratoryElectricPanel", "", Color.DimGray),
        new TileData("LaboratoryScreen", "", Color.DarkGray),
        new TileData("LaboratoryServer", "", new Color(82, 67, 66)),
        new TileData("LaboratoryTerminal", "", Color.DarkSlateGray),
        new TileData("ReinforcedCrate", "", Color.DimGray),
        new TileData("AuricToiletTile", "", new Color(191, 142, 111)),
        new TileData("BabyFlakCrabCageTile", "", new Color(175, 238, 238)),
        new TileData("BabyGhostBellJarTile", "", new Color(64, 224, 208)),
        new TileData("BlueCandle", "", new Color(238, 145, 105)),
        new TileData("BossTrophy", "", new Color(120, 85, 60)),
        new TileData("ChaosCandle", "", new Color(238, 145, 105)),
        new TileData("CorruptionEffigy", "", new Color(126, 156, 134)),
        new TileData("CrimsonEffigy", "", new Color(238, 145, 105)),
        new TileData("EffigyOfDecayPlaceable", "", new Color(113, 90, 71)),
        new TileData("PiggyCageTile", "", new Color(175, 238, 238)),
        new TileData("PinkCandle", "", new Color(238, 145, 105)),
        new TileData("PurpleCandle", "", new Color(238, 145, 105)),
        new TileData("SCalAltar", "", new Color(43, 19, 42)),
        new TileData("SeaMinnowJarTile", "", new Color(175, 238, 238)),
        new TileData("TranquilityCandle", "", new Color(238, 145, 105)),
        new TileData("TwinklerInABottleTile", "", new Color(255, 99, 71)),
        new TileData("WulfrumLure", "", new Color(194, 255, 67)),
        new TileData("YellowCandle", "", new Color(238, 145, 105)),
        new TileData("AncientAltar", "", new Color(191, 142, 111)),
        new TileData("AshenAltar", "", new Color(191, 142, 111)),
        new TileData("BotanicPlanter", "", new Color(191, 142, 111)),
        new TileData("CosmicAnvil", "", new Color(159, 125, 201)),
        new TileData("DraedonsForge", "", new Color(230, 157, 41)),
        new TileData("EutrophicShelf", "", new Color(191, 142, 111)),
        new TileData("MonolithAmalgam", "", new Color(191, 142, 111)),
        new TileData("PlagueInfuser", "", new Color(191, 142, 111)),
        new TileData("ProfanedCrucible", "", new Color(191, 142, 111)),
        new TileData("SilvaBasin", "", new Color(191, 142, 111)),
        new TileData("StaticRefiner", "", new Color(191, 142, 111)),
        new TileData("VoidCondenser", "", new Color(191, 142, 111)),
        new TileData("ThankYouPaintingTile", "", new Color(120, 85, 60)),
        new TileData("AbyssBathtub", "", new Color(191, 142, 111)),
        new TileData("AbyssBed", "", new Color(191, 142, 111)),
        new TileData("AbyssBookcase", "", new Color(191, 142, 111)),
        new TileData("AbyssCandelabra", "", new Color(253, 221, 3)),
        new TileData("AbyssCandle", "", new Color(253, 221, 3)),
        new TileData("AbyssChest", "", new Color(191, 142, 111), true),
        new TileData("AbyssClock", "", new Color(191, 142, 111)),
        new TileData("AbyssDresser", "", new Color(191, 142, 111), true),
        new TileData("AbyssSynth", "", new Color(191, 142, 111)),
        new TileData("AbyssTorch", "", new Color(253, 221, 3)),
        new TileData("AbyssWorkBench", "", new Color(191, 142, 111)),
        new TileData("AcidwoodBathTile", "", new Color(191, 142, 111)),
        new TileData("AcidwoodBedTile", "", new Color(191, 142, 111)),
        new TileData("AcidwoodBookcaseTile", "", new Color(191, 142, 111)),
        new TileData("AcidwoodCandelabraTile", "", new Color(253, 221, 3)),
        new TileData("AcidwoodCandleTile", "", new Color(253, 221, 3)),
        new TileData("AcidwoodChestTile", "", new Color(191, 142, 111), true),
        new TileData("AcidwoodClockTile", "", new Color(191, 142, 111)),
        new TileData("AcidwoodDresserTile", "", new Color(191, 142, 111), true),
        new TileData("AcidwoodPianoTile", "", new Color(191, 142, 111)),
        new TileData("AcidwoodWorkBenchTile", "", new Color(191, 142, 111)),
        new TileData("AncientBasin", "", new Color(191, 142, 111)),
        new TileData("AncientBathtub", "", new Color(191, 142, 111)),
        new TileData("AncientBed", "", new Color(191, 142, 111)),
        new TileData("AncientBookcase", "", new Color(191, 142, 111)),
        new TileData("AncientDresser", "", new Color(191, 142, 111), true),
        new TileData("AncientMonolith", "", new Color(191, 142, 111)),
        new TileData("AncientPipeOrgan", "", new Color(191, 142, 111)),
        new TileData("AncientWorkBench", "", new Color(191, 142, 111)),
        new TileData("AshenBasin", "", new Color(191, 142, 111)),
        new TileData("AshenBathtub", "", new Color(191, 142, 111)),
        new TileData("AshenBed", "", new Color(191, 142, 111)),
        new TileData("AshenBookcase", "", new Color(191, 142, 111)),
        new TileData("AshenCandelabra", "", new Color(253, 221, 3)),
        new TileData("AshenCandle", "", new Color(253, 221, 3)),
        new TileData("AshenChest", "", new Color(174, 129, 92), true),
        new TileData("AshenDresser", "", new Color(191, 142, 111), true),
        new TileData("AshenMonolith", "", new Color(191, 142, 111)),
        new TileData("AshenPipeOrgan", "", new Color(191, 142, 111)),
        new TileData("AshenWorkBench", "", new Color(191, 142, 111)),
        new TileData("MonolithBathtub", "", new Color(191, 142, 111)),
        new TileData("MonolithBed", "", new Color(191, 142, 111)),
        new TileData("MonolithBookcase", "", new Color(191, 142, 111)),
        new TileData("MonolithCandelabra", "", new Color(253, 221, 3)),
        new TileData("MonolithCandle", "", new Color(253, 221, 3)),
        new TileData("MonolithChest", "", new Color(191, 142, 111), true),
        new TileData("MonolithClock", "", new Color(191, 142, 111)),
        new TileData("MonolithDresser", "", new Color(191, 142, 111), true),
        new TileData("MonolithPiano", "", new Color(191, 142, 111)),
        new TileData("MonolithWorkBench", "", new Color(191, 142, 111)),
        new TileData("BotanicBathtub", "", new Color(191, 142, 111)),
        new TileData("BotanicBed", "", new Color(191, 142, 111)),
        new TileData("BotanicBookcase", "", new Color(191, 142, 111)),
        new TileData("BotanicCandelabra", "", new Color(253, 221, 3)),
        new TileData("BotanicCandle", "", new Color(253, 221, 3)),
        new TileData("BotanicChest", "", new Color(191, 142, 111), true),
        new TileData("BotanicClock", "", new Color(191, 142, 111)),
        new TileData("BotanicDresser", "", new Color(191, 142, 111), true),
        new TileData("BotanicPiano", "", new Color(191, 142, 111)),
        new TileData("BotanicWorkBench", "", new Color(191, 142, 111)),
        new TileData("CosmiliteBasinTile", "", new Color(238, 145, 105)),
        new TileData("CosmiliteBathtub", "", new Color(191, 142, 111)),
        new TileData("CosmiliteBed", "", new Color(191, 142, 111)),
        new TileData("CosmiliteBookcase", "", new Color(191, 142, 111)),
        new TileData("CosmiliteCandelabra", "", new Color(253, 221, 3)),
        new TileData("CosmiliteCandle", "", new Color(253, 221, 3)),
        new TileData("CosmiliteChest", "", new Color(191, 142, 111), true),
        new TileData("CosmiliteClock", "", new Color(191, 142, 111)),
        new TileData("CosmiliteDresser", "", new Color(191, 142, 111), true),
        new TileData("CosmilitePiano", "", new Color(191, 142, 111)),
        new TileData("CosmiliteSconce", "", new Color(191, 142, 111)),
        new TileData("CosmiliteWorkBench", "", new Color(191, 142, 111)),
        new TileData("EutrophicBathtub", "", new Color(191, 142, 111)),
        new TileData("EutrophicBed", "", new Color(191, 142, 111)),
        new TileData("EutrophicBookcase", "", new Color(191, 142, 111)),
        new TileData("EutrophicCandelabra", "", new Color(253, 221, 3)),
        new TileData("EutrophicCandle", "", new Color(253, 221, 3)),
        new TileData("EutrophicChest", "", new Color(191, 142, 111), true),
        new TileData("EutrophicClock", "", new Color(191, 142, 111)),
        new TileData("EutrophicDresser", "", new Color(191, 142, 111), true),
        new TileData("EutrophicPiano", "", new Color(191, 142, 111)),
        new TileData("EutrophicWorkBench", "", new Color(191, 142, 111)),
        new TileData("ExoBathtubTile", "", new Color(71, 95, 114)),
        new TileData("ExoBedTile", "", new Color(71, 95, 114)),
        new TileData("ExoBookcaseTile", "", new Color(71, 95, 114)),
        new TileData("ExoCandelabraTile", "", new Color(253, 221, 3)),
        new TileData("ExoCandleTile", "", new Color(253, 221, 3)),
        new TileData("ExoChestTile", "", new Color(71, 95, 114), true),
        new TileData("ExoClockTile", "", new Color(71, 95, 114)),
        new TileData("ExoConsoleTile", "", new Color(71, 95, 114)),
        new TileData("ExoDisplayTile", "", new Color(71, 95, 114)),
        new TileData("ExoDoorClosed", "", new Color(71, 95, 114)),
        new TileData("ExoDoorOpen", "", new Color(71, 95, 114)),
        new TileData("ExoDresserTile", "", new Color(71, 95, 114), true),
        new TileData("ExoKeyboardTile", "", new Color(71, 95, 114)),
        new TileData("ExoScreenTile", "", new Color(71, 95, 114)),
        new TileData("ExoServerTile", "", new Color(71, 95, 114)),
        new TileData("ExoTerminalTile", "", new Color(71, 95, 114)),
        new TileData("ExoToiletTile", "", new Color(71, 95, 114)),
        new TileData("ExoWorkbenchTile", "", new Color(71, 95, 114)),
        new TileData("OtherworldlyBathtub", "", new Color(191, 142, 111)),
        new TileData("OtherworldlyBed", "", new Color(191, 142, 111)),
        new TileData("OtherworldlyBookcase", "", new Color(191, 142, 111)),
        new TileData("OtherworldlyCandelabra", "", new Color(253, 221, 3)),
        new TileData("OtherworldlyCandle", "", new Color(253, 221, 3)),
        new TileData("OtherworldlyChest", "", new Color(191, 142, 111), true),
        new TileData("OtherworldlyClock", "", new Color(191, 142, 111)),
        new TileData("OtherworldlyDresser", "", new Color(191, 142, 111), true),
        new TileData("OtherworldlyPiano", "", new Color(191, 142, 111)),
        new TileData("OtherworldlyWorkBench", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateBasin", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateBathtub", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateBed", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateBookcase", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateCandelabra", "", new Color(253, 221, 3)),
        new TileData("PlaguedPlateCandle", "", new Color(253, 221, 3)),
        new TileData("PlaguedPlateChest", "", new Color(191, 142, 111), true),
        new TileData("PlaguedPlateClock", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateDresser", "", new Color(191, 142, 111), true),
        new TileData("PlaguedPlatePiano", "", new Color(191, 142, 111)),
        new TileData("PlaguedPlateWorkbench", "", new Color(191, 142, 111)),
        new TileData("ProfanedBath", "", new Color(191, 142, 111)),
        new TileData("ProfanedBed", "", new Color(191, 142, 111)),
        new TileData("ProfanedBookcase", "", new Color(191, 142, 111)),
        new TileData("ProfanedCandelabra", "", new Color(253, 221, 3)),
        new TileData("ProfanedCandle", "", new Color(253, 221, 3)),
        new TileData("ProfanedChest", "", new Color(191, 142, 111), true),
        new TileData("ProfanedClock", "", new Color(191, 142, 111)),
        new TileData("ProfanedDresser", "", new Color(191, 142, 111), true),
        new TileData("ProfanedPiano", "", new Color(191, 142, 111)),
        new TileData("ProfanedWorkbench", "", new Color(191, 142, 111)),
        new TileData("MonolithOfTheAccursedTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousBathtubTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousBedTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousBookcaseTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousCandelabraTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousCandleTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousChestTile", "", new Color(43, 19, 42), true),
        new TileData("SacrilegiousClockTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousDresserTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousOrganTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousTableTile", "", new Color(43, 19, 42)),
        new TileData("SacrilegiousWorkBenchTile", "", new Color(43, 19, 42)),
        new TileData("DraedonsAmbienceMusicBox", "", new Color(191, 142, 111)),
        new TileData("SilvaBathtub", "", new Color(191, 142, 111)),
        new TileData("SilvaBed", "", new Color(191, 142, 111)),
        new TileData("SilvaBookcase", "", new Color(191, 142, 111)),
        new TileData("SilvaCandelabra", "", new Color(253, 221, 3)),
        new TileData("SilvaCandle", "", new Color(253, 221, 3)),
        new TileData("SilvaChest", "", new Color(191, 142, 111), true),
        new TileData("SilvaClock", "", new Color(191, 142, 111)),
        new TileData("SilvaDresser", "", new Color(191, 142, 111), true),
        new TileData("SilvaPiano", "", new Color(191, 142, 111)),
        new TileData("SilvaWorkBench", "", new Color(191, 142, 111)),
        new TileData("StatigelBath", "", new Color(191, 142, 111)),
        new TileData("StatigelBed", "", new Color(191, 142, 111)),
        new TileData("StatigelBookcase", "", new Color(191, 142, 111)),
        new TileData("StatigelCandelabra", "", new Color(253, 221, 3)),
        new TileData("StatigelCandle", "", new Color(253, 221, 3)),
        new TileData("StatigelChest", "", new Color(191, 142, 111), true),
        new TileData("StatigelClock", "", new Color(191, 142, 111)),
        new TileData("StatigelDresser", "", new Color(191, 142, 111), true),
        new TileData("StatigelPiano", "", new Color(191, 142, 111)),
        new TileData("StatigelWorkbench", "", new Color(191, 142, 111)),
        new TileData("StratusBathtub", "", new Color(191, 142, 111)),
        new TileData("StratusBed", "", new Color(191, 142, 111)),
        new TileData("StratusBookcase", "", new Color(191, 142, 111)),
        new TileData("StratusCandelabra", "", new Color(253, 221, 3)),
        new TileData("StratusCandle", "", new Color(253, 221, 3)),
        new TileData("StratusChest", "", new Color(191, 142, 111), true),
        new TileData("StratusClock", "", new Color(191, 142, 111)),
        new TileData("StratusDresser", "", new Color(191, 142, 111), true),
        new TileData("StratusPiano", "", new Color(191, 142, 111)),
        new TileData("StratusWorkbench", "", new Color(191, 142, 111)),
        new TileData("VoidBath", "", new Color(191, 142, 111)),
        new TileData("VoidBed", "", new Color(191, 142, 111)),
        new TileData("VoidBookcase", "", new Color(191, 142, 111)),
        new TileData("VoidCandelabra", "", new Color(253, 221, 3)),
        new TileData("VoidCandle", "", new Color(253, 221, 3)),
        new TileData("VoidChest", "", new Color(191, 142, 111), true),
        new TileData("VoidClock", "", new Color(191, 142, 111)),
        new TileData("VoidDresser", "", new Color(191, 142, 111), true),
        new TileData("VoidPiano", "", new Color(191, 142, 111)),
        new TileData("VoidWorkbench", "", new Color(191, 142, 111)),
        new TileData("AerialiteOre", "", new Color(145, 255, 255)),
        new TileData("AerialiteOreDisenchanted", "", new Color(204, 170, 81)),
        new TileData("AstralOre", "", new Color(255, 153, 255)),
        new TileData("AuricOre", "", new Color(255, 200, 0)),
        new TileData("ScoriaOre", "", new Color(210, 101, 28)),
        new TileData("InfernalSuevite", "", new Color(17, 16, 26)),
        new TileData("CryonicOre", "", new Color(0, 0, 150)),
        new TileData("ExodiumOre", "", new Color(51, 48, 68)),
        new TileData("HallowedOre", "", new Color(250, 250, 150)),
        new TileData("PerennialOre", "", new Color(200, 250, 100)),
        new TileData("UelibloomOre", "", new Color(0, 255, 0)),
        new TileData("BrainCoral", "", new Color(36, 61, 111)),
        new TileData("EutrophicSand", "", new Color(92, 145, 167)),
        new TileData("FanCoral", "", new Color(54, 69, 72)),
        new TileData("Navystone", "", new Color(31, 92, 114)),
        new TileData("SeaAnemone", "", new Color(54, 69, 72)),
        new TileData("SeaPrism", "", new Color(0, 150, 200)),
        new TileData("SeaPrismCrystals", "", new Color(0, 150, 200)),
        new TileData("SmallBrainCoral", "", new Color(36, 61, 111)),
        new TileData("SmallTubeCoral", "", new Color(36, 61, 111)),
        new TileData("SunkenCrateTile", "", new Color(106, 218, 230)),
        new TileData("TableCoral", "", new Color(54, 69, 72)),
        new TileData("TubeCoral", "", new Color(36, 61, 111)),
        new TileData("VernalSoil", "", new Color(80, 120, 0)),
        new TileData("AbyssTreasureChest", "", new Color(71, 49, 41), true),
        new TileData("AbyssVent1", "", new Color(106, 80, 102)),
        new TileData("AbyssVent2", "", new Color(106, 80, 102)),
        new TileData("AbyssVent3", "", new Color(106, 80, 102)),
        new TileData("PirateCrate1", "", new Color(97, 69, 52)),
        new TileData("PirateCrate2", "", new Color(97, 69, 52)),
        new TileData("PirateCrate3", "", new Color(97, 69, 52)),
        new TileData("PirateCrate4", "", new Color(97, 69, 52)),
        new TileData("PirateCrate5", "", new Color(97, 69, 52)),
        new TileData("PirateCrate6", "", new Color(97, 69, 52)),
        new TileData("ThermalVent1", "", new Color(132, 56, 42)),
        new TileData("ThermalVent2", "", new Color(132, 56, 42)),
        new TileData("ThermalVent3", "", new Color(132, 56, 42)),
        new TileData("AstralVines", "", new Color(65, 56, 83)),
        new TileData("BrimstoneSlab", "", new Color(79, 55, 70)),
        new TileData("GloomTorch", "", new Color(253, 221, 3)),
        new TileData("SpineSapling", "", new Color(38, 25, 27)),
        new TileData("SpineTree", "", new Color(38, 25, 27)),
        new TileData("OnyxExcavatorTile", "", new Color(128, 0, 128)),
        new TileData("LanternCenterTile", "", new Color(99, 99, 99)),
        new TileData("WulfrumLabstation", "", new Color(71, 95, 114)),
        new TileData("WulfrumBathtub", "", new Color(71, 95, 114)),
        new TileData("WulfrumBed", "", new Color(71, 95, 114)),
        new TileData("WulfrumBookcase", "", new Color(71, 95, 114)),
        new TileData("WulfrumCandelabra", "", new Color(253, 221, 3)),
        new TileData("WulfrumCandle", "", new Color(253, 221, 3)),
        new TileData("WulfrumClock", "", new Color(71, 95, 114)),
        new TileData("WulfrumDresser", "", new Color(71, 95, 114), true),
        new TileData("WulfrumPiano", "", new Color(71, 95, 114)),
        new TileData("WulfrumToilet", "", new Color(71, 95, 114)),
        new TileData("WulfrumWorkbench", "", new Color(71, 95, 114)),
        new TileData("AlgalPrismTorch", "", new Color(253, 221, 3)),
        new TileData("NavyPrismTorch", "", new Color(253, 221, 3)),
        new TileData("RefractivePrismTorch", "", new Color(253, 221, 3)),
        new TileData("SeaPrismBrick", "", new Color(47, 193, 236)),
    };
}