using System.Collections.Generic;
using CalamityRuTranslate.Common;
using Microsoft.Xna.Framework;

namespace CalamityRuTranslate.Catalogs
{
    public static class ThoriumCatalog
    {
        public static List<string> Buff = new List<string>
        {
            "AbyssalShell",
            "AbyssalShellWeak",
            "AirStrikeShieldBuff",
            "AquaAffinity",
            "Aquamancer",
            "AquaticAptitude",
            "ArtilleryBuff",
            "AssassinBuff",
            "BatRepellentBuff",
            "BeetleCarapace",
            "BerserkSoul",
            "BlightFever",
            "BloodRush",
            "BouncingFlameBuff",
            "Bubbled",
            "CactusJuice",
            "CalmWaters",
            "CannotChain",
            "ChaosState",
            "Charmed",
            "Chill",
            "ChokingDepths",
            "ChosenMight",
            "Christmas",
            "CleanBubble",
            "CobblerBuff",
            "Conflagrate",
            "Corporeal",
            "Corrosion",
            "CounterAttack",
            "CreativityDrop",
            "CursedHurtle",
            "DarknessWithin",
            "DashBuff",
            "DecayingFlesh",
            "DemonBloodExhaust",
            "DemonicDance",
            "DepthBreath",
            "DepthDamage",
            "DepthSpeed",
            "Destabilized",
            "DevilSoul",
            "DevilTired",
            "DRLimit",
            "EarwormBuff",
            "EmergencyAir",
            "EnemyFrozen",
            "EscapeRocketBuff",
            "ExplodePrevent",
            "ExplosionCoating",
            "FishRepellentBuff",
            "FleshFrenzy",
            "Frenzy",
            "FrostCoating",
            "FrostHeart",
            "Full",
            "Gateway",
            "GhastlySoul",
            "GhastlyTired",
            "GorganCoating",
            "Gouge",
            "Grace",
            "GraniteSurge",
            "GravityDamage",
            "Grimshadow",
            "Grimshadow2",
            "Grimshadow3",
            "Halloween",
            "Hallucination",
            "Hexed",
            "Honey",
            "HydrationBuff",
            "IlluminatedNPC",
            "IncandescentBurn",
            "Insanity",
            "InsectRepellentBuff",
            "InspirationReach",
            "Karma",
            "LegacyBurn",
            "LichActive",
            "LichNotActive",
            "LifeTransfusion",
            "LifeWaterRegen",
            "LightCurse",
            "LimbSnatch",
            "Liquefied",
            "MagickStaffDebuff",
            "Magma",
            "MajorEnchanted",
            "Melting",
            "MetamorphosisBad",
            "MetamorphosisGood",
            "MetamorphosisRealBad",
            "MidnightOil",
            "Mycelium",
            "MyceliumVeins",
            "Napalm",
            "Nightshade",
            "NinjaBuff",
            "OceansBuffer",
            "OceansBufferExhaust",
            "OmniVision",
            "Oozed",
            "Overcharge",
            "Paralyzed",
            "ParryStance",
            "Petrify",
            "PoisonHeart",
            "Revealed",
            "SandshroudPouchBuff",
            "SandshroudPouchDebuff",
            "Sanguine",
            "SchmelzeDebuff",
            "SeasonsGreeting",
            "Shackled",
            "SilverTongue",
            "Singed",
            "SkeletonRepellentBuff",
            "SlagfuryStandBuffTired",
            "SnakeBite",
            "SoulHarvest",
            "SporeCoating",
            "Spored",
            "Staggered",
            "Stunned",
            "Sunder",
            "TastyJelly",
            "TerrariumMix",
            "TerrariumRegen",
            "ToxicCoating",
            "TrueStrike",
            "TrueStrikeTired",
            "Tuned",
            "ViscountDebuff",
            "WarmongerBuff",
            "WidowsKiss",
            "WindBurst",
            "Wither",
            "ZombieRepellentBuff",
            "AudioOverload",
            "ConductorBuff",
            "GhostConductor",
            "MetronomeBuff",
            "MetronomeDebuff",
            "ShockAbsorbtion",
            "Soloist",
            "SoloistDebuff",
            "ZunpetBuff",
            "AegisAura",
            "AngelBuff",
            "Awake",
            "BloodBoost",
            "BloomBoost",
            "BoneArmor",
            "BulwarkBuff",
            "CelestialDamage",
            "CelestialHeal",
            "ConsumingShadow",
            "Cured",
            "DarkContagion",
            "DevilBuff",
            "DistortedTime",
            "DistortedTimeBoost",
            "DistortedTimeEnemy",
            "DragonHeart",
            "DreamBuff",
            "DreamCatcherBuff",
            "DreamCatcherDebuff",
            "EffigyRegen",
            "Gaurdian",
            "GaurdianBad",
            "GuardianDamage",
            "GuardianDefense",
            "GuardianRegen",
            "HealerDefenseAura",
            "HealerPotionBuff",
            "HealingLoss",
            "HealingMastery",
            "HolyAuraTired",
            "HolyBonus",
            "HolyDefense",
            "HolyGlare",
            "HolyShine",
            "KarmicConvergance",
            "LifeRecovery",
            "LifeSpiritBuff",
            "MistBulwark",
            "Mortality",
            "NullZoneBuff",
            "Overgrowth",
            "PheonixBuff",
            "QuickRecovery",
            "RadiantBoost",
            "Rebound",
            "RoseWind",
            "RoseWindBad",
            "Savior",
            "SerpentsBubble",
            "ShieldDroneBuff",
            "SmiteFire",
            "SoulEssence",
            "SpeedBurst",
            "SpiritualConnection",
            "Stabilized",
            "TangyHeal",
            "TheDream",
            "TwilightBoost",
            "VoidForm",
            "BallBuff",
            "BatBuffGood",
            "BathtubCartBuff",
            "BeetleTFBuff",
            "BroomMountBuff",
            "CarMount",
            "DragonMountBuff",
            "EnemyCrabBuff",
            "FrogBuff",
            "GoldfishTFBuff",
            "InfernalHoundBuff",
            "MaggotTFBuff",
            "MimicFormBuff",
            "OldDebt",
            "RagMountBuff",
            "RocketCartBuff",
            "SpectralFangBuff",
            "SquirrelBuff",
            "StarvedMountBuff",
            "SuperAnvilBuff",
            "WargMountBuff",
            "WhaleMountBuff",
            "WyvernMountBuff",
            "Enrage",
            "Protection",
            "QuickFire",
            "Regeneration",
            "AbyssalWhistleBuff",
            "AmnesiacBuff",
            "AncientRatBuff",
            "BabyBaliBuff",
            "BioFeederBuff",
            "BlisterBuff",
            "ChaoticMarbleBuff",
            "ClownfishPetBuff",
            "DrachmaBuff",
            "Experiment3Buff",
            "FerretBuff",
            "HolyGoatBuff",
            "JellyPet",
            "LilMogBuff",
            "LittlePhylacteryBuff",
            "LockBoxBuff",
            "MaidBuff",
            "OmegaBuff",
            "PickleBuff",
            "PinkSlimeBuff",
            "ShineDust",
            "SkunkBuff",
            "SnowyOwlBuff",
            "SubterraneanAnglerBuff",
            "SupportLanternBuff",
            "TortleScuteBuff",
            "WyvernPetBuff",
            "BannerConfusion",
            "BannerDamage",
            "BannerDefense",
            "BannerFalcon",
            "BannerGhost",
            "BannerLifeRegen",
            "BannerPower",
            "Beholding",
            "BlackCaneBuff",
            "BlobfishBuff",
            "BloodDrinker",
            "BloodMinionBuff",
            "BloodPact",
            "BloodyPaganStaffBuff",
            "ButterflyMinionBuff",
            "Command",
            "CorrodeSlimeBuff",
            "CorruptMinionBuff",
            "CrimsonMinionBuff",
            "DarkRisenBuff",
            "DinoBuff",
            "DragonMinionBuff",
            "EnchantedShieldBuff",
            "EnchantedTomeBuff",
            "EnigmaMinion",
            "HailBomberBuff",
            "HatchlingBuff",
            "IceFairyBuff",
            "LadyLightBuff",
            "MantisMinionBuff",
            "MeteorHeadStaff",
            "MeteorShieldBuff",
            "MoltenBannerBuff",
            "MushroomArmy",
            "NebulaMinionBuff",
            "OdinEyeBuff",
            "RosySlimeBuff",
            "SaplingBuff",
            "SeahorseBuff",
            "SlagMinionBuff",
            "SteamgunnerBuff",
            "TigerMinionBuff",
            "ValkyrieBladeBuff",
            "BloodLotus",
            "LastStandBuff",
            "ThrowingSpeed"
        };

        public static List<string> NPC = new List<string>
        {
            "AggroDummy",
            "AncientArcher",
            "AncientCharger",
            "AncientPhalanx",
            "ArmyAnt",
            "AstroBeetle",
            "BabyBaliNpc",
            "BabySpider",
            "BabySpiderWall",
            "BatOutaHell",
            "BigBone",
            "Biter",
            "Blacksmith",
            "BlackWidow",
            "BlackWidowWall",
            "Blister",
            "BlisterPod",
            "BloomMahoganyEnt",
            "BoneFlayer",
            "BoulderMimic",
            "BrownRecluse",
            "BrownRecluseBaby",
            "BrownRecluseBabyWall",
            "BrownRecluseWall",
            "BulletAnt",
            "ButterflyNPC",
            "ChilledCannon",
            "ChilledSpitter",
            "Clot",
            "Cobbler",
            "CoinBagCopper",
            "CoinBagGold",
            "CoinBagSilver",
            "Coldling",
            "ConfusedZombie",
            "Cook",
            "Coolmera",
            "CrimipedeBody",
            "CrimipedeHead",
            "CrimipedeTail",
            "DarksteelKnight",
            "DesertTraveler",
            "DissonanceSeer",
            "Diverman",
            "Druid",
            "DummyEnemy",
            "EarthenBat",
            "EarthenGolem",
            "EpiDermon",
            "FesteringSprinter",
            "FesteringWalker",
            "FireAnt",
            "Fish",
            "FlamekinCaster",
            "FlyingBioMass",
            "Freezer",
            "FrostFang",
            "FrostFangWall",
            "FrostWormBody",
            "FrostWormHead",
            "FrostWormTail",
            "FrozenFace",
            "FrozenGross",
            "GelatinousCube",
            "GelatinousSludge",
            "GildedBat",
            "GildedLycan",
            "GildedSlime",
            "GildedSlimeMini",
            "GlitteringGolem",
            "Gnome1",
            "Gnome2",
            "Gnome3",
            "Gnome4",
            "Gnomes",
            "GoblinDrummer",
            "GoblinSpiritGuide",
            "GoblinTrapper",
            "GoldDuck",
            "GoldDuck1",
            "GraniteEradicator",
            "GraniteFusedSlime",
            "GraniteSurger",
            "HealingDummy",
            "HellBringerMimic",
            "HoppingSpider",
            "HorrificCharger",
            "Illusionist",
            "IllusionistBolt",
            "IllusionistDecoy",
            "IllusionistMirror",
            "IllusionistSpawn",
            "InfernalHound",
            "Invader",
            "LifeCrystalMimic",
            "LihzardMimic",
            "LihzardPotMimic1",
            "LihzardPotMimic2",
            "LivingHemorage",
            "LostProbe",
            "Lycan",
            "MahoganyEnt",
            "MoltenMortar",
            "MossWasp",
            "MudMan",
            "MyceliumMimic",
            "NecroPot",
            "Nestling",
            "Phantom",
            "RagingMinotaur",
            "ScissorStalker",
            "SeaShantySinger",
            "ShadowflameRevenant",
            "Shambler",
            "SnowBall",
            "SnowEater",
            "SnowSinga",
            "SolarPriest",
            "SoulCorrupter",
            "SpaceSlime",
            "Spectrumite",
            "Spiritualist",
            "StrangeBulb",
            "Tarantula",
            "TarantulaWall",
            "TheInnocent",
            "TheStarved",
            "ThoriumNPC",
            "Tracker",
            "UFO",
            "UnderworldPot1",
            "UnderworldPot2",
            "VileFloater",
            "WeaponMaster",
            "WindElemental",
            "Viscount",
            "ViscountBaby",
            "EnemyBeholder",
            "FallenDeathBeholder",
            "FallenDeathBeholder2",
            "BlizzardBat",
            "BoreanHopper",
            "BoreanMyte1",
            "BoreanStrider",
            "BoreanStriderPopped",
            "FrostBurnt",
            "FrostBurntFlayer",
            "SnowElemental",
            "SnowyOwl",
            "Abomination",
            "BloodDrop",
            "GorgedEye",
            "GraveLimb",
            "Maggot",
            "NecroticImbuer",
            "PatchWerk",
            "SeveredLegs",
            "Shade",
            "Warg",
            "CorpseBloom",
            "CorpsePetal",
            "CorpseWeed",
            "BuriedSpawn",
            "BuriedVolley",
            "TheBuriedWarrior",
            "TheBuriedWarrior1",
            "TheBuriedWarrior2",
            "BlueHag",
            "CyanHag",
            "GreenHag",
            "RedHag",
            "AbyssalAngler",
            "AbyssalAngler2",
            "AbyssalSpawn",
            "Abyssion",
            "AbyssionCracked",
            "AbyssionReleased",
            "AquaticHallucination",
            "Barracuda",
            "Blobfish",
            "Blowfish",
            "CrownofThorns",
            "DepthMimic",
            "EelBody",
            "EelHead",
            "EelTail",
            "FeedingFrenzy",
            "FeedingFrenzy2",
            "GigaClam",
            "Globee",
            "Hammerhead",
            "Kraken",
            "ManofWar",
            "MorayBody",
            "MorayHead",
            "MorayTail",
            "Octopus",
            "PutridSerpent",
            "Sharptooth",
            "VampireSquid",
            "Whale",
            "EncroachingEnergy",
            "EnergyBarrier",
            "EnergyStormConduit",
            "GraniteEnergy",
            "GraniteEnergyStorm",
            "GraniteSpawn",
            "Lich",
            "LichHeadless",
            "ThousandSoulPhalactry",
            "AngerSpirit",
            "Aquaius",
            "AquaiusBubble",
            "DespairSpirit",
            "DreadSpirit",
            "LucidBubble",
            "Omnicide",
            "RealityBreaker",
            "SlagFury",
            "DistractJelly",
            "QueenJelly",
            "SpittingJelly",
            "ZealousJelly",
            "BioCore",
            "CryoCore",
            "PyroCore",
            "ThePrimeScouter",
            "Hatchling",
            "TheGrandThunderBirdv2"
        };

        public static List<string> Prefix = new List<string>
        {
            "Loud",
            "Supersonic",
            "Vibrant",
            "Euphonic",
            "Melodic",
            "Inspiring",
            "Muted",
            "OffKey",
            "Rambling",
            "Refined",
            "Buzzing",
            "Fabled"
        };

        public static List<ModTileTranslation> Tile = new List<ModTileTranslation>
        {
            new ModTileTranslation("Altar", "", new Color(155, 125, 100)),
            new ModTileTranslation("Aquaite", "", new Color(0, 130, 255)),
            new ModTileTranslation("AquaticDepthsBanner", "", new Color(13, 88, 130)),
            new ModTileTranslation("AquaticDepthsBiomeChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("AquaticDepthsBiomeChest", "AquaticDepthsBiomeChest_Locked", new Color(174, 129, 92), "AquaticDepthsBiomeChest_Locked"),
            new ModTileTranslation("ArcaneArmorFabricator", "", new Color(150, 150, 150)),
            new ModTileTranslation("BloodAltar", "", new Color(100, 100, 100)),
            new ModTileTranslation("BloodSplatterTile", "", new Color(175, 135, 125)),
            new ModTileTranslation("BloodstainedChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("ChessBlock", "", new Color(80, 80, 80)),
            new ModTileTranslation("CookTiles1", "", new Color(200, 170, 125)),
            new ModTileTranslation("CookTiles2", "", new Color(200, 170, 125)),
            new ModTileTranslation("CookTiles3", "", new Color(200, 170, 125)),
            new ModTileTranslation("CursedChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("DepthChestTile", "", new Color(58, 177, 236)),
            new ModTileTranslation("DepthsAmber", "", new Color(180, 130, 75)),
            new ModTileTranslation("DepthsAmethyst", "", new Color(140, 58, 166)),
            new ModTileTranslation("DepthsDiamond", "", new Color(125, 191, 197)),
            new ModTileTranslation("DepthsEmerald", "", new Color(56, 150, 97)),
            new ModTileTranslation("DepthsOnyx", "", new Color(45, 30, 45)),
            new ModTileTranslation("DepthsOpal", "", new Color(255, 102, 255)),
            new ModTileTranslation("DepthsRuby", "", new Color(196, 96, 114)),
            new ModTileTranslation("DepthsSapphire", "", new Color(110, 140, 182)),
            new ModTileTranslation("DepthsTopaz", "", new Color(160, 118, 58)),
            new ModTileTranslation("DesertBiomeChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("DesertBiomeChest", "DesertBiomeChest_Locked", new Color(174, 129, 92), "DesertBiomeChest_Locked"),
            new ModTileTranslation("EvergreenChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("FurnitureBathtub", "", new Color(144, 147, 144)),
            new ModTileTranslation("FurnitureBed", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureBookcase", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureCandelabra", "", new Color(253, 221, 3)),
            new ModTileTranslation("FurnitureCandle", "", new Color(253, 221, 3)),
            new ModTileTranslation("FurnitureChair", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureChandelier", "", new Color(235, 166, 135)),
            new ModTileTranslation("FurnitureClock", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureCup", "", new Color(144, 147, 144)),
            new ModTileTranslation("FurnitureDoorClosed", "", new Color(119, 105, 79)),
            new ModTileTranslation("FurnitureDoorOpen", "", new Color(119, 105, 79)),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Thorium", new Color(191, 142, 111), "FurnitureDresser_Thorium"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Yew", new Color(191, 142, 111), "FurnitureDresser_Yew"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Marine", new Color(191, 142, 111), "FurnitureDresser_Marine"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Lodestone", new Color(191, 142, 111), "FurnitureDresser_Lodestone"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Permafrost", new Color(191, 142, 111), "FurnitureDresser_Permafrost"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Plate", new Color(191, 142, 111), "FurnitureDresser_Plate"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Scarlet", new Color(191, 142, 111), "FurnitureDresser_Scarlet"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Ornate", new Color(191, 142, 111), "FurnitureDresser_Ornate"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Valadium", new Color(191, 142, 111), "FurnitureDresser_Valadium"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Cursed", new Color(191, 142, 111), "FurnitureDresser_Cursed"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Shady", new Color(191, 142, 111), "FurnitureDresser_Shady"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Naga", new Color(191, 142, 111), "FurnitureDresser_Naga"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Bloodstained", new Color(191, 142, 111), "FurnitureDresser_Bloodstained"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Evergreen", new Color(191, 142, 111), "FurnitureDresser_Evergreen"),
            new ModTileTranslation("FurnitureDresser", "FurnitureDresser_Gingerbread", new Color(191, 142, 111), "FurnitureDresser_Gingerbread"),
            new ModTileTranslation("FurnitureLamp", "", new Color(253, 221, 3)),
            new ModTileTranslation("FurnitureLantern", "", new Color(251, 235, 127)),
            new ModTileTranslation("FurnitureMusicBox", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurniturePiano", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureSink", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureSofa", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureTable", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureToilet", "", new Color(191, 142, 111)),
            new ModTileTranslation("FurnitureWorkbench", "", new Color(191, 142, 111)),
            new ModTileTranslation("GingerbreadBlock", "", new Color(240, 220, 200)),
            new ModTileTranslation("GingerbreadChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("GrayDPainting", "", new Color(90, 50, 30)),
            new ModTileTranslation("GrimPedestal", "", new Color(119, 101, 125)),
            new ModTileTranslation("GrimPedestal", "GrimPedestal_Crimson", new Color(214, 127, 133), "GrimPedestal_Crimson"),
            new ModTileTranslation("IllumiteChunk", "", new Color(255, 51, 153)),
            new ModTileTranslation("JungleFlower1", "", new Color(255, 75, 150)),
            new ModTileTranslation("JungleFlower2", "", new Color(255, 75, 150)),
            new ModTileTranslation("JungleFlower3", "", new Color(255, 75, 150)),
            new ModTileTranslation("JungleFlower4", "", new Color(255, 75, 150)),
            new ModTileTranslation("LargeCoral", "", new Color(245, 133, 191)),
            new ModTileTranslation("LifeCrystal", "", new Color(174, 24, 69)),
            new ModTileTranslation("LifeQuartz", "", new Color(255, 56, 115)),
            new ModTileTranslation("LivingLeafBush", "", new Color(140, 205, 115)),
            new ModTileTranslation("LodeStone", "", new Color(150, 95, 75)),
            new ModTileTranslation("LodestoneChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("MagmaOre", "", new Color(255, 125, 0)),
            new ModTileTranslation("MarineChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("MediciteBrick", "", new Color(140, 90, 90)),
            new ModTileTranslation("MistletoeTile", "", new Color(27, 109, 69)),
            new ModTileTranslation("MonsterBannerCave", "", new Color(13, 88, 130)),
            new ModTileTranslation("MonsterBannerJungle", "", new Color(13, 88, 130)),
            new ModTileTranslation("MonsterBannerSky", "", new Color(13, 88, 130)),
            new ModTileTranslation("MonsterBannerSpider", "", new Color(13, 88, 130)),
            new ModTileTranslation("NagaChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("OceanCrystal", "", new Color(175, 235, 255)),
            new ModTileTranslation("Onyx", "", new Color(45, 30, 45)),
            new ModTileTranslation("OnyxTorch", "", new Color(200, 200, 200)),
            new ModTileTranslation("Opal", "", new Color(255, 102, 255)),
            new ModTileTranslation("OpalTorch", "", new Color(200, 200, 200)),
            new ModTileTranslation("OrnateChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("PaintTileHuge", "", new Color(90, 50, 30)),
            new ModTileTranslation("PaintTileLarge", "", new Color(90, 50, 30)),
            new ModTileTranslation("PaintTileMedium", "", new Color(90, 50, 30)),
            new ModTileTranslation("PaintTileSmall", "", new Color(90, 50, 30)),
            new ModTileTranslation("PaintTileTall", "", new Color(90, 50, 30)),
            new ModTileTranslation("PearlStone", "", new Color(153, 255, 204)),
            new ModTileTranslation("PermafrostChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("PlacedGem", "Opal", new Color(255, 147, 255), "PlacedGem_Opal"),
            new ModTileTranslation("PlacedGem", "Onyx", new Color(45, 20, 45), "PlacedGem_Onyx"),
            new ModTileTranslation("PlacedGem", "Pearl", new Color(153, 255, 204), "PlacedGem_Pearl"),
            new ModTileTranslation("PlateChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("RecipeCatalog", "", new Color(51, 255, 153)),
            new ModTileTranslation("SakuraSapling", "", new Color(200, 170, 150)),
            new ModTileTranslation("ScarletChest", "", new Color(180, 0, 0)),
            new ModTileTranslation("ShadyChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("SmoothCoal", "", new Color(40, 40, 40)),
            new ModTileTranslation("SoulForge", "", new Color(0, 102, 255)),
            new ModTileTranslation("SpookySapling", "", new Color(200, 170, 150)),
            new ModTileTranslation("StrangeCrate", "", new Color(160, 120, 92)),
            new ModTileTranslation("StrangePlatingTile", "", new Color(180, 180, 180)),
            new ModTileTranslation("SugarCookieBlock", "", new Color(240, 220, 200)),
            new ModTileTranslation("SynthGold", "", new Color(204, 204, 0)),
            new ModTileTranslation("SynthPlatinum", "", new Color(210, 210, 210)),
            new ModTileTranslation("ThoriumAnvil", "", new Color(80, 200, 200)),
            new ModTileTranslation("ThoriumChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("ThoriumOre", "", new Color(50, 220, 220)),
            new ModTileTranslation("TrackerBoardTile", "", new Color(90, 50, 30)),
            new ModTileTranslation("TrappedChests", "AquaticDepthsBiomeChest_Trapped", new Color(174, 129, 92), "AquaticDepthsBiomeChest_Trapped"),
            new ModTileTranslation("TrappedChests", "DepthChestTile_Trapped", new Color(58, 177, 236), "DepthChestTile_Trapped"),
            new ModTileTranslation("TrappedChests", "DesertBiomeChest_Trapped", new Color(174, 129, 92), "DesertBiomeChest_Trapped"),
            new ModTileTranslation("TrappedChests", "MarineChest_Trapped", new Color(174, 129, 92), "MarineChest_Trapped"),
            new ModTileTranslation("TrappedChests", "ScarletChest_Trapped", new Color(180, 0, 0), "ScarletChest_Trapped"),
            new ModTileTranslation("TrappedChests", "ThoriumChest_Trapped", new Color(174, 129, 92), "ThoriumChest_Trapped"),
            new ModTileTranslation("TrappedChests", "UnderworldChest_Trapped", new Color(174, 129, 92), "UnderworldChest_Trapped"),
            new ModTileTranslation("TrappedChests", "YewChest_Trapped", new Color(174, 129, 92), "YewChest_Trapped"),
            new ModTileTranslation("TrappedChests", "PermafrostChest_Trapped", new Color(174, 129, 92), "PermafrostChest_Trapped"),
            new ModTileTranslation("TrappedChests", "PlateChest_Trapped", new Color(174, 129, 92), "PlateChest_Trapped"),
            new ModTileTranslation("TrappedChests", "LodestoneChest_Trapped", new Color(174, 129, 92), "LodestoneChest_Trapped"),
            new ModTileTranslation("TrappedChests", "OrnateChest_Trapped", new Color(174, 129, 92), "OrnateChest_Trapped"),
            new ModTileTranslation("TrappedChests", "ValadiumChest_Trapped", new Color(174, 129, 92), "ValadiumChest_Trapped"),
            new ModTileTranslation("TrappedChests", "CursedChest_Trapped", new Color(174, 129, 92), "CursedChest_Trapped"),
            new ModTileTranslation("TrappedChests", "ShadyChest_Trapped", new Color(174, 129, 92), "ShadyChest_Trapped"),
            new ModTileTranslation("TrappedChests", "NagaChest_Trapped", new Color(174, 129, 92), "NagaChest_Trapped"),
            new ModTileTranslation("TrappedChests", "BloodstainedChest_Trapped", new Color(174, 129, 92), "BloodstainedChest_Trapped"),
            new ModTileTranslation("Trophies", "", new Color(120, 85, 60)),
            new ModTileTranslation("UnderworldChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("UnderworldChest", "UnderworldChest_Locked", new Color(174, 129, 92), "UnderworldChest_Locked"),
            new ModTileTranslation("ValadiumChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("ValadiumChunk", "", new Color(153, 51, 255)),
            new ModTileTranslation("YewChest", "", new Color(174, 129, 92)),
            new ModTileTranslation("YewSapling", "", new Color(200, 170, 150))
        };

        public static List<string> Dresser = new List<string>
        {
            "FurnitureDresser",
        };

        public static List<string> Chest = new List<string>
        {
            "AquaticDepthsBiomeChest",
            "BloodstainedChest",
            "CursedChest",
            "DepthChestTile",
            "DesertBiomeChest",
            "EvergreenChest",
            "GingerbreadChest",
            "LodestoneChest",
            "MarineChest",
            "NagaChest",
            "OrnateChest",
            "PermafrostChest",
            "PlateChest",
            "ScarletChest",
            "ShadyChest",
            "ThoriumChest",
            "UnderworldChest",
            "ValadiumChest",
            "YewChest",
        };

        public static List<string> KeyLocalization = new List<string>
        {
            "LodestoneWarning1",
            "LodestoneWarning2",
            "ValadiumWarning1",
            "ValadiumWarning2",
            "GraniteMarbleWarning",
            "IllumiteWarning",
            "HMDeapthsWarning",
            "AbyssionWarning",
            "JellyWarning",
            "ExpertAbyssion1",
            "ExpertAbyssion2",
            "AbyssionDefeat",
            "SpiderDefeat",
            "SpiderWarning",
            "SpiderAppear",
            "PatchDefeat",
            "BloomDefeat",
            "IllusionistDefeat",
            "BuriedAppear",
            "GraniteAppear",
            "DiverFree",
            "RagStart",
            "RagVictory",
            "outdatedBossChecklist",
        };
    }
}