using Terraria.ModLoader;
using Terraria.Localization;

namespace CalamityRuTranslate.ModOfRedemption.NPCs
{
    internal class RedemptionNPCs
    {
        public static void Setup()
        {
            NPCs();
        }

        private static void NPCs()
        {
            Mod redemption = ModLoader.GetMod("Redemption");
            
            redemption.GetNPC("AAAA").DisplayName.AddTranslation(GameCulture.Russian, "Ремнант");
            redemption.GetNPC("AJollyMadman").DisplayName.AddTranslation(GameCulture.Russian, "Веселый безумец");
            redemption.GetNPC("Android").DisplayName.AddTranslation(GameCulture.Russian, "Андроид");
            redemption.GetNPC("Apidroid").DisplayName.AddTranslation(GameCulture.Russian, "Апидроид");
            redemption.GetNPC("Blobble").DisplayName.AddTranslation(GameCulture.Russian, "Слиззо");
            redemption.GetNPC("BloodWormBody").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый червь");
            redemption.GetNPC("BloodWormHead").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый червь");
            redemption.GetNPC("BloodWormTail").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый червь");
            redemption.GetNPC("BoneLeviathanBody").DisplayName.AddTranslation(GameCulture.Russian, "Костяной левиафан");
            redemption.GetNPC("BoneLeviathanHead").DisplayName.AddTranslation(GameCulture.Russian, "Костяной левиафан");
            redemption.GetNPC("BoneLeviathanTail").DisplayName.AddTranslation(GameCulture.Russian, "Костяной левиафан");
            redemption.GetNPC("BoneSpider").DisplayName.AddTranslation(GameCulture.Russian, "Костяной паук");
            redemption.GetNPC("Chicken").DisplayName.AddTranslation(GameCulture.Russian, "Курица");
            redemption.GetNPC("ChickenCultist").DisplayName.AddTranslation(GameCulture.Russian, "Куримен-культист");
            redemption.GetNPC("ChickenGold").DisplayName.AddTranslation(GameCulture.Russian, "Золотая курица");
            redemption.GetNPC("CoastScarab").DisplayName.AddTranslation(GameCulture.Russian, "Прибрежный скарабей");
            redemption.GetNPC("CorpseWalkerPriest").DisplayName.AddTranslation(GameCulture.Russian, "Ходячий труп жреца");
            redemption.GetNPC("CorruptedBlade").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный клинок");
            redemption.GetNPC("CorruptedProbe").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный дрон");
            redemption.GetNPC("CorruptedTBot").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный Т-Бот");
            redemption.GetNPC("CorruptedWormBody").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный червь");
            redemption.GetNPC("CorruptedWormHead").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный червь");
            redemption.GetNPC("CorruptedWormTail").DisplayName.AddTranslation(GameCulture.Russian, "Искаженный червь");
            redemption.GetNPC("CrusherBody").DisplayName.AddTranslation(GameCulture.Russian, "Крушитель");
            redemption.GetNPC("CrusherHead").DisplayName.AddTranslation(GameCulture.Russian, "Крушитель");
            redemption.GetNPC("CrusherTail").DisplayName.AddTranslation(GameCulture.Russian, "Крушитель");
            redemption.GetNPC("DarkSoul").DisplayName.AddTranslation(GameCulture.Russian, "Темная душа");
            redemption.GetNPC("DarkSoul2").DisplayName.AddTranslation(GameCulture.Russian, "Темная душа");
            redemption.GetNPC("DarkSoul3").DisplayName.AddTranslation(GameCulture.Russian, "Темная душа");
            redemption.GetNPC("DarkSoul4").DisplayName.AddTranslation(GameCulture.Russian, "Угасающая душа");
            redemption.GetNPC("DarkSoul5").DisplayName.AddTranslation(GameCulture.Russian, "Угасающая душа");
            redemption.GetNPC("DeathGardener").DisplayName.AddTranslation(GameCulture.Russian, "Садовник смерти");
            redemption.GetNPC("DirtPile").DisplayName.AddTranslation(GameCulture.Russian, "Подозрительная кучка грязи");
            redemption.GetNPC("EarthwormBody").DisplayName.AddTranslation(GameCulture.Russian, "Земляной червь");
            redemption.GetNPC("EarthwormHead").DisplayName.AddTranslation(GameCulture.Russian, "Земляной червь");
            redemption.GetNPC("EarthwormTail").DisplayName.AddTranslation(GameCulture.Russian, "Земляной червь");
            redemption.GetNPC("Fallen").DisplayName.AddTranslation(GameCulture.Russian, "Падший");
            redemption.GetNPC("FatPirate").DisplayName.AddTranslation(GameCulture.Russian, "Кок");
            redemption.GetNPC("Fly").DisplayName.AddTranslation(GameCulture.Russian, "Муха");
            redemption.GetNPC("ForestGolem").DisplayName.AddTranslation(GameCulture.Russian, "Лесной голем");
            redemption.GetNPC("ForestGolemBlooming").DisplayName.AddTranslation(GameCulture.Russian, "Лесной голем");
            redemption.GetNPC("ForestGolemWounded").DisplayName.AddTranslation(GameCulture.Russian, "Лесной голем");
            redemption.GetNPC("ForestNymph").DisplayName.AddTranslation(GameCulture.Russian, "Лесная нимфа");
            redemption.GetNPC("ForestSpider").DisplayName.AddTranslation(GameCulture.Russian, "Лесной паук");
            redemption.GetNPC("GrandLarva").DisplayName.AddTranslation(GameCulture.Russian, "Великая личинка");
            redemption.GetNPC("GraniteCluster").DisplayName.AddTranslation(GameCulture.Russian, "Гранитное скопление");
            redemption.GetNPC("HazmatSkeleton").DisplayName.AddTranslation(GameCulture.Russian, "Скелет в костюме химзащиты");
            redemption.GetNPC("HazmatZombie").DisplayName.AddTranslation(GameCulture.Russian, "Зомби в костюме химзащиты");
            redemption.GetNPC("InfectedCaveBat").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированная пещерная летучая мышь");
            redemption.GetNPC("InfectedDemonEye").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный демонический глаз");
            redemption.GetNPC("InfectedDiggerBody").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный копатель");
            redemption.GetNPC("InfectedDiggerHead").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный копатель");
            redemption.GetNPC("InfectedDiggerTail").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный копатель");
            redemption.GetNPC("InfectedGiantBat").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированная гигантская летучая мышь");
            redemption.GetNPC("InfectedGiantWormBody").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный гигантский червь");
            redemption.GetNPC("InfectedGiantWormHead").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный гигантский червь");
            redemption.GetNPC("InfectedGiantWormTail").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный гигантский червь");
            redemption.GetNPC("InfectedZombie").DisplayName.AddTranslation(GameCulture.Russian, "Зараженный зомби");
            redemption.GetNPC("LickyLickyCactus").DisplayName.AddTranslation(GameCulture.Russian, "Язык Дьявола");
            redemption.GetNPC("LivingBlackGloop").DisplayName.AddTranslation(GameCulture.Russian, "Живая черная дрянь");
            redemption.GetNPC("LivingBloom").DisplayName.AddTranslation(GameCulture.Russian, "Живоцвецие");
            redemption.GetNPC("LostSoul1").DisplayName.AddTranslation(GameCulture.Russian, "Заблудшая душа");
            redemption.GetNPC("LostSoul2").DisplayName.AddTranslation(GameCulture.Russian, "Заблудшая душа");
            redemption.GetNPC("LostSoul3").DisplayName.AddTranslation(GameCulture.Russian, "Заблудшая душа");
            redemption.GetNPC("MarbleChessHorse").DisplayName.AddTranslation(GameCulture.Russian, "Мраморный шахватный конь");
            redemption.GetNPC("MartianScamArtist").DisplayName.AddTranslation(GameCulture.Russian, "Марсианский аферист");
            redemption.GetNPC("MoltenGolem").DisplayName.AddTranslation(GameCulture.Russian, "Литой голем");
            redemption.GetNPC("MoonflareBat").DisplayName.AddTranslation(GameCulture.Russian, "Летучая мышь лунной вспышки");
            redemption.GetNPC("Newb").DisplayName.AddTranslation(GameCulture.Russian, "Ньюб");
            redemption.GetNPC("OmegaAndroid").DisplayName.AddTranslation(GameCulture.Russian, "Омега-андроид");
            redemption.GetNPC("OmegaMK2Droid1").DisplayName.AddTranslation(GameCulture.Russian, "Омега Мк-2 дроид");
            redemption.GetNPC("OmegaMK2Droid2").DisplayName.AddTranslation(GameCulture.Russian, "Омега Мк-2 дроид");
            redemption.GetNPC("OmegaPrototype").DisplayName.AddTranslation(GameCulture.Russian, "Прототип Омега");
            redemption.GetNPC("OmegaSpacePaladin").DisplayName.AddTranslation(GameCulture.Russian, "Космический омега-паладин");
            redemption.GetNPC("PrototypeSilver").DisplayName.AddTranslation(GameCulture.Russian, "Прототип Сильвер");
            redemption.GetNPC("RadiumDiggerBody").DisplayName.AddTranslation(GameCulture.Russian, "Радиевый копатель");
            redemption.GetNPC("RadiumDiggerHead").DisplayName.AddTranslation(GameCulture.Russian, "Радиевый копатель");
            redemption.GetNPC("RadiumDiggerTail").DisplayName.AddTranslation(GameCulture.Russian, "Радиевый копатель");
            redemption.GetNPC("RaggedZombie").DisplayName.AddTranslation(GameCulture.Russian, "Яростный зомби");
            redemption.GetNPC("RainbowChicken").DisplayName.AddTranslation(GameCulture.Russian, "Радужная курица");
            redemption.GetNPC("RogueTBot").DisplayName.AddTranslation(GameCulture.Russian, "Изгнанный Т-Бот");
            redemption.GetNPC("SandskinSpider").DisplayName.AddTranslation(GameCulture.Russian, "Песочный паук");
            redemption.GetNPC("ShieldedZombie").DisplayName.AddTranslation(GameCulture.Russian, "Зомби");
            redemption.GetNPC("SkeleDruid").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-друид");
            redemption.GetNPC("Skelemies").DisplayName.AddTranslation(GameCulture.Russian, "Шкелет");
            redemption.GetNPC("Skelemies2").DisplayName.AddTranslation(GameCulture.Russian, "Старенький скелет");
            redemption.GetNPC("SkeletonAssassin").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-убийца");
            redemption.GetNPC("SkeletonDueller").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-дуэлянт");
            redemption.GetNPC("SkeletonMinion").DisplayName.AddTranslation(GameCulture.Russian, "Скелет");
            redemption.GetNPC("SkeletonNoble").DisplayName.AddTranslation(GameCulture.Russian, "Благородный скелет");
            redemption.GetNPC("SkeletonNobleArmoured").DisplayName.AddTranslation(GameCulture.Russian, "Благородный скелет");
            redemption.GetNPC("SkeletonNobleArmoured2").DisplayName.AddTranslation(GameCulture.Russian, "Благородный скелет");
            redemption.GetNPC("SkeletonNobleArmoured3").DisplayName.AddTranslation(GameCulture.Russian, "Благородный скелет");
            redemption.GetNPC("SkeletonWanderer").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-бродяга");
            redemption.GetNPC("SkeletonWarden").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-надзиратель");
            redemption.GetNPC("SkullDigger").DisplayName.AddTranslation(GameCulture.Russian, "Черепокопатель");
            redemption.GetNPC("SludgyBoi").DisplayName.AddTranslation(GameCulture.Russian, "Облученный ил");
            redemption.GetNPC("SnowyBoi").DisplayName.AddTranslation(GameCulture.Russian, "Хладнокровный заклинатель");
            redemption.GetNPC("SpaceKeeper").DisplayName.AddTranslation(GameCulture.Russian, "Космический хранитель");
            redemption.GetNPC("SpacePaladin").DisplayName.AddTranslation(GameCulture.Russian, "Космический паладин");
            redemption.GetNPC("StoneGolemAncient1").DisplayName.AddTranslation(GameCulture.Russian, "Древний каменный голем");
            redemption.GetNPC("StoneGolemAncient2").DisplayName.AddTranslation(GameCulture.Russian, "Древний каменный голем");
            redemption.GetNPC("SunkenCaptain").DisplayName.AddTranslation(GameCulture.Russian, "Затонувший капитан");
            redemption.GetNPC("SunkenDeckhand").DisplayName.AddTranslation(GameCulture.Russian, "Затонувший пират");
            redemption.GetNPC("SunkenParrot").DisplayName.AddTranslation(GameCulture.Russian, "Затонувший попугай");
            redemption.GetNPC("TBot").DisplayName.AddTranslation(GameCulture.Russian, "Дружелюбный Т-Бот");
            redemption.GetNPC("TBotUnconscious").DisplayName.AddTranslation(GameCulture.Russian, "Адам");
            redemption.GetNPC("TheSoulless").DisplayName.AddTranslation(GameCulture.Russian, "Бездушный");
            redemption.GetNPC("TreeBug").DisplayName.AddTranslation(GameCulture.Russian, "Древесный жук");
            redemption.GetNPC("UndeadExecutioner1").DisplayName.AddTranslation(GameCulture.Russian, "Оживший палач");
            redemption.GetNPC("UndeadExecutioner2").DisplayName.AddTranslation(GameCulture.Russian, "Оживший палач");
            redemption.GetNPC("UndeadExecutioner3").DisplayName.AddTranslation(GameCulture.Russian, "Оживший палач");
            redemption.GetNPC("UndeadViolinist").DisplayName.AddTranslation(GameCulture.Russian, "Оживший скрипач");
            redemption.GetNPC("UnstablePortal").DisplayName.AddTranslation(GameCulture.Russian, "Нестабильный портал");
            redemption.GetNPC("WanderingSoul").DisplayName.AddTranslation(GameCulture.Russian, "Скитающаяся душа");
            redemption.GetNPC("XenoChomper").DisplayName.AddTranslation(GameCulture.Russian, "Ксено-зубастик");
            redemption.GetNPC("XenomiteGargantuan").DisplayName.AddTranslation(GameCulture.Russian, "Ксеномитный колосс");
            redemption.GetNPC("XenomiteGolem").DisplayName.AddTranslation(GameCulture.Russian, "Ксеномитный голем");
            redemption.GetNPC("XenonRoller").DisplayName.AddTranslation(GameCulture.Russian, "Ксено-кататель");
            redemption.GetNPC("CleaverClone1").DisplayName.AddTranslation(GameCulture.Russian, "Призрачный секач");
            redemption.GetNPC("KingChicken").DisplayName.AddTranslation(GameCulture.Russian, "Могучий куриный король");
            redemption.GetNPC("VlitchCleaver").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящий секач");
            redemption.GetNPC("VlitchCore1").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящее ядро");
            redemption.GetNPC("VlitchCore2").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящее ядро");
            redemption.GetNPC("VlitchCore3").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящее ядро");
            redemption.GetNPC("VlitchWormBody").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящая гиганожка");
            redemption.GetNPC("VlitchWormHead").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящая гиганожка");
            redemption.GetNPC("VlitchWormTail").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящая гиганожка");
            redemption.GetNPC("EaglecrestGolem").DisplayName.AddTranslation(GameCulture.Russian, "Голем Иглекреста");
            redemption.GetNPC("EaglecrestGolemPZ").DisplayName.AddTranslation(GameCulture.Russian, "Голем Иглекреста");
            redemption.GetNPC("EaglecrestGolemSleep").DisplayName.AddTranslation(GameCulture.Russian, "Спящие камни");
            redemption.GetNPC("EaglecrestRockPile").DisplayName.AddTranslation(GameCulture.Russian, "Кучка камней Иглкреста");
            redemption.GetNPC("EaglecrestRockPilePZ").DisplayName.AddTranslation(GameCulture.Russian, "Кучка камней Иглкреста");
            redemption.GetNPC("Ukko").DisplayName.AddTranslation(GameCulture.Russian, "Укко");
            redemption.GetNPC("InfectedEye").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный глаз");
            redemption.GetNPC("XenomiteEye").DisplayName.AddTranslation(GameCulture.Russian, "Ксеномитное око");
            redemption.GetNPC("KSEntrance").DisplayName.AddTranslation(GameCulture.Russian, "Убийца королей III");
            redemption.GetNPC("KSNope").DisplayName.AddTranslation(GameCulture.Russian, "Убийца королей III");
            redemption.GetNPC("KSEntranceClone").DisplayName.AddTranslation(GameCulture.Russian, "Убийца Королей III...?");
            redemption.GetNPC("BigNebuleus").DisplayName.AddTranslation(GameCulture.Russian, "Небулеус, Ангел Космоса");
            redemption.GetNPC("NebuleusClone").DisplayName.AddTranslation(GameCulture.Russian, "Иллюзорная Небулеус");
            redemption.GetNPC("BigNebuleusClone").DisplayName.AddTranslation(GameCulture.Russian, "Иллюзорная Небулеус");
            redemption.GetNPC("NebEye1").DisplayName.AddTranslation(GameCulture.Russian, "Глаз космоса");
            redemption.GetNPC("Nebuleus").DisplayName.AddTranslation(GameCulture.Russian, "Небулеус, ангел Космоса");
            redemption.GetNPC("StarWyvernHead").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernNeck").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernCollar").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernBody").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernLeg").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernTail1").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernTail2").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("StarWyvernTail3").DisplayName.AddTranslation(GameCulture.Russian, "Гигантский звездный змей");
            redemption.GetNPC("OO").DisplayName.AddTranslation(GameCulture.Russian, "Омега-уничтожитель");
            redemption.GetNPC("OOShield").DisplayName.AddTranslation(GameCulture.Russian, "Орбитальный барьер");
            redemption.GetNPC("SeedGrowth").DisplayName.AddTranslation(GameCulture.Russian, "Порождение улья");
            redemption.GetNPC("SoI").DisplayName.AddTranslation(GameCulture.Russian, "Семя заражения");
            redemption.GetNPC("StrangePortal").DisplayName.AddTranslation(GameCulture.Russian, "Странный портал");
            redemption.GetNPC("TheKeeper").DisplayName.AddTranslation(GameCulture.Russian, "Хранительница");
            redemption.GetNPC("Akka").DisplayName.AddTranslation(GameCulture.Russian, "Акка");
            redemption.GetNPC("ManaBarrierPro").DisplayName.AddTranslation(GameCulture.Russian, "Мана-барьер");
            redemption.GetNPC("ManaBarrierPro2").DisplayName.AddTranslation(GameCulture.Russian, "Мана-барьер");
            redemption.GetNPC("Thorn").DisplayName.AddTranslation(GameCulture.Russian, "Терн, Погибель леса");
            redemption.GetNPC("ThornPZ").DisplayName.AddTranslation(GameCulture.Russian, "Терн, Погибель леса");
            redemption.GetNPC("BomberChicken").DisplayName.AddTranslation(GameCulture.Russian, "Курица-бомбардир");
            redemption.GetNPC("BoneChicken").DisplayName.AddTranslation(GameCulture.Russian, "Костяная курица");
            redemption.GetNPC("ChickenBallista").DisplayName.AddTranslation(GameCulture.Russian, "Куриная баллиста");
            redemption.GetNPC("ChickenCavalry").DisplayName.AddTranslation(GameCulture.Russian, "Куриная кавалерия");
            redemption.GetNPC("ChickenMan").DisplayName.AddTranslation(GameCulture.Russian, "Курамен");
            redemption.GetNPC("ChickenSwarmer").DisplayName.AddTranslation(GameCulture.Russian, "Куриный роевик");
            redemption.GetNPC("ChickmanArchmage").DisplayName.AddTranslation(GameCulture.Russian, "Куриный архимаг");
            redemption.GetNPC("ChickmanChickromancer").DisplayName.AddTranslation(GameCulture.Russian, "Куримен-куромант");
            redemption.GetNPC("GreatChickenWarrior").DisplayName.AddTranslation(GameCulture.Russian, "Великий куримен");
            redemption.GetNPC("RoosterKing").DisplayName.AddTranslation(GameCulture.Russian, "Король Петушок");
            redemption.GetNPC("ShieldedChickenMan").DisplayName.AddTranslation(GameCulture.Russian, "Куримен-пехотинец");
            redemption.GetNPC("TrojanChicken").DisplayName.AddTranslation(GameCulture.Russian, "Троянская курица");
            redemption.GetNPC("Blisterling").DisplayName.AddTranslation(GameCulture.Russian, "Нарывец");
            redemption.GetNPC("Blisterling2").DisplayName.AddTranslation(GameCulture.Russian, "Нарывец");
            redemption.GetNPC("HiveGrowth").DisplayName.AddTranslation(GameCulture.Russian, "Порождение улья");
            redemption.GetNPC("HiveGrowth2").DisplayName.AddTranslation(GameCulture.Russian, "Порождение улья");
            redemption.GetNPC("InfectionHive").DisplayName.AddTranslation(GameCulture.Russian, "Инфекционный улей");
            redemption.GetNPC("SludgyBlob").DisplayName.AddTranslation(GameCulture.Russian, "Иловый слизнячок");
            redemption.GetNPC("SludgyBoi2").DisplayName.AddTranslation(GameCulture.Russian, "Облученный ил");
            redemption.GetNPC("Stage2Scientist").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный ученый");
            redemption.GetNPC("WalterInfected").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный ученый");
            redemption.GetNPC("XenoChomper2").DisplayName.AddTranslation(GameCulture.Russian, "Ксено-зубастик");
            redemption.GetNPC("Blisterface2").DisplayName.AddTranslation(GameCulture.Russian, "Нарыволицый");
            redemption.GetNPC("CraneTrolley").DisplayName.AddTranslation(GameCulture.Russian, "Кран");
            redemption.GetNPC("IrradiatedBehemoth2").DisplayName.AddTranslation(GameCulture.Russian, "Облученный бегемот");
            redemption.GetNPC("IrradiatedBehemothBody").DisplayName.AddTranslation(GameCulture.Russian, "Облученный бегемот");
            redemption.GetNPC("JanitorBot").DisplayName.AddTranslation(GameCulture.Russian, "Уборщик");
            redemption.GetNPC("JanitorBotCleaning").DisplayName.AddTranslation(GameCulture.Russian, "Уборщик");
            redemption.GetNPC("JanitorBotDefeated").DisplayName.AddTranslation(GameCulture.Russian, "Уборщик");
            redemption.GetNPC("JanitorBotNPC").DisplayName.AddTranslation(GameCulture.Russian, "Уборщик");
            redemption.GetNPC("LabSentryDrone").DisplayName.AddTranslation(GameCulture.Russian, "Лабораторный дрон");
            redemption.GetNPC("LabSentryTurretLeg").DisplayName.AddTranslation(GameCulture.Russian, "Лабораторная турель");
            redemption.GetNPC("MACEControllerIdle").DisplayName.AddTranslation(GameCulture.Russian, "Оператор крана");
            redemption.GetNPC("MACEProjectFist1A").DisplayName.AddTranslation(GameCulture.Russian, "Кулак проекта Б.У.Л.А.В.А");
            redemption.GetNPC("MACEProjectFist1B").DisplayName.AddTranslation(GameCulture.Russian, "Кулак проекта Б.У.Л.А.В.А");
            redemption.GetNPC("MACEProjectHeadA").DisplayName.AddTranslation(GameCulture.Russian, "Проект Б.У.Л.А.В.А");
            redemption.GetNPC("MACEProjectJawA").DisplayName.AddTranslation(GameCulture.Russian, "Проект Б.У.Л.А.В.А");
            redemption.GetNPC("MACEProjectJawOffA").DisplayName.AddTranslation(GameCulture.Russian, "Проект Б.У.Л.А.В.А");
            redemption.GetNPC("MACEProjectOffA").DisplayName.AddTranslation(GameCulture.Russian, "Проект Б.У.Л.А.В.А");
            redemption.GetNPC("ProtectorVoltNPC").DisplayName.AddTranslation(GameCulture.Russian, "Защитник Вольт");
            redemption.GetNPC("PZ2BodyCover").DisplayName.AddTranslation(GameCulture.Russian, "Кари");
            redemption.GetNPC("PZ2Eyelid").DisplayName.AddTranslation(GameCulture.Russian, "Нулевой пациент");
            redemption.GetNPC("PZ2Fight").DisplayName.AddTranslation(GameCulture.Russian, "Нулевой пациент");
            redemption.GetNPC("Stage3Scientist2").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный ученый - 3 стадия заражения");
            redemption.GetNPC("TbotMiniboss").DisplayName.AddTranslation(GameCulture.Russian, "Защитник Вольт");
            redemption.GetNPC("TbotMinibossStart").DisplayName.AddTranslation(GameCulture.Russian, "Защитник Вольт");
            redemption.GetNPC("EvilJellyBoss").DisplayName.AddTranslation(GameCulture.Russian, "Темный слизень");
            redemption.GetNPC("MossyGoliath").DisplayName.AddTranslation(GameCulture.Russian, "Мшистый голиаф");
            redemption.GetNPC("MossyGoliath_Sleep").DisplayName.AddTranslation(GameCulture.Russian, "Мшистый голиаф");
            redemption.GetNPC("AncientArcher").DisplayName.AddTranslation(GameCulture.Russian, "Древний лучник");
            redemption.GetNPC("AncientCaster").DisplayName.AddTranslation(GameCulture.Russian, "Древний временщик");
            redemption.GetNPC("BabbyDragonHead").DisplayName.AddTranslation(GameCulture.Russian, "Звездный змей");
            redemption.GetNPC("BabbyDragonBody").DisplayName.AddTranslation(GameCulture.Russian, "Звездный змей");
            redemption.GetNPC("BabbyDragonLeg").DisplayName.AddTranslation(GameCulture.Russian, "Звездный змей");
            redemption.GetNPC("BabbyDragonTail1").DisplayName.AddTranslation(GameCulture.Russian, "Звездный змей");
            redemption.GetNPC("BabbyDragonTail2").DisplayName.AddTranslation(GameCulture.Russian, "Звездный змей");
            redemption.GetNPC("BileBoomer").DisplayName.AddTranslation(GameCulture.Russian, "Рвотный бомбардир");
            redemption.GetNPC("BloatedFaceMonster").DisplayName.AddTranslation(GameCulture.Russian, "Вздутый лицемонстр");
            redemption.GetNPC("BloatedGoldfish").DisplayName.AddTranslation(GameCulture.Russian, "Вздутая золотая рыбка");
            redemption.GetNPC("BloodBoiledSkeleton").DisplayName.AddTranslation(GameCulture.Russian, "Кроваво-закипевший скелет");
            redemption.GetNPC("BloodDiggerBody").DisplayName.AddTranslation(GameCulture.Russian, "Мозговой пожиратель");
            redemption.GetNPC("BloodDiggerHead").DisplayName.AddTranslation(GameCulture.Russian, "Мозговой пожиратель");
            redemption.GetNPC("BloodDiggerTail").DisplayName.AddTranslation(GameCulture.Russian, "Мозговой пожиратель");
            redemption.GetNPC("BobTheBlob").DisplayName.AddTranslation(GameCulture.Russian, "Сли, Слизь");
            redemption.GetNPC("CleaverDagger").DisplayName.AddTranslation(GameCulture.Russian, "Кинжал Гирус");
            redemption.GetNPC("CorruptedCopter1").DisplayName.AddTranslation(GameCulture.Russian, "Штурмовой везделет Гирус");
            redemption.GetNPC("CorruptedDrone1").DisplayName.AddTranslation(GameCulture.Russian, "Штурмовой дрон Гирус");
            redemption.GetNPC("CursedThornBloom").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый цветок");
            redemption.GetNPC("Daerel1").DisplayName.AddTranslation(GameCulture.Russian, "Путник");
            redemption.GetNPC("Daerel2").DisplayName.AddTranslation(GameCulture.Russian, "Путник");
            redemption.GetNPC("Daerel2Unconscious").DisplayName.AddTranslation(GameCulture.Russian, "Даррел");
            redemption.GetNPC("Daerel3").DisplayName.AddTranslation(GameCulture.Russian, "Темный охотник");
            redemption.GetNPC("Daerel3Unconscious").DisplayName.AddTranslation(GameCulture.Russian, "Даррел");
            redemption.GetNPC("DaerelUnconscious").DisplayName.AddTranslation(GameCulture.Russian, "Даррел");
            redemption.GetNPC("DecayedGhoul").DisplayName.AddTranslation(GameCulture.Russian, "Гнилой гуль");
            redemption.GetNPC("ElderForestGolem").DisplayName.AddTranslation(GameCulture.Russian, "Старший лесной голем");
            redemption.GetNPC("ElderForestGolemBlooming").DisplayName.AddTranslation(GameCulture.Russian, "Старший лесной голем");
            redemption.GetNPC("ElderForestGolemWounded").DisplayName.AddTranslation(GameCulture.Russian, "Старший лесной голем");
            redemption.GetNPC("FallenAncient").DisplayName.AddTranslation(GameCulture.Russian, "Павший древний");
            redemption.GetNPC("ForestGolemHibernating").DisplayName.AddTranslation(GameCulture.Russian, "Лесной голем");
            redemption.GetNPC("GreenPigron").DisplayName.AddTranslation(GameCulture.Russian, "Свинья-дракон");
            redemption.GetNPC("InfectedChicken").DisplayName.AddTranslation(GameCulture.Russian, "Зараженная курица");
            redemption.GetNPC("InfectedGrub").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированная личинка");
            redemption.GetNPC("InfectedSnowFlinx").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный снежный флинкс");
            redemption.GetNPC("InfectedSwarmer").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный взрослый муравьиный лев");
            redemption.GetNPC("Injector").DisplayName.AddTranslation(GameCulture.Russian, "Инжектор");
            redemption.GetNPC("IrradiatedSpear").DisplayName.AddTranslation(GameCulture.Russian, "Облученное копье");
            redemption.GetNPC("IrradiatedWorldFeederBody").DisplayName.AddTranslation(GameCulture.Russian, "Облученный кормилец миров");
            redemption.GetNPC("IrradiatedWorldFeederHead").DisplayName.AddTranslation(GameCulture.Russian, "Облученный кормилец миров");
            redemption.GetNPC("IrradiatedWorldFeederTail").DisplayName.AddTranslation(GameCulture.Russian, "Облученный кормилец миров");
            redemption.GetNPC("NerveParasite").DisplayName.AddTranslation(GameCulture.Russian, "Нейропаразит");
            redemption.GetNPC("NuclearSlime").DisplayName.AddTranslation(GameCulture.Russian, "Ядерный слизень");
            redemption.GetNPC("OmegaPilotDroid").DisplayName.AddTranslation(GameCulture.Russian, "Омега Мк-2 пилот");
            redemption.GetNPC("RadioactiveSlime").DisplayName.AddTranslation(GameCulture.Russian, "Радиоактивный слизень");
            redemption.GetNPC("RadioactiveSlimer").DisplayName.AddTranslation(GameCulture.Russian, "Радиоактивный слизневик");
            redemption.GetNPC("RadiumDigger2Body").DisplayName.AddTranslation(GameCulture.Russian, "Рассекатель пустоши");
            redemption.GetNPC("RadiumDigger2Head").DisplayName.AddTranslation(GameCulture.Russian, "Рассекатель пустоши");
            redemption.GetNPC("RadiumDigger2Tail").DisplayName.AddTranslation(GameCulture.Russian, "Рассекатель пустоши");
            redemption.GetNPC("RadiumRampager").DisplayName.AddTranslation(GameCulture.Russian, "Радиевый набрасыватель");
            redemption.GetNPC("Shadebug").DisplayName.AddTranslation(GameCulture.Russian, "Теневая ошибка");
            redemption.GetNPC("ShadesoulNPC").DisplayName.AddTranslation(GameCulture.Russian, "Теневая душа");
            redemption.GetNPC("SmallShadesoulNPC").DisplayName.AddTranslation(GameCulture.Russian, "Малая теневая душа");
            redemption.GetNPC("SneezyInfectedFlinx").DisplayName.AddTranslation(GameCulture.Russian, "Инфицированный снежный флинкс");
            redemption.GetNPC("SoullessAssassin").DisplayName.AddTranslation(GameCulture.Russian, "Бездушный убийца");
            redemption.GetNPC("SoullessDueller").DisplayName.AddTranslation(GameCulture.Russian, "Бездушный дуэлянт");
            redemption.GetNPC("SoullessWanderer").DisplayName.AddTranslation(GameCulture.Russian, "Бездушный бродяга");
            redemption.GetNPC("SpikyRadioactiveSlime").DisplayName.AddTranslation(GameCulture.Russian, "Шипованный радиоактивный слизень");
            redemption.GetNPC("Superbug").DisplayName.AddTranslation(GameCulture.Russian, "Супержук");
            redemption.GetNPC("Superbug2").DisplayName.AddTranslation(GameCulture.Russian, "Супержук");
            redemption.GetNPC("TheSoulless2").DisplayName.AddTranslation(GameCulture.Russian, "Бездушный");
            redemption.GetNPC("VirusJelly").DisplayName.AddTranslation(GameCulture.Russian, "Чумная физалия");
            redemption.GetNPC("Xenoling").DisplayName.AddTranslation(GameCulture.Russian, "Ксенолинщик");
            redemption.GetNPC("XenomiteBeast").DisplayName.AddTranslation(GameCulture.Russian, "Зараженный зверь");
            redemption.GetNPC("Zep2Unconscious").DisplayName.AddTranslation(GameCulture.Russian, "Зефос");
            redemption.GetNPC("Zep3Unconscious").DisplayName.AddTranslation(GameCulture.Russian, "Зефос");
            redemption.GetNPC("Zephos1").DisplayName.AddTranslation(GameCulture.Russian, "Путник");
            redemption.GetNPC("Zephos2").DisplayName.AddTranslation(GameCulture.Russian, "Путник");
            redemption.GetNPC("Zephos3").DisplayName.AddTranslation(GameCulture.Russian, "Рассекатель");
            redemption.GetNPC("ZepUnconscious").DisplayName.AddTranslation(GameCulture.Russian, "Зефос");
            redemption.GetNPC("EbonForestGolem").DisplayName.AddTranslation(GameCulture.Russian, "Чернодревесный голем");
            redemption.GetNPC("EbonNymph").DisplayName.AddTranslation(GameCulture.Russian, "Лесная нимфа");
            redemption.GetNPC("HallowNymph").DisplayName.AddTranslation(GameCulture.Russian, "Лесная нимфа");
            redemption.GetNPC("LeghornChicken").DisplayName.AddTranslation(GameCulture.Russian, "Курица");
            redemption.GetNPC("LongChicken").DisplayName.AddTranslation(GameCulture.Russian, "Д л и н н а я  курица");
            redemption.GetNPC("RedChicken").DisplayName.AddTranslation(GameCulture.Russian, "Курица");
            redemption.GetNPC("ShadeForestGolem").DisplayName.AddTranslation(GameCulture.Russian, "Мрачнодревесный голем");
            redemption.GetNPC("ShadeNymph").DisplayName.AddTranslation(GameCulture.Russian, "Лесная нимфа");
            redemption.GetNPC("SkeletonAssassin2").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-убийца");
            redemption.GetNPC("SkeletonWanderer2").DisplayName.AddTranslation(GameCulture.Russian, "Скелет-бродяга");
            redemption.GetNPC("Vepdor").DisplayName.AddTranslation(GameCulture.Russian, "Останки поставщика");
            redemption.GetNPC("VlitchChicken").DisplayName.AddTranslation(GameCulture.Russian, "Курица?");
            redemption.GetNPC("KS3Sitting").DisplayName.AddTranslation(GameCulture.Russian, "Убийца королей III");
        }
    }
}
