using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ModOfRedemption.Buffs
{
	internal class RedemptionBuffs
	{
		public static void Setup()
		{
			Buffs();
		}
		private static void Buffs()
		{
			Mod redemption = ModLoader.GetMod("Redemption");
			
			redemption.GetBuff("AncientForcefieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Древнее силовое поле");
			redemption.GetBuff("AncientForcefieldBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы защищены древними силами\"");
			redemption.GetBuff("AncientForcefieldBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Древнее силовое поле");
			redemption.GetBuff("AncientForcefieldBuff2").Description.AddTranslation(GameCulture.Russian, "\"Вы защищены древними силами\"");
			redemption.GetBuff("AncientMirrorBuff").DisplayName.AddTranslation(GameCulture.Russian, "Древний зеркальный щит");
			redemption.GetBuff("AncientMirrorBuff").Description.AddTranslation(GameCulture.Russian, "\"Отражает снаряды!\"");
			redemption.GetBuff("AncientStoneMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Древняя галька");
			redemption.GetBuff("AncientStoneMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается волшебная галька!\"");
			redemption.GetBuff("AndroidMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Андроид - прислужник");
			redemption.GetBuff("AndroidMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается маленький андроид!\"");
			redemption.GetBuff("AntiXenomiteBuff").DisplayName.AddTranslation(GameCulture.Russian, "Иммунитет к Ксеномиту");
			redemption.GetBuff("AntiXenomiteBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы невосприимчивы к Ксеномиту...\"");
			redemption.GetBuff("BarkskinBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лубяная кожа");
			redemption.GetBuff("BInfectionDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Бактериальная инфекция");
			redemption.GetBuff("BInfectionDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы медленно теряете здоровье\"");
			redemption.GetBuff("BirdMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Птица");
			redemption.GetBuff("BirdMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается птица!\"");
			redemption.GetBuff("BlackenedHeartBuff").DisplayName.AddTranslation(GameCulture.Russian, "Бездушие");
			redemption.GetBuff("BlackenedHeartBuff").Description.AddTranslation(GameCulture.Russian, "\"...\"");
			redemption.GetBuff("BlackenedHeartBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Бездушие");
			redemption.GetBuff("BlackenedHeartBuff2").Description.AddTranslation(GameCulture.Russian, "\"...\"");
			redemption.GetBuff("BlackenedHeartDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Бездушие");
			redemption.GetBuff("BlackenedHeartDebuff").Description.AddTranslation(GameCulture.Russian, "\"...\"");
			redemption.GetBuff("BlightedShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Чумной щит");
			redemption.GetBuff("BlightedShieldBuff").Description.AddTranslation(GameCulture.Russian, "\"Увеличивает вашу защиту!\"");
			redemption.GetBuff("BloodCrystalDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Пронзённый!");
			redemption.GetBuff("BloodCrystalDebuff").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			redemption.GetBuff("BurntHands").DisplayName.AddTranslation(GameCulture.Russian, "Горящие руки");
			redemption.GetBuff("BurntHands").Description.AddTranslation(GameCulture.Russian, "\"Горячо, горячо, горячо!\"");
			redemption.GetBuff("ChainedDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Прикованный!");
			redemption.GetBuff("ChainedDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы не можете сбежать!\"");
			redemption.GetBuff("CharismaPotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Харизма");
			redemption.GetBuff("CharismaPotionBuff").Description.AddTranslation(GameCulture.Russian, "\"Городские жители продают товары дешевле, с противников падает больше монет\"");
			redemption.GetBuff("ChickenBuff").DisplayName.AddTranslation(GameCulture.Russian, "Домашняя курица");
			redemption.GetBuff("ChickenBuff").Description.AddTranslation(GameCulture.Russian, "\"Она никогда не покинет вас...\"");
			redemption.GetBuff("ChickenCrownBuff").DisplayName.AddTranslation(GameCulture.Russian, "Куриный король!");
			redemption.GetBuff("ChickenCrownBuff").Description.AddTranslation(GameCulture.Russian, "Вы - Могучий Куриный Король!");
			redemption.GetBuff("ChickenMountBuff").DisplayName.AddTranslation(GameCulture.Russian, "Куриная кавалерия");
			redemption.GetBuff("ChickenMountBuff").Description.AddTranslation(GameCulture.Russian, "'Кавалерия прибыла!'");
			redemption.GetBuff("ChickenShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Защищенный");
			redemption.GetBuff("ChickenShieldBuff").Description.AddTranslation(GameCulture.Russian, "\"Увеличивает защиту и даёт иммунитет к отбрасыванию, но снижает скорость передвижения\"");
			redemption.GetBuff("ChickenSwarmerMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Куриный роевик");
			redemption.GetBuff("ChickenSwarmerMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается летающая курица!\"");
			redemption.GetBuff("CombatChickenBuff").DisplayName.AddTranslation(GameCulture.Russian, "Боевой Петух");
			redemption.GetBuff("CombatChickenBuff").Description.AddTranslation(GameCulture.Russian, "\"Теперь вы Король кур!\"");
			redemption.GetBuff("CorpseSkullBuff").DisplayName.AddTranslation(GameCulture.Russian, "Череп ходячего трупа");
			redemption.GetBuff("CorpseSkullBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается иссушенный череп!\"");
			redemption.GetBuff("CorruptedCopterBuff").DisplayName.AddTranslation(GameCulture.Russian, "Маленький штурмовой везделёт Гирус");
			redemption.GetBuff("CorruptedCopterBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается маленький везделёт Гирус!\"");
			redemption.GetBuff("CursedCrystalDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Пронзенный!");
			redemption.GetBuff("CursedCrystalDebuff").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			redemption.GetBuff("DaggerBuff").DisplayName.AddTranslation(GameCulture.Russian, "Уколотый");
			redemption.GetBuff("DaggerBuff").Description.AddTranslation(GameCulture.Russian, "Повышает ваш урон ценой уменьшения максимального запаса здоровья");
			redemption.GetBuff("DarkSoulBuff").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная душа");
			redemption.GetBuff("DarkSoulBuff").Description.AddTranslation(GameCulture.Russian, "За вас сражается тёмная душа");
			redemption.GetBuff("DisgustingDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Отвратительно");
			redemption.GetBuff("DisgustingDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы попробовали что-то невероятно омерзительное\"");
			redemption.GetBuff("DreamsongBuff").DisplayName.AddTranslation(GameCulture.Russian, "Мечтапеснь");
			redemption.GetBuff("DreamsongBuff").Description.AddTranslation(GameCulture.Russian, "В бездушных пещерах ваше зрение улучшается");
			redemption.GetBuff("DruidEssenceBuff").DisplayName.AddTranslation(GameCulture.Russian, "Эссенция друида");
			redemption.GetBuff("DruidEssenceBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и критический урон друида\"");
			redemption.GetBuff("DruidsBane").DisplayName.AddTranslation(GameCulture.Russian, "Проклятие друида");
			redemption.GetBuff("DruidsBane").Description.AddTranslation(GameCulture.Russian, "\"Сила созидания друида проклинает вас\"");
			redemption.GetBuff("DruidsBlessing").DisplayName.AddTranslation(GameCulture.Russian, "Благословение друида");
			redemption.GetBuff("DruidsBlessing").Description.AddTranslation(GameCulture.Russian, "\"Сила созидания друида благословляет вас\"");
			redemption.GetBuff("EaglecrestMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Прислужник с Иглкреста");
			redemption.GetBuff("EaglecrestMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается маленький голем!\"");
			redemption.GetBuff("EarthbindDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Привязан к земле");
			redemption.GetBuff("EarthbindDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы вынуждены вернуться на землю!\"");
			redemption.GetBuff("EldritchRootBuff").DisplayName.AddTranslation(GameCulture.Russian, "Древняя регенерация");
			redemption.GetBuff("EldritchRootBuff").Description.AddTranslation(GameCulture.Russian, "\"Значительно повышает восстановление здоровья\"");
			redemption.GetBuff("ElementBlessed").DisplayName.AddTranslation(GameCulture.Russian, "Благословение");
			redemption.GetBuff("ElementBlessed").Description.AddTranslation(GameCulture.Russian, "\"Вы благословлены божественной защитой Икара...\"");
			redemption.GetBuff("EnjoymentDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Наслаждение");
			redemption.GetBuff("EnjoymentDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы слишком сильно наслаждаетесь этим\"");
			redemption.GetBuff("EvilJellyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Злое желе");
			redemption.GetBuff("EvilJellyBuff").Description.AddTranslation(GameCulture.Russian, "\"Приманивает тёмного слизня\"");
			redemption.GetBuff("FireBlessed").DisplayName.AddTranslation(GameCulture.Russian, "Благословение");
			redemption.GetBuff("FireBlessed").Description.AddTranslation(GameCulture.Russian, "\"Вы благословлены божественной защитой Икара...\"");
			redemption.GetBuff("FireForceBuff").DisplayName.AddTranslation(GameCulture.Russian, "Огненная сила");
			redemption.GetBuff("FireForceBuff").Description.AddTranslation(GameCulture.Russian, "\"Горящие кристаллы усиливают ваше тело\"");
			redemption.GetBuff("FreezeForceBuff").DisplayName.AddTranslation(GameCulture.Russian, "Замораживающая сила");
			redemption.GetBuff("FreezeForceBuff").Description.AddTranslation(GameCulture.Russian, "\"Замораживающие кристаллы усиливают ваше тело\"");
			redemption.GetBuff("FrightBuff").DisplayName.AddTranslation(GameCulture.Russian, "Аура ужаса");
			redemption.GetBuff("FrightBuff").Description.AddTranslation(GameCulture.Russian, "Повышает весь урон и шансы критического удара");
			redemption.GetBuff("FrostBlessed").DisplayName.AddTranslation(GameCulture.Russian, "Благословение");
			redemption.GetBuff("FrostBlessed").Description.AddTranslation(GameCulture.Russian, "\"Вы благословлены божественной защитой Икара...\"");
			redemption.GetBuff("FrozenEnemyDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Заморожен");
			redemption.GetBuff("GirusCloakBuff").DisplayName.AddTranslation(GameCulture.Russian, "Под покровом");
			redemption.GetBuff("GirusCloakBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы скрыты от Гирус\"");
			redemption.GetBuff("GloomShroomDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Споры: сумрачный гриб");
			redemption.GetBuff("GloomShroomDebuff").Description.AddTranslation(GameCulture.Russian, "\"Сумрачные споры покрывают вашу кожу\"");
			redemption.GetBuff("GlowingMBuff").DisplayName.AddTranslation(GameCulture.Russian, "Споры: светящиеся грибы");
			redemption.GetBuff("GlowingMBuff").Description.AddTranslation(GameCulture.Russian, "\"Незначительно увеличивает все характеристики\"");
			redemption.GetBuff("GolemSpelltomeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Зачарование Иглкреста");
			redemption.GetBuff("GolemSpelltomeBuff").Description.AddTranslation(GameCulture.Russian, "\"Привлекает спящие камни\"");
			redemption.GetBuff("GraniteAuraBuff").DisplayName.AddTranslation(GameCulture.Russian, "Гранитная аура");
			redemption.GetBuff("GraniteAuraBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы источаете энергию\"");
			redemption.GetBuff("GSSBuff").DisplayName.AddTranslation(GameCulture.Russian, "Небесное парирование");
			redemption.GetBuff("GuardianCooldownDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка природного стража");
			redemption.GetBuff("GuardianCooldownDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы не можете призвать природных стражей\"");
			redemption.GetBuff("HalPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Бутерброд с ветчиной");
			redemption.GetBuff("HalPetBuff").Description.AddTranslation(GameCulture.Russian, "Бойся меня");
			redemption.GetBuff("HazardLaserDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Сожжен!");
			redemption.GetBuff("HazardLaserDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вас атакуют лазером!\"");
			redemption.GetBuff("HazmatSuitBuff").DisplayName.AddTranslation(GameCulture.Russian, "Защитный костюм");
			redemption.GetBuff("HazmatSuitBuff").Description.AddTranslation(GameCulture.Russian, "Вы защищены от воды лаборатории");
			redemption.GetBuff("HealShroomBuff").DisplayName.AddTranslation(GameCulture.Russian, "Споры: исцеляющий гриб");
			redemption.GetBuff("HealShroomBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает восстановление здоровья\"");
			redemption.GetBuff("HeartEmblemBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сердечная спешка");
			redemption.GetBuff("HeartEmblemBuff").Description.AddTranslation(GameCulture.Russian, "\"Значительно повышает восстановление здоровья!\"");
			redemption.GetBuff("HeavyRadiationDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Мощная радиация");
			redemption.GetBuff("HeavyRadiationDebuff").Description.AddTranslation(GameCulture.Russian, "\"Из-за радиации характеристики значительно снижены\"");
			redemption.GetBuff("HEVSuitBuff").Description.AddTranslation(GameCulture.Russian, "Снаряжение <HEV>");
			redemption.GetBuff("HEVSuitBuff").DisplayName.AddTranslation(GameCulture.Russian, "Вы защищены от инфекции и радиации");
			redemption.GetBuff("HitActivation").DisplayName.AddTranslation(GameCulture.Russian, "ударен");
			redemption.GetBuff("HitActivation").Description.AddTranslation(GameCulture.Russian, "И как ты это читаешь?");
			redemption.GetBuff("HiveGrowthBuff").DisplayName.AddTranslation(GameCulture.Russian, "Порождение улья");
			redemption.GetBuff("HiveGrowthBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается порождение улья!\"");
			redemption.GetBuff("HKStatueBuff").DisplayName.AddTranslation(GameCulture.Russian, "...");
			redemption.GetBuff("HKStatueBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы чувствуете, что за вами наблюдают...\"");
			redemption.GetBuff("HoloMinionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Голограмма");
			redemption.GetBuff("HoloMinionBuff").Description.AddTranslation(GameCulture.Russian, "\"Подождите, в смысле голограммы атакуют?!\"");
			redemption.GetBuff("HolyFireDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Накал");
			redemption.GetBuff("HolyFireDebuff").Description.AddTranslation(GameCulture.Russian, "\"НЕТ! СЛИШКОМ ВЕЛИКОЛЕПНО! ОСТАНОВИСЬ!\"");
			redemption.GetBuff("IntruderAlertDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Обнаружен");
			redemption.GetBuff("IntruderAlertDebuff").Description.AddTranslation(GameCulture.Russian, "\"Защитные системы лаборатории заметили вас\"");
			redemption.GetBuff("JanitorStun").DisplayName.AddTranslation(GameCulture.Russian, "Ошеломление уборщика");
			redemption.GetBuff("JanitorStun").Description.AddTranslation(GameCulture.Russian, "\"Как ТЫ читаешь это?! Это же только для Уборщика!\"");
			redemption.GetBuff("KSShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "За щитом");
			redemption.GetBuff("KSShieldBuff").Description.AddTranslation(GameCulture.Russian, "Вы прикрыты щитом");
			redemption.GetBuff("KSShieldCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка карманного щита");
			redemption.GetBuff("KSShieldCooldown").Description.AddTranslation(GameCulture.Russian, "Щит не защитит вас от смертельного урона");
			redemption.GetBuff("LaceratedDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Разорван");
			redemption.GetBuff("LaceratedDebuff").Description.AddTranslation(GameCulture.Russian, "\"Глубокий порез\"");
			redemption.GetBuff("LavaCubeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Лавовый куб");
			redemption.GetBuff("LavaCubeBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается раскаленный куб!\"");
			redemption.GetBuff("LilyBuff").DisplayName.AddTranslation(GameCulture.Russian, "Усиление лилии");
			redemption.GetBuff("LilyBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон друида, снижает остальной урон\"");
			redemption.GetBuff("LotusBuff").DisplayName.AddTranslation(GameCulture.Russian, "Усиление лотоса");
			redemption.GetBuff("LotusBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает шанс критического удара друида, снижает остальные шансы критического удара\"");
			redemption.GetBuff("MageDroneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Медузный дрон");
			redemption.GetBuff("MageDroneBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается медузный дрон!\"");
			redemption.GetBuff("MartianShieldBuff").DisplayName.AddTranslation(GameCulture.Russian, "Марсианский щит");
			redemption.GetBuff("MartianShieldBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы защищены инопланетным силовым полем\"");
			redemption.GetBuff("MechEnhancementBuff").DisplayName.AddTranslation(GameCulture.Russian, "Механическое усиление");
			redemption.GetBuff("MechEnhancementBuff").Description.AddTranslation(GameCulture.Russian, "\"Нанороботы улучшают ваши боевые способности\"");
			redemption.GetBuff("MightBuff").DisplayName.AddTranslation(GameCulture.Russian, "Аура могущества");
			redemption.GetBuff("MightBuff").Description.AddTranslation(GameCulture.Russian, "Повышает сопротивление урону, вы невосприимчивы к отбрасыванию");
			redemption.GetBuff("Mk1MicrobotBuff").DisplayName.AddTranslation(GameCulture.Russian, "Микробот, модель I");
			redemption.GetBuff("Mk1MicrobotBuff").Description.AddTranslation(GameCulture.Russian, "\"Бип буп\"");
			redemption.GetBuff("Mk2MicrobotBuff").DisplayName.AddTranslation(GameCulture.Russian, "Микробот, модель II");
			redemption.GetBuff("Mk2MicrobotBuff").Description.AddTranslation(GameCulture.Russian, "\"Буп бип\"");
			redemption.GetBuff("Mk3MicrobotBuff").DisplayName.AddTranslation(GameCulture.Russian, "Микробот, модель III");
			redemption.GetBuff("Mk3MicrobotBuff").Description.AddTranslation(GameCulture.Russian, "\"Бип буп, пиу пиу\"");
			redemption.GetBuff("MoonFireDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Призрачные огни");
			redemption.GetBuff("MoonFireDebuff").Description.AddTranslation(GameCulture.Russian, "\"\"");
			redemption.GetBuff("NatureGuardian10Buff").DisplayName.AddTranslation(GameCulture.Russian, "Страж-скелет");
			redemption.GetBuff("NatureGuardian10Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает страж-скелет!\"");
			redemption.GetBuff("NatureGuardian11Buff").DisplayName.AddTranslation(GameCulture.Russian, "Грязевой страж");
			redemption.GetBuff("NatureGuardian11Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает грязевой страж!\"");
			redemption.GetBuff("NatureGuardian12Buff").DisplayName.AddTranslation(GameCulture.Russian, "Лавовый страж");
			redemption.GetBuff("NatureGuardian12Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает лавовый страж!\"");
			redemption.GetBuff("NatureGuardian13Buff").DisplayName.AddTranslation(GameCulture.Russian, "Осколок мраморного короля");
			redemption.GetBuff("NatureGuardian13Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает осколок мраморного короля!\"");
			redemption.GetBuff("NatureGuardian14Buff").DisplayName.AddTranslation(GameCulture.Russian, "Лунная статуэтка");
			redemption.GetBuff("NatureGuardian14Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает лунная статуэтка!\"");
			redemption.GetBuff("NatureGuardian15Buff").DisplayName.AddTranslation(GameCulture.Russian, "Истинная лунная статуэтка");
			redemption.GetBuff("NatureGuardian15Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает истинная лунная статуэтка!\"");
			redemption.GetBuff("NatureGuardian16Buff").DisplayName.AddTranslation(GameCulture.Russian, "Святая статуэтка");
			redemption.GetBuff("NatureGuardian16Buff").Description.AddTranslation(GameCulture.Russian, "\"Он наблюдает...\"");
			redemption.GetBuff("NatureGuardian17Buff").DisplayName.AddTranslation(GameCulture.Russian, "Истинная святая статуэтка");
			redemption.GetBuff("NatureGuardian17Buff").Description.AddTranslation(GameCulture.Russian, "\"Он наблюдает...\"");
			redemption.GetBuff("NatureGuardian18Buff").DisplayName.AddTranslation(GameCulture.Russian, "Древо созидания");
			redemption.GetBuff("NatureGuardian18Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает древо созидания!\"");
			redemption.GetBuff("NatureGuardian19Buff").DisplayName.AddTranslation(GameCulture.Russian, "Терра-страж");
			redemption.GetBuff("NatureGuardian19Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает терра-страж!\"");
			redemption.GetBuff("NatureGuardian20Buff").DisplayName.AddTranslation(GameCulture.Russian, "Дух Сапфирона");
			redemption.GetBuff("NatureGuardian20Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает дух Сапфирона!\"");
			redemption.GetBuff("NatureGuardian21Buff").DisplayName.AddTranslation(GameCulture.Russian, "Дух Скарлиона");
			redemption.GetBuff("NatureGuardian21Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает дух Скарлиона!\"");
			redemption.GetBuff("NatureGuardian22Buff").DisplayName.AddTranslation(GameCulture.Russian, "Солнечная пикси");
			redemption.GetBuff("NatureGuardian22Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает солнечная пикси!\"");
			redemption.GetBuff("NatureGuardian23Buff").DisplayName.AddTranslation(GameCulture.Russian, "Ледовая пикси");
			redemption.GetBuff("NatureGuardian23Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает ледяная пикси!\"");
			redemption.GetBuff("NatureGuardian24Buff").DisplayName.AddTranslation(GameCulture.Russian, "Споровая пикси");
			redemption.GetBuff("NatureGuardian24Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает споровая пикси!\"");
			redemption.GetBuff("NatureGuardian25Buff").DisplayName.AddTranslation(GameCulture.Russian, "Троица пикси");
			redemption.GetBuff("NatureGuardian25Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищают все пикси!\"");
			redemption.GetBuff("NatureGuardian26Buff").DisplayName.AddTranslation(GameCulture.Russian, "Северная статуэтка");
			redemption.GetBuff("NatureGuardian26Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает северная статуэтка!\"");
			redemption.GetBuff("NatureGuardian27Buff").DisplayName.AddTranslation(GameCulture.Russian, "Древняя статуя");
			redemption.GetBuff("NatureGuardian27Buff").Description.AddTranslation(GameCulture.Russian, "\"Он наблюдает...\"");
			redemption.GetBuff("NatureGuardian28Buff").DisplayName.AddTranslation(GameCulture.Russian, "Лунный барон");
			redemption.GetBuff("NatureGuardian28Buff").Description.AddTranslation(GameCulture.Russian, "Вас защищает лунный барон!");
			redemption.GetBuff("NatureGuardian2Buff").DisplayName.AddTranslation(GameCulture.Russian, "Природный страж");
			redemption.GetBuff("NatureGuardian2Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает природный страж!\"");
			redemption.GetBuff("NatureGuardian3Buff").DisplayName.AddTranslation(GameCulture.Russian, "Искаженная пикси");
			redemption.GetBuff("NatureGuardian3Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает искаженная пикси!\"");
			redemption.GetBuff("NatureGuardian4Buff").DisplayName.AddTranslation(GameCulture.Russian, "Багряная пикси");
			redemption.GetBuff("NatureGuardian4Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает багряная пикси!\"");
			redemption.GetBuff("NatureGuardian5Buff").DisplayName.AddTranslation(GameCulture.Russian, "Древняя пикси");
			redemption.GetBuff("NatureGuardian5Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает древняя пикси!\"");
			redemption.GetBuff("NatureGuardian6Buff").DisplayName.AddTranslation(GameCulture.Russian, "Лунная вспышка");
			redemption.GetBuff("NatureGuardian6Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает лунная вспышка!\"");
			redemption.GetBuff("NatureGuardian7Buff").DisplayName.AddTranslation(GameCulture.Russian, "Освященный страж");
			redemption.GetBuff("NatureGuardian7Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает освященный страж!\"");
			redemption.GetBuff("NatureGuardian8Buff").DisplayName.AddTranslation(GameCulture.Russian, "Искаженная фея");
			redemption.GetBuff("NatureGuardian8Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает искаженная фея!\"");
			redemption.GetBuff("NatureGuardian9Buff").DisplayName.AddTranslation(GameCulture.Russian, "Багряная фея");
			redemption.GetBuff("NatureGuardian9Buff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает багряная фея!\"");
			redemption.GetBuff("NatureGuardianBuff").DisplayName.AddTranslation(GameCulture.Russian, "Природная пикси");
			redemption.GetBuff("NatureGuardianBuff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает природная пикси!\"");
			redemption.GetBuff("NebPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Небби");
			redemption.GetBuff("NebPetBuff").Description.AddTranslation(GameCulture.Russian, "\"Неббити Ноббити Ниббити Ной, эта маленькая звёздная девочка следует за тобой\"");
			redemption.GetBuff("NecroticGouge").DisplayName.AddTranslation(GameCulture.Russian, "Некротическая пустота");
			redemption.GetBuff("NeedleDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Уколотый!");
			redemption.GetBuff("NeedleDebuff").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			redemption.GetBuff("NightshadePotionBuff").DisplayName.AddTranslation(GameCulture.Russian, "Вендетта");
			redemption.GetBuff("NightshadePotionBuff").Description.AddTranslation(GameCulture.Russian, "\"Атакующие также получают урон, и на них накладывается отравление\"");
			redemption.GetBuff("NoitaBombCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка бомб");
			redemption.GetBuff("NoitaBombCooldown").Description.AddTranslation(GameCulture.Russian, "\"Вы не можете использовать жезл бомбы\"");
			redemption.GetBuff("NoobsBlessingBuff").DisplayName.AddTranslation(GameCulture.Russian, "Благословение Ньюба");
			redemption.GetBuff("NoobsBlessingBuff").Description.AddTranslation(GameCulture.Russian, "Ваше оружие благословлено королём Нубов...");
			redemption.GetBuff("OblitBuff1").DisplayName.AddTranslation(GameCulture.Russian, "Мотивация уничтожения");
			redemption.GetBuff("OblitBuff1").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и защиту, снижает восстановление здоровья\"");
			redemption.GetBuff("OblitBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Мотивация уничтожения");
			redemption.GetBuff("OblitBuff2").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и защиту, снижает восстановление здоровья\"");
			redemption.GetBuff("OblitBuff3").DisplayName.AddTranslation(GameCulture.Russian, "Мотивация уничтожения");
			redemption.GetBuff("OblitBuff3").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и защиту, снижает восстановление здоровья\"");
			redemption.GetBuff("OblitBuff4").DisplayName.AddTranslation(GameCulture.Russian, "Мотивация уничтожения");
			redemption.GetBuff("OblitBuff4").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и защиту, снижает восстановление здоровья\"");
			redemption.GetBuff("OblitBuff5").DisplayName.AddTranslation(GameCulture.Russian, "Мотивация уничтожения");
			redemption.GetBuff("OblitBuff5").Description.AddTranslation(GameCulture.Russian, "\"Повышает урон и защиту, снижает восстановление здоровья\"");
			redemption.GetBuff("PowerSurgeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Силовой всплеск");
			redemption.GetBuff("PowerSurgeBuff").Description.AddTranslation(GameCulture.Russian, "\"Ваша броня полна энергии\"");
			redemption.GetBuff("RadioactiveFalloutDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Радиоактивные осадки");
			redemption.GetBuff("RadioactiveFalloutDebuff").Description.AddTranslation(GameCulture.Russian, "\"Из-за радиации характеристики значительно снижены\"");
			redemption.GetBuff("RedemptiveEmbraceBuff").DisplayName.AddTranslation(GameCulture.Russian, "Искупительное объятие");
			redemption.GetBuff("RedemptiveEmbraceBuff").Description.AddTranslation(GameCulture.Russian, "\"Взгляни в лицо грехам своим!\"");
			redemption.GetBuff("SandDustDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Распылен");
			redemption.GetBuff("SandDustDebuff").Description.AddTranslation(GameCulture.Russian, "\"Значительно уменьшает защиту!\"");
			redemption.GetBuff("sansDebuff").DisplayName.AddTranslation(GameCulture.Russian, "санс");
			redemption.GetBuff("sansDebuff").Description.AddTranslation(GameCulture.Russian, "\"Плохое время время\"");
			redemption.GetBuff("ShadeboundBuff").DisplayName.AddTranslation(GameCulture.Russian, "Тенесвязь");
			redemption.GetBuff("ShadeboundBuff").Description.AddTranslation(GameCulture.Russian, "\"Царство духов взывает к тебе\"");
			redemption.GetBuff("Sharpen2Buff").DisplayName.AddTranslation(GameCulture.Russian, "Острота II");
			redemption.GetBuff("Sharpen2Buff").Description.AddTranslation(GameCulture.Russian, "\"Оружия ближнего боя отлично пробивают броню\"");
			redemption.GetBuff("Sharpen3Buff").DisplayName.AddTranslation(GameCulture.Russian, "Острота III");
			redemption.GetBuff("Sharpen3Buff").Description.AddTranslation(GameCulture.Russian, "\"Оружия ближнего боя невероятно пробивают броню\"");
			redemption.GetBuff("ShieldDroneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Щитовой дрон Гирус");
			redemption.GetBuff("ShieldDroneBuff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает щитовой дрон Гирус!\"");
			redemption.GetBuff("ShineArmour2Buff").DisplayName.AddTranslation(GameCulture.Russian, "Сияющая броня II");
			redemption.GetBuff("ShineArmour2Buff").Description.AddTranslation(GameCulture.Russian, "\"Неплохо увеличивает защиту\"");
			redemption.GetBuff("ShineArmour3Buff").DisplayName.AddTranslation(GameCulture.Russian, "Сияющая броня III");
			redemption.GetBuff("ShineArmour3Buff").Description.AddTranslation(GameCulture.Russian, "\"Сильно увеличивает защиту\"");
			redemption.GetBuff("ShineArmourBuff").DisplayName.AddTranslation(GameCulture.Russian, "Сияющая броня");
			redemption.GetBuff("ShineArmourBuff").Description.AddTranslation(GameCulture.Russian, "\"Увеличивает защиту\"");
			redemption.GetBuff("SightBuff").DisplayName.AddTranslation(GameCulture.Russian, "Аура прозрения");
			redemption.GetBuff("SightBuff").Description.AddTranslation(GameCulture.Russian, "Улучшает зрение, вы видите существа и ловушки");
			redemption.GetBuff("SilverwoodArrowDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Стрела из серебряной древесины");
			redemption.GetBuff("SilverwoodArrowDebuff").Description.AddTranslation(GameCulture.Russian, "Вы теряете здоровье");
			redemption.GetBuff("SleepPowderDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Сонный");
			redemption.GetBuff("SleepPowderDebuff").Description.AddTranslation(GameCulture.Russian, "\"Сильно снижает скорость передвижения!\"");
			redemption.GetBuff("SmashedDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Раздавлен!");
			redemption.GetBuff("SmashedDebuff").Description.AddTranslation(GameCulture.Russian, "\"\"");
			redemption.GetBuff("SniperDroneBuff").DisplayName.AddTranslation(GameCulture.Russian, "Снайперский дрон Гирус");
			redemption.GetBuff("SniperDroneBuff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает снайперский дрон Гирус!\"");
			redemption.GetBuff("SoulbladeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Клинок душ");
			redemption.GetBuff("SoulbladeBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает спиритический уровень\"");
			redemption.GetBuff("SoulboundBuff").DisplayName.AddTranslation(GameCulture.Russian, "Душесвязь");
			redemption.GetBuff("SoulboundBuff").Description.AddTranslation(GameCulture.Russian, "\"Царство духов зовёт вас\"");
			redemption.GetBuff("SoulCallerDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Безумное видение");
			redemption.GetBuff("SoulCallerDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы не можете использовать талисман древнего почитателя\"");
			redemption.GetBuff("SoulStaveBuff").DisplayName.AddTranslation(GameCulture.Russian, "Гид души");
			redemption.GetBuff("SoulStaveBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает спиритический уровень\"");
			redemption.GetBuff("SpiceBlueBuff").DisplayName.AddTranslation(GameCulture.Russian, "Светящиеся специи");
			redemption.GetBuff("SpiceBlueBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы излучаете свет\"");
			redemption.GetBuff("SpiceGreenBuff").DisplayName.AddTranslation(GameCulture.Russian, "Земляные специи");
			redemption.GetBuff("SpiceGreenBuff").Description.AddTranslation(GameCulture.Russian, "\"Немного повышает урон и шанс критического удара друида\"");
			redemption.GetBuff("SpiceOrangeBuff").DisplayName.AddTranslation(GameCulture.Russian, "Пикантные специи");
			redemption.GetBuff("SpiceOrangeBuff").Description.AddTranslation(GameCulture.Russian, "\"Ваше оружие поджигает врагов\"");
			redemption.GetBuff("SpiceRedBuff").DisplayName.AddTranslation(GameCulture.Russian, "Острые специи");
			redemption.GetBuff("SpiceRedBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы поджигаете ближайших врагов\"");
			redemption.GetBuff("SpiceWhiteBuff").DisplayName.AddTranslation(GameCulture.Russian, "Соленые специи");
			redemption.GetBuff("SpiceWhiteBuff").Description.AddTranslation(GameCulture.Russian, "\"Повышает сопротивление урону\"");
			redemption.GetBuff("SpiritDragonBuff").DisplayName.AddTranslation(GameCulture.Russian, "Духовный дракон");
			redemption.GetBuff("SpiritDragonBuff").Description.AddTranslation(GameCulture.Russian, "За вас сражается духовный дракон");
			redemption.GetBuff("SpiritWyvernBuff").DisplayName.AddTranslation(GameCulture.Russian, "Духовная виверна");
			redemption.GetBuff("SpiritWyvernBuff").Description.AddTranslation(GameCulture.Russian, "За вас сражается духовная виверна");
			redemption.GetBuff("StarSerpentBuff").DisplayName.AddTranslation(GameCulture.Russian, "Детеныш звёздного змея");
			redemption.GetBuff("StarSerpentBuff").Description.AddTranslation(GameCulture.Russian, "За вас сражается детёныш звездного змея");
			redemption.GetBuff("StoneskinBuff").DisplayName.AddTranslation(GameCulture.Russian, "Каменная кожа");
			redemption.GetBuff("StunnedDebuff").Description.AddTranslation(GameCulture.Russian, "Оглушение!");
			redemption.GetBuff("StunnedDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы оглушены!\"");
			redemption.GetBuff("SunAuraBuff").DisplayName.AddTranslation(GameCulture.Russian, "Солнечная аура");
			redemption.GetBuff("SunAuraBuff").Description.AddTranslation(GameCulture.Russian, "\"Усиление от древних сил ящуров\"");
			redemption.GetBuff("TiedPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Тайд");
			redemption.GetBuff("TiedPetBuff").Description.AddTranslation(GameCulture.Russian, "\"Испуганный\"");
			redemption.GetBuff("TimestopDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Сдвиг времени");
			redemption.GetBuff("TimestopDebuff").Description.AddTranslation(GameCulture.Russian, "\"Время замедлило свой ход!\"");
			redemption.GetBuff("UkkonenBuff").DisplayName.AddTranslation(GameCulture.Russian, "Укконен");
			redemption.GetBuff("UkkonenBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается громоподобный Укконен!\"");
			redemption.GetBuff("UltraFlameDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Плавление!");
			redemption.GetBuff("UltraFlameDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы медленно плавитесь\"");
			redemption.GetBuff("VesselPickBuff").DisplayName.AddTranslation(GameCulture.Russian, "Теневой всплеск");
			redemption.GetBuff("VesselPickBuff").Description.AddTranslation(GameCulture.Russian, "Значительно повышает скорость добычи");
			redemption.GetBuff("VlitchCoreBuff").DisplayName.AddTranslation(GameCulture.Russian, "Висбоящее ядро");
			redemption.GetBuff("VlitchCoreBuff").Description.AddTranslation(GameCulture.Russian, "\"Вас защищает маленькое висбоящее ядро!\"");
			redemption.GetBuff("VlitchCoreCooldown").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка висбоящего ядра");
			redemption.GetBuff("VlitchCoreCooldown").Description.AddTranslation(GameCulture.Russian, "\"Висбоящему ядру нужно время на починку\"");
			redemption.GetBuff("WorldStaveCooldownDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Перезарядка мирового шеста");
			redemption.GetBuff("WorldStaveCooldownDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы не можете использовать мировые шесты\"");
			redemption.GetBuff("XeniumTurretBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff1").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff1").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff10").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff10").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff11").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff11").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff12").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff12").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff2").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff2").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff3").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff3").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff4").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff4").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff5").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff5").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff6").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff6").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff7").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff7").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff8").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff8").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XeniumTurretBuff9").DisplayName.AddTranslation(GameCulture.Russian, "Ксениевая автотурель");
			redemption.GetBuff("XeniumTurretBuff9").Description.AddTranslation(GameCulture.Russian, "\"Пиупиупиупиупиупиу\"");
			redemption.GetBuff("XenoEyeSBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ксеномитное око");
			redemption.GetBuff("XenoEyeSBuff").Description.AddTranslation(GameCulture.Russian, "\"За вас сражается ксеномитное око!\"");
			redemption.GetBuff("XenomiteDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Легкое заражение");
			redemption.GetBuff("XenomiteDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы контактируете с ксеномитом...\"");
			redemption.GetBuff("XenomiteDebuff2").DisplayName.AddTranslation(GameCulture.Russian, "Тяжелое заражение");
			redemption.GetBuff("XenomiteDebuff2").Description.AddTranslation(GameCulture.Russian, "\"В вашем теле растёт ксеномит...\"");
			redemption.GetBuff("XenomiteElementalPetBuff").DisplayName.AddTranslation(GameCulture.Russian, "Домашний ксеномитный элементаль");
			redemption.GetBuff("XenomiteElementalPetBuff").Description.AddTranslation(GameCulture.Russian, "\"Миленько...\"");
			redemption.GetBuff("XenomiteHatchlingBuff").DisplayName.AddTranslation(GameCulture.Russian, "Ксеномитовый детеныш");
			redemption.GetBuff("XenomiteHatchlingBuff").Description.AddTranslation(GameCulture.Russian, "\"Милейшее инфицированное существо из всех что вы видели\"");
			redemption.GetBuff("XenomiteSkullDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Оборонительная система лаборатории");
			redemption.GetBuff("XenomiteSkullDebuff").Description.AddTranslation(GameCulture.Russian, "\"Ваше тело расщепляют волны энергии...\"");
			redemption.GetBuff("BileDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Жгучая кислота");
			redemption.GetBuff("BileDebuff").Description.AddTranslation(GameCulture.Russian, "\"Ваша защита снижена\"");
			redemption.GetBuff("BileFlaskBuff").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение оружия: рвота");
			redemption.GetBuff("BileFlaskBuff").Description.AddTranslation(GameCulture.Russian, "Атаки ближнего боя накладывают жгучую кислоту");
			redemption.GetBuff("BioweaponDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Клеточное разрушение");
			redemption.GetBuff("BioweaponDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы теряете здоровье\"");
			redemption.GetBuff("BioweaponFlaskBuff").DisplayName.AddTranslation(GameCulture.Russian, "Насыщение оружия: коррозия");
			redemption.GetBuff("BioweaponFlaskBuff").Description.AddTranslation(GameCulture.Russian, "Атаки ближнего боя накладывают клеточное разрушение");
			redemption.GetBuff("FatigueDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Усталость");
			redemption.GetBuff("FatigueDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы переполнены усталостью\"");
			redemption.GetBuff("FeverDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Лихорадка");
			redemption.GetBuff("FeverDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы чувствуете себя очень плохо.\"");
			redemption.GetBuff("HairLossDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Потеря волос");
			redemption.GetBuff("HairLossDebuff").Description.AddTranslation(GameCulture.Russian, "\"Ваши волосы пропали!\"");
			redemption.GetBuff("HeadacheDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Головная боль");
			redemption.GetBuff("HeadacheDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы чувствуете внутри вашего черепа внезапную пульсирующую боль.\"");
			redemption.GetBuff("NauseaDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Тошнота");
			redemption.GetBuff("NauseaDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы не очень хорошо себя чувствуете.\"");
			redemption.GetBuff("PanaceaBuff").DisplayName.AddTranslation(GameCulture.Russian, "Панацея");
			redemption.GetBuff("PanaceaBuff").Description.AddTranslation(GameCulture.Russian, "\"Вы чувствуете себя просто замечательно!\"");
			redemption.GetBuff("PillSickness").DisplayName.AddTranslation(GameCulture.Russian, "Послепилюльная болезнь");
			redemption.GetBuff("PillSickness").Description.AddTranslation(GameCulture.Russian, "\"Вы не очень хорошо себя чувствуете\"");
			redemption.GetBuff("RadiationDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Облучен");
			redemption.GetBuff("RadiationDebuff").Description.AddTranslation(GameCulture.Russian, "\"Вы умираете от радиации!\"");
			redemption.GetBuff("SkinBurnDebuff").DisplayName.AddTranslation(GameCulture.Russian, "Ожог кожи");
			redemption.GetBuff("SkinBurnDebuff").Description.AddTranslation(GameCulture.Russian, "\"Ваша кожа горит!\"");
		}
	}
}
