using System.Reflection;
using CalamityMod.UI.DraedonLogs;
using CalamityRuTranslate.Common;
using CalamityRuTranslate.Common.Utilities;
using CalamityRuTranslate.Core.MonoMod;
using MonoMod.Cil;

namespace CalamityRuTranslate.Mods.CalamityMod.MonoMod;

public class DraedonLogHellGUIPatch : ILPatcher
{
    public override bool AutoLoad => ModsCall.Calamity != null && TranslationHelper.IsRussianLanguage;
        
    public override MethodInfo ModifiedMethod => typeof(DraedonLogHellGUI).GetCachedMethod(nameof(DraedonLogHellGUI.GetTextByPage));

    public override ILContext.Manipulator PatchMethod { get; } = il =>
    {
        TranslationHelper.ModifyIL(il, "The Underworld is a realm with history dating back more than a millenia when the Crags were first settled, and acts as a glance into both the modern and ancient world simultaneously. Prior to my joining of Yharim’s forces, Azafure was the center of scientific advancement in this world. Explosives, firearms, smithing techniques, and even entire schools of magic have roots in the city. It is doubtless that the city has been largely aided by the fact that forging is trivial in the Underworld, along with an abundance of food due to Silva’s essence dripping down from the Abyss above. Due to this, it has prospered even with the occasional attack from Demons.", "Преисподняя - это царство с историей, которая восходит к первым поселениям на скалах более тысячелетия назад, и является симбиозом современного и древнего мира. До того, как я вступил в ряды армии Ярима, Азафур был ведущим центром научных исследований во всём мире. В этом городе были заложены основы взрывчатых веществ, огнестрельного оружия, технологий кузнечного ремесла и даже целых школ магии. Безусловно, развитию города способствовал тот факт, что кузнечное ремесло в преисподней весьма тривиально, а также изобилие пищи, получаемой за счёт сущности Сильвы, стекающей из бездны сверху. Благодаря этому город процветал, несмотря на периодические налёты демонов.");
        TranslationHelper.ModifyIL(il, "A particular being here has been the subject of my interest: a massive wall created from biological material lies in this place created many years ago by the greatest mages Azafure has to offer. It is a living being, though only just. It lacks both pain and emotion, and brings terror to all who lay their eyes upon it. It is kept protected via high security by the city, and so few aside from the Godseeker’s closest allies have had the opportunity to observe it. For as long as Azafure continues to stand, it is unlikely to ever be truly released. Yet, I do not deny that I would be fascinated to see the effects its release would have on the world.", "В этом месте меня заинтересовало одно конкретное существо: огромная стена, состоящая из биологического материала, созданная много лет назад величайшими магами Азафура. Это живое существо, хотя и в минимальной степени. Оно лишено боли и эмоций, вызывая ужас у всех, кто видел его своими глазами. Оно находится под строгой охраной города, и только близкие союзники богоискателя имели возможность его увидеть. Пока Азафур продолжает существовать, маловероятно, что это существо когда-либо будет по-настоящему освобождено. Но я не могу не признать, что меня увлекает мысль о том, какие последствия его освобождения произойдут для мира.");
        TranslationHelper.ModifyIL(il, "Azafure has not existed without consequence, of course. Any society on such a large scale leaves an ecological footprint behind. This can be seen most clearly in the sea far above the city, appropriately known as the Sulphurous Sea. Brimstone fumes became intense enough in the city that they began rising up through the Abyss via a process akin to osmosis, and eventually reached the sea. Reducing the pollution the city creates, particularly from forging, is a goal Yharim wishes for me to prioritize. I see little need in it, yet it is a field of study few in this world have delved into. I refuse to squander an opportunity for scientific breakthrough.", "Конечно, существование Азафура не прошло без последствий. Любое общество такого масштаба оставляет свой экологический след. Воздействие Азафура на окружающую среду можно наблюдать в сернистом море, находящемся высоко над городом. Интенсивность выбросов серы в городе достигла такого уровня, что они начали подниматься через бездну благодаря процессу, похожему на осмос, и, в конечном итоге, достигли моря. Основной целью, которую Ярим хотел бы, чтобы я достиг, является снижение загрязнения, создаваемого городом, особенно во время кузнечного ремесла. Я не вижу смысла в этом, но это малоисследованная область науки, в которой можно добиться прорыва. И я не хочу упустить такую возможность.");
    };
}