using System.Reflection;
using CalamityMod.UI.DraedonLogs;
using CalamityRuTranslate.Common;
using CalamityRuTranslate.Common.Utilities;
using CalamityRuTranslate.Core.MonoMod;
using MonoMod.Cil;

namespace CalamityRuTranslate.Mods.CalamityMod.MonoMod;

public class DraedonLogPlanetoidGUIPatch : ILPatcher
{
    public override bool AutoLoad => ModsCall.Calamity != null && TranslationHelper.IsRussianLanguage;
        
    public override MethodInfo ModifiedMethod => typeof(DraedonLogPlanetoidGUI).GetCachedMethod(nameof(DraedonLogPlanetoidGUI.GetTextByPage));

    public override ILContext.Manipulator PatchMethod { get; } = il =>
    {
        TranslationHelper.ModifyIL(il, "High above even the sky islands upheaved long ago lies a fascinating geological phenomenon. Though, unlike the islands, their airborne nature appears to have formed more naturally. I speculate that they formed long ago when the world was in its infancy judging by soil samples I have taken while testing high atmosphere plant growth. Perhaps these “planetoids”, as many refer to them as, formed via meteor strikes tossing matter high into the atmosphere. This would simultaneously explain many geological oddities I have found on the world’s surface.", "Высоко над небесными островами, возвышающимися уже давно, расположено захватывающее геологическое явление. Правда, в отличие от островов, их воздушная природа, по-видимому, образовалась более естественным образом. По моему мнению, эти образования возникли давным-давно, когда мир ещё только зарождался, о чем свидетельствуют образцы почвы, взятые мной при исследовании роста растений в высоких слоях атмосферы. Вероятно, эти 'планетоиды', как их называют многие, сформировались в результате метеоритных ударов, выбрасывающих материал на большую высоту в атмосфере. Это заодно объяснило бы множество геологических аномалий, которые я заметил на поверхности мира.");
        TranslationHelper.ModifyIL(il, "Travel between worlds is a fascination of mine. The planets within reasonable distance to this provide no use to me in terms of materials or study opportunities they could provide. And so, I wish to go further beyond this mere cluster of planets some day. It will likely take many more decades of technological progress, however, as travel between worlds would take years even at the maximum speed physical matter can currently go. Perhaps I will find a way to shatter this limit once this world holds my interest no longer.", "Меня очаровывают путешествия между мирами. Планеты в пределах доступного расстояния от этой не представляют для меня никакого интереса с точки зрения материалов или возможностей для исследования. И потому я желаю однажды отправиться за пределы этого скопления планет. Вероятно, потребуется ещё много десятилетий развития технологического прогресса, поскольку путешествия между мирами займут многие годы даже при максимальной скорости, которую может развить физическая материя. Возможно, я найду способ преодолеть это ограничение, когда интерес к этому миру иссякнет.");
        TranslationHelper.ModifyIL(il, "A request from Yharim has been delivered. An inquiry to create a suit of armor for the serpent that has joined his forces recently, the “Devourer of Gods” as the serpent calls himself. He is a bothersome yet fascinating being. And so, I have taken the opportunity so that I may learn more of his home dimension. Using materials from his place of origin, I have forged armor of immense size and durability yet extreme flexibility. It is certainly one of the most unique materials I have worked with and has advanced my knowledge greatly. Though, I have learned more than I expected to about the cosmic beast from this. Perhaps more than he wished for me to.", "Я получил запрос от Ярима на создание доспехов для змея, который недавно присоединился к его армии. Змей называет себя 'Пожирателем богов'. Хоть он и досаждает мне, но он невероятно интересен для меня. Я решил воспользоваться этой возможностью и узнать больше о его измерении. Используя материалы из его родного мира, я создал доспехи огромных размеров, которые отличаются необычайной прочностью и удивительной гибкостью. Это, безусловно, один из самых уникальных материалов, с которым мне когда-либо доводилось работать, и он значительно расширил мои знания. Я узнал о космическом звере гораздо больше, чем ожидал. Наверное, даже больше, чем Ярим хотел бы, чтобы я знал.");
    };
}