using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.ShadowsOfAbaddon.Items
{
	internal class SacredToolsItemName
	{
		public static void Setup()
		{
			Items();
		}
		
		private static void Items()
		{
			Mod sacredTools = ModLoader.GetMod("SacredTools");
			
			sacredTools.GetItem("ArcticFur").DisplayName.AddTranslation(GameCulture.Russian, "Шерсть Дикри");
			sacredTools.GetItem("AsthralCell").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая топливная ячейка");
			sacredTools.GetItem("AsthraltiteChunks").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовые осколки");
			sacredTools.GetItem("BirdFeather").DisplayName.AddTranslation(GameCulture.Russian, "Белое перо");
			sacredTools.GetItem("BlackSun").DisplayName.AddTranslation(GameCulture.Russian, "Фрагмент чёрного солнца");
			sacredTools.GetItem("Blazefury").DisplayName.AddTranslation(GameCulture.Russian, "Пламенное неистовство");
			sacredTools.GetItem("BlazePowder").DisplayName.AddTranslation(GameCulture.Russian, "Огненный порошок");
			sacredTools.GetItem("BlazeRod").DisplayName.AddTranslation(GameCulture.Russian, "Огненный стержень");
			sacredTools.GetItem("Blightbone").DisplayName.AddTranslation(GameCulture.Russian, "Мрачнокость");
			sacredTools.GetItem("DarkMist").DisplayName.AddTranslation(GameCulture.Russian, "Элемент погибели");
			sacredTools.GetItem("DesertCrystal").DisplayName.AddTranslation(GameCulture.Russian, "Пустынный кварц");
			sacredTools.GetItem("DraconiumAlloy").DisplayName.AddTranslation(GameCulture.Russian, "Дракониевый сплав");
			sacredTools.GetItem("EmberOfOmen").DisplayName.AddTranslation(GameCulture.Russian, "Зола предвестия");
			sacredTools.GetItem("Enduflora").DisplayName.AddTranslation(GameCulture.Russian, "Стойкоцвет");
			sacredTools.GetItem("ErosionSample").DisplayName.AddTranslation(GameCulture.Russian, "Образец эрозии");
			sacredTools.GetItem("FieryFin").DisplayName.AddTranslation(GameCulture.Russian, "Огнегребень");
			sacredTools.GetItem("FlareEssentia").DisplayName.AddTranslation(GameCulture.Russian, "Эссенция яркого пламени");
			sacredTools.GetItem("ForgottenCrown").DisplayName.AddTranslation(GameCulture.Russian, "Забытая корона");
			sacredTools.GetItem("ForgottenCrystalBattery").DisplayName.AddTranslation(GameCulture.Russian, "Забытая кристальная батарея");
			sacredTools.GetItem("ForgottenTablet").DisplayName.AddTranslation(GameCulture.Russian, "Забытая скрижаль");
			sacredTools.GetItem("FragmentBlight").DisplayName.AddTranslation(GameCulture.Russian, "Фрагмент запустения");
			sacredTools.GetItem("FragmentHatred").DisplayName.AddTranslation(GameCulture.Russian, "Фрагмент ненависти");
			sacredTools.GetItem("FragmentNova").DisplayName.AddTranslation(GameCulture.Russian, "Квазарный фрагмент");
			sacredTools.GetItem("FrigidOoze").DisplayName.AddTranslation(GameCulture.Russian, "Замороженная грязь");
			sacredTools.GetItem("GoldenFeather").DisplayName.AddTranslation(GameCulture.Russian, "Перо королевской гарпии");
			sacredTools.GetItem("GoldNugget").DisplayName.AddTranslation(GameCulture.Russian, "Золотой самородок");
			sacredTools.GetItem("HarpyDrop").DisplayName.AddTranslation(GameCulture.Russian, "Перо великой гарпии");
			sacredTools.GetItem("Illumifern").DisplayName.AddTranslation(GameCulture.Russian, "Светящийся папоротник");
			sacredTools.GetItem("JellyNebula").DisplayName.AddTranslation(GameCulture.Russian, "Желе туманности");
			sacredTools.GetItem("JellyQuasar").DisplayName.AddTranslation(GameCulture.Russian, "Квазарное желе");
			sacredTools.GetItem("JellySolar").DisplayName.AddTranslation(GameCulture.Russian, "Солнечное желе");
			sacredTools.GetItem("JellyStardust").DisplayName.AddTranslation(GameCulture.Russian, "Желе звёздной пыли");
			sacredTools.GetItem("JellyVortex").DisplayName.AddTranslation(GameCulture.Russian, "Желе вихря");
			sacredTools.GetItem("LifeEmber").DisplayName.AddTranslation(GameCulture.Russian, "Зола жизни");
			sacredTools.GetItem("LihzahrdBar").DisplayName.AddTranslation(GameCulture.Russian, "Слиток Ящуров");
			sacredTools.GetItem("LunaticEssence").DisplayName.AddTranslation(GameCulture.Russian, "Светящаяся эссенция");
			sacredTools.GetItem("LunaVenom").DisplayName.AddTranslation(GameCulture.Russian, "Яд Луны");
			sacredTools.GetItem("ManaFruit").DisplayName.AddTranslation(GameCulture.Russian, "Фрукт маны");
			sacredTools.GetItem("MarstechChip").DisplayName.AddTranslation(GameCulture.Russian, "Марсианский чип");
			sacredTools.GetItem("MoonstoneBar").DisplayName.AddTranslation(GameCulture.Russian, "Тиридиевый слиток");
			sacredTools.GetItem("OblivionBar").DisplayName.AddTranslation(GameCulture.Russian, "Слиток забвения");
			sacredTools.GetItem("PandolarMuns").DisplayName.AddTranslation(GameCulture.Russian, "Маленький займ в 100 платиновых монет");
			sacredTools.GetItem("PrimordialRune").DisplayName.AddTranslation(GameCulture.Russian, "Извечная руна");
			sacredTools.GetItem("PumpkinFlame").DisplayName.AddTranslation(GameCulture.Russian, "Пламя ужаса");
			sacredTools.GetItem("RefinedBismuth").DisplayName.AddTranslation(GameCulture.Russian, "Обработанный висмут");
			sacredTools.GetItem("RefinedLapis").DisplayName.AddTranslation(GameCulture.Russian, "Обработанный лазурит");
			sacredTools.GetItem("SnowBar").DisplayName.AddTranslation(GameCulture.Russian, "Иллиновый слиток");
			sacredTools.GetItem("SoulOfLuminite").DisplayName.AddTranslation(GameCulture.Russian, "Древняя искра");
			sacredTools.GetItem("SoulOfTide").DisplayName.AddTranslation(GameCulture.Russian, "Клетки мутанта");
			sacredTools.GetItem("SpaceJunk").DisplayName.AddTranslation(GameCulture.Russian, "Космический мусор");
			sacredTools.GetItem("TrueGem").DisplayName.AddTranslation(GameCulture.Russian, "Инфузионный кристалл");
			sacredTools.GetItem("TrueOblivionBar").DisplayName.AddTranslation(GameCulture.Russian, "Следы хаоса");
			sacredTools.GetItem("Tumblestick").DisplayName.AddTranslation(GameCulture.Russian, "Перекати-палка");
			sacredTools.GetItem("VenomiteBar").DisplayName.AddTranslation(GameCulture.Russian, "Отравленный слиток");
			sacredTools.GetItem("VenomSample").DisplayName.AddTranslation(GameCulture.Russian, "Образец яда");
			sacredTools.GetItem("VialFlame").DisplayName.AddTranslation(GameCulture.Russian, "Пробирка с горящей кровью");
			sacredTools.GetItem("Welkinbell").DisplayName.AddTranslation(GameCulture.Russian, "Небоцвет");
			sacredTools.GetItem("MementoMori").DisplayName.AddTranslation(GameCulture.Russian, "Мементо Мори");
			sacredTools.GetItem("NebulaSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать туманности");
			sacredTools.GetItem("QuasarSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать квазара");
			sacredTools.GetItem("SolarSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать солнечной вспышки");
			sacredTools.GetItem("StardustSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать звёздной пыли");
			sacredTools.GetItem("VortexSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать вихря");
			sacredTools.GetItem("EerieChest").DisplayName.AddTranslation(GameCulture.Russian, "Зловещий нагрудник");
			sacredTools.GetItem("EerieHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Зловещий шлем");
			sacredTools.GetItem("EerieLegs").DisplayName.AddTranslation(GameCulture.Russian, "Зловещие поножи");
			sacredTools.GetItem("LapisChest").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый нагрудник");
			sacredTools.GetItem("LapisHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый шлем");
			sacredTools.GetItem("LapisLegs").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовые поножи");
			sacredTools.GetItem("NovaBreastplate").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник квазара");
			sacredTools.GetItem("NovaHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Шлем квазара");
			sacredTools.GetItem("NovaLegs").DisplayName.AddTranslation(GameCulture.Russian, "Поножи квазара");
			sacredTools.GetItem("PrairieChest").DisplayName.AddTranslation(GameCulture.Russian, "Браслеты прерий");
			sacredTools.GetItem("PrairieHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Головной убор из перьев прерий");
			sacredTools.GetItem("PrairieLegs").DisplayName.AddTranslation(GameCulture.Russian, "Набедренная повязка прерий");
			sacredTools.GetItem("AsthralChest").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый нагрудник");
			sacredTools.GetItem("AsthralLegs").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая мантия");
			sacredTools.GetItem("AsthralMage").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый капюшон");
			sacredTools.GetItem("AsthralMelee").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый шлем");
			sacredTools.GetItem("AsthralRanged").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовое забрало");
			sacredTools.GetItem("AsthralSummon").DisplayName.AddTranslation(GameCulture.Russian, "Азралтитовая маска");
			sacredTools.GetItem("AsthralThrown").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый обтекатель");
			sacredTools.GetItem("BismuthChest").DisplayName.AddTranslation(GameCulture.Russian, "Висмутовый нагрудник");
			sacredTools.GetItem("BismuthHelm").DisplayName.AddTranslation(GameCulture.Russian, "Висмутовый шлем");
			sacredTools.GetItem("BismuthLegs").DisplayName.AddTranslation(GameCulture.Russian, "Висмутовые поножи");
			sacredTools.GetItem("BlightChest").DisplayName.AddTranslation(GameCulture.Russian, "Мрачнокостяной нагрудник");
			sacredTools.GetItem("BlightLegs").DisplayName.AddTranslation(GameCulture.Russian, "Мрачнокостяные поножи");
			sacredTools.GetItem("BlightMask").DisplayName.AddTranslation(GameCulture.Russian, "Мрачнокостяная маска");
			sacredTools.GetItem("CairoCrusaderFaulds").DisplayName.AddTranslation(GameCulture.Russian, "Латная юбка каирского крестоносца");
			sacredTools.GetItem("CairoCrusaderRobe").DisplayName.AddTranslation(GameCulture.Russian, "Мантия каирского крестоносца");
			sacredTools.GetItem("CairoCrusaderTurban").DisplayName.AddTranslation(GameCulture.Russian, "Тюрбан каирского крестоносца");
			sacredTools.GetItem("FrosthunterBoots").DisplayName.AddTranslation(GameCulture.Russian, "Ботинки морозного охотника");
			sacredTools.GetItem("FrosthunterHeaddress").DisplayName.AddTranslation(GameCulture.Russian, "Головной убор морозного охотника");
			sacredTools.GetItem("FrosthunterWrappings").DisplayName.AddTranslation(GameCulture.Russian, "Куртка морозного охотника");
			sacredTools.GetItem("FlariumChest").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник яркого пламени");
			sacredTools.GetItem("FlariumCowl").DisplayName.AddTranslation(GameCulture.Russian, "Обтекатель яркого пламени");
			sacredTools.GetItem("FlariumCrown").DisplayName.AddTranslation(GameCulture.Russian, "Корона яркого пламени");
			sacredTools.GetItem("FlariumHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Шлем яркого пламени");
			sacredTools.GetItem("FlariumHood").DisplayName.AddTranslation(GameCulture.Russian, "Капюшон яркого пламени");
			sacredTools.GetItem("FlariumLeggings").DisplayName.AddTranslation(GameCulture.Russian, "Наколенники яркого пламени");
			sacredTools.GetItem("FlariumMask").DisplayName.AddTranslation(GameCulture.Russian, "Наголовник яркого пламени");
			sacredTools.GetItem("ExodusChest").DisplayName.AddTranslation(GameCulture.Russian, "Кольчуга угасающего света");
			sacredTools.GetItem("ExodusHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Шлем угасающего света");
			sacredTools.GetItem("ExodusLegs").DisplayName.AddTranslation(GameCulture.Russian, "Поножи угасающего света");
			sacredTools.GetItem("LuxDustMagic").DisplayName.AddTranslation(GameCulture.Russian, "Пыль осколка света");
			sacredTools.GetItem("LuxDustMelee").DisplayName.AddTranslation(GameCulture.Russian, "Пыль осколка света");
			sacredTools.GetItem("LuxDustRanged").DisplayName.AddTranslation(GameCulture.Russian, "Пыль осколка света");
			sacredTools.GetItem("LuxDustSummon").DisplayName.AddTranslation(GameCulture.Russian, "Пыль осколка света");
			sacredTools.GetItem("LuxDustThrown").DisplayName.AddTranslation(GameCulture.Russian, "Пыль осколка света");
			sacredTools.GetItem("NubaChest").DisplayName.AddTranslation(GameCulture.Russian, "Одеяние ученика туманности");
			sacredTools.GetItem("NubaHood").DisplayName.AddTranslation(GameCulture.Russian, "Капюшон ученика туманности");
			sacredTools.GetItem("NubaRobe").DisplayName.AddTranslation(GameCulture.Russian, "Мантия ученика туманности");
			sacredTools.GetItem("FallenPrinceBoots").DisplayName.AddTranslation(GameCulture.Russian, "Ботинки падшего принца");
			sacredTools.GetItem("FallenPrinceChest").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник падшего принца");
			sacredTools.GetItem("FallenPrinceHelm").DisplayName.AddTranslation(GameCulture.Russian, "Шлем падшего принца");
			sacredTools.GetItem("BlazingBruteHelm").DisplayName.AddTranslation(GameCulture.Russian, "Рыцарский шлем пылающего дикаря");
			sacredTools.GetItem("BlazingBruteLegs").DisplayName.AddTranslation(GameCulture.Russian, "Сабатоны пылающего дикаря");
			sacredTools.GetItem("BlazingBrutePlate").DisplayName.AddTranslation(GameCulture.Russian, "Латы пылающего дикаря");
			sacredTools.GetItem("StellarPriestChest").DisplayName.AddTranslation(GameCulture.Russian, "Одеяние звездного жреца");
			sacredTools.GetItem("StellarPriestHead").DisplayName.AddTranslation(GameCulture.Russian, "Венец звездного жреца");
			sacredTools.GetItem("StellarPriestLegs").DisplayName.AddTranslation(GameCulture.Russian, "мантия звездного жреца");
			sacredTools.GetItem("VortexCommanderGreaves").DisplayName.AddTranslation(GameCulture.Russian, "Поножи звездного капитана");
			sacredTools.GetItem("VortexCommanderHat").DisplayName.AddTranslation(GameCulture.Russian, "Обтекатель звездного капитана");
			sacredTools.GetItem("VortexCommanderSuit").DisplayName.AddTranslation(GameCulture.Russian, "Костюм звездного капитана");
			sacredTools.GetItem("MarstechHelm").DisplayName.AddTranslation(GameCulture.Russian, "Рыцарский техношлем марсиан");
			sacredTools.GetItem("MarstechLegs").DisplayName.AddTranslation(GameCulture.Russian, "Технопоножи марсиан");
			sacredTools.GetItem("MarstechPlate").DisplayName.AddTranslation(GameCulture.Russian, "Технолаты марсиан");
			sacredTools.GetItem("AraneasMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Аранеи");
			sacredTools.GetItem("DecreeMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Дикри");
			sacredTools.GetItem("DustiteMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Пылида");
			sacredTools.GetItem("ElvenEars").DisplayName.AddTranslation(GameCulture.Russian, "Уши эльфа");
			sacredTools.GetItem("ErazorMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Ирейзора");
			sacredTools.GetItem("FlamingPumpkinMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска пылающей тыквы");
			sacredTools.GetItem("HarpyMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска великолепной гарпии");
			sacredTools.GetItem("HarpyMask2").DisplayName.AddTranslation(GameCulture.Russian, "Маска Рейнар");
			sacredTools.GetItem("KagomeMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Kagome");
			sacredTools.GetItem("NihilusMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Нигилуса");
			sacredTools.GetItem("NovanielMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Нованиэля");
			sacredTools.GetItem("NubaMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Небу");
			sacredTools.GetItem("OblivionMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Абаддона");
			sacredTools.GetItem("PrimordiaMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Ипостаси");
			sacredTools.GetItem("RalnekMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Ралнека");
			sacredTools.GetItem("SerialMask").DisplayName.AddTranslation(GameCulture.Russian, "Серийная маска");
			sacredTools.GetItem("SerpentMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска змея");
			sacredTools.GetItem("SolariusMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Солярия");
			sacredTools.GetItem("VoxaMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Вихрины");
			sacredTools.GetItem("VoidChest").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник пустотного защитника");
			sacredTools.GetItem("VoidChestOffense").DisplayName.AddTranslation(GameCulture.Russian, "Чешуйчатые доспехи пустотного защитника");
			sacredTools.GetItem("VoidHelm").DisplayName.AddTranslation(GameCulture.Russian, "Шлем пустотного защитника");
			sacredTools.GetItem("VoidLegs").DisplayName.AddTranslation(GameCulture.Russian, "Поножи пустотного защитника");
			sacredTools.GetItem("PumpkinArmor").DisplayName.AddTranslation(GameCulture.Russian, "Ужаснопламенные латы");
			sacredTools.GetItem("PumpkinBoots").DisplayName.AddTranslation(GameCulture.Russian, "Ужаснопламенные ботинки");
			sacredTools.GetItem("PumpkinMask").DisplayName.AddTranslation(GameCulture.Russian, "Ужаснопламенная маска");
			sacredTools.GetItem("SpaceJunkBody").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник из космического мусора");
			sacredTools.GetItem("SpaceJunkHelm").DisplayName.AddTranslation(GameCulture.Russian, "Шлем из космического мусора");
			sacredTools.GetItem("SpaceJunkLegs").DisplayName.AddTranslation(GameCulture.Russian, "Ботинки из космического мусора");
			sacredTools.GetItem("CommanderHat").DisplayName.AddTranslation(GameCulture.Russian, "Командирская шляпа");
			sacredTools.GetItem("DanHair").DisplayName.AddTranslation(GameCulture.Russian, "Мистическая прическа");
			sacredTools.GetItem("DariusChest").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник Darius");
			sacredTools.GetItem("DariusCrown").DisplayName.AddTranslation(GameCulture.Russian, "Священная корона Darius");
			sacredTools.GetItem("DariusHair").DisplayName.AddTranslation(GameCulture.Russian, "Парик Darius");
			sacredTools.GetItem("DariusImpersonation").DisplayName.AddTranslation(GameCulture.Russian, "Воплощение Darius");
			sacredTools.GetItem("DariusLegs").DisplayName.AddTranslation(GameCulture.Russian, "Мантия Darius");
			sacredTools.GetItem("DragonChest").DisplayName.AddTranslation(GameCulture.Russian, "Резные чешуйчатые доспехи Ivor");
			sacredTools.GetItem("DragonHead").DisplayName.AddTranslation(GameCulture.Russian, "Отрубленная голова Ivor");
			sacredTools.GetItem("DragonLegs").DisplayName.AddTranslation(GameCulture.Russian, "Оторванные лапы Ivor");
			sacredTools.GetItem("EgoChest").DisplayName.AddTranslation(GameCulture.Russian, "Нагрудник Shocked");
			sacredTools.GetItem("EgoHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Святая корона Shocked");
			sacredTools.GetItem("EgoLegs").DisplayName.AddTranslation(GameCulture.Russian, "Ботинки Shocked");
			sacredTools.GetItem("GiraffeHead").DisplayName.AddTranslation(GameCulture.Russian, "Маска жирафа");
			sacredTools.GetItem("GoteMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска Alexis");
			sacredTools.GetItem("IndiChest").DisplayName.AddTranslation(GameCulture.Russian, "Рубашка Indi");
			sacredTools.GetItem("IndiHead").DisplayName.AddTranslation(GameCulture.Russian, "Маска Indi");
			sacredTools.GetItem("IndiLegs").DisplayName.AddTranslation(GameCulture.Russian, "Лосины Indi");
			sacredTools.GetItem("JensenChest").DisplayName.AddTranslation(GameCulture.Russian, "Перьевой костюм великолепной гарпии");
			sacredTools.GetItem("JensenTalons").DisplayName.AddTranslation(GameCulture.Russian, "Когти великолепной гарпии");
			sacredTools.GetItem("KoopaBoots").DisplayName.AddTranslation(GameCulture.Russian, "Ботинки Koopa");
			sacredTools.GetItem("KoopaHelm").DisplayName.AddTranslation(GameCulture.Russian, "Рыцарский шлем Koopa");
			sacredTools.GetItem("KoopaShell").DisplayName.AddTranslation(GameCulture.Russian, "Панцирь Koopa");
			sacredTools.GetItem("LCSBody").DisplayName.AddTranslation(GameCulture.Russian, "Фрак LordCakeSpy");
			sacredTools.GetItem("LCSHead").DisplayName.AddTranslation(GameCulture.Russian, "Маска LordCakeSpy");
			sacredTools.GetItem("LCSLegs").DisplayName.AddTranslation(GameCulture.Russian, "Джинсы LordCakeSpy");
			sacredTools.GetItem("LuxordHair").DisplayName.AddTranslation(GameCulture.Russian, "Прическа азартного игрока");
			sacredTools.GetItem("NanoplasmaticBreastplate").DisplayName.AddTranslation(GameCulture.Russian, "Наноплазматический нагрудник");
			sacredTools.GetItem("NanoplasmaticHood").DisplayName.AddTranslation(GameCulture.Russian, "Наноплазматический капюшон");
			sacredTools.GetItem("NanoplasmaticLeggings").DisplayName.AddTranslation(GameCulture.Russian, "Наноплазматические лосины");
			sacredTools.GetItem("PandolarMask").DisplayName.AddTranslation(GameCulture.Russian, "Маска пандоларца");
			sacredTools.GetItem("PandolarPaws").DisplayName.AddTranslation(GameCulture.Russian, "Лапы пандоларца");
			sacredTools.GetItem("RiellCape").DisplayName.AddTranslation(GameCulture.Russian, "Шарф Riell");
			sacredTools.GetItem("RossoArm").DisplayName.AddTranslation(GameCulture.Russian, "Зараженные руки Rosso");
			sacredTools.GetItem("SaitamaBoots").DisplayName.AddTranslation(GameCulture.Russian, "Геройские лосины");
			sacredTools.GetItem("SaitamaShirt").DisplayName.AddTranslation(GameCulture.Russian, "Геройская рубашка");
			sacredTools.GetItem("SeraphChest").DisplayName.AddTranslation(GameCulture.Russian, "Латное одеяние серафима смерти");
			sacredTools.GetItem("SeraphHair").DisplayName.AddTranslation(GameCulture.Russian, "Волосы серафима смерти");
			sacredTools.GetItem("SeraphLegs").DisplayName.AddTranslation(GameCulture.Russian, "Защитная мантия серафима смерти");
			sacredTools.GetItem("SerpentTail").DisplayName.AddTranslation(GameCulture.Russian, "Змеиный хвост");
			sacredTools.GetItem("SpletChest").DisplayName.AddTranslation(GameCulture.Russian, "Пиджак Splet");
			sacredTools.GetItem("SpletHead").DisplayName.AddTranslation(GameCulture.Russian, "Маска Splet");
			sacredTools.GetItem("SpletLegs").DisplayName.AddTranslation(GameCulture.Russian, "Джинсы Splet");
			sacredTools.GetItem("SumeBody").DisplayName.AddTranslation(GameCulture.Russian, "Рубашка Sumenora");
			sacredTools.GetItem("SumeHead").DisplayName.AddTranslation(GameCulture.Russian, "Маска Sumenora");
			sacredTools.GetItem("SumeLegs").DisplayName.AddTranslation(GameCulture.Russian, "Лосины Sumenora");
			sacredTools.GetItem("TreeMask").DisplayName.AddTranslation(GameCulture.Russian, "Древесная маска");
			sacredTools.GetItem("VanitasChestplate").DisplayName.AddTranslation(GameCulture.Russian, "Костюм Vanitas");
			sacredTools.GetItem("VanitasHelmet").DisplayName.AddTranslation(GameCulture.Russian, "Шлем Vanitas");
			sacredTools.GetItem("VanitasLeggings").DisplayName.AddTranslation(GameCulture.Russian, "Поножи Vanitas");
			sacredTools.GetItem("XIIICoat").DisplayName.AddTranslation(GameCulture.Russian, "Чёрная куртка");
			sacredTools.GetItem("XIIIHair").DisplayName.AddTranslation(GameCulture.Russian, "Парик путешественника во времени");
			sacredTools.GetItem("XIIIHood").DisplayName.AddTranslation(GameCulture.Russian, "Чёрный капюшон");
			sacredTools.GetItem("YamiRobe").DisplayName.AddTranslation(GameCulture.Russian, "Зараженная мантия");
			sacredTools.GetItem("AsthraltiteHeadset").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовые наушники");
			sacredTools.GetItem("BasicHeadset").DisplayName.AddTranslation(GameCulture.Russian, "Обычные наушники");
			sacredTools.GetItem("FlariumHeadset").DisplayName.AddTranslation(GameCulture.Russian, "Наушники яркого пламени");
			sacredTools.GetItem("LunarianHeadset").DisplayName.AddTranslation(GameCulture.Russian, "Кристаллические наушники");
			sacredTools.GetItem("OblivionHeadset").DisplayName.AddTranslation(GameCulture.Russian, "Наушники забвения");
			sacredTools.GetItem("VulcanChest").DisplayName.AddTranslation(GameCulture.Russian, "Одеяние вулканического жнеца");
			sacredTools.GetItem("VulcanHelm").DisplayName.AddTranslation(GameCulture.Russian, "Шлем вулканического жнеца");
			sacredTools.GetItem("VulcanLegs").DisplayName.AddTranslation(GameCulture.Russian, "Мантия вулканического жнеца");
			sacredTools.GetItem("AraneasBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("AsthralBrickBox").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая Brick Containment Unit");
			sacredTools.GetItem("BruteBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("ChallengerBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("DecreeBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("HarpyBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("HarpyBag2").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("KeyToTheHeart").DisplayName.AddTranslation(GameCulture.Russian, "Ключ к сердцу");
			sacredTools.GetItem("LunarBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("OblivionBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("PrimordiaBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("PumpkinBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("SerpentBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("SpookboiBag").DisplayName.AddTranslation(GameCulture.Russian, "Мешок с сокровищами");
			sacredTools.GetItem("AlexisCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Alexis)");
			sacredTools.GetItem("BGhostCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (BGhost)");
			sacredTools.GetItem("CrimCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Crimsoneye)");
			sacredTools.GetItem("DanCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Dan Yami)");
			sacredTools.GetItem("DexaCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Dexavior)");
			sacredTools.GetItem("IndiCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Indi)");
			sacredTools.GetItem("KirbyCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Flashkirby)");
			sacredTools.GetItem("KoopaCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Koopahunter)");
			sacredTools.GetItem("LCSCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (LCS)");
			sacredTools.GetItem("NickyCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Nicky)");
			sacredTools.GetItem("RiellCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Riell Raito)");
			sacredTools.GetItem("ShockCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (ShockedHorizon)");
			sacredTools.GetItem("SkyreCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Skyre Ventes)");
			sacredTools.GetItem("SpletCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Splet)");
			sacredTools.GetItem("SumeCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Sumenora)");
			sacredTools.GetItem("VikCube").DisplayName.AddTranslation(GameCulture.Russian, "Куб снаряжения (Darius)");
			sacredTools.GetItem("BlazingSerpentBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя пылающего змия");
			sacredTools.GetItem("CauldronBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя кислотного котла");
			sacredTools.GetItem("CrusherBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя драконического дробителя");
			sacredTools.GetItem("FestiveFuriaBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя праздничной фурии");
			sacredTools.GetItem("FrigidJellyBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя леденящей медузы");
			sacredTools.GetItem("FrigidSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя леденящего слизня");
			sacredTools.GetItem("FrigidSpiritBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя леденящего духа");
			sacredTools.GetItem("FuriaBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя фурии");
			sacredTools.GetItem("FuriousSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя свирепого слизня");
			sacredTools.GetItem("GoldSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя золотого слизня");
			sacredTools.GetItem("LancerBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя тёмного копейщика");
			sacredTools.GetItem("NebulaSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя слизня туманности");
			sacredTools.GetItem("NestWardenBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя смотрителя гнезда");
			sacredTools.GetItem("NightmareWraithBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя кошмарного духа");
			sacredTools.GetItem("ObserverBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя немого наблюдателя");
			sacredTools.GetItem("QuasarSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя квазарного слизня");
			sacredTools.GetItem("ShrubBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя пылающего кустарника");
			sacredTools.GetItem("SolarSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя солнечного слизня");
			sacredTools.GetItem("SpiderlingBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя паучка");
			sacredTools.GetItem("SpiritBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя пламенного духа");
			sacredTools.GetItem("StalkerBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя призрачного преследователя");
			sacredTools.GetItem("StardustSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя слизня звёздной пыли");
			sacredTools.GetItem("VenomStalkerBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя ядовитого преследователя");
			sacredTools.GetItem("VortexSlimeBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя вихревого слизня");
			sacredTools.GetItem("WingedBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя крылатой фурии");
			sacredTools.GetItem("UpgradeGem0").DisplayName.AddTranslation(GameCulture.Russian, "Пустой мистический камень");
			sacredTools.GetItem("UpgradeGem1").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 1 уровня");
			sacredTools.GetItem("UpgradeGem10").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 10 уровня");
			sacredTools.GetItem("UpgradeGem11").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 11 уровня");
			sacredTools.GetItem("UpgradeGem2").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 2 уровня");
			sacredTools.GetItem("UpgradeGem3").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 3 уровня");
			sacredTools.GetItem("UpgradeGem4").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 4 уровня");
			sacredTools.GetItem("UpgradeGem5").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 5 уровня");
			sacredTools.GetItem("UpgradeGem6").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 6 уровня");
			sacredTools.GetItem("UpgradeGem7").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 7 уровня");
			sacredTools.GetItem("UpgradeGem8").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 8 уровня");
			sacredTools.GetItem("UpgradeGem9").DisplayName.AddTranslation(GameCulture.Russian, "Мистический камень 9 уровня");
			sacredTools.GetItem("AwakenedJustice").DisplayName.AddTranslation(GameCulture.Russian, "Правосудие");
			sacredTools.GetItem("CatSock").DisplayName.AddTranslation(GameCulture.Russian, "Носок с котом");
			sacredTools.GetItem("CrimLash").DisplayName.AddTranslation(GameCulture.Russian, "Багряный змей");
			sacredTools.GetItem("CrimsonVeins").DisplayName.AddTranslation(GameCulture.Russian, "Багровые вены");
			sacredTools.GetItem("DragonslayerPandolarra").DisplayName.AddTranslation(GameCulture.Russian, "Пандоларский драконоубийца");
			sacredTools.GetItem("DreadwoodBow").DisplayName.AddTranslation(GameCulture.Russian, "Анагматис");
			sacredTools.GetItem("Eredhun").DisplayName.AddTranslation(GameCulture.Russian, "Эредун");
			sacredTools.GetItem("Exterdaeviam").DisplayName.AddTranslation(GameCulture.Russian, "Экстердевиам");
			sacredTools.GetItem("GavGun").DisplayName.AddTranslation(GameCulture.Russian, "Пушка Gav");
			sacredTools.GetItem("Ghrimorhas").DisplayName.AddTranslation(GameCulture.Russian, "Гриморхас 2.0");
			sacredTools.GetItem("HalacandrianToolkit").DisplayName.AddTranslation(GameCulture.Russian, "Набор халакандрианеца");
			sacredTools.GetItem("KoopaHammer").DisplayName.AddTranslation(GameCulture.Russian, "Уничтожитель панцирей Koopa");
			sacredTools.GetItem("LCSynth").DisplayName.AddTranslation(GameCulture.Russian, "LCSинтезатор");
			sacredTools.GetItem("MidnightBlade").DisplayName.AddTranslation(GameCulture.Russian, "Полночь");
			sacredTools.GetItem("NvidiaGeforce").DisplayName.AddTranslation(GameCulture.Russian, "Nvidia GeForce GTX 1090 ti");
			sacredTools.GetItem("PlasmaCleaver").DisplayName.AddTranslation(GameCulture.Russian, "Наноплазматический тесак");
			sacredTools.GetItem("PootisSpencer").DisplayName.AddTranslation(GameCulture.Russian, "Путис Спенсер");
			sacredTools.GetItem("ShadowflareMidnight").DisplayName.AddTranslation(GameCulture.Russian, "Полночь тёмного пламени");
			sacredTools.GetItem("SumeCore").DisplayName.AddTranslation(GameCulture.Russian, "Ядро душ");
			sacredTools.GetItem("SupremeCrystal").DisplayName.AddTranslation(GameCulture.Russian, "Высший кристалл");
			sacredTools.GetItem("UnobtainiumHook").DisplayName.AddTranslation(GameCulture.Russian, "Унобтаниевый крюк");
			sacredTools.GetItem("AbaddonHeart").DisplayName.AddTranslation(GameCulture.Russian, "Стеклянное сердце");
			sacredTools.GetItem("AraghurHeart").DisplayName.AddTranslation(GameCulture.Russian, "Стеклянное сердце");
			sacredTools.GetItem("ErazorHeart").DisplayName.AddTranslation(GameCulture.Russian, "Стеклянное сердце");
			sacredTools.GetItem("LunarianHeart").DisplayName.AddTranslation(GameCulture.Russian, "Стеклянное сердце");
			sacredTools.GetItem("MooshCart").DisplayName.AddTranslation(GameCulture.Russian, "Муухоморная вагонетка");
			sacredTools.GetItem("RottenDrumstick").DisplayName.AddTranslation(GameCulture.Russian, "Гнилая голень");
			sacredTools.GetItem("SerpentSceptre").DisplayName.AddTranslation(GameCulture.Russian, "Змииный Скипетр");
			sacredTools.GetItem("AbaddonStatue").DisplayName.AddTranslation(GameCulture.Russian, "Статуя Абаддона");
			sacredTools.GetItem("AntheeFountain").DisplayName.AddTranslation(GameCulture.Russian, "Фонтан воспоминаний");
			sacredTools.GetItem("AraneasTrophy").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Аранеи");
			sacredTools.GetItem("BendyCutout").DisplayName.AddTranslation(GameCulture.Russian, "Картонка Бенди");
			sacredTools.GetItem("BoneThrone").DisplayName.AddTranslation(GameCulture.Russian, "Костяной трон");
			sacredTools.GetItem("BricksEmber").DisplayName.AddTranslation(GameCulture.Russian, "Тлеющий кирпич");
			sacredTools.GetItem("BricksThermal").DisplayName.AddTranslation(GameCulture.Russian, "Горячие кирпичи");
			sacredTools.GetItem("CatLamp").DisplayName.AddTranslation(GameCulture.Russian, "Котолампа");
			sacredTools.GetItem("CelestialBox").DisplayName.AddTranslation(GameCulture.Russian, "Музыкальная шкатулка (Звездное Правосудие)");
			sacredTools.GetItem("Chalk").DisplayName.AddTranslation(GameCulture.Russian, "Мел");
			sacredTools.GetItem("Decoration_Bulb").DisplayName.AddTranslation(GameCulture.Russian, "Консервированный бутон");
			sacredTools.GetItem("EmberBrickWall").DisplayName.AddTranslation(GameCulture.Russian, "Стена тлеющего кирпича");
			sacredTools.GetItem("EndufloraSeeds").DisplayName.AddTranslation(GameCulture.Russian, "Семена стойкоцвета");
			sacredTools.GetItem("FishronPlush").DisplayName.AddTranslation(GameCulture.Russian, "Плюшевая игрушка рыброна");
			sacredTools.GetItem("FlamePlatform").DisplayName.AddTranslation(GameCulture.Russian, "Платформа из тлеющей древесины");
			sacredTools.GetItem("FlameRack").DisplayName.AddTranslation(GameCulture.Russian, "Горячий базальт");
			sacredTools.GetItem("FlameWall").DisplayName.AddTranslation(GameCulture.Russian, "Стена из горячего базальта");
			sacredTools.GetItem("FlameWood").DisplayName.AddTranslation(GameCulture.Russian, "Тлеющая кора");
			sacredTools.GetItem("FlamingRack").DisplayName.AddTranslation(GameCulture.Russian, "Тлеющий камень");
			sacredTools.GetItem("FlareTorch").DisplayName.AddTranslation(GameCulture.Russian, "Факел яркого пламени");
			sacredTools.GetItem("FlariumAnvil").DisplayName.AddTranslation(GameCulture.Russian, "Наковальня яркого пламени");
			sacredTools.GetItem("FlariumBed").DisplayName.AddTranslation(GameCulture.Russian, "Кровать яркого пламени");
			sacredTools.GetItem("FlariumBookshelf").DisplayName.AddTranslation(GameCulture.Russian, "Книжный шкаф яркого пламени");
			sacredTools.GetItem("FlariumCandelabra").DisplayName.AddTranslation(GameCulture.Russian, "Канделябр яркого пламени");
			sacredTools.GetItem("FlariumCandleItem").DisplayName.AddTranslation(GameCulture.Russian, "Свеча яркого пламени");
			sacredTools.GetItem("FlariumChairItem").DisplayName.AddTranslation(GameCulture.Russian, "Стул яркого пламени");
			sacredTools.GetItem("FlariumChandelierItem").DisplayName.AddTranslation(GameCulture.Russian, "Люстра яркого пламени");
			sacredTools.GetItem("FlariumChestItem").DisplayName.AddTranslation(GameCulture.Russian, "Сундук яркого пламени");
			sacredTools.GetItem("FlariumCrate").DisplayName.AddTranslation(GameCulture.Russian, "Ящик яркого пламени");
			sacredTools.GetItem("FlariumDoor").DisplayName.AddTranslation(GameCulture.Russian, "Дверь яркого пламени");
			sacredTools.GetItem("FlariumDresser").DisplayName.AddTranslation(GameCulture.Russian, "Комод яркого пламени");
			sacredTools.GetItem("FlariumForge").DisplayName.AddTranslation(GameCulture.Russian, "Кузня яркого пламени");
			sacredTools.GetItem("FlariumItem").DisplayName.AddTranslation(GameCulture.Russian, "Кристалл яркого пламени");
			sacredTools.GetItem("FlariumLampItem").DisplayName.AddTranslation(GameCulture.Russian, "Лампа яркого пламени");
			sacredTools.GetItem("FlariumPlatform").DisplayName.AddTranslation(GameCulture.Russian, "Платформа яркого пламени");
			sacredTools.GetItem("FlariumTableItem").DisplayName.AddTranslation(GameCulture.Russian, "Стол яркого пламени");
			sacredTools.GetItem("FlariumWall").DisplayName.AddTranslation(GameCulture.Russian, "Стена из тлеющей коры");
			sacredTools.GetItem("FlariumWorkbench").DisplayName.AddTranslation(GameCulture.Russian, "Верстак яркого пламени");
			sacredTools.GetItem("FrostbitePanel").DisplayName.AddTranslation(GameCulture.Russian, "Иллиновая панель");
			sacredTools.GetItem("FrostbiteWall").DisplayName.AddTranslation(GameCulture.Russian, "Иллиновая стена");
			sacredTools.GetItem("FruitLantern").DisplayName.AddTranslation(GameCulture.Russian, "Лампа фрукта жизни");
			sacredTools.GetItem("FStatue").DisplayName.AddTranslation(GameCulture.Russian, "Статуя перевернутой 'F'");
			sacredTools.GetItem("FuryMonolith").DisplayName.AddTranslation(GameCulture.Russian, "Знамя FuryForged");
			sacredTools.GetItem("HardenedScorchedSand").DisplayName.AddTranslation(GameCulture.Russian, "Блок затвердевшего выжженного песка");
			sacredTools.GetItem("IllumifernSeeds").DisplayName.AddTranslation(GameCulture.Russian, "Семена иллюзорного папоротника");
			sacredTools.GetItem("KHMonolith").DisplayName.AddTranslation(GameCulture.Russian, "Монолит сердца");
			sacredTools.GetItem("LunarAltar").DisplayName.AddTranslation(GameCulture.Russian, "Тиридиумовый инфузер");
			sacredTools.GetItem("LunarVaultItem").DisplayName.AddTranslation(GameCulture.Russian, "Тиридиумовое хранилише");
			sacredTools.GetItem("ManaFruitPlaceable").DisplayName.AddTranslation(GameCulture.Russian, "Фрукт маны (Декоративный)");
			sacredTools.GetItem("OblivionAltarItem").DisplayName.AddTranslation(GameCulture.Russian, "Алтарь адского камня");
			sacredTools.GetItem("OblivionBrick").DisplayName.AddTranslation(GameCulture.Russian, "Забвенный кирпич");
			sacredTools.GetItem("OblivionForgeItem").DisplayName.AddTranslation(GameCulture.Russian, "Кузня забвения");
			sacredTools.GetItem("OblivionOre").DisplayName.AddTranslation(GameCulture.Russian, "Осколок забвения");
			sacredTools.GetItem("PandolarSigil").DisplayName.AddTranslation(GameCulture.Russian, "Пандоларская печать");
			sacredTools.GetItem("PrimordiaTrophy").DisplayName.AddTranslation(GameCulture.Russian, "Трофей испостаси");
			sacredTools.GetItem("QuasarFragmentBlock").DisplayName.AddTranslation(GameCulture.Russian, "Блок квазарных фрагментов");
			sacredTools.GetItem("QuasarMonolith").DisplayName.AddTranslation(GameCulture.Russian, "Монолит квазара");
			sacredTools.GetItem("RainDrum").DisplayName.AddTranslation(GameCulture.Russian, "Барабан дождя");
			sacredTools.GetItem("RawBismuth").DisplayName.AddTranslation(GameCulture.Russian, "Необработанный висмут");
			sacredTools.GetItem("RawLapis").DisplayName.AddTranslation(GameCulture.Russian, "Необработанный лазурит");
			sacredTools.GetItem("RoyalThrone").DisplayName.AddTranslation(GameCulture.Russian, "Королевский трон");
			sacredTools.GetItem("ScorchedSand").DisplayName.AddTranslation(GameCulture.Russian, "Блок выжженного песка");
			sacredTools.GetItem("ScorchedSandstone").DisplayName.AddTranslation(GameCulture.Russian, "Выжженный песчаниковый блок");
			sacredTools.GetItem("StormMonolith").DisplayName.AddTranslation(GameCulture.Russian, "Монолит шторма");
			sacredTools.GetItem("TheFlamingBeanbag").DisplayName.AddTranslation(GameCulture.Russian, "Кресло-мешок яркого пламени");
			sacredTools.GetItem("ThermalBrickWall").DisplayName.AddTranslation(GameCulture.Russian, "Стена из горячего кирпича");
			sacredTools.GetItem("TrophyDecree").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Дикри");
			sacredTools.GetItem("TrophyErazor").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Ирейзора");
			sacredTools.GetItem("TrophyHarpy").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Дженсен");
			sacredTools.GetItem("TrophyHarpy2").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Рейнар");
			sacredTools.GetItem("TrophyLunar").DisplayName.AddTranslation(GameCulture.Russian, "Статуя справедливости");
			sacredTools.GetItem("TrophyLunarians").DisplayName.AddTranslation(GameCulture.Russian, "Трофей потерянных близнецов");
			sacredTools.GetItem("TrophyNihilus").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Нигилуса");
			sacredTools.GetItem("TrophyOblivion").DisplayName.AddTranslation(GameCulture.Russian, "Трофей Абаддона");
			sacredTools.GetItem("TrophyPumpkin").DisplayName.AddTranslation(GameCulture.Russian, "Трофей пылающей тыквы");
			sacredTools.GetItem("TrophySerpent_Lame").DisplayName.AddTranslation(GameCulture.Russian, "Трофей змея");
			sacredTools.GetItem("VenomiteOre").DisplayName.AddTranslation(GameCulture.Russian, "Ядовитая руда");
			sacredTools.GetItem("WeaverChest").DisplayName.AddTranslation(GameCulture.Russian, "Сундук ткача");
			sacredTools.GetItem("WeaverChestLocked").DisplayName.AddTranslation(GameCulture.Russian, "Закрытый сундук ткача");
			sacredTools.GetItem("WeaverEgg").DisplayName.AddTranslation(GameCulture.Russian, "Яйцо ткача");
			sacredTools.GetItem("WeaverEggAraneas").DisplayName.AddTranslation(GameCulture.Russian, "Статуя Аранеи");
			sacredTools.GetItem("WeaverRocks").DisplayName.AddTranslation(GameCulture.Russian, "Кирпичи ткача");
			sacredTools.GetItem("WeaverStalactitesBig").DisplayName.AddTranslation(GameCulture.Russian, "Большие паучьи сталактиты");
			sacredTools.GetItem("WeaverStalactitesSmall").DisplayName.AddTranslation(GameCulture.Russian, "Малые паучьи сталактиты");
			sacredTools.GetItem("WeaverStalagmitesBig").DisplayName.AddTranslation(GameCulture.Russian, "Большие паучьи сталагмиты");
			sacredTools.GetItem("WeaverStalagmitesSmall").DisplayName.AddTranslation(GameCulture.Russian, "Малые паучьи сталагмиты");
			sacredTools.GetItem("Weaverstone").DisplayName.AddTranslation(GameCulture.Russian, "Паукокамень");
			sacredTools.GetItem("WeaverWall").DisplayName.AddTranslation(GameCulture.Russian, "Паукостена");
			sacredTools.GetItem("WelkinbellSeeds").DisplayName.AddTranslation(GameCulture.Russian, "Семена небесноцвета");
			sacredTools.GetItem("AsthralBed").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая кровать");
			sacredTools.GetItem("AsthralBookshelf").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый книжный шкаф");
			sacredTools.GetItem("AsthralCandelabra").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый канделябр");
			sacredTools.GetItem("AsthralCandle").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая свеча");
			sacredTools.GetItem("AsthralChair").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый стул");
			sacredTools.GetItem("AsthralChandelier").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая люстра");
			sacredTools.GetItem("AsthralChestItem").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый сундук");
			sacredTools.GetItem("AsthralDoor").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая дверь");
			sacredTools.GetItem("AsthralDresser").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый комод");
			sacredTools.GetItem("AsthralLamp").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая лампа");
			sacredTools.GetItem("AsthralLantern").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый фонарь");
			sacredTools.GetItem("AsthralPlatform").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая платформа");
			sacredTools.GetItem("AsthralSofa").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый диван");
			sacredTools.GetItem("AsthralTable").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая стол");
			sacredTools.GetItem("AsthralWall").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая стена");
			sacredTools.GetItem("AsthralWorkbench").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый верстак");
			sacredTools.GetItem("BricksAsthral").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый кирпич");
			sacredTools.GetItem("PumpboiObelisk").DisplayName.AddTranslation(GameCulture.Russian, "Обелиск ужаса");
			sacredTools.GetItem("AbaddonPainting").DisplayName.AddTranslation(GameCulture.Russian, "Взгляд отчаяния");
			sacredTools.GetItem("Daryl").DisplayName.AddTranslation(GameCulture.Russian, "Дэррил");
			sacredTools.GetItem("Deepfreeze").DisplayName.AddTranslation(GameCulture.Russian, "Холодные шипы");
			sacredTools.GetItem("GodOfTerraria").DisplayName.AddTranslation(GameCulture.Russian, "Бог террарии");
			sacredTools.GetItem("Kappa").DisplayName.AddTranslation(GameCulture.Russian, "Каппа");
			sacredTools.GetItem("KipSmug").DisplayName.AddTranslation(GameCulture.Russian, "KipSmug");
			sacredTools.GetItem("LunaticCultistPainting").DisplayName.AddTranslation(GameCulture.Russian, "Проповедник культа");
			sacredTools.GetItem("MoodPainting").DisplayName.AddTranslation(GameCulture.Russian, "Цвет настроения: тыква");
			sacredTools.GetItem("Polarius").DisplayName.AddTranslation(GameCulture.Russian, "Полярная звезда");
			sacredTools.GetItem("StrangeMap").DisplayName.AddTranslation(GameCulture.Russian, "Странная карта");
			sacredTools.GetItem("Warmth").DisplayName.AddTranslation(GameCulture.Russian, "Выжженный ландшафт");
			sacredTools.GetItem("ShrineBrick").DisplayName.AddTranslation(GameCulture.Russian, "Кирпич святилища");
			sacredTools.GetItem("ShrineWall").DisplayName.AddTranslation(GameCulture.Russian, "Стена святилища");
			sacredTools.GetItem("AsthralHeal").DisplayName.AddTranslation(GameCulture.Russian, "Демонический эликсир лечения");
			sacredTools.GetItem("AsthralMana").DisplayName.AddTranslation(GameCulture.Russian, "Демонический эликсир маны");
			sacredTools.GetItem("BurnCure").DisplayName.AddTranslation(GameCulture.Russian, "Зелье вспышки");
			sacredTools.GetItem("CleanseSpray").DisplayName.AddTranslation(GameCulture.Russian, "Вычищающий раствор");
			sacredTools.GetItem("CommandingPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье командира");
			sacredTools.GetItem("DawnPotion").DisplayName.AddTranslation(GameCulture.Russian, "Рассветное зелье");
			sacredTools.GetItem("DraconiumSkinPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье дракониумовой кожи");
			sacredTools.GetItem("DuskPotion").DisplayName.AddTranslation(GameCulture.Russian, "Закатное зелье");
			sacredTools.GetItem("FlareSolution").DisplayName.AddTranslation(GameCulture.Russian, "Выжигающий раствор");
			sacredTools.GetItem("InstantHeal").DisplayName.AddTranslation(GameCulture.Russian, "Супер-дупер мега невероятно невообразимо большое лечебное зелье");
			sacredTools.GetItem("MegaHealingPotion").DisplayName.AddTranslation(GameCulture.Russian, "Невероятное лечебное зелье");
			sacredTools.GetItem("MegaManaPotion").DisplayName.AddTranslation(GameCulture.Russian, "Невероятное зелье маны");
			sacredTools.GetItem("Milk").DisplayName.AddTranslation(GameCulture.Russian, "Молоко");
			sacredTools.GetItem("MoonlightPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье лунного света");
			sacredTools.GetItem("NightmarePotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье кошмарного топлива");
			sacredTools.GetItem("RobustMusclePotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье крепкой мускулатуры");
			sacredTools.GetItem("SandPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье защиты от ветра");
			sacredTools.GetItem("SmolderingSpicyCurry").DisplayName.AddTranslation(GameCulture.Russian, "Обжигающе острое карри");
			sacredTools.GetItem("ThrownPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье ниндзя фокусировки");
			sacredTools.GetItem("TowerSurmountPotion").DisplayName.AddTranslation(GameCulture.Russian, "Зелье преодоления башни");
			sacredTools.GetItem("AhristaElixir").DisplayName.AddTranslation(GameCulture.Russian, "Эликсир Ахристы");
			sacredTools.GetItem("FlariumFlurry").DisplayName.AddTranslation(GameCulture.Russian, "Прорыв яркого пламени");
			sacredTools.GetItem("h").DisplayName.AddTranslation(GameCulture.Russian, "h");
			sacredTools.GetItem("KrysteaElixir").DisplayName.AddTranslation(GameCulture.Russian, "Эликсир Кристеи");
			sacredTools.GetItem("NumberOne").DisplayName.AddTranslation(GameCulture.Russian, "Number One");
			sacredTools.GetItem("SeriousSyrusianSyrup").DisplayName.AddTranslation(GameCulture.Russian, "Сироп серьезного Сирусианца");
			sacredTools.GetItem("AntiRainDrum").DisplayName.AddTranslation(GameCulture.Russian, "Барабан анти-дождя");
			sacredTools.GetItem("AsthralHammer").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый молот");
			sacredTools.GetItem("AsthralPick").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая киркопил");
			sacredTools.GetItem("AsthraltiteHook").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый механизм передвижения");
			sacredTools.GetItem("BanHammer").DisplayName.AddTranslation(GameCulture.Russian, "Молот Бана");
			sacredTools.GetItem("CorruptedSigil").DisplayName.AddTranslation(GameCulture.Russian, "Печать зараженного");
			sacredTools.GetItem("DecreeSummon").DisplayName.AddTranslation(GameCulture.Russian, "Морозная руна");
			sacredTools.GetItem("DragonDrill").DisplayName.AddTranslation(GameCulture.Russian, "Драконий бур");
			sacredTools.GetItem("ErazorTestItem").DisplayName.AddTranslation(GameCulture.Russian, "?????");
			sacredTools.GetItem("ExitumRod").DisplayName.AddTranslation(GameCulture.Russian, "Заклинатель света");
			sacredTools.GetItem("FieryCatcher").DisplayName.AddTranslation(GameCulture.Russian, "Огненный ловец");
			sacredTools.GetItem("FlariumHamaxe").DisplayName.AddTranslation(GameCulture.Russian, "Молотопор яркого пламени");
			sacredTools.GetItem("FlariumHook").DisplayName.AddTranslation(GameCulture.Russian, "Змеиная хватка");
			sacredTools.GetItem("FlariumPick").DisplayName.AddTranslation(GameCulture.Russian, "Кирка яркого пламени");
			sacredTools.GetItem("FRFGenItem").DisplayName.AddTranslation(GameCulture.Russian, "????? 0.2");
			sacredTools.GetItem("HarpySummon").DisplayName.AddTranslation(GameCulture.Russian, "Перьевой талисман");
			sacredTools.GetItem("HarpySummon2").DisplayName.AddTranslation(GameCulture.Russian, "Королевская роза");
			sacredTools.GetItem("HeirsAuthority").DisplayName.AddTranslation(GameCulture.Russian, "Власть наследника");
			sacredTools.GetItem("IDontExist").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая пластина");
			sacredTools.GetItem("LapisPick").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовая кирка");
			sacredTools.GetItem("LunarCoin").DisplayName.AddTranslation(GameCulture.Russian, "Лунодовый монеты");
			sacredTools.GetItem("ManaPickaxe").DisplayName.AddTranslation(GameCulture.Russian, "Лунный экскаватор");
			sacredTools.GetItem("MatterManipulator").DisplayName.AddTranslation(GameCulture.Russian, "Манипулятор материи");
			sacredTools.GetItem("MoonEmblem").DisplayName.AddTranslation(GameCulture.Russian, "Эмблема Сорана");
			sacredTools.GetItem("MysteriousGem").DisplayName.AddTranslation(GameCulture.Russian, "Мистический самоцвет");
			sacredTools.GetItem("NovaHamaxe").DisplayName.AddTranslation(GameCulture.Russian, "Молотопор квазара");
			sacredTools.GetItem("NovaPickaxe").DisplayName.AddTranslation(GameCulture.Russian, "Кирка квазара");
			sacredTools.GetItem("OblivionMiner").DisplayName.AddTranslation(GameCulture.Russian, "Копатель забвения");
			sacredTools.GetItem("PandolarPick").DisplayName.AddTranslation(GameCulture.Russian, "Кирка пандолара");
			sacredTools.GetItem("PhantomClock").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный часы");
			sacredTools.GetItem("PigmanBanner").DisplayName.AddTranslation(GameCulture.Russian, "Знамя армии пиглинов");
			sacredTools.GetItem("PrimordiaSummon").DisplayName.AddTranslation(GameCulture.Russian, "Забытая эмблема");
			sacredTools.GetItem("PumpkinLantern").DisplayName.AddTranslation(GameCulture.Russian, "Ужасная лампа");
			sacredTools.GetItem("SandstormMedallion").DisplayName.AddTranslation(GameCulture.Russian, "Медальон песчаной бури");
			sacredTools.GetItem("SerpentSummon").DisplayName.AddTranslation(GameCulture.Russian, "Излучатель теплового потока");
			sacredTools.GetItem("ShadowWrathSummonItem").DisplayName.AddTranslation(GameCulture.Russian, "Ловец кошмаров");
			sacredTools.GetItem("TabletFragment").DisplayName.AddTranslation(GameCulture.Russian, "Фрагмент реликвии");
			sacredTools.GetItem("TabletOfWeaponMastery").DisplayName.AddTranslation(GameCulture.Russian, "Табличка Вознесения");
			sacredTools.GetItem("TestItem2").DisplayName.AddTranslation(GameCulture.Russian, "????? 69.420");
			sacredTools.GetItem("WeaverKey").DisplayName.AddTranslation(GameCulture.Russian, "Ключ Ткача");
			sacredTools.GetItem("AccursedMolotov").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый Молотов");
			sacredTools.GetItem("Bloodbath").DisplayName.AddTranslation(GameCulture.Russian, "Кровавая Баня");
			sacredTools.GetItem("Bloodstain").DisplayName.AddTranslation(GameCulture.Russian, "Кровавое пятно");
			sacredTools.GetItem("ChromaUltima").DisplayName.AddTranslation(GameCulture.Russian, "Хрома Ультима");
			sacredTools.GetItem("CursedFlameMolotov").DisplayName.AddTranslation(GameCulture.Russian, "Молотов проклятого пламени");
			sacredTools.GetItem("DeathJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Падение ночи");
			sacredTools.GetItem("DecionSpear").DisplayName.AddTranslation(GameCulture.Russian, "Двойной Разряд");
			sacredTools.GetItem("DualRedLightsaber").DisplayName.AddTranslation(GameCulture.Russian, "Красный двойной световой меч");
			sacredTools.GetItem("EerieCane").DisplayName.AddTranslation(GameCulture.Russian, "Зловещая трость");
			sacredTools.GetItem("ElementalFlinger").DisplayName.AddTranslation(GameCulture.Russian, "Выпускатель элементов");
			sacredTools.GetItem("EmperorScepter").DisplayName.AddTranslation(GameCulture.Russian, "Скипетр Императора");
			sacredTools.GetItem("EnergyRifle").DisplayName.AddTranslation(GameCulture.Russian, "Энергетическая винтовка");
			sacredTools.GetItem("Ethereal").DisplayName.AddTranslation(GameCulture.Russian, "Эфемерность");
			sacredTools.GetItem("FairGame").DisplayName.AddTranslation(GameCulture.Russian, "Честная игра");
			sacredTools.GetItem("FangJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Клык");
			sacredTools.GetItem("FrostBeam").DisplayName.AddTranslation(GameCulture.Russian, "Морозная коса");
			sacredTools.GetItem("GoldDoorHandle").DisplayName.AddTranslation(GameCulture.Russian, "Золотая честь");
			sacredTools.GetItem("GoldJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Золотое метательное копье");
			sacredTools.GetItem("GospelOfDismay").DisplayName.AddTranslation(GameCulture.Russian, "Проповедь смятения");
			sacredTools.GetItem("GraniteEradicator").DisplayName.AddTranslation(GameCulture.Russian, "Гранитовый уничтожитель");
			sacredTools.GetItem("GrassJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Кустарник");
			sacredTools.GetItem("Hellebarde").DisplayName.AddTranslation(GameCulture.Russian, "Воспламенившийся");
			sacredTools.GetItem("HornetNeedle").DisplayName.AddTranslation(GameCulture.Russian, "Игла");
			sacredTools.GetItem("HorrificAssault").DisplayName.AddTranslation(GameCulture.Russian, "Ужасная атака");
			sacredTools.GetItem("IchorMolotov").DisplayName.AddTranslation(GameCulture.Russian, "Ихоровый молотов");
			sacredTools.GetItem("LapisBow").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый лук");
			sacredTools.GetItem("LapisJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Течение");
			sacredTools.GetItem("LapisStaff").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритовый посох");
			sacredTools.GetItem("LapisSword").DisplayName.AddTranslation(GameCulture.Russian, "Лазуритный меч");
			sacredTools.GetItem("MoonEdgedColdFront").DisplayName.AddTranslation(GameCulture.Russian, "Луной окаймленный, Холодный фронт");
			sacredTools.GetItem("MoonEdgedPandolarra").DisplayName.AddTranslation(GameCulture.Russian, "Луной окаймленный, Пандоларр");
			sacredTools.GetItem("Needler").DisplayName.AddTranslation(GameCulture.Russian, "Игольник");
			sacredTools.GetItem("NeedlerCorruption").DisplayName.AddTranslation(GameCulture.Russian, "Зараженный игольник");
			sacredTools.GetItem("NeedlerCrimson").DisplayName.AddTranslation(GameCulture.Russian, "Окровавленный игольник");
			sacredTools.GetItem("NeedlerFlare").DisplayName.AddTranslation(GameCulture.Russian, "Кактилерия");
			sacredTools.GetItem("NeedlerHallow").DisplayName.AddTranslation(GameCulture.Russian, "Кактическая винтовка");
			sacredTools.GetItem("NovaknifePack").DisplayName.AddTranslation(GameCulture.Russian, "Кунай квазара");
			sacredTools.GetItem("NovaLance").DisplayName.AddTranslation(GameCulture.Russian, "Квантовый разрушитель");
			sacredTools.GetItem("OrbFlayer").DisplayName.AddTranslation(GameCulture.Russian, "Сфера живодера");
			sacredTools.GetItem("OrbitalDestruction").DisplayName.AddTranslation(GameCulture.Russian, "Орбитальное уничтожение");
			sacredTools.GetItem("OversizedFang").DisplayName.AddTranslation(GameCulture.Russian, "Клык XL");
			sacredTools.GetItem("Pandolance").DisplayName.AddTranslation(GameCulture.Russian, "Пандалебарда");
			sacredTools.GetItem("PandolarBow").DisplayName.AddTranslation(GameCulture.Russian, "Холодный фронт");
			sacredTools.GetItem("Pandolarra").DisplayName.AddTranslation(GameCulture.Russian, "Пандоларр");
			sacredTools.GetItem("PandolarRepeater").DisplayName.AddTranslation(GameCulture.Russian, "Истинный Холодный фронт");
			sacredTools.GetItem("PandolarYoyo").DisplayName.AddTranslation(GameCulture.Russian, "Пандолариан");
			sacredTools.GetItem("PlatinumJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Платиновое метательное копье");
			sacredTools.GetItem("RetinalMeltdown").DisplayName.AddTranslation(GameCulture.Russian, "Плавление сетчатки");
			sacredTools.GetItem("SatelliteStaff").DisplayName.AddTranslation(GameCulture.Russian, "Спутниковый передатчик");
			sacredTools.GetItem("ShadowJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Тень");
			sacredTools.GetItem("Skelebowne").DisplayName.AddTranslation(GameCulture.Russian, "Скелестрел");
			sacredTools.GetItem("SpearOfJustice").DisplayName.AddTranslation(GameCulture.Russian, "Морознодитовое копье");
			sacredTools.GetItem("SpineRattler").DisplayName.AddTranslation(GameCulture.Russian, "Костяная гремучая змея");
			sacredTools.GetItem("Sunbender").DisplayName.AddTranslation(GameCulture.Russian, "Солнечные клещи");
			sacredTools.GetItem("TerraLance").DisplayName.AddTranslation(GameCulture.Russian, "Великое Терракопье");
			sacredTools.GetItem("TheAegean").DisplayName.AddTranslation(GameCulture.Russian, "Эгейское море");
			sacredTools.GetItem("ThrowingCross").DisplayName.AddTranslation(GameCulture.Russian, "Святой обезглавливатель");
			sacredTools.GetItem("Tonbogiri").DisplayName.AddTranslation(GameCulture.Russian, "'Нихонго'");
			sacredTools.GetItem("TrueDecapitator").DisplayName.AddTranslation(GameCulture.Russian, "Истинный святой обезглавливатель");
			sacredTools.GetItem("TrueMoonEdgedPandolarra").DisplayName.AddTranslation(GameCulture.Russian, "Небесами окаймленный, Пандолар");
			sacredTools.GetItem("TrueNightSpear").DisplayName.AddTranslation(GameCulture.Russian, "Истинное падение ночи");
			sacredTools.GetItem("TruePandolarra").DisplayName.AddTranslation(GameCulture.Russian, "Истинный пандолар");
			sacredTools.GetItem("VeridianMight").DisplayName.AddTranslation(GameCulture.Russian, "Мощь веридиан");
			sacredTools.GetItem("Whirlpool").DisplayName.AddTranslation(GameCulture.Russian, "Омут");
			sacredTools.GetItem("WoodJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Деревянное копье");
			sacredTools.GetItem("AsthralArrow").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая стрела");
			sacredTools.GetItem("AsthralArrowPack").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый набор стрел");
			sacredTools.GetItem("AsthralBullet").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая пуля");
			sacredTools.GetItem("AsthralBulletPack").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый набор пуль");
			sacredTools.GetItem("AsthralBurst").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая рокета");
			sacredTools.GetItem("AsthralBurstPack").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый набор ракет");
			sacredTools.GetItem("FlariumArrow").DisplayName.AddTranslation(GameCulture.Russian, "Стрела яркого пламени");
			sacredTools.GetItem("FlariumBullet").DisplayName.AddTranslation(GameCulture.Russian, "Пуля яркого пламени");
			sacredTools.GetItem("FlariumRocket").DisplayName.AddTranslation(GameCulture.Russian, "Ракета яркого пламени");
			sacredTools.GetItem("OblivionArrow").DisplayName.AddTranslation(GameCulture.Russian, "Стрела забвения");
			sacredTools.GetItem("OrbAdamantite").DisplayName.AddTranslation(GameCulture.Russian, "Адамантитовая сфера");
			sacredTools.GetItem("OrbChlorophyte").DisplayName.AddTranslation(GameCulture.Russian, "Хлорофитовая сфера");
			sacredTools.GetItem("OrbCobalt").DisplayName.AddTranslation(GameCulture.Russian, "Кобальтовая сфера");
			sacredTools.GetItem("OrbMarstech").DisplayName.AddTranslation(GameCulture.Russian, "Молниеносная сфера");
			sacredTools.GetItem("OrbMythril").DisplayName.AddTranslation(GameCulture.Russian, "Мифриловая сфера");
			sacredTools.GetItem("OrbOrichalcum").DisplayName.AddTranslation(GameCulture.Russian, "Орихалковая сфера");
			sacredTools.GetItem("OrbPalladium").DisplayName.AddTranslation(GameCulture.Russian, "Палладиевая сфера");
			sacredTools.GetItem("OrbSpectral").DisplayName.AddTranslation(GameCulture.Russian, "Спектральная сфера");
			sacredTools.GetItem("OrbTitanium").DisplayName.AddTranslation(GameCulture.Russian, "Титановая сфера");
			sacredTools.GetItem("OrbVenomite").DisplayName.AddTranslation(GameCulture.Russian, "Ядовитая сфера");
			sacredTools.GetItem("PhaseArrow").DisplayName.AddTranslation(GameCulture.Russian, "Лунная стрела");
			sacredTools.GetItem("PhaseArrowInfinite").DisplayName.AddTranslation(GameCulture.Russian, "Бесконечная лунная стрела");
			sacredTools.GetItem("PhaseBullet").DisplayName.AddTranslation(GameCulture.Russian, "Лунная пуля");
			sacredTools.GetItem("PhaseBulletInfinite").DisplayName.AddTranslation(GameCulture.Russian, "Бесконечная лунная пуля");
			sacredTools.GetItem("ShadowBullet").DisplayName.AddTranslation(GameCulture.Russian, "Черная пуля");
			sacredTools.GetItem("AsthralBlade").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый клинок");
			sacredTools.GetItem("AsthralBow").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый разломовый лук");
			sacredTools.GetItem("AsthralBurster").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый кристальный взрыватель");
			sacredTools.GetItem("AsthralDroneStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох азралититового дрона");
			sacredTools.GetItem("AsthralGun").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовая фазовая винтовка");
			sacredTools.GetItem("AsthralKnives").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовые ножи");
			sacredTools.GetItem("AsthralPartisan").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый лучевой протазан");
			sacredTools.GetItem("AsthralSaber").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый цепные лезвия");
			sacredTools.GetItem("AsthralStaff").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый посох");
			sacredTools.GetItem("AsthraltiteIncinerator").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый сжигатель");
			sacredTools.GetItem("AsthralTome").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый том");
			sacredTools.GetItem("AsthralYoyo").DisplayName.AddTranslation(GameCulture.Russian, "Сумерки предателя");
			sacredTools.GetItem("Phaselash").DisplayName.AddTranslation(GameCulture.Russian, "Азралититовый хлыст");
			sacredTools.GetItem("BismuthChakram").DisplayName.AddTranslation(GameCulture.Russian, "Висутовый чакрам");
			sacredTools.GetItem("RainbowHandgun").DisplayName.AddTranslation(GameCulture.Russian, "Радужный пистолет");
			sacredTools.GetItem("TheCluster").DisplayName.AddTranslation(GameCulture.Russian, "Скопление");
			sacredTools.GetItem("Evisceration").DisplayName.AddTranslation(GameCulture.Russian, "Эвисцерация");
			sacredTools.GetItem("FrigidFusillade").DisplayName.AddTranslation(GameCulture.Russian, "Морозный залп");
			sacredTools.GetItem("FrostGlobeStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох морозной ауры");
			sacredTools.GetItem("IceclawShuriken").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной сюрикен");
			sacredTools.GetItem("OmegaStrongbow").DisplayName.AddTranslation(GameCulture.Russian, "Омега лук");
			sacredTools.GetItem("RoseChakram").DisplayName.AddTranslation(GameCulture.Russian, "Чакрам-роза");
			sacredTools.GetItem("SpookGrenade").DisplayName.AddTranslation(GameCulture.Russian, "Граната бездны");
			sacredTools.GetItem("SpookGun").DisplayName.AddTranslation(GameCulture.Russian, "Отчаяние");
			sacredTools.GetItem("SpookStaff").DisplayName.AddTranslation(GameCulture.Russian, "Сжигатель душ");
			sacredTools.GetItem("SpookSword").DisplayName.AddTranslation(GameCulture.Russian, "Пламя порицания");
			sacredTools.GetItem("SpookTome").DisplayName.AddTranslation(GameCulture.Russian, "Тьма");
			sacredTools.GetItem("FlameBeamFish").DisplayName.AddTranslation(GameCulture.Russian, "Огненная лучерыба");
			sacredTools.GetItem("FlareFlail").DisplayName.AddTranslation(GameCulture.Russian, "Сияющая вспышка");
			sacredTools.GetItem("FlariumBow").DisplayName.AddTranslation(GameCulture.Russian, "Коготь феникса");
			sacredTools.GetItem("FlariumDisc").DisplayName.AddTranslation(GameCulture.Russian, "Горящий диск");
			sacredTools.GetItem("FlariumFlask").DisplayName.AddTranslation(GameCulture.Russian, "Коррозийная колба");
			sacredTools.GetItem("FlariumJavelin").DisplayName.AddTranslation(GameCulture.Russian, "Яростный пронзатель");
			sacredTools.GetItem("FlariumRifle").DisplayName.AddTranslation(GameCulture.Russian, "Термогенезис");
			sacredTools.GetItem("FlariumRocketLauncher").DisplayName.AddTranslation(GameCulture.Russian, "Окислитель");
			sacredTools.GetItem("FlariumRod").DisplayName.AddTranslation(GameCulture.Russian, "Огненный зов");
			sacredTools.GetItem("FlariumSceptre").DisplayName.AddTranslation(GameCulture.Russian, "Эсканделете");
			sacredTools.GetItem("FlariumStaff").DisplayName.AddTranslation(GameCulture.Russian, "Золяной клык");
			sacredTools.GetItem("FlariumSword").DisplayName.AddTranslation(GameCulture.Russian, "Двуручный меч яркого пламени");
			sacredTools.GetItem("FlariumTome").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв ярости");
			sacredTools.GetItem("FlariumYoyo").DisplayName.AddTranslation(GameCulture.Russian, "Пламя бездны");
			sacredTools.GetItem("SerpentChain").DisplayName.AddTranslation(GameCulture.Russian, "Цепь огненного змея");
			sacredTools.GetItem("Featherbook").DisplayName.AddTranslation(GameCulture.Russian, "Том гарпий");
			sacredTools.GetItem("Feathergun").DisplayName.AddTranslation(GameCulture.Russian, "Пушка гарпий");
			sacredTools.GetItem("Featherstaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох гарпий");
			sacredTools.GetItem("Featherstorm").DisplayName.AddTranslation(GameCulture.Russian, "Шокирователь гарпий");
			sacredTools.GetItem("Feathersword").DisplayName.AddTranslation(GameCulture.Russian, "Клинок гарпий");
			sacredTools.GetItem("HarpyStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох королевских гарпий");
			sacredTools.GetItem("RedBook").DisplayName.AddTranslation(GameCulture.Russian, "Том королевских гарпий");
			sacredTools.GetItem("RedGun").DisplayName.AddTranslation(GameCulture.Russian, "Пушка королевских гарпий");
			sacredTools.GetItem("RedStorm").DisplayName.AddTranslation(GameCulture.Russian, "Шокирователь королевских гарпий");
			sacredTools.GetItem("RedSword").DisplayName.AddTranslation(GameCulture.Russian, "Нарезатель королевских гарпий");
			sacredTools.GetItem("AethersBlasphemy").DisplayName.AddTranslation(GameCulture.Russian, "Райское богохульство");
			sacredTools.GetItem("BluebelloftheHeavens").DisplayName.AddTranslation(GameCulture.Russian, "Колокольчики небес");
			sacredTools.GetItem("DeathsGarden").DisplayName.AddTranslation(GameCulture.Russian, "Смертельный сад");
			sacredTools.GetItem("DevilsRose").DisplayName.AddTranslation(GameCulture.Russian, "Роза дьявола");
			sacredTools.GetItem("Duskpalm").DisplayName.AddTranslation(GameCulture.Russian, "Сумеречная пальма");
			sacredTools.GetItem("Duskshine").DisplayName.AddTranslation(GameCulture.Russian, "Сияние сумерек");
			sacredTools.GetItem("Everbloom").DisplayName.AddTranslation(GameCulture.Russian, "Вечноцвет");
			sacredTools.GetItem("Everglow").DisplayName.AddTranslation(GameCulture.Russian, "Вечносвет");
			sacredTools.GetItem("GleamingRoot").DisplayName.AddTranslation(GameCulture.Russian, "Сверкающий корень");
			sacredTools.GetItem("ImpactVine").DisplayName.AddTranslation(GameCulture.Russian, "Ударная лоза");
			sacredTools.GetItem("NaturesBetrayer").DisplayName.AddTranslation(GameCulture.Russian, "Предатель природы");
			sacredTools.GetItem("PolarBramble").DisplayName.AddTranslation(GameCulture.Russian, "Полярная ежевика");
			sacredTools.GetItem("Seapalm").DisplayName.AddTranslation(GameCulture.Russian, "Морская пальма");
			sacredTools.GetItem("AsteroidShower").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритный дождь");
			sacredTools.GetItem("BlindJustice").DisplayName.AddTranslation(GameCulture.Russian, "Слепое правосудие - прототип 1");
			sacredTools.GetItem("CosmicCloudBracelet").DisplayName.AddTranslation(GameCulture.Russian, "Браслет из космического облака");
			sacredTools.GetItem("CosmicDesolation").DisplayName.AddTranslation(GameCulture.Russian, "Космическое опустошение");
			sacredTools.GetItem("DolphinGun").DisplayName.AddTranslation(GameCulture.Russian, "Г.Д.У.");
			sacredTools.GetItem("GalaxyScepter").DisplayName.AddTranslation(GameCulture.Russian, "Галактический скипетр");
			sacredTools.GetItem("Gunblade").DisplayName.AddTranslation(GameCulture.Russian, "Оникс, несущий смерть");
			sacredTools.GetItem("LightningRifle").DisplayName.AddTranslation(GameCulture.Russian, "Молниеносная винтовка");
			sacredTools.GetItem("LunarCrystalStaff").DisplayName.AddTranslation(GameCulture.Russian, "Призматический скачок");
			sacredTools.GetItem("LunaticBurstStaff").DisplayName.AddTranslation(GameCulture.Russian, "Лунный шквал");
			sacredTools.GetItem("LunaticsGamble").DisplayName.AddTranslation(GameCulture.Russian, "Лунная игра");
			sacredTools.GetItem("Nyanmere").DisplayName.AddTranslation(GameCulture.Russian, "Мьяумеч");
			sacredTools.GetItem("PrismBreak").DisplayName.AddTranslation(GameCulture.Russian, "Разлом призмы");
			sacredTools.GetItem("StarScourge").DisplayName.AddTranslation(GameCulture.Russian, "Звездный бич");
			sacredTools.GetItem("StarShower").DisplayName.AddTranslation(GameCulture.Russian, "Муссонная комета");
			sacredTools.GetItem("TheLunarian").DisplayName.AddTranslation(GameCulture.Russian, "Лунарианец");
			sacredTools.GetItem("Claymarine").DisplayName.AddTranslation(GameCulture.Russian, "Клейморе");
			sacredTools.GetItem("EnergyFlail").DisplayName.AddTranslation(GameCulture.Russian, "Энергетическая цепь");
			sacredTools.GetItem("Extraterrestrial").DisplayName.AddTranslation(GameCulture.Russian, "Внеземность");
			sacredTools.GetItem("PhaseSlasher").DisplayName.AddTranslation(GameCulture.Russian, "Фазовый рубитель");
			sacredTools.GetItem("PlasmaDischarge").DisplayName.AddTranslation(GameCulture.Russian, "Плазменный разряд");
			sacredTools.GetItem("SolMatrix").DisplayName.AddTranslation(GameCulture.Russian, "Марсианский наноклинок");
			sacredTools.GetItem("TeslaGauntlet").DisplayName.AddTranslation(GameCulture.Russian, "Перчатка теслы");
			sacredTools.GetItem("Trispear").DisplayName.AddTranslation(GameCulture.Russian, "Троица");
			sacredTools.GetItem("ZappersInsanity").DisplayName.AddTranslation(GameCulture.Russian, "Электрошоковое безумие");
			sacredTools.GetItem("Armageddon").DisplayName.AddTranslation(GameCulture.Russian, "Армагеддон");
			sacredTools.GetItem("BrinkOfDespair").DisplayName.AddTranslation(GameCulture.Russian, "Грань отчаяния");
			sacredTools.GetItem("DarkRemnant").DisplayName.AddTranslation(GameCulture.Russian, "Темный остаток");
			sacredTools.GetItem("Dawnfall").DisplayName.AddTranslation(GameCulture.Russian, "Падение сумерек");
			sacredTools.GetItem("DeathBreath").DisplayName.AddTranslation(GameCulture.Russian, "Дыхание смерти");
			sacredTools.GetItem("Despair").DisplayName.AddTranslation(GameCulture.Russian, "Отчаяние");
			sacredTools.GetItem("DespairObserverStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох обозревателя отчаяния");
			sacredTools.GetItem("DuskCrossbow").DisplayName.AddTranslation(GameCulture.Russian, "Сумеречный арбалет");
			sacredTools.GetItem("EdgeOfGehenna").DisplayName.AddTranslation(GameCulture.Russian, "Край Геенны");
			sacredTools.GetItem("Evanescense").DisplayName.AddTranslation(GameCulture.Russian, "Исчезновение");
			sacredTools.GetItem("Marbas").DisplayName.AddTranslation(GameCulture.Russian, "Марбас");
			sacredTools.GetItem("OblivionRod").DisplayName.AddTranslation(GameCulture.Russian, "Посох забвения");
			sacredTools.GetItem("OblivionSpear").DisplayName.AddTranslation(GameCulture.Russian, "Фантомное бритва");
			sacredTools.GetItem("PGMUltimaRatioHecateII").DisplayName.AddTranslation(GameCulture.Russian, "Высший образец Гекаты II");
			sacredTools.GetItem("SinisterKnives").DisplayName.AddTranslation(GameCulture.Russian, "Ножи греха");
			sacredTools.GetItem("Soulhunter").DisplayName.AddTranslation(GameCulture.Russian, "Охотник за душами");
			sacredTools.GetItem("VoidAim").DisplayName.AddTranslation(GameCulture.Russian, "Пустотная цель");
			sacredTools.GetItem("WitherSwing").DisplayName.AddTranslation(GameCulture.Russian, "Иссушающий вращатель");
			sacredTools.GetItem("Brandblade").DisplayName.AddTranslation(GameCulture.Russian, "Фирменное лезвие");
			sacredTools.GetItem("DeadVoxel").DisplayName.AddTranslation(GameCulture.Russian, "Битый воксел");
			sacredTools.GetItem("FlareBolt").DisplayName.AddTranslation(GameCulture.Russian, "Огненная арбалетная стрела");
			sacredTools.GetItem("Midas").DisplayName.AddTranslation(GameCulture.Russian, "Мидас");
			sacredTools.GetItem("MissingFury").DisplayName.AddTranslation(GameCulture.Russian, "Пропавшая ярость");
			sacredTools.GetItem("Ribarang").DisplayName.AddTranslation(GameCulture.Russian, "Рибаранг");
			sacredTools.GetItem("RoastStaff").DisplayName.AddTranslation(GameCulture.Russian, "Адская трость");
			sacredTools.GetItem("Sausbow").DisplayName.AddTranslation(GameCulture.Russian, "Cоуарбалет");
			sacredTools.GetItem("TwinFury").DisplayName.AddTranslation(GameCulture.Russian, "Двойная ярость");
			sacredTools.GetItem("Ainfijarnar").DisplayName.AddTranslation(GameCulture.Russian, "Айнфиджарнар");
			sacredTools.GetItem("Jarih").DisplayName.AddTranslation(GameCulture.Russian, "Джарих");
			sacredTools.GetItem("Minshar").DisplayName.AddTranslation(GameCulture.Russian, "Миншар");
			sacredTools.GetItem("Satiesama").DisplayName.AddTranslation(GameCulture.Russian, "Сатисама");
			sacredTools.GetItem("Shaytnajima").DisplayName.AddTranslation(GameCulture.Russian, "Шайтнаджима");
			sacredTools.GetItem("Yakhudh").DisplayName.AddTranslation(GameCulture.Russian, "Яхуда");
			sacredTools.GetItem("HarvestStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох урожая");
			sacredTools.GetItem("MoodSummon").DisplayName.AddTranslation(GameCulture.Russian, "Ужасный корень");
			sacredTools.GetItem("PumpGlove").DisplayName.AddTranslation(GameCulture.Russian, "Тыквенная перчатка");
			sacredTools.GetItem("PumpkinCarver").DisplayName.AddTranslation(GameCulture.Russian, "Резчик по тыкве");
			sacredTools.GetItem("PumpkinFlare").DisplayName.AddTranslation(GameCulture.Russian, "Тыквенная вспышка");
			sacredTools.GetItem("Pumpnade").DisplayName.AddTranslation(GameCulture.Russian, "Тыкваната");
			sacredTools.GetItem("PumpYoyo").DisplayName.AddTranslation(GameCulture.Russian, "Тыквенный мяч");
			sacredTools.GetItem("VineSpear").DisplayName.AddTranslation(GameCulture.Russian, "Копье из лозы");
			sacredTools.GetItem("DesertStaff").DisplayName.AddTranslation(GameCulture.Russian, "Запретный скипетр");
			sacredTools.GetItem("Avalanche").DisplayName.AddTranslation(GameCulture.Russian, "Лавина");
			sacredTools.GetItem("BlindJusticeMK2").DisplayName.AddTranslation(GameCulture.Russian, "Слепое правосудие MK2");
			sacredTools.GetItem("BloodKunai").DisplayName.AddTranslation(GameCulture.Russian, "Кровожадный кунай");
			sacredTools.GetItem("CeruleanCyclone").DisplayName.AddTranslation(GameCulture.Russian, "Лазурный циклон");
			sacredTools.GetItem("Devilsknife").DisplayName.AddTranslation(GameCulture.Russian, "Дьявольский нож");
			sacredTools.GetItem("DimensionalCrusher").DisplayName.AddTranslation(GameCulture.Russian, "Серп Нефарии");
			sacredTools.GetItem("EndOfTheWorld").DisplayName.AddTranslation(GameCulture.Russian, "Конец света");
			sacredTools.GetItem("FatesLament").DisplayName.AddTranslation(GameCulture.Russian, "Плач судьбы");
			sacredTools.GetItem("FlariumSummon").DisplayName.AddTranslation(GameCulture.Russian, "Посох Арагура");
			sacredTools.GetItem("HyperPrism").DisplayName.AddTranslation(GameCulture.Russian, "Разрушенная призма");
			sacredTools.GetItem("LampOfCinders").DisplayName.AddTranslation(GameCulture.Russian, "Лампа пепла");
			sacredTools.GetItem("MaxDeathbringer").DisplayName.AddTranslation(GameCulture.Russian, "Злоба MK-1");
			sacredTools.GetItem("MaxDesertStaff").DisplayName.AddTranslation(GameCulture.Russian, "Оскверненный скипетр");
			sacredTools.GetItem("NeedlerRelic").DisplayName.AddTranslation(GameCulture.Russian, "Реликвия пустынь");
			sacredTools.GetItem("QueenSwarm").DisplayName.AddTranslation(GameCulture.Russian, "Королевский рой");
			sacredTools.GetItem("RogueWave").DisplayName.AddTranslation(GameCulture.Russian, "Разбойничья волна");
			sacredTools.GetItem("SwordOfGreed").DisplayName.AddTranslation(GameCulture.Russian, "Перкисас - Меч жадности");
			sacredTools.GetItem("Casey").DisplayName.AddTranslation(GameCulture.Russian, "Кейси");
			sacredTools.GetItem("Crescent").DisplayName.AddTranslation(GameCulture.Russian, "Полумесяц");
			sacredTools.GetItem("HarpyBoomerang").DisplayName.AddTranslation(GameCulture.Russian, "Волшебный бумеранг Дженсен");
			sacredTools.GetItem("Haven").DisplayName.AddTranslation(GameCulture.Russian, "Небеса");
			sacredTools.GetItem("Meenmourne").DisplayName.AddTranslation(GameCulture.Russian, "Минмоурн");
			sacredTools.GetItem("MidnightKey").DisplayName.AddTranslation(GameCulture.Russian, "Полуночный ключ");
			sacredTools.GetItem("OptionStaff").DisplayName.AddTranslation(GameCulture.Russian, "Посох альтернатив");
			sacredTools.GetItem("Prejordian").DisplayName.AddTranslation(GameCulture.Russian, "Прейордиан");
			sacredTools.GetItem("Skill_FuryForged").DisplayName.AddTranslation(GameCulture.Russian, "Кованая ярость");
			sacredTools.GetItem("SolusKatana").DisplayName.AddTranslation(GameCulture.Russian, "Катана солнца");
			sacredTools.GetItem("TheLeviathan").DisplayName.AddTranslation(GameCulture.Russian, "Левиафан");
			sacredTools.GetItem("TheLeviathan2").DisplayName.AddTranslation(GameCulture.Russian, "Левиафан II");
			sacredTools.GetItem("TheLeviathan3").DisplayName.AddTranslation(GameCulture.Russian, "Левиафан III");
			sacredTools.GetItem("Yaldabaoth").DisplayName.AddTranslation(GameCulture.Russian, "Ялдаваоф");
			sacredTools.GetItem("ArachnesGaze").DisplayName.AddTranslation(GameCulture.Russian, "Взгляд Арахны");
			sacredTools.GetItem("HoariHemonga").DisplayName.AddTranslation(GameCulture.Russian, "Хоари Хемонга");
			sacredTools.GetItem("RazorfangDagger").DisplayName.AddTranslation(GameCulture.Russian, "Кинжал острых клыков");
			sacredTools.GetItem("SanguineumVirgam").DisplayName.AddTranslation(GameCulture.Russian, "Кровавый посох");
			sacredTools.GetItem("VenomiteBow").DisplayName.AddTranslation(GameCulture.Russian, "Отравленный лук");
			sacredTools.GetItem("VenomiteDagger").DisplayName.AddTranslation(GameCulture.Russian, "Отравленный кинжал");
			sacredTools.GetItem("VenomiteStaff").DisplayName.AddTranslation(GameCulture.Russian, "Отравленный посох");
			sacredTools.GetItem("VenomiteSword").DisplayName.AddTranslation(GameCulture.Russian, "Отравленный разрушитель");
			sacredTools.GetItem("SymbolFRF").DisplayName.AddTranslation(GameCulture.Russian, "Сгоревший лес");
			sacredTools.GetItem("SymbolSky").DisplayName.AddTranslation(GameCulture.Russian, "Небо");
			sacredTools.GetItem("SymbolUG").DisplayName.AddTranslation(GameCulture.Russian, "Пещеры");
			sacredTools.GetItem("SymbolUGCo").DisplayName.AddTranslation(GameCulture.Russian, "Подземное Искажение");
			sacredTools.GetItem("SymbolUGCr").DisplayName.AddTranslation(GameCulture.Russian, "Подземный Багрянец");
			sacredTools.GetItem("SymbolUGD").DisplayName.AddTranslation(GameCulture.Russian, "Подземная Пустыня");
			sacredTools.GetItem("SymbolUGH").DisplayName.AddTranslation(GameCulture.Russian, "Подземное Освящение");
			sacredTools.GetItem("SymbolUW").DisplayName.AddTranslation(GameCulture.Russian, "Ад");
		}
	}
}
