using Terraria.Localization;

namespace CalamityRuTranslate.CalamityMod.Projectiles
{
    internal static class CalamityProjectiles
    {
        public static void Setup()
        {
            Projectiles();
        }

        private static void Projectiles()
        {
            ModCompatibility.CalamityMod.GetProjectile("BelchingCoralSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            ModCompatibility.CalamityMod.GetProjectile("CrabBoulder").DisplayName.AddTranslation(GameCulture.Russian, "Булыжник");
            ModCompatibility.CalamityMod.GetProjectile("CragmawBeam").DisplayName.AddTranslation(GameCulture.Russian, "Гамма-луч");
            ModCompatibility.CalamityMod.GetProjectile("CragmawBubble").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный пузырь");
            ModCompatibility.CalamityMod.GetProjectile("CragmawSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            ModCompatibility.CalamityMod.GetProjectile("CragmawVibeCheckChain").DisplayName.AddTranslation(GameCulture.Russian, "Ты думаешь, что в безопасности?");
            ModCompatibility.CalamityMod.GetProjectile("CrimsonSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            ModCompatibility.CalamityMod.GetProjectile("DraedonLaser").DisplayName.AddTranslation(GameCulture.Russian, "Лазер турели лаборатории");
            ModCompatibility.CalamityMod.GetProjectile("EarthRockBig").DisplayName.AddTranslation(GameCulture.Russian, "Камень");
            ModCompatibility.CalamityMod.GetProjectile("EarthRockSmall").DisplayName.AddTranslation(GameCulture.Russian, "Камень");
            ModCompatibility.CalamityMod.GetProjectile("FlakAcid").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            ModCompatibility.CalamityMod.GetProjectile("FlameBurstHostile").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв");
            ModCompatibility.CalamityMod.GetProjectile("GammaAcid").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            ModCompatibility.CalamityMod.GetProjectile("GammaBeam").DisplayName.AddTranslation(GameCulture.Russian, "Гамма-луч");
            ModCompatibility.CalamityMod.GetProjectile("HorsWaterBlast").DisplayName.AddTranslation(GameCulture.Russian, "Вода");
            ModCompatibility.CalamityMod.GetProjectile("InkBombHostile").DisplayName.AddTranslation(GameCulture.Russian, "Чернильная бомба");
            ModCompatibility.CalamityMod.GetProjectile("InkPoisonCloud").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            ModCompatibility.CalamityMod.GetProjectile("InkPoisonCloud2").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            ModCompatibility.CalamityMod.GetProjectile("InkPoisonCloud3").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            ModCompatibility.CalamityMod.GetProjectile("NuclearBulletLarge").DisplayName.AddTranslation(GameCulture.Russian, "Ядерная пуля");
            ModCompatibility.CalamityMod.GetProjectile("NuclearBulletMedium").DisplayName.AddTranslation(GameCulture.Russian, "Ядерная пуля");
            ModCompatibility.CalamityMod.GetProjectile("NuclearToadGoo").DisplayName.AddTranslation(GameCulture.Russian, "Вязкая масса");
            ModCompatibility.CalamityMod.GetProjectile("OrthoceraStream").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный поток");
            ModCompatibility.CalamityMod.GetProjectile("PearlBurst").DisplayName.AddTranslation(GameCulture.Russian, "Жемчужный всплеск");
            ModCompatibility.CalamityMod.GetProjectile("PearlRain").DisplayName.AddTranslation(GameCulture.Russian, "Жемчужный дождь");
            ModCompatibility.CalamityMod.GetProjectile("PufferExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв");
            ModCompatibility.CalamityMod.GetProjectile("StormMarkHostile").DisplayName.AddTranslation(GameCulture.Russian, "Метка");
            ModCompatibility.CalamityMod.GetProjectile("SulphuricAcidBubble").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный пузырь");
            ModCompatibility.CalamityMod.GetProjectile("SulphuricAcidMist").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный туман");
            ModCompatibility.CalamityMod.GetProjectile("TornadoHostile").DisplayName.AddTranslation(GameCulture.Russian, "Торнадо");
            ModCompatibility.CalamityMod.GetProjectile("ToxicMinnowCloud").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            ModCompatibility.CalamityMod.GetProjectile("TrilobiteSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            ModCompatibility.CalamityMod.GetProjectile("AbyssBallVolley").DisplayName.AddTranslation(GameCulture.Russian, "Залп шаров бездны");
            ModCompatibility.CalamityMod.GetProjectile("AbyssBallVolley2").DisplayName.AddTranslation(GameCulture.Russian, "Залп шаров бездны");
            ModCompatibility.CalamityMod.GetProjectile("AbyssMine").DisplayName.AddTranslation(GameCulture.Russian, "Мина бездны");
            ModCompatibility.CalamityMod.GetProjectile("AbyssMine2").DisplayName.AddTranslation(GameCulture.Russian, "Мина бездны");
            ModCompatibility.CalamityMod.GetProjectile("AstralFlame").DisplayName.AddTranslation(GameCulture.Russian, "Астральное преследующее пламя");
            ModCompatibility.CalamityMod.GetProjectile("AstralLaser").DisplayName.AddTranslation(GameCulture.Russian, "Залп астральных лазеров");
            ModCompatibility.CalamityMod.GetProjectile("AstralShot2").DisplayName.AddTranslation(GameCulture.Russian, "Астральный лазер");
            ModCompatibility.CalamityMod.GetProjectile("BigFlare").DisplayName.AddTranslation(GameCulture.Russian, "Большая вспышка");
            ModCompatibility.CalamityMod.GetProjectile("BigFlare2").DisplayName.AddTranslation(GameCulture.Russian, "Большая вспышка");
            ModCompatibility.CalamityMod.GetProjectile("BirbAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура дракона");
            ModCompatibility.CalamityMod.GetProjectile("BirbAuraFlare").DisplayName.AddTranslation(GameCulture.Russian, "Вспышка ауры дракона");
            ModCompatibility.CalamityMod.GetProjectile("BloodGeyser").DisplayName.AddTranslation(GameCulture.Russian, "Кровяной гейзер");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneBall").DisplayName.AddTranslation(GameCulture.Russian, "Шар серного огня");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneBarrage").DisplayName.AddTranslation(GameCulture.Russian, "Серный дротик");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneFire").DisplayName.AddTranslation(GameCulture.Russian, "Серный огонь");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneFireblast").DisplayName.AddTranslation(GameCulture.Russian, "Серный мегавзрыв");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneGigaBlast").DisplayName.AddTranslation(GameCulture.Russian, "Серный огненный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneHellblast").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский взрыв");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneHellblast2").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский взрыв");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneHellfireball").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский огненный шар");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneLaser").DisplayName.AddTranslation(GameCulture.Russian, "Серный лазер");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneLaserSplit").DisplayName.AddTranslation(GameCulture.Russian, "Серный преследующий лазер");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneMonster").DisplayName.AddTranslation(GameCulture.Russian, "Серное отродье");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneRay").DisplayName.AddTranslation(GameCulture.Russian, "Серный луч");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneTargetRay").DisplayName.AddTranslation(GameCulture.Russian, "Серный прицеливающийся луч");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneWave").DisplayName.AddTranslation(GameCulture.Russian, "Серный череп");
            ModCompatibility.CalamityMod.GetProjectile("DarkEnergyBall").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная энергия");
            ModCompatibility.CalamityMod.GetProjectile("DarkEnergyBall2").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная энергия");
            ModCompatibility.CalamityMod.GetProjectile("DarkOrb").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная сфера");
            ModCompatibility.CalamityMod.GetProjectile("DestroyerCursedLaser").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый лазер");
            ModCompatibility.CalamityMod.GetProjectile("DestroyerElectricLaser").DisplayName.AddTranslation(GameCulture.Russian, "Электрический лазер");
            ModCompatibility.CalamityMod.GetProjectile("DeusMine").DisplayName.AddTranslation(GameCulture.Russian, "Астральная мина");
            ModCompatibility.CalamityMod.GetProjectile("DeusRitualDrama").DisplayName.AddTranslation(GameCulture.Russian, "Ритуальная драма Деуса");
            ModCompatibility.CalamityMod.GetProjectile("DoGBeam").DisplayName.AddTranslation(GameCulture.Russian, "Портальный лазер");
            ModCompatibility.CalamityMod.GetProjectile("DoGBeamPortal").DisplayName.AddTranslation(GameCulture.Russian, "Портал лучей");
            ModCompatibility.CalamityMod.GetProjectile("DoGDeath").DisplayName.AddTranslation(GameCulture.Russian, "Смертельный луч");
            ModCompatibility.CalamityMod.GetProjectile("DoGFire").DisplayName.AddTranslation(GameCulture.Russian, "Смертельный огонь");
            ModCompatibility.CalamityMod.GetProjectile("DoGTeleportRift").DisplayName.AddTranslation(GameCulture.Russian, "Разлом");
            ModCompatibility.CalamityMod.GetProjectile("EssenceDust").DisplayName.AddTranslation(GameCulture.Russian, "Космическая пыль");
            ModCompatibility.CalamityMod.GetProjectile("Flare").DisplayName.AddTranslation(GameCulture.Russian, "Вспышка");
            ModCompatibility.CalamityMod.GetProjectile("FlareBomb").DisplayName.AddTranslation(GameCulture.Russian, "Бомба вспышки");
            ModCompatibility.CalamityMod.GetProjectile("FlareDust").DisplayName.AddTranslation(GameCulture.Russian, "Вспышки пыли");
            ModCompatibility.CalamityMod.GetProjectile("FlareDust2").DisplayName.AddTranslation(GameCulture.Russian, "Бомба вспышки");
            ModCompatibility.CalamityMod.GetProjectile("Flarenado").DisplayName.AddTranslation(GameCulture.Russian, "Огненный торнадо");
            ModCompatibility.CalamityMod.GetProjectile("FrostMist").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной туман");
            ModCompatibility.CalamityMod.GetProjectile("GreatSandBlast").DisplayName.AddTranslation(GameCulture.Russian, "Великий песчаный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("HealOrbProv").DisplayName.AddTranslation(GameCulture.Russian, "Лечение");
            ModCompatibility.CalamityMod.GetProjectile("HellfireExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв серного адского пламени");
            ModCompatibility.CalamityMod.GetProjectile("HiveBombGoliath").DisplayName.AddTranslation(GameCulture.Russian, "Бомба улья");
            ModCompatibility.CalamityMod.GetProjectile("HolyAura").DisplayName.AddTranslation(GameCulture.Russian, "Святая аура");
            ModCompatibility.CalamityMod.GetProjectile("HolyBlast").DisplayName.AddTranslation(GameCulture.Russian, "Святой взрыв");
            ModCompatibility.CalamityMod.GetProjectile("HolyBomb").DisplayName.AddTranslation(GameCulture.Russian, "Святая бомба");
            ModCompatibility.CalamityMod.GetProjectile("HolyBurnOrb").DisplayName.AddTranslation(GameCulture.Russian, "Святая сфера");
            ModCompatibility.CalamityMod.GetProjectile("HolyFire").DisplayName.AddTranslation(GameCulture.Russian, "Святой огонь");
            ModCompatibility.CalamityMod.GetProjectile("HolyFire2").DisplayName.AddTranslation(GameCulture.Russian, "Святой огонь");
            ModCompatibility.CalamityMod.GetProjectile("HolyFlare").DisplayName.AddTranslation(GameCulture.Russian, "Святая вспышка");
            ModCompatibility.CalamityMod.GetProjectile("HolyLight").DisplayName.AddTranslation(GameCulture.Russian, "Святой свет");
            ModCompatibility.CalamityMod.GetProjectile("HolySpear").DisplayName.AddTranslation(GameCulture.Russian, "Святое копьё");
            ModCompatibility.CalamityMod.GetProjectile("IceBlast").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной взрыв");
            ModCompatibility.CalamityMod.GetProjectile("IceBomb").DisplayName.AddTranslation(GameCulture.Russian, "Ледяная бомба");
            ModCompatibility.CalamityMod.GetProjectile("IceRain").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной дождь");
            ModCompatibility.CalamityMod.GetProjectile("IchorShot").DisplayName.AddTranslation(GameCulture.Russian, "Ихоровый выстрел");
            ModCompatibility.CalamityMod.GetProjectile("Infernado").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            ModCompatibility.CalamityMod.GetProjectile("Infernado2").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            ModCompatibility.CalamityMod.GetProjectile("InfernadoRevenge").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            ModCompatibility.CalamityMod.GetProjectile("JewelProjectile").DisplayName.AddTranslation(GameCulture.Russian, "Рубиновый выстрел");
            ModCompatibility.CalamityMod.GetProjectile("LeviathanBomb").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритная рвота");
            ModCompatibility.CalamityMod.GetProjectile("MoltenBlast").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("MoltenBlob").DisplayName.AddTranslation(GameCulture.Russian, "Расплавленная капля");
            ModCompatibility.CalamityMod.GetProjectile("MushBomb").DisplayName.AddTranslation(GameCulture.Russian, "Грибной выстрел");
            ModCompatibility.CalamityMod.GetProjectile("MushBombFall").DisplayName.AddTranslation(GameCulture.Russian, "Падающий гриб");
            ModCompatibility.CalamityMod.GetProjectile("Mushmash").DisplayName.AddTranslation(GameCulture.Russian, "Грибная каша");
            ModCompatibility.CalamityMod.GetProjectile("OldDukeGore").DisplayName.AddTranslation(GameCulture.Russian, "Сернистые останки");
            ModCompatibility.CalamityMod.GetProjectile("OldDukeSummonDrop").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            ModCompatibility.CalamityMod.GetProjectile("OldDukeVortex").DisplayName.AddTranslation(GameCulture.Russian, "Сернистый вихрь");
            ModCompatibility.CalamityMod.GetProjectile("OverlyDramaticDukeSummoner").DisplayName.AddTranslation(GameCulture.Russian, "Призыватель Старого герцога");
            ModCompatibility.CalamityMod.GetProjectile("PhantomBlast").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("PhantomBlast2").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("PhantomGhostShot").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный выстрел души");
            ModCompatibility.CalamityMod.GetProjectile("PhantomHookShot").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный крюковый выстрел");
            ModCompatibility.CalamityMod.GetProjectile("PhantomMine").DisplayName.AddTranslation(GameCulture.Russian, "Фантомная сфера");
            ModCompatibility.CalamityMod.GetProjectile("PhantomShot").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный выстрел");
            ModCompatibility.CalamityMod.GetProjectile("PhantomShot2").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный выстрел");
            ModCompatibility.CalamityMod.GetProjectile("PlagueExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Чумной жало-выстрел");
            ModCompatibility.CalamityMod.GetProjectile("PlagueStingerGoliath").DisplayName.AddTranslation(GameCulture.Russian, "Чумное преследующее жало");
            ModCompatibility.CalamityMod.GetProjectile("PlagueStingerGoliathV2").DisplayName.AddTranslation(GameCulture.Russian, "Взрывное чумное жало");
            ModCompatibility.CalamityMod.GetProjectile("ProfanedSpear").DisplayName.AddTranslation(GameCulture.Russian, "Осквернённое копьё");
            ModCompatibility.CalamityMod.GetProjectile("ProvidenceCrystal").DisplayName.AddTranslation(GameCulture.Russian, "Святой кристалл");
            ModCompatibility.CalamityMod.GetProjectile("ProvidenceCrystalShard").DisplayName.AddTranslation(GameCulture.Russian, "Осколок святого кристалла");
            ModCompatibility.CalamityMod.GetProjectile("ProvidenceHolyRay").DisplayName.AddTranslation(GameCulture.Russian, "Святой луч");
            ModCompatibility.CalamityMod.GetProjectile("RavagerFlame").DisplayName.AddTranslation(GameCulture.Russian, "Синее пламя");
            ModCompatibility.CalamityMod.GetProjectile("RedLightning").DisplayName.AddTranslation(GameCulture.Russian, "Красная молния");
            ModCompatibility.CalamityMod.GetProjectile("RedLightningFeather").DisplayName.AddTranslation(GameCulture.Russian, "Перо красной молнии");
            ModCompatibility.CalamityMod.GetProjectile("SandBlast").DisplayName.AddTranslation(GameCulture.Russian, "Песчаный взрыв");
            ModCompatibility.CalamityMod.GetProjectile("SandPoisonCloud").DisplayName.AddTranslation(GameCulture.Russian, "Ядовитое облако");
            ModCompatibility.CalamityMod.GetProjectile("SandTooth").DisplayName.AddTranslation(GameCulture.Russian, "Песчаный зуб");
            ModCompatibility.CalamityMod.GetProjectile("ScavengerLaser").DisplayName.AddTranslation(GameCulture.Russian, "Преследующий дротик");
            ModCompatibility.CalamityMod.GetProjectile("ScavengerNuke").DisplayName.AddTranslation(GameCulture.Russian, "Преследующая ядерная ракета");
            ModCompatibility.CalamityMod.GetProjectile("ShadeNimbusHostile").DisplayName.AddTranslation(GameCulture.Russian, "Теневая туча");
            ModCompatibility.CalamityMod.GetProjectile("ShaderainHostile").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый дождь");
            ModCompatibility.CalamityMod.GetProjectile("ShadowflameFireball").DisplayName.AddTranslation(GameCulture.Russian, "Шар теневого пламени");
            ModCompatibility.CalamityMod.GetProjectile("Shadowflamethrower").DisplayName.AddTranslation(GameCulture.Russian, "Дыхание теневого пламени");
            ModCompatibility.CalamityMod.GetProjectile("SignusScythe").DisplayName.AddTranslation(GameCulture.Russian, "Коса");
            ModCompatibility.CalamityMod.GetProjectile("SirenSong").DisplayName.AddTranslation(GameCulture.Russian, "Нота");
            ModCompatibility.CalamityMod.GetProjectile("SkyFlare").DisplayName.AddTranslation(GameCulture.Russian, "Небесная вспышка");
            ModCompatibility.CalamityMod.GetProjectile("SkyFlareRevenge").DisplayName.AddTranslation(GameCulture.Russian, "Небесная вспышка");
            ModCompatibility.CalamityMod.GetProjectile("SporeGasPlantera").DisplayName.AddTranslation(GameCulture.Russian, "Газ со спорами");
            ModCompatibility.CalamityMod.GetProjectile("VileClot").DisplayName.AddTranslation(GameCulture.Russian, "Мерзкий сгусток");
            ModCompatibility.CalamityMod.GetProjectile("WaterSpear").DisplayName.AddTranslation(GameCulture.Russian, "Водяное копьё");
            ModCompatibility.CalamityMod.GetProjectile("YharonFireball").DisplayName.AddTranslation(GameCulture.Russian, "Шар драконьего огня");
            ModCompatibility.CalamityMod.GetProjectile("YharonFireball2").DisplayName.AddTranslation(GameCulture.Russian, "Шар драконьего огня");
            ModCompatibility.CalamityMod.GetProjectile("AcidDrop").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            ModCompatibility.CalamityMod.GetProjectile("BrimstoneGeyser").DisplayName.AddTranslation(GameCulture.Russian, "Дым");
            ModCompatibility.CalamityMod.GetProjectile("GeyserTelegraph").DisplayName.AddTranslation(GameCulture.Russian, "Гейзер");
            ModCompatibility.CalamityMod.GetProjectile("HotSteam").DisplayName.AddTranslation(GameCulture.Russian, "Пар");
            ModCompatibility.CalamityMod.GetProjectile("LavaChunk").DisplayName.AddTranslation(GameCulture.Russian, "Лавовый кусок");
            ModCompatibility.CalamityMod.GetProjectile("LightningMark").DisplayName.AddTranslation(GameCulture.Russian, "Отметка молнии");
            ModCompatibility.CalamityMod.GetProjectile("SmokeTelegraph").DisplayName.AddTranslation(GameCulture.Russian, "Дым");
        }
    }
}