using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityRuTranslate.CalamityMod.Projectiles
{
    internal class CalamityProjectiles
    {
        public static void Setup()
        {
            Projectiles();
        }

        private static void Projectiles()
        {
            Mod calamity = ModLoader.GetMod("CalamityMod");
            
            calamity.GetProjectile("BelchingCoralSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            calamity.GetProjectile("CrabBoulder").DisplayName.AddTranslation(GameCulture.Russian, "Булыжник");
            calamity.GetProjectile("CragmawBeam").DisplayName.AddTranslation(GameCulture.Russian, "Гамма-луч");
            calamity.GetProjectile("CragmawBubble").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный пузырь");
            calamity.GetProjectile("CragmawSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            calamity.GetProjectile("CragmawVibeCheckChain").DisplayName.AddTranslation(GameCulture.Russian, "Ты думаешь, что в безопасности?");
            calamity.GetProjectile("CrimsonSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            calamity.GetProjectile("DraedonLaser").DisplayName.AddTranslation(GameCulture.Russian, "Лазер турели лаборатории");
            calamity.GetProjectile("EarthRockBig").DisplayName.AddTranslation(GameCulture.Russian, "Камень");
            calamity.GetProjectile("EarthRockSmall").DisplayName.AddTranslation(GameCulture.Russian, "Камень");
            calamity.GetProjectile("FlakAcid").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            calamity.GetProjectile("FlameBurstHostile").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв");
            calamity.GetProjectile("GammaAcid").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            calamity.GetProjectile("GammaBeam").DisplayName.AddTranslation(GameCulture.Russian, "Гамма-луч");
            calamity.GetProjectile("HorsWaterBlast").DisplayName.AddTranslation(GameCulture.Russian, "Вода");
            calamity.GetProjectile("InkBombHostile").DisplayName.AddTranslation(GameCulture.Russian, "Чернильная бомба");
            calamity.GetProjectile("InkPoisonCloud").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            calamity.GetProjectile("InkPoisonCloud2").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            calamity.GetProjectile("InkPoisonCloud3").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            calamity.GetProjectile("NuclearBulletLarge").DisplayName.AddTranslation(GameCulture.Russian, "Ядерная пуля");
            calamity.GetProjectile("NuclearBulletMedium").DisplayName.AddTranslation(GameCulture.Russian, "Ядерная пуля");
            calamity.GetProjectile("NuclearToadGoo").DisplayName.AddTranslation(GameCulture.Russian, "Вязкая масса");
            calamity.GetProjectile("OrthoceraStream").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный поток");
            calamity.GetProjectile("PearlBurst").DisplayName.AddTranslation(GameCulture.Russian, "Жемчужный всплеск");
            calamity.GetProjectile("PearlRain").DisplayName.AddTranslation(GameCulture.Russian, "Жемчужный дождь");
            calamity.GetProjectile("PufferExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв");
            calamity.GetProjectile("StormMarkHostile").DisplayName.AddTranslation(GameCulture.Russian, "Метка");
            calamity.GetProjectile("SulphuricAcidBubble").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный пузырь");
            calamity.GetProjectile("SulphuricAcidMist").DisplayName.AddTranslation(GameCulture.Russian, "Кислотный туман");
            calamity.GetProjectile("TornadoHostile").DisplayName.AddTranslation(GameCulture.Russian, "Торнадо");
            calamity.GetProjectile("ToxicMinnowCloud").DisplayName.AddTranslation(GameCulture.Russian, "Облако");
            calamity.GetProjectile("TrilobiteSpike").DisplayName.AddTranslation(GameCulture.Russian, "Шип");
            calamity.GetProjectile("AbyssBallVolley").DisplayName.AddTranslation(GameCulture.Russian, "Залп шаров бездны");
            calamity.GetProjectile("AbyssBallVolley2").DisplayName.AddTranslation(GameCulture.Russian, "Залп шаров бездны");
            calamity.GetProjectile("AbyssMine").DisplayName.AddTranslation(GameCulture.Russian, "Мина бездны");
            calamity.GetProjectile("AbyssMine2").DisplayName.AddTranslation(GameCulture.Russian, "Мина бездны");
            calamity.GetProjectile("AstralFlame").DisplayName.AddTranslation(GameCulture.Russian, "Астральное преследующее пламя");
            calamity.GetProjectile("AstralLaser").DisplayName.AddTranslation(GameCulture.Russian, "Залп астральных лазеров");
            calamity.GetProjectile("AstralShot2").DisplayName.AddTranslation(GameCulture.Russian, "Астральный лазер");
            calamity.GetProjectile("BigFlare").DisplayName.AddTranslation(GameCulture.Russian, "Большая вспышка");
            calamity.GetProjectile("BigFlare2").DisplayName.AddTranslation(GameCulture.Russian, "Большая вспышка");
            calamity.GetProjectile("BirbAura").DisplayName.AddTranslation(GameCulture.Russian, "Аура дракона");
            calamity.GetProjectile("BirbAuraFlare").DisplayName.AddTranslation(GameCulture.Russian, "Вспышка ауры дракона");
            calamity.GetProjectile("BloodGeyser").DisplayName.AddTranslation(GameCulture.Russian, "Кровяной гейзер");
            calamity.GetProjectile("BrimstoneBall").DisplayName.AddTranslation(GameCulture.Russian, "Шар серного огня");
            calamity.GetProjectile("BrimstoneBarrage").DisplayName.AddTranslation(GameCulture.Russian, "Серный дротик");
            calamity.GetProjectile("BrimstoneFire").DisplayName.AddTranslation(GameCulture.Russian, "Серный огонь");
            calamity.GetProjectile("BrimstoneFireblast").DisplayName.AddTranslation(GameCulture.Russian, "Серный мегавзрыв");
            calamity.GetProjectile("BrimstoneGigaBlast").DisplayName.AddTranslation(GameCulture.Russian, "Серный огненный взрыв");
            calamity.GetProjectile("BrimstoneHellblast").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский взрыв");
            calamity.GetProjectile("BrimstoneHellblast2").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский взрыв");
            calamity.GetProjectile("BrimstoneHellfireball").DisplayName.AddTranslation(GameCulture.Russian, "Серный адский огненный шар");
            calamity.GetProjectile("BrimstoneLaser").DisplayName.AddTranslation(GameCulture.Russian, "Серный лазер");
            calamity.GetProjectile("BrimstoneLaserSplit").DisplayName.AddTranslation(GameCulture.Russian, "Серный преследующий лазер");
            calamity.GetProjectile("BrimstoneMonster").DisplayName.AddTranslation(GameCulture.Russian, "Серное отродье");
            calamity.GetProjectile("BrimstoneRay").DisplayName.AddTranslation(GameCulture.Russian, "Серный луч");
            calamity.GetProjectile("BrimstoneTargetRay").DisplayName.AddTranslation(GameCulture.Russian, "Серный прицеливающийся луч");
            calamity.GetProjectile("BrimstoneWave").DisplayName.AddTranslation(GameCulture.Russian, "Серный череп");
            calamity.GetProjectile("DarkEnergyBall").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная энергия");
            calamity.GetProjectile("DarkEnergyBall2").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная энергия");
            calamity.GetProjectile("DarkOrb").DisplayName.AddTranslation(GameCulture.Russian, "Тёмная сфера");
            calamity.GetProjectile("DestroyerCursedLaser").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый лазер");
            calamity.GetProjectile("DestroyerElectricLaser").DisplayName.AddTranslation(GameCulture.Russian, "Электрический лазер");
            calamity.GetProjectile("DeusMine").DisplayName.AddTranslation(GameCulture.Russian, "Астральная мина");
            calamity.GetProjectile("DeusRitualDrama").DisplayName.AddTranslation(GameCulture.Russian, "Ритуальная драма Деуса");
            calamity.GetProjectile("DoGBeam").DisplayName.AddTranslation(GameCulture.Russian, "Портальный лазер");
            calamity.GetProjectile("DoGBeamPortal").DisplayName.AddTranslation(GameCulture.Russian, "Портал лучей");
            calamity.GetProjectile("DoGDeath").DisplayName.AddTranslation(GameCulture.Russian, "Смертельный луч");
            calamity.GetProjectile("DoGFire").DisplayName.AddTranslation(GameCulture.Russian, "Смертельный огонь");
            calamity.GetProjectile("DoGTeleportRift").DisplayName.AddTranslation(GameCulture.Russian, "Разлом");
            calamity.GetProjectile("EssenceDust").DisplayName.AddTranslation(GameCulture.Russian, "Космическая пыль");
            calamity.GetProjectile("Flare").DisplayName.AddTranslation(GameCulture.Russian, "Вспышка");
            calamity.GetProjectile("FlareBomb").DisplayName.AddTranslation(GameCulture.Russian, "Бомба вспышки");
            calamity.GetProjectile("FlareDust").DisplayName.AddTranslation(GameCulture.Russian, "Вспышки пыли");
            calamity.GetProjectile("FlareDust2").DisplayName.AddTranslation(GameCulture.Russian, "Бомба вспышки");
            calamity.GetProjectile("Flarenado").DisplayName.AddTranslation(GameCulture.Russian, "Огненный торнадо");
            calamity.GetProjectile("FrostMist").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной туман");
            calamity.GetProjectile("GreatSandBlast").DisplayName.AddTranslation(GameCulture.Russian, "Великий песчаный взрыв");
            calamity.GetProjectile("HealOrbProv").DisplayName.AddTranslation(GameCulture.Russian, "Лечение");
            calamity.GetProjectile("HellfireExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Взрыв серного адского пламени");
            calamity.GetProjectile("HiveBombGoliath").DisplayName.AddTranslation(GameCulture.Russian, "Бомба улья");
            calamity.GetProjectile("HolyAura").DisplayName.AddTranslation(GameCulture.Russian, "Святая аура");
            calamity.GetProjectile("HolyBlast").DisplayName.AddTranslation(GameCulture.Russian, "Святой взрыв");
            calamity.GetProjectile("HolyBomb").DisplayName.AddTranslation(GameCulture.Russian, "Святая бомба");
            calamity.GetProjectile("HolyBurnOrb").DisplayName.AddTranslation(GameCulture.Russian, "Святая сфера");
            calamity.GetProjectile("HolyFire").DisplayName.AddTranslation(GameCulture.Russian, "Святой огонь");
            calamity.GetProjectile("HolyFire2").DisplayName.AddTranslation(GameCulture.Russian, "Святой огонь");
            calamity.GetProjectile("HolyFlare").DisplayName.AddTranslation(GameCulture.Russian, "Святая вспышка");
            calamity.GetProjectile("HolyLight").DisplayName.AddTranslation(GameCulture.Russian, "Святой свет");
            calamity.GetProjectile("HolySpear").DisplayName.AddTranslation(GameCulture.Russian, "Святое копьё");
            calamity.GetProjectile("IceBlast").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной взрыв");
            calamity.GetProjectile("IceBomb").DisplayName.AddTranslation(GameCulture.Russian, "Ледяная бомба");
            calamity.GetProjectile("IceRain").DisplayName.AddTranslation(GameCulture.Russian, "Ледяной дождь");
            calamity.GetProjectile("IchorShot").DisplayName.AddTranslation(GameCulture.Russian, "Ихоровый выстрел");
            calamity.GetProjectile("Infernado").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            calamity.GetProjectile("Infernado2").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            calamity.GetProjectile("InfernadoRevenge").DisplayName.AddTranslation(GameCulture.Russian, "Адский торнадо");
            calamity.GetProjectile("JewelProjectile").DisplayName.AddTranslation(GameCulture.Russian, "Рубиновый выстрел");
            calamity.GetProjectile("LeviathanBomb").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритная рвота");
            calamity.GetProjectile("MoltenBlast").DisplayName.AddTranslation(GameCulture.Russian, "Метеоритный взрыв");
            calamity.GetProjectile("MoltenBlob").DisplayName.AddTranslation(GameCulture.Russian, "Расплавленная капля");
            calamity.GetProjectile("MushBomb").DisplayName.AddTranslation(GameCulture.Russian, "Грибной выстрел");
            calamity.GetProjectile("MushBombFall").DisplayName.AddTranslation(GameCulture.Russian, "Падающий гриб");
            calamity.GetProjectile("Mushmash").DisplayName.AddTranslation(GameCulture.Russian, "Грибная каша");
            calamity.GetProjectile("OldDukeGore").DisplayName.AddTranslation(GameCulture.Russian, "Сернистые останки");
            calamity.GetProjectile("OldDukeSummonDrop").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            calamity.GetProjectile("OldDukeVortex").DisplayName.AddTranslation(GameCulture.Russian, "Сернистый вихрь");
            calamity.GetProjectile("OverlyDramaticDukeSummoner").DisplayName.AddTranslation(GameCulture.Russian, "Призыватель Старого герцога");
            calamity.GetProjectile("PhantomBlast").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный взрыв");
            calamity.GetProjectile("PhantomBlast2").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный взрыв");
            calamity.GetProjectile("PhantomGhostShot").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный выстрел души");
            calamity.GetProjectile("PhantomHookShot").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный крюковый выстрел");
            calamity.GetProjectile("PhantomMine").DisplayName.AddTranslation(GameCulture.Russian, "Фантомная сфера");
            calamity.GetProjectile("PhantomShot").DisplayName.AddTranslation(GameCulture.Russian, "Фантомный выстрел");
            calamity.GetProjectile("PhantomShot2").DisplayName.AddTranslation(GameCulture.Russian, "Мощный фантомный выстрел");
            calamity.GetProjectile("PlagueExplosion").DisplayName.AddTranslation(GameCulture.Russian, "Чумной жало-выстрел");
            calamity.GetProjectile("PlagueStingerGoliath").DisplayName.AddTranslation(GameCulture.Russian, "Чумное преследующее жало");
            calamity.GetProjectile("PlagueStingerGoliathV2").DisplayName.AddTranslation(GameCulture.Russian, "Взрывное чумное жало");
            calamity.GetProjectile("ProfanedSpear").DisplayName.AddTranslation(GameCulture.Russian, "Осквернённое копьё");
            calamity.GetProjectile("ProvidenceCrystal").DisplayName.AddTranslation(GameCulture.Russian, "Святой кристалл");
            calamity.GetProjectile("ProvidenceCrystalShard").DisplayName.AddTranslation(GameCulture.Russian, "Осколок святого кристалла");
            calamity.GetProjectile("ProvidenceHolyRay").DisplayName.AddTranslation(GameCulture.Russian, "Святой луч");
            calamity.GetProjectile("RavagerFlame").DisplayName.AddTranslation(GameCulture.Russian, "Синее пламя");
            calamity.GetProjectile("RedLightning").DisplayName.AddTranslation(GameCulture.Russian, "Красная молния");
            calamity.GetProjectile("RedLightningFeather").DisplayName.AddTranslation(GameCulture.Russian, "Перо красной молнии");
            calamity.GetProjectile("SandBlast").DisplayName.AddTranslation(GameCulture.Russian, "Песчаный взрыв");
            calamity.GetProjectile("SandPoisonCloud").DisplayName.AddTranslation(GameCulture.Russian, "Ядовитое облако");
            calamity.GetProjectile("SandTooth").DisplayName.AddTranslation(GameCulture.Russian, "Песчаный зуб");
            calamity.GetProjectile("ScavengerLaser").DisplayName.AddTranslation(GameCulture.Russian, "Преследующий дротик");
            calamity.GetProjectile("ScavengerNuke").DisplayName.AddTranslation(GameCulture.Russian, "Преследующая ядерная ракета");
            calamity.GetProjectile("ShadeNimbusHostile").DisplayName.AddTranslation(GameCulture.Russian, "Теневая туча");
            calamity.GetProjectile("ShaderainHostile").DisplayName.AddTranslation(GameCulture.Russian, "Проклятый дождь");
            calamity.GetProjectile("ShadowflameFireball").DisplayName.AddTranslation(GameCulture.Russian, "Шар теневого пламени");
            calamity.GetProjectile("Shadowflamethrower").DisplayName.AddTranslation(GameCulture.Russian, "Дыхание теневого пламени");
            calamity.GetProjectile("SignusScythe").DisplayName.AddTranslation(GameCulture.Russian, "Коса");
            calamity.GetProjectile("SirenSong").DisplayName.AddTranslation(GameCulture.Russian, "Нота");
            calamity.GetProjectile("SkyFlare").DisplayName.AddTranslation(GameCulture.Russian, "Небесная вспышка");
            calamity.GetProjectile("SkyFlareRevenge").DisplayName.AddTranslation(GameCulture.Russian, "Небесная вспышка");
            calamity.GetProjectile("SporeGasPlantera").DisplayName.AddTranslation(GameCulture.Russian, "Газ со спорами");
            calamity.GetProjectile("VileClot").DisplayName.AddTranslation(GameCulture.Russian, "Мерзкий сгусток");
            calamity.GetProjectile("WaterSpear").DisplayName.AddTranslation(GameCulture.Russian, "Водяное копьё");
            calamity.GetProjectile("YharonFireball").DisplayName.AddTranslation(GameCulture.Russian, "Шар драконьего огня");
            calamity.GetProjectile("YharonFireball2").DisplayName.AddTranslation(GameCulture.Russian, "Шар драконьего огня");
            calamity.GetProjectile("AcidDrop").DisplayName.AddTranslation(GameCulture.Russian, "Кислота");
            calamity.GetProjectile("BrimstoneGeyser").DisplayName.AddTranslation(GameCulture.Russian, "Дым");
            calamity.GetProjectile("GeyserTelegraph").DisplayName.AddTranslation(GameCulture.Russian, "Гейзер");
            calamity.GetProjectile("HotSteam").DisplayName.AddTranslation(GameCulture.Russian, "Пар");
            calamity.GetProjectile("LavaChunk").DisplayName.AddTranslation(GameCulture.Russian, "Лавовый кусок");
            calamity.GetProjectile("LightningMark").DisplayName.AddTranslation(GameCulture.Russian, "Отметка молнии");
            calamity.GetProjectile("SmokeTelegraph").DisplayName.AddTranslation(GameCulture.Russian, "Дым");
        }
    }
}